### ISSUE TITLE
Install packages on install or detect existing packages

### ISSUE THREAD

**Issue by twsI** [hacs/integration#1002]
**Is your feature request related to a problem? Please describe.**
I configure my HA with yaml, so I can put it on git and track changes. Therefore I obviously use the legacy way to add hacs as long as it is not removed. But I have to install hacs packages by hand. Even if I include the downloaded components folder, hacs won't automatically detect, that I already have components kinda installed.

**Describe the solution you'd like**
I'd love a way to configure hacs to download packages upon installation or validate already existing packages.

**Describe alternatives you've considered**
The only alternative would be to manually intall them via the UI.

**Comment by ludeeus** [comment]
From the UI is the way, and why is explained here https://hacs.xyz/docs/basic/existing_elements

**Comment by twsI** [comment]
That explains, why hacs won't scan for existing files. But the option, to add a bunch of plugins to the yaml file, which are automatically installed upon start is still valid
