### ISSUE TITLE
Uninstalling themes does not delete them

### ISSUE THREAD

**Issue by Santobert** [hacs/integration#1009]
## Version of HACS
0.23.2

## Describe the bug

The themes remain in the `themes` directory after they have been uninstalled via hacs.

1. Install a theme via hacs
2. Remove the theme via hacs
3. Take a look at the  `themes/` directory

## Debug log

```text
2020-03-17 14:02:28 INFO (MainThread) [hacs.repository.theme.naofireblade.clear-theme-dark] Uninstalling
```

**Comment by Santobert** [comment]
I did some research. This only happens when the `.gitignore` file excludes themes. I use git to backup my configuration. Since themes came through hacs, I don't need to include them in my backup, so I added the `themes/` directory to `.gitignore`. This seems to prevent hacs from deleting uninstalled themes.

**Comment by ludeeus** [comment]
That sounds strange.
I think it's something I forgot to change when I updated the handling of theme files.
If you reinstall it, then remove it again it should be gone.

**Comment by Santobert** [comment]
@ludeeus Thanks for your answer. I'm also fine with deleting them manually. I just wanted to report this error.

Some additional information: Even if `themes/` is not excluded via `.gitignore` the empty folders remain there. The theme files are removed if `themes/` is not excluded.

**Comment by ludeeus** [comment]
HACS does not care about your .gitignore file.

**Comment by Santobert** [comment]
Well, you are right. I cannot reproduce the behavior now :unamused: All theme files (not the directories) are deleted as expected. Thats strange indeed.

Close this issue if you wish. Sorry to disturb you.

**Comment by ludeeus** [comment]
It's still an issue for themes installed before i changed the logic.
If you upgrade/reinstall the theme it's not an issue, but if you don't there is no added logic to handle it.
