### ISSUE TITLE
Home Assistant not coming up when integrated with HACS

### ISSUE THREAD

**Issue by sudeshacharya** [hacs/integration#1010]
**Version** 
HACS: 0.23.2
Home Assistant: 0.103.3
m/c: Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3",

**Description:**
After integrating, home assistant pods fails with readynessProbe/liveProb failure. However if HACS integration is removed then the home assistant works fine

How Integration of HACS is done
1) The directory structure looks  as follows . custom_components exist under same location where configuration.yaml is located. The permission of 0755 is provided.

├── custom_components
│   └── hacs
│       ├── config_flow.py
│       ├── configuration_schema.py
│       ├── const.py
│       ├── constrains.py
│       ├── globals.py
│       ├── hacsbase
│       │   ├── backup.py
│       │   ├── configuration.py
│       │   ├── const.py
│       │   ├── data.py
│       │   ├── exceptions.py
│       │   ├── __init__.py
│       │   └── task_factory.py
│       ├── handler
│       │   ├── download.py
│       │   ├── __init__.py
│       │   └── template.py
│       ├── helpers
│       │   ├── download.py
│       │   ├── filters.py
│       │   ├── get_defaults.py
│       │   ├── information.py
│       │   ├── install.py
│       │   ├── misc.py
│       │   ├── network.py
│       │   ├── register_repository.py
│       │   └── validate_repository.py
│       ├── http.py
│       ├── iconset.js
│       ├── __init__.py
│       ├── manifest.json
│       ├── repositories
│       │   ├── appdaemon.py
│       │   ├── __init__.py
│       │   ├── integration.py
│       │   ├── manifest.py
│       │   ├── netdaemon.py
│       │   ├── plugin.py
│       │   ├── python_script.py
│       │   ├── removed.py
│       │   ├── repositorydata.py
│       │   ├── repository.py
│       │   └── theme.py
│       ├── sensor.py
│       ├── services.yaml
│       ├── setup.py
│       ├── store.py
│       └── ws_api_handlers.py

The content under .storage
 ls -ltr .storage/
total 44
-rw------- 1 root root  295 Mar 16 14:27 auth_provider.homeassistant
-rw-r--r-- 1 root root  320 Mar 16 14:27 person
-rw-r--r-- 1 root root  469 Mar 16 14:27 core.area_registry
-rw------- 1 root root  259 Mar 16 14:28 core.config
-rw------- 1 root root  167 Mar 16 14:29 onboarding
-rw-r--r-- 1 root root 1309 Mar 16 14:50 core.config_entries
-rw-r--r-- 1 root root 1472 Mar 16 14:51 core.entity_registry
-rw-r--r-- 1 root root  850 Mar 17 09:55 core.device_registry
-rw------- 1 root root 2908 Mar 17 10:26 auth
-rw-r--r-- 1 root root  923 Mar 17 10:32 core.restore_state
-rw-r--r-- 1 root root  295 Mar 17 10:32 hacs.critical

Home Assistant Logs:
2020-03-17 16:33:12 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-03-17 16:33:13 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=160 from 2020-03-17 16:30:52.878333)
2020-03-17 16:33:26 WARNING (MainThread) [homeassistant.setup] Setup of default_config is taking over 10 seconds.
~

Home Assistant failure message:
Readiness probe failed: Get https://10.32.0.7:8123/: dial tcp 10.32.0.7:8123: connect: connection refused
Liveness probe failed: Get https://10.32.0.7:8123/: dial tcp 10.32.0.7:8123: connect: connection refused

Uninstall of HACS:
Removed the directory hacs under custom_components
removed files starting with hacs under .storage
restarted home assistant.
Able to access home -assistant

**Comment by ludeeus** [comment]
HACS has not started.
You most likely have issues with requirements installation.
And you are missing the .translations dir.
Since this fails before HACS starts, there is nothing I can do in HACS for your issue.

**Comment by sudeshacharya** [comment]
Ensured to see .translations directory exist. Here is the content with hidden filed.
```
.   config_flow.py           const.py       globals.py  handler  http.py     __init__.py    __pycache__   sensor.py      setup.py  .translations
..  configuration_schema.py  constrains.py  hacsbase    helpers  iconset.js  manifest.json  repositories  services.yaml  store.py  ws_api_handlers.py
```

**Comment by ludeeus** [comment]
Several things have been done to the images for Home Assistant in 107, upgrade to that and try again.
