### ISSUE TITLE
Keep custom files/configs in the install directory for AppDaemon integrations

### ISSUE THREAD

**Issue by kylerw** [hacs/integration#1011]
**Is your feature request related to a problem? Please describe.**

Sort of. I separate AppDaemon configs into the folder of the respective app for maintainability. Today when the app is upgraded from HACS the whole folder is overwritten and thus my config is lost.

**Describe the solution you'd like**

I'd like custom files, configs, folders, etc in the install directory to be left intact upon upgrade.

**Describe alternatives you've considered**

The standard method of config management is within a single apps.yaml but can become difficult to maintain with many apps.

**Additional context**

N/A

**Comment by ludeeus** [comment]
@apop880 Since you initially requested AD support, what do you think of this?
It is certainly possible to implement, HACS does the same for Netdaemon apps.

**Comment by apop880** [comment]
@ludeeus Yeah, I think that makes perfect sense. No need to overwrite anything except the .py file itself.

**Comment by sylvaindd** [comment]
I think I am facing a similar problem.
I'm running HA and AppDaemon with docker, I mounted the /config/appdaemon from HA (which is used by HACS) to the same host folder as AppDaemon.
Unfortunately HACS overwrite this everytimes.

**Comment by ludeeus** [comment]
Open an issue with logs @sylvaindd

**Comment by ludeeus** [comment]
If I implement this, will it have any drawbacks for the user/dev?
Is it a scenario where a dev uses a yaml file in the app dir?
And updates that with the app itself?

**Comment by kylerw** [comment]
should be no drawbacks.

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
