### ISSUE TITLE
Unable to uninstall plugin - Compact Custom Header from HACS

### ISSUE THREAD

**Issue by silviudc** [hacs/integration#1015]
## Version of HACS

0.107.0

## Describe the bug
![image](https://user-images.githubusercontent.com/17740184/77146331-b8fb6f80-6a82-11ea-833e-b27bc12f58fb.png)

When I click uninstall it spins indefinitely and never removes the plugin. Can it be removed manually somehow?

## Debug log

<details>
  <summary>Logs</summary>

```text
Logger: hacs
Source: custom_components/hacs/http.py:76
First occurred: 8:06:50 AM (2 occurrences)
Last logged: 8:06:50 AM

Tried to serve up '/config/www/community/compact-custom-header/null' but it does not exist Are you sure you want to uninstall "Compact Custom Header"?
No  Yes  
Connection lost. Reconnecting…

```

</details>

**Comment by ludeeus** [comment]
`Tried to serve up '/config/www/community/compact-custom-header` that means that you still have it in your resources somewhere.

As for uninstalling, try a reinstall first.

**Comment by silviudc** [comment]
Sorted it out, after doing a search for it in all the HACS files and deleting all references.

**Comment by Schocker360** [comment]
> Sorted it out, after doing a search for it in all the HACS files and deleting all references.

@silviudc I have tried to remove the files manually but HACS is still finding the plugin.  Do you recall where you had to delete the references?
