### ISSUE TITLE
[Feature] New category for (templated) packages

### ISSUE THREAD

**Issue by hsolberg** [hacs/integration#1026]
**Is your feature request related to a problem? Please describe.**
There's many good HomeAssistant packages ([doc](https://www.home-assistant.io/docs/configuration/packages/)) that solves usecases like the battery-notifications pack [here](https://github.com/notoriousbdg/Home-AssistantConfig/blob/master/packages/battery_alert.yaml). It's using templates and discovery to do the heavy lifting, so the user won't need to add entities manually. The downside is that you'll have to check for updates manually.

**Describe the solution you'd like**
"If we build it they will come."

I believe if HACS adds a new category for packages there will be an incentive to adjust existing packages to support HACS and use templating to make it easier.

I believe the community would benefit from this in the long run.

**Describe alternatives you've considered**
The alternative is to manually check for updates. For packages that does not use templating yet it's a hassle to update them. Having to manually edit entityids for each file. I believe if HACS has a category for packages there's a greater chance that the community choose to use templating to get their project into HACS.

[Here's](https://github.com/mcfrojd/hassio_lovelace_multiremote/tree/master/packages) a good example of a project that's very good, but does not use templating to the same extent as the battery-notifications package mentioned earlier.

**Comment by ludeeus** [comment]
How should this be implemented?
What should be the rules for the repositories?
Who will manage a standalone repository for a `package`?
Are there any example repositories?

**Comment by hsolberg** [comment]
Hi! I totally forgot about this, sorry about that! I've added some suggestions below for each question. I don't have the complete solution for how to achieve this, but tried to come up with some ideas. Hopefully someone else might have a better suggestion on how to solve this.

> 1. How should this be implemented?

Like normal packages, but they should be easy to add without having to manually maintain entity-names as that would break the possibilities of getting updates/changes from the repo.

> 2. What should be the rules for the repositories?

The main idea was to only allow packages that does not require the user to alter their config in any way. The only exception would be to add one line in their configuration.yaml to pick up (ideally) all files in the packages-folder (needing no further changes for each new package that's added to the category). So the only entry in your config-file should be something like this:
```
homeassistant:
  packages: !include_dir_named packages # Here goes your existing packages (non HACS).
  packages community_dictionary_packages: !include_dir_named dictionary_packages/community # For dictionary-structure.
  packages community_list_packages: !!include_dir_list list_packages/community # For packages with several list-structure.
```

Suggested folder-structure:
`/config/dictionary_packages/community/_INSERT_REPONAME_HERE_/package-files_here.yaml`

I'm not sure what the preferred way of storing packages are in the community, but should be possible support to all methods if needed.

> 3. Who will manage a standalone repository for a `package`?

The creator of the the repository and contributors. I'm not sure I understood this question, but my answer to the next question might be what you meant?

> 4. Are there any example repositories?

Yes, this one, but unfortunately it's not in it's own dedicated [repo]( https://github.com/notoriousbdg/Home-AssistantConfig/blob/master/packages/battery_alert.yaml). 
It might not be ideal to force it to be in a dedicated repo though, you could reuse the discovery-function that's used by HACS to find new repos combined with checking for the correct folder-structure. The example package I mention does not require anything else than adding the line `packages: !include_dir_named packages` mentioned in 2. to my configuration.yaml-file.

**Comment by hsolberg** [comment]
I think the gist of what I wish for might be solved by using substitutions ([example from ESPHome](https://gist.github.com/hsolberg/4203c2b4f0a005940ade4470192bd62f)) or global variables ([link](https://community.home-assistant.io/t/wth-no-global-entity-variables-in-template-sensors/226648), [link2](https://community.home-assistant.io/t/why-the-heck-dont-we-have-global-variables/219671)). If packages used substitutions/variables that you could map to entity_id's in your own configuration that would make it easier to reuse others configuration without having to search and replace manually. [Here's](https://github.com/mcfrojd/hassio_lovelace_multiremote/tree/master/packages) a good example that would benefit from that.

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
