### ISSUE TITLE
Dual Gauge plugin ot working anymore

### ISSUE THREAD

**Issue by dede34fr** [hacs/integration#1027]
## Version of HACS: last
Integration version: | 0.23.2
Frontend version: | 20200309184730

## Describe the bug
Dual Gauge 0.51 not working anymore since HA V106. Worked before. No change done on my lovelace code. 
Would like to know the plugin's future status (removed or replaced?).
Would like an alternative.

## Debug log
`Cannot assign to read only property 'min' of object '#<Object>'`

## Lovelace code (unchanged)
`        - type: custom:dual-gauge-card
          title: "Conso électrique kWh"
          cardwidth: 480
          background_color:
          shadeInner: true
          max: 12000
          min: 0
          inner:
            entity: sensor.conso_elec_prec
            attribute:
            label: "An-1"
            unit: ""
            colors:
            - color: var(--label-badge-blue)
              value: 0
          outer:
            entity: sensor.conso_elec_annuelle
            attribute:
            label: An
            unit: ""
            colors:
            - color: var(--label-badge-red)
              value: 10000
            - color: var(--label-badge-yellow)
              value: 8000
            - color: var(--label-badge-green)
              value: 0`

**Comment by ludeeus** [comment]
You need to as the developer of that plug-in.
