### ISSUE TITLE
Can't install or remove

### ISSUE THREAD

**Issue by JohnnyPicnic** [hacs/integration#1030]
I'm stuck in limbo with HACS not being fully installed and unable to uninstall.
HACS  0.23.2
Error in the logs is: 
```
Setup failed for hacs: Unable to import component: No module named 'custom_components.hacs.helpers'
Connection lost. Reconnecting…

```

I have tried removing via the delete button in integrations. Deleting hacs files in .storage and removing the hacs folder.
I've tried reinstalling by adding the folder but HACS no longer shows up in the integration list.

**Comment by olivvv59** [comment]
same problem since update 0.7.1.7
I've lost everything.

try to push my last snapshot in 0.7.1.4 : doesn't resolve my problem

**Comment by ludeeus** [comment]
@JohnnyPicnic just do exactly as the docs say:
- Remove <https://hacs.xyz/docs/installation/remove>
- Install <https://hacs.xyz/docs/installation/prerequisites>

0.7.1.7 has never existed.

**Comment by olivvv59** [comment]
![Screenshot_20200331-161419_Chrome](https://user-images.githubusercontent.com/10774296/78036659-dc6bc780-736a-11ea-94bb-915e73471342.jpg)

trash icon doesn t make anything

**Comment by ludeeus** [comment]
@olivvv59 That is for supervisor (previously known as hassio), not HACS.
I think you are in the wrong place mate.

**Comment by olivvv59** [comment]
don't know if it is the good place

hacs doesn t work anymore after ha update 🙃

maybe this is an ha's problem and not a hacs problem .

I don't know the both to tell you 😊

**Comment by JohnnyPicnic** [comment]
@ludeeus 

I have tried all methods listed. I didn't use the legacy install method so there is no line in my config and the delete button has no effect.

**Comment by w1tw0lf** [comment]
Have the same issue, follow the steps and no luck so far in fixing it.

**Comment by ludeeus** [comment]
The integration needs to have all its files for the UI delete to work, that is why deleting the HACS dir is the last step of removal.

**Comment by JohnnyPicnic** [comment]
I was able to solve my issue be deleting some of the other files in .storage, not just the ones that had hacs in the filename.
