### ISSUE TITLE
ERROR (MainThread) [hacs] Tried to serve up '/config/www/community/calendar-card/calendar-card.js.map' but it does not exist

### ISSUE THREAD

**Issue by pergolafabio** [hacs/integration#1032]
## Describe the bug
I am usng the calendar-card, all is working fine, the card shows up, but whenver i do a refresh in chrome, i always have the logbook filled up like error below... i tried uninstalling the card, folder was removed, error still shows up ... even when i remove ir from the resources...
what is causing this?

## Debug log

```text
2020-03-31 20:32:11 ERROR (MainThread) [hacs] Tried to serve up '/config/www/community/calendar-card/calendar-card.js.map' but it does not exist
```

**Comment by ludeeus** [comment]
A client (browser) still has a reference in the cache.

**Comment by pergolafabio** [comment]
i did a clear cache, als in incognito it still happens?
