### ISSUE TITLE
Onboarding process of HACS is back after every restart of HA

### ISSUE THREAD

**Issue by PerVildstrand** [hacs/integration#1033]
## Version of HACS

Integration version: | 0.23.2
Frontend version: | 20200309184730
Repositories: | 470

## Describe the bug
![image](https://user-images.githubusercontent.com/19605243/78132920-d84cb200-741d-11ea-9ef4-d08cfcdd1cb2.png)

Since the last (or maybe the last before that) update of HACS and HA (i normally update to new versions of HA when they arrive, the onboarding screens of HACS keep appearing after every restart of HA (whether it is a complete restart of my RPi or just HA).

I run the latest version of HassOS and Supervisor (as well as HA 0.107.7), as screenshot below:
![image](https://user-images.githubusercontent.com/19605243/78133014-0500c980-741e-11ea-8c69-a6c226d76ea5.png)

## Debug log

<details>
  <summary>Logs</summary>
```

</details>

**Comment by ludeeus** [comment]
`2020-04-01 13:19:58 DEBUG (MainThread) [hacs.data] Saving data`
That one should store the state, how are you running HA (core/HAOS/supervised)?
Can you upload all the files under `.storage` that has `hacs` in the name?

**Comment by PerVildstrand** [comment]
[HACS.storage files.zip](https://github.com/hacs/integration/files/4414855/HACS.storage.files.zip)

**Comment by PerVildstrand** [comment]
Note that after this restart I have not walked through the onboarding yet.

**Comment by PerVildstrand** [comment]
I guess that this parameter:

{
    "data": {
        "compact": false,
        "onboarding_done": **false**,
        "view": "Grid"
    },
    "key": "hacs.hacs",
    "version": "6"
}

Should change to **true** when done. I Guess it did´nt before.

**Comment by ludeeus** [comment]
All the files looks correct, and it can write to them.
Can you do the onboarding now with debug active, and upload browser console logs + HA logs when you are done?

**Comment by PerVildstrand** [comment]
ludeeus, I completed the onboarding and got the following results:

Extract from HA logs:
2020-04-01 21:39:55 DEBUG (MainThread) [hacs] WS action 'onboarding_done'
2020-04-01 21:39:55 DEBUG (MainThread) [hacs.data] Saving data

New data in hacs.hacs file:
{
    "data": {
        "compact": false,
        "onboarding_done": **true**,
        "view": "Grid"
    },
    "key": "hacs.hacs",
    "version": "6"
}

Unfortunately I did not get any browser console logs, but I guess the above will do. I will try to restart HA again and see if the issue returns.

**Comment by PerVildstrand** [comment]
After a restart of HA the onboarding_done parameter was re-set to false:

hacs.hacs file:
{
    "data": {
        "compact": false,
        "onboarding_done": false,
        "view": "Grid"
    },
    "key": "hacs.hacs",
    "version": "6"
}

Attaching log file: [home-assistant.log](https://github.com/hacs/integration/files/4417389/home-assistant.log)

**Comment by ludeeus** [comment]
You have HACS defined both with YAML, and in the UI, remove the YAML configuration for HACS.

**Comment by PerVildstrand** [comment]
Ok, so just comment my hacs: line with token out in configuration.yaml and restart?

**Comment by ludeeus** [comment]
yes

**Comment by PerVildstrand** [comment]
Ok. HACS menu item gone. Same errors in log:

```
2020-04-01 22:09:58 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/config/custom_components/hacs/__init__.py", line 81, in async_setup_entry
    startup_result = await hacs_startup()
  File "/config/custom_components/hacs/__init__.py", line 143, in hacs_startup
    await setup_frontend()
  File "/config/custom_components/hacs/setup.py", line 103, in setup_frontend
    require_admin=True,
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 190, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel hacs
```
Complete log here:
[home-assistant.log](https://github.com/hacs/integration/files/4417441/home-assistant.log)

**Comment by ludeeus** [comment]
It still loads from YAML:
`2020-04-01 22:09:52 DEBUG (MainThread) [hacs] Configuration type: yaml`
And UI:
`2020-04-01 22:09:58 DEBUG (MainThread) [hacs] Configuration type: flow`

**Comment by PerVildstrand** [comment]
Ok. I was also trying to set up from UI, but i can´t set the token there. Will check yaml file again. Thanks for replying so quickly.

**Comment by PerVildstrand** [comment]
Only found the log entry for hacs, and my mistake, the menu item is not called HACS anymore. Forgot that. Community item is where it should be. Removing the log entry and restarting again.

**Comment by PerVildstrand** [comment]
Somehow this worked. Onbording value still true. However, i commented the debug log entry for hacs, so I can´t verify the logs, will uncomment and confirm.

**Comment by PerVildstrand** [comment]
Yep, only one line for configuration type in the logs:

`2020-04-01 22:09:58 DEBUG (MainThread) [hacs] Configuration type: flow`

Thanks Joakim!

**Comment by ludeeus** [comment]
And I guess now that you only have one, it works as it should?

**Comment by PerVildstrand** [comment]
Correct. It works as it should. Thanks. Did you see my DM?

**Comment by ludeeus** [comment]
The email?
if so yes, I was in bed when I got that, but I _think_ this would do:
![image](https://user-images.githubusercontent.com/15093472/78217701-d980ec00-74bc-11ea-80cc-59e917d2c5c1.png)

The files are still on github servers somewhere (probably), but that is out of my controll

**Comment by PerVildstrand** [comment]
Well, unfortunately I don´t think so. If I already have the link, the file is still accessible, at least yesterday evening after you deleted the comments. I saw an old issue on github that attachments remained even if the comment was deleted. Didn´t find a solution.

**Comment by ludeeus** [comment]
Only github staff can do anything then I guess, try reaching out to them

**Comment by PerVildstrand** [comment]
Are you in control of the Discord server as well?

**Comment by PerVildstrand** [comment]
Yes, I have a support ticket, but no progress yet.

**Comment by PerVildstrand** [comment]
Update on the support ticket, they have deleted the files. Puh :-) I´m satisfied, if you want to close the issue it´s fine with me @ludeeus .
