### ISSUE TITLE
Hass 0.108 (now beta) logo brand missing

### ISSUE THREAD

**Issue by sagitt** [hacs/integration#1041]
Missing brands for this integration.

https://rc.home-assistant.io/blog/2020/03/27/release-108/

Integration logos & icons
We have created a new repository on GitHub containing all the brand icons and logos Home Assistant is able to integrate with. These images are, for example, used in our documentation.

In 0.108, we made a start on using the content from this repository in the Home Assistant frontend. The device information page got a layout update and the integrations page as well.

These pages will now show the icons and logos matching the integration.

**Comment by Misiu** [comment]
@ludeeus HACS is so well known that I think it should be added there.
I'll create a topic and ask for that.
Hopefully, core developers will agree.

**Comment by ludeeus** [comment]
@Misiu I do not agree custom integrations do not belong on that page, no matter how well known they might be, there are other ways to solve that than to allow custom integrations on that page.

**Comment by Misiu** [comment]
@ludeeus I'm listening :)
I'd like to add brands images for HACS and Shelly.
This won't make anything work better, but it will look better.
For security reasons, images won't be server from custom URL's and it should stay like this.

**Comment by sagitt** [comment]
new 0.110

![Schermata 2020-05-16 alle 17 37 31](https://user-images.githubusercontent.com/169086/82123868-fbe47580-979b-11ea-8406-0f518a01dee5.png)
