### ISSUE TITLE
Can't remove a Plugin flagged as 'Repository is in the blacklist'

### ISSUE THREAD

**Issue by genem2** [hacs/integration#1052]
HA 0.108.0
HACS version 0.23.2

After updating to Home Assistant 1.108.0, the Store is displaying An error occurred while processing
Repository is in the blacklist.

I wasn't using that any longer so just tried to uninstall it.
General symptom: 
In the store, click on the offending plugin:

![fig1](https://user-images.githubusercontent.com/46231389/78832800-ba90c700-79a0-11ea-8a47-54121c386dcb.png)

That larger spinning circle never stops.
Click on Uninstall.
The Uninstall text changes to a green spinning wait indicator and never stops.
![Fig2](https://user-images.githubusercontent.com/46231389/78832896-e318c100-79a0-11ea-89b2-70af1d3b0964.png)

For better or worse, I:

- Went into the Home Assistant Configuration | Lovelace Dashboards | Resources and removed the entry from there. 
- I verified 'dual-gauge-card' was not called for in any file in my HA directory tree.
- I deleted the folder from the community folder.
- Restarted HA.

That wasn't enough to fool HACS, so I performed a Reload Data. 
Nothing's helping... HACS store reflects it's still installed.
![Fig3](https://user-images.githubusercontent.com/46231389/78833310-81a52200-79a1-11ea-96af-8181b366815e.png)

Any suggestions?

## Debug log

[log.txt](https://github.com/hacs/integration/files/4452791/log.txt)

**Comment by ludeeus** [comment]
It has been fixed, but not yet released, update HACS when a new version comes.
Then uninstall it.
