### ISSUE TITLE
hacs tries to load up non-existant file

### ISSUE THREAD

**Issue by fribse** [hacs/integration#1055]
## Version of HACS

HACS:  0.23.2
HA: 0.108.2

## Describe the bug
While debugging other stuff, I saw in the logfile that it tries to load up a non-existing file.
The light-entity-card is loaded from it's correct location, so it seems to some old stuff, but I can't find the 'ressources' any longer in the text based lovelace editor, and I have no idea where to look otherwise, so I can clean it out.

## Debug log

<details>
  <summary>Logs</summary>

```text
2020-04-10 18:39:40 ERROR (MainThread) [hacs] Tried to serve up '/config/www/community/light-entity-card/dist/light-entity-card.js' but it does not exist
```

</details>

**Comment by ludeeus** [comment]
`:8123/config/lovelace/resources` but that is not really related to HACS.

**Comment by fribse** [comment]
But the logfile says:
`2020-04-11 23:36:53 ERROR (MainThread) [hacs] Tried to serve up '/config/www/community/light-entity-card/dist/light-entity-card.js' but it does not exist`
So I thought it was resources I had to find?
