### ISSUE TITLE
HACS does not working from few days.

### ISSUE THREAD

**Issue by arecdudek** [hacs/integration#1056]
Hi,
I did not update HA or HACS and I can not access to HACS tab. Also i did reset & wipe to my backup and also HACS did not work. I have an error: hacs "This entity is currently unavailable".

Also why this repo is not exist anymore: https://custom-components.github.io/hacs/?

**Comment by ludeeus** [comment]
The template is there for a reason, next time you open an issue, fill it out.

> Also why this repo is not exist anymore: https://custom-components.github.io/hacs/?

That is not a repo, it's a website, it was moved. https://hacs.xyz/
