### ISSUE TITLE
Make addon package for hassio

### ISSUE THREAD

**Issue by iBobik** [hacs/integration#1057]
**Is your feature request related to a problem? Please describe.**
Current installation and configuration procedure is not intuitive, especially for people used to use Hass.io's addons store.

**Describe the solution you'd like**
Prepare addon what will be available in Hassio's store, so it could be installed easilly in a few clicks.

**Describe alternatives you've considered**
Install script what user could just copy&paste? No, because not everybody has working SSH to their installation and the methods could be diferent (webterminal addon, daemon running in addon's container or on host, different file sharing addons, …) and not everybody knows concept of public key for SSH (and it could be hard to instruct them to secure it properly).

Install guide by using some other addon (in official docs, for hassio user)? May work, but still requires some labour and maintanance of this guide.

**Additional context**
My consideration about target groups:

Users who can use SSH and understand architecture of Hass.io (Docker containers) can easilly install HACS. But they also can easilly install all packages offered by it, so does not necessarily needs HACS.

Users who are not nerds can not install HACS easilly but would benefit from it's seamless packages installation.

**Comment by ludeeus** [comment]
This will not happen, an addon for the installation of something is not what add-ons should be used for.

Addons are for services that should run continuously. Installation is a one-off.
If you find it hard to install with any of the two install options, you should not use _any_ custom enhancements in your system.

**Comment by iBobik** [comment]
This is technical constrain or your opinion how it should not be used?

**Comment by ludeeus** [comment]
Mine (and that opinions are shared with add-on devs)
