### ISSUE TITLE
Hacs tries to load non-existant file

### ISSUE THREAD

**Issue by fribse** [hacs/integration#1058]
## Version of HACS

HA: 0.108.3
HACS: 0.23.2

## Describe the bug
I get an error in the logfile, that hacs tries to load a non-existant file
I reported the previously, and the answer was it wasn't something to do with hacs, but given the logfile I must disagree.
At some point of installations, the file must have been in a subfolder called dist, but it isn't any longer, it's directly in light-entity-card, and hacs loads it from there.
An uninstall / reinstall does not change the error.

## Debug log

<details>
  <summary>Logs</summary>
```text
2020-04-11 23:36:53 ERROR (MainThread) [hacs] Tried to serve up '/config/www/community/light-entity-card/dist/light-entity-card.js' but it does not exist
```

</details>

**Comment by ludeeus** [comment]
You can disagree how much you want, it will still not change the reality :)
It is not HACS that is trying this, it is _something_ trying to access that file using HACS endpoint.
This can be:
- Cache
- Current lovelace resources 

You are using one or both of these _somewhere_:
- `/hacsfiles/light-entity-card/dist/light-entity-card.js`
- `/community_plugin/light-entity-card/dist/light-entity-card.js`
