### ISSUE TITLE
Removal required deleting other .storage files

### ISSUE THREAD

**Issue by JohnnyPicnic** [hacs/integration#1063]
I was able to resolve my issue of not being able to re install or remove HACS by deleting not only the files in .storage that had HACS in the filename but all the files that referenced HACS in their content. Maybe that's what the instructions elude to but it wasn't that clear to me.

**Comment by ludeeus** [comment]
You are thinking of `.storage/config.entries`, that is what the "trashcan" icon does, and also why 2 restarts are needed.
