### ISSUE TITLE
open integration page in new tab

### ISSUE THREAD

**Issue by centralhardware** [hacs/integration#1064]
***problem***

after exiting the integration page, the scrolling is reset, which is why it is not convenient to look at the integration of interest to you, because you have to look for the place where you stopped each time

**Describe the solution you'd like**

enable the button or middle mouse button to go to the integration page in a new tab

**Comment by ludeeus** [comment]
That only works with links.
Items in HACS (and in HA for that matter) are opened by using events.
So this will not work.
