### ISSUE TITLE
Options are invisible / no Sidepanel

### ISSUE THREAD

**Issue by Mikei386** [hacs/integration#1066]
Hi there,

I followed your tutorial but all the texts on the integration page are invisible.
I can see the xxxxxxx's, the lines for textfields and the checkboxes but no text.
Also when finished there is no side panel.

I tried it multiple time...
On an old HomeAssistant instance where I'm using the old yaml method, everything works.

![Bildschirmfoto 2020-04-15 um 11 31 49](https://user-images.githubusercontent.com/44135113/79322665-6c824300-7f0d-11ea-9364-ea1980465e06.png)

**Comment by ludeeus** [comment]
You are missing the `.translations` dir.

**Comment by Mikei386** [comment]
oh I saw it in the windows explorer but it didn't get copied.
sorry for the inconvenience.
