### ISSUE TITLE
Cannot reboot via Server Management, error: Configuration invalid

### ISSUE THREAD

**Issue by terenceng81** [hacs/integration#1069]
## Version of HACS
HACS (Home Assistant Community Store)
Manage (Install, track, upgrade) and discover custom elements for Home Assistant.
Authors:ludeeus
GitHub stars: 896
Downloads: 8266
Last updated: one day ago
Frontend version: 20200413144153
Installed: 0.24.0

## Describe the bug
Hi, I have installed the HACS without issue, I can see HASC in my left panel of HA. I have also configured the token in the Configuration. My issue is that I am not able to reboot HA via Configuration > Server Controls > Server Management > Restart, 

I run the Validation, Configuration > Server Controls > Configuration validation > CHECK CONFIGURATION and received the error below:
Configuration invalid
Package services setup failed. Component install Integration 'install' not found.
Package services setup failed. Component register Integration 'register' not found.

I have to reboot via the ssh console by running command "host reboot" and every time after reboot, the wizard below have to redo again and again like the installation never successful. 

==============================
Welcome to HACS!👋
Congratulations, you have successfully installed HACS! 🎉
This onboarding process will hopefully help you to understand what HACS is and what it does.

To start off here are a few useful links:

HACS Documentation
HACS @ GitHub
HACS @ Discord

NB!: You will only see this onboarding once, so take your time to read it all.

=-=============================

How do i get rib of this? You help is much apprecaited.

## Debug log

<details>
  <summary>Logs</summary>

```text
Log Details (ERROR)
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:269
Integration: Hass.io (documentation, issues)
First occurred: 2:53:06 PM (1 occurrences)
Last logged: 2:53:06 PM

Package services setup failed. Component install Integration 'install' not found. Package services setup failed. Component register Integration 'register' not found.

```

</details>

**Comment by ludeeus** [comment]
Your restart issues are not related to HACS (you have a config issue in one of your packages).
If you see the wizard on every startup, you have HACS configured with UI and YAML, remove the YAML config.

**Comment by terenceng81** [comment]
> Your restart issues are not related to HACS (you have a config issue in one of your packages).
> If you see the wizard on every startup, you have HACS configured with UI and YAML, remove the YAML config.

I have only 1 configuration for HACS configured in the configuration.yaml, is this the one that i have to remove?

```
hacs:
  token: xxxxx
  appdaemon: true
  netdaemon: true
#  python_script: true
  theme: true
  sidepanel_title: HACS
  sidepanel_icon: mdi:store
#  options:
#    experimental: true
```

**Comment by ludeeus** [comment]
Yes

**Comment by terenceng81** [comment]
> Yes

thanks Ludeeus, I am rebooting and will update the outcome here.

**Comment by terenceng81** [comment]
The wizard no longer occur every start up, thanks.

However this error is still occur every time i try restart in the HA UI.
```
Log Details (ERROR)
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:269
Integration: Hass.io (documentation, issues)
First occurred: 3:52:19 PM (1 occurrences)
Last logged: 3:52:19 PM

Package services setup failed. Component install Integration 'install' not found. Package services setup failed. Component register Integration 'register' not found
```

**Comment by ludeeus** [comment]
Like I said:
> Your restart issues are not related to HACS (you have a config issue in one of your packages).

That has nothing to do with HACS, I suggest you ask on the Home Assistant discord server or the Home Assistant forum.

**Comment by terenceng81** [comment]
> Like I said:
> 
> > Your restart issues are not related to HACS (you have a config issue in one of your packages).
> 
> That has nothing to do with HACS, I suggest you ask on the Home Assistant discord server or the Home Assistant forum.

ok thanks
