### ISSUE TITLE
Integration icon

### ISSUE THREAD

**Issue by kyote73** [hacs/integration#1083]
**Is your feature request related to a problem? Please describe.**
Perhaps include a HACS icon in the Integration section of Home Assistant. Hardly a big deal and of course in no way affects the functionality of this awesome HA addon - just pretties things up a bit :)

**Describe the solution you'd like**
Icon for HACS under Integrations.

**Comment by ludeeus** [comment]
That is currently not possible for any custom integration

**Comment by kyote73** [comment]
Oh, that's a shame... I should perhaps post this on HA Github page... sorry.
