### ISSUE TITLE
Losing everything after update from 0.24.1 to 0.24.2 

### ISSUE THREAD

**Issue by adamotte** [hacs/integration#1085]
Just update to 0.24.1 to 0.24.2 after notification received, HA restart, then was back to HACS firsts steps and got all my configurations reset

Maybe due to github issue during the update ?

Help me to retreive my setup. 
Thx

**Comment by adamotte** [comment]
Answer to myself i will try to restore an old backup and try the update again. Keep you in touch.

**Comment by ludeeus** [comment]
The template is missing, an no an update did not do that.

**Comment by singhj0910** [comment]
I have the same exact problem except it happened before I updated HACS. HACS doesn't see any of my installed apps or themes anymore after going through the first steps prompt. The themes and python scripts tabs disappeared as well but a reboot brought those back. Should I reinstall all of my apps and integrations again??

**Comment by ludeeus** [comment]
> happened before I updated HACS. 

That's because it has nothing to do with an update.

> Should I reinstall all of my apps and integrations again??

That or:

> restore an old backup

**Comment by UbhiTS** [comment]
I lost all my hacs installed apps info yesterday too after the update. I dont know if it was HACS update or HASS.IO update, but something messed up :(

**Comment by ludeeus** [comment]
Only a restore will get that back.
