### ISSUE TITLE
Can't update HACS 0.24.4

### ISSUE THREAD

**Issue by EdoZullo** [hacs/integration#1089]
I can't update HACS on my HASS
Getting this error:
![Schermata 2020-04-23 alle 23 52 49](https://user-images.githubusercontent.com/38581202/80153563-102ebb80-85be-11ea-91c9-76fd1e8168de.png)

this is the log on HASS:
`Logger: hacs
Source: deps/lib/python3.8/site-packages/integrationhelper/logger.py:25
First occurred: 0:04:20 (3 occurrences)
Last logged: 23:52:37

Could not use repository with ID 172733314`

**Comment by EdoZullo** [comment]
So sorry, forgot to share log.
[home-assistant.log](https://github.com/hacs/integration/files/4528062/home-assistant.log)

**Comment by ludeeus** [comment]
Do a restart of Home Assistant and try again.

**Comment by EdoZullo** [comment]
i tried to restart but error happened again. Now i update manually, when new release comes up see if happen again.

**Comment by EdoZullo** [comment]
Same error trying to update to 0.24.4

**Comment by ludeeus** [comment]
What version of Home Assistant is this?

**Comment by EdoZullo** [comment]
Latest available right now:
Home Assistant 0.109.6

**Comment by nigelhewitt** [comment]
Can I log a 'me too'?

Every time HACS wants to update itself I just end up with a big red bar saying

An error occurred while processing
Could not use repository with ID 172733314

Or such. So I go and remove HACS. I oh so carefully step through the instructions getting a lovely shiny new git hub token, which of course I don't need then as I have just done a whole new unzipped custom_components/hacs folder. So there I am thinking "this time I am sure I read every word, dotted every i and crossed every t. It must work this time and shortly after it smoothly updates one or more of my integrations and my confidence rises.
However, after a week or so, they push some more changes, HACS wants to update, I click the UPDATE and we're back to the big red bar.

The log just says
2020-05-09 13:11:59 ERROR (MainThread) [hacs] Could not use repository with ID 172733314

I have a git account. I have a lot of C++ stashed there but I'm a poor old retired embedded systems programmer and python reads funny to my senile old brain. Is there some way to determine what I'm doing wrong? It's a nice system running on a Pi3 in simple vend mode that looks after my lights and plugs.

Yes, I have removed all the previous tokens and I checked the token I feed into the install is right.
I did try the yaml configuration option but that was the same.

**Comment by ludeeus** [comment]
Are you both using a venv @nigelhewitt && @EdoZullo ?
Both python 3.8?

**Comment by EdoZullo** [comment]
Yes i do

**Comment by nigelhewitt** [comment]
Yes. Run by the systemd daemon.
HA and the Pi3 all on latest and greatest updates. No other tasks on the Pi3.
This is my only outstanding problem so I am reasonably confident that all is well.

**Comment by ludeeus** [comment]
That is interesting, can you also confirm that you run python 3.8 @nigelhewitt ?
That may be the common thing here.
Both the previously named "hassio" installation and the docker containers both run python 3.7.7
Which can explain why this only happens to a small subset of users.

**Comment by nigelhewitt** [comment]
Python 3.7.3 according to the HA developers page.
Should I update? If so what version would you recommend?

**Comment by ludeeus** [comment]
3.7.7 is the most tested version, but I do not know if that will help, but it's absolutely worth a try.

**Comment by nigelhewitt** [comment]
That was sad. It took a couple of hours to figure my way round all the gotchas it puts in your way but finally I got HA up on 3.7.7 then I did all the updates and checked again.

2020-05-10 15:44:23 ERROR (MainThread) [hacs] Could not use repository with ID 172733314

**Comment by kpmkpm** [comment]
Same error here. Might be python 3.8 oriented. I have 3.8.2 and no luck in updating to the 0.24.4.

**Comment by Coolie1101** [comment]
Just wanted to confirm, upgrading Python from 3.7.3 to 3.7.7 in python venv did not solve the issue.

![image](https://user-images.githubusercontent.com/28989417/81809183-f0205700-94ee-11ea-8817-589df614e961.png)

**Comment by maxfarrior** [comment]
I ran into and fixed this issue by changing the permissions on the `custom_components/hacs` directory. The user running HomeAssistant didn't have permissions to write to the files. A simple `chown` and then I was able to successfully update.

HomeAssistant (Core in venv) 0.109.3
Python 3.7.7 (in venv)
HACS 24.3 (now updated to 0.24.5)

**Comment by Coolie1101** [comment]
@maxfarrior 
Confirmed, thank you.

![image](https://user-images.githubusercontent.com/28989417/81893179-02e06d80-957b-11ea-986b-89d8838f3f84.png)

**Comment by nigelhewitt** [comment]
My owner was the basic pi:pi account as I was unpacking the hacs.zip on the PC and moving it over via samba.
Using sudo chown -R homeassistant .....hacs and then chgrp the same seems to have done it as it just did a reinstall OK.
I shall await the next push of updates with trepidation.
So it was, basically, my unfamiliarity it linux? I rather expected that.

Thanks for your time guys.

**Comment by EdoZullo** [comment]
Unfortunately i can't downgrade to python 3.7.7.
Try to change permission when next release comes up.

**Comment by ludeeus** [comment]
ahhhh.
Yeah... permissions would cause that..
The user running homeassistant, needs full control on everything under the custom_components directory.

**Comment by maxfarrior** [comment]
Glad that helped some people. A couple thoughts:

* I think it's common to have a user account for normal system interaction, and a separate one for running HA.

* I also think that the HACS error message was not particularly helpful.

A few ideas:

1. Have the code that does the downloading/extraction check for correct permissions, and throw a (descriptive) error if they're wrong.

1. Have a generic permission check somewhere in HACS. Maybe this issue could be detected during installation. Or maybe the same code that checks during installation can be called again to check before any downloading/extracting happens.

1. Add a note to the installation directions to make sure the necessary directories are writable by the user running HA.

Just throwing that out there.

**Comment by ludeeus** [comment]
Feel free to open PR's to the code and/or documentation to add those 👍

**Comment by maxfarrior** [comment]
I'll give it a shot. I don't know if I can contribute any code though.

**Comment by ludeeus** [comment]
_anything_ is better than nothing 😃

**Comment by ludeeus** [comment]
protip for you venv folks, use the cli script to install.
https://hacs.xyz/docs/installation/manual_cli

**Comment by EdoZullo** [comment]
Change permission on hacs folder and upgrade to version 1.0.0.  Upgrading works now!

**Comment by hubersimone** [comment]
I have the same problem but i can't change the permissions of the homeassistant folder.
Can some help me?

I installed homeassitnt core on rasbberry but not even through the graphical interface (dekstop) of the raspberry and not even connected via console via ssh I can change the permissions to be able to update the hacs.

**Comment by Mibix** [comment]
> I have the same problem but i can't change the permissions of the homeassistant folder.
> Can someone help me?
> 
> I installed homeassitnt core on rasbberry but not even through the graphical interface (dekstop) of the raspberry and not even connected via console via ssh I can change the permissions to be able to update the hacs.

Are you doing it as root?

**Comment by hubersimone** [comment]
Yes, on the console I can have all the permission 
sorry for the late reply

**Comment by hubersimone** [comment]
How can I do?
