### ISSUE TITLE
Minimum version requirement doesn't take into account beta versions

### ISSUE THREAD

**Issue by SeanPM5** [hacs/integration#1092]
## Version of HACS

Frontend version: 20200422201603
Installed: 0.24.2

## Describe the bug

There was an issue with a certain custom component (Spotcast) that only occurs in Home Assistant 0.109 (currently in beta). The component author resolved this issue and released an update with min requirements of HA 0.109 which is correct.

But HACS is not allowing me to upgrade and get this fix, because the versions don't match exactly cause of "b2" being in the version number.

`You are running Home Assistant version '0.109.0b2', but this repository requires minimum version '0.109.0' to be installed.`

![image](https://i.imgur.com/MD5TcPk.png)

I think this requirement should take into account betas by ignoring the "b2" part of version number. Because I _am_ in fact already running 0.109, just a few days earlier than most.

## Debug log

<details>
  <summary>Logs</summary>

```text
N/A
```

</details>

**Comment by ludeeus** [comment]
I do not agree that this is a bug.
This is working as it should.

The final 0.109.0 version is the first one without a b in the version.
0.109.0 will be newer than 0.109.0b2.

If I just ignore the b part(I did that in the beginning), there will not be possible for the dev to set b1 for instance as the minimum (which has been needed in the past)

**Comment by SeanPM5** [comment]
Thanks for clarifying, hadn't considered that scenario. I agree and will close this now.

**Comment by jes1417** [comment]
If we set the version to a beta version will HACS allow it to be installed on the stable release?
