### ISSUE TITLE
Not able to Install on Lovelace

### ISSUE THREAD

**Issue by BarryLuft** [hacs/integration#1095]
I am very new to Home Assistant so please don't dump on me if I don't know how or where to ask or all the details needed.  I have a Lovelace version installed on an Oracle VM running on Linux Mint (which I am also new to).
I want to install HACS but cannot find the Home Assistant directory containing the config directory. I've watch 15 youtube instructions and another lot of googled instructions but they all say "Unzip HACS into a custom_components folder in the Home Assistant directory containing the config file". Well, I would love to but where do I find that?
They are mostly about a Raspberry pi or something that bears no resemblance to what I am  looking at.
Would someone out there be so kind  to explain what I need to do?

**Comment by BarryLuft** [comment]
Home Assistant 0.108.9 Lovelace is what I am using

**Comment by ludeeus** [comment]
configdir is where configuration.yaml and home-assistant.log is.
This is not a bug, if you need any help with finding this, you should join the discord server.

https://hacs.xyz/help
