### ISSUE TITLE
HACS doesn't know what is installed

### ISSUE THREAD

**Issue by cjramseyer** [hacs/integration#1098]
## Describe the bug
Power failure event cause reboot of Home Assistant + HACS.
Subsequent reboot, HACS see itself as installed but does not know about the other components that were installed using HACS previously.  i.e badnest, Garbage Collection, Alexa Media Player, etc.
These components are functioning, but HACS doesn't show them as being installed.

HA Version: 0.108.6
Hardware: rPi 3 B+

## Debug log

No errors shown in the log

<details>
Our area suffered a power outage late the evening of 4/26.
Power was restored roughly 4am (outage for about 8 hours).
When HA booted up again, HACS did not show anything (including itself) being installed, and did not show any of the HACS modules being installed.
Rebooted HA without making any changes, and HACS showed as being installed, but still did now show what modules were instaled.
Did a second reboot without any configuration changes, and still nothing showing as installed.

```text
Paste your logs here.
```

How can this be resolved?

</details>

**Comment by ludeeus** [comment]
Only way to solve it is by restoring `.storage/hacs.repositories` from a backup.
