### ISSUE TITLE
Unable to uninstall archived repository

### ISSUE THREAD

**Issue by lbouriez** [hacs/integration#1109]
## Version of HACS
![image](https://user-images.githubusercontent.com/4749766/80767742-9b580600-8b16-11ea-8ef3-455a52467872.png)

## Describe the bug
Unable to uninstall a CC that is archived.

## Debug log
![image](https://user-images.githubusercontent.com/4749766/80767777-b460b700-8b16-11ea-9e59-12e250073178.png)
![image](https://user-images.githubusercontent.com/4749766/80767788-bd518880-8b16-11ea-977b-af4d32f3030a.png)

> Log Details (ERROR)
> Logger: hacs.repository.integration.robmarkcole.Hue-remotes-HASS
> Source: custom_components/hacs/repositories/repository.py:431
> First occurred: 7:11:54 PM (2 occurrences)
> Last logged: 7:13:50 PM
> 
> Missing domain

and another log

> Log Details (ERROR)
> Logger: hacs
> Source: custom_components/hacs/ws_api_handlers.py:252
> First occurred: 7:11:52 PM (4 occurrences)
> Last logged: 7:13:50 PM
> 
> Repository is archived.
> Could not uninstall

I tried looking in the .storage folder for any hueremote text, there is nothing. I have no idea of what to do to get rid of it. I am not using it anymore, I also deleted the folder in the CC folder...

**Comment by ludeeus** [comment]
Currently, you can't remove it, I had to do this due to a bug that would wipe the entire `custom_components` dir.

Will fix it in an upcomming version of HACS.

**Comment by lbouriez** [comment]
Thanks :)

**Comment by apozzato73** [comment]
thanks

**Comment by netrene** [comment]
Same problem her. Is there a way of manually deinstalling it? I tried to delete the folder but it still shows up in HACS.

**Comment by ludeeus** [comment]
There is, but that requires messing with files you should not mess with.
The fix for this will be a part of the next HACS version.
ETA for that is planned for late next week.
