### ISSUE TITLE
Promote other components

### ISSUE THREAD

**Issue by peternijssen** [hacs/integration#1110]
**Is your feature request related to a problem? Please describe.**
So I've created an integration and someone else built a plugin based on my integration. What you see is that there is a link between both systems. The plugin has no use without the integration and anyone with the integration could benefit from the plugin.

I understand from #693 that handling dependencies would be a problem though.

**Describe the solution you'd like**
I was thinking that perhaps within the hacs.json file, we could include a new "promote" attribute which allows everyone to send in an array of repositories.

Filled in repositories are then matched against the ones in hacs/default. If the repository doesn't exist, we simply drop it. When it's there, we maybe can include a direct link to that component in HACS. Perhaps that component in HACS could even have a slightly different color to indicate that it might be something interesting for you to review or have a special "interesting components for you" place.

This doesn't require HACS to install dependencies, but allows you to visually connect components together which is controlled by the owner of the component themselves.

**Describe alternatives you've considered**
An alternative is of course to keep it within the info.md file. I am however not sure if people read it after installing the component and it's possible of course new components are introduced that could benefit from each other.

**Additional context**
Hope it all makes sense. Not sure if "promote" is the correct word, but couldn't come up with anything else. Happy to create some screens if you would like to understand better what I mean.

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
