### ISSUE TITLE
Can't reinstall HACS

### ISSUE THREAD

**Issue by TheWidowLicker** [hacs/integration#1113]
## Version of HACS
0.24.3

## Describe the bug
I installed an integration from in HACS. When installing it said there was a custom_components folder and should it recreate it. I clicked yes. When I restarted HA, I got a message saying that hacs configuration wasn't right. I tried to get it going but couldn't. Finally I tried to remove the hacs integration but that wouldn't work. I finally removed it from the files in .storage. On reboot the message was gone so was the integration. So I re-downloaded the latest hacs.zip and extracted it to a hacs folder under custom_components but on reboot it is not showing up integrations. I have tried a number of times and cleared the cache on the browser as well as use other browsers but cannot seem to get the integration to appear.
Permissions and ownership for hacs folder inside custom_components looks ok.

## Debug log

<details>
  <summary>Logs</summary>

```text
Paste your logs here.
```

</details>

**Comment by ludeeus** [comment]
if you still have issues, use the install script <https://hacs.xyz/docs/installation/manual_cli>
