### ISSUE TITLE
adding integration keeps loading forever

### ISSUE THREAD

**Issue by cagnulein** [hacs/integration#1114]
![Immagine](https://user-images.githubusercontent.com/48216/80858648-f1ce5d00-8c5a-11ea-8245-bdd253ed84a5.png)

## Version of HACS

0.24.3

## Describe the bug
I'm installing HACS following the wiki, but when i try to add HACS to integration, the loading page stills forever.

## Debug log

These are the only lines that matters in the debug log:

`2020-05-02 07:48:00 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.139746845239952] Sending {'id': 52, 'type': 'result', 'success': True, 'result': {'resources': {'component.hacs.config.abort.single_instance_allowed': 'Only a single configuration of HACS is allowed.', 'component.hacs.config.error.auth': 'Personal Access Token is not correct.', 'component.hacs.config.step.user.data.appdaemon': 'Enable AppDaemon apps discovery & tracking', 'component.hacs.config.step.user.data.netdaemon': 'Enable NetDaemon apps discovery & tracking', 'component.hacs.config.step.user.data.python_script': 'Enable python_scripts discovery & tracking', 'component.hacs.config.step.user.data.sidepanel_icon': 'Side panel icon', 'component.hacs.config.step.user.data.sidepanel_title': 'Side panel title', 'component.hacs.config.step.user.data.theme': 'Enable Themes discovery & tracking', 'component.hacs.config.step.user.data.token': 'GitHub Personal Access Token', 'component.hacs.config.step.user.description': 'If you need help with the configuration have a look here: https://hacs.xyz/docs/configuration/start/', 'component.hacs.config.step.user.title': 'HACS (Home Assistant Community Store)', 'component.hacs.config.title': 'HACS (Home Assistant Community Store)'}}}`

</details>

**Comment by lucasff** [comment]
I had the same issue in the past but it somehow worked after some attempts. Now I'm having the same issue and it doesn't work.

**Comment by cagnulein** [comment]
@lucasff which version did you have before?

**Comment by cagnulein** [comment]
@ludeeus could you please explain the label? Are you aware of this issue?

**Comment by ludeeus** [comment]
That happens in HA (before HACS is loaded, there is nothing I can do about that in HACS)

**Comment by cagnulein** [comment]
> That happens in HA (before HACS is loaded, there is nothing I can do about that in HACS)

ok but how can we solve it? every users will think that it will be a HACS issue

**Comment by ludeeus** [comment]
Disable adguard, pihole, use ethernet, disable proxy 🤷‍♂️

**Comment by cagnulein** [comment]
> Disable adguard, pihole, use ethernet, disable proxy 🤷‍♂️

disabled pihole, i'm over ethernet and i have no proxy. the issue remains. I'm over 4G and it's my only network, maybe something with NAT or similar?

**Comment by cagnulein** [comment]
is there any way to debug it deeper?

**Comment by cagnulein** [comment]
this morning i've retried changing the language from italian to english: i don't know why but it worked, without disabling pihole or anything else

**Comment by AreaKode** [comment]
I'm also having this issue. HassOS 3.13. Installing HACS for the first time. It just sits on "Please wait while the integration is being installed" when I try to add the integration.

I've successfully uninstalled the component and added it back. Same issue. Multiple reboots in between steps.

**Comment by ajobbins** [comment]
I'm also having this issue trying to install HACS for the first time. Sits on "Please wait while the integration is being installed" for about a minute before going back to the integrations screen.

HACS 0.24.3, HA Core 0.109.4 on Docker

**Comment by iMicknl** [comment]
I am having the same issues on 2 different installs.

HACS 0.24.3
Home Assistant 0.109.4
HassOS

**Comment by Tekno-man** [comment]
I am having the same issue. Fresh install of Hassio on a VM. I previously installed HACS on a previous building using the config.YAML method with no problems. This is my first attempt at installing through integrations page. As described above- Sits on "Please wait while the integration is being installed" for about a minute before going back to the integrations screen. HACS 0.24.3, HA Core 0.109.4. 

EDIT - Rebooted VM/host again and now it installed.

**Comment by war1000** [comment]
I am having this exact same issue. I have rebooted multiple times. Removed the hacs folder and reuploaded, still getting stuck at this screen. Anything else I can try? I am on core. 0.109.2

**Comment by Tekno-man** [comment]
Have you tried rebooting the the host not just HA, ie turn off the computer?

**Comment by oneWaveAdrian** [comment]
Ran into the same problem with classic install. Worked fine using the [CLI method](https://hacs.xyz/docs/installation/manual_cli).

**Comment by rchl** [comment]
Same here when trying to install.

Trying to install HACS triggers `POST /api/config/config_entries/flow` to my HA instance but it time-outs with 504 response eventually.

**Comment by rchl** [comment]
It started working for me.
All I did was restarting machine (raspberry pi) that is running HA and running `apt upgrade`. Not sure what helped.

**Comment by rijn** [comment]
I looked into this issue a little bit and found that `importlib_metadata.version` somehow doesn't work on my ubuntu. Updating the following line

https://github.com/home-assistant/core/blob/dev/homeassistant/util/package.py#L54
```python
return version(req.project_name) in req
```

to
```python
return pkg_resources.get_distribution(req.project_name).version in req
```
works for me.

**Comment by johnf** [comment]
> I looked into this issue a little bit and found that `importlib_metadata.version` somehow doesn't work on my ubuntu.
The same fix works in the docker images

**Comment by Roemer** [comment]
I had the same issue. I could solve it by using the internal ip to connect to Home Assistant and install HACS from there instead from the external access.

**Comment by horrorhound** [comment]
We sure this isn't the issue after HACS installs?

HACS is disabled (Ratelimited)
GitHub API calls are ratelimited, this will clear in less than 1 hour.

After HACS is installed there's a lot of API calls to GitHub to obtain all the repositories.  So I'm thinking our GitHub accounts hits the API call limit and then HACS should start working again after 1 hour?

**Comment by vadipp** [comment]
> We sure this isn't the issue after HACS installs?

This happens before we are asked for GitHub credentials, so this shouldn't be related to rate-limiting.
