### ISSUE TITLE
Handle symbolic links during installation

### ISSUE THREAD

**Issue by nikrolls** [hacs/integration#1115]
**Is your feature request related to a problem? Please describe.**
I have a simple integration and want to avoid managing the same strings in both `strings.json` and `translations/en.json`. I also want to support both folders: `translations` and `.translations`. I'm currently doing this with no issues using symbolic links. However HACS turns these links into plaintext files with paths on installation which breaks Home Assistant's strings system entirely.

This is one use-case for symlinks, but there could be many others and it will be confusing for developers to have their integrations break when they introduce them, possibly quite publicly because you won't realise it's going to break until it's available for HACS to install.

**Describe the solution you'd like**
When checking out a repository with symlinks, maintain those links during installation. Alternatively, follow the symlinks to make sure the content is equivalent to if the files were linked.

**Describe alternatives you've considered**
The alternative for me is to maintain three copies of the same file which is just asking for something to be missed. I could also create a build process that copies these files, but symlinks are a much better way and should be supported. There may also be other valid reasons for developers to use symlinks which will currently break their integration.

**Comment by ludeeus** [comment]
HACS uses githubs API to download files, does that ever support this?
If you use zip release like HACS itself, this may work now

**Comment by nikrolls** [comment]
@ludeeus I'm not exactly sure how HACS is retrieving files, but GitHub's Contents API follows symlinks as expected: https://developer.github.com/v3/repos/contents/

**Comment by nikrolls** [comment]
In fact, I've just tried by attaching a zip file with symlinks included and the issue remains. I've also verified that GitHub's own zip files (the ones automatically generated and attached to releases, and the ones you download from the `Clone or download` button in the UI) include symlinks correctly. 

So it seems the issue is with HACS not extracting/creating symlinks or their content properly.

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
