### ISSUE TITLE
Uninstalling integrations should call unload entry if available or warn

### ISSUE THREAD

**Issue by alandtse** [hacs/integration#1116]
**Is your feature request related to a problem? Please describe.**
I'm having users [report](https://github.com/custom-components/alexa_media_player/issues/681#event-3297858553) that they try to uninstall `alexa_media` using HACS. And then notice `alexa_media` can't load. I need to then explain they have to delete the integration first before using HACS to uninstall.

**Describe the solution you'd like**
Would it be possible to have HACS delete the integration (assuming it can detect it) prior to deleting the files? Or alternatively, warn users they have to delete before they uninstall from HACS?

**Describe alternatives you've considered**
Warning to delete or automatically unload the config entry. Obviously if the component doesn't expose it, it won't do anything. Nothing can be done with non-config entry integrations I think.

**Additional context**

**Comment by ludeeus** [comment]
Automatic unload, maybe far far far in the future.
Warning, maybe if HACS can get that data, last I tried that it was super unstable.

**Comment by alandtse** [comment]
The warning just has to when someone clicks uninstall on an integration to make remind them to delete the integration BEFORE uninstalling.  You already have the popup.
```
 Are you sure you want to uninstall "X"?
```

**Comment by ludeeus** [comment]
yeah.
But what I referred to was the data that say if it's loaded or not.

**Comment by ludeeus** [comment]
home-assistant/core PR #36130 is now merged.
This allows a user to remove an integration where the files have been deleted.
I feel that cover what was needed from this FR, and will therefore not look at other solutions.
