### ISSUE TITLE
Add hacs.json entry to not install plugin in resources

### ISSUE THREAD

**Issue by Villhellm** [hacs/integration#1123]
**Describe the solution you'd like**

Add an optional entry in hacs.json to disable the plugin install instructions at the bottom of the hacs page and the popup to add to resources at the top. Some plugins need to be added as a frontend extra_module_url, so it's misleading to instruct/prompt to add to lovelace resources if that is the case.

**Comment by ludeeus** [comment]
If you need that you are missusing the plug-in concept.
You are better off publishing your module as a custom component, there is a few that do it like that already.

**Comment by Villhellm** [comment]
It doesn't fit into either plugin or custom component directly, but it's 95% the same as a plugin. Adding python file structure for a single javascript file doesn't make any more sense.

**Comment by ludeeus** [comment]
Sure, that is now, things may change in the future, next you want to add options to it, make it more customisable, maybe the structure of plug-ins changes.
My biggest reason to not add this is that those instructions and that button will be removed soon, as everything will be handled automatically, at least for non-YAML users, adding more checks for this will add more things I need to remember/test/maintain when doing changes to HACS.
An option is a new category, but I don't see that being added in the near future, maybe later in the year 🤷

**Comment by Villhellm** [comment]
Not doing something because it "may change in the future" would mean nothing would ever get done if it relates to Home Assistant. It's a constantly changing platform. 

Anything added under extra_module_url *will* function if you add it as a lovelace resource, but only if the user loads a lovelace dashboard first. Either way it gets added to the main document body. Another category seems like a huge overkill for such a minimal difference. Adding the hacs.json entry seems like the most sensical solution to me, and easier to test/maintain compared to an entirely new category, but I won't try to convince you anymore. I'll just keep the module off hacs for now so I'm not violating any rules/guidelines.
