### ISSUE TITLE
Add flag to validate action to ignore logo

### ISSUE THREAD

**Issue by MatthewFlamm** [hacs/integration#1132]
**Is your feature request related to a problem? Please describe.**
HACS has recently required logos for integrations to be stored on home assistants repository.  My integration needs permission to use logo, but the home assistant core devs do not share my view.

**Describe the solution you'd like**
To be able to turn off the logo check in HACS validate so that I can use the validate action.

**Describe alternatives you've considered**
Remove validate action from my repo.

**Additional context**

**Comment by ludeeus** [comment]
Implemented, documentation updated https://hacs.xyz/docs/publish/action
