### ISSUE TITLE
Adding Hide/Unhide button on list/table elements for integration/plugin/...

### ISSUE THREAD

**Issue by olijouve** [hacs/integration#1133]
**Is your feature request related to a problem? Please describe.**
Being able to Hide component is a very nice feature, it offers a clearest view by filtering out by status for what we can considerate as unappropriate elements(unapplyable country specifics...).
But having to enter in each integration to Hide from the drop down menu can be plainfull, especially because number of integration is quite huge now(and it's a good thing), but navigate back from element details page to listing page loose last scrolling position and return to the top...

**Describe the solution you'd like**
It would be nice to have an Hide action button/icon directly in the integration/plugin/... listing for each elements. Request would be played in background so we could keep staying in the listing page.

**Describe alternatives you've considered**
An alternative could also be, just like the "Clear New" link, to have a "Hide All" link, then by filtering by Name or Stars we could have an Unhide action button/icon directly in the integration/plugin/... listing for each elements.

**Comment by ludeeus** [comment]
Dismiss (hide) was added in 1.0.0, so you don't have to enter anymore.
That's probably as far as this FR will go.
