### ISSUE TITLE
Clearer naming of Integrations / Plugins

### ISSUE THREAD

**Issue by noxhirsch** [hacs/integration#1134]
Hi,
first things first: Thank you for this amazing add-on to Home Assistant! ❤️ 

My problem is, that I always mix up integrations and plugins and I think that this is a problem especially for beginners (which I am not). For me as a non-native speaker it sounds like integrations and plugins are randomly interchangable between custom components and "lovelace extensions" (at least both could be called "plugin").
I'd suggest to name it as clear as possible: "Custom Components" and "Lovelace Plugins". 
It would also help if only the plugins are called "Lovelace Plugins".

Thank you very much! 😃 

EDIT: There was no template?! But I think I covered everything from the guidlines: My problem, my suggestion and my alternative suggestion.

**Comment by ludeeus** [comment]
Changed with https://github.com/hacs/frontend/commit/78ca7f7ca20bf9615178afbfca507ba205dd7cc3
