### ISSUE TITLE
Showing installations number

### ISSUE THREAD

**Issue by sermayoral** [hacs/integration#1135]
It would be great if HACS could show the installations number of each integration (maybe it is also valid for plugins, python_scripts or themes).

For example, in the frontend for an integration, HACS could shows this information:

*Authors: someone*

*GitHub stars: 10*
**Installations (or something like that): 23**
*Last updated: 13 minutes ago*

**Comment by ludeeus** [comment]
HACS does not know that (that would require HACS sending information to a data collection server), so there will be nothing to show.
