### ISSUE TITLE
awkward margin when using transparent --app-header-background-color

### ISSUE THREAD

**Issue by basnijholt** [hacs/integration#1136]
See this (left of installed):

<img width="415" alt="Screenshot 2020-05-07 at 20 12 28" src="https://user-images.githubusercontent.com/6897215/81329671-2c8f2580-909f-11ea-9b43-ba4fdd6506d8.png">

Using this css:
![image](https://user-images.githubusercontent.com/6897215/81329529-01a4d180-909f-11ea-913b-41febf5260f8.png)

I have a suspension it is due to:
![image](https://user-images.githubusercontent.com/6897215/81329797-58121000-909f-11ea-8d50-c109cbca3020.png)

**Comment by ludeeus** [comment]
I will not change this until I can test it.
Which theme are you using?

**Comment by basnijholt** [comment]
I am using https://github.com/basnijholt/lovelace-ios-themes

However, to circumvent the bug in that theme I have increased the transparency of `app-header-backgroud-color`.

I think you can reproduce this bug (with any theme) with just setting:
```
app-header-backgroud-color: rgba(0, 0, 0, 0.1)
```
