### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by chemelli74** [hacs/integration#1138]
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         |  0.24.4
Home Assistant version         | 0.109.5
Installation method for HA    | docker
Web browser                         | Edge Chromium / Firefox
Web browser version            | latest for both

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.

## Describe the issue

Number of updates is always reported in English and not localized based on UI current language

### Steps to reproduce

1. Add sensor.hacs to a entity card
2. Check value: "0 pending udpate(s)"
3. Switch UI language to Italian
4. Check value: is still the same, not localized

### Screenshots

![image](https://user-images.githubusercontent.com/57354320/81495467-be21b180-92b0-11ea-9132-38c648d3a16c.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```
-
```

</details>

**Comment by ludeeus** [comment]
That is the unit of measurement, is it possible to translate that?
Can you point me to another integration that does that?

**Comment by chemelli74** [comment]
> That is the unit of measurement, is it possible to translate that?
> Can you point me to another integration that does that?

I see translation for time in your "it.json", I was in the hope you can add also other unit of measurement.
If this is not the case, can you be so kind to open a PR to the HA core Team ? you are for sure more valuable than me ;-)

Simone

**Comment by ludeeus** [comment]
AFAIK this is not possible, but I may be wrong (which is why I asked for other integrations that do this).
If you don't know of any, I will not use any time investigating this (it has to be supported in HA core for HACS to use it).
What you can do, is to create a template sensor.
there you can set a custom `unit_of_measurement` https://www.home-assistant.io/integrations/template/#unit_of_measurement

**Comment by chemelli74** [comment]
I was thinking about a workaround: what about if the status just have a number and no words ?
So moving from:

![image](https://user-images.githubusercontent.com/57354320/83353079-4cd59b80-a350-11ea-90a0-e8826ad89c1d.png)

to

![image](https://user-images.githubusercontent.com/57354320/83353326-1731b200-a352-11ea-9b11-5a53564018c7.png)

So localization will be as simple as adding a new name to the entity.


Simone
