### ISSUE TITLE
Integration checks wheels repo for requirements when dependencies is the key

### ISSUE THREAD

**Issue by garbled1** [hacs/integration#1142]
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 0.24.4
Home Assistant version         | 0.109.6
Installation method for HA    | venv

## Checklist

- [X] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read https://hacs.xyz/docs/issues
- [X] This issue is related to the backend of HACS.

## Describe the issue

custom_components/hacs/helpers/action.py looks to see if a repository has any requirements, and if it does, it then checks that the integration is added to the home-assistant/wheels repo.  However, the key to being added to the wheels repo, is if the manifest.json has any dependencies.  This can be seen in the following PR, https://github.com/home-assistant/wheels-custom-integrations/pull/28

Due to this, the github action to auto-test code for pulling into the hacs default cannot pass for any of my integrations.

### Steps to reproduce

1. Build a simple integration with no dependencies in the manifest.json
2. Create github action per HACS docs
3. watch it fail.

## Debug logs

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
This is wrong, the python requirements are under the `requirements` key.
`dependencies` are other integrations, those do not belong in that repo.
