### ISSUE TITLE
Unable to add custom integration repository into HACS 0.24.4

### ISSUE THREAD

**Issue by landiatico** [hacs/integration#1143]
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 0.24.4
Home Assistant version         | 0.110.0.dev20200510 (32bit)
Installation method for HA    | docker on raspberry Pi 4 on ubuntu 64
Web browser                         | Firefox and Chrome
Web browser version            | FF 76.0 (64-bit) and Chrome 81.0.4044.138 (64bit)

## Checklist

- [X] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read https://hacs.xyz/docs/issues
- [X] This issue is related to the frontend of HACS.

## Describe the issue

I am trying to add the AlexxIT/SonoffLAN custom repository into HACS in order to sonfigure my Sonoff devices as described in https://github.com/AlexxIT/SonoffLAN but after clicking the save disk icon; nothing happens, just an error log entry in docker.

This was working before on another docker instance, I reinstalled my docker from scratch and now I am unable to load custom repositories. 

Thank you!

### Steps to reproduce

1. Fresh install of home-assistant for Raspberry Pi4 (32bit) on docker (homeassistant/raspberrypi4-homeassistant:latest).
2. Install HACS and wait until it finishes loading repositories.
3. After that go to HACS >> Settings and add AlexxIT/SonoffLAN as Integration and click save.
4. Nothing happens. Just the following line is logged.

### Screenshots

![Screen Shot 2020-05-10 at 17 28 43](https://user-images.githubusercontent.com/41938073/81513188-b4fe0800-92e3-11ea-8a90-9239b940f007.png)

## Javascript logs from your browser console
<details>
  <summary>Browser Logs</sumary>

```text

Browser Log:

TypeError: e.composedPath(...)[2].children[1] is undefined frontend-20200426112021.js:2437:1358

home-assistant.log

2020-05-10 17:22:13 INFO (MainThread) [hacs.repository.theme.home-assistant-community-themes.vaporwave-pink] Registration complete,
2020-05-10 17:28:36 ERROR (MainThread) [frontend.js.latest.202005090] http://192.168.1.100:8123/hacsfiles/frontend-20200426112021.js:2437:1358 TypeError: e.composedPath(...)[2].children[1] is undefined
</details>

<!-- IssueTemplateID: issue_frontend -->

**Comment by ludeeus** [comment]
This is due to a change in the icon handling that is now in HA dev.
Fix for this will be a part of a bigger release for HACS later this week

**Comment by francodutch** [comment]
> This is due to a change in the icon handling that is now in HA dev.
> Fix for this will be a part of a bigger release for HACS later this week

Thanks for your work. Since this was 10 days ago is there a new ETA for this bigger release? Tx

**Comment by ludeeus** [comment]
< 12h (hopefully) There are still a few missing things that need to be added before I start testing/documentation

**Comment by korsarnsk** [comment]
**I have the following version of HACS:**
HACS (Home Assistant Community Store)
Manage (Install, track, upgrade) and discover custom elements for Home Assistant.
Авторы:
ludeeus
Звезды GitHub: 990
Загрузки: 14203
Последнее обновление: 7 часов назад
Версия: 20200426112021
Установлено: 0.24.5
Доступно: (новейшая: 0.24.5)

The following version of HASSIO:  Home Assistant 0.110.1

But I still experience the issue while trying to add a new repo to HACS:
https://aaaa.bbbb.ccc:zzzz/hacsfiles/frontend-20200426112021.js:2437:1387 Uncaught TypeError: Cannot read property 'selectedItem' of undefined
0:15:49 – components/system_log/__init__.py (ERROR)

**Comment by korsarnsk** [comment]
Btw, I have upgraded the HACS to 1.0.1. But it still doesn't show me an integration (f.e., https://github.com/smartHomeHub/SmartIR) as installed, after I tried to install it, at the same time files related to the SmartIR are located in custom_components/smartir.
