### ISSUE TITLE
HIve Custom Component - An error occurred while processing

### ISSUE THREAD

**Issue by holdestmade** [hacs/integration#1152]
The Hive component in a custom repo:
**[integration] Rendili/hive-for-home-assistant**

Hive For Home Assistant
Hive component, platforms and custom components
Authors:  Rendili, KJonline
GitHub stars: 11
Last updated: 2 days ago
Installed: de43254
Available: v2019.1

Is showing red box with:
An error occurred while processing
GitHub returned 404 for https://api.github.com/repos/Rendili/hive-for-home-assistant/git/trees/v2019.1

I can't update it or remove it

**Comment by ludeeus** [comment]
As stated in the issue templates, and the issue guidelines, issues that do **not** fill out the templates will be closed.
Feel free to open another issue by using one of the templates 👋
