### ISSUE TITLE
Removed Purple theme... removed everything

### ISSUE THREAD

**Issue by DavidFW1960** [hacs/integration#1154]
## Describe the issue

A clear and concise description of what the issue is.

I removed the depreciated purple theme (uninstalled from page)
This removed my entire themes directory and all themes.. not just purple.yaml !!!!
I guess this theme was not in it's own folder - it was in the root /config/themes...

**Comment by ludeeus** [comment]
This has nothing to do with hacs-bot.
Please reopen with the backend/integration issue template, thanks 👍
