### ISSUE TITLE
Blank repository menu icon in HA 0.110

### ISSUE THREAD

**Issue by gadgetchnnel** [hacs/integration#1156]
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 0.24.5
Home Assistant version         | 0.110.0b0
Installation method for HA    | Python venv  
Web browser                         | Google Chrome
Web browser version            | 81.0.4044.138

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.

## Describe the issue

A clear and concise description of what the issue is.

When viewing a repository, the icon on the button which displays the menu (Update Information, Show Beta, etc.) does not show. The button is there, and  if you click in the right spot the menu will appear.

This may be due to the [changes in how Home Assistant 0.110 handles icons](https://rc.home-assistant.io/blog/2020/05/12/release-110/#icons) where it only loads icons that are needed. See also [the related PR](https://github.com/home-assistant/frontend/pull/4379) where it seems all uses of **iron-icon** were replaced with **ha-icon** as part of this.

### Steps to reproduce

1. Open HACS
2. Select any repository under Installed, Plugins, or Integrations

### Screenshots

Example showing invisible menu button:
![image](https://user-images.githubusercontent.com/2099542/81976564-a172da00-9620-11ea-89fc-84df96e737d0.png)

Menu still works:
![image](https://user-images.githubusercontent.com/2099542/81976970-3e357780-9621-11ea-9fe7-1b51a138ad36.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
This has already been fixed, and will be a part of the next release
