### ISSUE TITLE
Icons issue in HA 0.110 beta

### ISSUE THREAD

**Issue by SeanPM5** [hacs/integration#1157]
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         |  0.24.5 Frontend version: 20200426112021
Home Assistant version         | 0.110.0b1
Installation method for HA    | Supervised
Web browser                         | Chrome on Mac
Web browser version            | Version 81.0.4044.138 (Official Build) (64-bit)

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.

## Describe the issue

A clear and concise description of what the issue is.

Am 99.9% sure you know of this already, but can't hurt to have an issue for it too I guess. With the icon changes in 0.110.0b there's a tiny bit of funkiness going on with HACS icons.

* Sometimes you see a humongous HACS icon when first loading HA (screenshot below)
* Icon is missing from the more-info dialog of `sensor.hacs`
* Overflow menu icon is missing in the top right corner when inside HACS, can still be clicked but is invisible

### Steps to reproduce

1. Open sensor.hacs more-info
1. Open HACS section and look at top right

### Screenshots

Courtesy cgtobi in #devs_frontend

![image](https://cdn.discordapp.com/attachments/351047592588869643/710727811567976458/unknown.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE
N/A
```

</details>

**Comment by DavidFW1960** [comment]
That funky icon has been doing this for a few releases. A refresh clears it and I never thought is was a HACS bug but more likely to be inconsequential HA funkiness..

**Comment by ludeeus** [comment]
previously it would show if the frontend did not load, or load slowly, and at that point there was only that icon that was working.
Now with the icon changes, if shows more often.
Delete the file `/config/custom_components/hacs/iconset.js` to "fix" it, the icon is broken anyway until I release a new version.
Icon handling has been fixed:
https://github.com/hacs/integration/blob/3eae779e641abcab44da930e92c59951130c26ec/custom_components/hacs/iconset.js#L1-L7

**Comment by ludeeus** [comment]
The next version of HACS will be delayed, if you are using HA 0.110+
Replace the content of `/config/custom_components/hacs/iconset.js` with https://github.com/hacs/integration/blob/master/custom_components/hacs/iconset.js to get the icon working again until the next release.

**Comment by Routout** [comment]
> previously it would show if the frontend did not load, or load slowly, and at that point there was only that icon that was working.
> Now with the icon changes, if shows more often.
> Delete the file `/config/custom_components/hacs/iconset.js` to "fix" it, the icon is broken anyway until I release a new version.
> Icon handling has been fixed:
> https://github.com/hacs/integration/blob/3eae779e641abcab44da930e92c59951130c26ec/custom_components/hacs/iconset.js#L1-L7

Deleting file wont fix issue

**Comment by ludeeus** [comment]
Deleting the file is masking the issue.
Clearing your cache will fix it.
