### ISSUE TITLE
Call stop script when cover is opened 

### ISSUE THREAD

**Issue by fabiobott** [hacs/integration#1158]
## Category

- [X] Backend/Integration
- [ ] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## The idea

In lovelace I click on up button and this integration call up script.
When cover is opened I would the integration call stop script

## Implementation

Call stop script when cover is totally opened or closed

**Comment by ludeeus** [comment]
This integration does not do anything like what you are describing, I think you have this repo confused with another one.
