### ISSUE TITLE
Hacs add unwanted custom repository at every reboot

### ISSUE THREAD

**Issue by ikxdf** [hacs/integration#1159]
After last update I've notice that strange custom repository. If I remove the repos hacs recreate the entries after reboot. 
If I don't delete the repo and reboot Ham has will duplicate the entries.
This is on my log at every reboot:

2020-05-15 19:38:14 INFO (MainThread) [hacs.repository.plugin.hasl-platform.lovelace-hasl-departure-card] Registration complete    
2020-05-15 19:38:14 INFO (MainThread) [hacs.repository.plugin.hasl-platform.lovelace-hasl-traffic-status-card] Registration complete   

This is a screenshot of my custom repos menu:

<img width="1224" alt="Schermata 2020-05-15 alle 21 40 58" src="https://user-images.githubusercontent.com/18067289/82090846-9c805a00-96f6-11ea-8bef-246ec91515e4.png">

**Comment by ikxdf** [comment]
I've try to delete all __pycache__ folder of hacs and reinstall ha container without results

**Comment by ludeeus** [comment]
They renamed the org, this has been fixed in master and will be a part of the next release.
