### ISSUE TITLE
problem beta version IOS app home assistant

### ISSUE THREAD

**Issue by pilot1981** [hacs/integration#1161]
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 0.24.5
Home Assistant version         | 0.109.6
Installation method for HA    | HASSIO
Web browser                         | app IOS homeassistant companion
Web browser version            | app IOS homeassistant companion

## Checklist

- [ X] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [X ] I have filled out the issue template to the best of my ability.
- [X ] I have read https://hacs.xyz/docs/issues
- [X ] This issue is related to the frontend of HACS.

## Describe the issue

Using app IOS homeassistant companion, when I select show beta, I don't see beta version in the list of available release (test with many addons)

### Steps to reproduce

0. open app IOS home assistant companion
1. open HACS
2. open one add-on
3. flag show beta
4. nothing happen

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
There is not a single "addon" in HACS.
Which _spesific_ repositories did you try?

**Comment by pilot1981** [comment]
this one:

https://github.com/bruxy70/Garbage-Collection

**Comment by ludeeus** [comment]
![2020-05-16_20-54-04](https://user-images.githubusercontent.com/15093472/82127948-7078dd80-97b7-11ea-92f3-413b7375a15a.gif)
It works fine for me.
Try clearing your cache, if that does not help I need the browser logs (I have no idea how you get those).

**Comment by pilot1981** [comment]
You are using safari?

**Comment by ludeeus** [comment]
https://www.browserstack.com/ with safari yes.
Apple does not allow any app on iOS to use anything else anyway.

**Comment by ludeeus** [comment]
With the new version, this is moved, and should no longer be an issue
