### ISSUE TITLE
Requires minimum version '0.110.0b0'

### ISSUE THREAD

**Issue by dannyyy** [hacs/integration#1162]
## Describe the issue

I updated HA to version 0.109.6 and wanted to update HACS from 0.21.5 to a more up to date version. Since the introduction of a minimum HA version on May 10th, I'm not able to update to any version. Doesn't matter which. The new minimum is set to 0.110.0b0. I don't like to use beta version for what I'm using HA. Is it really meant to block any update in HACS for people wo decide to stay with the latest stable HA version?

Under the hood HA changed view things which requires a newer HACS version. I guess the latest 0.23.x should be compatible with HA 0.109.6?

**Comment by ludeeus** [comment]
A version of HACS that requires `0.110.0b0` has not been released.
if you see that, you are running the master branch, don't do that.
use https://github.com/hacs/integration/releases/tag/0.24.5

https://github.com/hacs/integration/blob/954958ba1f92c6287f2be6904084d28ad6d736e7/custom_components/hacs/constrains.py#L10
