### ISSUE TITLE
Can't add custom repository.

### ISSUE THREAD

**Issue by AkshatShah1** [hacs/integration#1164]
Hi, I am new to Home Assistant so forgive me if I am overlooking something simple, however, I am trying to add this custom repository to Home Assistant https://github.com/JoshuaMulliken/ha-wyzebulb repository. However, I get the following error:

20-05-15 22:20:13 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/JoshuaMulliken/ha-wyzebulb repository

20-05-15 22:20:15 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/87977a50/repository.json: [Errno 2] No such file or directory: '/data/addons/git/87977a50/repository.json'

20-05-15 22:20:15 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/87977a50/repository.json

I submitted this in the github for the custom repo and I was told that it seems like a HACS problem and I should ask here.

**Comment by ludeeus** [comment]
Hi 👋 
That is not HACS, that is the supervisor.
This is HACS: https://hacs.xyz/

The supervisor does not handle integrations, you need HACS for that.
