### ISSUE TITLE
Can't reinstall HACS

### ISSUE THREAD

**Issue by EryxFR** [hacs/integration#1170]
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 0.25.5
Home Assistant version         | 0.110
Installation method for HA    | Docker

## Checklist

- [] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [ ] I have enabled debug logging for my installation.
- [X ] I have filled out the issue template to the best of my ability.
- [X ] I have read https://hacs.xyz/docs/issues
- [ ] This issue is related to the backend of HACS.

hello, guys, 
Yesterday, i tried to upgrade Hacs to 0.25.5 (i had 0.25.3). Home Assistant wrote me there is an error (Configuration is not good). 
I deleted the Hacs folder and the entries in .storage, i modified the core entries (to erase everything about hacs). Finally, the integration of hacs went over. i deleted the cache of my browser. 
but impossible to reinstall hacs! When i choose it in the list of integration, nothing happen! 
Any help for me? 
Thx  

### Steps to reproduce

1.
1.
1.

## Debug logs

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by vikdb** [comment]
Got the same problem, got an error when updating to 0.110 and figured l could just reinstall..

**Comment by ludeeus** [comment]
@EryxFR Where are your logs?
@vikdb You have issues with your Home Assistant installation, you are not able to install the requirements.

**Comment by EryxFR** [comment]
> @EryxFR Where are your logs?

i restarted home assistant session. I don't have logs anymore :(

**Comment by EryxFR** [comment]
> @EryxFR Where are your logs?

I tried to reinstall Hacs now: 

Logger: homeassistant.config_entries
Source: config_entries.py:510
First occurred: 18:03:07 (1 occurrences)
Last logged: 18:03:07

Error occurred loading configuration flow for integration hacs: No module named 'custom_components.hacs'

**Comment by ludeeus** [comment]
That say you do not have the HACS files in the expected location.
use this: https://hacs.xyz/docs/installation/manual
or: https://hacs.xyz/docs/installation/manual_cli

**Comment by EryxFR** [comment]
> That say you do not have the HACS files in the expected location.
> use this: https://hacs.xyz/docs/installation/manual
> or: https://hacs.xyz/docs/installation/manual_cli

I followed the method, but that's the same.

![Capture-2](https://user-images.githubusercontent.com/39946769/82471321-d7073f80-9ac6-11ea-9b75-5bf06fd16be3.jpg)
![Capture-1](https://user-images.githubusercontent.com/39946769/82471402-ef775a00-9ac6-11ea-896e-4d1bf55e75ae.jpg)

**Comment by ludeeus** [comment]
You did not follow it ;)
You named it `Hacs` it should have been named `hacs`

**Comment by EryxFR** [comment]
> You did not follow it ;)
> You named it `Hacs` it should have been named `hacs`

Damn.. i feel so stupid :( 

thx a lot ;)
