### ISSUE TITLE
Uninstalling theme in HACS deletes entire theme directory

### ISSUE THREAD

**Issue by dredzed** [hacs/integration#1177]
I had the following in my log:
“You have sinclairpaul/ha_purple_theme installed with HACS this repository has been removed, please consider removing it. Removal reason (blacklist)”

So I want to HACS and uninstalled Purple Theme.
This action then deleted my whole themes directory, so I only had access to the default theme.
I am on Home Assistant 0.109.6

Just to check, I reinstalled a snapshot to repeat the process, but the same thing happened. I’m probably doing something wrong, but just wanted to warn people!

**Comment by ludeeus** [comment]
Dude.... reopen this issue and fill out the template (this would be backend/integration)
