### ISSUE TITLE
Uninstalling theme in HACS deletes entire theme directory

### ISSUE THREAD

**Issue by dredzed** [hacs/integration#1180]
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         |0.24.5
Home Assistant version         |0.109.6
Installation method for HA    |generic Hassio on nuc

## Checklist

- [ x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [too hard on phone ] I have enabled debug logging for my installation.
- [ x] I have filled out the issue template to the best of my ability.
- [ x] I have read https://hacs.xyz/docs/issues
- [ x] This issue is related to the backend of HACS.

## Describe the issue

A clear and concise description of what the issue is.

I had the following in my log:
“You have sinclairpaul/ha_purple_theme installed with HACS this repository has been removed, please consider removing it. Removal reason (blacklist)”

So I want to HACS and uninstalled Purple Theme.
This action then deleted my whole themes directory, so I only had access to the default theme.

### Steps to reproduce

1.uninstall purple theme via HACS
1.
1.

## Debug logs

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE
Sorry, not at home and this is very difficult to do on my phone. I can try to add them in a week or so?
```

</details>

**Comment by Nealtron** [comment]
I have also encountered this issue.


Description | Value
-- | --
Home Assistant | 0.110.4
Installation method for HA | generic Hassio on VirtualBox
Integration version |1.0.3
Frontend version | 202005242033
