### ISSUE TITLE
Missing icon after upgrade new version

### ISSUE THREAD

**Issue by sagitt** [hacs/integration#1181]
see image.
![Schermata 2020-05-21 alle 20 03 25](https://user-images.githubusercontent.com/169086/82590570-3421f480-9b9e-11ea-849d-6e245f275c13.png)

Integration version: | 1.0.0
-- | --
Frontend version: | 20200521162326
Repositories: | 587
Installed repositories: | 11

**Comment by ludeeus** [comment]
Clear your cache

**Comment by sagitt** [comment]
solved. yes!
