### ISSUE TITLE
Bring back new/updated repos in 1.0.0

### ISSUE THREAD

**Issue by mdegat01** [hacs/integration#1182]
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## The idea

In prior versions of HACS there used to be an easy way to see what repositories have been added/updated since the last time you looked.  This was really great since the list of repositories is enormous.  I can certainly search for terms when I know I need something but the "new/update" indicator was a fantastic way to find things you find useful but you hadn't thought of yet.  Or if you searched and failed to find something you probably aren't going to search for that thing again unless something makes you believe the answer will be there this time (like if a component with a name that matches your search is in the new/updated repositories list).

## Implementation

The two implementation paths that came to mind were:
- A new tab next to "Integrations", "Frontend" and "Automations" for "New/Updated Repositories". Every time you visit this tab the flag is cleared for all repositories.
- "New/Updated Repositories"  float to the top of the list that is shown when the '+' icon is pressed along with some kind of visual indicator denoting "new/updated".  This flag is cleared for all repositories after the pop-up is closed

## Alternatives

Could also just add this info to a sensor like "sensor.hacs_repos_with_changes_today" and then users can choose to build their own UI out of it or not.  Would probably be better to limit such a sensor to "updates today" to prevent it from getting too large and creating errors in recorder.

## Additional context

New UI looks nice, still getting used to it.  Was sad to see this feature disappear though.

**Comment by ludeeus** [comment]
"In prior versions of HACS there used to be an easy way to see what repositories have been added/updated since the last time you looked. "

That is still there?

**Comment by thecode** [comment]
The problem is that the new repositories are shown at the top so that you can not see the installed ones. If you clear new repositories it is ok.

**Comment by ludeeus** [comment]
It sounds like this is what you are after https://hacs.xyz/docs/basic/automation#new-repositories-added.

But the title and context here are confusing since the new repositories and updates are clearly marked (show with my screenshot.)

**Comment by mdegat01** [comment]
Oh my bad. I think what happened is the flag for "new/updated" got cleared on update of have. I check for what's new periodically and hadn't checked in a bit so I would've expected some new repos. When I didn't see any in the UI or mention of it moving/changing in the release notes i assumed that it had gone away.

But you're right, your screenshot shows exactly what I was looking for, i just needed to give it more time. Thanks! Closing this.
