### ISSUE TITLE
Separate new repo notifications from installed components 

### ISSUE THREAD

**Issue by allan-reynolds** [hacs/integration#1183]
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## The idea
The new page layout feels a little confusing and if you have a lot of custom additions new repos may be missed if they are further down.  

## Implementation
Move the newly added repos to their own tab which would only be shown if new repos exist.   This keeps the installed features pages clean whilst allowing you to look at the new repos when you have time rather than when you have gone in to do something else. 

## Alternatives

Surface new repos at the top of the page with your installed ones below as per the old installs page.

**Comment by scooper1** [comment]
+1

**Comment by nikrolls** [comment]
Agreed. I like the new UI (nice work @ludeeus!) but I feel like having new (and often irrelevant to me) items mixed in with your existing ones is a conflation of UX workflows. I either want to manage my existing integrations and plugins, or I want to find new ones, but I would never consider doing both at the same time and it's actually a very confusing default option.

**Comment by theaquarium** [comment]
Yeah, I support this too. I somewhat fail to see the need for having the new repository notifications at all but if it's necessary for discoverability, I'd like to see my currently installed on top.
