### ISSUE TITLE
Always display close button on add repository

### ISSUE THREAD

**Issue by royto** [hacs/integration#1184]
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## The idea
With the new layout, when a repository is open, the close button is in the header.
If we scroll down, the close button is hidden and we need to scroll up to be able to close the pop up.

![image](https://user-images.githubusercontent.com/6990995/82597278-01312e00-9ba9-11ea-8af0-945c61259ec1.png)

The close button should be always visible to be able to close the pop up easily.

## Implementation

Make the button always visible

## Alternatives

Are there any alternative solutions or features you've considered?
Maybe the header should be always visible. We can always see on which repository we are viewing.
Only the content is scrollable

**Comment by GeorgeSG** [comment]
Copying my take from #1194 

The only way to close the popup is clicking the "X" button. This is especially frustrating when you've scrolled down the list of repositories and the "X" button is not visible. This is true for all popups in HACS and is frustrating in each of them IMO.

**Suggestion**: Enable closing the popup via the ESC key and by clicking outside of the popup.

**Comment by royto** [comment]
On mobile, there is not esc and pop up is full screen ...

**Comment by GeorgeSG** [comment]
Fair enough, I think these are nice to have. On desktop, it's intuitive to click away from the popup or hit Escape.

Always showing the close button is a cross-platform solution though, so I agree it's the most important addition :)
