### ISSUE TITLE
Use paper-dialog-background-color for pop up card background in v1.0.0

### ISSUE THREAD

**Issue by adamoberley** [hacs/integration#1185]
## Category
- [x] Frontend

## The idea
Use `paper-dialog-background-color` for the background of the pop up cards in v1.0.0. It is the same theme element that the rest of the HA pop up cards use for their background. This will help people that use transparent themes be able to read the cards.

## Example
Not using `paper-dialog-background-color`
<img width="540" alt="image" src="https://user-images.githubusercontent.com/37665060/82598715-13937380-9b79-11ea-86f7-9926a90b3810.png">

Using `paper-dialog-background-color`
<img width="454" alt="image" src="https://user-images.githubusercontent.com/37665060/82598890-5c4b2c80-9b79-11ea-9eaa-b405b0664b05.png">

**Comment by tomlut** [comment]
Or use 
```
card-background-color
```

Which is what the other UI elements seem to use.
