### ISSUE TITLE
Make add repository button more accessible

### ISSUE THREAD

**Issue by royto** [hacs/integration#1188]
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## The idea
To install a new integration, cards, ... we need to scroll to the bottom of the add repository pop up to be able to see buttons 

Button need to be more visible and more accessible 

## Implementation

I have though about several options:

- duplicate button in the header (inside a three dot button for example)
- make the footer always visible (fixed). Only the content is scrollable

I think the second one is what I prefer ...

## Additional context

![image](https://user-images.githubusercontent.com/6990995/82599737-15772a00-9bad-11ea-8fb7-038c273e7385.png)

**Comment by ludeeus** [comment]
related to https://github.com/hacs/integration/issues/1184
Both the action part and the header should always show.

**Comment by Lymkin** [comment]
My add button does not work at all.

**Comment by ludeeus** [comment]
@Lymkin open a issue with the frontend template
