### ISSUE TITLE
Display only relative package on add repository pop up

### ISSUE THREAD

**Issue by royto** [hacs/integration#1189]
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## The idea
It feel weird to me that we have tabs for integration and front-end but when adding a repository we see all types

I expect when I am in integration and click on +, to see only integrations
same for front-end ...

## Implementation

Only display packages relative to the current tab
If in integrations tabs, show only integrations
If in front-end tabs, show only cards and theme

## Alternatives

Are there any alternative solutions or features you've considered?

in the material design guideline about [buttons floating action button](https://material.io/components/buttons-floating-action-button#types-of-transitions), we can open sub-button like

![image](https://user-images.githubusercontent.com/6990995/82600758-b87c7380-9bae-11ea-84ee-db3e2f4fcecf.png)

On click on the add button, we could display different type of package type: integration, cards, themes, ... and the pop up only display the selected type

**Comment by scooper1** [comment]
+1
