### ISSUE TITLE
Add integration/frontend not working on fresh install

### ISSUE THREAD

**Issue by CJNE** [hacs/integration#1190]
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 1.0.0
Home Assistant version         | 0.110.1
Installation method for HA    | New way, no YAML
Web browser                         | Chrome MacOS
Web browser version            | 81.0.4044.138

## Checklist

- [ x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x ] I have filled out the issue template to the best of my ability.
- [x ] I have read https://hacs.xyz/docs/issues
- [x ] This issue is related to the frontend of HACS.

## Describe the issue

When i click the + icon at the bottom of the Integrations or frontend screen nothing happens.
Javascript error:
Uncaught (in promise) TypeError: Cannot read property 'toLocaleLowerCase' of null 
at HTMLElement.render (frontend-20200521162326.js:25759)

the minified javascript for that line looks like this:
const repositories = this._filterRepositories(this._repositoriesInActiveCategory(this.repositories, (_a = this.configuration) === null || _a === void 0 ? void 0 : _a.categories), this._searchInput.toLocaleLowerCase());

### Steps to reproduce

1. On a fresh install of HA, install hacs following the official installation guide
2. After initial configuration (github key) and restart, click on HACS on the sidebar
3. Click integrations and the the + icon at the bottom.

### Screenshots
No visual error, integrations screen is empty

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

Uncaught (in promise) TypeError: Cannot read property 'toLocaleLowerCase' of null
    at HTMLElement.render (frontend-20200521162326.js:25759)
    at HTMLElement.update (frontend-20200521162326.js:2628)
    at HTMLElement.performUpdate (frontend-20200521162326.js:2132)
    at HTMLElement._enqueueUpdate (frontend-20200521162326.js:2091)

```

</details>

**Comment by benyaming** [comment]
Hi, how should i fix the issue if I don't want to install not stable version?

**Comment by ludeeus** [comment]
You wait for the next release
