### ISSUE TITLE
Bring Back Hidden Cards

### ISSUE THREAD

**Issue by broyuken** [hacs/integration#1191]
I clicked hide on one of the cards when I first updated to 1.0 when it listed them all as new (Air purifier card). How can I get it back? I don't see it under the list of integrations when I search for it.

**Comment by broyuken** [comment]
Also, one of my buddies has an automations section under the main menu but I do not. I only have frontend and integrations.

**Comment by ludeeus** [comment]
Use the issue templates, thanks 👍
