### ISSUE TITLE
HACS 1.0 UI feedback

### ISSUE THREAD

**Issue by GeorgeSG** [hacs/integration#1194]
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## The idea
Hey 👋,

Congratulations on the 1.0 release! 🎉

First of all, HACS has been instrumental in me being able to configure my setup the way I want it, so I'm really thankful for that! I'm happy to see it maturing, being upgraded and cared for :)

I have some feedback about the 1.0 release I thought I'd share. Feel free to close this and ignore it if you disagree, I know some of this is just my opinion. I'll try to provide constructive feedback and suggestions :)

Also, apologies in advance if there is some backlog that I've missed and I'm suggesting things that are already planned.

### Home page

In general, I like the new home page. I see how it can enable future improvements and features. I really like that all available updates are clearly visible there.

**Problem**:  However, right now a lot of the times it's mostly making me do an extra click, especially if I'm looking to install something.

**Suggestion**: Consider adding the + FAB button to the Home page. It'll make it easier to go straight to browsing / searching / installing repositories.

### Pages (Integration, Frontend, Automation)

**Problem**: I don't know if that's true for most users, but my 2 main use cases for HACS are: 1. updating installed repositories (handled on the Home page), and 2. browsing/installing new repositories. Giving so much dedicated space for currently installed ones looks good and is consistent with HA's Integrations page, but is less useful IMO.

**Suggestion**: This will be somewhat in conflict with my other suggestions, but consider making the list of available repositories a first-level citizen instead of it being hidden in a popup. To me, the discovery/exploration part of HACS is the most-important use-case (both as a user and as a contributor). Seeing the list of your already installed repositories that don't even have an update is a secondary job IMO.

### "Add repository" popup 

**Problem**: The only way to close the popup is clicking the "X" button. This is especially frustrating when you've scrolled down the list of repositories and the "X" button is not visible. This is true for all popups in HACS and is frustrating in each of them IMO.

**Suggestion**: Enable closing the popup via the ESC key and by clicking outside of the popup.

---

**Problem**: Searching changes the popup width:
![2020-05-22 00 03 50](https://user-images.githubusercontent.com/2514425/82606522-df8f7100-9bbf-11ea-8899-f766bd24ceaf.gif)

**Suggestion**: Consider setting a fixed width for the popup.

---

**Problem**: Sorting is gone. I think it was really useful for discovery purposes. For new users, it's useful to sort by stars - to quickly see the most popular repositories. There's good chance that these will be the best plugins. 

For power users, it's really nice to be able to sort by new or recently updated, to see if anything new has appeared or something is updated and try it out.

**Suggestion**: Consider bringing back the sorting of available repositories.

---

**Problem**: All repositories are in a single list. It's a little bit confusing that the same popup is opened on every page. I would expect that when I'm on "Integrations" I would only see Integrations in the popup. Also, it's useful to browse only themes, or only plugins - especially if you're in "discovery" mode and not specifically searching for something.

**Suggestion**: Consider adding filtering by type in the popup. Consider setting a default filter when the user opens the popup from a specific page. If you add the popup to the Home page, it can be opened without filters from there.

--- 

**Problem**: "Only the first 100 repositories are shown, use the search to filter what you need". This is also a hit to discoverability. It wouldn't be that big of a problem if there were filtering and sorting options, but as it is, some repositories will just never be shown. 

For example, at least on my install, button-card is the second to last repository. This is one of the most popular and useful repositories IMO. It wouldn't be good if it isn't visible. Maybe users won't think to search for "button" - there already is a button at the end of the day, why would they need that?

**Suggestion**: Consider adding dynamic loading on scroll or pagination to the list.

---

I think that's it. If you've read all of this - I really appreciate it :) I hope it's helpful.

**Comment by hellcry37** [comment]
This is exactly what I've login here to say :)

**Comment by marcelkous** [comment]
I have another suggestion for the Pages "Integrations" and "Frontend"

**Problem (for both the Integrations page and Frontend page):**
All the listed add-ons, _installed_ and _not installed_, are in the same list. You have to search the ones you have installed. 

**Solution**
List the installed Add-ons first, add a ruler, and then list the other Add-ons.
Or add a dashboard where only the installed version are listed. 
Like in the HA Supervisor screen. 

Thanks,

**Comment by ludeeus** [comment]
@GeorgeSG  @marcelkous CAn you open separate feature requests for each item, thanks 👍 
"catchall" issues are generally a bad idea since they tend to get messy fast.

**Comment by lseufer** [comment]
Same here. I will hold back updating right now. Not having the new integrations and plugins displayed is a bummer. This is how I have discovered most of the integrations I installed via HACS.

**Comment by ludeeus** [comment]
> Not having the new integrations and plugins displayed is a bummer.

They are there... but this is the first and last comment I will give in this FR before it's broken up.
![image](https://user-images.githubusercontent.com/15093472/82647752-ef866f80-9c16-11ea-8041-3b7bbc8c183b.png)


@GeorgeSG You did a good job creating this, but it needs to be broken up.

**Comment by Dinth** [comment]
im not a big fan of the new UI either.
1) i dont like the main page which opens after clicking on HACS link. In my opinion it is completely uncesserary.
2) i dont like the fact that new repositories are mixed up with already installed integrations/plugins.

**Comment by GeorgeSG** [comment]
@Dinth, if your comment is about the "Add repository" popup, I think your second point has already been fixed by version 1.0.1.

Folks, please refrain from adding more comments here, as requested by @ludeeus. I'll split this issue up and close it when I get off from work today :)

**Comment by kulmegil** [comment]
- While obviously already mentioned I feel like I have to repeat this one:
  ability to SORT (by stars and last update especially) and possibility SEE ALL REPOS at once.
  I cannot comprehend why this functionality was considered as non-essential and not included before releasing 1.0 and it kind. It bothers me.

- I have to scroll all the way up to close any repo card - since close button is in the (not fixed) card hader.  Can't I just click outside the card to close it and return to listings?

- my currently installed repositories are mixed with new repos making whole thing unreadable
  (at least for frontend plugins.. there are none new repos displayed in integrations section?)

- There was a warning when a frontend plugin is not added to Lovelace resources and now it's gone.

**Comment by GeorgeSG** [comment]
As we discussed - I've split this issue in multiple feature requests.

- Home page suggestion - dropped. It's kinda a duplicate of #1188, and I don't think it's high priority. If it is, somebody else should bring it up.
- Pages (Integration, Frontend, Automation) - opened #1224
- Searching changes the popup width - opened #1225 
- Sorting is gone - didn't open a new issue - conversation continues in #1219
- All repositories are in a single list - duplicate of #1189 - will be addresed with [this PR](https://github.com/hacs/frontend/pull/143)
- Only the first 100 repositories are shown - opened #1223

The discussion about mixing new and installed repositories is in #1183

@kulmegil, if you don't see your suggestions in the list of opened issues, I suggest you open a feature request for what's missing.

For everyone that upvoted this issue - if you agree with some of these feature requests, please go and 👍 them. I think this will help surfacing the suggestions that are most important. Thanks!

Also, thanks @ludeeus for your patience :) I'm closing this as it is obsolete now.

**Comment by ludeeus** [comment]
Thanks! @GeorgeSG ❤️
