### ISSUE TITLE
Add preview/screenshot browsing for themes

### ISSUE THREAD

**Issue by lilbuh** [hacs/integration#1196]
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## The idea

it s kinda hard to find a good theme without installing it , adding a theme gallery would be a nice feature
## Implementation

- adding a required screenshot of the theme in the theme's repo
- create a gallery view to access the theme's description/install prompt

**Comment by ludeeus** [comment]
It is up to the developer of the theme to include screenshots (placed in the readme.md/info.md files).
No new repositories are added as default now without screenshots.
Those screenshots you will see before installing them.
