### ISSUE TITLE
1.0 - Cannot find "search" or "filter" or "enable/disable" beta

### ISSUE THREAD

**Issue by chemelli74** [hacs/integration#1198]
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 1.0
Home Assistant version         | 0.110.1
Installation method for HA    | Docker
Web browser                         | Chromium
Web browser version            | Version 81.0.416.72 (Official build) (64-bit)

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.

## Describe the issue

Unfortunately with the new UI I cannot find the "search" or "filter" function.
Also "show beta" toggle can be seen only at first install, but I cnanot find a way to change it afterwards.

### Steps to reproduce

1. Update to HACS 1.0

### Screenshots

![image](https://user-images.githubusercontent.com/57354320/82642935-fc9f6080-9c0e-11ea-8b3a-7d2b24c856d6.png)

---

![image](https://user-images.githubusercontent.com/57354320/82643238-76374e80-9c0f-11ea-824c-685d29449308.png)

---

![image](https://user-images.githubusercontent.com/57354320/82642923-f7daac80-9c0e-11ea-828b-b28cce39243f.png)

---

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
> Unfortunately with the new UI I cannot find the "search" or "filter" function.

You have that when you are searching for new items with the  + in the bottom right corner.

> Also "show beta" toggle can be seen only at first install, but I cnanot find a way to change it afterwards.

Click "reinstall" on the card to open the installation dialog.

**Comment by chemelli74** [comment]
Thx, everything in piace as you told.
Fantastic job!!!

Simone
