### ISSUE TITLE
The "+" button doesn't work

### ISSUE THREAD

**Issue by rauljerico** [hacs/integration#1200]
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         |1.0.0
Home Assistant version         |0.110.0
Installation method for HA    |Docker
Web browser                         |Chrome
Web browser version            |Last

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.

## Describe the issue

The "+" button doesn't work

### Steps to reproduce
After restart HA I can't use the Add button

### Screenshots
https://i.imgur.com/TimzY6f.png

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by Manuel-1982** [comment]
Same issue as #1190 
https://github.com/hacs/integration/issues/1190
