### ISSUE TITLE
NEW Version 1.0 ISSUES CALENDAR-CARD AND Custom Header Stop working

### ISSUE THREAD

**Issue by giugit** [hacs/integration#1202]
Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 1.0
Home Assistant version         | LATEST
Installation method for HA    | HassOS 3.13
Web browser                         | ALL
Web browser version            | MOST RECENT
- [X ] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [X ] I have filled out the issue template to the best of my ability.
- [X] I have read https://hacs.xyz/docs/issues
- [X ] This issue is related to the frontend of HACS.

## Describe the issue

Custom Header not appear
Calendar-Card - Custom element doesn't exist
Is not possible to reinstall the previous version!
What can I do?
THANKS!

### Steps to reproduce

1. CUSTOM HEADER MENU NOT APPAIR
2. CALENDAR-CARD NOT SHOWED WITH THE ERROR I WROTE

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
@giugit You need to open issues with the developer _those_ repositories, not with HACS.
