### ISSUE TITLE
HACS not loading after update to 1.0.0 - Restore Failed

### ISSUE THREAD

**Issue by Gavin-A92** [hacs/integration#1204]
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 1.0.0
Home Assistant version         | 0.110.1
Installation method for HA    | host_os: HassOS 3.13 / installation_type: Home Assistant

## Checklist

- [ x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [ x] I have enabled debug logging for my installation.
- [ x] I have filled out the issue template to the best of my ability.
- [ x] I have read https://hacs.xyz/docs/issues
- [ x] This issue is related to the backend of HACS.

## Describe the issue

HACS upgrades as expected and asks to Restart Home Assistant.
Upon restart HACS is present in Integrations and can be configured/modified but is not available on the Sidebar or via direct URL.

Log (see below) report that a restore failed because [time data '' does not match format '%Y-%m-%dT%H:%M:%S']

### Steps to reproduce

1. Upgrade from 24.5 to 1.0.0 (upgrade using HACS) and restart HA

## Debug logs

<details>
  <summary>Logs</summary>

```text

2020-05-22 09:32:28 INFO (MainThread) [hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.0.0
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2020-05-22 09:32:30 DEBUG (MainThread) [hacs] Can update 487 repositories
2020-05-22 09:32:30 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Checking repository.
2020-05-22 09:32:31 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Running checks against 1.0.0
2020-05-22 09:32:32 INFO (MainThread) [hacs.repository.integration.hacs.integration] Registration complete
2020-05-22 09:32:32 INFO (MainThread) [hacs.data] Restore started
2020-05-22 09:32:32 CRITICAL (MainThread) [hacs.data] [time data '' does not match format '%Y-%m-%dT%H:%M:%S'] Restore Failed!
2020-05-22 09:32:32 INFO (MainThread) [hacs] Disabling HACS
2020-05-22 09:32:32 INFO (MainThread) [hacs] Removing recuring tasks
2020-05-22 09:32:32 INFO (MainThread) [hacs] Removing sensor
2020-05-22 09:32:32 INFO (MainThread) [hacs] Removing sidepanel
2020-05-22 09:32:32 INFO (MainThread) [hacs] HACS is now disabled

```

</details>

**Comment by ludeeus** [comment]
Can you upload the `/config/.storage/hacs.repositories` file?

**Comment by yniezink** [comment]
I have the same issue. When I put the old files from 24.5 back everything works again

**Comment by ludeeus** [comment]
@yniezink When you have the same issue, just add a 👍 to the issue, there is no need to flood issues with comments that do not add to the context, thanks 👍

**Comment by Gavin-A92** [comment]
[hacs.repositories.zip](https://github.com/hacs/integration/files/4667007/hacs.repositories.zip)

here you go (had to zip it to upload)

**Comment by ludeeus** [comment]
That's fine, thanks👍

**Comment by Gavin-A92** [comment]
taking a clue from the file you have asked for.......if I remove/rename this file HACS starts fine (without restarting HA) and is now running through it's startup process.

**Comment by ludeeus** [comment]
Sure, but that will make it lose track of everything

**Comment by tofuSCHNITZEL** [comment]
> 
> 
> Sure, but that will make it lose track of everything

what do you mean with "everything"? it displayed all the already installed repositories and update states just fine... just had to "hide all new" again.
but after a HA restart the error is back.

**Comment by ludeeus** [comment]
> it displayed all the already installed repositories and update.

It should not do that if you remove/rename hacs.repositories

**Comment by tofuSCHNITZEL** [comment]
okay.... for my install these infos are in a file called "hacs.installed".
I have the following files: hacs.(critical|installed|removed|repositories|hacs)
In my other HA install where I installed hacs quite recently (but before 1.0.0) I only have hacs.(critical|hacs|repositories)
(but I have stuff installed there via hacs)

**Comment by ludeeus** [comment]
`hacs.installed` has not been used since v 0.15.0

**Comment by tofuSCHNITZEL** [comment]
should I delete .installed and .removed?

**Comment by ludeeus** [comment]
no

**Comment by Gavin-A92** [comment]
Thanks for this
I've manually edit the file you modified and all seems to be working fine now....cheers

**Comment by tofuSCHNITZEL** [comment]
yes thanks. it works now even after HA restart.
