### ISSUE TITLE
Bring Back Hidden Cards

### ISSUE THREAD

**Issue by broyuken** [hacs/integration#1209]
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 1.0.1
Home Assistant version         | 0.110.0
Installation method for HA    | Docker
Web browser                         | Chrome, Firefox, iOS app
Web browser version            |

## Checklist

- [x ] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x ] I have filled out the issue template to the best of my ability.
- [x ] I have read https://hacs.xyz/docs/issues
- [x ] This issue is related to the frontend of HACS.

## Describe the issue

A clear and concise description of what the issue is.
If I hide a card, it is gone forever with no way to bring it back. 

### Steps to reproduce

1. On the initial screen when I first upgraded, it showed all the "new" cards/integrations.
2. Select hide on one of them. I chose Air Purifier Card
3. It's gone forever

**Comment by ludeeus** [comment]
If you "hide" a new repositories, it will still show on the Add new repository dialog (the + icon in the bottom right corner)

**Comment by broyuken** [comment]
That particular card doesn’t show up if I type purifier, but it does if I type air. So somethings messed up with the search.
