### ISSUE TITLE
Freezes when scrolling down to install anything

### ISSUE THREAD

**Issue by broyuken** [hacs/integration#1210]
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 1.0.1
Home Assistant version         | 0.110.0
Installation method for HA    | Docker
Web browser                         | Chrome, Firefox, iOS app
Web browser version            |

## Checklist

- [x ] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x ] I have filled out the issue template to the best of my ability.
- [x ] I have read https://hacs.xyz/docs/issues
- [x ] This issue is related to the frontend of HACS.

## Describe the issue

A clear and concise description of what the issue is.
If I scroll down on any integration/card it freezes and I am unable to install anything

### Steps to reproduce

1. Click on an intrgration, such as Custom Header
2. Scroll down to install
3. HACS freezes, can only click back to overview or any other HA tabs, but HACS is locked up.

**Comment by ludeeus** [comment]
I'm not able to reproduce this, can you add a screen recording of it?

**Comment by broyuken** [comment]
https://youtu.be/Q4aV-b5Er-o

Here, I am unable to scroll down and click install.

**Comment by Tacchi1983** [comment]
I have this problem too on mobile Phone. The install button is not there. On my laptop this doesnt happen. I think this is a general problem on mobile phone.

**Comment by pipip** [comment]
same here on mobile devices - - > I dont have an install button at the bottom
