### ISSUE TITLE
Install latest version when clicking install.

### ISSUE THREAD

**Issue by niemyjski** [hacs/integration#1213]
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

Clicking install on a new theme brings me a modal in a modal to select the version, let's just install the latest version!!! 
![image](https://user-images.githubusercontent.com/1020579/82674264-a5968d00-9c08-11ea-9390-8c8676ab52cc.png)

**Comment by ludeeus** [comment]
How would you then get the information of the location?
And for Lovelace elements that you need to add to your resources (if YAML mode), how would you get that?

**Comment by niemyjski** [comment]
Use the latest tag, if no tag just use master. Output the location to the log. I'm not sure why I'd ever need the location if I'm in yaml mode it's my job to figure it out via documentation or physically looking. But with HACS and changes that HA is making, yaml days are numbered.

**Comment by ludeeus** [comment]
> Use the latest tag, if no tag just use master.

It uses that when you click install, there is no need to select a version
