### ISSUE TITLE
Add new Repository - make name clickable to the repository and add install to the left side of header.

### ISSUE THREAD

**Issue by niemyjski** [hacs/integration#1214]
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

Clicking on an add search result to install an item makes you scroll down an entire readme which can be really long. Perhaps make the item name (in the header) be a link to the repository with an external link mdi icon and then add the install primary button to left side of the header: 
![image](https://user-images.githubusercontent.com/1020579/82674173-87c92800-9c08-11ea-896b-d1e64b3289dd.png)

**Comment by ludeeus** [comment]
This will be handled by <https://github.com/hacs/integration/issues/1188>
