### ISSUE TITLE
Add new says add repository but it's not a repository

### ISSUE THREAD

**Issue by niemyjski** [hacs/integration#1215]
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

Clicking add on an integration says add repository but it's not a repository (in a users perspective, it's an integration, theme etc..)

**Comment by ludeeus** [comment]
That is by design, they are all repositories.
And the wording change is on purpose to help "teach" the user that.
