### ISSUE TITLE
Highlight newly released integrations

### ISSUE THREAD

**Issue by niemyjski** [hacs/integration#1216]
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

How do I know about newly released integrations? I kinda liked the old ui in this respect (I learned about newly released integrations.

**Comment by ludeeus** [comment]
What do you mean by that?
New releases to things you have installed are shown to you as an update both on the main page, and on the section pages for that repository.

**Comment by niemyjski** [comment]
I'm talking about new repositories, how would I know they are available or recently added?

**Comment by ludeeus** [comment]
New repositories are shown as a card along with your installed.

**Comment by edenhaus** [comment]
@ludeeus Is it possible to disable showing new repositories? Or even better to separate them from the installed ones? For me it's hard to see quickly, which one I have installed... If you want, I can open a new issue for that.

**Comment by ludeeus** [comment]
They are separated with <https://github.com/hacs/frontend/pull/148> @edenhaus
