### ISSUE TITLE
Custom repository icons

### ISSUE THREAD

**Issue by niemyjski** [hacs/integration#1217]
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

I wasn't 100% sure if this was a bug, but it seemed inconsistent for the icons and how they were resolved.

Not sure where the icons come from for custom repos but they are all GitHub repos (didn't remember see anything in hacs.json either??: 
![image](https://user-images.githubusercontent.com/1020579/82673767-eb9f2100-9c07-11ea-81cc-36490ee3ce7d.png)

**Comment by ludeeus** [comment]
Icons for integrations use the same repository as core HA <https://github.com/home-assistant/brands>, when they do not exist it is expected to see an "Icon not available" (as you do in HA Core).
This only applies to integrations.
