### ISSUE TITLE
Update Information functionality

### ISSUE THREAD

**Issue by niemyjski** [hacs/integration#1218]
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea
 I'm not sure what update information here does: 
![image](https://user-images.githubusercontent.com/1020579/82673552-abd83980-9c07-11ea-9651-aab31ecdda61.png). I'm assuming refreshes metadata, not sure that should be the first item?

Maybe we just refresh the repository data when you click on the information menu item?

**Comment by ludeeus** [comment]
> Maybe we just refresh the repository data when you click on the information menu item?

That is done as well (if needed), but users spam the update function when they have seen on the forum (or other places) that a repo they have has an update.
It can probably be moved to under "information" but it needs to be there.
