### ISSUE TITLE
Add ability to sort repositories in Add dialog

### ISSUE THREAD

**Issue by niemyjski** [hacs/integration#1219]
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea
The add dialog should be default sorted by most popular, with a dropdown for sorting by most downloaded, recently updated, name.

**Comment by ludeeus** [comment]
HACS only know about "installs" by looking at the download counter of the release assets that GitHub has in their API, there is a very small amount of repositories in HACS that uses it, for those that does not use it, the value of that counter will be 0.

Is that fair?

**Comment by GeorgeSG** [comment]
To avoid opening a duplicate, copying my take on this from #1194:

---

**Problem**: Sorting is gone. I think it was really useful for discovery purposes. For new users, it's useful to sort by stars - to quickly see the most popular repositories. There's good chance that these will be the best plugins.

For power users, it's really nice to be able to sort by new or recently updated, to see if anything new has appeared or something is updated and try it out.

**Suggestion**: Consider bringing back the sorting of available repositories.

---

@ludeeus, to answer your question, I think sorting by downloads is nice-to-have, definitely shouldn't be the default, and if implemented should come with `* - data not available for all repos`.

I think the default sort should be by stars.

@niemyjski, I suggest renaming the Issue to "Add ability to sort repositories in Add dialog".

**Comment by ludeeus** [comment]
I think sorting by downloads just adds confusion since very few repositories have that metric.

**Comment by niemyjski** [comment]
Then maybe by GitHub stars?
