### ISSUE TITLE
Show available repositories by default

### ISSUE THREAD

**Issue by GeorgeSG** [hacs/integration#1224]
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

Extracted from #1194

I don't know if that's true for most users, but my 2 main use cases for HACS are: 1. updating installed repositories (handled on the Home page), and 2. browsing/installing new repositories. 

Dedicating so much space for currently installed repositories looks good and is consistent with HA's Integrations page, but is less useful IMO.

## Implementation

Consider making the list of available repositories a first-level citizen instead of it being hidden in a popup. 

To me, the discovery/exploration part of HACS is the most-important use-case (both as a user and as a contributor). Seeing the list of your already installed repositories that don't even have an update is a secondary job IMO.

I would experiment with showing available repositories in each page and showing the installed ones in a popup.

## Alternative

Show all repositories in their respective pages. Group installed ones at the top, show all others after that. 

If there is search/filter/sort it can apply to all repositories per-group. E.g. if you sort by stars, it will first show the installed group sorted by stars, then the available group sorted by stars.

**Comment by DendelX** [comment]
For me the popup page to add new repositories is not very friendly either.  I cannot search for something that I do not know exists and that only shows 100 repositories is an error. For me it should be paginated. being able to spend time searching and gossiping for new ideas and repositories.

You cannot search for what you don't know that exists.

**Comment by GeorgeSG** [comment]
I think with all the improvements to the 1.0 UI in the past weeks, this is obsolete now. We have good options for sorting and seeing all available repositories in the popup and a lot of the issues with the popups have been resolved.

Closing this as I don't think it's relevant anymore.
