### ISSUE TITLE
Integration installation not accurately reflected in UI

### ISSUE THREAD

**Issue by tmchow** [hacs/integration#1228]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.0.1
| Home Assistant version     | 0.110.1
| Installation method for HA | HASS in Docker
| Web browser                | Chrome
| Web browser version        | 83.0.4103.61

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

After upgrading to 1.0 (and still persists in 1.0.1), integration installation status isn't accurately reflected in the HACS UI.  

For example, I have the "Mitsubishi Kumo" integration installed and it's functioning correctly since I have the new climate entities exposing my thermostat. However, in the HACS UI, look at the screenshots at end of bug report which shows the UI thinks it's not installed.

### Steps to reproduce

1. Update from 0.27 to 1.0 HACS with integrations already installed before the ugprade.
2.Install a new integration (like the Mitsubishi Kumo integration) by tapping "Install" on HACS frontend

Expected: Card shows proper installation state
Actual: Card behaves as if it's not installed.

### Screenshots

This is card state after the integration was installed:
![image](https://user-images.githubusercontent.com/517103/82709646-ea84e880-9c35-11ea-9c08-1d8eeb780436.png)

This shows the files are indeed installed:
![image](https://user-images.githubusercontent.com/517103/82709747-26b84900-9c36-11ea-8db5-2d8d5142a850.png)

This shows the entities created from the integration, so I know it's working:
![image](https://user-images.githubusercontent.com/517103/82709689-025c6c80-9c36-11ea-937d-64577002563c.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

https://paste.ee/p/PX26f
</details>

**Comment by aidbish** [comment]
Was the custom integration installed by HACS originally or manually?

**Comment by barto95100** [comment]
I have the same problem with the other card (Linky Card) HACS show me not installed but is OK in directory and lovelace

**Comment by aidbish** [comment]
> I have the same problem with the other card (Linky Card) HACS show me not installed but is OK in directory and lovelace

Was the custom integration installed by HACS originally or manually?

**Comment by ludeeus** [comment]
From your logs you did not install it (search for `[hacs] Running install for`) to see what you installed.
For the discovery of existing items see: https://hacs.xyz/docs/basic/existing_elements

**Comment by barto95100** [comment]
> > I have the same problem with the other card (Linky Card) HACS show me not installed but is OK in directory and lovelace
> 
> Was the custom integration installed by HACS originally or manually?

I add the repository on HACS Custom repository and installed with HACS:
![2020-05-23_11-54-32](https://user-images.githubusercontent.com/17863254/82727662-35f9ce00-9cec-11ea-9cd1-33e759942f83.png)

and 

![2020-05-23_11-55-11](https://user-images.githubusercontent.com/17863254/82727692-5a55aa80-9cec-11ea-9dbc-82b08b53801f.png)

in lovelace after add in custom this is work : 
![2020-05-23_11-56-20](https://user-images.githubusercontent.com/17863254/82727716-79ecd300-9cec-11ea-9957-c28f787e4219.png)

**Comment by ludeeus** [comment]
@barto95100 Then you have a different issue your backend is not saving the states, open a separate issue with the backend template, and provide debug logs of the installation process.

**Comment by tmchow** [comment]
> From your logs you did not install it (search for `[hacs] Running install for`) to see what you installed.
> For the discovery of existing items see: https://hacs.xyz/docs/basic/existing_elements

I did install the “Mitsubishi kumo” integration from the HACS dashboard. It’s in the file system and exposed the climate entities that otherwise wouldn’t be created without this integration. 

The integration definitely was NOT installed outside of HACS nor was it installed prior to the upgrade to HACS 1.0
