### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications

### ISSUE THREAD

**Issue by vlad36N** [hacs/integration#1229]
## Installation details

Environment

    Home Assistant Core release with the issue: Home Assistant 0.110.1
    Last working Home Assistant Core release (if known): Home Assistant 0.110
    Operating environment (Home Assistant/Supervised/Docker/venv):
    Firefox 76.0.1 (64-bit), Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)
    arch | x86_64
    dev | false
    docker | true
    hassio | true
    host_os | Ubuntu 18.04.4 LTS
    installation_type | Home Assistant Supervised
    os_name | Linux
    os_version | 4.15.0-99-generic
    python_version | 3.7.7
    supervisor | 222

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Log Details (ERROR)

Logger: frontend.js.latest.202005191
Source: components/system_log/init.py:209
First occurred: 6:28:43 PM (4 occurrences)
Last logged: 6:48:43 PM
:0:0 ResizeObserver loop completed with undelivered notifications.

### Steps to reproduce

1. 1. 1.

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

Log Details (ERROR)

Logger: frontend.js.latest.202005191
Source: components/system_log/init.py:209
First occurred: 5:57:10 PM (4 occurrences)
Last logged: 6:54:33 PM

https://xxxxx.xxxxxx.xxx/hacsfiles/frontend-20200522122100.js:1:0 NotSupportedError: CustomElementRegistry.define: 'hacs-frontendbase' has already been defined as a custom element
:0:0 ResizeObserver loop completed with undelivered notifications.

```

</details>

**Comment by ludeeus** [comment]
`'hacs-frontendbase' has already been defined as a custom element` You get this each time you update HACS, clearing the cache on the client solves it.
