### ISSUE TITLE
Problem with the logo HACS from the last actualization

### ISSUE THREAD

**Issue by brano1990** [hacs/integration#1230]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.0.1
| Home Assistant version     |0.110.1
| Installation method for HA |HassOS 3.13 PI4
| Web browser                |mobile and chrome
| Web browser version        |

## Checklist

- [x ] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x ] I have filled out the issue template to the best of my ability.
- [ x] I have read https://hacs.xyz/docs/issues
- [x ] This issue is related to the frontend of HACS.
- [x ] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

From the last actualization Home Assistant 0.110.1
a HACS 	1.0.1, I have the logo HACS on every screen .

### Screenshots

![problem pozadia](https://user-images.githubusercontent.com/59432151/82725758-7e5ebf00-9cdf-11ea-8276-b35e499c78bb.png)

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by GoSpursGoNL** [comment]
I notice the same thing. But only via the mobile Android app, not in Firefox.

**Comment by pove** [comment]
Same here. I have found this on the log:

`Logger: frontend.js.latest.202005191
Source: components/system_log/__init__.py:209
First occurred: 18:47:32 (1 occurrences)
Last logged: 18:47:32

https://xxxxxxx:yyyy/hacsfiles/frontend-20200522122100.js:1:17185 Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "hacs-frontendbase" has already been used with this registry`

**Comment by ludeeus** [comment]
Clear our browser cache and it goes away.

**Comment by GoSpursGoNL** [comment]
I cleared the cache for the entire HA Android app but that did not solve it.

**Comment by brano1990** [comment]
I deleted buffer memory in application android and chrome, and than it works. Thank you
