### ISSUE TITLE
Information Popups Overflow Offscreen

### ISSUE THREAD

**Issue by theaquarium** [hacs/integration#1235]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.0.1 |
| Home Assistant version     | 0.110.1 |
| Installation method for HA | Hass.io |
| Web browser                | Microsoft Edge for Windows |
| Web browser version        | 83.0.478.37 |

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

When you click the information button for a repository with long unbroken lines of text, the popup overflows to the left and is impossible to close because the close button is offscreen.

### Steps to reproduce

1. Open the information popup for a repository with a long unbroken lines.

### Screenshots

![image](https://user-images.githubusercontent.com/26528805/82732527-cd0a5a00-9cdb-11ea-8b40-fdddab4368a6.png)

## Javascript logs from your browser console

```text

```

**Comment by ludeeus** [comment]
Click the button to hide/show the sidebar
![image](https://user-images.githubusercontent.com/15093472/82732896-93a01180-9d10-11ea-9291-86e0d7ab74c5.png)

**Comment by theaquarium** [comment]
Ok, that does seem to fix it permanently. However, it should probably behave this way from the start.

**Comment by ludeeus** [comment]
yes, not sure why that value was not set in your browser, it's a default part of the layout HA uses.
