### ISSUE TITLE
Install button doesn't show in mobile view

### ISSUE THREAD

**Issue by rudizl** [hacs/integration#1236]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.0.1
| Home Assistant version     |0.110.1
| Installation method for HA |hass.io
| Web browser                |Samsung internet, Ms Edge for android, Home assistant app for android

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

There is no install button in Android HA app, nor in mobile view of my two browsers. In desktop view everything is OK. 

### Steps to reproduce

The screen shots are showing the issue. 

### Screenshots
![Screenshot_20200523-164700_Home Assistant](https://user-images.githubusercontent.com/5582186/82733788-23e55300-9d1f-11ea-8100-8f08937daa1b.jpg)
![Screenshot_20200523-164729_Samsung Internet](https://user-images.githubusercontent.com/5582186/82733796-2ba4f780-9d1f-11ea-9ad8-99ccf2e0695e.jpg)
![Screenshot_20200523-164810_Samsung Internet](https://user-images.githubusercontent.com/5582186/82733800-33649c00-9d1f-11ea-8e33-2f586a2769c7.jpg)

**Comment by samnewman86** [comment]
I also have the same issue

**Comment by titomontes** [comment]
+1
