### ISSUE TITLE
Hacs broken after upgrade

### ISSUE THREAD

**Issue by samnewman86** [hacs/integration#1238]
## Installation details

Using ha supervised

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.0
| Home Assistant version     | 110.1
| Installation method for HA | supervised

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A clear and concise description of what the issue is.

### Steps to reproduce

Error in log on startup, hacs is missing from the sidebar.

1. 1. 1.

## Debug logs

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```
Logger: hacs.data
Source: custom_components/hacs/hacsbase/data.py:139
First occurred: 19:26:03 (6 occurrences)
Last logged: 19:28:43

[[Errno 20] Not a directory: '/config/.storage/hacs/120370503.hacs'] Restore Failed!
</details>

**Comment by ludeeus** [comment]
You have permission / FS issues, delete the `/config/.storage/hacs` directory and it will be good.
