### ISSUE TITLE
Searching for plugin Cuts off the last one

### ISSUE THREAD

**Issue by fiservedpi** [hacs/integration#1242]
## Installation details

| Description                | when using search function the last entry is cut-off (on mobile) |
| -------------------------- | ----- |
| HACS version               |1.0.1

Integration version: | 1.0.1
-- | --
Frontend version: | 20200522122100

| Home Assistant version     |0.110.1
| Installation method for HA |

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
installation_type | Home Assistant Core on Docker
os_name | Linux
os_version | 4.19.107-Unraid
python_version | 3.7.7
timezone | America/New_York
version | 0.110.1
virtualenv | false

| Web browser                |chrome
| Web browser version        |83.0.410360

## Checklist

- [ ✓] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [ ✓] I have filled out the issue template to the best of my ability.
- [ ✓] I have read https://hacs.xyz/docs/issues
- [ ✓] This issue is related to the frontend of HACS.
- [✓ ] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

When searching for a repo the last entry gets cut off

### Steps to reproduce
Search for light plugin

1. 1. 1.

### Screenshots
![Screenshot_20200524-084604](https://user-images.githubusercontent.com/42981853/82754629-2fc32a80-9d9c-11ea-93d7-0a9a8b802c45.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```NA

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
Update to 1.0.2
