### ISSUE TITLE
add some kind of rating for available plugins/themes etc

### ISSUE THREAD

**Issue by RezzZ** [hacs/integration#1243]
- [X] Frontend

Can we get some kind of rating for the repos offered via HACS?
Right now it takes several click to to browse through eg, the available themes whitout any indication of a theme is 'loved' / popular.
Perhaps show the nr of stars a repository / plugin/theme has to show some kind of rating?
Or the nr installed via HACS plugin?

**Comment by ludeeus** [comment]
You already have that:
![image](https://user-images.githubusercontent.com/15093472/82755808-556d2580-9dd6-11ea-97da-58f40f7688e0.png)

**Comment by RezzZ** [comment]
@ludeeus sure, but only when you click a single item.

Now with the recently new layout as well, you can't see the actual stars a repository has. You can Sort on stars but the nr of stars is not displayed. Could be a nice addition to add imho.
