### ISSUE TITLE
Search could be improved

### ISSUE THREAD

**Issue by klejejs** [hacs/integration#1247]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.0.3
| Home Assistant version     |0.110
| Installation method for HA |Docker

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [ ] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Searching for integrations could be improved as currently searching "card tools" doesn't yield the wanted result and it is required to search for "card-tools". Maybe search should also look into readme files?

### Steps to reproduce
-

**Comment by ludeeus** [comment]
This is by design, and not an issue.
