### ISSUE TITLE
"New" repositories should not be in the "Installed" section

### ISSUE THREAD

**Issue by nikrolls** [hacs/integration#1249]
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

First off, I know that getting negativity about the new UI has been difficult. As an open-source maintainer I've been there, I know how hard it is, and I really don't want to pile on to that. I actually really like the new UI, you've done an excellent job. There's just this one thing which, from my experience working professionally in UX every day, is very much against good user experience principles. 

**"New" repositories should not be in the "Installed" section, because these are fundamentally different workflows.**

_As a user, when I want to manage my Installed repositories, I **never** want to see new ones, because that information is **irrelevant** at the time and just gets in the way._

_As a user, when I want to look for New repositories, I **never** want to see my installed ones, because that information is **irrelevant** at the time and just gets in the way._

The way things are done at the moment is conflating two completely different workflows which is a bad user experience. I know it was tweaked to sort new to the top (so new wasn't mixed in with the installed ones) but that's almost worse because now I need to scroll down past suggestions that are irrelevant to me to get manage my installed repositories.

I know that this is meant to mirror the "discovered integrations" functionality in HA Core, but there's a fundamental difference there: with discovered integrations, these are things _that I own_ and are _on my network_. With HACS new repositories, these are new integrations that 99% of the time I will never install. It would be like if HA core showed a discovered integration every time someone merged a new integration into the core repository even though I don't own the device. It's less equivalent to discovered integrations and much more equivalent to adverts in search results or news articles.

## Implementation

In my opinion, it would be a far better user experience to show new repositories at the top of the "Add repositories" list. This way you can easily see what's new, but use search to find what you're actually looking for.

## Alternatives

Another way to implement this, which would be a bit more work but would satisfy the people who requested enhanced visibility for new repositories (and likely led to New being displayed alongside Installed in the first place) would be to add a new section on the main HACS screen, above the Integrations section, called "New repositories". It could have the orange "notification dot" when there's anything there that you haven't seen. When you open it, it shows the 20 newest repositories, in two groups (Integrations and Frontend).

---
Keep up the good work, the new frontend is really going in the right direction overall.

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
