### ISSUE TITLE
Already removed integration generate Error message

### ISSUE THREAD

**Issue by Korte68** [hacs/integration#1257]
## Describe the issue

Old, already removed integration generate Error message.

Earlier I installed the surveillance-card integration.
Liter it became blacklisted, so I removed it.

But since that i receive Errors in the LOG:

hacs  Tried to serve up '/config/www/community/surveillance-card/surveillance-card.js' but it does not exist

**Comment by ludeeus** [comment]
This is not an issue, It's still in use on one of your clients, it might be cache.
_something_ is requesting that file.

**Comment by Korte68** [comment]
It has benn removed from the configuration as well

**Comment by PierreScerri** [comment]
But I'm getting this too, with 3 cards that I installed to try out and later removed.  So how can we find out what that _something_ is?

```
Logger: hacs
Source: custom_components/hacs/http.py:58
First occurred: 2:34:57 PM (5 occurrences)
Last logged: 2:39:11 PM

Tried to serve up '/config/www/community/button-text-card/button-text-card.js' but it does not exist
Tried to serve up '/config/www/community/simple-weather-card/simple-weather-card-bundle.js' but it does not exist
Tried to serve up '/config/www/community/custom-sidebar/custom-sidebar.js' but it does not exist
```
