### ISSUE TITLE
Make the "add" button context aware

### ISSUE THREAD

**Issue by finity69x2** [hacs/integration#1258]
## Category

- [ ] Backend/Integration
- [x ] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [ x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

When selecting the "add" button in the bottom right only show the corresponding functions depending on the tab that is selected.

## Implementation

For example, if I am on the integration tab then when I click the "add" button then only show a list of integrations in the pop up box.

This should also be combined with the request that the tabs for "frontend" be split between "plugins" and "themes" (FR for that to come)

Right now having them be all in one monolithic list is impossible to find sometrhing specific unless you already know what you are searching for.

The benefit of HACS has always been the ability to "window shop".

## Alternatives

Sorry, none I can think of.

**Comment by ludeeus** [comment]
This was changed in 1.0.1 (implemented here https://github.com/hacs/frontend/pull/143), try an upgrade.
