### ISSUE TITLE
Split tabs for "Frontend" to "Plugins" and "Themes"

### ISSUE THREAD

**Issue by finity69x2** [hacs/integration#1259]
## Category

- [ ] Backend/Integration
- [x ] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x ] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

Make the "Frontend" tab into two tabs - "Plugins" and "Themes"

## Implementation

Only one way that I know of.

## Alternatives

Sorry none I can think of with the limitations of the card view.

**Comment by firestrife23** [comment]
+1

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
