### ISSUE TITLE
scrolling the information screen after the title

### ISSUE THREAD

**Issue by MYLE-01** [hacs/integration#1261]
## Category

- [ ] Backend/Integration
- [ x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [ x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

could the information screen be a scrolling after the title bit
![image](https://user-images.githubusercontent.com/4362345/82840376-67f67480-9f26-11ea-806e-80bc88eb734a.png)

will just make easyer to close when finish reading it

**Comment by ludeeus** [comment]
Was implemented in https://github.com/hacs/frontend/pull/164, it's a part of the next release
