### ISSUE TITLE
Persistent HACS logo throughout HA

### ISSUE THREAD

**Issue by jibincj** [hacs/integration#1264]
I am getting a persistent HACS logo throughout HA at the bottom of any page. See attached screenshots. These are just two screens. But as I mentioned, its persistent throughout.

Configuration Page Screenshot:
![CONFIGURATION](https://user-images.githubusercontent.com/59428037/82903607-ce7b9280-9f26-11ea-9f56-052c0b60d16f.png)

Default View Screenshot:
![HOME](https://user-images.githubusercontent.com/59428037/82903609-cf142900-9f26-11ea-9d54-968775578c11.png)

Customizations running-
Custom Header - https://github.com/maykar/custom-header
iOS Dark Mode Theme - https://github.com/basnijholt/lovelace-ios-dark-mode-theme#ios-dark-mode-theme

**Comment by ludeeus** [comment]
Update HACS (that file was changed in 0.24.5) and clear cache.

**Comment by jibincj** [comment]
I am running HACS Integration version: 1.0.3.

Tried clearing Cache just now. it didn't help.

Persistent HACS logo started appearing after updating HA to 0.110.2 on 05/25 (yesterday)

**Comment by ludeeus** [comment]
Then you have not cleared the cache properly, that icon as shown here does not exist in current versions of HACS.

**Comment by djryan012** [comment]
Will Confirm that I had the same problem and clearing browser cache resolved rendering issues
