### ISSUE TITLE
Add tabs in the Add section : when Theme selected it shows only the list of themes 

### ISSUE THREAD

**Issue by sky-future** [hacs/integration#1266]
## Category

- [ ] Backend/Integration
- [ ] Frontend
- [ ] Documentation
- [ ] Bot
- [x] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

When you go to the Add section. There should be some tags (Themes, Plugins, Integrations, Cards ...). 

When you shose one of this tags it shows only the elements related to it. 

This allows users to look in the list and have an idea of what is available and can find some interesting stuff like this... 

Otherwise like now you have to know the name of what you are looking for... 

## Implementation

How do you see this beeing implemented?

## Alternatives

Are there any alternative solutions or features you've considered?

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/82923474-525f6a00-9f7b-11ea-94e0-6025df1b8e72.png)
That is already there...

**Comment by sky-future** [comment]
Yes but it shows everithing mixed. For example when you click on integration it should show only Integration elements.

**Comment by ludeeus** [comment]
It does that already...
Update HACS and clear your browser cache.

**Comment by sky-future** [comment]
Indeed, I was clicking on the tab, not putting the name of the tab in the search bar. I will delete my post thanks.
