### ISSUE TITLE
"User input malformed" error when submitting integration options

### ISSUE THREAD

**Issue by sockmonkey0223** [hacs/integration#1271]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.03|
| Home Assistant version     |0.110.3|
| Installation method for HA |HA Image / RasPi|

## Checklist

- [ X] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [X ] I have enabled debug logging for my installation.
- [X ] I have filled out the issue template to the best of my ability.
- [X ] I have read https://hacs.xyz/docs/issues
- [X ] This issue is related to the backend of HACS.
- [X ] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Cannot change any integration options for HACS. When clicking submit, receive "User input malformed" error.

### Steps to reproduce

1) Navigate: HA Configuration --> Integrations --> HACS card --> Options
2) Change any value (or don't) and click "submit".

Current values
Side panel title:  
Side panel icon: 
Number of releases to show: 5
Filter with country code: ALL
Enable AppDaemon apps discovery & tracking: unchecked
Enable NetDaemon apps discovery & tracking: unchecked
Enable debug: checked
Enable experimental features: checked

1. 1. 1.

## Debug logs

<details>
  <summary>Logs</summary>

```text

None generated around this error

```

</details>

**Comment by ludeeus** [comment]
Can not be reproduced anymore, probably solved in master

**Comment by sockmonkey0223** [comment]
Updated to 1.1.0, problem still reproduceable.

**Comment by sockmonkey0223** [comment]
Deleted and reinstalled HACS - issue resolved.

**Comment by drogfild** [comment]
Bumped into this one. Version 1.1.2 with HA 0.111.4

Anything I could/should try to debug or just reinstall HACS?

**Comment by nathan-sav** [comment]
I also ran into this on 1.1.2 was able to fix it by settings and unsetting netdaemon support. Looks like the default value is set to null rather than false, which results in a 400 error from the backend (and no errors logged).

**Comment by drogfild** [comment]
I didn't find a setting that would let me proceed. I already did deleted hacs (from integrations) and reinstalled it. Now it works.

**Comment by flozsc** [comment]
> I also ran into this on 1.1.2 was able to fix it by settings and unsetting netdaemon support. Looks like the default value is set to null rather than false, which results in a 400 error from the backend (and no errors logged).

Thanks! Solved it by checking everything and entering values in all text boxes. Then I could save and also disable everything that I don't need again.

**Comment by ricricucit** [comment]
solved it, but still not showing HACS in side panel...
