### ISSUE TITLE
Failed to load SourceMap: ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by chemelli74** [hacs/integration#1274]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.0.3
| Home Assistant version     | 0.110.3
| Installation method for HA | Docker
| Web browser                | Windows 10 Chromium
| Web browser version        | Version 83.0.478.37 (Official build) (64-bit)

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Error logged while debugging with Chromium

### Steps to reproduce

1. Open HA with Chromium Windows 10
2. Open browser debug (F12)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text
DevTools failed to load SourceMap: Could not load content for https://nas.homechemelli.com:8424/hacsfiles/bar-card/index.m.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

</details>

**Comment by ludeeus** [comment]
You need to report that to the developer of that card.

**Comment by chemelli74** [comment]
Sorry, didn't see the name of the card in the log. Need more coffe this morning.

Simone
