### ISSUE TITLE
Filter and Sort of Integration and Frontend Cards

### ISSUE THREAD

**Issue by dkebler** [hacs/integration#1276]
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

bunch of folks didn't like the ui change #1239.  To me it's fine it just needs a way to filter and sort  .  As it is it's kinda difficult to use and as more packages are added it's going to become untenable without some db like filtering and sorting. 

Possible Filters

* installed/not installed/all
* release/update since (have a default date like two weeks ago)
* new to hacs 
* by name(partial)  (glob or regex)

Possible Sorts (should allow multiple sorts

* Alpha (already done)
* installed/not-installed  (would allow installed to top)
* by latest release

Filters and sorts should be combinable

## Implementation

How do you see this being implemented?  

I don't know how HACs establishes a db for all the repos but I assume it's some kind of db that can be filtered and sorted

the ui for that could be in a popup called via the hamburger (three dots, upper right) or via a accordion like expanding dropdown like I have in one of my UI designs

![image](https://user-images.githubusercontent.com/1316185/83283774-94152e00-a190-11ea-85f0-0d7a35b6dbc0.png)

**Comment by GeorgeSG** [comment]
I'm adding search in this [PR](https://github.com/hacs/frontend/pull/171).

As far as filters - maybe later down the road :)

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905

**Comment by ludeeus** [comment]
Filter and sort was implemented a long time ago
