### ISSUE TITLE
Information from hacs.json is not refreshed in HACS (Custom respository)

### ISSUE THREAD

**Issue by jbouwh** [hacs/integration#1278]
## Installation details
I have made an automation for AppDaemon that can be added as custom respository:
[](https://github.com/jbouwh/omnikdatalogger)
I install it as custom respository and followed all steps. The install is successful.

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.0.3
| Home Assistant version     | 0.110.4
| Installation method for HA | Image for RPI3

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

### Background
At first I only supplied a name and the parameter to parse README.md.
Later I changed hacs.json ('name' and 'render_readme') so it should render INFO.md, and change te title to the new name.

### Problem
The name is not changed. README.md is still parsed, while this should be changed to INFO.MD. In some way the old hacs.json is still cached and used.
I have tried:
* Removing the custom repository, and add it again
* Using the context option `Update information` at the item.
* Reload window
* Creating a new release
* Wait a full day

### Steps to reproduce
* Add a custom repository to HACS.
* Install the integration.
* Update the hacs.json
* Do everyting I described above to make the repository information from hacs.json to be re-read.

1. 1. 1.

## Debug logs

<details>
  <summary>Logs</summary>

```text
DEBUG LOG WILL BE ADDED AS FILE
```

</details>

**Comment by jbouwh** [comment]
[home-assistant.log](https://github.com/hacs/integration/files/4706856/home-assistant.log)

**Comment by ludeeus** [comment]
HACS fetches files for the latest version <https://github.com/jbouwh/omnikdatalogger/blob/v0.93-beta/hacs.json> which does not contain the changes you are talking about.
Your changes were done in the default branch 22h ago, you need to cut a new release for HACS to see those changes.

**Comment by jbouwh** [comment]
A new release solved my problem, thank you.
