### ISSUE TITLE
Linux Command Line Install : mkdir: cannot create directory ‘custom_components’: Permission denied

### ISSUE THREAD

**Issue by nodecentral** [hacs/integration#1279]
Hi,

I’m following the guide to install HACS via the linux command line, (https://hacs.xyz/docs/installation/manual_cli ) but I’m unable to progress because of the following error..
```
homeassistant@debian-NR:~$ sudo curl -sfSL https://hacs.xyz/install | bash -
Trying to find the correct directory
Changing directory to /usr/share/hassio/homeassistant
Creating custom_components directory
mkdir: cannot create directory ‘custom_components’: Permission denied
Changing to the custom_components directory
bash: line 49: cd: custom_components: No such file or directory
homeassistant@debian-NR:~$
```

I’ve tried it with and without sudo, but I get the same message - any ideas what might be causing the issue and how to fix it ?

**Comment by ludeeus** [comment]
You are running a supervised installation.
change to the user running that suite, or use one of the SSH addons.
