### ISSUE TITLE
Lost the Lovelace menu bar

### ISSUE THREAD

**Issue by Korte68** [hacs/integration#1280]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.0.3
| Home Assistant version     |0.110.4
| Installation method for HA |Docker

## Checklist

- [x ] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [ x] I have enabled debug logging for my installation.
- [ x] I have filled out the issue template to the best of my ability.
- [x ] I have read https://hacs.xyz/docs/issues
- [x ] This issue is related to the backend of HACS.
- [ x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

After updating the HA and the HACS the lovelace menu bar disappeared.

I found the problem is with the Lovelace_resource file.

the url has changed to : "/hacsfiles/...."
If a changed back to : "/community_plugins/..." the menu came back again

### Steps to reproduce

1. 1. 1.

## Debug logs

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
Your custom header is outdated

**Comment by Korte68** [comment]
HACS should update it.. but not

**Comment by Korte68** [comment]
did not find custom header in the HACS
