### ISSUE TITLE
opt-in to get old layout back

### ISSUE THREAD

**Issue by prankousky** [hacs/integration#1285]
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

It would be nice to get the old layout back, for those reasons:

1. the old layout offered a wider overview of all integrations
2. (unless I have missed it) the new layout does not have an option to **update all** integrations with available updates at once.
3. it seems to me like the old layout would load considerably faster than the new layout

## Implementation

on/off toggle for old/new layout

## Alternatives

None that I can think off.

I really love HACS, but the old layout made things much easier in my personal opinion. Would it be possible to get that layout back somehow? Thank you for your great work :)

**Comment by ludeeus** [comment]
Download the old version here: <https://github.com/hacs/integration/releases/tag/0.24.5>
Other than that, no. 
ref: https://github.com/hacs/integration/pull/1227
