### ISSUE TITLE
Unable to remove HACS after loading a Snapshot on a brand new HA

### ISSUE THREAD

**Issue by Knot83** [hacs/integration#1295]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version        |   0.17.4 
| Home Assistant version     | 0.110.4
| Installation method for HA | As an image for your device (no Raspbian, no Docker)
| Raspberry version | 3 Model B+

## Checklist

- [] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I've installed a brand new Homeassistant and reloaded a previous Snapshot where I had HACS (version 0.17.4 based on what I read in hacs/const.py) . Since it's providing the following error (see log below) I tried to remove HACS following the official documentation (https://hacs.xyz/docs/installation/remove) in order to later install the latest HACS version (1.0.3) compatible with Home Assistant 0.110.4. 

But unfortunatelly I'm not able to remove HACS from the Integration page of HA. Also clicking on Delete it still remain there.

### Steps to reproduce

1) Load an old Snapshot on Homeassistant  0.110.4
2) Removed the configuration from configuration.yaml 
3) Tried to delete HACS from Integration webpage of HA (it was not possible)
4) Restart HA two times
5) Delete the hacs directory under custom_components.
6) Delete all files and directories containing hacs under the .storage directory.
7) Restart HA

## Debug logs

<details>
  <summary>Logs</summary>

```text

2020-06-04 16:41:36 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration hacs - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 50, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 129, in _async_setup_component
    await async_process_deps_reqs(hass, config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 298, in async_process_deps_reqs
    hass, integration.domain
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 78, in async_get_integration_with_requirements
    hass, integration.domain, integration.requirements
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 124, in async_process_requirements
    if pkg_util.is_installed(req):
  File "/usr/src/homeassistant/homeassistant/util/package.py", line 44, in is_installed
    return version(req.project_name) in req
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3145, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 703, in contains
    item = parse(item)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 31, in parse
    return Version(version)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

```

</details>

**Comment by Knot83** [comment]
As per my description I'm not running in docker. I've a `deps` dir in my config folder although it's empty. 

Instead of removing HACS what's the correct procedure to upgrade it while in my situation? I'd like to have HACS working

**Comment by ludeeus** [comment]
Do a regular installation of it

**Comment by Knot83** [comment]
In the regular installation there's a step to add HACS in the Integration page where I've already it. Shall I try to leave it as it is?

**Comment by ludeeus** [comment]
Yes

**Comment by Knot83** [comment]
I did try to delete the old hacs folder and add the newest 1.0.3 version but HA performances become worst (no able to check configuration, restart very slow) as well as HACS doesn't appear in the left bar. 
In the integration page the `hacs` entity status is having an exlamation point saying Restored. 

Can you please route me in a definitive way to remove HACS at all since it's causing me several troubles?

**Comment by ludeeus** [comment]
https://hacs.xyz/docs/installation/remove

**Comment by Knot83** [comment]
OK done this procedure also two times as explained in that webpage but I still see the HACS under the Integration of HA GUI. I tried to remove it from its option the second time since I had already removed `hacs:` from configuration.yaml during the first attempt but it doesn't appear. I've also tried to cancel my Chrome cache. Nothing.

Now I've also the following error in the HA log:

`Error (Main Thread) [homeassistant.setup] Setup failed for hacs: Integration not found.`

Please help me, I need to remove it.

**Comment by ludeeus** [comment]
You need to set it up before  you can remove it
or upgrade to the current HA beta.

**Comment by Knot83** [comment]
In a couple of comments back I said I tried to set it up with newest 1.0.3 but it doesn't work.  I think we're turning around the problem, without having a clear direction of what to do.

I was enough clear on my problem description and I'm not getting a clear direction on how to remove definitively HACS from my environment. The question is: Why I'm not able to remove it from the Integration page of HA? Being the developer you shall have an alternative way to do that.

**Comment by ludeeus** [comment]
Currently removing it there, require it to be set up correctly.
That changes in HA 0.111 which are in beta ATM.
**before** HACS is set up, there is **nothing** that can be done from HACS.

**Comment by Knot83** [comment]
Why are you mentioning HA 0.111? I'm in 0.110.4. Are you suggesting me to wait the upcoming stable version? or try with the Beta (never done before) ?

**Comment by ludeeus** [comment]
I'm mentioning that because that version add that possibility.
What you decide to do is up to you 🤷

**Comment by Knot83** [comment]
What possibility? To remove it also without being correctly setup?

**Comment by ludeeus** [comment]
yes

**Comment by Knot83** [comment]
OK therefore I'll wait the next stable HA release
