### ISSUE TITLE
HACS Does not Acquire/Display custom-cards whose .js is found in github "/releases" Directories

### ISSUE THREAD

**Issue by kaijk** [hacs/integration#1297]
Installation details
| Description                        | Value |
| HACS version                     | 1.0.3
| Home Assistant Core version      | 0.110.4
| Installation method for HA | Raspbian in Docker
This is a new installation of HA/HACS. However, the the cards above appear in my production version of HACS on Homeassistant on a RasPi with HA Supervised OS running the same HA/HACS versions and current Supervisor and HASSOS versions.  So, I only see the issue in the Docker installation. My docker-compose script is attached.
[docker-compose.txt](https://github.com/hacs/integration/files/4732317/docker-compose.txt)

HACS has been installed for about 24 hours now.

Note: the decluttering-card (which has a different .js file location in github) is listed in HACS and I successfully installed it into the www/community directory as expected.
## Checklist
- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue
A clear and concise description of what the issue is.
With this installation method, HACS fails to acquire/list custom-cards whose .js files reside in "./releases" directories, like:
`https://github.com/custom-cards/canvas-gauge-card/releases` and 
`https://github.com/custom-cards/button-card/releases`.
These and other similar cards have been long-known to HACS and their github file structures do not appear to have recently changed.  HACS just can't seem to find them with this HA/HACS installation method.

### Steps to reproduce
Install/upgrade HACS, navigate to Frontend. Note that almost all of the cards shown are theme cards. Note that the two cards referenced above do not appear in the list.

## Debug logs
```text
See Attached Log 
file (Log is too long to embed).
```
[logdata.txt](https://github.com/hacs/integration/files/4732321/logdata.txt)

</details>

**Comment by ludeeus** [comment]
Tha is not true.
![image](https://user-images.githubusercontent.com/15093472/83802715-9228fe80-a6ab-11ea-9e9c-3d63cc0d63eb.png)
![image](https://user-images.githubusercontent.com/15093472/83802723-948b5880-a6ab-11ea-89be-b333c8f6ffc1.png)

**Comment by kaijk** [comment]
OK, I"d assumed every custom-card would be a "new" repository on a new HACS
/ HA installation and would show up in that card-view collection.  The
subject cards didn't show up in the card view collection of "new" Front End
repositories (and that's where I thought I could add them and where I
focused initially till now). I just now dismissed all "new" cards and hit
[+] to add a card, Yes, they're there below the [+] in the list view.  I
guess the issue is not quite as I thought.
