### ISSUE TITLE
Header group

### ISSUE THREAD

**Issue by EvertJob** [hacs/integration#1300]
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

Giving the header-group a fixed position so we don't need to scroll up the close a modal window. Maybe a simple idea but very useful!

## Implementation

Set a fixed position in the `header-group` section in the css files

**Comment by ludeeus** [comment]
This is already the case.
![2020-06-05_13-21-28](https://user-images.githubusercontent.com/15093472/83870987-7ff0a400-a72f-11ea-952b-affba9129650.gif)

**Comment by EvertJob** [comment]
That It should be a bug reporting because this is not working on Safari.
