### ISSUE TITLE
Side panel icon is missing after update 

### ISSUE THREAD

**Issue by Madman833** [hacs/integration#1301]
## Installation details

| Description                | Value |
| I have updated to the lates version of HASSIO and for the latest version of OS syetem as well, than to the latest version of HACS| ----- |
| HACS version   1.0.3            |
|Home Assistant version 0.110.4     |
| Started the update from the HACS application |

## Checklist

- [ x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [ x] I have enabled debug logging for my installation.
- [ x] I have filled out the issue template to the best of my ability.
- [ x] I have read https://hacs.xyz/docs/issues
- [ x] This issue is related to the backend of HACS.
- [ x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A clear and concise description of what the issue is.

### Steps to reproduce

1. 1. 1.

## Debug logs

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
Clear your browser cache.
