### ISSUE TITLE
HACS showing error on HA reboot

### ISSUE THREAD

**Issue by daconrad0** [hacs/integration#1304]
![2A2ED9FC-1B5C-404E-A4DD-9B610B78CE08](https://user-images.githubusercontent.com/48894833/83953314-89503e00-a80d-11ea-90be-7fd66bee9eb5.png)

## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 202005242033
| Home Assistant version     | 0.110.5
| Installation method for HA | Integration

![052FDFC9-0509-4263-B1F4-F5A3DAE98090](https://user-images.githubusercontent.com/48894833/83953543-0a5c0500-a80f-11ea-8866-e4c81b8ade66.png)

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A clear and concise description of what the issue is.  After I upgrade to 0.110.5, HACS not longer loads.  I have attached the log file with the exception.

### Steps to reproduce

I can reproduce on a reboot.  Before no issues were experienced with HACS.

## Debug logs

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by daconrad0** [comment]
I submitted this to HA and they said it is an HACS issue.  Can someone give me thought on who can address this issue.

https://github.com/home-assistant/core/issues/36513

**Comment by Adminiuga** [comment]
1. if you rollback to 0.110.4, does the issue persist?
2. seems like camera integration setup is failing too, are you sure the exception you provided is related to hacs and not camera?
3. see https://www.home-assistant.io/integrations/logger/ and enable logging for `custom_components.hacs: debug`
restart and provide logs. 
There were only three PRs in https://www.home-assistant.io/blog/2020/05/20/release-110/#release-01105---june-5

**Comment by daconrad0** [comment]
Thanks
