### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by foXaCe** [hacs/integration#1309]
Hello,

is it possible to update the french translation please ?

**Comment by ludeeus** [comment]
Only reviewed keys are downloaded, what is your lokalise user so I can give you that role?

**Comment by foXaCe** [comment]
my name on lokalise is Stéphane Chabrol

**Comment by ludeeus** [comment]
You already have a reviewer role there.
I see that you also have reviewed all of them 👍 
They will be a part of the next frontend build.
