### ISSUE TITLE
Make close (X) icon always visible on Information modal window

### ISSUE THREAD

**Issue by DenisBY** [hacs/integration#1316]
## Category

- [X] Frontend

## Checklist

- [X] This Feature Request only contain 1 request

## The idea

On INFORMATION page of i.e. 'Integration' or 'Frontend' if you scroll down, an icon X to close modal window also scrolls up and you have to scroll to the top to close that window.

## Implementation

It would be nice to have a header with X always visible so you can close if at any time.

**Comment by ludeeus** [comment]
That is already the case...
![2020-06-08_10-25-13](https://user-images.githubusercontent.com/15093472/84008593-5d9a9880-a972-11ea-81e3-376cf7b326a5.gif)

**Comment by DenisBY** [comment]
It doesn't work for me. I have HACS 1.1.0. let me create a video.

**Comment by ludeeus** [comment]
if it does not work, open a frontend issue
