### ISSUE TITLE
X icon on INFORMATION modal windows scrolls with content in Firefox

### ISSUE THREAD

**Issue by DenisBY** [hacs/integration#1317]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.1.0 |
| Home Assistant version     | 0.110.5|
| Installation method for HA | Docker |
| Web browser                | Firefox |
| Web browser version        | 77.0.1|

## Checklist

- [ ] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read https://hacs.xyz/docs/issues
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

X icon on INFORMATION modal windows scrolls with content but according to  #1316 it should be always visible. In Chrome it works as expected.

### Steps to reproduce

Have HACS 1.1.0 installed and open any INFO page in Firefox

### Screenshots

![vokoscreen-2020-06-08_10-43-42](https://user-images.githubusercontent.com/1147703/84010656-4315ee80-a975-11ea-8337-9042a9678696.gif)

**Comment by ludeeus** [comment]
That is not the latest version of the frontend, clear your cache.

**Comment by DenisBY** [comment]
Now it works, thanks.
