### ISSUE TITLE
install to async_install

### ISSUE THREAD

**Issue by andriej** [hacs/integration#1320]
## Installation details

Integration version: | 1.1.0
-- | --
Frontend version: | 202006071141
Repozytoria: | 630
Installed repositories: | 21

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

While trying to install i.e. mini media player error is shown in logs.
![image](https://user-images.githubusercontent.com/6303489/84166647-7344b680-aa75-11ea-86b6-e8973b0a14c4.png)

## Debug logs

<details>
  <summary>Logs</summary>

```text

Logger: hacs.repository.plugin.kalkih.mini-media-player
Source: custom_components/hacs/repositories/helpers/methods/installation.py:17
First occurred: 17:17:05 (1 occurrences)
Last logged: 17:17:05

'install' is deprecated, use 'async_install' instead

```

</details>

**Comment by skank01** [comment]
Having the issue too with weather card and check button card
