### ISSUE TITLE
Easier access to custom repositories configuration

### ISSUE THREAD

**Issue by royto** [hacs/integration#1321]
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

In my opinion, custom repositories configuration is harder to find with new UI.

## Implementation

Add a new section in the HACS home page for settings like we have in HA

![image](https://user-images.githubusercontent.com/6990995/84192650-9766be80-aa9a-11ea-85a9-3f775fdd148a.png)

**Comment by ludeeus** [comment]
I do not agree at all with this.
How often are you changing out custom repositories?

**Comment by royto** [comment]
I have several custom repos set.

I think most people don't know about this and this way it could be known ...

I have a custom integration that I have not yet put on default repository and i ask people to add it using this feature ...

**Comment by ludeeus** [comment]
Sure you have them set, that's what is there for.
But how often do you change them?

**Comment by royto** [comment]
Not so often I admit.

But to me, it is not a reason to not add it to home page.

As a comparison, in the ha configuration panel, there are some entry I don't go often too and some never ( areas, zones, people, . .) But there are present to be find quickly and be known that it is configurable ...

**Comment by rccoleman** [comment]
The current method directly mirrors the way that addon repos are added to the Supervisor, so there is some consistency there.  I don't add custom repos to either very often, but it does seem a bit hidden away when one needs to add something.

**Comment by royto** [comment]
In supervisor, this is done like this but there is no home page in supervisor. You directly arrive on a tab. 

Then this menu is only accessible from add-on store tab. It make sense as it is only useful for add-ons.

Here it is a bit different as custom repositories apllies for multiple types ...

**Comment by jspanitz** [comment]
Literally just spent nearly 30 minutes looking for this in the new UI.  Obviously made my way here to file a bug report and then found out it was intentional.  :(  100% voice my support to making this more intuitive / easier to find.

**Comment by anyuta1166** [comment]
> Literally just spent nearly 30 minutes looking for this in the new UI.

The same thing. I was forced to update from old good HACS 0.24.5 to the latest version after upgrading Home Assistant to 0.115, because 0.24.5 stopped working after HA upgrade. And I even thought that the ability to add a custom repository was completely removed until I occasionally found it deeper in the menu.

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
