### ISSUE TITLE
Bot checking wrong repository

### ISSUE THREAD

**Issue by alryaz** [hacs/integration#1323]
## Describe the issue

I tried to re-open my pull request (https://github.com/hacs/default/pull/503), and then I see that the bot is checking some completely unrelated repository.
Is this a known issue?

The direct URL for bot's comment is: https://github.com/hacs/default/pull/503#issuecomment-641863359

The bot started checking `nitobuendia/oura-custom-component`, whereas I am submitting `alryaz/hass-hekr-component`.

**Comment by ludeeus** [comment]
Your branch is outdated.
You need to rebase it.
