### ISSUE TITLE
Some parts of HACS icon appear in Lovelace

### ISSUE THREAD

**Issue by Wagoneermaster007** [hacs/integration#1327]
Since I have updated HACS to version 1.0.0, I have experienced some parts of the HACS logo to appear in the background of the frontend (Lovelace).
![image](https://user-images.githubusercontent.com/59421784/84351901-92019500-abbc-11ea-86f0-6a83a641276f.png)
I have cleared the cache several times, many restarts etc, but somehow I can't get rid of it. Also in version 1.1.0. the background shows the part of the logo.
It had been worse (showing on all the dashboard pages as well, but those are now ok), but in the HACS menu, this is the only logo part left.

Any suggestions on how to get rid of it?

**Comment by ludeeus** [comment]
This started when you upgraded HA to 0.110+ not HACS to 1.0.0 (that part does not exist in HACS 0.24.5+) ;)

Clear your browser cache to solve it.
