### ISSUE TITLE
Hacs/Integrations - NO Plugins (hass RPi)

### ISSUE THREAD

**Issue by ZXant** [hacs/integration#1329]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.1.0
| Home Assistant version     | 0.110.4
| Installation method for HA | RPi env

## Checklist

- [X] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read https://hacs.xyz/docs/issues
- [X] This issue is related to the backend of HACS.
- [X] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

There is no Plugins inside Tab Integrations, but integrations per se. Trying to find "Mini-Media-Player", but does not show-up.

Other Tabs are Frontend and Automation.

### Steps to reproduce

Installed HACS twice, at same behaviour. 

Click HACS side menu, takes to HACS window with Integrations/Frontend/Automation Tabs.
Inside Integrations Tab, click the "plus" icon lower-right corner, which opens a pop-up with all Integrations, but no plugins.

1. 1. 1.

## Debug logs

Debug Log is enable, but no issues.

**Comment by ludeeus** [comment]
Plugins are frontend

**Comment by ZXant** [comment]
ludeeus

Thanks for the prompt reply, and apologies if Backend/Fronted mix.

Searched everywhere (I'm probably missing something basic), but Plugins don't show anywhere...

- Tab Integrations: shows Integrations
- Tab FrontEnd: shows Lovelace, Theme
- Automation: shows AppDaemon, NetDaemon

No Plugins, no Mini-Media-Player or other.

Thx,
Xant

**Comment by ludeeus** [comment]
Lovelace  is the new name for Plugins

**Comment by ZXant** [comment]
Apologies as I just started with HA, and thought something in this line... (although, the Gif animation on HACS main GitHub page, shows Plugins, which may lead to mix path...).

So, for clarification:

1) There is NO longer "plugins", but "Lovelace"
2) Mini-Media-Player - which also shows in the Gif animation - no longer listed in HACS (as it didn't shows-up in any Tab)

Best,
Xant
