### ISSUE TITLE
Hacs UI is not loaded

### ISSUE THREAD

**Issue by ocalvo** [hacs/integration#1330]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.1.0
| Home Assistant version     | 0.110.7
| Installation method for HA | hassio
| Web browser                | Edge Chromium
| Web browser version        |

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue
UI appears wrong and displays an error, it started happening after last update.

### Steps to reproduce

1. Install latest HACS
2. Open the HACS ui on the sidebar

### Screenshots
![image](https://user-images.githubusercontent.com/2091582/84444864-8d0e0700-abf7-11ea-8021-bc824a5986f7.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

Logs appear empty in the Console

```

</details>

**Comment by ludeeus** [comment]
https://hacs.xyz/docs/faq/status_not_loaded
