### ISSUE TITLE
Alternate y-axis card issue

### ISSUE THREAD

**Issue by FabioWielewski** [hacs/integration#1331]
| HACS version               | 1.1.0
| Home Assistant version     | 0111.0
| Installation method for HA | Docker

## Describe the issue

I realized that when applying the card, the first graphic referring to Água da Caixa, does not match the official graphic of the Home Assistant nor the separate mini-card, I realized that if I change any of the 2 Externa Caixa Dagua, Caixa Dagua roof it will have the same wrong graphic as Água da Caixa, am I doing something wrong or is there a problem?

entities:
  - entity: sensor.temperatura_da_caixa_dagua
    name: Água da Caixa
  - entity: sensor.temperatura_externa_caixa_dagua
    name: Externa Caixa Dagua
  - entity: sensor.temperatura_do_telhado_caixa_dagua
    name: Telhado Caixa Dagua
  - color: gray
    entity: input_number.nighttime
    name: Night
    show_legend: false
    show_line: false
    show_points: false
    y_axis: secondary
hours_to_show: 24
points_per_hour: 5
show:
  labels: true
  labels_secondary: true
type: 'custom:mini-graph-card'

**Comment by ludeeus** [comment]
This is the issue tracker for HACS, anything you install with HACS is not a part of HACS, they have their own issue trackers.
