### ISSUE TITLE
HACS removing wrong entry in Lovelace resources

### ISSUE THREAD

**Issue by PeeVv** [hacs/integration#1333]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |  1.1.0
| Home Assistant version     | 0.111.2
| Installation method for HA | Hass.io on Docker

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

When uninstalling a repository in HACS it removes entries from the Lovelace sources that do not belong to the uninstalled repository.

### Steps to reproduce

1. Installing e.g. slider-entity-row
2. I'm in Lovelace storage mode, so i add /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js as Lovelace resource
3. Uninstall slider-entity-row
4. In my case /hacsfiles/spotify-card/spotify-card.js is removed as Lovelace resource, /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js remains.

## Debug logs

<details>
  <summary>Logs</summary>

```text

2020-06-13 22:37:14 DEBUG (MainThread) [hacs] Running uninstall for thomasloven/lovelace-slider-entity-row
2020-06-13 22:37:14 INFO (MainThread) [hacs.repository.plugin.thomasloven.lovelace-slider-entity-row] Uninstalling
2020-06-13 22:37:14 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-slider-entity-row] Removing /config/www/community/lovelace-slider-entity-row
2020-06-13 22:37:14 DEBUG (MainThread) [hacs.data] Saving data

```

</details>

**Comment by tborychowski** [comment]
having the same issue.
Also - sometimes after I uninstall a front-end plugin - another plugin shows an error saying it has not been added to the lovelace.

**Comment by Larx** [comment]
Same here. Reproducable HACS removes simple-graph.js from lovelace when I uninstall lovelace-swipe-navigation.js?!?

**Comment by Dimand** [comment]
Also seeing weird things with Lovelace resources. Installing some things is fine but others need to be added manually.

**Comment by turbo4door** [comment]
Same issue here as well on 111.4. Started after most recent HACS update. Incredibly frustrating.
Removing Bar Card has removed either Atomic Calendar, Custom Header, or Battery card for me every time I try to remove it.

**Comment by ThomasPrior** [comment]
Replicated this issue in HACS 1.1.2

Environment: 
```
arch | x86_64
-- | --
dev | false
docker | false
hassio | false
installation_type | Home Assistant Core
os_name | Linux
os_version | 4.19.0-9-amd64
python_version | 3.8.3
timezone | Europe/London
version | 0.111.4
virtualenv | true
```

Steps to reproduce:


Action: Removed all lovelace plugins
Action: Installed calendar card
  Result: Resource not added to lovelace
Action: Installed vacuum card, not added to lovelace
  Result: Resource not added to lovelace
Action: Added /hacsfiles/calendar-card/calendar-card.js manually in Lovelace Resources
  Result: Calendar Card now shows up in Lovelace view
Action: Added /hacsfiles/vacuum-card/vacuum-card.js manually in Lovelace Resources
  Result: Vacuum card now shows up in Lovelace view
Action: Uninstalled Calendar Card via Hacs > Frontend > Calendar Card > Uninstall
  Result: Vacuum card automatically removed from Lovelace resources 

Debug logs: Too large to paste in a comment, attached below.
![image](https://user-images.githubusercontent.com/34111848/85954167-6bd64600-b96d-11ea-8347-5c2452946f4d.png)

[hacs_debug.txt](https://github.com/hacs/integration/files/4842718/hacs_debug.txt)
