### ISSUE TITLE
HACS icon on left sidebar sometimes doesn't appear/is blank

### ISSUE THREAD

**Issue by rccoleman** [hacs/integration#1336]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.1.0
| Home Assistant version     | 0.111.2
| Installation method for HA | Ubuntu KVM/HassOS
| Web browser                | Chrome on MacOS
| Web browser version        | 83.xxx

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Sometimes the HACS icon on the left sidebar doesn't show up, and there's only a blank space there.  I can click on it and HACS loads, so it's just a problem with the icon on the sidebar.

### Steps to reproduce

Observe that sometimes the HACS icon is missing from the sidebar.

### Screenshots

<img width="1670" alt="Screen Shot 2020-06-14 at 4 17 36 PM" src="https://user-images.githubusercontent.com/860888/84606391-a6fb5400-ae5a-11ea-9946-21ac2f95b869.png">

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

hacs:14 -
```text
      }</script><script>import("/frontend_latest/core.cca20d3e.js"),import("/frontend_latest/app.cb642fbe.js"),window.customPanelJS="/frontend_latest/custom-panel.9054f397.js",window.latestJS=!0</script><script type="module" crossorigin="use-credentials" src="/simpleicons/data/si.js"></script><script type="module" crossorigin="use-credentials" src="/browser_mod.js"></script><script type="module" crossorigin="use-credentials" src="/hacsfiles/iconset.js"></script><script>(function() {

```

</details>

I see a reference to `/browser_mod.js` in there and I had commented that out of my resources definition because it didn't seem necessary for my use of brower_mod, so I added it back, refreshed the Lovelace dashboard and the icon showed up.  I'm not sure if that's related, though.  I just added this to my resources:
```
  - url: /browser_mod.js
    type: module
```

Could be unrelated, but thought I'd mention it.

**Comment by rccoleman** [comment]
Circling back on this, I'm still seeing the HACS icon sometimes missing even after the browser_mod change that I mentioned above.  It happens both on my Desktop machine (Mac, running Chrome) and on my iPhone running the iOS app, Safari, or Chrome.  I just had a tab open on my Mac where the icon was showing, refreshed, and icon disappeared.  These are the messages in the console:

<img width="629" alt="Screen Shot 2020-06-15 at 12 29 19 PM" src="https://user-images.githubusercontent.com/860888/84698029-f8abe900-af03-11ea-885c-345963734a22.png">

**Comment by chemelli74** [comment]
From time to time, I miss the icon for "sensor.hacs" as well.

Simone

**Comment by maximosm** [comment]
Having same problem.Side icon (HACS) is not any more there.

**Comment by ludeeus** [comment]
That is a feature of HA 0.111.0
The frontend now shows before all integrations have loaded since that icon is provided by the HACS integration, it will not be there (since that integration is not loaded).
Refresh/clear cache in the browser and it shows up.

**Comment by rccoleman** [comment]
Not a great user experience, though, right?  Maybe an integration that wants to display something that it controls can kick off a refresh automatically.

**Comment by ludeeus** [comment]
That would not be possible, and if it where it would result in random refreshes of the UI (which is worse)

**Comment by rccoleman** [comment]
Ok, understood.  If it's the difference between the "start" and "started" events, perhaps a refresh could be initiated either by HA at the latter, or via an automation (browser_mod.lovelace_reload).  If having third-party integrations be able to add to the sidebar is supported, it seems like it we need to end up with something other than a blank space there.  It looks broken and will generate more support requests.

**Comment by rccoleman** [comment]
From Bram here: https://github.com/home-assistant/frontend/issues/6187

bramkragten commented 14 hours ago

This is a timing thing, HACS should register its icon before adding itself to the sidebar.
