### ISSUE TITLE
Formatted codeblocks only readable when marked in dark themes

### ISSUE THREAD

**Issue by VDRainer** [hacs/integration#1339]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.1.0
| Home Assistant version     |0.111.2
| Installation method for HA |Python 3.8 venv
| Web browser                |Firefox amd Chrome
| Web browser version        |latest on Ubuntu 18.04

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A clear and concise description of what the issue is.

Codeblocks in the information popups are not readable in dark themes.
You need to mark the code to read it. 

### Steps to reproduce

Change HA to a dark theme (i tested darkorange and slate) and open an information popup of an integration/custom-card/theme.

### Screenshots
![Auswahl_357](https://user-images.githubusercontent.com/26381449/84695355-0042b080-af4b-11ea-9d68-bb0f8a1a39b8.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
Set the color in the theme. `markdown-code-background-color`
