### ISSUE TITLE
Improve log when a removed repository is detected

### ISSUE THREAD

**Issue by bokub** [hacs/integration#1342]
## Category

- [x] Backend/Integration
- [ ] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

Hi,

This morning, I noticed a log from HACS in my home-assistant logs:

`You have custom-cards/button-entity-row installed with HACS this repository has been removed, please consider removing it. Removal reason (blacklist)`

From what I can see in [this commit](https://github.com/hacs/default/commit/c19cae47ae3d7e16bb5cc51443a9299669599597), you have included a `reason` which is:

> Not maintained anymore

Is it possible to add that reason **in the log** ?

[A lot a people](https://github.com/custom-cards/button-entity-row/issues/27) (including me) didn't understand **why** it was blacklisted, and if it was dangerous or not to keep it

Thanks :+1:

**Comment by ludeeus** [comment]
The plan is to show that in the UI, on the HACS entry page.
