### ISSUE TITLE
Unexpected frontend version

### ISSUE THREAD

**Issue by nickrout** [hacs/integration#1350]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.1.1
| Home Assistant version     | 0.111.4
| Installation method for HA |supervised
| Web browser                |Chrome
| Web browser version        | Version 83.0.4103.106 (Official Build) (64-bit)

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

In HACS itself this message appears

Information
Unexpected frontend version
You are running version 202006071141 of the HACS frontend, but version 202006201137 ...

(I can't read the rest)
### Steps to reproduce
 
Click HACS in the side menu

1. 1. 1.

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
> , but version 202006201137 was expected, you should clear your browser cache.

That is the rest.
Clear your cache.

**Comment by nickrout** [comment]
D'oh I am always telling other people to do that.
