### ISSUE TITLE
Unable to install repositories using HACS

### ISSUE THREAD

**Issue by Meph88** [hacs/integration#1357]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| Integration version               | 1.1.1
| Frontend version               | 202006201137
| Home Assistant version     | HassOS 4.8
| Installation method for HA | VMDK

## Checklist

[:heavy_check_mark:] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
[:heavy_check_mark:] I have enabled debug logging for my installation.
[:heavy_check_mark:] I have filled out the issue template to the best of my ability.
[:heavy_check_mark:] I have read https://hacs.xyz/docs/issues
[:heavy_check_mark:] This issue is related to the backend of HACS.
[:heavy_check_mark:] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I am unable to install repositories using HACS.

### Steps to reproduce

1. Installed HACS from directions on hacs.xyz
2. Attempted to install a custom repository - it failed - after clicking "install" the icon spins for a few moments then the popup window closes and I am back at the integrations view of HACS but nothing was installed
3. Tried installing an included repository, same result as custom repository
4. Fully uninstalled HACS again as per instructions on the site
5. Reinstalled HACS by installation instructions
6. Repeated steps 2 and 3

No success, no matter what I have tried, I can not install any repositories with HACS.

## Debug logs

<details>
  <summary>Logs</summary>

```text

Pending

```

</details>

**Comment by ludeeus** [comment]
That is the startup log... not the logs for the installation

**Comment by Meph88** [comment]
Understood.
I will try to figure out how to get the correct logs.
I did my best by the directions given in the template but I guess I missed something and got the wrong thing.

**Comment by ludeeus** [comment]
Logs are only useful if it contains the action that failed ;)
Starting up does not fail

**Comment by Meph88** [comment]
I see.
Just so I'm clear, does that mean in this case logs won't be necessary?
Is there anything else I need to add?
I tried to get it right......

**Comment by ludeeus** [comment]
he logs for the installation is needed, the thing that fails

**Comment by Meph88** [comment]
OK, thank you for the info.
I think I'm just a little out of my depth here, can you tell me how to find those logs?

**Comment by ludeeus** [comment]
Please uninstall HACS.

**Comment by Meph88** [comment]
OK, done

**Comment by Meph88** [comment]
Hi, I'm confused why this was closed?

**Comment by Meph88** [comment]
Will installing HACS again with the code in my configuration.yaml to allow logging create the necessary log file?
