### ISSUE TITLE
My integration is not showing in HACS (SamsungTV Tizen)

### ISSUE THREAD

**Issue by jaruba** [hacs/integration#1358]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version                | 1.1.1 |
| Home Assistant version    | 0.111.1 |
| Installation method for HA | HassOS |

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [ ] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [ ] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I can't see my integration: SamsungTV Tizen ([line where it's added to hacs/default > integration](https://github.com/hacs/default/blob/master/integration#L131)). It was there in previous versions of HACS, did it get flagged? If so, for what reason? It's an active repository and the integration works fine with the latest (and older) HA versions.

### Steps to reproduce

1. Go to "Community" in the left sidebar from HA
2. Press "Integrations"
3. Search "Tizen" and you will get no results

## Debug logs

_Not required_

**Comment by rccoleman** [comment]
It shows up for me:

![image](https://user-images.githubusercontent.com/860888/85903932-65ed3300-b7bc-11ea-8d40-d534ca128418.png)

You hit '+' first to add an integration, and it's not already installed?

**Comment by jaruba** [comment]
You're right, I guess I got confused by the new UI of HACS after not updating it for a long time.. Sorry for the misleading issue. :)
