### ISSUE TITLE
unable to add different repositories for the same dev 

### ISSUE THREAD

**Issue by adonno** [hacs/integration#1359]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |  1.1.1 
| Home Assistant version     | 0.111.4
| Installation method for HA | supervised on ubuntu

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A clear and concise description of what the issue is.

I have already added the following repo : 
https://github.com/dmulcahey/zha-network-visualization-card 
and now I am unable to add this one 
https://github.com/dmulcahey/zha-network-card

### Steps to reproduce

try to add both repoes
1. 1. 1.

## Debug logs

<details>
  <summary>Logs</summary>

```text



```

</details>

**Comment by ludeeus** [comment]
https://github.com/dmulcahey/zha-network-card is a default repository in HACS, which is why you can't add it.
It has nothing to do with multiple repos from the same dev.
https://hacs.xyz/docs/default_repositories
