### ISSUE TITLE
Incorrect 'button name' in FAQ

### ISSUE THREAD

**Issue by Gordontgopher** [hacs/integration#1364]
## Describe the issue
[https://hacs.xyz/docs/categories/plugins#open-plugin-button](url) refers to the the 'open plugin button' (in the heading and within the paragraph below. I believe this should now refer to the 'open source' option on the hamburger menu for each plugin.

## Screenshots

![image](https://user-images.githubusercontent.com/3321366/86338459-43d73300-bc4a-11ea-9855-8b44cebe8f2b.png)

**Comment by ludeeus** [comment]
Correct, there is an edit button on that page if you want to make a PR to change it.

**Comment by Gordontgopher** [comment]
Done! First PR so please be gentle :)
