### ISSUE TITLE
Error message when reloading HA after update of HACS 

### ISSUE THREAD

**Issue by rjenx** [hacs/integration#1365]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.1.2
| Home Assistant version     |0.111.4
| Installation method for HA | Docker
| Web browser                | Google Chrome on MAC OSX
| Web browser version        |83.0.4103.116 (Official Build) (64-bit)

## Checklist

- [ ] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [ ] I have filled out the issue template to the best of my ability.
- [ ] I have read https://hacs.xyz/docs/issues
- [ ] This issue is related to the frontend of HACS.
- [ ] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue
Updated HACs to latest version, when rebooting HA I noticed an error message in the HACS front page, 
"Unexpected frontend version
You are running version 202006201137 of the HACS frontend, but version 202006281222"

According to HACS I am running 202006201137.  The message seems to be truncated but I am guessing the front end is down level. No error messages in the logs.  

A clear and concise description of what the issue is.

### Steps to reproduce

1. 1. 1.

### Screenshots
![image](https://user-images.githubusercontent.com/64302977/86345970-2a3ae900-bc54-11ea-86b2-3e1d35445266.png)
![image](https://user-images.githubusercontent.com/64302977/86346041-43439a00-bc54-11ea-9327-b2746be1cfb1.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
Clear your cache. (the hidden part tell you to do that)

**Comment by rjenx** [comment]
Thanks I was also in the process of updating HA to latest. Which fixed it for me...!
