### ISSUE TITLE
Text on the "Install" button disappears when clicked

### ISSUE THREAD

**Issue by ZephireNZ** [hacs/integration#1366]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.1.2 (frontend 202006281222)
| Home Assistant version     | 0.112.0 (frontend 20200701.0)
| Installation method for HA | Docker
| Web browser                | Chrome on Windows
| Web browser version        | 83.0.4103.116

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

The text on the "Install" button disappears when clicked.

### Steps to reproduce

1. Find a HACS integration/resource to install
2. Click install on the card - text will disappear (but the material design hover/ripple will still show).

### Screenshots

![image](https://user-images.githubusercontent.com/1644496/86404373-9cb6d200-bd03-11ea-9f05-26f3fac283a8.png)

## Javascript logs from your browser console

None

**Comment by sreknob** [comment]
Also in the current version the text for the beta toggle is missing. You can see in in the screenshot above - a toggle with no indication of what it does...
