### ISSUE TITLE
impossible to add integration to hacs / default: hassfest fails with exception error

### ISSUE THREAD

**Issue by nagyrobi** [hacs/integration#1370]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | Integration version: 1.1.2 |
| Home Assistant version     | Home Assistant Core 0.112.2 |
| Installation method for HA | normal |

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Please help me determining why can't I add to hacs / default [this](https://github.com/nagyrobi/home-assistant-custom-components-linkplay). I've added other integration in the past to HACS and it all worked fine, but this time it keeps failing at `hassfest` with an error message not describing the real reason of the failure:
```
Run hassfest 5s
##[error]Process completed with exit code 1.
Run integration=$(python3 -m scripts.helpers.integration_path)
Validating json... done in 0.00s
Validating codeowners... done in 0.00s
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/homeassistant/script/hassfest/__main__.py", line 177, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/script/hassfest/__main__.py", line 107, in main
    plugin.validate(integrations, config)
  File "/usr/src/homeassistant/script/hassfest/config_flow.py", line 109, in validate
    config.cache["config_flow"] = content = generate_and_validate(integrations, config)
  File "/usr/src/homeassistant/script/hassfest/config_flow.py", line 99, in generate_and_validate
    validate_integration(config, integration)
  File "/usr/src/homeassistant/script/hassfest/config_flow.py", line 26, in validate_integration
    if integration.get("config_flow"):
AttributeError: 'Integration' object has no attribute 'get'
Validating config_flow...
##[error]Process completed with exit code 1.
```
Sorry if I posted in the wrong place. 

### Steps to reproduce

Re-check this PR: https://github.com/hacs/default/pull/539

## Debug logs

<details>
  <summary>Logs</summary>

```text
N/A
```

</details>

**Comment by ludeeus** [comment]
Made a PR to solve it here <https://github.com/home-assistant/core/pull/37535>
As for why, you do not have a config_flow.py file, but you have elements that needs it.

- "SSDP information in a manifest requires a config flow to exist"
<https://github.com/home-assistant/core/blob/dev/script/hassfest/config_flow.py#L39>

**Comment by nagyrobi** [comment]
Aaaah thanks.
