### ISSUE TITLE
Installed card is not added to Lovelace resource

### ISSUE THREAD

**Issue by wolverinevn** [hacs/integration#1372]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.1.2
| Home Assistant version     | 0.112.2
| Installation method for HA | HassOS

## Checklist

- [x ] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [ x] I have enabled debug logging for my installation.
- [ x] I have filled out the issue template to the best of my ability.
- [ x] I have read https://hacs.xyz/docs/issues
- [ x] This issue is related to the backend of HACS.
- [ x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

After successfully installed, card is not added to Lovelace dashboard resources automatically. Therefore card is not loaded in Lovelace. Reinstall does not help. Uninstall and install might solve but another card is removed from lovelace resource (?).

### Steps to reproduce

- Install new card
- Check HACS frontend section

1. 1. 1.

## Debug logs

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
That only works if you are using Lovelace in storage mode

**Comment by wolverinevn** [comment]
> That only works if you are using Lovelace in storage mode

Sure. Never switch back to yaml mode from Hass 0.1x.

**Comment by damiano75** [comment]
Same problem, these are my logs, very long but I don't know which are the relevant informations, hope could help
[home-assistant.log](https://github.com/hacs/integration/files/4892001/home-assistant.log)

**Comment by holdestmade** [comment]
> Same problem, these are my logs, very long but I don't know which are the relevant informations, hope could help
> [home-assistant.log](https://github.com/hacs/integration/files/4892001/home-assistant.log)

Be careful posting your logs, you've exposed your email, an API KEY, and your camera login details.....

**Comment by sgofferj** [comment]
Same issue here, HA 112.4 in docker, HACS 1.1.2.
I don't particularly mind that a new card isn't automatically added to resources but it's slightly annoying that HACS removes a random resource if a card is uninstalled.

**Comment by damiano75** [comment]
It seems it is related to the hard disk usage, I removed my database file, every partition goes from 25% to 24% and my cards are loaded again:

![image](https://user-images.githubusercontent.com/47896789/87442679-deddee80-c5f4-11ea-83af-36a974df0f33.png)

I don't know exactly how this usage works, but from my sensor I still have about 20G free

![image](https://user-images.githubusercontent.com/47896789/87442924-206e9980-c5f5-11ea-849a-a6f6c1958aae.png)

So for me it's very strange I don't have enough space...

**Comment by sgofferj** [comment]
My installation runs on Docker on an x86_64 server. The storage where HA lives has a bit over a Terabyte free, so I don't believe, that's the issue.
