### ISSUE TITLE
Require system restart when installing a theme.

### ISSUE THREAD

**Issue by orickcorreia** [hacs/integration#1375]
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [ ] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

Warn the user that they will need to restart HA after installing a theme. Many users expect the themes to work magically after installing.

## Implementation

Alert the user that a restart is required.

## Alternatives

Or call service frontend.reload_themes

**Comment by ludeeus** [comment]
"Or call service frontend.reload_themes" HACS allready does that.

A restart is not needed if the frontend was already configured with themes.

https://github.com/hacs/integration/blob/98a57667ddc1ed784cd65ac84fd62bff7354647b/custom_components/hacs/repositories/theme.py#L27-L33
