### ISSUE TITLE
HACS background present in HA pages

### ISSUE THREAD

**Issue by clau-bucur** [hacs/integration#1376]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.1.2 (frontend 202006281222)
| Home Assistant version     | 0.112.3
| Installation method for HA | Hassio manually installed in Ubuntu 19.10
| Web browser                | Firefox on Windows
| Web browser version        | 78.0.1

## Checklist

- [ x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x ] I have filled out the issue template to the best of my ability.
- [ x] I have read <https://hacs.xyz/docs/issues>
- [x ] This issue is related to the frontend of HACS.
- [ x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A partial HACS black text appears on every page load of Home Assistant.
It dissapears quickly after the page is fully loaded, but it remains visible on HACS and "Configure Home Assistant" pages.

Clearing the browser cache, restarting HA, or using a different and clean browser did not have any effect in fixing the issue.

### Steps to reproduce

1. Simply have HACS installed and browse through HA pages.

### Screenshots
![image](https://user-images.githubusercontent.com/47672949/87171707-bba4fd80-c2db-11ea-83c0-0e295e9750e7.png)
![image](https://user-images.githubusercontent.com/47672949/87171730-c495cf00-c2db-11ea-8b36-bc36b014611a.png)

**Comment by ludeeus** [comment]
That has not been in HACS for many many many versions.
Clear your browser cache

**Comment by clau-bucur** [comment]
Please read my info there: "**Clearing the browser cache**, restarting HA, or **using a different and clean browser** did not have any effect in fixing the issue."
I have used all browsers available for Windows and for all the issue is present for me.

**Comment by clau-bucur** [comment]
![image](https://user-images.githubusercontent.com/47672949/87173800-f3617480-c2de-11ea-926e-6fa727e15153.png)
Chrome and Vivaldi, both running with completely cleared off cache, cookies and history.

**Comment by AalianKhan** [comment]
I have also the same issue.
![Screen Shot 2020-07-23 at 5 08 26 PM](https://user-images.githubusercontent.com/39784853/88338958-307a2d80-cd07-11ea-8139-87eb15d930cc.png)
![Screen Shot 2020-07-23 at 5 08 15 PM](https://user-images.githubusercontent.com/39784853/88338960-3112c400-cd07-11ea-8e8c-ab30a2d30c34.png)
When I remove hacs, the issue disappears, when I reinstall the issue comes back.

**Comment by clau-bucur** [comment]
In the end it was not HACS' fault. It was caused by another custom component: https://github.com/Armaell/home-assistant-custom-icons-loader
Once I removed it, everything worked properly.
