### ISSUE TITLE
Can't find plugin despite they exist in hacs database

### ISSUE THREAD

**Issue by bobbar17** [hacs/integration#1379]
Hello, I installed successfully hacs.i can search, 
install successfully in all three categories. In the frontend category I try to install one plugin that hacs it in the base of the hacs but didn’t find him. For example lovelace-card-template
--+-+
Home Assistant 0.112.2
----++---+
Hacs
Integration version: | 1.1.2
-- | --
Frontend version: | 202006281222

![Screenshot_2020-07-10-15-51-25-803_cn wps xiaomi abroad lite](https://user-images.githubusercontent.com/48641309/87221625-1ab75080-c376-11ea-8e12-ac4cf03fcfa4.jpg)

**Comment by ludeeus** [comment]
You are looking in the wrong place.
Click the +
![image](https://user-images.githubusercontent.com/15093472/87221911-e9d41d00-c36f-11ea-8499-0855b68c98f0.png)
