### ISSUE TITLE
Custom repository menu item missing

### ISSUE THREAD

**Issue by TheZoker** [hacs/integration#1384]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.1.2
| Home Assistant version     |  0.112.4
| Installation method for HA | Hassio
| Web browser                | Edge Chrome
| Web browser version        |  84

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I tried to add a custom repository, but I don't see the menu item mentioned on this page:
https://hacs.xyz/docs/faq/custom_repositories

### Steps to reproduce

1. Install latest (1.1.2) version of HACS
2. Look for the "Custom Repositories" menu item

### Screenshots

![Screenshot_2020 07 14_11h17m18s_014_](https://user-images.githubusercontent.com/1368405/87412182-028b3f80-c5c9-11ea-962f-d881007b37ea.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

No javascript log

```

</details>

**Comment by ludeeus** [comment]
It is hidden while background tasks is running to stop the user to break their installation

**Comment by TheZoker** [comment]
Thanks for the hint! 

Maybe add that to the linked documentation. Was not clear to me at all
