### ISSUE TITLE
.translations folder is removed, but explicitly referenced in the install manual

### ISSUE THREAD

**Issue by maui1911** [hacs/integration#1387]
.translations folder is removed, but explicitly referenced in the install manual

## Screenshots
![image](https://user-images.githubusercontent.com/1742072/87796775-1a252b00-c84a-11ea-81b7-55b33e35cdba.png)

![image](https://user-images.githubusercontent.com/1742072/87797672-54db9300-c84b-11ea-8d6a-21bac14a40d3.png)

https://hacs.xyz/docs/installation/manual

**Comment by ludeeus** [comment]
https://github.com/hacs/documentation/commit/18cbeba0bc6aa58d08aa1fdc1e9fdad319a69ca2
