### ISSUE TITLE
custom-components/alexa_media_player

### ISSUE THREAD

**Issue by neviim** [hacs/integration#1388]
## Describe why you are flagging this

_This template should **only** be used if a repository **needs** to be removed/blacklisted from HACS_

 Invalid config for [sensor.template]: value is not allowed for dictionary value @ data['sensors']['updater_hacs']['device_class']. Got 'problem'. (See ?, line ?).

**Comment by ludeeus** [comment]
**This template should only be used if a repository needs to be removed/blacklisted from HACS**
