### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by huzefamansoorali** [hacs/integration#1393]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |
| Home Assistant version     |
| Installation method for HA |

## Checklist

- [ ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ ] I have enabled debug logging for my installation.
- [ ] I have filled out the issue template to the best of my ability.
- [ ] I have read <https://hacs.xyz/docs/issues>
- [ ] This issue is related to the backend of HACS.
- [ ] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

After I make and chown and chmod the folder custom_components and copy hacs folder into it, My HA fails to start on reboot.

As per log files it errors for permission for custom_components folder.

After I remove the folder HA loads fine
### Steps to reproduce

1. 1. 1.

## Debug logs

pi@raspberrypi:/home/homeassistant/.homeassistant $ sudo chmod 755 custom_components/
pi@raspberrypi:/home/homeassistant/.homeassistant $ ls -lah
total 6.2M
drwxr-xr-x 7 homeassistant homeassistant 4.0K Jul 19 15:09 .
drwxr-xr-x 4 homeassistant homeassistant 4.0K Jul 19 05:22 ..
-rw-r--r-- 1 homeassistant homeassistant    2 Jul 19 05:22 automations.yaml
drwxr-xr-x 2 homeassistant homeassistant 4.0K Jul 19 05:23 .cloud
-rw-r--r-- 1 homeassistant homeassistant  263 Jul 19 05:22 configuration.yaml
drwxr-xr-x 3 homeassistant homeassistant 4.0K Jul 19 15:08 custom_components
drwxr-xr-x 2 homeassistant homeassistant 4.0K Jul 19 05:22 deps
-rw-r--r-- 1 homeassistant homeassistant    0 Jul 19 05:22 groups.yaml
-rw-r--r-- 1 homeassistant homeassistant    7 Jul 19 05:22 .HA_VERSION
-rw-r--r-- 1 homeassistant homeassistant 2.5K Jul 19 15:12 home-assistant.log
-rw-r--r-- 1 homeassistant homeassistant 6.1M Jul 19 15:09 home-assistant_v2.db
-rw-r--r-- 1 homeassistant homeassistant    0 Jul 19 05:22 scenes.yaml
-rw-r--r-- 1 homeassistant homeassistant    0 Jul 19 05:22 scripts.yaml
-rw-r--r-- 1 homeassistant homeassistant  161 Jul 19 05:22 secrets.yaml
drwxr-xr-x 2 homeassistant homeassistant 4.0K Jul 19 15:09 .storage
drwxr-xr-x 2 homeassistant homeassistant 4.0K Jul 19 05:30 tts
pi@raspberrypi:/home/homeassistant/.homeassistant $ sudo systemctl start home-assistant@homeassistant.service 
pi@raspberrypi:/home/homeassistant/.homeassistant $ sudo systemctl status home-assistant@homeassistant.service 
● home-assistant@homeassistant.service - Home Assistant
   Loaded: loaded (/etc/systemd/system/home-assistant@homeassistant.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-07-19 15:20:42 BST; 1s ago
  Process: 31911 ExecStart=/srv/homeassistant/bin/hass -c /home/homeassistant/.homeassistant (code=exited, status=1/FAILURE)
 Main PID: 31911 (code=exited, status=1/FAILURE)

Jul 19 15:20:42 raspberrypi hass[31911]:     result = self.fn(*self.args, **self.kwargs)
Jul 19 15:20:42 raspberrypi hass[31911]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 156, in resolve
Jul 19 15:20:42 raspberrypi hass[31911]:     if not manifest_path.is_file():
Jul 19 15:20:42 raspberrypi hass[31911]:   File "/usr/lib/python3.7/pathlib.py", line 1365, in is_file
Jul 19 15:20:42 raspberrypi hass[31911]:     return S_ISREG(self.stat().st_mode)
Jul 19 15:20:42 raspberrypi hass[31911]:   File "/usr/lib/python3.7/pathlib.py", line 1161, in stat
Jul 19 15:20:42 raspberrypi hass[31911]:     return self._accessor.stat(self)
Jul 19 15:20:42 raspberrypi hass[31911]: PermissionError: [Errno 13] Permission denied: '/home/homeassistant/.homeassistant/custom_components/
Jul 19 15:20:42 raspberrypi systemd[1]: home-assistant@homeassistant.service: Main process exited, code=exited, status=1/FAILURE
Jul 19 15:20:42 raspberrypi systemd[1]: home-assistant@homeassistant.service: Failed with result 'exit-code'.

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
This is not an issue with HACS.
as the homeassistant user, run this https://hacs.xyz/docs/installation/manual_cli
