### ISSUE TITLE
Github links in info.md is changet to raw.**

### ISSUE THREAD

**Issue by hakana** [hacs/integration#1401]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.2.2
| Home Assistant version     | 0.113.1
| Installation method for HA | HassIO

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

When I click on the document link for ShellyForHass it open the readme.md in raw format. I have checked my info.md and it pointing to the right address.

Info.md: https://github.com/StyraHem/ShellyForHASS/blob/master/README.md
Open: https://raw.githubusercontent.com/StyraHem/ShellyForHASS/master/README.md

This will open README.md in a raw format not as md-formated as it should.

### Steps to reproduce

1. Install ShellyForHass plugin
2. <click on menu "Information" for ShellyForHass and click the link Documentation in the bottom

You can probably see this just by a search for ShellyForHass integration and show info.

## Debug logs

N/A

**Comment by hakana** [comment]
![image](https://user-images.githubusercontent.com/1168654/88453047-f7a39b00-ce63-11ea-8423-f61fb741d115.png)

**Comment by hakana** [comment]
![image](https://user-images.githubusercontent.com/1168654/88453064-1d30a480-ce64-11ea-9637-221588faa4ef.png)

**Comment by ludeeus** [comment]
This was done to cope with folks not understanding linking (for things like images) those failed, so logic to use the raw URL was implemented.

Can probably add an exception for files ending with .md, so those open the UI version

**Comment by hakana** [comment]
![image](https://user-images.githubusercontent.com/1168654/88453099-6da80200-ce64-11ea-9967-b8972b83839d.png)

**Comment by hakana** [comment]
Thanks for your quick response!

Yes, that will work for me

**Comment by hakana** [comment]
Thanks, missed the button!

**Comment by ludeeus** [comment]
I killed my dev machine last night, so not sure when I will be able to add this.

If someone wants to try, this is where it happens <https://github.com/hacs/frontend/blob/master/src/tools/markdown/markdown.ts#L44>

**Comment by hakana** [comment]
Maybe it is better to add .png, .gif., .jpeg, .jpg ect instead of exclude .md ?

Can´t you just edit the file in github to trig a build?

**Comment by ludeeus** [comment]
> Maybe it is better to add .png, .gif., .jpeg, .jpg ect instead of exclude .md ?

GitHub only have pretty view for markdown, I think it's better to just exclude those instad of including all other, it will also cause fewer issues if someone uses some obscure valid extention.

I could just do it, but then I would not be able to test my change, so I will not do that.

**Comment by hakana** [comment]
Ok, I thought maybe you have a dev branch you could test it on first.

Can I do anything to help, I guess it is too much work for me to set up the dev environment quickly.

**Comment by ludeeus** [comment]
Implemented in hacs/frontend#197
