### ISSUE TITLE
"Unexpected frontend version" since update to 0.113.0 and 0.113.1

### ISSUE THREAD

**Issue by Vxider** [hacs/integration#1404]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.2.2 |
| Home Assistant version     | 0.113.1|
| Installation method for HA | supervised|
| Web browser                |Chrome|
| Web browser version        |84.0.4147.89|

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

In HACS itself this message appears

Unexpected frontend version
You have 202006071141 of the HACS frontend installed, but version 202007180957 was expected, if this you see this message Home Assistant was not able to install the new version, try restarting Home Assistant.

I have found solutions in #1350 and #1351, but clear cache doesn't solve my problem, I also tried to restart HA many times, and use a new tablet (have never logged in HA).

### Steps to reproduce

Click HACS in the side menu

### Screenshots

<img width="652" alt="截屏2020-07-26 12 06 35" src="https://user-images.githubusercontent.com/6134315/88471182-7cf87f80-cf38-11ea-8df1-4b8d582ebeab.png">

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

CARD-MOD 2.0.0 IS INSTALLED 
button-card.js:1597   BUTTON-CARD   Version 3.3.6 
mini-graph-card-bundle.js:1  MINI-GRAPH-CARD  0.9.4 
vertical-stack-in-card.js:2 vertical-stack-in-cardVersion: 0.3.3
air-visual-card.js:3   AIR-VISUAL-CARD    Version 0.0.11   
custom-header.js:617   CUSTOM-HEADER    Version 1.6.7  
simple-thermostat.js:1 simple-thermostat: 0.35.0
weather.ts:343 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://hassio:8123/static/fonts/roboto/Roboto-Bold.woff2
mini-graph-card-bundle.js:1 mini-graph-card:  value [64] not found in state_map
xc @ mini-graph-card-bundle.js:1
mini-graph-card-bundle.js:1 mini-graph-card:  value [2222] not found in state_map
xc @ mini-graph-card-bundle.js:1
card-mod.js:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://hassio:8123/static/fonts/roboto/Roboto-Light.woff2
2mini-graph-card-bundle.js:1 mini-graph-card:  value [64] not found in state_map
xc @ mini-graph-card-bundle.js:1
2mini-graph-card-bundle.js:1 mini-graph-card:  value [2222] not found in state_map
xc @ mini-graph-card-bundle.js:1
custom-header.js:617 Current User's Name:  XXXX
custom-header.js:617 Current User's ID:  XXXX
custom-header.js:617 Device ID:  XXXX
4DevTools failed to load SourceMap: Could not load content for chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/content_scripts/purify.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

```

</details>

**Comment by ludeeus** [comment]
As the message states, you get this when Home Assistant is not able to install the new version.
Closing this as this is not an issue with HACS.

**Comment by RoldyBuffalo** [comment]
@Vxider  Control+F5, pretty sure it's a browser cache issue. I've had this exact issue in the past, and digging around, people have found it to be a browser cache issue. Crumbs for anyone else wondering.
