### ISSUE TITLE
Update Button replaces Repository link

### ISSUE THREAD

**Issue by SonomaGTS** [hacs/integration#1406]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.2.2
| Home Assistant version     | 0.112.4
| Installation method for HA | Jedi Mind Transfer (whatever hassio is called these days)
| Web browser                | Chrome
| Web browser version        | Whatever the last updated version is

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

When an Integration has an update the Update button replaces the Repository link. Both should be available so we can quickly see the changelog before updating.
  
### Steps to reproduce

wait for something that needs an update.

### Screenshots

![update-repo](https://user-images.githubusercontent.com/58022736/88483455-b4156380-cf2d-11ea-88c8-97804e4f804e.png)

**Comment by ludeeus** [comment]
The changelog shows when you click the update button

**Comment by SonomaGTS** [comment]
that is a different screen. i'm referring to the overview. even if it was added to the 3 dot drop down would be nice or was there permanently would work too.
