### ISSUE TITLE
USA-RedDragon/badnest

### ISSUE THREAD

**Issue by user897943** [hacs/integration#1412]
## Describe why you are flagging this

This is no longer maintained. Please replace with https://github.com/vinodmishra/badnest instead! This one is being actively updated.

_This template should **only** be used if a repository **needs** to be removed/blacklisted from HACS_

**Comment by user897943** [comment]
There is no need to try to contact the owner, there are several issues on the original that have not been seen to. It's clearly abandoned. Please replace with https://github.com/vinodmishra/badnest which is being actively maintained.

**Comment by ludeeus** [comment]
USA-RedDragon/badnest is not a default repository in HACS, just remove it from your installation
List of default repositories: https://hacs.xyz/docs/default_repositories
