### ISSUE TITLE
Unexpected frontend

### ISSUE THREAD

**Issue by pgdg71** [hacs/integration#1414]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version              | latest 
| Home Assistant version    | 0.113.2
| Installation method for HA |  Hassio
| Web browser               | Chrome
| Web browser version        | 84.0

## Checklist

- [x ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ x] I have filled out the issue template to the best of my ability.
- [ ] I have read <https://hacs.xyz/docs/issues>
- [ x] This issue is related to the frontend of HACS.
- [ x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Error reported in the attached image. App redirects the opening to the browser.

### Steps to reproduce

Upgrade Have and then open it via HA App

1. 1. 1.

### Screenshots

![Screenshot_20200730-153238](https://user-images.githubusercontent.com/59010811/88929134-0205d080-d27a-11ea-8419-259b5e97f063.jpg)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
Do what it says and the issues will be resolved

**Comment by antoweb** [comment]
I have cleared the cache but the issue still remain

**Comment by gadgetchnnel** [comment]
The same here, the message pops up and then disappears within a second every time the HACS frontend is opened.
