### ISSUE TITLE
"Beta" release numbers should not be appearing in the stable releases pushed to users

### ISSUE THREAD

**Issue by nickdos** [hacs/integration#1417]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.3.0b1
| Home Assistant version     |  0.113.2 
| Installation method for HA | Supervisor

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Versioning up to now has followed the well established `major.minor.patch` **numbering**  format . Then in the past week I see the update has letters in the version (`1.3.0b1`), suggesting it is a `beta` release (`b` in patch number is well established as being a `beta` release). 

I don't want to update to a beta version, I expect the releases to be stable and the numbering to reflect this fact.

The most recent versioning gives the impression of a non-stable release.

Please revert to the standard versioning format **without letters** and keep unstable releases for your `beta` testers.

**Comment by ludeeus** [comment]
b0 and b1 are beta.
both were marked as pre-releases at the time of releasing.
but something changes if after.

by the time it was discovered it was too late to change since it was already downloaded.

**Comment by nickdos** [comment]
No worries, sounds like an honest mistake.

**Comment by ludeeus** [comment]
Nope, no mistake.
There is a bug somewhere in the actions that are triggered after the release that changes it.

**Comment by nickdos** [comment]
Ah OK, sorry for closing - thought "something changes it after" was reference to a person doing "something", not software. Good luck tracking it down.

**Comment by pilot1981** [comment]
also occur in 0.112 version of HASSIO
