### ISSUE TITLE
Unexpected fromtend version

### ISSUE THREAD

**Issue by antoweb** [hacs/integration#1419]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.3.0b1
| Home Assistant version     |
| Installation method for HA | 

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [ ] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

After last update to 1.3.0b1 after restart hassio when i go to HACS i see an error message (atached)
![Cattura](https://user-images.githubusercontent.com/32364871/89024537-90835c00-d325-11ea-8f7a-d912a9b8a1ec.PNG)

Already cleared chache and using new browser but the issue still remain.

Is there a method to reinstall hacs withou losing all integration installed?

### Steps to reproduce

1. 1. 1.

## Debug logs

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
It does not get the data from HACS.
Check your browser console for issues.

**Comment by antoweb** [comment]
Thans i'm closing this because opened in wrong section. Reponed in right section
