### ISSUE TITLE
Unexpected frontend version

### ISSUE THREAD

**Issue by antoweb** [hacs/integration#1420]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.3.0b1
| Home Assistant version     | 0.113.2
| Installation method for HA |  Upgrading from HA
| Web browser                | Chrome/Firefox
| Web browser version        | 

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [ ] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

After last update to 1.3.0b1 after restart hassio when i go to HACS i see an error message (atached)
![Cattura](https://user-images.githubusercontent.com/32364871/89025294-de4c9400-d326-11ea-8aac-cebb369427e9.PNG)

Already cleared chache and using new browser but the issue still remain.

Is there a method to reinstall hacs withou losing all integration installed?

### Steps to reproduce

1. 1. 1.

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
It does not get the data from HACS.
Check your browser console for issues.

**Comment by antoweb** [comment]
In browser console no message

**Comment by ludeeus** [comment]
Paste the messages from the "websocket" entry under network in your browser dev-tools

**Comment by antoweb** [comment]
{"id": 28, "type": "result", "success": true, "result": [{"acknowledged": true, "link": "https://github.com/hacs/default/pull/2", "reason": "Security issues, known to steal auth tokens.", "repository": "test/test"}]}

But the message disappears immediately afterwards i click on HACS

**Comment by antoweb** [comment]
Here are the respons eheader

HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: upgrade
Sec-WebSocket-Accept: tm6h4Yt68Cf6F8NE/geSS7KrCSg=
Sec-WebSocket-Extensions: permessage-deflate
Content-Type: application/octet-stream
Date: Fri, 31 Jul 2020 10:41:12 GMT
Server: Python/3.8 aiohttp/3.6.1

**Comment by ludeeus** [comment]
None of them are useful
You want a websocket command for HACS/configuration

**Comment by antoweb** [comment]
I cant find a "command" in websoct window on console

**Comment by antoweb** [comment]
Can i try to remove e re-instal, HACS wthou lost the tracking for component installed trought HACS?

**Comment by ludeeus** [comment]
Don't do anything
I will try to find it on my own.

**Comment by ivanovd** [comment]
I have the same issue. After updating to 1.3.0b1 Button Card and Custom Header no longer work. Reinstalling them doesn't work. Clearing the cache doesn't work as well.

**Comment by scacace** [comment]
Get similar from Silk browser, but goes away...happens each time I refresh page.  After updating to .0b1,  Edge on Xbox did not display HACS page, and on Win10, after clearing cache will not complete HA login...stuck on initializing..fine on Chrome.

**Comment by antoweb** [comment]
> Get similar from Silk browser, but goes away...happens each time I refresh page. After updating to .0b1, Edge on Xbox did not display HACS page, and on Win10, after clearing cache will not complete HA login...stuck on initializing..fine on Chrome.

Same issue, goes away after 1/2 seconds after refresh or change page and change back to HACS (browser chrome and firefox)

**Comment by antoweb** [comment]
Sorry but why closed?

**Comment by ludeeus** [comment]
it's fixed, fixed issues are closed

**Comment by antoweb** [comment]
maybe I missed something but how do I apply the fix?

**Comment by ludeeus** [comment]
You follow the development documentation and build it
or wait for a release that contains it.
