### ISSUE TITLE
Repository is installed but can't find resources

### ISSUE THREAD

**Issue by mikyjazz** [hacs/integration#1428]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.3.0b
| Home Assistant version     | 0.113.3
| Installation method for HA | Supervisor

## Checklist

- [X ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ ] I have enabled debug logging for my installation.
- [X ] I have filled out the issue template to the best of my ability.
- [X ] I have read <https://hacs.xyz/docs/issues>
- [X ] This issue is related to the backend of HACS. (it sholud be... :) )
- [X ] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I would like to install the Mini Media Player card.
Cannot find in Lovelace list
Tryed to install repository https://github.com/kalkih/mini-media-player but hacs reports that repository is already present

### Steps to reproduce

- look for Mini Media Player into list of Lovelace Custom Cards... (it should not be present)
- try to add the repository to custom repositories; Hacs should respond "repository is already present"
- look again for Mini Media Player into list.. It is not there...

**Comment by ludeeus** [comment]
Click the + in the bottom right corner

**Comment by mikyjazz** [comment]
Thanks, found. Why do only "new repositories" appear in the list and not all of them? In fact, I wondered why they were "all new" :) Thanks again
