### ISSUE TITLE
Philips Hue Integration Not working 

### ISSUE THREAD

**Issue by Tokn59** [hacs/integration#1432]
HA version : 

Home Assistant 0.113.3
Frontend version: 20200716.0 - latest
Hardware : Raspberry Pi 4

Repro : Configuration - "+" - Hue
Error message : Unable to discover hue bridges (See attached)

No automatic discovery of Hue Bridge
Tried : 
- Reboot Hue Bridge
- Reboot HA
- Pressed Hue Bridge Button

Checked HA logfile : No entry regarding Hue

Thanks for helping me solve this issue !

Kind Regards,

Tony
![Hue](https://user-images.githubusercontent.com/9215231/89207850-b6299300-d5bb-11ea-94d6-3de7e378842f.jpg)

arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.11
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7l
python_version | 3.8.3
supervisor | 229
timezone | Europe/Brussels
version | 0.113.3
virtualenv | false

**Comment by ludeeus** [comment]
This is the issue tracker for HACS, HACS does not track issues for other integrations.
If this is a core integration open the issue in home-assistant/core.
If this is a custom integration, open an issue in the repo for that integration.
