### ISSUE TITLE
Some menu item not working with Safari on Mac

### ISSUE THREAD

**Issue by AudioNutz** [hacs/integration#1434]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.3.1
| Home Assistant version     | 113.3
| Installation method for HA |  Hassio Image

## Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend of HACS.
- [X] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue
Safari browser on Mac does not allow one to add a “custom repository”

### Steps to reproduce
On a Macintosh computer:
1. Click on the HACS sidebar item
2. Click on integrations
3. Click on the ellipsis in the e upper right, and attempt to click “Custom Repositories”

I expect to be able to add a custom repository, but instead it does nothing.
Safari on iPad works, as does Firefox on Mac.  It just seems this bit of code is not friendly to the Mac version of the Safari browser.

**Comment by ludeeus** [comment]
And what console errors do you get in the browser?

**Comment by ludeeus** [comment]
What version of the OS/browser do you have?

**Comment by maykar** [comment]
For what it's worth, I can confirm that none of the items inside that paper-listbox element can be interacted with while using Safari 12.1.2. Once the list-box is open an cannot be dismissed as well. Gotta love Safari.

![Safari_Ugh](https://user-images.githubusercontent.com/25127328/89325848-60a2c400-d657-11ea-88dd-e850f72bfb37.gif)

**Comment by AudioNutz** [comment]
> What version of the OS/browser do you have?
Mac OS X 10.11.6 (El Capitan) and Safari 11.1.2

It appears that @maykar is showing you video of what he sees.  This is the exact behavior that I'm seeing as well.  You can open the flyout menu, but once it's open you can't click on anything, or dismiss it.  (Unless you browse to another page)

I also see the same thing in the console log:
[Warning] No web animations detected. This element will not function without a web animations polyfill. (frontend-202008021908.js, line 45623)
[Error] ReferenceError: Can't find variable: KeyframeEffect
	configure (frontend-202008021908.js:45693)
	_configureAnimations (frontend-202008021908.js:45168)
	playAnimation (frontend-202008021908.js:45248)
	_renderOpened (frontend-202008021908.js:45483)
	__openedChanged (frontend-202008021908.js:44720)
	nextAnimationFrame (frontend-202008021908.js:44746)
	nextAnimationFrame

**Comment by ludeeus** [comment]
Update safari.
Have tested this on both 13.1 (Catalina) and 14.0 (Big Sur) and it works as expected.

**Comment by AudioNutz** [comment]
Yikes!
I wish I could...  I suppose I’ll just stop using HACS.

**Comment by ludeeus** [comment]
If you are really using a 1y+ old browser you should really consider changing it to chrome/firefox/other until you can update your OS
