### ISSUE TITLE
New View for Installed Packages

### ISSUE THREAD

**Issue by igloo15** [hacs/integration#1435]
## Category

- [ ] Backend/Integration
- [X ] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

Currently installed plugins, themes, frontend cards, etc show up at the bottom of their respective section. When trying something out I may install a package give a whirl and then want to go back and uninstall it. Right now it sort of a pain to scroll all way to the bottom of a quite long list to find the installed component and then uninstall it. The scrolling is additionally hard because the scrollbar is very tiny and hard to click on in order to get to bottom quicker.

Previous UI had the installed packages in a separate section. Either we should reintroduce that or make the installed packages float to the top instead of the bottom of the section. This will help to quickly facilitate viewing of what packages are installed and removal if you are testing things out.

## Implementation

Either having a separate tab for installed packages or having the installed packages be at the top instead of at the bottom.

## Alternatives

Two possible implementations but if neither of those are possible then potentially we could add a button that immediately scrolls to the bottom of page/installed components. This could be similar to those bottoms you see at the bottom of pages that scroll you all the way to the top of a page.

**Comment by ludeeus** [comment]
It's not really designed to have 100+ new repositories at any given time (which is why at the top there is a line describing how you remove them).
You should try that and see how that feels.

**Comment by igloo15** [comment]
I don't think I have 100+ repositories I just have the default HACS that was installed. I haven't added any repositories to it. Certainly limiting the amount of packages shown by removing repositories could work. 

But I feel like that goes against the idea of the page to begin with. I mean the page starts with a search box so obviously it wants you to search through a large number of packages to find something you are interested in. So making the number of packages smaller so it is easier to scroll to bottom doesn't really solve the problem in my opinion.

**Comment by jgalak** [comment]
This would be extremely helpful.  Something like the add-ons interface, where there's one tab for installed stuff and another tab for available stuff would be great.

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
