### ISSUE TITLE
1.3.2 version not load theme correctly

### ISSUE THREAD

**Issue by sagitt** [hacs/integration#1437]
After last 1.3.2 upgrade i see this:

![Schermata 2020-08-04 alle 19 17 31](https://user-images.githubusercontent.com/169086/89324260-4d0f5180-d687-11ea-934f-28d745c9c334.png)

**Comment by ludeeus** [comment]
And?

**Comment by sagitt** [comment]
graphic issue. not load the theme as before

**Comment by ludeeus** [comment]
HACS does not load themes.
It get that from HA.
Are default theme working?

**Comment by conrad66** [comment]
I have the same problem.
All the time a light theme regardless of which one is selected

**Comment by J-o-h-n-M** [comment]
same issue, I use the Dark Mint theme and my screen looks the same as in the initial post. All previous version were ok

**Comment by aptonline** [comment]
Same here something has changed in HACS to cause this 1.3.1 was working correctly.
