### ISSUE TITLE
Ability to search, "new", "installed", or "all"

### ISSUE THREAD

**Issue by mrsnyds** [hacs/integration#1438]
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

Currently, the search box will search only "installed" or "new" repositories.  It is a smart search box that is context-sensitive, depending on if you are searching integrations, frontend, or automation, and will not show "new" if you have dismissed all of the new ones.  But maybe you dismissed one, and you sometime later wanted to find it again?  If it is already dismissed, it does not show in search results.   Or maybe you uninstalled, and wanted to go find it again because you intended to reinstall as a troubleshooting step ... again, you cannot find that repository because it is not "installed" or "new". 

So I am simply suggesting some way of searching "all" repositories so that you can use HACS to install even ones that are not "new" (or already installed)

## Implementation

This could be implemented with a checkbox somewhere.  Maybe next to the existing filter checkboxes, as in the attached mock up?  If using this implementation, the context-sensitive label in the search box would need to change.  In the example below, it shows "Search for installed repositories", but that would not make sense if the proposed checkbox was selected.
![search_all](https://user-images.githubusercontent.com/41122989/89329087-5505cc00-d65c-11ea-8bf7-666f46dff972.jpg)
## Alternatives

An alternative might be to "reset", or "clear" the previously listing of already dismissed repositories.

**Comment by wizbowes** [comment]
Plus one for this, although perhaps it doesn't go far enough.  I'd actually call it a defect that there is no way to bring back a dismissed repository.  Currently I'm completely unable to install some Frontend components that I've seen being used by others in a great way, because I dismissed them previously. 

So I'd suggest that not only this change is implemented as a priority, but the ability to 'undismiss' all, so I can browse old cards when my usage requirements change 1 year after I dismissed a card.  With your proposal unless you know the name of the card, you still won't be able to see it.

**Comment by scooper1** [comment]
Personally I would like to see all items in one list  with category selection tick boxes plus a installed category. 
Nice to haves would a sort on date last change date,  rating.   I personally still do not like the new menu system and would like to see it made like older interface but without the internal surport issues that older one had.  

I don't see the need for large overside icons in a maintenance part of the system

**Comment by ludeeus** [comment]
Click the + in the bottom right corner and you can search for everything.

**Comment by mrsnyds** [comment]
> Click the + in the bottom right corner and you can search for everything.

That does seem to solve my main problem.   I'm not sure when that "+" appeared, but I missed it previously.  Thanks, and great job on HACS in general!
