### ISSUE TITLE
Error after Update from 1.2.2 to 1.3.2

### ISSUE THREAD

**Issue by hafnerra** [hacs/integration#1439]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |
| Home Assistant version     |
| Installation method for HA |

## Checklist

- [ x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ x] I have enabled debug logging for my installation.
- [x ] I have filled out the issue template to the best of my ability.
- [x ] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x ] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue
Get an error after the Update on my Rasbperry PI 4 HA venv installation.
![grafik](https://user-images.githubusercontent.com/66806427/89329787-96639f00-d68f-11ea-9db9-53f30e3a2154.png)

The only solution is a new install from HACS 1.2.2. I cant see and add a higher version in the integrations.
 
### Steps to reproduce

1. 1. 1.

## Debug logs

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
The file does not exist, or HA can't read it.

**Comment by hafnerra** [comment]
You mean the file 'configuration_schema.py' ? Do you need the file to find the Problem?

**Comment by ludeeus** [comment]
That's the file 👍
It's missing or it have wrong premissions so HA can't use it

**Comment by hafnerra** [comment]
I do the Update with the HA UI. What can i do wrong?
![grafik](https://user-images.githubusercontent.com/66806427/89331695-7d102200-d692-11ea-8383-03ae2f25f361.png)

**Comment by ludeeus** [comment]
Not sure, but make sure the user that is running ha have full access to the entire custom component dir

**Comment by hafnerra** [comment]
Im sure the user have all premission. When i reinstall version 1.2.2 all works fine. I cant install version 1.3.2 because i cant see and add it in the integrations.

**Comment by hafnerra** [comment]
The hacs.zip file are very different between the hacs version 1.2.2 and 1.3.2.
![grafik](https://user-images.githubusercontent.com/66806427/89333779-c31ab500-d695-11ea-80e6-89235c1c77a4.png)

And the __ini__.py file too.
![grafik](https://user-images.githubusercontent.com/66806427/89333885-f0676300-d695-11ea-9100-e37d02e48a02.png)

After the Update i still have the __ini__.py file from 1.2.2 in the path folder custom_components. The __ini__,py file from1.3.2 is in the folder custom_components/hacs. Do the installer something wrong?

**Comment by ludeeus** [comment]
1.3.0 had a restructure, if you still have an old file, it's definitely a permission issue

**Comment by hafnerra** [comment]
I dont think that is the Problem. I can delete the hacs version 1.2.2 but when i try to install the version 1.3.2 according to these guide "https://hacs.xyz/docs/installation/manual". I cant see hacs on this step:
![grafik](https://user-images.githubusercontent.com/66806427/89335121-ddee2900-d697-11ea-9512-026fc323413a.png)

With the hacs.zip from version 1.2.2 i see hacs. Why?

**Comment by ludeeus** [comment]
If you can't see it:
- you are missing some files
- premissions
- missing cache clear

**Comment by hafnerra** [comment]
When i use the hacs.zip from 1.2.2 on the same way, than i can see hacs in this step. All is same but different zips

**Comment by hafnerra** [comment]
I found the solution. Thanks for help and sorry for the circumstances.

**Comment by oopiicaa** [comment]
What is the solution (I can't see it clearly)? I'm having pretty much the same issue (running HA in Python (3.8) venv on Win10) - cannot get to work anything after version 1.2.2 - not with clean install, not with update via HA.

`Log Details (ERROR)

Logger: homeassistant.config_entries
Source: c:\home assistant\lib\site-packages\homeassistant\config_entries.py:248
First occurred: 10:32:44 AM (1 occurrences)
Last logged: 10:32:44 AM
Error setting up entry for hacs

Traceback (most recent call last):
  File "c:\home assistant\lib\site-packages\homeassistant\config_entries.py", line 219, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "C:\home assistant\custom_components\hacs\__init__.py", line 30, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "C:\home assistant\custom_components\hacs\operational\setup.py", line 61, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "C:\home assistant\custom_components\hacs\operational\setup.py", line 86, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "C:\home assistant\custom_components\hacs\operational\setup.py", line 165, in async_hacs_startup
    if not await async_load_hacs_repository():
  File "C:\home assistant\custom_components\hacs\operational\setup_actions\load_hacs_repository.py", line 17, in async_load_hacs_repository
    await register_repository("hacs/integration", "integration")
  File "C:\home assistant\custom_components\hacs\helpers\functions\register_repository.py", line 29, in register_repository
    await repository.async_registration(ref)
  File "C:\home assistant\custom_components\hacs\helpers\methods\registration.py", line 37, in async_registration
    await self.async_post_registration()
  File "C:\home assistant\custom_components\hacs\helpers\methods\registration.py", line 42, in async_post_registration
    await async_run_repository_checks(self)
  File "C:\home assistant\custom_components\hacs\validate\__init__.py", line 24, in async_run_repository_checks
    await async_initialize_rules()
  File "C:\home assistant\custom_components\hacs\validate\__init__.py", line 18, in async_initialize_rules
    await hass.async_add_executor_job(_initialize_rules)
  File "C:\Program Files\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\home assistant\custom_components\hacs\validate\__init__.py", line 13, in _initialize_rules
    importlib.import_module(rule)
  File "C:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.hacsC:\\home assistant\\custom_components\\hacs\\validate\\common\\hacs_manifest'`

**Comment by hafnerra** [comment]
I deleted the complete custom_components folder and in the storage folder all files and folders with "hacs" in their names.
Similar to this guide https://hacs.xyz/docs/installation/remove

Than download the hacs.zip file version 1.3.2 and copy the unzip hacs folder in the custom_components folder.
My mistake was copying the contents from the hacs.zip folder in the custom_components folder. But the content must be in the Path "custom_components\hacs". Then it was possible to add hacs via the integration. Dont forget cache clear (FireFox: STRG + F5)
