### ISSUE TITLE
Unhandled exception: queueman.exceptions.QueueManagerExecutionStillInProgress

### ISSUE THREAD

**Issue by vturekhanov** [hacs/integration#1441]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.3.3 |
| Home Assistant version     | 0.113.3 |
| Installation method for HA | Hassio |

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ ] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Mostly once per day I find following error message in the log. I don't know if it is important for correct hacs work or not but as it is an error I decided to post it here. Since this error appears once per day, not sure if it is necessary to turn on debug logs for all day. Is it possible to schedule turning on/off debug to specific time? If yes, please, tell me how.

### Steps to reproduce

I installed hacs about a month ago. Since that time I upgrade hacs in Home Assistant GUI. Found this issue after upgrading from 1.2.2 to 1.3.0b2.

## Debug logs

<details>
  <summary>Logs</summary>

```text

2020-08-06 09:22:46 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 307, in recurring_tasks_all
    await self.async_load_default_repositories()
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 347, in async_load_default_repositories
    await self.queue.execute()
  File "/usr/local/lib/python3.8/site-packages/queueman/manager.py", line 41, in execute
    raise QueueManagerExecutionStillInProgress
queueman.exceptions.QueueManagerExecutionStillInProgress

```

</details>

**Comment by vturekhanov** [comment]
One more error in log:
```text
2020-08-06 22:42:46 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 271, in prosess_queue
    await self.queue.execute(can_update)
  File "/usr/local/lib/python3.8/site-packages/queueman/manager.py", line 41, in execute
    raise QueueManagerExecutionStillInProgress
queueman.exceptions.QueueManagerExecutionStillInProgress
```

**Comment by Misiu** [comment]
Same issue here.
HA: 0.114.4
HACS: 1.5.2
hacs-frontend: 202008231558

> QueueManagerExecutionStillInProgress: null
>   File "/config/custom_components/hacs/hacsbase/hacs.py", line 306, in recurring_tasks_all
>     await self.async_load_default_repositories()
>   File "/config/custom_components/hacs/hacsbase/hacs.py", line 346, in async_load_default_repositories
>     await self.queue.execute()
>   File "queueman/manager.py", line 41, in execute
>     raise QueueManagerExecutionStillInProgress

**Comment by ludeeus** [comment]
Weird... it's not fixed and you still see it :thinking:

**Comment by Misiu** [comment]
@ludeeus sorry for that. I saw different line numbers in the error message and was thinking it might be something else. My bad
I wanted to be helpful, nothing more. I wish I could help with the development, but I'm still new to HA.

**Comment by thecode** [comment]
@ludeeus I still see it also, I did not leave a comment because I saw the issue is active and I though it is still in progress.
same versions as @Misiu

**Comment by marc-gist** [comment]
happening to me on 0.116.4 and hacs up to date
