### ISSUE TITLE
Frontend styling issues with automatic dark mode in HA 0.114

### ISSUE THREAD

**Issue by gadgetchnnel** [hacs/integration#1447]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.3.3
| Home Assistant version     | 0.114.0b2
| Installation method for HA | HA Core in Python venv (Raspberry Pi)
| Web browser                | Google Chrome
| Web browser version        | 84.0.4147.105

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A clear and concise description of what the issue is.

Then the theme in Home Assistant is set to automatically switch between light and dark mode (added in the 0.114 beta) and the browser/operating system is in dark mode the HACS frontend is incorrectly styled, with white panels against a dark background and the header completely white:

### Steps to reproduce

1. Set the light/dark mode setting for the theme to **Auto** as in the first screenshot below
2. Switch operating system to dark mode
3. Navigate to the HACS frontend
4. It will display as the second screenshot

Manually changing the mode to Light or Dark will show it with correct styling, as in the thrid screenshot (for Dark mode)

### Screenshots

![image](https://user-images.githubusercontent.com/2099542/89683873-3d934100-d8f1-11ea-81e1-67e8b5180e23.png)

![image](https://user-images.githubusercontent.com/2099542/89683847-2f452500-d8f1-11ea-911c-940852e9cffa.png)

![image](https://user-images.githubusercontent.com/2099542/89684586-a9c27480-d8f2-11ea-85a5-3d7a436b72d9.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
Is your header in HA ie. The profile page blue now?

**Comment by gadgetchnnel** [comment]
The header's blue if the theme is in Light mode (either by the manually switching to Light mode or if the OS is in Light mode) otherwise the header has a dark background. HACS appears to be the only thing which doesn't have the correct background colours (and with the theme in Auto).

The rest of the HACS interface also shows the wrong theme when in Auto mode, but it is more consistent with everything having the light background (when the rest of HA uses the dark theme):

![image](https://user-images.githubusercontent.com/2099542/89689744-f8750c00-d8fc-11ea-97a3-e9d9696ec80e.png)

**Comment by gadgetchnnel** [comment]
I've taken at look at how the themes are applied in Home Assistant itself in 0.114:

https://github.com/home-assistant/frontend/blob/e08b2817bab9610143a176c64fd8ee4aa8ac8844/src/state/themes-mixin.ts

That has logic like this (truncated the code slightly):

```
const mql = matchMedia("(prefers-color-scheme: dark)");

this._applyTheme(mql.matches);

private _applyTheme(dark: boolean) {
const themeName =
        this.hass!.selectedTheme?.theme ||
        (dark && this.hass!.themes.default_dark_theme
          ? this.hass!.themes.default_dark_theme!
          : this.hass!.themes.default_theme);
// etc.
```
This is looking for `prefers-color-scheme: dark` in the media query to determine if the OS/browser is in dark mode and switching theme based on this if hass!.selectedTheme?.theme is not defined, which only seems to be the case if you manually select Light or Dark mode which is probably why the HACS styling is correct if I manually select the mode but not when I set it to Auto.

**Comment by aptonline** [comment]
Seeing the same issues with default HA theme and dark mode enabled in 0.114.0.

**Comment by ruifung** [comment]
or well, using frontend.set_theme with mode dark and mode light basically forces it into auto mode too.

And it shows the same issue.

**Comment by ChipSkylark37** [comment]
Confirming that I see the same with 0.114.0 and HACS 1.3.3
