### ISSUE TITLE
Possible wrong content height on repos (Mobile only)

### ISSUE THREAD

**Issue by JuanMTech** [hacs/integration#1449]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.3.3
| Home Assistant version     | 0.113.3
| Installation method for HA | HassOS 4.12
| Web browser                | Chrome
| Web browser version        | 84.0.4147.105

## Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

When opening a repo installed or from the available repos, there is a blank space at the bottom. Making the available view of the content smaller. This issue only happens when the window width is 563px or less.  So mobile experience is affected.

### Steps to reproduce

1. Open HACS in a mobile device
2. Open a repo already install or a repo from the available repos to install

### Screenshots
![Issue 1](https://i.imgur.com/1N0UXLd.jpg)
![Issue 2](https://i.imgur.com/pzBQRiN.jpg)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by tomlut** [comment]
This is probably what causes the rendering of the card list to fail when rotating from landscape to portrait mode on a tablet too.

**Comment by KTibow** [comment]
Can fix this in devtools by unchecking a style:
![image](https://user-images.githubusercontent.com/10727862/103450105-54527f80-4c66-11eb-83fc-c80619747050.png)
