### ISSUE TITLE
Request to add ESPHome custom_components as a category

### ISSUE THREAD

**Issue by jesserockz** [hacs/integration#1458]
## Category

- [ ] Backend/Integration
- [ ] Frontend
- [ ] Documentation
- [ ] Bot
- [x] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

It would be good if users could easily install and share their custom_components for ESPHome. Currently there is no central location for custom_components and github links are scattered around the place.

## Implementation

How do you see this being implemented?
I think this would be very similar to HA integrations but with a different repo list and folder that they are saved in.

## Alternatives

Are there any alternative solutions or features you've considered?
This could be a feature built into the ESPHome dashboard, but the focus there is on the actual development of ESPHome and I believe that this fits with the use case of HACS.

## Additional context

Considering if people are mostly using ESPHome as an addon to HA, then the ESPHome config folder is located inside the HA config folder and the custom_components for esphome would be placed in `esphome/custom_components`

**Comment by ludeeus** [comment]
What is this?
Do you have links to documentation for it?
Are there any github repos that offer custom_components for ESP home now?

**Comment by jesserockz** [comment]
> [ESPHome](https://esphome.io) is a system to control your ESP8266/ESP32 by simple yet powerful configuration files and control them remotely through Home Automation systems.

Custom_components in ESPHome have been made to mirror the way they work in HA. It is mentioned [here](https://esphome.io/guides/contributing.html?highlight=custom_components#directory-structure) a little further down the page.

I will post an example when I find one, but like I mentioned above they only pop up (in discord) when someone asks about a specific component that is not integrated yet but someone else has built it for themselves.

**Comment by jesserockz** [comment]
[Here](https://github.com/ssieb/custom_components/) is a repo by @ssieb with a bunch of custom components.

**Comment by ludeeus** [comment]
Yeah, but that would not fit in a HACS model.
HACS requires one "Thing" pr. repo.

**Comment by jesserockz** [comment]
Also there is a list on the esphome documentation website [here](https://esphome.io/guides/diy.html#custom-components-code)

**Comment by jesserockz** [comment]
> Yeah, but that would not fit in a HACS model.
> HACS requires one "Thing" pr. repo.

I realise that and i believe given the opportunity, people would be happy to format their repos to make them compatible.

**Comment by ludeeus** [comment]
_maybe_, the same argument has been given for all added categories (and those still pending) :man_shrugging: 
If you look at <https://hacs.xyz/docs/default_repositories#netdaemon-apps> or <https://hacs.xyz/docs/default_repositories#python-scripts> there are not much

**Comment by jesserockz** [comment]
hmm, yeah. 🤷‍♂️ 
Was just an idea I had. I don't know how much work it would be for you (or others) to actually implement and maintain.

**Comment by ludeeus** [comment]
By now I have probably used somewhere between 50-100h for each of the categories in maintenance, things are simpler now than when the last one was added, but it's still much work.
Implementation is "easy"

**Comment by jesserockz** [comment]
A couple of examples:
- https://github.com/jesserockz/esphome-inkplate
- https://github.com/jesserockz/esphome-rf-bridge

Most likely there would be supporting files for HACS

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
