### ISSUE TITLE
HACS loads font from Google

### ISSUE THREAD

**Issue by tribut** [hacs/integration#1460]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.3.3
| Home Assistant version     | 0.114.1
| Installation method for HA | Docker
| Web browser                | Firefox
| Web browser version        | 80

## Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

When opening HACS, Roboto is loaded from `fonts.googleapis.com`. This is unnecessary (because HA ships is own copy of Roboto already) and a potential privacy problem. It appears to be caused by `@polymer/font-roboto@^3.0.1` from yarn.lock.

A similar issue was resolved recently in home-assistant/frontend: https://github.com/home-assistant/frontend/issues/4165, https://github.com/home-assistant/frontend/pull/5849

### Steps to reproduce

1. Open HACS
2. Observe network requests in DevTools

**Comment by ludeeus** [comment]
HACS does not have access to elements in HA.

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
