### ISSUE TITLE
BWAlarm integration installing wrong (very old, not functional) version.

### ISSUE THREAD

**Issue by Aephir** [hacs/integration#1467]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |  1.3.3
| Home Assistant version     | 0.113.3
| Installation method for HA | Core in Docker

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

The integration [BWAlarm](https://github.com/akasma74/Hass-Custom-Alarm) installs a very old version, when installing via HACS. The installed version is v1.3.6 even though it says in HACS that it will install v1.12.6.

I don't know where the issue lies, but while searching for a solution, I saw that [the author of that integration stated in the issue in their repo, that it was a HACS issue](https://github.com/akasma74/Hass-Custom-Alarm/issues/104#issuecomment-647178195).

### Steps to reproduce

1. Install HACS.
2. Install the integration as per the [guide in the repo](https://github.com/akasma74/Hass-Custom-Alarm#how-to-installation).
   1. Newest version (v1.12.6 at the time of writing) is displayed correctly in HACS, but this is not what is installed.
3. Navigate to Alarm panel in Home Assistant UI - it shows v1.3.6, and this version doesn't work in newer HA versions (as also evident from HA logs).

## Debug logs

<details>
  <summary>Logs</summary>

```text

I cannot add the log, I get an error from github:

Comment is too long (maximum is 65536 characters)
There was an error creating your Issue: body is too long (maximum is 65536 characters). 

I have uploaded the log here instead: https://raw.githubusercontent.com/Aephir/Home_Assistant-Accessory-files/master/home-assistant.log

```

</details>

**Comment by ludeeus** [comment]
Your logs does not contain the installation of the repository?

**Comment by ludeeus** [comment]
I just tried it myself, and the downloaded file has `var _VERSION = 'v1.12.6';` at line 8 in custom_component/bwalarm/resources/panel.html` as expected.

Have you cleared your cache after installing/upgrading it?

**Comment by Aephir** [comment]
Yes, cleared cache and restarted HA. As has the people in the issue I linked to (https://github.com/akasma74/Hass-Custom-Alarm/issues/104). I even tried with a browser (Iridium) that has never opened my HASS URL before.

Again, I have no clue where the problem is, I opened this issue because the best I could find was the issue in the integration repo, where the author stated that this was a HACS issue (and recommended opening an issue for HACS).

I've added the logs from when I installed, before restarting (https://raw.githubusercontent.com/Aephir/Home_Assistant-Accessory-files/master/home-assistant_2.log). I can also see that it states v1.12.6. That's just not what
shows in the UI.

**Comment by ludeeus** [comment]
If the file states it, nothing is wrong with the files or what HACS downloads.
(HACS only downloads files, so if the files have the correct content, it's not an issue with HACS.)

The issue is what you see in your browser, in most cases this is cache.
<https://github.com/akasma74/Hass-Custom-Alarm/blob/master/custom_components/bwalarm/alarm_control_panel.py#L393> uses the `custom_component/bwalarm/resources/panel.html` file, so if that is correct on your server as well, there is not much I can do on the HACS side of it (its job is to download the files)

**Comment by Aephir** [comment]
Sure, I'll link to this thread in the issue in the integration repo, and hope something good comes from it. Thanks!
