### ISSUE TITLE
Double scrollbars?

### ISSUE THREAD

**Issue by KTibow** [hacs/integration#1481]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.5.2
| Home Assistant version     | 0.114.3
| Installation method for HA | Home Assistant OS
| Web browser                | Chrome
| Web browser version        | 78.0.3904.108

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Sometimes in HACS, the area that's supposed to be scrolled is big enough to cause two scrollbars.

### Steps to reproduce

1. Go to the Frontend tab
2. Click on the Add button
3. Resize window if needed

### Screenshots

![2020-08-23-103016_1920x1080_scrot](https://user-images.githubusercontent.com/10727862/90984748-e06fd000-e52b-11ea-8930-bffded46dfd7.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

contentscript.js:951 contentscript.js: https://ourtreehouse.duckdns.org/hacs/frontend 
browser_mod.js:149 BROWSER_MOD 1.1.6 IS INSTALLED    DeviceID: 57ea5fcc-3b1c07fa
VM11426:11   HA RESTART BROWSER EXT         Version: 2.0       
content.js:121 [API CHECK] success! {"message": "API running."}
chunk.01ac4f0bc647204552a4.js:1 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
value @ chunk.01ac4f0bc647204552a4.js:1
value @ chunk.01ac4f0bc647204552a4.js:1
performUpdate @ app.664a8247.js:1
_enqueueUpdate @ app.664a8247.js:1
card-tools.js:90 CARD-TOOLS 2.1.2 IS INSTALLED  DeviceID: 57ea5fcc-3b1c07fa
hui-element.js:1 HUI-ELEMENT 1.0.1 IS INSTALLED 
layout-card.js:92 LAYOUT-CARD 1.3.1 IS INSTALLED 
button-card.js:1597   BUTTON-CARD   Version 3.3.6 
light-entity-card.js:434   LIGHT-ENTITY-CARD     Version 4.2.0       
card-mod.js:5 CARD-MOD 2.0.0 IS INSTALLED 
mini-graph-card-bundle.js:1  MINI-GRAPH-CARD  0.9.4 
203[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
custom-sidebar.js:1 Custom Sidebar is loading
frontend-202008231558.js:1416 [Violation] 'setTimeout' handler took 2050ms
custom-sidebar.js:129 GET https://ourtreehouse.duckdns.org/local/sidebar-order.yaml?rnd=2yy39uy5j356k3far12eae 404 (Not Found)
run @ custom-sidebar.js:129
setInterval (async)
(anonymous) @ custom-sidebar.js:3
custom-sidebar.js:104 Uncaught TypeError: Cannot read property 'length' of null
    at rearrange (custom-sidebar.js:104)
    at XMLHttpRequest.req.onload (custom-sidebar.js:121)
rearrange @ custom-sidebar.js:104
req.onload @ custom-sidebar.js:121
load (async)
run @ custom-sidebar.js:119
setInterval (async)
(anonymous) @ custom-sidebar.js:3
manifest.json:1 Manifest: property 'theme_color' ignored, 'var(--primary-background-color)' is not a valid color.
frontend-202008231558.js:3630 [Violation] 'requestAnimationFrame' handler took 101ms
[Violation] Forced reflow while executing JavaScript took 100ms
frontend-202008231558.js:3630 [Violation] 'setTimeout' handler took 176ms

```

</details>

**Comment by ludeeus** [comment]
unable to replicate, what size is your browser running with?
Can you try incognito to rule out any browser plugin?

**Comment by KTibow** [comment]
Still get it in incognito. My browser is 1920px by 910px.

**Comment by davidlb** [comment]
Same here on my laptop: 1366x768

**Comment by KTibow** [comment]
I think I just figured out how to solve this.
