### ISSUE TITLE
Add native automations

### ISSUE THREAD

**Issue by KTibow** [hacs/integration#1486]
## Category

- [x] Backend/Integration
- [ ] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

Add a way to add a Home Assistant automation made by someone else.

## Implementation

Basically, just under the Automations tab, with all the other scripts and daemon apps, there would be an option to add automations. They would be appended to the end of `automations.yaml`.

## Alternatives

Are there any alternative solutions or features you've considered?
Not that I can think of.

## Additional context

Nope.

**Comment by ludeeus** [comment]
This is a bad idea for several reasons and I do not see this ever being a part of HACS.

- HACS should not write to the same files as users/HA (This is solvable with an include statement).
- This will only work for YAML automation, so UI support can not be done.
- Most if not all automation requires installation-specific information like entity_id's which then needs to be changed after every update of the automation.
- I really do not see anyone creating and maintaining a full repository for a single automation.

**Comment by KTibow** [comment]
You're right. I could see this solvable by doing a couple of things:

- Wait until automation/scene/script grouping support is added to Home Assistant
- On install, ask for entity IDs
- Use GitHub Gists instead

But this really does go against HACS. I guess it was just me having a hard time finding cool automations on the forum, and looking for a central place to put them.

**Comment by KTibow** [comment]
Blueprints have now been added, do you still think this is a bad idea?
