### ISSUE TITLE
Feature: use frontend-package version in lovelace resource URI

### ISSUE THREAD

**Issue by boesing** [hacs/integration#1489]
## Category

- [X] Backend/Integration

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

To avoid browser cache issues between version upgrades of frontend packages, I'd like to propose the idea of using the release version of the package inside the resource URI.
That means, when updating "custom-foo-package" from version 1.11 to version 1.12, the URI for the lovelace resource changes from `/hacsfiles/custom-foo-package/package.js?v=1.11` to `/hacsfiles/custom-foo-package/package.js?v=1.12`.

## Implementation

Not sure if it is possible to search in already added lovelace-resources, but I think so as I remember a notification inside the HACS UI which said that the Lovelace Resources is not loaded or sth. like that.

1. As a BC one could search for the resource "without" the version inside the resource list and replace it with the new version (when updating, I would not suggest to apply this on *every* package already installed *BUT* during an update). 
2. If no resource is attached (either without version nor with the previous version), there is nothing TODO. If it is attached, remove it
3. add the new resource with the new version in the URI

## Alternatives

Nope.

## Additional context

-

**Comment by KTibow** [comment]
It already sends headers to use less caching, but I think this is a good idea, so Home Assistant loads faster.

**Comment by ludeeus** [comment]
I will not add a `?*` that will only help users in storage (UI) mode.
But it could be a popup there, same as HA has when you add resources in the UI.

**Comment by boesing** [comment]
Not sure if I can follow your idea @ludeeus, could you elaborate?

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/93026691-40780480-f608-11ea-9466-c21eea07f9a0.png)

**Comment by boesing** [comment]
I see. So this will trigger after upgrading, right? 
What about those devices which do not trigger that update?

**Comment by ludeeus** [comment]
After install/upgrade

Even for those your purposed request would have had no impact.

**Comment by boesing** [comment]
Hm, I've re-checked the `Cache-Control` headers and I am unsure but there is `no-store; max-age=0` in there.
So yes, it won't have an impact, you're right.
Closing here as the `Cache-Control` header wont cache either.
