### ISSUE TITLE
Show README if info.md not detected by default

### ISSUE THREAD

**Issue by KTibow** [hacs/integration#1493]
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

If someone forgets to add an `info.md` file or specify to use the README instead, HACS will say "No info available". It should automatically look for a README instead.

## Implementation

Whenever it can't find a file, it'll query the GitHub API for preferred README, and render it.

## Alternatives

Maybe just show something that says `You can check if there's a [README](github.com/repo/repo)` after that message.

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
