### ISSUE TITLE
Recommended to cancel the redirection to hasfiles

### ISSUE THREAD

**Issue by fineemb** [hacs/integration#1501]
## Category

- [x] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [ ] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

The current version of HASS speeds up the startup speed, but the custom cards are based on HACS. The custom cards need to be fully started after the HACS is fully started to display correctly. It takes a long time for the HACS to load.

**Comment by ludeeus** [comment]
What is the purpose of this?
The description does not make sense, is something missing from it?

**Comment by fineemb** [comment]
![01](https://user-images.githubusercontent.com/16739914/91662822-646f1c80-eb17-11ea-9667-4b8fd6238a5a.png)
Custom card due to resource redirection
After restarting HASS, you need to wait for the HACS to load to be displayed correctly.
But HACS loading takes a long time
This causes the front-end card to take a long time to display correctly

**Comment by ludeeus** [comment]
I still don't see the request here.
Sure it takes time, but it will do that anyway.

Exactly what is it that you are requesting that should change in HACS?

**Comment by fineemb** [comment]
Maybe can change the redirect(/hasfiles) time  
Which can speed up the display of custom cards

**Comment by ludeeus** [comment]
There is no redirect?

**Comment by fineemb** [comment]
![01](https://user-images.githubusercontent.com/16739914/91663359-dd23a800-eb1a-11ea-9ed8-fb314863d5db.png)

**Comment by ludeeus** [comment]
There is NO redirect?!?!

**Comment by fineemb** [comment]
redirect no problem
But it caused the custom card to take longer to loading
Hope to reduce the waiting time for loading custom cards

**Comment by ludeeus** [comment]
I give up..

**Comment by DavidFW1960** [comment]
> redirect no problem
> But it caused the custom card to take longer to loading
> Hope to reduce the waiting time for loading custom cards

HACS has to load to provide the endpoint for the /hacsfiles where custom cards are loaded. The whole point (or at least a major one) is that using this endpoint tells the browser not to cache the card so you don't have to use version numbers etc every time there is a change. So if you don't want to get this benefit then don't use HACS and deal with these version numbers etc.
You're only talking about 30 seconds right?

**Comment by fineemb** [comment]
> > redirect no problem
> > But it caused the custom card to take longer to loading
> > Hope to reduce the waiting time for loading custom cards
> 
> HACS has to load to provide the endpoint for the /hacsfiles where custom cards are loaded. The whole point (or at least a major one) is that using this endpoint tells the browser not to cache the card so you don't have to use version numbers etc every time there is a change. So if you don't want to get this benefit then don't use HACS and deal with these version numbers etc.
> You're only talking about 30 seconds right?
You're right
My idea is too radical
The disadvantages after cancellation outweigh the advantages
