### ISSUE TITLE
Frontend Initial UI Load Hanging in Chrome Browser

### ISSUE THREAD

**Issue by WeldFire** [hacs/integration#1505]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.5.2 |
| Home Assistant version     | 114.4 |
| Installation method for HA |  Python |
| Web browser                | Chrome |
| Web browser version        | 85.0.4183.83 (Official Build) beta (64-bit) |

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

When visiting the HACs panel(/hacs/entry) the browser will freeze until I kill it with task manager or Chrome offers to kill it. 
Incognito, and other browsers do not exhibit this issue.
Clearing site data under Dev Tools > Application > Clear Storage > Clear Site Data with all boxes checked doesn't fix this issue.
When profiling, it appears to be a JS infinite loop, but I can't tell exactly where.

This issue appeared when upgrading from a previous HACs version. (Maybe 1.3.0 to 1.4.x? I'm not sure :/)

### Steps to reproduce

1. Open HA in Chrome
2. Click HACS sidebar
3. Witness issue

### Screenshots

1. Issue visuals
![image](https://user-images.githubusercontent.com/293969/91909332-9779f300-ec72-11ea-93cb-18713933f483.png)

2. Chrome Task Manager
![image](https://user-images.githubusercontent.com/293969/91909405-bd9f9300-ec72-11ea-8898-c265a15d82b5.png)

3. Chrome Performance Profile
![image](https://user-images.githubusercontent.com/293969/91909653-3c94cb80-ec73-11ea-983e-5cc1f343cda3.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>
Unchecked runtime.lastError: The message port closed before a response was received.
</details>

**Comment by ludeeus** [comment]
I developed bit with chrome and have never seen this.
Try incognito window

**Comment by WeldFire** [comment]
Hello Ludeeus, as mentioned in the original post, Incognito doesn't have this issue. 

I can't figure out how Incognito doesn't break, but clearing all data in standard doesn't fix the problem :/

**Comment by ludeeus** [comment]
Oh, didn't catch that.

Then there are only 2 things that can cause it:
- Browser cahce.
- Browser plugins.

Start with disabling all browser plugins, then enabled them back again one by one

**Comment by WeldFire** [comment]
No worries!

Good idea!

Turns out it has something to do with [Qualys Browser Recorder](https://chrome.google.com/webstore/detail/qualys-browser-recorder/abnnemjpaacaimkkepphpkaiomnafldi). lol, I'm not sure why that should be interacting with the page at all without me invoking it.

In the extension it looks like it has some nasty code for bubbling itself to the top, which mayyy be the culprit, but all in all I'm just glad to have figured out how to repair it and am not really interested in getting it to work with that extension. I could see this being an issue with other extensions, but I would hope they would be implemented a bit better than this one so it would be a bit more obvious. 

Thank you for your help ludeeus! 

(Here is the plugin's code referenced previously that looks like it may be the culprit)
```
function getFrameLocation() {
    let frameLocation = "";
    let currentWindow = window;
    let currentParentWindow;
    while (currentWindow !== window.top) {
        currentParentWindow = currentWindow.parent;
        for (let idx = 0; idx < currentParentWindow.frames.length; idx++)
            if (currentParentWindow.frames[idx] === currentWindow) {
                frameLocation = ":" + idx + frameLocation;
                currentWindow = currentParentWindow;
                break;
            }
    }
    frameLocation = "root" + frameLocation;
    return frameLocation;
}
```
xD
