### ISSUE TITLE
basnijholt/lovelace-ios-dark-mode-theme

### ISSUE THREAD

**Issue by makuser** [hacs/integration#1507]
## Describe why you are flagging this

https://github.com/basnijholt/lovelace-ios-dark-mode-theme has been abandoned and/or superseded by https://github.com/basnijholt/lovelace-ios-themes which not only includes the dark theme, but also a light variant and many more color variants.

The new repository has already been added to HACS.

**Comment by ludeeus** [comment]
Had a chat with the author, this is not abandoned

**Comment by basnijholt** [comment]
I prefer to leave them both in for now because I know some users experience issues with the new themes.

**Comment by makuser** [comment]
@basnijholt Alright, good to know. Just keep in mind, that the old one is incompatible with the last few minor versions of hass. That made me look into alternatives and then I found your other theme. But it's obvious, I mean the old theme has not been updated for 10 months now, and homeassistant-frontend moved on quite a bit during that time, so...

Maybe add a note to your old theme linking to the new theme, so that users that are still on the old one can migrate to the new one?

**Comment by basnijholt** [comment]
I don't understand how you get to that 10 months, the latest commit is from 3 June 2020: https://github.com/basnijholt/lovelace-ios-dark-mode-theme/commits/master.
