### ISSUE TITLE
HACS not adding Resources entries

### ISSUE THREAD

**Issue by blhoward2** [hacs/integration#1508]
HACS has not been adding resource entries automatically during installation, which happened to me and several others on Reddit. Specifically with custom_header but I also had to with the custom button card entry. If this is intended functionality it is not working on the most recent version of HA with the most recent HACS. 

## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.5.2 / 
| Home Assistant version     | 0.114.1 / 202008231558 (frontend)
| Installation method for HA | Core/venv
| Web browser                | N/A
| Web browser version        | N/A

## Checklist

- [X ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X ] I have filled out the issue template to the best of my ability.
- [X ] I have read <https://hacs.xyz/docs/issues>
- [ X] This issue is related to the frontend of HACS.
- [X ] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

HACS has not been adding resource entries automatically during installation of cards, which happened to me and several others on Reddit. Specifically with custom_header but I also had to with the custom button card entry. If this is intended functionality it is not working on the most recent version of HA with the most recent HACS. 

### Steps to reproduce

1. Install frontend package
2. No Resource line is added and Lovelace reports the card cannot be found
3. Add the Resource line and it works

### Screenshots

N/A

## Javascript logs from your browser console

N/A.

**Comment by ludeeus** [comment]
Use the content from the frontend issue template to make this issue complete

**Comment by blhoward2** [comment]
Done. Sorry, github didn't present the templates the first time around.

**Comment by ludeeus** [comment]
And the browser console logs

**Comment by blhoward2** [comment]
I don't have browser console logs, because I've added it to my Resources line and now works fine.
