### ISSUE TITLE
Automatically add clickable links inside of release notes browser for commit hashes

### ISSUE THREAD

**Issue by alandtse** [hacs/integration#1513]
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

GitHub/GitLab release notes may include links to specific commits with more info just by including the commit hash in the markdown link. See this example for HACS commit. (71ce7917ada49c36563352817d6fa07a70bb44b0) GitHub doc [reference](https://docs.github.com/en/github/writing-on-github/autolinked-references-and-urls#commit-shas).

## Implementation

Automatically create the links like GitHub/Gitlab does by prepending `https://github.com/hacs/integration/commit/` / `https://gitlab.com/keatontaylor/alexapy/-/commit/` to markdown links.

## Alternatives

Are there any alternative solutions or features you've considered?
Integration maintainers can manually add the link in their release notes generation. I'm suspecting that's what you'll specifically decide. ;)  I'd be happy just for GitHub support.

## Additional context
HACS:
![image](https://user-images.githubusercontent.com/7086117/92433918-4165ed80-f153-11ea-82fa-01c1f83b7d4a.png)
GitHub:
![image](https://user-images.githubusercontent.com/7086117/92433960-5d698f00-f153-11ea-9b60-4b4df5e5171f.png)

**Comment by ludeeus** [comment]
HACS does not generate these notes, it's fetched from Github as is.
A developer can add whatever to those notes, so I do not see a clean/safe way of doing this.

Gihub can do it since they sit on the DB of all commits and can do a match against that.

**Comment by alandtse** [comment]
Yes, I understand you're just taking the raw body text. I'm just suggesting finding `(hash)` and just prepending the GitHub static string if it's a GitHub link. I'm not suggesting any confirmation that it's a valid hash.

**Comment by ludeeus** [comment]
Unless I can do it right (without needing to guess), I probably will not add it.
There _may_ be a header that can be sendt to get a rendered text in return

**Comment by alandtse** [comment]
SHA-256 hashes have a length of 40 when represented by ascii so I think it'd be a simple regex replace. `\([a-z0-9]{40}\)`. Alternatively you could make sure it's an incomplete markdown link. `[^]]*\([a-z0-9]{40}\)`

But if you wanted to confirm the link before rewriting it then that'd be harder.

**Comment by alandtse** [comment]
I haven't programmed in TS but I think you could run the regex replace to update the markdown.
- [During the display](https://github.com/hacs/frontend/blob/main/src/components/dialogs/hacs-update-dialog.ts#L73)

```typescript
            ? this._releaseNotes.map(
                (release) => html`<details>
                  <summary
                    >${localize("dialog_update.releasenotes").replace(
                      "{release}",
                      release.tag
                    )}</summary
                  >
                  ${markdown.html((release.body).replace(/[^]]*\(([a-zA-Z0-9]{40})\)/, "[$&](https://github.com/${repository.full_name/commit/}$&",g)))}
                </details>`
              )
            : ""}

```

I did this in GitHub so may have messed up a parentheses.

**Comment by ludeeus** [comment]
Sure, that _may_ work, but it will be "guessing"
Something like <https://docs.github.com/en/rest/overview/media-types#html> is stable

**Comment by alandtse** [comment]
True, I guess the downside to body_html is you have to parse it as HTML instead of markdown but it's basically done.

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
