### ISSUE TITLE
HACS does not load frontent extensions when booted with no internet

### ISSUE THREAD

**Issue by wmap-gussun** [hacs/integration#1515]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.5.2|
| Home Assistant version     |0.111.2|
| Installation method for HA | Docker

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

This version of HACS will not load custom cards and plugins if homeassistant is started without internet connection.
Some previous version did load custom cards even with no internet connection.
The homeassistant log under developer tools show HACS errors trying to connect to github, and failing.
Log also states that the github token is invalid.
I personally use homeassistant without internet access alot.

With this new behaviour you cannot reboot your homeassistant with no internet connection because when it boots again no custom cards will work.

### Steps to reproduce

1. Install HACS
2. Add custom cards
3. Remove internet connection
4. Reboot homeassistant

## Debug logs

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
Fixed here https://github.com/hacs/integration/commit/b9356123d3a26c436d44cf28185d341ba775ac69#diff-53cd6bf3e4a9a52a7b2b5bda23565957

**Comment by wmap-gussun** [comment]
Great work! Thank you!
