### ISSUE TITLE
RFC: Add more to checks

### ISSUE THREAD

**Issue by KTibow** [hacs/integration#1517]
## Category

- [ ] Backend/Integration
- [ ] Frontend
- [ ] Documentation
- [ ] Bot
- [x] Other

## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

One category, multiple ideas.

## The idea

Add more strict checks to the PR checks for `hacs/default`:
- README or info.md is specified
- No useless `info.md`
- Only one custom component
- Custom component directory name matches repo name
- No changes that aren't added to a release
- Something is in `.github/workflows`

## Implementation

Add more checks to https://github.com/hacs/default/tree/master/scripts and https://github.com/hacs/default/tree/master/.github/workflows

## Alternatives

Not required at all.

**Comment by ludeeus** [comment]
The "No useless info.md" I like, the others I don't really see a need for them.
But I'm not going to add more rules unless needed because I want them.

So I'll let this sit for a while giving both users and developers a chance to see it.

**Comment by KTibow** [comment]
This might be better to put on the issue template checklist, and maybe add an `(if makes sense)` to the end of some of them...

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
