### ISSUE TITLE
iantrich/untappd-card - no longer exists

### ISSUE THREAD

**Issue by nanobra1n** [hacs/integration#1519]
## Describe why you are flagging this
Getting errors in the log for HACS 

iantrich/untappd-card - GitHub returned 404 for https://api.github.com/repos/iantrich/untappd-card

Repository https://github.com/iantrich/untappd-card/ indeed does not exists

**Comment by ludeeus** [comment]
This is not a default repository in HACS <https://hacs.xyz/docs/default_repositories> just remove it in your installation.

**Comment by mf-social** [comment]
@ludeeus - there is a problem here somewhere, I have never installed the iantrich/untappd-card, nor do I have anything 'stray' in my www folder, yet I still get this error several times a day.
