### ISSUE TITLE
Possible Uninstallation Change Needed

### ISSUE THREAD

**Issue by IIAIronWolf** [hacs/integration#1520]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               1.5.2|
| Home Assistant version     0.115.0b6 |
| Installation method for HA Home Assistant OS|

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

During the installation of HomeKit Bridge I was continually getting an error that the wyzeapi integration was missing and HomeKit failed to setup each time. I believe this is because HACS is not fully uninstalling integrations. There is no trace of wyzeapi in my custom_components folder, configuration.yaml or anywhere else I searched. You can see more info here: https://github.com/JoshuaMulliken/ha-wyzeapi/issues/82

The HomeKit issue was fixed with the HomeKit dev in home-assistant/core, but it is still concerning that there are traces of previously installed HACS integrations hiding out on my Home Assistant server.

If this needs to be an issue somewhere else, please help me know where to report this to.

### Steps to reproduce

1. Install the wyzeapi HACS integration.
2. Uninstall it. 
3. Try to install HomeKit Bridge (official HA integration).
4. Check logs to see that HomeKit Bridge setup failed due to the inability to find the missing wyzeapi integration. 

Note: this is currently reproducible on the 0.114 version of Home Assistant Core, but will not be reproducible when 0.115 releases. The issue of wyzeapi still hiding in my server will be there, but these steps to reproduce will not work since the HomeKit dev updated the code to not fail when it can't find an integration.

## Debug logs

<details>
  <summary>Logs</summary>

```

homeassistant.loader.IntegrationNotFound: Integration 'wyzeapi' not found.

```

</details>

**Comment by ludeeus** [comment]
On uninstallation HACS just deletes the directory under custom_components.
You still have that integration under HA UI -> configuration -> integrations, remove it from there.

**Comment by IIAIronWolf** [comment]
@ludeeus unfortunately that is not true. It is not under integrations, entities, or devices...

**Comment by IIAIronWolf** [comment]
Also unfortunately, I cannot report this to Home Assistant since HACS is not officially support and they do not allow issue reports for unofficial integrations/add-ons/etc.
