### ISSUE TITLE
Empty screen in hacs after update to 0.114.4

### ISSUE THREAD

**Issue by impestrator** [hacs/integration#1523]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version                |1.5.0|
| Home Assistant version     |0.114.4|
| Installation method for HA||Home Assistant Supervised|

## Describe the issue

After I updated HASSIO to 0.114.4, I noticed that I only get a empty screen after clicking on hacs in the left panel. Usually I got the information about hacs integrations etc.

Under “integrations” I just can see two pending updates. Version 1.5.0 is running, but I cannot upgrade. Logs doesn´t tell me anything about any hacs issues. I´ve tried to reinstall hacs without success, I´ve also tried three different browsers either on Windows or Ubuntu. I´ve also restored a backup with hassio 0.113.3. Within that snapshot, hacs is working, but I changed a lot of stuff since then, so I´d like to make it work also in the new version.

**Comment by ludeeus** [comment]
Add the logs from browser console.

**Comment by impestrator** [comment]
this what I got from browser console:

`Uncaught (in promise) TypeError: Cannot read property 'title' of undefined
    at frontend-202008231427.js:1317
    at Array.forEach (<anonymous>)
    at Ur (frontend-202008231427.js:1317)
    at HTMLElement.value (frontend-202008231427.js:2139)
    at HTMLElement.update (frontend-202008231427.js:1)
    at HTMLElement.performUpdate (frontend-202008231427.js:1)
    at HTMLElement._enqueueUpdate (frontend-202008231427.js:1)`

**Comment by ludeeus** [comment]
I'm not able to reproduce that, upgrade HACS manually by following the installation guide.

**Comment by impestrator** [comment]
Installing hacs manually by following the installation guide fixed the issue. Thank you
