### ISSUE TITLE
HACS not automatically loading Lovelace resources

### ISSUE THREAD

**Issue by flyize** [hacs/integration#1529]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.5.2
| Home Assistant version     | .114.4
| Installation method for HA | Docker

## Checklist

- [x]  I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I have tried adding a couple of frontend repos into HACS (Lovelace Valetudo Map Card, Vacuum Card), and HACS isn't adding the resources for any of them.  I'm running Lovelace in storage mode.  I have not seen any errors in the Chrome console when adding.

### Steps to reproduce

1. Install Vacuum Card
2. Nothing shows when trying to add new custom card
3. No resources shown under Configuration > Lovelace Dashboards > Resources

## Debug logs

<details>
  <summary>Logs</summary>

```

Not sure how to just pull HACS logs

```

</details>

**Comment by ludeeus** [comment]
Logs are not just for errors, paste the console logs for when you are adding these.

**Comment by flyize** [comment]
@ludeeus Apologies, but what exactly is meant by console logs?  When researching this issue, I saw folks ask for Chrome console logs.  Is that what you mean, or is there an HA/HACS console log that is needed?

**Comment by ludeeus** [comment]
Regular browser console

**Comment by flyize** [comment]
I turned on Verbose to get anything at all
`[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
frontend-202008231558.js:1317 [HACS:_installRepository] plugin
frontend-202008231558.js:1317 [HACS:_installRepository] auto-gen`

**Comment by ludeeus** [comment]
I see, you are not in storage mode, you are in auto-gen.
You need to take control of you UI before it will work

**Comment by flyize** [comment]
Ahh, I think my newness is showing!  I assumed if I wasn't in YAML mode, I was in storage mode.  I will research the differences.

**Comment by flyize** [comment]
@ludeeus I just tried setting the lovelace mode to storage in configuration.yaml and restarting.  After that, I uninstalled and reinstalled the repo.  I had no change.

I saw another mention that just taking control of the default dashboard will set it in storage mode.  So I attempted that, restarted, and again no change.

With either method, the vacuum card was not available to be added to my dashboard, nor was the file listed in Configuration > Lovelace > Resources.

**Comment by ludeeus** [comment]
Then your console logs have changed, paste new logs.

**Comment by flyize** [comment]
I current have 'taken over' the default dashboard, but do not have lovelace mode set to storage in configuration.yaml.  Logs appear to be the same.
`[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
frontend-202008231558.js:1317 [HACS:_installRepository] plugin
frontend-202008231558.js:1317 [HACS:_installRepository] auto-gen`

**Comment by ludeeus** [comment]
As long as you are in auto-gen, HACS will not even try to add it.
Can you try adding a dummy resources in the Lovelace UI to see if that helps?

**Comment by flyize** [comment]
I'm sorry, but not sure I follow.

In between your reply and mine, I added storage mode to the configuration.yaml file.  Now I see an error in HACS that 10 Lovelace are not properly loaded in Lovelace.  No idea if that's helpful or obvious.

**Comment by ludeeus** [comment]
Sounds like you are in storage mode now :+1: 

<https://hacs.xyz/docs/faq/status_not_loaded> have a look here.

**Comment by flyize** [comment]
Clicking reinstall did not fix the issue.

**Comment by ludeeus** [comment]
Then your console logs have changed, paste new logs.

**Comment by flyize** [comment]
Ahhhh!  It seems it did fix the issue, but I needed to refresh the browser.  Thank you!
