### ISSUE TITLE
hacs/integration/action@1.6.0 not working

### ISSUE THREAD

**Issue by xaviml** [hacs/integration#1542]
## Installation details
https://github.com/xaviml/controllerx/runs/1141301727

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.0 and master
| Home Assistant version     | Not relevant to this issue
| Installation method for HA | Not relevant to this issue

## Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

The hacs/integration/action stopped working. You can see in [here](https://github.com/xaviml/controllerx/runs/1141301727) in more detail what the error is.

### Steps to reproduce

1. Add a GitHub action that uses hacs/integration/action@master or hacs/integration/action@1.6.0
2. Execute the action

## Debug logs

<details>
  <summary>Logs</summary>

```
::INFO:: Category: appdaemon
::INFO:: Repository: xaviml/controllerx
Traceback (most recent call last):
  File "/hacs/action.py", line 142, in <module>
    LOOP.run_until_complete(preflight())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/hacs/action.py", line 123, in preflight
    await validate_repository(repository, category, ref)
  File "/hacs/action.py", line 136, in validate_repository
    await register_repository(repository, category, ref=ref)
  File "/hacs/custom_components/hacs/helpers/functions/register_repository.py", line 26, in register_repository
    repository = RERPOSITORY_CLASSES[category](full_name)
  File "/hacs/custom_components/hacs/repositories/appdaemon.py", line 19, in __init__
    self.content.path.local = self.localpath
  File "/hacs/custom_components/hacs/repositories/appdaemon.py", line 26, in localpath
    return f"{self.hacs.core.config_path}/appdaemon/apps/{self.data.name}"
AttributeError: type object 'HacsCore' has no attribute 'config_path'
```

</details>

**Comment by ludeeus** [comment]
It's fixed in `main`

**Comment by xaviml** [comment]
Thanks @ludeeus. I confirm it is working with the "main" branch: https://github.com/xaviml/controllerx/runs/1142550915

**Comment by Misiu** [comment]
@ludeeus thank you for the fix :)
