### ISSUE TITLE
No URL field when adding custom repo

### ISSUE THREAD

**Issue by nrehn** [hacs/integration#1566]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.0 |
| Home Assistant version     | 0.116 |
| Installation method for HA | HassOS |
| Web browser                | Chrome |
| Web browser version        | 85.0.4183.121 |

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

When adding custom repo there is no field to type URL.

### Steps to reproduce

1. Go to any of the sections (integrations, frontend, automation).
2. Click on the 3 dots in the top right corner.
3. Select "Custom repositories"
4. No field to add URL.

### Screenshots

![image](https://user-images.githubusercontent.com/22245798/95446690-ec3f1680-0960-11eb-90e4-d6ac914c2d88.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

No logs on this.

```

</details>

**Comment by ludeeus** [comment]
"Add custom repository URL" _is_ the URL field

**Comment by nrehn** [comment]
Ahh sorry, my bad.. Thanks
