### ISSUE TITLE
Installed repos that are archived shouldn't get flagged as errors

### ISSUE THREAD

**Issue by agneevX** [hacs/integration#1573]
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

Installed repositories that are archived should not show up in logs as errors.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/19761269/95678410-17886680-0bea-11eb-9c8a-112a3d8c7de8.png">

There are simply no errors.

## Implementation

Should be `WARNING` instead.

## Alternatives
N/A

**Comment by QNimbus** [comment]
I agree with this issue - however as a workaround in the meantime you could probably remove the offending repository from HACS. Only I haven't been able to find the `maykar/custom-header` in the `hacs/hacs.repositories` file.

**Comment by agneevX** [comment]
> you could probably remove the offending repository from HACS

Why?

**Comment by KTibow** [comment]
Made a PR: #1775
