### ISSUE TITLE
Dismiss/Hide/Ignore Repository Updates

### ISSUE THREAD

**Issue by bittles** [hacs/integration#1580]
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

Some integrations I have I would prefer to not update for a variety of reasons.  Maybe the new version I'm on has been stable and working for a long time, or there is an introduced breaking change to my specific config.  It would be very nice to have the option of being able to dismiss or hide updates by repository on the main HACS page in order to prevent accidental updates or just to have a cleaner interface.

## Implementation

I could see this being similar to the dismiss button used currently on the repository pages.  Then, if you wanted to update in the future you could go to the repository category that it is in and update it like you can from that page currently.

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
