### ISSUE TITLE
dual-thermostat obsolete and no longer maintained

### ISSUE THREAD

**Issue by PD75** [hacs/integration#1587]
## Describe why you are flagging this
**On the repository page it says:**
Starting with HA 0.103, HA now defines only one entity for the Z-Wave thermostats thus this card is no longer needed. Use the native card instead. Card will no longer be maintained.

_This template should **only** be used if a repository **needs** to be removed/blacklisted from HACS_

https://github.com/enriqg9/dual-thermostat

**Comment by ludeeus** [comment]
Removed
