### ISSUE TITLE
ollo69/ha-smartthinq-sensors

### ISSUE THREAD

**Issue by robertfgoodworth** [hacs/integration#1588]
## Describe why you are flagging this

_This template should **only** be used if a repository **needs** to be removed/blacklisted from HACS_

I'm removing this integration in the hope that after I install again it might work completely, It finds my LG 16Kg washer, but the error and the one i really wanted "completed" does not work. just today 3 loads completed, got a message on my phone yet nothing in the lg_washer completed entity.

**Comment by ludeeus** [comment]
Report issues with it here https://github.com/ollo69/ha-smartthinq-sensors/issues
