### ISSUE TITLE
Expose Personal Access Token to options for HACs integration.

### ISSUE THREAD

**Issue by Bodge-IT** [hacs/integration#1595]
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea
A better way for users to fix a change in Personal Access Token (PAT) resulting in HttpStatusCode.UNAUTHORIZED errors when trying to add a new repo to HACS.

A good description of what you are suggesting.
Allow for renewal/change/update of the PAT without first having to uninstall/reinstall HACS & then reboot HomeAssistant.  At present it(PAT field) is only presented to user during install process.

## Implementation
How do you see this being implemented?
By exposing the Personal Access token field in the config options of the HACS integration.

## Alternatives
A setting in HACS itself under the 3 dots?

## Additional context

Better user experience.  Maybe also improve the reported error, HttpStatusCode.UNAUTHORIZED doesn't mean much to some especially when there is no config for authorisation visible anywhere in HACS.

**Comment by ludeeus** [comment]
PAT has been removed for UI setups, it has been replaced by device OAuth flow which will be in the next release.
