### ISSUE TITLE
HACS frontend cards only visible after refreshing the page

### ISSUE THREAD

**Issue by DasBootU96** [hacs/integration#1597]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.6.0
| Home Assistant version     |0.116.4
| Installation method for HA |https://github.com/home-assistant/operating-system/releases/download/4.14/hassos_ova-4.14.vhdx.gz
| Web browser                |Edge/Brave/Chrome
| Web browser version        |Version 86.0.622.48 (Official build) (64-bit) / Version 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit) / Version 86.0.4240.111 (Official Build) (64-bit)

## Checklist

- [v] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [v] I have filled out the issue template to the best of my ability.
- [v] I have read <https://hacs.xyz/docs/issues>
- [v] This issue is related to the frontend of HACS.
- [v] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I’ve added some HACS front ends like weather card and upcoming media card (using radarr/sonarr/kodi integrations).

When opening the home assistant webpage, these HACS front end cards are not visible. When the page is refreshed, the HACS integrations show up. Usually.

Same behavior in different browsers Edge/Brave/Chrome. Also same on Android Chrome and Android companion app. It does not matter if I connect (ssl:443) to the duckdns.org name or home assistants ip address (8123). 

### Steps to reproduce

1. Install any HACS frontend
2. Configure it in LoveLace
3. Open home assistant web page
4. Notice missing HACS entity. Press F5. Entity usually shows. F5 again and sometimes HACS entity is gone.

### Screenshots

Here is an animated GIF that shows missing entities when loaded. Pressing F5 will usually show them. This is just an example of the upcoming media cards, but I see the same behavior for others like weather card or the simple thermostat.

![m3jQ5wgOGo](https://user-images.githubusercontent.com/54699211/96918339-74b5cf00-14aa-11eb-89bf-5bf32fa2af26.gif)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

Followed guide https://support.google.com/docs/thread/1873663?hl=en

Errors from 'recently added episodes' and Kodi who want to use http instead of ssl https. 
This only happens on this page. 
The page where HACS 'weather card' and 'simple thermostat' live, show console message: No issues detected so far, yet they are not visible.

10Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure element '<URL>'. This request was automatically upgraded to HTTPS, For more information see <URL>
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://192.168.1.17:8080/image/image%3A%2F%2Fsmb%253A%252F%252Fnas.my.domain%252FMoviesAndSeries%2524%252FTelevision%252FStar%2520Trek-%2520Discovery%252Ffanart.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://192.168.1.17:8080/image/image%3A%2F%2Fsmb%253A%252F%252Fnas.my.domain%252FMoviesAndSeries%2524%252FTelevision%252FThe%2520Third%2520Day%252Ffanart.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://192.168.1.17:8080/image/image%3A%2F%2Fsmb%253A%252F%252Fnas.my.domain%252FMoviesAndSeries%2524%252FTelevision%252FThe%2520Third%2520Day%252Ffanart.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://192.168.1.17:8080/image/image%3A%2F%2Fsmb%253A%252F%252Fnas.my.domain%252FMoviesAndSeries%2524%252FTelevision%252FThe%2520Third%2520Day%252Ffanart.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://192.168.1.17:8080/image/image%3A%2F%2Fsmb%253A%252F%252Fnas.my.domain%252FMoviesAndSeries%2524%252FTelevision%252FThe%2520Third%2520Day%252Ffanart.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://image.tmdb.org/t/p/original/AfgTcW4C6gq6JyUj6KcEs3ZBgeb.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://image.tmdb.org/t/p/original/8sEsY2btFsYULAS0dl21gy64qzQ.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://image.tmdb.org/t/p/original/aO5ILS7qnqtFIprbJ40zla0jhpu.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://image.tmdb.org/t/p/original/v8Nf6Y1qL1Q3PWTBezXNPPaXqza.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://image.tmdb.org/t/p/original/rFDWMS8WwAxvFkn8txGDjnZRhkl.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
2/lovelace/media:1 GET https://192.168.1.17:8080/image/image%3A%2F%2Fsmb%253A%252F%252Fnas.my.domain%252FMoviesAndSeries%2524%252FTelevision%252FStar%2520Trek-%2520Discovery%252Ffanart.jpg net::ERR_CONNECTION_CLOSED



```

</details>

**Comment by ludeeus** [comment]
Use `/local/community/` instead of `/hacsfiles/`, then run the test again.

**Comment by DasBootU96** [comment]
Changed ```/hacsfiles/``` to ```/local/community/``` like in the screenshot below, but still the same behavior.

![hacstolocalcommunity](https://user-images.githubusercontent.com/54699211/96923796-0d038200-14b2-11eb-8c92-48d36c774eb3.JPG)

**Comment by ludeeus** [comment]
Then you are no longer using HACS, so it's not a HACS issue ;)

I suggest you open a bug on the HA frontend (or try the current HA beta to see if that solves it for you) :+1:

**Comment by DasBootU96** [comment]
you ***are*** fast :) Thanks

**Comment by mike391** [comment]
> Use `/local/community/` instead of `/hacsfiles/`, then run the test again.

/custom_components/hacs/helpers/classes/frontend_view.py
Generates urls using `/hacsfiles/`

I changed that and it fixed it for me....

**Comment by DasBootU96** [comment]
It was a bug, now fixed in Home Assistant 0.117

More:
https://github.com/home-assistant/frontend/issues/7384
https://github.com/home-assistant/frontend/pull/7407
https://github.com/home-assistant/frontend/issues/7452

**Comment by mike391** [comment]
I'm running 0.117.  I actually upgraded to .117 and then upgraded hacs,
maybe that caused it?

**Comment by DasBootU96** [comment]
Don't know Mike, try opening a topic here https://community.home-assistant.io/c/configuration/frontend/33

Maybe others have had the same or can give better advice.
