### ISSUE TITLE
USA-RedDragon/badnest

### ISSUE THREAD

**Issue by camui-alexandru** [hacs/integration#1601]
The reposotiry doesn't exist no more.

**Comment by Ascariota** [comment]
Same issue for me

**Comment by ludeeus** [comment]
This is not a default repo, and can therefore not be removed here, remove it from your custom repositories:
 - https://hacs.xyz/docs/faq/custom_repositories

- https://hacs.xyz/docs/default_repositories
- https://github.com/hacs/default
