### ISSUE TITLE
Provide a way to keep in sync the linters with Home Assistant

### ISSUE THREAD

**Issue by tetienne** [hacs/integration#1604]
## Category

- [ ] Backend/Integration
- [ ] Frontend
- [ ] Documentation
- [x] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

To increase quality of the custom components available through HACS, today their is already the hassfest and the validate Github Action. But looking at different custom components repositories, I notice that everybody  use (or not) their own linter rules. And so the code quality is not the same as the one we have on the Core repository.

It would be great to have a way to share or keep in sync the linter rules used by HA Core repository.

## Implementation
* Create an action, that run the same linters with the same rules used by HA.
* Create a pre-commit that run the same linters with the same rules used by HA.

## Alternatives

* If not automated, a good start would be to update ̏https://github.com/custom-components/blueprint`, but it does not concern HACS.

**Comment by ludeeus** [comment]
I don't think this belongs here, the mentioned blueprint would be a better place.

Anyway, thanks for your suggestion :+1:
