### ISSUE TITLE
HACS GitHub Action: Don't check whether issues are enabled for forks

### ISSUE THREAD

**Issue by KTibow** [hacs/integration#1606]
## Category

- [ ] Backend/Integration
- [ ] Frontend
- [ ] Documentation
- [ ] Bot
- [x] Other

## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

Don't check whether issues are enabled for forks. If the current repo is a fork, and issues aren't enabled, don't fail.

## Implementation

When you ask GitHub whether or not issues are enabled, also check whether it's a fork. If it's a fork, remove the "issues not enabled" message and don't fail.

## Alternatives

Just turn it into a warning.

**Comment by KTibow** [comment]
oops accidentially pressed enter, i'll fill in the details.

**Comment by ludeeus** [comment]
The action is used for /default
It needs to fail there

**Comment by KTibow** [comment]
Could there be an env var to just disable it?

**Comment by ludeeus** [comment]
Yes, but before I change it, I want to convert it to a composite action

**Comment by KTibow** [comment]
What do you mean? What would it have?

**Comment by ludeeus** [comment]
https://github.blog/changelog/2020-08-07-github-actions-composite-run-steps/

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/97625264-93771100-1a28-11eb-8e9d-d38a509e3232.png)
Takes time to convert...

**Comment by KTibow** [comment]
So is there anything stopping this from getting beta tested by people?

**Comment by ludeeus** [comment]
Well, it's only 10% done, so there is that? :smile: 

Will probably have converted enough later this week to publish it as a beta action aimed at replacing the current.

**Comment by KTibow** [comment]
Sounds good. By the way, you might be able to make any `clone`s quicker with `--single-branch`, `--branch`, and `--fetch-depth`.

**Comment by ludeeus** [comment]
At the point of cloning I don't know the branch, depth I already have for all of them, but sure :+1: 
It's not the cloning that takes time, it's running hassfest and HACS load test :smile:

**Comment by ludeeus** [comment]
The new action does currently not check fork at all, I'll reserve that to the hacs/default repo instead :+1:
<https://github.com/marketplace/actions/hacs-action>

**Comment by KTibow** [comment]
Sounds good! Why would you want to do the `requirements` check? Python builtins can be very useful.

**Comment by ludeeus** [comment]
Builtins are fine, using 3.party imports that overwrites them, not so much

**Comment by KTibow** [comment]
And what exactly does this mean?
> ✅ This day ends with an 'y' (Sunday)

**Comment by ludeeus** [comment]
That this day ends with the character 'y'

**Comment by KTibow** [comment]
Why does it check for that?

**Comment by ludeeus** [comment]
1) It does not check
2) For fun
