### ISSUE TITLE
GitHub returned 404 for https://api.github.com/repos/iantrich/untappd-card

### ISSUE THREAD

**Issue by fribse** [hacs/integration#1613]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.0
| Home Assistant version     | 0.116.4
| Installation method for HA | Supervised, VM on PVE

## Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I keep seeing this about the untappd card, if I go and search github for it I find it, so it's available somehow.
It is only shown once in the logs.
I do not have the untappd card installed.

### Steps to reproduce

1. Installed HACS
2. No further actions

## Debug logs

<details>
  <summary>Logs</summary>

```
Logger: custom_components.hacs.factory
Source: custom_components/hacs/operational/factory.py:27
Integration: HACS (documentation, issues)
First occurred: 01.35.42 (1 occurrences)
Last logged: 01.35.42
iantrich/untappd-card - GitHub returned 404 for https://api.github.com/repos/iantrich/untappd-card 

Logger: custom_components.hacs.repository.plugin.iantrich.untappd-card
Source: custom_components/hacs/helpers/functions/validate_repository.py:40
Integration: HACS (documentation, issues)
First occurred: 01.35.42 (1 occurrences)
Last logged: 01.35.42
GitHub returned 404 for https://api.github.com/repos/iantrich/untappd-card 
```

</details>

**Comment by ludeeus** [comment]
Removed it from custom repositories and the error is gone.
https://hacs.xyz/docs/faq/custom_repositories
