### ISSUE TITLE
 Add repositoty panel missing input.

### ISSUE THREAD

**Issue by ssirkakriss** [hacs/integration#1622]
| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.1
| Home Assistant version     | 0.117.2
| Installation method for HA | Nuc Home assistant OS , formally HassOS  
| Web browser                | Crome 
| Web browser version        | 86.0.4240.111

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue
The add repository panel is missing the repository field.

### Steps to reproduce
This happened after removing the only two custom integrations that I had in my list. I wasn't using them, so I removed.

![hacs-1](https://user-images.githubusercontent.com/32778627/97955028-1ffc3900-1d73-11eb-9a65-f6fe8ccd6a02.PNG)

## Javascript logs from your browser console
[java.txt](https://github.com/hacs/integration/files/5479539/java.txt)

PASTE YOUR DEBUG LOGS HERE

No errors in home-assistant.log

**Comment by ludeeus** [comment]
It's not missing, I can see it in your screenshot (to the right of the dropdown)

**Comment by ssirkakriss** [comment]
![hacs3](https://user-images.githubusercontent.com/32778627/98022033-15718c00-1dd3-11eb-9953-d179b384e9c8.PNG)

There is No where to enter a git repository on the panel.

Where do you see the place to enter a repository on this screen shot?

**Comment by ssirkakriss** [comment]
I'm an idiot.

Sorry, seems I'm due for a eye examination.
