### ISSUE TITLE
Validation is failing on actions

### ISSUE THREAD

**Issue by troykelly** [hacs/integration#1628]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |
| Home Assistant version     |
| Installation method for HA |

## Checklist

- [ ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ ] I have enabled debug logging for my installation.
- [ ] I have filled out the issue template to the best of my ability.
- [ ] I have read <https://hacs.xyz/docs/issues>
- [ ] This issue is related to the backend of HACS.
- [ ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

HACS Validation is failing

### Steps to reproduce

1. Run HACS Validation

## Debug logs

<details>
  <summary>Logs</summary>

```

Traceback (most recent call last):
  File "/hacs/action.py", line 10, in <module>
    from custom_components.hacs.hacsbase.configuration import Configuration
  File "/hacs/custom_components/hacs/__init__.py", line 13, in <module>
    from .operational.setup import (
  File "/hacs/custom_components/hacs/operational/setup.py", line 8, in <module>
    from homeassistant.helpers.event import async_call_later
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/event.py", line 48, in <module>
    from homeassistant.helpers.template import RenderInfo, Template, result_as_boolean
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/template.py", line 34, in <module>
    from homeassistant.helpers import config_validation as cv, location as loc_helper
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/config_validation.py", line 534, in <module>
    def template(value: Optional[Any]) -> template_helper.Template:
AttributeError: partially initialized module 'homeassistant.helpers.template' has no attribute 'Template' (most likely due to a circular import)

```

</details>

**Comment by MatthewFlamm** [comment]
#1623 changed the order of importing in the module that has the ultimate circular import sequence. Im not sure if the fix should rather be in homeassistant to prevent the circular import.

**Comment by ludeeus** [comment]
was fixed in the action container earlier today
