### ISSUE TITLE
After installing HACS it disappears from the side bar and not working

### ISSUE THREAD

**Issue by nikandgr** [hacs/integration#1640]
## Describe the issue

I had been using HACS for months. After an HA update it dissappeared from my side bar. I removed everything and reinstalled it again. After installation is shows on by side bar fro seconds and then it dissapears. I may be able to load hacs for a few seconds but then it disappears again. I have tried unistalling and reinstalling for several time but still the same. I get the following error in HA logs:
Logger: custom_components.hacs.data
Source: custom_components/hacs/hacsbase/data.py:117
Integration: HACS (documentation, issues)
First occurred: 2:20:53 PM (3 occurrences)
Last logged: 2:21:19 PM

[Expecting value: line 1 column 1 (char 0)] Restore Failed!
 Can you please help me to fix this ?
Regards Nick

**Comment by ludeeus** [comment]
One or more of the data files HACS uses has been corrupted (is blank), find the blank file under `/config/.storage/` and delete it or restore it from a backup (it will be named something with "hacs").
