### ISSUE TITLE
Frontend - integration not found?

### ISSUE THREAD

**Issue by vahaldor** [hacs/integration#1651]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.2.
| Home Assistant version     |  HassOS 4.16
| Installation method for HA | Rpi
| Web browser                | chrome
| Web browser version        | 86.0.4240.193

## Checklist

- [ Yes] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [Yes ] I have filled out the issue template to the best of my ability.
- [ Yes] I have read <https://hacs.xyz/docs/issues>
- [ Yes] This issue is related to the frontend of HACS.
- [ Yes] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I have a clear installation of HACS with circadian lightning only. I tried to install hacs several times as it did not launched quickly (neverending starting etc., common troubles I see all around).

It seems to work but returns all the time this error that is related to frontend. Setup.py launches front end on line 139, the line 138 is a note.

### Steps to reproduce

It returns this error, I cannot reproduce the steps.

### Screenshots

![image](https://user-images.githubusercontent.com/6329152/99144188-1670ac00-2664-11eb-8a0c-7b38e1e1c144.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

2020-11-14 10:18:28 ERROR (MainThread) [homeassistant.setup] Setup failed for resources: Integration not found.

PASTE YOUR DEBUG LOGS HERE

```

</details>

<!-- IssueTemplateID: issue_frontend -->

**Comment by ludeeus** [comment]
This is not a issue, and not related to HACS
You have not placed `resources:` in the correct place.

**Comment by vahaldor** [comment]
Ok. Would you be so kind and help me what is the correct place? Thanks

**Comment by ludeeus** [comment]
Look at lovelace documentation, or don't use YAML for lovelace.

**Comment by vahaldor** [comment]
Thank you for your help.
