### ISSUE TITLE
Improve `hacsfiles` caching

### ISSUE THREAD

**Issue by bdraco** [hacs/integration#1653]
One of my installs loads slow on mobile and I did some investigating and narrowed part of the issue  down to the frontend having to re-download 9 js files in `/hacsfiles/...`

I'm trying to come up with a way to solve caching issue with the frontend files being loaded every time because of the `custom_components.hacs.webresponses.category.async_serve_category_file` explicitly disabling caching which I assume is to ensure updates can happen without clearing browser cache.

```
                response.headers["Cache-Control"] = "no-store, max-age=0"
                response.headers["Pragma"] = "no-store"
```

In my install I have 9 included JS files like:

`/hacsfiles/lovelace-card-tools/card-tools.js`

I'm thinking one way to allow caching would be do so something like

`/hacsfiles/id-<HASH>/lovelace-card-tools/card-tools.js`

Then any url that matches `/hacsfiles/id-` could have `id-<HASH>` stripped.

When the `card-tools.js` file changes, recalculate the hash of the file contents and change the url in the frontend if needed.

**Comment by ludeeus** [comment]
Files are requested by browser clients.
There are no way of signaling that out to all (both connected, and disconnected clients).

**Comment by bdraco** [comment]
I've been digging around for a way to trigger a "frontend update" when lovelace resources are updated but I haven't found a good way to do it.

My workaround was to switch out `/hacsfiles` for `/local/community`.

**Comment by ludeeus** [comment]
I have spent a lot of time on figuring out _something_ in the past, but nothing was stable enough for me to implement without it causing issues for disconnected clients / mobile apps
