### ISSUE TITLE
'Go now' dialog box too big

### ISSUE THREAD

**Issue by PierreScerri** [hacs/integration#1656]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.2
| Home Assistant version     | 0.117.6
| Installation method for HA | OS
| Web browser                | Chrome (ios)
| Web browser version        | 86.0.4240.93

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A clear and concise description of what the issue is.

Selecting 'Actions' in HACS tab open a dialog box with a countdown that is too big for the Screen.
The 'Go Now' button is only partially visible (see screenshot)
This happens on all browsers and in the Companion app.

### Steps to reproduce

1. Open Chrome in iPhone
2. Browse to HA
3. Select HACS icon from sidebar
4. Select 'Addons'
 
### Screenshots

![IMG_7790](https://user-images.githubusercontent.com/34303331/99250919-c84adc80-280c-11eb-9aec-979d44f27123.PNG)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by KTibow** [comment]
Did some experimenting, found the root cause, sending in a PR.

**Comment by PierreScerri** [comment]
Thanks
