### ISSUE TITLE
Frontend main page with incorrect colors 

### ISSUE THREAD

**Issue by pedrolamas** [hacs/integration#1657]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.6.2
| Home Assistant version     |0.117.6
| Installation method for HA |Docker container
| Web browser                |Microsoft Edge (Dev channel)
| Web browser version        |88.0.692.0

## Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I'm using the [Google Dark Theme](https://github.com/JuanMTech/google_dark_theme/blob/master/themes/google_dark_theme.yaml) on my HA, and seems that HACS doesn't like it as the main page is almost unreadable.

### Steps to reproduce

1. Install [Google Dark Theme](https://github.com/JuanMTech/google_dark_theme/blob/master/themes/google_dark_theme.yaml)
2. Enable it with `frontend.set_theme` service call
3. Enter HACS page and observe

### Screenshots

![image](https://user-images.githubusercontent.com/85504/99259990-b9672880-2812-11eb-863d-eb191f5a49ad.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/99261199-ab1e0a00-281c-11eb-9208-fe742287a1b9.png)
Unable to replecate.

**Comment by pedrolamas** [comment]
Small update: I can only see this happening on **Microsoft Edge Dev** (full version is "Version 88.0.692.0 (Official build) dev (64-bit)
"), so this might actually be a bug on the browser...

I have flushed the Cache but that didn't fix it as I can still repro the issue!

**Comment by denilsonsa** [comment]
I can see this issue on Google Chrome 87.0.4280.66.
I cannot see this issue on Firefox 82.0.2.

Using both the "default" dark theme, and the "Google Dark Theme" (installed from HACS), or also with some other dark themes I tested.

From some quick debugging:

```
<iframe> ← background-color: var(--primary-background-color);
 └ #document
   └ <html> ← default computed style of background-color: rgba(0,0,0,0)
```

For some reason, Chrome (Blink) is applying the transparency of the root `<html>` element, but it is considering a white background behind this root element (disregarding the `<iframe>` background color.

**Comment by pedrolamas** [comment]
Nice catch @denilsonsa! Seems to be a bug in Chromium then...

**Comment by luisiam** [comment]
Issue happens after I upgraded Chrome to version 87. Version 86 has no issue.

**Comment by rpitera** [comment]
Seeing the same here with Chrome 87.  
![Clipboard01](https://user-images.githubusercontent.com/19910294/99693630-97abb280-2a59-11eb-8ac8-f77211d3b3da.jpg)
Interestingly enough, if I go directly via URL to the integration or frontend pages, the display is correct.
![Clipboard02](https://user-images.githubusercontent.com/19910294/99693860-d2ade600-2a59-11eb-9e93-cfe789eb5b7e.jpg)
It only seems to be affecting the entry page URL.

**Comment by pedrolamas** [comment]
That matches my experience with the current MS Edge Dev, so I guess something changed in Chromium code base... question now is if this is a bug of theirs or expect behavior from this point on!

Either way, maybe better to mitigate this directly in HACS, no?

**Comment by darkkatarsis** [comment]
Same here only on new Chrome Version 87.0.4280.67 (Official Build) (x86_64)
