### ISSUE TITLE
Star repository within HACS

### ISSUE THREAD

**Issue by KTibow** [hacs/integration#1662]
## Category

- [x] Backend/Integration
- [ ] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

A button that uses the GitHub API to star a repository, without needing to open a new tab.

## Implementation

How do you see this being implemented?
This API: https://developer.github.com/v3/activity/starring/
Add a button inside of the card, next to "repository".

## Alternatives

Are there any alternative solutions or features you've considered?
Manually press the "repository" button, and hit "star".

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
