### ISSUE TITLE
HACS do not load Card in lovelace

### ISSUE THREAD

**Issue by aladin2000** [hacs/integration#1666]
## Installation details

Using HACS 1.6.2 in HA 117.6 
card-mod hav been installed correctly 

| Description                | Value |
| --------------------------    | -----   |
| HACS version                  | 1.6.2   
| Home Assistant version    |  117.6
| Installation method for HA  | docker
| Web browser                     |either chromium or chrome of firefox
| Web browser version          |Version 87.0.4280.66 (Build officiel) snap (64 bits)
HACS (Home Assistant Community Store) | Version: 1.6.2

## Checklist

- [x ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x ] I have filled out the issue template to the best of my ability.
- [x ] I have read <https://hacs.xyz/docs/issues>
- [ ] This issue is related to the frontend of HACS.
- [x ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue
After a while, lovelace shows an error related to the installed module named "card-mod"  either in on complet code of in a simple 
custom card  
with error : r.setConfig is not a function
type: 'custom:card-mod'

A clear and concise description of what the issue is.

r.setConfig is not a function
type: 'custom:card-mod'

### Steps to reproduce

1. install card-mod frontend module  (  from HACS  or manually wit ui-lovelace ressource modification after couing .js file to correct resources file localtion  )
2. reboot HA
3. create frontend custom card type: 'custom:card-mod'

### Screenshots

![Untitled](https://user-images.githubusercontent.com/16690723/99811693-cb640680-2b45-11eb-9562-a7e597aae28b.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```


PASTE YOUR DEBUG LOGS HERE

[debug.log](https://github.com/hacs/integration/files/5574103/debug.log)
```

</details>

**Comment by ludeeus** [comment]
Since you get `r.setConfig is not a function` it's loaded, I suggest you open an issue in the repo for that card.

**Comment by aladin2000** [comment]
> Since you get `r.setConfig is not a function` it's loaded, I suggest you open an issue in the repo for that card.

already done  but the support said that it is not a card problem but rather hacs  ... 
Error from HACS saying that the loading is not 'complete' after that error  occurs

**Comment by aladin2000** [comment]
question :  As the card support said :" This is a problem with HACS, not card-mod. 
It probably will be resolved by uninstalling it, and reinstalling it, and force reloading." 

How can I backup HACS config ( 43 packages) and re install HACS without trouble ?

**Comment by ludeeus** [comment]
> it probably will be resolved by uninstalling it, and reinstalling it, and force reloading.

That in reference to card-mod, not HACS

**Comment by aladin2000** [comment]
> > it probably will be resolved by uninstalling it, and reinstalling it, and force reloading.
> 
> That in reference to card-mod, not HACS

Already done 10 times....

**Comment by ludeeus** [comment]
This and the linked issue have nothing to do with each other.
What you posted there, yeah I agree that could look like a HACS issue, but most ofter solved by clearing cache.

What you posted here, tells me that it's loaded correctly, since lovelace is trying to use the code from it.

**Comment by aladin2000** [comment]
> This and the linked issue have nothing to do with each other.
> What you posted there, yeah I agree that could look like a HACS issue, but most ofter solved by clearing cache.
> 
> What you posted here, tells me that it's loaded correctly, since lovelace is trying to use the code from it.

You were referring to cache, but I used several browser and alsos android device , same behaviors. 
Is there a 'server' cache to empty ?

**Comment by ludeeus** [comment]
yes. browser.

> plugin card-mod is not loaded by hacs 'Not loaded' is the error (what you posted in your link)

Could be installation/cache issue.

> r.setConfig is not a function (what you posted here)

Is not that.

**Comment by aladin2000** [comment]
OK i will continue to investigate , sorry for disrupting , I close the issue
