### ISSUE TITLE
Urlencoding needed for branch names

### ISSUE THREAD

**Issue by alandtse** [hacs/integration#1668]
## Describe the issue

HACS fails when issues include a `#` in the branch name. The pull should probably urlencode the branch name. When using GitHub to access it converts the url to https://github.com/alandtse/alexa_media_player/tree/%23826.

Logs:

```text
Error:  GitHub returned 404 for https://api.github.com/repos/alandtse/alexa_media_player/git/trees/#826
```

### Links

- **Link to action run:** https://github.com/custom-components/alexa_media_player/runs/1434476921?check_suite_focus=true
- **Link to action configuration:** https://github.com/custom-components/alexa_media_player/blob/dev/.github/workflows/validate.yaml

**Comment by ludeeus** [comment]
Try this instead <https://github.com/hacs/action>

**Comment by alandtse** [comment]
Ok, that worked better without the error. Thanks!
