### ISSUE TITLE
HA darkmode, Hacs inital screen wrong color! 

### ISSUE THREAD

**Issue by sp3cialck** [hacs/integration#1676]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |
| Home Assistant version     |
| Installation method for HA |
| Web browser                |
| Web browser version        |

## Checklist

- [x ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x ] I have filled out the issue template to the best of my ability.
- [x ] I have read <https://hacs.xyz/docs/issues>
- [x ] This issue is related to the frontend of HACS.
- [x ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A clear and concise description of what the issue is.

### Steps to reproduce

1.
2.
3.

### Screenshots

![hacs](https://user-images.githubusercontent.com/49992692/100139247-77338c00-2e8f-11eb-810b-ad05ece6515f.JPG)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
How rude!
