### ISSUE TITLE
Installed HACS following guide, does not show up in integration tab

### ISSUE THREAD

**Issue by darrylb83** [hacs/integration#1678]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.2
| Home Assistant version:    | 0.118.3  
| Installation method for HA:   | Ubuntu + Supervised

## Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Attempted install from the installer script. Confirmed the created folder "custom_components" is in the same folder as my configuration.yaml. The script created the hacs folder, and all the files are there. Cannot add integration, as it does not show up.

I am deployed to an up to date a manually installed Ubuntu + Docker, with Docker-compose to launch HomeAssistant. I am wondering if permissions could be related, much like python venv, but wouldn't know quite what to look for. Wondering if the docker itself can access the folder... trying to figure out how to check.

### Steps to reproduce

1. Installed via scripted install (sh script)
2. Restarted whole Intel NUC
3. Cleared Browser Cache
4. Tried with InPrivate (to be sure)
5. Tried to add integration

## Debug logs

<details>
  <summary>Logs</summary>

```

Sorry, I enabled the logging, but do not get ANY logs on this. The logs show within HomeAssistant, but not in the home-assistant.log file. In reviewing, I cannot find anything new, triggered by the debug commands provided on the hacs.xyz site.
```

</details>

**Comment by ludeeus** [comment]
There are 3 things that can do that:

1) The files are not in the expected place
2) You have not restart Home Assistant
3) You have not cleared the browser cache.

If you do not see this in the logs it's 1 or 2, if you see it, it's 3

> You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

**Comment by darrylb83** [comment]
> There are 3 things that can do that:
> 
> 1. The files are not in the expected place
> 2. You have not restart Home Assistant
> 3. You have not cleared the browser cache.
> 
> If you do not see this in the logs it's 1 or 2, if you see it, it's 3
> 
> > You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

#1: I ran the script thats provided, and it did load the files... my config file is in ~/docker/homeassistant/configuration.yaml, and the hacs folder is sitting in ~/docker/homeassistant/custom_components/hacs/. I believe that is the intended location.
#2: Full Hardware reset 3 times, including one power down (unrelated thing I am doing).
#3: Cleared the browser cache, and ran it "InPrivate" to be sure.

I don't see that message at all. I did a search for "hac" in my logs, and it doesn't show up. Could this be permissions related with docker?

**Comment by ludeeus** [comment]
Those paths are not correct at all for a supervised installation

**Comment by darrylb83** [comment]
> Those paths are not correct at all for a supervised installation

That definitely explains it, but its the only path I can access, and it is where my configuration.yaml is located. I am SSH'd into the OS and see it as such. So, I'm not sure what to look for.

**Comment by ludeeus** [comment]
Use one of the SSH addons from the supervisor

**Comment by darrylb83** [comment]
> Use one of the SSH addons from the supervisor

Ok, this makes sense. So I have two configuration.yaml files. One on the host, and one within the docker supervised container. Ill try reinstalling.

Thank you for this guidance!

**Comment by darrylb83** [comment]
This did resolve the issue, this was on me, without question.

Per ludeeus, using an SSH Addon from the supervisor, then running the install fixed it.

Thanks
