### ISSUE TITLE
USA-RedDragon/badnest

### ISSUE THREAD

**Issue by sd5932** [hacs/integration#1690]
## Describe why you are flagging this

_This template should **only** be used if a repository **needs** to be removed/blacklisted from HACS_

can't remove repository

**Comment by ludeeus** [comment]
This is not a default repo, and can therefore not be removed here, remove it from your custom repositories:
 - https://hacs.xyz/docs/faq/custom_repositories
- https://hacs.xyz/docs/default_repositories
- https://github.com/hacs/default
