### ISSUE TITLE
xMrVizzy/button-toolbar

### ISSUE THREAD

**Issue by dorremez** [hacs/integration#1696]
## Describe why you are flagging this

The Repo was deleted by the maker.. Can't Remove the Installed integration, getting a 404 error for it, and a "Not loaded" error in HACS.
Can't be uninstalled/removed manually.. Even after deleting ALL of its file, it will re-create the associated file in the /config/.storage/hacs folder, and will continue showing the errors..

_This template should **only** be used if a repository **needs** to be removed/blacklisted from HACS_

**Comment by chinezbrun** [comment]
similar issue 


Logger: custom_components.hacs.factory
Source: custom_components/hacs/operational/factory.py:27
Integration: HACS (documentation, issues)
First occurred: 3:42:28 AM (2 occurrences)
Last logged: 5:02:29 PM
xMrVizzy/button-toolbar - GitHub returned 404 for https://api.github.com/repos/xMrVizzy/button-toolbar

**Comment by packo761** [comment]
How remove this addons?

**Comment by SmartHomeFanatic** [comment]
Can't get rid of this thing anyhow. Please advise as there are many users experiencing this problem for sure!

**Comment by valoo89** [comment]
Idem chez moi impossible de supprimer!
une idée ?

**Comment by kw4c** [comment]
I removed the folder from... /config/www/community
and went into /config/.storage removed the code for it from hacs.repository
error is gone.

**Comment by packo761** [comment]
remove link to xMrVizzy/button-toolbar from custom repository in HACS. 

[https://landisk.eu/hacs.png](url)
