### ISSUE TITLE
HACS 1.8 Oauth code dialog box formatting error.

### ISSUE THREAD

**Issue by cdrom1028** [hacs/integration#1701]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |  1.8
| Home Assistant version     | Home Assistant 0.118.5
| Installation method for HA | HassOS on a NUC
| Web browser                | Chrome
| Web browser version        | Version 87.0.4280.88 (Official Build) (64-bit)

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

there is a formatting issue in HACS for the Oauth pop-up

### Steps to reproduce

1. I removed HACS from the frontend integrations panel and rebooted
2. I added HACS from the frontend integrations panel 
3. in the Oauth dialog there is a formatting error with the auto generated code is getting frames with several extra \n tags on both sides of the code value.  

### Screenshots

![image](https://user-images.githubusercontent.com/12717639/101266484-2fc5bf00-371d-11eb-8b34-4ff899c18524.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
I'm not able to reproduce this, make sure you have cleared your browser cache and try again.
