### ISSUE TITLE
HACS dialogs aren't fully responsive to widths between full and mobile

### ISSUE THREAD

**Issue by raman325** [hacs/integration#1706]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.8.0
| Home Assistant version     | 0.118.5
| Installation method for HA | Docker
| Web browser 1               | MacOS Companion app
| Web browser version 1       | 2020.7 (10)
| Web browser 2               | Chrome
| Web browser version 2       | 86.0.4240.198

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

The integration/frontend/automation repository browser and repo installation browsers get cut off because the width is too large for the default window size of the Companion desktop browser (see screenshots below). I can confirm that on mobile and in a normal width desktop web view, everything works as expected, but when I shrank my Chrome browser, I saw the same issue which is why I think this is related to the HACS frontend and not the Companion app.

### Steps to reproduce

1. If using Chrome, shrink your browser width to something like 2/3 and click on "Explore & Add Repositories" on any repo type, then click on a repo, and observe that both dialogs are cut off.
2. If using the Companion app, just start it with the default width and perform the same steps as 1

### Screenshots

Companion app:
![image](https://user-images.githubusercontent.com/7243222/101289439-7291a080-37ca-11eb-9007-09481dc93dd6.png)
![image](https://user-images.githubusercontent.com/7243222/101289443-7a514500-37ca-11eb-91a4-e3efb4acf5b5.png)

Browser:
![image](https://user-images.githubusercontent.com/7243222/101289446-889f6100-37ca-11eb-9140-d01ce9b657d1.png)
![image](https://user-images.githubusercontent.com/7243222/101289455-9654e680-37ca-11eb-83c6-41bcca99766c.png)

## Javascript logs from your browser console

There were none and I don't think it's relevant

**Comment by KTibow** [comment]
Looks like it's not accounting for the sidebar. Collapsing it should fix it. Probably in issue in HA's iframe embed system, not HACS.
