### ISSUE TITLE
Removed repositories can not be uninstalled

### ISSUE THREAD

**Issue by giggo** [hacs/integration#1708]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.8.0
| Home Assistant version     | 0.118.5
| Installation method for HA | hass.io
| Web browser                | Chrome Mac
| Web browser version        | 87.0

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A repository that was previously installed but that is not available anymore (i.e. repository link gives http 404) can not be uninstalled

### Steps to reproduce

1. Install a repo
2. Delete it from webserver
3. Try to uninstall from HACS
4. Nothing happens

### Screenshots

![image](https://user-images.githubusercontent.com/213763/101337919-92819c80-387c-11eb-9121-a283ef3d423c.png)

![image](https://user-images.githubusercontent.com/213763/101338120-d674a180-387c-11eb-9cf0-3251093dbf5d.png)

Click uninstall: Nothing happens
## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by MYLE-01** [comment]
@giggo  think your problem is you have add it as a Custom repositores  you need to delete that first
