### ISSUE TITLE
Action has a typo, causing a 404 error

### ISSUE THREAD

**Issue by FutureTense** [hacs/integration#1716]
## Action has a typo

[This action](https://github.com/hacs/default/pull/724/checks?check_run_id=1505225720) has a typo.

Line 114 of HACS reads

` keymaster is added to https://github.com/home-assistant/brands, NICE! `

The comma in that is causing a 404

### Links

- **Link to action run:**
- **Link to action configuration:**

**Comment by KTibow** [comment]
What is causing a 404? You clicking on the link? Anyone can contribute to hacs/action so you can fix it.
