### ISSUE TITLE
Blueprints

### ISSUE THREAD

**Issue by towerhand** [hacs/integration#1717]
## Category

- [ ] Backend/Integration
- [ ] Frontend
- [ ] Documentation
- [ ] Bot
- [ X] Other

## Checklist

- [ X] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

Add the option to manage Blueprints in HACS.

## Implementation
This is coming from the point of view of a user, by no means have the knowledge of a dev.

I can imagine having a lot of people creating blueprints and uploading them would be challenging and really hard to maintain for the devs, dealing with dupes or bad blueprints.

What I suggest is the ability to add a someone's "home assistant config/blueprint" gtihub repo, so for example: I could go to arsaboo config repo (https://github.com/arsaboo/homeassistant-config) and add it to hacs, if he got a blueprints folder then the repo gets added to hacs and list the blueprints, from there you could have the option to import, notify if they get updated or add new ones and so on. Basically I could add a hand full of repos and have access to 100s of blueprints right in HA, no need to be looking at the forums, copying and pasting to import each individual blueprint.

I'm sure it's a lot more complicated that it seems but it's just an idea, after all HA keeps trying to make it easier for the end users like me.

## Additional context
Just continuing the conversation from discord, I understand you don't think it would add enough value to justify the effort and I'm probably wasting both of our time by filling out this feature request but I would like to understand how hard it would be to implement, plus I'm sure it won't be the first person asking about it.

**Comment by ludeeus** [comment]
The option you purpost does would not work as it does not fit with the model that HACS needs, each element in HACS needs a separate repo, whithout that HACS would not know what to do, or what to look for.

So that would mean that each blueprint, would need a separate repo.
That with the fact that HA Core will get update logic for them, I really don't see this being a thing.

**Comment by towerhand** [comment]
Sounds good, thanks for explaining better.

Maybe should pinch in a "Nabu Casa Friends" idea to HA devs lol.
