### ISSUE TITLE
Yet another HACS logo.. HACS updated, cache cleared, no dice 

### ISSUE THREAD

**Issue by Fettkeewl** [hacs/integration#1723]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.8.0
| Home Assistant version     | 0.118.5
| Installation method for HA | Hassio on Virtualbox
| Web browser                | Chrome 
| Web browser version        | 87.0.4280.88

## Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

HACS logo messes up my lovelace front end.
I've read up on how people solved it before and I tried the same

- Update HACS (went from somewhere 0.6 to 1.8)

- Clear cache (since dawn of time!)

- Restart Chrome

It's still there..

### Steps to reproduce

1. Open front end... any overview

### Screenshots

![image](https://user-images.githubusercontent.com/25577040/102084534-992c8880-3e15-11eb-9a8d-70dfedfdc6fe.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

It's empty

```

</details>

The text hides behind the background sometimes..
![image](https://user-images.githubusercontent.com/25577040/102085882-83b85e00-3e17-11eb-9b3b-880abdaaa822.png)

**Comment by ludeeus** [comment]
This has not exsisted inside HACS since May.
This is:
A) Cache
B) Another custom integration

Since it does not exist, there is nothing that can be done by HACS to help you.
