### ISSUE TITLE
lovelace-thermostat-card, button-card dont work after homeassistant update to version 2020.12.0

### ISSUE THREAD

**Issue by mwsun58** [hacs/integration#1725]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version           | 1.8.0   |
| Frontend version: | 202012051441 |
-- | --
| Home Assistant version  |  2020.12.0 |
| Installation method for HA | Phython 3.8 venv|
| Web browser           |     chrome/firefox|
| Web browser version   | chrome: 87.0.4280.66 / firefox: 83.0 (64bit)|

## Checklist

- [x ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x ] I have filled out the issue template to the best of my ability.
- [x ] I have read <https://hacs.xyz/docs/issues>
- [x ] This issue is related to the frontend of HACS.
- [ x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

after updating my HA to 2020.12.0 my Thermostat-cards ,and other hacs cards, in lovelace only shows this error:

_Custom element doesn't exist: thermostat-card.
type: 'custom:thermostat-card'_

Also it's not possible to use other hacs custom cards. Always the same error.

### Steps to reproduce

1. try to create a new custom card in lovelace, always same error. "Custom element..."
2.
3.

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
Open issues in the repository for that item
