### ISSUE TITLE
Blueprints support

### ISSUE THREAD

**Issue by bboerendans** [hacs/integration#1736]
## Category

- [ ] Backend/Integration
- [ ] Frontend
- [ ] Documentation
- [ ] Bot
- [x] Other

## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

Add an option for Blueprints. So users can search for existing blueprints. Maybe an option to add new blueprints from a url to get that indexed too?

## Implementation

Maybe an extra option Blueprints besides Integration and Frontend?

## Alternatives

Searching google, github or community forums. Just one search option within HACS would be very useful.

**Comment by ludeeus** [comment]
See https://github.com/hacs/integration/issues/1717

**Comment by bboerendans** [comment]
Ah, makes sense. 
Lets hope someone will build a simple search for blueprints. 

Besides that, thanks for your work on HACS!
