### ISSUE TITLE
Error to update HACS

### ISSUE THREAD

**Issue by davidgontier** [hacs/integration#1741]
Currently, my homeassistant/Hacs has a pending update : Installed version: 1.6.2. Available version: 1.9.0

When I click "Update", I have the following error:

2020-12-17 15:21:08 ERROR (MainThread) [custom_components.hacs.api.repository_data] Could not use repository with ID 172733314 ('HacsIntegration' object has no attribute 'errors')

**Comment by ludeeus** [comment]
There was an issue with older versions, you need to update manually.
<https://hacs.xyz/docs/installation/manual>
<https://hacs.xyz/docs/installation/manual_cli>

**Comment by davidgontier** [comment]
I removed hacs folder, remove the integration in HA, restarted HA to uninstall.

Then, I re-installed the latest version that I could find (how do I check that it is the correct version), from 1.9.0/hacs.zip.

Hacs still tells me that this is version 1.6.2, that the new version 1.9.0 is available, and I have the same error message.

Am I missing something?
