### ISSUE TITLE
Unexpected frontend version - 1.9.0

### ISSUE THREAD

**Issue by jonare77** [hacs/integration#1749]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.9.0
| Home Assistant version     | 2012.12
| Installation method for HA | Home Assitant Docker Core
| Web browser                | Chrome / Chrome Edge
| Web browser version        | Chrome 87.0.4280.88 

## Checklist

- [ x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ x] I have filled out the issue template to the best of my ability.
- [ x] I have read <https://hacs.xyz/docs/issues>
- [ x] This issue is related to the frontend of HACS.
- [ x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue
Upgraded HA 108.4 to 2012.1, after restart HACS tell me to upgrade from 1.8.0 to 1.9.0. After new restart HACS tell me,

Unexpected frontend version
You are running version 202012051441 of the HACS frontend, but version 20201205162459 was expected, you should clear your browser cache.

Browser cache cleaned. Try several browsers on different OS.

A clear and concise description of what the issue is.

Unexpected frontend version

### Steps to reproduce

1. Upgrade HA to 2012.1 from 108.4
2. Upgrade HACS from 1.8.0 to 1.9.0

### Screenshots
![hacs_frontend](https://user-images.githubusercontent.com/8417277/102772034-26785b80-4387-11eb-9413-ec22c0aaa92c.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
Clear browser cache, nothing else will solve that issue

**Comment by jonare77** [comment]
> Clear browser cache, nothing else 

> Clear browser cache, nothing else will solve that issue

As you can see this has been done. Even installed a new OS, after first boot, gone directly to HA and the error is there.
