### ISSUE TITLE
All links inside of parenthesis cause 404

### ISSUE THREAD

**Issue by KTibow** [hacs/integration#1753]
## Describe the issue
If a link is inside of a parenthesis, when you click on it, it has a `)` added to the end.

### Links

- **Link to action run:** https://github.com/hacs/action/runs/1589647298
- **Link to action configuration:** ???

**Comment by ludeeus** [comment]
<https://github.com/hacs/integration/issues/1716#issuecomment-748142859> :smile:

**Comment by KTibow** [comment]
I know. I just wasn't sure what the proper approach would be.
