### ISSUE TITLE
Github Personal Access Token never used.

### ISSUE THREAD

**Issue by tanderson1992** [hacs/integration#1755]
## Describe the issue
This page describes obtaining a personal access token: https://hacs.xyz/docs/configuration/pat. The page walks the user through the process, and ends with the instruction to "make sure that you copy it manually or by clicking the clipboard icon." The next step goes on to initial configuration at https://hacs.xyz/docs/configuration/basic.

The personal access token obtained on the previous page is never mentioned again in the rest of the configuration process. If this token is required to be copied, there should be a corresponding step where it's pasted, but I don't see anything in the documentation. In fact, it seems like the initial configuration step negates the need for a PAT because the user logs in to github to allow HACS to access their account.

It's not clear to me if the PAT is required at all, but it apparently doesn't need to be copied at the end. Perhaps someone more familiar with github can decide if this page can be deleted entirely from the documentation, or if the page can be edited to remove the instructions/screenshot to copy the code.

If this code is essential and might need to be used some day, I think there should be more precise instructions regarding the use of the token. For example, "Paste this code into a text file and keep it somewhere safe. You will need this token again if you want to (revoke access to HACS, leave github, etc, whatever is appropriate here)."

## Screenshots

![image](https://user-images.githubusercontent.com/59940072/102837439-c214d500-4436-11eb-885f-1fb74e065a05.png)

**Comment by DavidFW1960** [comment]
The integration via GUI uses OAuth instead of the token. You only use the token if you configure HACS in yaml file....

**Comment by tanderson1992** [comment]
In that case I propose someone who knows what they're talking about edit the documentation to reflect that. Having just installed HACS (and not configuring with yaml), it was disconcerting to have the step to copy the token and then never have it mentioned again. Perhaps there can be an option on the previous page to skip this step entirely if not configuring manually. It seems like a fairly low-hanging fruit and a way to make the documentation match the user's install experience more closely.

**Comment by ludeeus** [comment]
removed
