### ISSUE TITLE
Add support for using Content-Security-Policy header in proxy

### ISSUE THREAD

**Issue by NullEnt1ty** [hacs/integration#1764]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.9.0
| Home Assistant version     | 2020.12.1
| Installation method for HA | Docker (with supervisor)
| Web browser                | Firefox
| Web browser version        | 84.0.1

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

The HACS frontend won't load when blocking `eval` (and similar) calls using the "Content-Security-Policy" (CSP) header.

```js
// entrypoint.js

try {
  new Function("import('/hacsfiles/frontend/e.1b8d9b76.js')")(); // blocked by CSP
} catch (err) {
  // HACS falls back to this
  var el = document.createElement('script');
  el.src = '/hacsfiles/frontend/e.1b8d9b76.js';
  document.body.appendChild(el);
  // Uncaught SyntaxError: export declarations may only appear at top level of a module (e.1b8d9b76.js:1743:1675)
}
```

Disabling the CSP header "fixes" the problem but not really the root cause. The fallback-catch-block is simply not working as intended.

### Steps to reproduce

1. Use the following header (e.g. by using a reverse proxy): `content-security-policy: default-src 'self' http: https: data: blob: 'unsafe-inline'`
2. Navigate to `<ha url>/hacs`

### Screenshots

![image](https://user-images.githubusercontent.com/966433/103139000-f6f38700-46d7-11eb-9f3a-810fa3b59cab.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“default-src”). entrypoint.js:3:2
Uncaught SyntaxError: export declarations may only appear at top level of a module e.1b8d9b76.js:1743:1675
```

</details>

**Comment by rigibe** [comment]
Same problem.

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
