### ISSUE TITLE
Self-served merge of integrations to hacs/default

### ISSUE THREAD

**Issue by tomasbedrich** [hacs/integration#1766]
## Category

- [ ] Backend/Integration
- [ ] Frontend
- [ ] Documentation
- [x] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

Self-served merge of new integrations to [hacs/default](https://github.com/hacs/default/) repository.

## Implementation

Enable PR author to merge the PR as soon as all CI checks pass. This can be done in GitHub repository settings.

## Alternatives

\-

## Additional context

\-

**Comment by ludeeus** [comment]
A PR require 3 approval from anyone with write access (everyone that have a previous merged PR get that), or an Admin.
This will not change.
