### ISSUE TITLE
rsnodgrass/hass-sensorpush

### ISSUE THREAD

**Issue by thetravellor** [hacs/integration#1771]
## Describe why you are flagging this

_This template should **only** be used if a repository **needs** to be removed/blacklisted from HACS_

The integrations been broken for months and the author is not responding

**Comment by ludeeus** [comment]
Integration is not broken.

**Comment by thetravellor** [comment]
Sorry @ludeeus, but it is. It spits put python errors and does nothing. Since formal attempts to log the issue on the authors github have been unresponded by the integration author there seems little point retaining it.
