### ISSUE TITLE
Errors in logs related to archived / blacklisted repositories

### ISSUE THREAD

**Issue by christophebaraer** [hacs/integration#1789]
Hi @ludeeus and thank you for the very useful tool. 

I saw the following error in the log yesterday. Looking at the custom_components folder, I cannot find any references to these integrations.

`Logger: custom_components.hacs
Source: custom_components/hacs/operational/factory.py:27
Integration: HACS (documentation, issues) 
First occurred: January 3, 2021, 3:56:05 AM (4 occurrences) 
Last logged: 6:36:05 AM

custom-components/sensor.rpi_power - Repository is archived.
custom-components/uilogs - Repository is in the blacklist. `

How can I remove any traces from these integrations and get rid of this error message?

Thanks!

**Comment by Metus88** [comment]
I have the same problem:
2021-01-04 12:50:42 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/sensor.rpi_power> Checking repository.

2021-01-04 12:50:42 ERROR (MainThread) [custom_components.hacs] custom-components/sensor.rpi_power - Repository is archived.
Where I can delete the Repository?

**Comment by Metus88** [comment]
I tried to delate (make a backup of this files first!!!) all file call hac in this path:
/home/homeassistant/.homeassistant/.storage
It worked for me. Be careful

**Comment by nielssteigenga** [comment]
Having the same issue here. Can't find any reposity that's calling this service. Custom-components (UI) don't seem to have issues

**Comment by seanomat** [comment]
Same problem here. This error with exactly this repository appears at least once a day at different times.

**Comment by ShadowFistOkami** [comment]
Hate to do a "me too" comment, but I'm also seeing the same errors for rpi.power & octocost.
I've been monitoring the issue for the past few weeks and there's always an associated spike in memory at the time of the error, which doesn't go back down unless I restart HA.
Could this be causing a memory leak? Anyone else seeing the same thing?

**Comment by christophebaraer** [comment]
Thank you all for confirming you're also experiencing the same problem. Perhaps @ludeeus can share some inputs?

**Comment by korasinski** [comment]
Same issue for me, on fresh install of HA and HACS. 

I see that there is aready a fix that changes from error to warning for archived repos: #1775 
But maybe it will be better to completly remove that logs when this repo is not installed. For me that information is not needed.  @ludeeus what do you think?
I've added _repository.data.installed_ to the validate_repository.py line 49. Check https://github.com/korasinski/integration/commit/77c3e3330b2bc99768c4281a59097f3fe99e97c9

**Comment by seanomat** [comment]
The weird thing is, it is the same repository, that is being archived daily for weeks now.

**Comment by ludeeus** [comment]
custom-components/sensor.rpi_power - has now been removed.
custom-components/uilogs - was removed if you still see that, you have it installed, remove it.

@korasinski without the logs, the repositories will never be removed, they are needed.

**Comment by christophebaraer** [comment]
Thank you @ludeeus for your answer. I don't recall installing uilogs and therefore would need your guidance to remove it. As you can see from the images, it cannot see it installed. 

<img width="1176" alt="Screenshot 2021-01-07 at 13 21 17" src="https://user-images.githubusercontent.com/38278243/103892135-55aefc80-50eb-11eb-9841-9368b098768d.png">
<img width="1181" alt="Screenshot 2021-01-07 at 13 21 22" src="https://user-images.githubusercontent.com/38278243/103892144-58a9ed00-50eb-11eb-885b-56095d7649d2.png">

**Comment by ludeeus** [comment]
Then there is nothing for you to do

**Comment by christophebaraer** [comment]
Thanks @ludeeus. I'll monitor and report if this occurs again.

**Comment by MrAlucardDante** [comment]
This one showed up for me today
2021-06-30 00:37:43 ERROR (MainThread) [custom_components.hacs] thomasloven/lovelace-dummy-entity-row - Repository is archived.

**Comment by rob1303-hub** [comment]
Installed HACS today (had previously always added custom cards and components manually without any issues).

On each **HA reboot** (HA OS on Proxmox) I now have the following errors in the logs:
2021-07-02 14:52:40 ERROR (MainThread) [custom_components.hacs] thomasloven/lovelace-dummy-entity-row - Repository is archived.
2021-07-02 14:52:40 ERROR (MainThread) [custom_components.hacs] thomasloven/lovelace-gap-card - Repository is archived.
2021-07-02 14:52:40 ERROR (MainThread) [custom_components.hacs] thomasloven/lovelace-gui-sandbox - Repository is archived.

I don't believe I have ever had any of these cards installed and, other than the log entries, I cannot find any trace of them on my system.

I do have Thomas' excellent auto-entities and slider-entity-row cards installed (replaced manual versions so now via HACS) and so I assume these are part of the same repository?

Thank you.

**Comment by domborovicova** [comment]
I got the same issue with 
[custom_components.hacs] thomasloven/lovelace-dummy-entity-row - Repository is archived.

I'm not using anything related to thomasloven as far as I know. There shouldn't be any dependencies.

**Comment by Thiryn** [comment]
@ludeeus needs to be reopened as the @thomasloven has archived his repos:
2021-07-04 19:59:10 ERROR (MainThread) [custom_components.hacs] thomasloven/lovelace-dummy-entity-row - Repository is archived.
2021-07-04 19:59:10 ERROR (MainThread) [custom_components.hacs] thomasloven/lovelace-gap-card - Repository is archived.
2021-07-04 19:59:10 ERROR (MainThread) [custom_components.hacs] thomasloven/lovelace-gui-sandbox - Repository is archived.
