### ISSUE TITLE
fineemb/Lynk-Co

### ISSUE THREAD

**Issue by Andoramb** [hacs/integration#1791]
Hi, this repository was removed, and I'm unable to uninstall it

[fineemb/Lynk-Co
](https://github.com/hacs/default/pull/650)
Thanks!

**Comment by ludeeus** [comment]
@fineemb fix this or everything will be removed. https://hacs.xyz/docs/publish/remove

> **WARNING**
If you as a maintainer delete/remove the GitHub repository that is added to HACS as a default repository, all your default repositories will be removed from HACS and you will not be able to add any more in the future.
So if you plan to do that, first create a PR to have it removed from HACS.

**Comment by fineemb** [comment]
sorry!
already fixed

> @fineemb fix this or everything will be removed. https://hacs.xyz/docs/publish/remove
> 
> > **WARNING**
> > If you as a maintainer delete/remove the GitHub repository that is added to HACS as a default repository, all your default repositories will be removed from HACS and you will not be able to add any more in the future.
> > So if you plan to do that, first create a PR to have it removed from HACS.

**Comment by ludeeus** [comment]
Thanks :+1:
