### ISSUE TITLE
Accept usage and Device Registration won't show properly.

### ISSUE THREAD

**Issue by aquatic7** [hacs/integration#1795]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | I don't know. Installed today with HACS install script.
| Home Assistant version     | Home Assistant OS 5.9
| Installation method for HA | Rasperry Pi
| Web browser                | Chromium / Firefox
| Web browser version        |  Version 87.0.4280.88 / 84.0.1 (64-bit)

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ x] I have filled out the issue template to the best of my ability.
- [x ] I have read <https://hacs.xyz/docs/issues>
- [x ] This issue is related to the frontend of HACS.
- [x ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue
When trying to install HACS the frontend of the installation, Accept usage,  won't show any text besides the check boxes.

Also if I check the check boxes and say submit, the next Device Registration won't properly show either. So I'm stuck there since I can't input anything.

### Steps to reproduce

1. Install HACS from ssh-addon with wget -q -O - https://hacs.xyz/install | bash -
2. Reboot HA
3. Go to Configuration > Add Integrations > HACS

### Screenshots
![image](https://user-images.githubusercontent.com/18247537/103884288-a53afb80-50de-11eb-8991-5824ee6078f4.png)
![image](https://user-images.githubusercontent.com/18247537/103884656-2befd880-50df-11eb-9d7b-aa4f586d2719.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```



Logger: homeassistant.loader
Source: loader.py:465
First occurred: 10:50:42 AM (1 occurrences)
Last logged: 10:50:42 AM
You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant. 

```

</details>

**Comment by ludeeus** [comment]
Clear browser cache or use incognito mode

**Comment by aquatic7** [comment]
> Clear browser cache or use incognito mode

Incognito solved it. Thanks!
