### ISSUE TITLE
Home Assistant update broke HACS ?

### ISSUE THREAD

**Issue by Salamandar** [hacs/integration#1796]
I just installed the latest 2021.01 update, and it looks like it broke HACS. It shows as disabled and Home Assistant tells me the hacs entity is unavailable.
Also, Home Assistant tells me HACS takes too much time to startup.

**Comment by Salamandar** [comment]
@ludeeus sorry, but what's invalid here ?

**Comment by ludeeus** [comment]
The entire template is missing.
