### ISSUE TITLE
Add version to Lovelace Resource definition

### ISSUE THREAD

**Issue by JJFourie** [hacs/integration#1800]
## Category

- [x] Backend/Integration
- [ ] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea
During installation and upgrade of a Lovelace card, add the version of the installed repository to the Resource URL.
e.g.
```
/hacsfiles/mini-graph-card/mini-graph-card-bundle.js?v=0.10.0
```
Possible advantages:
1. No need to delete the browser cache to force the browser to use the newly installed/upgraded logic, as the changed version tricks the browser into loading the new functionality instead of using anything in its cache. (?)
2. This resource version is also logged in the HA error logs, to help during troubleshooting if the user upgraded to a new version.
3. The user has a handy note of which version of the repository is implemented.
4. This will align HACS  with the Lovelace functionality. Lovelace ignores everything after the "?", but it seems HACS uses the exact Resource URL string when doing the validation check.

See [this explanation](https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#3-import-the-plugin-in-your-lovelace-config), under "Updating a plugin".

## Implementation
- Ignore the `?v=xxx` parameter in the Resource URL definition.
- During install/upgrade, append the version of the repository being installed to the Resource URL.

## Alternatives
No known alternatives.

**Comment by ludeeus** [comment]
HACS handles the cache busting for plugins, using a version is not needed for the `/hacsfiles` endpoint.
https://hacs.xyz/docs/categories/plugins#custom-view-hacsfiles
