### ISSUE TITLE
Is badguy a bad omen ?

### ISSUE THREAD

**Issue by oywino** [hacs/integration#1810]
## Describe why you are flagging this
I got this message in the HA logs today:

![image](https://user-images.githubusercontent.com/18447119/104449715-50e0c180-559f-11eb-9969-22b2dc24ba7a.png)

It worries me when I see that someone naming themselves "badguy" archives a repository on my server.
Is this a hacking attempt in works by a malicious component ?
If so, please remove it asap!

_This template should **only** be used if a repository **needs** to be removed/blacklisted from HACS_

**Comment by ludeeus** [comment]
nothing bad about it, and it has allready been removed

**Comment by oywino** [comment]
This log entry first appeared on my server today - and I have not received any HACS updates, so how can it already have been removed??

**Comment by ludeeus** [comment]
That's how HACS works.
All default repos are controlled in a central repository <https://github.com/hacs/default>

**Comment by oywino** [comment]
Ok, so I need not worry?

**Comment by ludeeus** [comment]
no
