### ISSUE TITLE
h.a fails to start after update to HACS 1.10.0

### ISSUE THREAD

**Issue by feaver12** [hacs/integration#1812]
Running h.a supervisor on a hyper-v virtual machine. today i updated to HACS 1.10.0 from 1.9.0 and upon restarting h.a i get no entities loading. logs show nothing irregular that i can see - i assume because h.a is hanging in a start loop. when i look at cpu usage it keeps spiking like when it does at initial startup of h.a then drops back to 0% over and over again . return to snapshot taken in hyper-v before update was made and everything is fine again obviously. i am unsure what the cause would be. any insight on the issue would be good to know if it has occurred to anybody else before and what the fix is if any.

**Comment by SAOPP** [comment]
Hi, Error while loading page entry have too after update to 1.10.0.

**Comment by ludeeus** [comment]
@feaver12 please fill out the entire issue template <https://github.com/hacs/integration/issues/new?assignees=&labels=issue%3Abackend&template=issue_backend.md> :+1:

**Comment by feaver12** [comment]
I can't view logs after update as h.a crashes and wont reload

**Comment by ludeeus** [comment]
Closing this as the other issue opened is more complete 👍

**Comment by SAOPP** [comment]
ctrl+f5 guys
