### ISSUE TITLE
hacs not filling resources in lovelace

### ISSUE THREAD

**Issue by xfinitybanchang** [hacs/integration#1814]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.10.0
| Home Assistant version     |2021.1.1
| Installation method for HA |supervised
| Web browser                |n/a
| Web browser version        |n/a

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

HACS not automatically filling in the resource info in lovelace dashboard settings unless the default view is changed to storage mode. This is not an issue, but can create strange behaviour:
On a clean install i created a new dashboard and put it in storage mode.
Everything from hacs did not install properly even though i had this dashboard in storage mode. The only solution was to change the default dashboard into storage mode.

### Steps to reproduce

< on clean install, create new dashboard. take control of dashboard and create a card.

1.
2. install custom button card from hacs
3.

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
This has been fixed in Home Assistant and will be part of their next release.
