### ISSUE TITLE
Setup failed for hacs: Unable to import component: No module named 'awesomeversion'

### ISSUE THREAD

**Issue by johanhammar** [hacs/integration#1815]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.10.0 |
| Home Assistant version     | 2021.1.2 |
| Installation method for HA | Docker |

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Hacs 1.10.0 is not starting. Module Awesomeversion is missing

### Steps to reproduce

Install Hacs using [Option 1](https://hacs.xyz/docs/installation/installation#option-1-run-the-installer-on-the-host-os):

1. wget -q -O - https://hacs.xyz/install | bash -
2. Restart Home Assistant
3. Check logs. 

![image](https://user-images.githubusercontent.com/69011/104711179-4ea67080-5721-11eb-9c48-05b8389ad41f.png)

## Debug logs

<details>
  <summary>Logs</summary>

```

Setup failed for hacs: Unable to import component: No module named 'awesomeversion'




```

</details>

**Comment by ludeeus** [comment]
Restart the container a few times, that should make HA install all the requirements.

**Comment by johanhammar** [comment]
Thanks. 

A few restarts later and it was installed :+1: 

```bash
bash-5.0# pip3 list | grep awesomeversion
awesomeversion                   21.1.0
```
