### ISSUE TITLE
Unable to update, h.a will not start

### ISSUE THREAD

**Issue by feaver12** [hacs/integration#1816]
## Installation details

| Description       ?         | Value |
| -------------------------- | ----- |
| HACS version------------   1.9.0         |
| Home Assistant version-----------  2021.1.1   |
| Installation method for HA ------- h.a running on a amd nuc in a vm through hyper-v. I cannot update h.a to 2021.1.2 as it renders all of my esp entities unavailable for some reason  

## Checklist

- [ ] I'm running the newest version of HACS --<https://github.com/hacs/integration/releases/latest>-----
- [ ] ------- cant update hacs, causes h.a to crash and have to restore snapshot in vm to get working again. 
- [ ] I have enabled debug logging for my installation.
- [ ] yes
- [ ] I have filled out the issue template to the best of my ability.
- [ ] yes
- [ ] I have read <https://hacs.xyz/docs/issues>
- [ ] yes
- [ ] This issue is related to the backend of HACS.
- [ ] pass
- [ ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue). yes

## Describe the issue
i noticed that there was a update available for hacs, upon trying to update and restart h.a becomes unavailable and will not load. Tried restarting virtual machine, power cycled the host machine and started hyper-v again with no luck. Have to restore previous snapshot to get h.a working again. 
A clear and concise description of what the issue is.

### Steps to reproduce

1. fresh installation of h.a supervisor in hyper-v vm on windows 10
2. esphome, duckdns, HACS and configuration editor installed
3. tried to update hacs after installation and this issue occurs  

## Debug logs

I am unable to access the logs as h.a is run in a vm and will not start after update. To view the logs i have to restore previous snapshot in hyper-v virtual machine which obviously is pointless because the logs are returned to their previous state when the snapshot was taken. Im unsure how im meant to view the logs if i can't even start the server 

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE
 cannot access logs once fault occurs as h.a will not start
```

</details>

**Comment by ludeeus** [comment]
If the VM runs HAOS you can get the logs in the hypervisor console by running `core logs`

**Comment by feaver12** [comment]
I will have a look for logs in hyper-v tomorrow

**Comment by ludeeus** [comment]
Closing as stale
