### ISSUE TITLE
New option to disable showing new repositories

### ISSUE THREAD

**Issue by fubar-coder** [hacs/integration#1817]
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

It would be nice to have an option to disable the HACS feature that shows all new repositories. I don't want HACS to show me new repositories. If I want to install something, then I'll search for it.

## Implementation

I'd suggest a new option in the integration options where one can - for example - enable the experimental features.

## Alternatives

I haven't found an alternative - besides just dismissing all repository cards, which is annoying.

## Additional context

No additional context

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
