### ISSUE TITLE
hacs

### ISSUE THREAD

**Issue by aderoju123** [hacs/integration#1819]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |
| Home Assistant version     |
| Installation method for HA |
| Web browser                |
| Web browser version        |

## Checklist

- [ ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ ] I have filled out the issue template to the best of my ability.
- [ ] I have read <https://hacs.xyz/docs/issues>
- [ ] This issue is related to the frontend of HACS.
- [ ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A clear and concise description of what the issue is.

### Steps to reproduce

1.
2.
3.

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
Closing this as it's completely empty 👍
