### ISSUE TITLE
USA-RedDragon/badnest

### ISSUE THREAD

**Issue by jdbressler** [hacs/integration#1827]
## Describe why you are flagging this

_This template should **only** be used if a repository **needs** to be removed/blacklisted from HACS_

The integration is no longer available.  It has been discontinued.

**Comment by Michele184** [comment]
Hi, I'm trying to cleanly remove the integration.
Removed everything from configuration.yaml
1st attempt - From the integrations menu I tried the uninstall button, but it does nothing, it remains.
2nd attempt - I tried to brutally remove internal config / custom_components / badnest folder, restarted, to no avail
I know this is not a clean step so the removed folder, I moved it to the pc and can restore it for a clean removal.
Advice?

**Comment by ludeeus** [comment]
This was removed from HACS a long time ago, if you still have it there, remove it from custom repos.
https://hacs.xyz/docs/faq/custom_repositories
