### ISSUE TITLE
Add restart button to message after updating an integration

### ISSUE THREAD

**Issue by masterfish1** [hacs/integration#1841]
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

The idea is to have a restart button on the message that appears after updating an integration saying that a restart is pending.

## Implementation

![Untitled](https://user-images.githubusercontent.com/7001305/105627803-4b099c80-5e39-11eb-87ff-900eea6c041c.jpg)

My suggestion would just be a little button titled "RESTART" in the bottom right-hand corner of this box that appears after updating an integration. Clicking on it could simply call the "homeassistant.restart" service. I can see this having quite a big benefit for (what I imagine) would be a small change.

## Alternatives

Only alternative is restarting HA the usual way.

**Comment by ludeeus** [comment]
The alternative is the correct approach, that way if HA change, HACS does not have to.
If you click that message you will be taken to the place you can restart.
This will not be added inside HACS again.
