### ISSUE TITLE
Clean-up /tmp right after the update

### ISSUE THREAD

**Issue by syssi** [hacs/integration#1842]
## Category

- [x] Backend/Integration
- [ ] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

Please remove /tmp/hacs.zip right after the update of HACS.

## Implementation

If the content was copied to custom_components/hacs this file can be removed.

## Alternatives

Use temporary filenames (basb scripts are using `tempfile`) if you write to /tmp.

## Additional context

I'm running two HA instances on the same host with different usernames. Both instances can write to /tmp/. If the first instance updates HACS / downloads hacs.zip to /tmp - the second cannot be updated because overwriting the file fails by:

```
2021-01-24 12:25:30 ERROR (MainThread) [custom_components.hacs] Could not write data to /tmp/hacs.zip - [Errno 13] Permission denied: '/tmp/hacs.zip'
2021-01-24 12:25:30 ERROR (MainThread) [custom_components.hacs] Could not use repository with ID 172733314 ('HacsIntegration' object has no attribute 'errors')
```

**Comment by ludeeus** [comment]
Why is this opened as a feature request? is this not a bug?
If so please reopen with the integration/backend template

**Comment by syssi** [comment]
Done: https://github.com/hacs/integration/issues/1906
