### ISSUE TITLE
Captcha does not work

### ISSUE THREAD

**Issue by herbert-roth** [hacs/integration#1847]
Captcha is not displayed.

Got Error from amazon:

<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Expires>2021-01-28T11:11:15Z</Expires>
<ServerTime>2021-01-28T11:38:15Z</ServerTime>
<RequestId>59A3D1E6BA2012F5</RequestId>
<HostId>
3OlnftI+ri/9xd3pR3PdoY3hWkHk6QpOUYPX2Q0Iza1REfOexYgC4wZGDa2MDoOgV/NyrqtxVZQ=
</HostId>
</Error>

**Comment by ludeeus** [comment]
HACS has no requests against amazon or any Captcha.
This is opened in the wrong repo I guess.
