### ISSUE TITLE
Hacs is disabled

### ISSUE THREAD

**Issue by mf-social** [hacs/integration#1864]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.10.1 |
| Home Assistant version     | 2021.2.1 |
| Installation method for HA | Supervised, Debian, Proxmox |

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ ] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

"Hacs is disabled, check your log file for more details" 

Log only says "WARNING (MainThread) [homeassistant.config_entries] Config entry '' for hacs integration not ready yet. Retrying in 5 seconds" 

No evidence of retries,and nothing to go on. 

Was working fine on 2021.2.0 - this happened immediately after updating. 

### Steps to reproduce

1. Update homeassistant core to 2021.2.1
2. Try to open Hacs
3. Cry 

## Debug logs

If anyone invents a way to be able to edit the configuration on a mobile again like we used to be able to, I'll happily do this bit, but unfortunately for well over 12 months the editable windows for homeassistant won't work with mobile browsers so I can't edit the configuration to do this currently. 

I've added the issue anyway because the fact that it is generating the error in the UI and telling me to check the logs implies that it should have updated the logs with the error at log-level 'error', which would have appeared with my current log settings but it didn't.

**Comment by ludeeus** [comment]
You are ratelimited, wait.

**Comment by mf-social** [comment]
Well, I waited over 24 hours and it never came back. Just rebooted homeassistant and its back straight away.

I would suggest this is still a bug because 

 - The log should say it is a rate limit problem at the warning/error level (as the component is rendered unusable) 
 - it doesn't 'fix' itself and requires a homeassistant restart, where really it should wait a couple of hours and re-enable itself once the connection is no longer rate-limited.

**Comment by aptonline** [comment]
I also received the same rate limit, first time ever after rebooting since the last update of HACS.

**Comment by PierreScerri** [comment]
What is the cause of this rate limit.  Can it be prevented?

**Comment by aeckard87** [comment]
also seeing the rate limit disabling hacs and not resolving after 1hr - let me try setting debug mode and see if any other logs could be beneficial. 

```2021-02-10 11:13:51 INFO (MainThread) [custom_components.hacs]
-------------------------------------------------------------------
HACS (Home Assistant Community Store)
Version: 1.11.2
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------
2021-02-10 11:13:51 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.WEBSOCKET
2021-02-10 11:13:51 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.FRONTEND
2021-02-10 11:13:51 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.CATEGORIES
2021-02-10 11:13:51 INFO (MainThread) [custom_components.hacs] HACS is enabled
2021-02-10 11:13:52 ERROR (MainThread) [custom_components.hacs] HACS is ratelimited, HACS will resume setup when the limit is cleared (11:52:21)
2021-02-10 11:13:52 ERROR (MainThread) [custom_components.hacs] HACS is disabled - HacsDisabledReason.RATE_LIMIT
2021-02-10 11:13:52 WARNING (MainThread) [homeassistant.config_entries] Config entry '' for hacs integration not ready yet. Retrying in 5 seconds
[a lot of logs redacted, this last log to show uptime - and no resolution to ratelimit]
2021-02-13 10:47:29 DEBUG (Thread-Heartbeater) [google.cloud.pubsub_v1.subscriber._protocol.heartbeater] Sent heartbeat.```

**Comment by mf-social** [comment]
I think that your log proves that my initial bug report was in fact NOT due to rate limiting, as it clearly shows in your log that rate limiting is logged at error level and I had no such entry in my logs.

Ah well, as I said, I still believe that it is a bug that the component never re-enables itself, and that the error message is clearly missing some detail between the quote marks.

**Comment by Maximus97** [comment]
I got the same error and also wonder if it is preventable?

**Comment by andersforsgren** [comment]
Does HACS really need 5000 API requests before it even starts up? Does it make those API requests by design?

**Comment by hanerd** [comment]
I've been rate limited for the last 33 hours with no end in sight.

My current GH rate limit is showing 0 usage.  Any thoughts on how to get things moving at all?

**Comment by homeautomatedemail2019** [comment]
a

**Comment by johncolet** [comment]
Its a simple fix.
in the configurations Config just enable this for Rate limit
        hacs.disable(HacsDisabledReason.RATE_LIMIT)
        return True

I tried restarting it over and over and never had this issues again.

**Comment by PierreScerri** [comment]
Is this what you mean?

config:
    hacs.disable(HacsDisabledReason.RATE_LIMIT) return True

Thanks

**Comment by johncolet** [comment]
> Is this what you mean?
> 
> config:
> hacs.disable(HacsDisabledReason.RATE_LIMIT) return True
> 
> Thanks

Yes, That's it, works like a charm, :) never had issues after this, let me know if it does work for you too.

**Comment by PierreScerri** [comment]
Giving it a try. We’ll see how it goes. 
Do you have a link to any documentation about this?

**Comment by Chidmas** [comment]
> Its a simple fix.
> in the configurations Config just enable this for Rate limit
> hacs.disable(HacsDisabledReason.RATE_LIMIT)
> return True
> 
> I tried restarting it over and over and never had this issues again.

Hi Where is the config file located where I should amend it? SOrry I am a noob and can't find the location in any documentation

**Comment by PierreScerri** [comment]
@Chidmas this is in the configuration.yaml file that you can access via the 'File Editor' add-on in Home Assistant.

**Comment by Chidmas** [comment]
> @Chidmas this is in the configuration.yaml file that you can access via the 'File Editor' add-on in Home Assistant.

Thank you, I have added it there but nothing seems to have changed do I need to add anything special before it?

**Comment by PierreScerri** [comment]
Sorry I only pointing out how to access the file.  I do not have any knowledge of what the change actually does.  I was only trying what @johncolet suggested.

**Comment by Chidmas** [comment]
> Sorry I was only pointing out how to access the file. I do not have any knowledge of what the change actually does. I was only trying what @johncolet suggested.

Okay thank you, I thought it required a change there but I couldn't work it out, I will do some experimenting. I have already added file editor etc just wasn't sure if it required a specific line before that. Thank you

**Comment by Chidmas** [comment]
> Sorry I was only pointing out how to access the file. I do not have any knowledge of what the change actually does. I was only trying what @johncolet suggested.
> ![Screenshot 2021-06-12 at 17 32 12](https://user-images.githubusercontent.com/34303331/121781255-33427300-cba4-11eb-804a-656a8bd28533.png)

Working now thanks

**Comment by nandox1** [comment]
i tried the configuration suggested but nothing chages for me... hacs still ratelimited

**Comment by apercrcl01** [comment]
Same here.  Tried the configuration but still rate limited.

**Comment by johncolet** [comment]
OH Sorry, I was too focus on building my codes for HA, didn't had time to respond.

I wasn't clear when I suggested it.
Here is what I did to make it work.

First make sure to complete the update. and when its done, modify it to This Parameter in this file to True.

This is under **custom_components/hacs/operational/setup.py**

        hacs.disable(HacsDisabledReason.RATE_LIMIT)
        return True  <------- Change this from False to "True" Caps
![image](https://user-images.githubusercontent.com/56405762/122847466-c03ca900-d2d5-11eb-878f-cc8493f397f7.png)

This call is base on this file
**custom_components/hacs/helpers/functions/remaining_github_calls.py**
![image](https://user-images.githubusercontent.com/56405762/122847298-6b992e00-d2d5-11eb-893a-1c0713a6f3b4.png)


If it still not gonna work . I am not responsible for this. :) Just trying to help what works for mine.
This will reactivate to false by time when you'll do some update but I never had the issues again so I am leaving it now as is.

**Comment by mehmetakin1996** [comment]
> 
> 
> > Sorry I was only pointing out how to access the file. I do not have any knowledge of what the change actually does. I was only trying what @johncolet suggested.
> > ![Screenshot 2021-06-12 at 17 32 12](https://user-images.githubusercontent.com/34303331/121781255-33427300-cba4-11eb-804a-656a8bd28533.png)
> 
> Working now thanks

Its working! Thanks!

**Comment by Sensemann2010** [comment]
Adding the Rate_LIMIT option to the configration.yaml helpt me also.
After waiting one day and restarting HASS HACS is working.
TNX for the info here!!!

**Comment by ludeeus** [comment]
To **anyone** that added **anything** in `configuration.yaml`, remove that! that is not valid. (and does not affect _anything_ related to HACS, but might blow up your installation later.)

This issue was closed because based on the information given, there was no real issue.
So if you have this, and come to this thread, please open a new issue where you fill out the _entire_ issue template (including debug logs)

<https://hacs.xyz/docs/faq/initial_startup> Docs on initial startup
<https://hacs.xyz/docs/basic/logs> Docs to enable debug logs

Thanks 👍
