### ISSUE TITLE
Hacs is waiting forever after restart of HA

### ISSUE THREAD

**Issue by Pirol62** [hacs/integration#1870]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | latest
| Home Assistant version     | 2021.1.4
| Installation method for HA | Homeassistant Core (Hass.io)

## Checklist

- [x ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ ] I have enabled debug logging for my installation.
- [x ] I have filled out the issue template to the best of my ability.
- [x ] I have read <https://hacs.xyz/docs/issues>
- [x ] This issue is related to the backend of HACS.
- [x ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

After Restart HACS is waiting and doesn't show the integrations/Frontend add ons
![image](https://user-images.githubusercontent.com/48820003/107124862-744d1280-68a6-11eb-8576-90fa62931fe6.png)

### Steps to reproduce

1.
2.
3.

## Debug logs
No logs 

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
It's not waiting forever, it's waiting to Home Assistant has finished startup completely

**Comment by Pirol62** [comment]
But HA did finish the startup. Everything is working

**Comment by Pirol62** [comment]
@ludeeus
After 1 hour hacs is still waiting. 
That is not a normal behavior. 
HA is up and everything is running

**Comment by Pirol62** [comment]
@ludeeus 
Ok, now, one day later, hacs is still waiting
![image](https://user-images.githubusercontent.com/48820003/107153354-5dbdbe80-696d-11eb-9d00-a85f3fbbe49f.png)
HA is working normal.
I'd like to get a hint what to do.
I fear, when I simply restart HA again, things getting worse.
I do not have the time, to tinker around in order to find a bug.
What could cause this situation, when HA obiously runs without issues.

**Comment by mrosseel** [comment]
also see this behavior currently.
version: latest HA 2021.4.2

restarting HA doesn't help, message stays even after hours.
