### ISSUE TITLE
USA-RedDragon/badnest

### ISSUE THREAD

**Issue by adamoutler** [hacs/integration#1877]
## Describe why you are flagging this
I can't remove the integration from web ui. I have tried to remove all files from ssh, and it still won't go away.  I am getting 2-errors in my logs on each startup.  The repository for this item was removed and I think that is causing the problem. 

I searched for several terms relating to removing repository from HACS and no information is available on repositories which were already shut down.  

Not sure how to handle this, but this is certainly an exceptional circumstance where a repository was created, added to HACS and the repository was then deleted.  

_This template should **only** be used if a repository **needs** to be removed/blacklisted from HACS_

**Comment by ludeeus** [comment]
You still have it as a custom repository, remove it from there.
https://hacs.xyz/docs/faq/custom_repositories
