### ISSUE TITLE
Error while loading page entry.

### ISSUE THREAD

**Issue by nunokaneco** [hacs/integration#1888]
When I try to access to the hacs tab I receiving the following error 

Error while loading page entry.
![image](https://user-images.githubusercontent.com/33290686/107374714-ccbb2480-6adf-11eb-9383-2db070f9d3e3.png)
 

| Description                | Value |
| -------------------------- | ----- |
| HACS version         last one available 
| Home Assistant version     core-2021.2.2

Can you please help me in order to solve this issue ?

Thank you for your support

**Comment by ludeeus** [comment]
You need to clear browser/proxy cache.

**Comment by rbouma** [comment]
@nunokaneco I fixed this problem not because of cache but unregistered the service worker in chrome

F12 -> Application -> Service Workers -> Unregister (top right)

Then reload page

This fixed my problem.

**Comment by rbouma** [comment]
If someone has same problem and have home assistant behind cloudflare dont forget to clear cloudflare cache

My issue was resolved after 4 hours which i set TTL cache in cloudflare on 4 hours, i came around this issue when the 404 error occurs with respons headers cf-cache-status: HIT 

Please purge everything and issue are gone.

![Screenshot 2021-02-15 at 12 40 20](https://user-images.githubusercontent.com/14012592/107942279-4a24e000-6f8b-11eb-8662-935e81afcada.png)
