### ISSUE TITLE
HACS UI not loading, shows blank screen when selected

### ISSUE THREAD

**Issue by edalquist** [hacs/integration#1890]
## Describe the issue
HACS UI not loading, shows blank screen when selected. 

Chrome Network tab shows a 404 when trying to load `http://homeassistant:8123/hacsfiles/frontend/e.652c5419.js`

The HACS iframe HTML is:
```
<html><head><script src="/frontend_latest/custom-panel.8b24fcfb.js"></script><style>body{margin:0}</style></head><body><script async="" src="/hacsfiles/frontend/entrypoint.js"></script><hacs-frontend></hacs-frontend></body></html>
```

## System Health

version | core-2021.2.2
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.10.11-v7l+
arch | armv7l
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4978
Installed Version | 1.11.0
Stage | running
Available Repositories | 741
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 14, 2021, 4:00 PM
relayer_connected | true
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Raspbian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.02.6
docker_version | 20.10.3
disk_total | 58.3 GB
disk_used | 18.8 GB
healthy | true
supported | ok
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (5.1), File editor (5.2.0), InfluxDB (4.0.3), Node-RED (8.1.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 4
-- | --
resources | 0
views | 6
mode | storage

</details>

**Comment by ludeeus** [comment]
You need to clear browser/proxy cache after update.

**Comment by rbouma** [comment]
Same problem, Clearing browser and proxy cache not working.

**Comment by chrislawson** [comment]
@rbouma try doing a hard refresh. 

To confirm page is there try opening in a different browser or incognito tab.

**Comment by rbouma** [comment]
Did everything but not working, problem is not browser or proxy cache related, many people same problem check https://github.com/hacs/integration/issues/1886#issuecomment-777184991

which is also closed

Not a cache issue

**Comment by Stevehans** [comment]
This is not a cache issue, why has the issue been closed without a resolution?

**Comment by rbouma** [comment]
@Stevehans @edalquist I fixed this problem not because of cache but unregistered the service worker in chrome

F12 -> Application -> Service Workers -> Unregister (top right)

This fixed my problem.

**Comment by rbouma** [comment]
If someone has same problem and have home assistant behind cloudflare dont forget to clear cloudflare cache

My issue was resolved after 4 hours which i set TTL cache in cloudflare on 4 hours, i came around this issue when the 404 error occurs with respons headers cf-cache-status: HIT 

Please purge everything and issue are gone.

![Screenshot 2021-02-15 at 12 40 20](https://user-images.githubusercontent.com/14012592/107942279-4a24e000-6f8b-11eb-8662-935e81afcada.png)

**Comment by eode** [comment]
If anyone *else* who:

* Is using Firefox
* Has tried clearing cache and that didn't work
* Has verified that HACS works fine in incognito mode
* Doesn't want to clear cookies and site data for every website

You can do the following in Firefox:
* Preferences -> Privacy & Security -> Cookies and Site Data -> Manage Data
* Search for 'hacs' and 'homeassistant' and delete all cookies and site data for those sites, e.g. 'hacs.xyz'
* It may be that only one of the above is needed (I suspect that 'hacs.xyz' would do it), but I deleted data for that and any site with 'homeassistant' in the name.
