### ISSUE TITLE
can't validate with lxml requirement

### ISSUE THREAD

**Issue by andvikt** [hacs/integration#1892]
## Describe the issue

I have integration that has lxml as dependency, but it can not be installed while hacs validation.

Yesterday everything worked ok and i did not change anything

### Links

- **Link to action run:** https://github.com/andvikt/mega_hacs/runs/1865599097
- **Link to action configuration:** https://raw.githubusercontent.com/andvikt/mega_hacs/master/.github/workflows/validate.yaml

**Comment by ludeeus** [comment]
Will be fixed by <https://github.com/home-assistant/wheels-custom-integrations/pull/283>
