### ISSUE TITLE
HACS UI not loading, shows blank screen when selected NOT A CACHE ISSUE!

### ISSUE THREAD

**Issue by rbouma** [hacs/integration#1896]
### Describe the issue
HACS UI not loading, shows blank screen when selected.

THIS IS NOT A CACHE ISSUE MENTION IN MULTIPLE CLOSED ISSUE!!.

TESTED ON EVERY BROWSER WITH AND WITHOUT CACHE + NEW CLEAN WINDOWS INSTALLATION WITH CLEAN BROWSER!

HACS BROKE NOT WORKING AFTER UPDATE MULTIPLE PEOPLE SAME PROBLEM: https://github.com/hacs/integration/issues/1886 https://github.com/hacs/integration/issues/1888 https://github.com/hacs/integration/issues/1890

Chrome Network tab shows a 404 when trying to load http://homeassistant:8123/hacsfiles/frontend/e.652c5419.js

**The HACS iframe HTML is:**

<html><head><script src="/frontend_latest/custom-panel.8b24fcfb.js"></script><style>body{margin:0}</style></head><body><script async="" src="/hacsfiles/frontend/entrypoint.js"></script><hacs-frontend></hacs-frontend></body></html>

**System Health**
version	core-2021.2.2
installation_type	Home Assistant Supervised
dev	false
hassio	true
docker	true
virtualenv	false
python_version	3.8.7
os_name	Linux
os_version	5.10.11-v7l+
arch	armv7l
timezone	America/Los_Angeles
Home Assistant Community Store
GitHub API	ok
Github API Calls Remaining	4978
Installed Version	1.11.0
Stage	running
Available Repositories	741
Installed Repositories	4
Home Assistant Cloud
logged_in	true
subscription_expiration	February 14, 2021, 4:00 PM
relayer_connected	true
remote_enabled	false
remote_connected	false
alexa_enabled	false
google_enabled	true
can_reach_cert_server	ok
can_reach_cloud_auth	ok
can_reach_cloud	ok
Hass.io
host_os	Raspbian GNU/Linux 10 (buster)
update_channel	stable
supervisor_version	supervisor-2021.02.6
docker_version	20.10.3
disk_total	58.3 GB
disk_used	18.8 GB
healthy	true
supported	ok
supervisor_api	ok
version_api	ok
installed_addons	Mosquitto broker (5.1), File editor (5.2.0), InfluxDB (4.0.3), Node-RED (8.1.1)
Lovelace
dashboards	4
resources	0
views	6
mode

**Comment by ludeeus** [comment]
THE FILE `e.652c5419.js` DOES NOT EXSIST IN THE CURRENT VERSION OF THE HACS FRONTEND, THAT BELONGS TO THE 20210103144316 VERSION THAT WAS IN A PREVIOUS VERSION OF HACS.

SO YEAH.... IF YOUR CLIENTS ARE TRYING TO FETCH THAT, THERE IS NOTHING OTHER THAN CACHE THAT WILL DO THAT!
