### ISSUE TITLE
Wrong resources for custom lovelace in zip

### ISSUE THREAD

**Issue by IhorSyerkov** [hacs/integration#1897]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.11.2 |
| Home Assistant version     | 2021.2.2 |
| Installation method for HA | supervised |

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I develop custom lovalece card https://github.com/IhorSyerkov/linak-desk-card.
There few js files and I put it into zip archive. According to the HACS docs I created folloving `hacs.json` file
```json
{
    "name": "LinakDesk Card",
    "render_readme": true,
    "zip_release": true,
    "filename": "linak-desk-card.zip"
}
```
After I added my custom repo to the hacs and installed the card.
The following path was automatically added to resources `/hacsfiles/linak-desk-card/linak-desk-card.zip`
If I change resource path statring to error in hacs store that card is not loaded.
### Steps to reproduce

1. Create custom lovalace card with several files files as zip archive
2. Add repository to HACS
3. Install card

<details>
if I change `"filename": "linak-desk-card.js"` in `hacs.json`. HACS store stop to accept my repository
</details>

**Comment by ludeeus** [comment]
That option only works for integrations, the documentation should be updated to reflect that.

**Comment by IhorSyerkov** [comment]
Actually all files were unachieved and putted into right place. The problem only in resource path.
It would be good to support zip files for cards as well.
For ex. in my case I separate editor and main card and load editor only if someone starts edit card.
It reduce initial loaded size of javascript

**Comment by ludeeus** [comment]
You can still separate it.

**Comment by IhorSyerkov** [comment]
I didn't find how.
if place in release few  files like now https://github.com/IhorSyerkov/linak-desk-card/releases/tag/v1.0.0
with config 
```json
{
    "name": "LinakDesk Card",
    "render_readme": true,
    "filename": "linak-desk-card.js"
}
```
HACS addon doesn't accept my repo with error `Repostitory structure for v1.0.0 is not compliant`

**Comment by ludeeus** [comment]
Your editor should be `linak-desk-card-editor.js` but that should not cause that error.
The internal cache of HACS might. Try restarting HA.

**Comment by IhorSyerkov** [comment]
Still getting an error. (tried to restart whole setup)

**Comment by IhorSyerkov** [comment]
```
2021-02-12 15:23:31 DEBUG (MainThread) [custom_components.hacs] <Plugin ihorsyerkov/linak-desk-card> Checking repository.
2021-02-12 15:23:31 DEBUG (MainThread) [custom_components.hacs] <Plugin IhorSyerkov/linak-desk-card> Running checks against v1.0.0
```
only logs what i see from hacs.

**Comment by IhorSyerkov** [comment]
For now I packed everything back into one js file. But would be nice to have document limitation, and how to split publish separate files for editor
