### ISSUE TITLE
r-renato/ha-climacell-weather

### ISSUE THREAD

**Issue by ictworkshop** [hacs/integration#1937]
## Describe why you are flagging this

_This template should **only** be used if a repository **needs** to be removed/blacklisted from HACS_

Im having an issue with the new version, which is the Moon Phase option.

If I add it to the sensors it stop the weather icon appearing on lovelace, but I did like that option.

Im I doing something wrong????

Thank you

**Comment by ludeeus** [comment]
please open an issue for that repository, that's out of HACS's control
