### ISSUE TITLE
HACS loads blank page after latest updates

### ISSUE THREAD

**Issue by Trebacz** [hacs/integration#1938]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| Web browser                | Chrome   |
| Web browser version        |  88.0.4324.150  |

## Checklist

- [ X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ X] I have filled out the issue template to the best of my ability.
- [ X] I have read <https://hacs.xyz/docs/issues>
- [ X] This issue is related to the frontend of HACS.
- [ X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I upgraded HACS. After that there were a couple complints about the front end not mathing the back end - now I get a 404 on this file - https://mydomain.com/hacsfiles/frontend/e.0123aca4.js

### Steps to reproduce

1. Upgrade HACS
2. Restart Hassio
3. Try and view the HACS menu item - blank page loads

### Screenshots

![image](https://user-images.githubusercontent.com/19363347/108011598-a3f5cc00-6fc4-11eb-8062-c1c3b07feca4.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
That file does not exist in HACS anymore.
The issue is cache, in browser or proxy. clear that.

**Comment by Trebacz** [comment]
Thank you. It was in my NGINX reverse proxy cache. I cleared it in the browser then the reverse proxy earlier. I did it a second time (on your recommendation). Did that and a CTRL-F5 in the browser and it's all good. Page loads now.
