### ISSUE TITLE
xiaomi_vacuum - wrong/missing commands

### ISSUE THREAD

**Issue by gabirinu87** [hacs/integration#1940]
hi all,
i have an issue with custom component "xiaomi_vacuum"
my vacuum is online but just only one button is working but its wrong, the button working is just "home" but instead to send the vacuum home this command send "start" command.

HACKS Integration used: Xiaomi 1C STYTJ01ZHM 
Vacuum model: mijia.vacuum.v2 - first generation (MJSTG1)

in to the logs I am getting the following error:

Logger: custom_components.xiaomi_vacuum.miio.device
Source: custom_components/xiaomi_vacuum/miio/device.py:218
Integration: Xiaomi Vacuum
First occurred: 9:30:08 PM (118 occurrences)
Last logged: 9:49:42 PM

    Unable to request properties [{'did': 'battery', 'siid': 2, 'piid': 1}, {'did': 'state', 'siid': 2, 'piid': 2}, {'did': 'error', 'siid': 3, 'piid': 1}, {'did': 'status', 'siid': 3, 'piid': 2}, {'did': 'brush_left_time', 'siid': 26, 'piid': 1}, {'did': 'brush_life_level', 'siid': 26, 'piid': 2}, {'did': 'filter_life_level', 'siid': 27, 'piid': 1}, {'did': 'filter_left_time', 'siid': 27, 'piid': 2}, {'did': 'brush_left_time2', 'siid': 28, 'piid': 1}, {'did': 'brush_life_level2', 'siid': 28, 'piid': 2}, {'did': 'operating_mode', 'siid': 18, 'piid': 1}, {'did': 'area', 'siid': 18, 'piid': 3}, {'did': 'timer', 'siid': 18, 'piid': 2}, {'did': 'fan_speed', 'siid': 18, 'piid': 6}]
    Unable to request properties [{'did': 'last_clean', 'siid': 18, 'piid': 13}, {'did': 'total_clean_count', 'siid': 18, 'piid': 14}, {'did': 'total_area', 'siid': 18, 'piid': 15}, {'did': 'total_log_start', 'siid': 18, 'piid': 16}, {'did': 'button_led', 'siid': 18, 'piid': 17}, {'did': 'clean_success', 'siid': 18, 'piid': 18}, {'did': 'life_sieve', 'siid': 19, 'piid': 1}, {'did': 'life_brush_side', 'siid': 19, 'piid': 2}, {'did': 'life_brush_main', 'siid': 19, 'piid': 3}, {'did': 'dnd_enabled', 'siid': 20, 'piid': 1}, {'did': 'dnd_start_time', 'siid': 20, 'piid': 2}, {'did': 'dnd_stop_time', 'siid': 20, 'piid': 3}, {'did': 'map_view', 'siid': 23, 'piid': 1}, {'did': 'audio_volume', 'siid': 24, 'piid': 1}]

**Comment by ludeeus** [comment]
You should open an issue with the developer of that, it has nothing to do with HACS.
