### ISSUE TITLE
custom-cards/light-entity-row

### ISSUE THREAD

**Issue by dapuzz** [hacs/integration#1955]
## Describe why you are flagging this
Plugin bloken since HA 0.106. [Issue](https://github.com/custom-cards/light-entity-row/issues/12) rised more than one year ago and never fixed by the author.
A new fork from maur8ino has fixed the implementation 
https://github.com/maur8ino/light-entity-row

Thank you

**Comment by ludeeus** [comment]
<https://github.com/custom-cards/light-entity-row/pull/13>

**Comment by ludeeus** [comment]
@paulbdavis ping
