### ISSUE TITLE
USA-RedDragon/badnest

### ISSUE THREAD

**Issue by ikillratz** [hacs/integration#1963]
I have this interation in my HA and it is screwing up my HA from loading right.  I can't seem to uninstall it.  When I go to integrations in HA and search for Bad this comes up.  I click the 3 dots to uninstall it but nothing happens.  I even went into the HACS folder and deleted the folder for Bad Nest and HA still tries to load it.  How do I get it completely out of my instance of HA?

**Comment by ludeeus** [comment]
You have to ask the developer of that integration, it has nothing to do with HACS.
