### ISSUE TITLE
HACS Deleted all my custom added repos suddenly

### ISSUE THREAD

**Issue by DavidFW1960** [hacs/integration#1964]
## Describe the issue

A clear and concise description of what the issue is.
HACS Deleted all the custom repos I added.
```
HACS Custom repos

Integrations
miguelangel-nubla/home-assistant-dewpoint
pnbruckner/ha-sun2
pnbruckner/ha-illuminance

Frontend
theOzzieRat/bom-radar-card
iantrich/list-card
```
### Links

- **Link to action run:**
- **Link to action configuration:**

**Comment by ludeeus** [comment]
Please reopen with the correct template <https://github.com/hacs/integration/issues/new?assignees=&labels=issue%3Abackend&template=issue_backend.md>

**Comment by MrLemur** [comment]
This can use more information for sure, but this happened to me as well. I can't tell at what point so debug logs are useless. All custom repos were removed and I only noticed when no updates were coming through.

**Comment by DavidFW1960** [comment]
The have not disappeared again after re-adding them anyway
