### ISSUE TITLE
Install script 404s

### ISSUE THREAD

**Issue by heytcass** [hacs/integration#1968]
Good morning.

Just started fresh on Home Assistant, and am trying to get HACS set up. When I run the script, it completes immediately, without any print out.

After going to [https://hacs.xyz/install](https://hacs.xyz/install) directly, I noticed that the site is 404ing. Did I just so happen to catch it in the middle of an update? Or is it down?

**Comment by ludeeus** [comment]
Currently in the process of migrating the website from netlify to cloudflare

**Comment by heytcass** [comment]
@ludeeus Just my luck. Ha. Thanks for the info!
