### ISSUE TITLE
Documentation: HACS PAT - incomplete?

### ISSUE THREAD

**Issue by systemcrash** [hacs/integration#1975]
## Describe the issue

What do we do once we've copied the github personal access token... does this go in config or somewhere else?

https://hacs.xyz/docs/configuration/pat

Seems like the Options panel needs a field for the PAT.

**Comment by systemcrash** [comment]
Perhaps a pointer that e.g.:

Add the following to your `configuration.yaml` file:

```
hacs:
  token: <paste the copied token here>
```

**Comment by ludeeus** [comment]
This is a helper page to <https://hacs.xyz/docs/configuration/legacy>

**Comment by systemcrash** [comment]
I think a bit more context should be provided on both pages. Because I mentally chose "I don't/won't use YAML to configure..." I skipped the YAML pages.

**Comment by systemcrash** [comment]
> This is a helper page to https://hacs.xyz/docs/configuration/legacy

You might know this - but I as a first time installer did not. 🤷

**Comment by ludeeus** [comment]
If you don't use YAML, then you don't use PAT, and should not look at that page at all.
https://hacs.xyz/docs/configuration/basic is for you, and no place there is linked to the PAT page, that is only linked from the YAML configuration
