### ISSUE TITLE
Wrong path for newly installed lovelace cards

### ISSUE THREAD

**Issue by ngohaiitdog** [hacs/integration#1983]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| Web browser                | Google Chrome |
| Web browser version        | 89.0.4389.90 64-bit  |

## System Health

version | core-2021.3.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | Asia/Hong_Kong

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4985
Installed Version | 1.11.3
Stage | running
Available Repositories | 758
Installed Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.6
docker_version | 19.03.13
disk_total | 57.8 GB
disk_used | 7.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | deCONZ (6.2.3), File editor (5.1.0), Duck DNS (1.12.1), Samba share (9.3.0), Terminal & SSH (9.1.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 5
-- | --
resources | 3
views | 6
mode | storage

</details>

## Checklist

- [Y ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [Y ] I have filled out the issue template to the best of my ability.
- [Y ] I have read <https://hacs.xyz/docs/issues>
- [Y ] This issue is related to the frontend of HACS.
- [ Y] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

After installing new Lovelace cards, the downloaded files are in "/local/community/".
But HACS would add the path under Configuration -> Lovelace Dashboards ->Resources as "/hacs-files/", so I have to manually changed the path to "/local/community" to use the customised cards downloaded.

### Steps to reproduce

1. Install custom Lovelace UI through HACS "Explore and add new repositories"

**Comment by ludeeus** [comment]
What HACS does is correct <https://hacs.xyz/docs/categories/plugins#custom-view-hacsfiles>

**Comment by ngohaiitdog** [comment]
It didn't appear when I tried to add that custom card in the dashboard.
But now when I try again, it does.

Sorry for that.
