### ISSUE TITLE
PR issue reported

### ISSUE THREAD

**Issue by chomupashchuk** [hacs/integration#1985]
## Describe the issue

A clear and concise description of what the issue is.

### Links

- https://github.com/hacs/default/pull/878/checks?check_run_id=2160850031
- https://github.com/chomupashchuk/delete-file-home-assistant/blob/master/.github/workflows/validate.yml

**Comment by chomupashchuk** [comment]
The first error I see is no manifest.json found, which is located here:
https://github.com/chomupashchuk/delete-file-home-assistant/blob/master/custom_components/delete/manifest.json

**Comment by ludeeus** [comment]
Not a bug
<https://github.com/chomupashchuk/delete-file-home-assistant/blob/1.6/hacs.json#L3> that value does not match your structure

**Comment by chomupashchuk** [comment]
thanks, my bad
