### ISSUE TITLE
None of the integrations are loaded but 3 out of 4 are working!?!

### ISSUE THREAD

**Issue by ctaggmk** [hacs/integration#1990]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| Web browser                | Chrome   |
| Web browser version        | Version 89.0.4389.90 (Official Build) (x86_64) <latest and uptodate>   |

## System Health details
System Health
Version | core-2021.3.4
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 5.4.99
CPU Architecture | x86_64
Timezone | Europe/London

HACS
GitHub API | ok
Github API Calls Remaining | 5000
Installed Version | 1.11.3
Stage | running
Available Repositories | 775
Installed Repositories | 9

Can see the root/config/.storage/hacs has 9 yaml files, including one with power-wheel info within.

hacs $ cat 160042309.hacs 
{
    "version": "6",
    "key": "hacs/160042309.hacs",
    "data": {
        "archived": false,
        "authors": [],
        "category": "plugin",
        "content_in_root": false,
        "country": [],
        "config_flow": false,
        "default_branch": "master",
        "description": "An intuitive way to represent the power and energy that your home is consuming or producing. (A custom card for the Lovelace UI of Home Assistant.)",
        "domain": "",
        "domains": [],
        "downloads": 0,
        "etag_repository": "W/\"ca0e2ab533b1efb57e219b5b535c3a9d3fa98c708e8b7b23826bb6adc55bebaf\"",
        "file_name": "power-wheel-card.js",
        "filename": "",
        "first_install": false,
        "fork": false,
        "full_name": "gurbyz/power-wheel-card",
        "hacs": null,
        "hide": false,
        "hide_default_branch": false,
        "homeassistant": null,
        "id": "160042309",
        "iot_class": null,
        "installed": true,
        "installed_commit": "d136d6d",
        "installed_version": "v0.1.5",
        "open_issues": 18,
        "last_commit": "d136d6d",
        "last_version": "v0.1.5",
        "last_updated": "2020-12-18T12:01:38Z",
        "manifest_name": null,
        "new": false,
        "persistent_directory": null,
        "pushed_at": "2020-12-18T12:01:38",
        "releases": true,
        "render_readme": false,
        "published_tags": [
            "v0.1.5",
            "v0.1.4",
            "v0.1.3",
            "v0.1.2",
            "v0.1.1"
        ],
        "selected_tag": null,
        "show_beta": false,
        "stargazers_count": 95,
        "topics": [
            "custom-card",
            "energy",
            "home-assistant",
            "lovelace-ui",
            "solar-panels"
        ],
        "zip_release": false
    }
}hacs $ 

HA.log uploaded with DEBUG enabled

[home-assistant.log](https://github.com/hacs/integration/files/6217629/home-assistant.log)

## Checklist

- [X ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X ] I have read <https://hacs.xyz/docs/issues>
- [X ] This issue is related to the frontend of HACS.
- [X ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue
In the HACS screen I am seeing warnings as all four integrations are not loaded. Screenshot attached
<img width="540" alt="hacs Screenshot at Mar 28 16-48-38" src="https://user-images.githubusercontent.com/66094563/112758523-cda00b00-8fe6-11eb-8505-2e2ad5299dd2.png">

<img width="808" alt="hacs Screenshot at Mar 28 16-49-24" src="https://user-images.githubusercontent.com/66094563/112758531-df81ae00-8fe6-11eb-9b79-af7a70c77fbe.png">

I discovered this whilst trying to fix an issue with the latest and fourth integration, the power-wheel-card. 

<img width="345" alt="hacs Screenshot at Mar 28 17-00-35" src="https://user-images.githubusercontent.com/66094563/112758597-28d1fd80-8fe7-11eb-948e-00f2e8b30d3c.png">

Despite these warnings about not being loaded 3 of the 4 integrations are working fine in the Lovelace dashboards. 

### Steps to reproduce

1. install latest version of HACS
2. add card-mod, power-wheel, light entity card and mini-graph-card integrations
3. add an example of each to a dashboard
4. check HACS screen from sidebar 

### Screenshots

see above

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

debug log file attached

```

</details>

**Comment by ludeeus** [comment]
This is expected when you use the wrong resource URL <https://hacs.xyz/docs/faq/status_not_loaded>

**Comment by Anton-Ka** [comment]
> Это ожидается, если вы используете неправильный URL-адрес ресурса [https://hacs.xyz/docs/faq/status_not_loaded.](https://hacs.xyz/docs/faq/status_not_loaded)

I have the same problem (the status is "not loaded" but the maps are working).
The solutions from the link do not solve the problem.
I don't see any problems in the address. See screenshot.
![image](https://user-images.githubusercontent.com/74901464/113694546-96151b00-96d8-11eb-9a27-d0b1099f40d9.png)
