### ISSUE TITLE
Error: Repostitory structure for 0.7.4 is not compliant

### ISSUE THREAD

**Issue by Milithor** [hacs/integration#1996]
## Describe the issue

When I try to add custom integration repository: https://github.com/Apipa169/Assistant-Relay-for-Hassio it gives following error: "Repostitory structure for 0.7.4 is not compliant"

## HACS Version

Integration version: 1.11.3
Frontend version: 20210214110032

**Comment by ludeeus** [comment]
Take that up with the maintainer of that.
