### ISSUE TITLE
HACS integration still hang on "setting up"

### ISSUE THREAD

**Issue by GitHubGio70** [hacs/integration#1999]
After the latest HACS addon update, HACS shows that is setting up with errors and never comes back

![HACS1](https://user-images.githubusercontent.com/67016464/113216210-4370d480-927c-11eb-93dc-c8f43c14a143.JPG)

this is the log

![HACS3](https://user-images.githubusercontent.com/67016464/113216282-626f6680-927c-11eb-8ac3-efd577cccf21.JPG)

Tried to remove the integration following the https://hacs.xyz/docs/installation/remove guides many times
Tried to reinstall following the https://hacs.xyz/docs/installation/installation guides many times
shutdowned and rebooted the host too
but nothing happens

this is my HA installation info

![HA1](https://user-images.githubusercontent.com/67016464/113216854-3d2f2800-927d-11eb-998f-cea12e655fee.JPG)
![HA2](https://user-images.githubusercontent.com/67016464/113216862-41f3dc00-927d-11eb-8d6f-0b985b7f7c04.JPG)
![HA3](https://user-images.githubusercontent.com/67016464/113216872-46b89000-927d-11eb-92b6-421805463e1c.JPG)

Could I kindly ask what does it can happened? How can I fix it?
Thnaks in advance 
Best Regards
Giorgio

**Comment by ludeeus** [comment]
Your `/config/.storage/hacs.repository` file is corrupt, delete it and restart Home Assistant (You should also look into replace whatever you are using as storage since this will not be the last time that happens, and it will happen to other files not related to HACS as well)
