### ISSUE TITLE
[GitHub API] Update your access token to the new format

### ISSUE THREAD

**Issue by damousys** [hacs/integration#2011]
Github asks me to update my token.
How can I do this in HACS when I have done this ?

https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/

**Comment by LArivee15** [comment]
I have the same message from Github

We noticed that, at April 5th, 2021 at 23:14 (UTC) your authentication token (HACS, with a user-agent header of python/AIOGitHubAPI) accessed the GitHub API, the token you used has an outdated format.

**Comment by corvy** [comment]
Same message here :)

**Comment by brhahlen** [comment]
Same thing here

**Comment by hampshire-al** [comment]
Same here.  I had the option in Github to regenerate token.  
Tried it, but not sure if that was a good idea!!
May now need to follow original instructions here https://hacs.xyz/docs/configuration/basic, particularly the last item that says delete integration ?!?

**Comment by ludeeus** [comment]
Unless you go into your configuration directory and delete files, nothing will be lost.

**Comment by NullEnt1ty** [comment]
Yep, I had to delete and re-add the integration. All of my previously installed repositories were still configured, no worries there 👍 

HACS uses a OAuth device flow for authentication now, so you can delete your personal access token afterwards.

**Comment by corvy** [comment]
Is there a quick guide how this is supposed to be done?

**Comment by ludeeus** [comment]
1) Use the delete "button/link" you get when clicking the 3 dots on the HACS integration in the UI <https://my.home-assistant.io/redirect/integrations/>
2) Set up HACS again <https://my.home-assistant.io/redirect/config_flow_start/?domain=hacs>

**Comment by damousys** [comment]
Isn't there a way to update the token ?
I haven't updated mine on github thou, but that would be easier then a compleet reinstall of HACS ?

**Comment by ludeeus** [comment]
<https://github.com/hacs/integration/issues/2011#issuecomment-813956134> is not a reinstall, it's a new setup of the integration, that is how you should do it for _all_ Home Assistant integrations if you want to change authentication/connection details.

**Comment by corvy** [comment]
This worked just fine for me. Deleted, and also I went into configuration.yaml and deleted the old token there (or rather commented it out). After adding HACS a-new it detected all the installed and worked just like before. Just new token :) Thanks for the information!
