### ISSUE TITLE
Status: Not Loaded

### ISSUE THREAD

**Issue by Anton-Ka** [hacs/integration#2012]
## Installation details
Installation of custom fishing cards was done through GUI HACS.

| Description                | Value |
| -------------------------- | ----- |
| Web browser                | Google Chrome   |
| Web browser version        | 89.0.4389.114   |
| App                | Mobile app  |
| App version        | 2021.3.1-full   |

## System Health

version | core-2021.3.4
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.10.11-v7+
arch | armv7l
timezone | Europe/Moscow

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4806
Installed Version | 1.11.3
Stage | running
Available Repositories | 841
Installed Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Raspbian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.9
docker_version | 20.10.3
disk_total | 14.3 GB
disk_used | 5.9 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), Samba share (9.3.1), MariaDB (2.2.2), Mosquitto broker (5.1.1), Zigbee2mqtt (1.18.1-1), Home Assistant Google Drive Backup (0.103.1), ADB - Android Debug Bridge (0.8.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 5
views | 14
mode | storage

</details>

## Checklist

- 

- [ *] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ *] I have filled out the issue template to the best of my ability.
- [ *] I have read <https://hacs.xyz/docs/issues>
- [ *] This issue is related to the frontend of HACS.
- [ *] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Loaded cards remain in the "Not Loaded" status.

Recommendations from the [FAQ](https://hacs.xyz/docs/faq/status_not_loaded) did not help solve the problem. Checking the addresses did not reveal any anomalies. For example, for the map ["lovelace-auto-entities"](https://github.com/thomasloven/lovelace-auto-entities) the recommended path is '/ config / www / community / lovelace-auto-entities'. I place the files along the path '/config/www/community/lovelace-auto-entities/auto-entities.js' etc. However, after reinstalling, I see * .gz files that appear in this folder. In 'configuration.yaml' I write the path```
 - url: /hacsfiles/lovelace-auto-entities/auto-entities.js?v=1.8.5
    type: module
```

Reinstallation, deletion-adding again did not solve the problem either.
The problem is observed only with Lovelace cards. The rest of the custom maps are working fine.
Moreover, the custom integrations of the Lovelace cards themselves work without failures, the problem is only in the message in the HACS menu.
This problem appeared at one point, but I didn’t do anything with these cards.

### Steps to reproduce

<!-- Without steps to reproduce, it will be hard to fix, it is very important that you fill out this part, issues without it will be closed -->

1. Instal this custom component from mobile app: https://github.com/mavrikkk/ha_kettler
2. I tried to set up the integration but was not satisfied with the result.
3. Removed the integration.
4. Removed the custom repository.
5. Saw a message that the integrations could not be loaded.

### Screenshots

![image](https://user-images.githubusercontent.com/74901464/113708215-9ec21d00-96e9-11eb-973c-9d1a54747e3e.png)

![113694546-96151b00-96d8-11eb-9a27-d0b1099f40d9 1](https://user-images.githubusercontent.com/74901464/113708110-8225e500-96e9-11eb-9268-832e204cf73f.png)
<!-- Here you paste screenshots to showcase the issue -->

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

Console was cleared
content-all-sites.js:8 <img>​
console.clear() was prevented due to 'Preserve log'
mini-graph-card-bundle.js??v=0.11.0:1  MINI-GRAPH-CARD  0.11.0-dev.4 
auto-entities.js?v=1.8.5:194 AUTO-ENTITIES 1.8.5 IS INSTALLED 
content-all-sites.js:8 <img>​
console.clear() was prevented due to 'Preserve log'
content-all-sites.js:8 <img>​
console.clear() was prevented due to 'Preserve log'

```

</details>

<!-- IssueTemplateID: issue_frontend -->

**Comment by ludeeus** [comment]
Remove ` ?v=1.8.5` that should not be there, HACS does an _exact_ match.
