### ISSUE TITLE
Document how to change GitHub Personal Access Token

### ISSUE THREAD

**Issue by barbieri** [hacs/integration#2013]
## Describe the issue

Github did deploy a new access token format and is urging people to regenerate their keys, see their post: https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/

After doing it, HACS won't detect the token needs updating and thus won't ask you for an updated token. In order to update the token, one must manually edit `.storage/core.config_entries` and find the `"domain": "hacs"` to update the `"data": { "token": "YOUR GITHUB PERSONAL ACCESS TOKEN (PAT)"}`, as:

```json
           {                       
                "entry_id": "19e7b02d93fa4b74a7761734e1088cde",
                "version": 1,
                "domain": "hacs",                              
                "title": "",      
                "data": {       
                    "token": "YOUR GITHUB PERSONAL ACCESS TOKEN (PAT)"
                }, 
```

Until the web interface is changed to request new access token, please document how to change it manually as per above.

**Comment by ludeeus** [comment]
Absolutely not, no user should ever do this.
See https://github.com/hacs/integration/issues/2011#issuecomment-813956134 for the proper way to change the token.

**Comment by barbieri** [comment]
ok, not that obvious that:

> Use the delete "button/link"

was the way to go or I'd need to redo all of the integrations I use. But thanks for pointing this!
