### ISSUE TITLE
Cannot open HACS on EDGE

### ISSUE THREAD

**Issue by mironalessandro** [hacs/integration#2016]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| Web browser                | EDGE|
| Web browser version        |  89.0.774.68 |

## Checklist

- [ x ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ x ] I have filled out the issue template to the best of my ability.
- [ x ] I have read <https://hacs.xyz/docs/issues>
- [ x  ] This issue is related to the frontend of HACS.
- [ x ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Cannot open HACS on Edge. Blank page returned.

### Steps to reproduce

1. Open Edge
2. Open Hacs
3. You can see a blank page

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE
![image](https://user-images.githubusercontent.com/54042200/113985518-87e80b80-984c-11eb-9808-a7538491be16.png)


```

</details>

**Comment by ludeeus** [comment]
Seems to be resolved with Edge  91.0.864.37
