### ISSUE TITLE
HACS cannot be installed/configured properly

### ISSUE THREAD

**Issue by benalla** [hacs/integration#2017]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| Web browser                | xxx   |
| Web browser version        | xxx   |

## Checklist

- [ x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x ] I have filled out the issue template to the best of my ability.
- [x ] I have read <https://hacs.xyz/docs/issues>
- [ x] This issue is related to the frontend of HACS.
- [ x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I had to reinstall HACS because it suddenly disappeared from the sidebar.
Now I can't get it installed properly anymore.
All steps followed correctly, HACS does not appear in the sidebar and does not look good in Integrations. Folder is created in custom components.

### Steps to reproduce

1. Remove HACS
2. Reboot HA
3. Install HACS

### Screenshots

![image](https://user-images.githubusercontent.com/3511603/114029262-a0bae600-9879-11eb-821c-c80ff8b7ecee.png)

```
Logger: homeassistant.config_entries
Source: helpers/collection.py:198
First occurred: 13:50:14 (1 occurrences)
Last logged: 13:50:14

Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 249, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 26, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 67, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 91, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 122, in async_hacs_startup
    lovelace_info = await system_health_info(hacs.hass)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/system_health.py", line 22, in system_health_info
    health_info.update(await hass.data[DOMAIN]["resources"].async_get_info())
  File "/usr/src/homeassistant/homeassistant/components/lovelace/resources.py", line 66, in async_get_info
    await self.async_load()
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 198, in async_load
    self.data[item[CONF_ID]] = item
KeyError: 'id'

```

</details>

**Comment by ludeeus** [comment]
Your lovelace configuration is broken, you need to fix that first.

**Comment by benalla** [comment]
Can you tell me the right configuration?
To my knowledge this has not been changed.

**Comment by ludeeus** [comment]
No, the logs don't say that.
The #frontend channel on the Home Assistant Discord might be able to help

**Comment by benalla** [comment]
Frontend???
So it's a frontend issue?
Then why the 'frontend' label was changed/removed?

**Comment by ludeeus** [comment]
The issue is not with the HACS frontend, it's with your lovelace configuration

**Comment by benalla** [comment]
Ah....that makes sense!
Thanks!
