### ISSUE TITLE
Install script for HACS needs to support 7-zip to work on Synology DSM6.2 NAS devices as Unzip is not available

### ISSUE THREAD

**Issue by DocDoo** [hacs/integration#2018]
## System Health

version | core-2021.4.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 4.4.59+
arch | x86_64
timezone | Europe/Copenhagen

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

## Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I have Home Assistant running in Docker on my Synology DS920+ NAS and would like to install HACS. But it is not possible to complete the installation as described in https://hacs.xyz/docs/installation/installation for Home Assistant Container as Synology have chosen to drop unzip in favor of 7-zip.

If possible, it would be great if the HACS installer could fall back to using "7z x" for extracting files from the downloaded archive, if it fails to detect unzip.

### Steps to reproduce

1. I have Home Assistant running in Docker on my Synology DS920+ NAS and would like to install HACS.
2. The HACS installation guide (https://hacs.xyz/docs/installation/installation) for Home Assistant Container describes that "Option 1: Run the installer on the host OS" can be used for installing HACS.
3. Following the instruction, I successfully establish a SSH connection to the Synology NAS and successfully log in.
4. However upon executing the command "wget -q -O - https://install.hacs.xyz | bash -" the error message "ERROR: 'unzip' is not installed" is shown and the command is aborted.

The reason for UNZIP not being available is that Sonology have chose to replace it with the "7z x" command instead.

## Debug logs

SynAdmin@HGV10-HQ:~$ wget -q -O - https://install.hacs.xyz | bash -
ERROR: 'unzip' is not installed

**Comment by ludeeus** [comment]
Run it inside the container.
https://hacs.xyz/docs/installation/installation/#option-2-run-the-installer-inside-the-container

**Comment by DocDoo** [comment]
Wow, super quick turn-around on this issue 👍 and my apologies for not trying the other installation option 🤦‍♂️ as that worked perfectly fine 😊.
