### ISSUE TITLE
HACS Page Blank: Unexpected token 'export'

### ISSUE THREAD

**Issue by monik3r** [hacs/integration#2021]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| Chrome                     | 89.04 |

## System Health

version | core-2021.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.94
arch | x86_64
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 1491
Installed Version | 1.11.3
Stage | running
Available Repositories | 776
Installed Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.11
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.9
docker_version | 19.03.13
disk_total | 30.8 GB
disk_used | 3.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (1.16.2), Almond (1.1.2), Spotify Connect (0.8.2), File editor (5.2.0), Terminal & SSH (9.1.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

## Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Hi, I've been having issues with the latest HACS/Homeassistant. I've tried installing from scratch with the latest version on both hass os and the docker containers. Both have the same errors - `Uncaught SyntaxError: Unexpected token 'export' e.b7f0888b.js:1750`. Both lead to blank pages.

I've tried other fixes such as unregistering the js worker, but they haven't led to any success. Thank you for the support, and the neat project.

### Steps to reproduce

1. Install Homeassistant via hass os or dockerfiles
2. Install HACS via the [instructions](https://hacs.xyz/docs/installation/installation)
3. Enable Integration
4. Restart Server, clear caches, reboot hass os just in case
5. Attempt to view the HACS page

### Screenshots

[https://i.imgur.com/rNjhjOc.png](https://i.imgur.com/rNjhjOc.png)

Here's the error I'm seeing: 
`Uncaught SyntaxError: Unexpected token 'export' e.b7f0888b.js:1750`

**Comment by ludeeus** [comment]
Does it work in incognito?
If not, enable the debug setting integration options, and try again in a new incognito window

**Comment by monik3r** [comment]
No it does not. I've enabled the debug setting, there aren't any additional logs in homeassistant. The only one that is present is `2021-04-12 15:38:23 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
`

**Comment by ludeeus** [comment]
The extra logs would be in the browser console

**Comment by monik3r** [comment]
There aren't any extra logs in the browser console.

**Comment by ludeeus** [comment]
There should be, at least the line numbers should change

**Comment by monik3r** [comment]
There's still a syntax error on the same line. Should it be loading a different javascript file?

**Comment by ludeeus** [comment]
It should use a non minified version with more console logs
It my be you need to set your browser console to debug

**Comment by monik3r** [comment]
The only other message is a verbose one: `Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
value @ chunk.8eec5fc55958fbdfae35.js:1
value @ chunk.8eec5fc55958fbdfae35.js:1
performUpdate @ app.ebe75b7a.js:12795
_enqueueUpdate @ app.ebe75b7a.js:12795`

**Comment by monik3r** [comment]
Hi, just wanted to check on this. It'd be cool to be able to use HACS. Thanks!

**Comment by monik3r** [comment]
I've moved over to installing on a raspberry pi instead of running with KVM. Things seem to work correctly, so I'll close this for now. Thanks for the neat project!
