### ISSUE TITLE
Not eable to install HACS in Homeassistant via GetHub installation script

### ISSUE THREAD

**Issue by dionmd** [hacs/integration#2025]
I Followed the Getup installation instruction : https://hacs.xyz/docs/installation/prerequisites

Home Assistant OS#
Go to the Supervisor panel
Install one of the SSH add-ons (you need to enable advanced mode in your user profile to see them)
Configure the SSH add-on you chose by following the documentation for it
Start the SSH add-on
Connect to the SSH add-on
Run the HACS install script: wget -q -O - https://install.hacs.xyz | bash -

That part worked correctly (see image)

![image](https://user-images.githubusercontent.com/61834323/114872963-ce97b180-9dc8-11eb-9867-76b607b50f47.png)

I've restarted my home assistant as instructed by SSH

Than in configuration: https://hacs.xyz/docs/configuration/basic

Followed the following instructions: 

in home assistant: Configuratiom: integration, clear my cache right there, than try to fin HACS...
![image](https://user-images.githubusercontent.com/61834323/114873996-de63c580-9dc9-11eb-864c-f65ff5ce503e.png)

Its not there!!!
![image](https://user-images.githubusercontent.com/61834323/114873558-64334100-9dc9-11eb-8043-8bce08ddce22.png)

What am I missing?

Whith this new procedure its seems that I cannot download the Hacs.xyz zip file and drop it in the appropriate folder like people use to do via Samba..

Please Help!

thanks

**Comment by ludeeus** [comment]
Do you see the log about using it after you restarted?
Remember that using the UI to restart, will not restart Home Assistant if there are any configuration issues.

**Comment by dionmd** [comment]
That must be it!, I do have a congiguration issue when in check configuration before restart I get an error message.. IlL clear everything and hopefully this will resolve it

Thanks!

**Comment by dionmd** [comment]
After a good clean of all configurations issues. I was able to find  HACS affter clicking check my configuration and restart home assistant.
