### ISSUE TITLE
HACS integration fails with Home Assistant OS  core-2021.4.5

### ISSUE THREAD

**Issue by rubenfiszel** [hacs/integration#2030]
Hacs integration started failing running with the same error as below.

I reinstalled it from scratch and I still cannot add the hacs integration:

```
 Error occurred loading configuration flow for integration hacs: cannot import name 'QueueManager' from 'queueman' (/usr/local/lib/python3.8/site-packages/queueman/__init__.py)
```

**Comment by Mazz94** [comment]
Dopo aver aggiornato home assistant a 2021.4.6 non c'è più l'integrazione Hacs sulla barra laterale ma le card funzionano comunque , pero mi restituisce questo errore :


Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:486
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 0:36:22 (1 occurrences)
Last logged: 0:36:22

Component error: hacs - cannot import name 'AIOGitHubAPIException' from 'aiogithubapi' (/usr/local/lib/python3.8/site-packages/aiogithubapi/__init__.py)

**Comment by haydndup** [comment]
I ran into the same issue. But, I seemed to have solved it by restoring to an older snapshot, updating the plugins within HACS, and then updating HASS again. I'm now running 2021.4.6 and HACS is okay.
