### ISSUE TITLE
HACS is not loading after upgrading hassOS to 2021.4.3

### ISSUE THREAD

**Issue by gshilo** [hacs/integration#2031]
## System Health

version | core-2021.4.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | Asia/Jerusalem

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | May 17, 2021, 3:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.0
docker_version | 19.03.15
disk_total | 57.8 GB
disk_used | 5.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Visual Studio Code (3.2.0), Terminal & SSH (9.1.0), Node-RED (8.2.1), Home Assistant Google Drive Backup (0.103.1), Duck DNS (1.12.5), WireGuard (0.5.1), Mosquitto broker (5.1.1), RPC Shutdown (2.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

## Checklist

- [ x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ x] I have enabled debug logging for my installation.
- [x ] I have filled out the issue template to the best of my ability.
- [x ] I have read <https://hacs.xyz/docs/issues>
- [x ] This issue is related to the backend of HACS.
- [ x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue
I had HACS working on my hassOS for a while. Few days ago I updated hassOS to 2021.4.3 and after that HACS cannot load. Meanwhile, I upgraded hassOS to 2021.4.4 and 2021.4.5 but the HACS problem still persists.

### Steps to reproduce

1. in hassOS, go to supervisor.
2. You find a message that a new version (2021.4.3, 2021.4.4 or 2021.4.5) and click upgrade.
3. After system restart, there is a notification that hacs has invalid configuration and cannot be setup.

## Debug logs

<details>
  <summary>Logs</summary>

```

2021-04-19 21:46:12 INFO (MainThread) [homeassistant.setup] Setup of domain weather took 0.0 seconds
2021-04-19 21:46:12 INFO (MainThread) [homeassistant.components.weather] Setting up weather.met
2021-04-19 21:46:12 INFO (MainThread) [homeassistant.components.weather] Not adding entity Home Hourly because it's disabled
2021-04-19 21:46:13 INFO (MainThread) [snitun.utils.aiohttp_client] AioHTTP snitun client connected to: eu-west-2.ui.nabu.casa:443
2021-04-19 21:48:23 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package hacs_frontend==20210214110032: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/hacs-frontend/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/hacs-frontend/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/hacs-frontend/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/hacs-frontend/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/hacs-frontend/
ERROR: Could not find a version that satisfies the requirement hacs_frontend==20210214110032 (from versions: 202006281222, 202007180957, 202008050145, 202008231558, 202009091732, 202009242003, 202011142129, 202011151903, 202011221222, 202012051441, 202017310251, 20201205162459, 20201223145936, 20210102161751, 20210103144316, 20210131153018, 20210207162610, 20210213120600, 20210214181913)
ERROR: No matching distribution found for hacs_frontend==20210214110032
WARNING: You are using pip version 20.2.4; however, version 20.3 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
2021-04-19 21:48:23 ERROR (MainThread) [homeassistant.setup] Setup failed for hacs: Requirements for hacs not found: ['hacs_frontend==20210214110032'].
2021-04-19 21:48:23 INFO (MainThread) [homeassistant.setup] Setting up rpi_power
2021-04-19 21:48:23 INFO (MainThread) [homeassistant.setup] Setup of domain rpi_power took 0.0 seconds

```

</details>

**Comment by ludeeus** [comment]
After all upgrades of Home Assistant, Home Assistant needs to install the requirements for all your custom integrations, as your logs state you have/had network issues at the time of starting, and the installation failed.
Restart Home Assistant usually solves that, if not you have to look into your network, there is nothing that can be done inside HACS to solve that.

**Comment by gshilo** [comment]
I have no problems installing official addons (via supervisor) at the same time that HACS cannot load....

**Comment by sphanley** [comment]
I think there may be something real here - my previously-stable HACS installation now can't load either. In my case I get the following errors in my logs:

> 2021-04-27 10:52:44 ERROR (MainThread) [custom_components.hacs] <Integration hacs/integration> Could not read manifest.json [encoding without a string argument]

and

> 2021-04-27 10:53:00 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
> File "/config/custom_components/hacs/hacsbase/hacs.py", line 140, in startup_tasks
> await self.handle_critical_repositories()
> File "/config/custom_components/hacs/hacsbase/hacs.py", line 195, in handle_critical_repositories
> critical = json.loads(critical.content)
> AttributeError: 'list' object has no attribute 'content'

**Comment by sphanley** [comment]
In my case, I reran the HACS installer, and it's now working as expected.
