### ISSUE TITLE
How to use hacs with private repositories

### ISSUE THREAD

**Issue by eloo** [hacs/integration#2036]
## Describe the issue

Hi,
i'm currently working on a custom integration and i'm wondering how i can configure HACS to use my private github repository.
I have already create a token which has access to private repositories and exchanged it in the .storage directory. 
My integration (github-repository) can then be found by hacs but the installation is still failing. 

Sadly i couldn't find any hints about that in the docs, so it seems that this missing in the docs.

Thanks

**Comment by ludeeus** [comment]
This is not documented for a really simple reason, it does not work, only public repos are supported

**Comment by eloo** [comment]
@ludeeus 
then it should be added to known limitations IMHO.

further is there a special reason why this is not possible? technically there should be everything present (token)
