### ISSUE TITLE
Could not read manifest.json

### ISSUE THREAD

**Issue by tschechniker** [hacs/integration#2039]
## System Health

version | core-2021.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.109
arch | x86_64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4986
Installed Version | 1.11.3
Stage | startup
Available Repositories | 1
Installed Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.0
docker_version | 19.03.15
disk_total | 30.8 GB
disk_used | 4.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (1.16.2), File editor (5.2.0), Mosquitto broker (5.1.1), InfluxDB (4.0.6), Grafana (6.3.2), Terminal & SSH (9.1.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 4
mode | storage

</details>

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ ] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I just installed HACS and see the following error:

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/integration.py:64
Integration: HACS (documentation, issues)
First occurred: 16:52:43 (1 occurrences)
Last logged: 16:52:43

<Integration hacs/integration> Could not read manifest.json [encoding without a string argument]

Logger: homeassistant
Source: custom_components/hacs/hacsbase/hacs.py:195
First occurred: 16:52:58 (1 occurrences)
Last logged: 16:52:58

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 140, in startup_tasks
    await self.handle_critical_repositories()
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 195, in handle_critical_repositories
    critical = json.loads(critical.content)
AttributeError: 'list' object has no attribute 'content'

### Steps to reproduce

1. Install HACS
2. Restart HA

## Debug logs

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
See #2038

**Comment by tschechniker** [comment]
Thx :) did search for open tickets but didn't expect to find one in the closed :+1:
