### ISSUE TITLE
HACS not installing (only a single configuration of hacs is allowed)

### ISSUE THREAD

**Issue by CorvetteCole** [hacs/integration#2043]
## System Health details

version | core-2021.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.99
arch | x86_64

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.0
docker_version | 19.03.13
disk_total | 30.8 GB
disk_used | 4.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), ESPHome (1.16.2), Terminal & SSH (9.1.0), Home Assistant Google Drive Backup (0.103.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [ ] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

This issue is identical to #1863 , except that the issue was not caused by a missing file in another integration. I found the cause and created this issue to make you all aware of it. This could be an upstream issue, I'm not sure. After upgrading to 2021.4.6, clicking the HACS icon would not open HACS. So I decided to reinstall it, and in the process of doing so ran in to the issue described in #1863. After much hand-wringing, I found out that there was a HACS related integration configuration in /config/.storage/core.config_entries. After removing that, I was able to install HACS normally. I am not sure what triggered this issue, but maybe the way I solved it could be a good clue

### Steps to reproduce

Unknown as of far

## Debug logs

Debug logs are not applicable as they literally showed nothing related to this issue.

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by CorvetteCole** [comment]
@ludeeus tried in incognito mode, different browser, and different devices even. I tried to get usable log output to make this a worthwhile issue. I maintain quite a few open source projects myself so believe me, I understand. But there was literally no log output at all related to this. I at least wanted to put this out here so if anybody else has this problem there is a reference

**Comment by ludeeus** [comment]
The new version of HA that comes in beta this Wednesday should offer more details when integrations fail to load properly.
https://dev--home-assistant-gallery.netlify.app/#demo-integration-card

**Comment by CorvetteCole** [comment]
Great, didn't mean to just create an issue with no value. Just solved my issue and wanted to document the solution SOMEWHERE so future people could find it.
