### ISSUE TITLE
Clean install of HACS, wrong resource URL for lovelace cards

### ISSUE THREAD

**Issue by vangorra** [hacs/integration#2052]
## System Health

version | core-2021.4.6
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 4.4.59+
arch | x86_64
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 1360
Installed Version | 1.12.3
Stage | running
Available Repositories | 776
Installed Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | May 5, 2021, 5:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 4
-- | --
resources | 2
views | 10
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Clean install of HACS, wrong resource URL for lovelace cards

When installing a lovelace card, the resource URL is `/hacs/<card name>/<card file name>.js`. The `/hacs/` URL does not resolve nor does it exist. Replacing `/hacs/` with `/local/community/` works. However, the HACS UI now complains that these custom cards are no longer configured properly.

External dirs config.
```
homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config/www
```

### Reproduction steps

1. Install HACS.
2. Install lovelace card.
3. Try to use the lovelace card, you will be told the element does not exist.
4. In `/config/lovelace/resources`, replace `/hacs/` with `/local/community/` in the resource URL.
5. Refresh page and use custom element without issue.
...

### Debug logs

```text
No logs needed.
```

**Comment by ludeeus** [comment]
It should be /hacsfiles/, not /hacs/
And remove allowlist_external_dirs, that should not be configured for that dir

**Comment by vangorra** [comment]
Disabling `allowlist_external_dirs` worked. Thanks.
