### ISSUE TITLE
Failed to set up error on 2021.5b when using YAML config

### ISSUE THREAD

**Issue by SeanPM5** [hacs/integration#2054]
## System Health

version | core-2021.5.0b5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 3872
Installed Version | 1.12.3
Stage | running
Available Repositories | 782
Installed Repositories | 18

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | May 16, 2021, 8:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | beta
supervisor_version | supervisor-2021.04.3
docker_version | 19.03.15
disk_total | 109.3 GB
disk_used | 7.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.1.1), File editor (5.3.0), Samba share (9.3.1), Visual Studio Code (3.3.0), Mosquitto broker (5.1.1), Dropbox Sync (1.3.0), Check Home Assistant configuration (3.7.1), SSH & Web Terminal (8.2.1), Network UPS Tools (0.6.2), InfluxDB (4.0.6), Grafana (6.3.3), ESPHome (1.16.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 7
-- | --
resources | 11
views | 26
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

First spotted by RobC in Discord and confirmed it on one of my instances. When HACS is configured via YAML, it appears to have issues on 2021.5b, says "Failed to set up" 

![image](https://cdn.discordapp.com/attachments/427516175237382144/838640232978841630/Screen_Shot_2021-05-02_at_9.56.19_PM.png)

Despite this error, everything appears to work fine. Can browse and update custom integrations and such no problems, hacs sensor works, etc. This was my config:

```
hacs:
  token: !secret github_token
  sidepanel_title: HACS
```

After deleting the integration and adding it via the UI, it worked fine with no errors.

### Reproduction steps

1.  Have HACS configured via YAML, see error on integrations page
2. Delete HACS via integrations page, add via integrations page (UI method)
3. Will work again

### Debug logs

```text
n/a - fixed by doing above steps before opening this issue
```

**Comment by ludeeus** [comment]
That is strange, it should not show there at all if you use YAML...

**Comment by ludeeus** [comment]
Okey... If you used HACS pre. 1.0 this might happen.
If you encounter this and are absolutely sure you have HACS configured with YAML, click the 3 dots, then hit delete, then restart Home Assistant.
When it starts up again, the HACS card is gone, and it's still working as expected.

**Comment by ktownsend-personal** [comment]
If I have this issue, but I want to use the UI instead of yaml for the HACS integration, how do I get the UI version to have the correct token? I considered deleting both yaml and UI, then re-adding to UI, but I am concerned that I would lose my configured packages.
