### ISSUE TITLE
Harmony-card not showing up even though it's on plugins list

### ISSUE THREAD

**Issue by ljmerza** [hacs/integration#2056]
### Web browser

Chrome

### Web browser version

84

## System Health

version | core-2021.4.6
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.0-642101212021-generic
arch | x86_64
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4982
Installed Version | 1.12.3
Stage | running
Available Repositories | 775
Installed Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 19
views | 5
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

sbryfcz/harmony-card exists in the plugins file but its not showing up in HACS when trying to install it. I searched for "harmony-card" and nothing pops up. I tried adding it manually but HACS says it already exists.

### Reproduction steps

1. Frontend
2. Explore and add repositories
3. Type harmony-card
...

### Screenshots

![Screenshot_20210504-005826_Home Assistant](https://user-images.githubusercontent.com/4085765/116962402-d7ff9580-ac73-11eb-8e6a-c4f93c34fb6e.jpg)

### Javascript logs from your browser console

```text
Na
```

**Comment by ludeeus** [comment]
Try restarting Home Assistant, it's definitely there 
![image](https://user-images.githubusercontent.com/15093472/116987663-a0bed200-accf-11eb-9b02-096de5df5d7c.png)

**Comment by ljmerza** [comment]
I restarted and still not showing up.
