### ISSUE TITLE
"<Integration hacs/integration> Could not read manifest.json [encoding without a string argument], " HACS stuck on starting up and stuck on V 1.11.3, UI lists pending updates for custom integrations but they have been updated (confirmed by manifest.json)

### ISSUE THREAD

**Issue by ballakers** [hacs/integration#2062]
### Web browser

Chrome

### Web browser version

90.0.4430.93

### System Health details

![Screen Shot 2021-05-08 at 8 00 05 AM](https://user-images.githubusercontent.com/69597117/117541920-74f36300-afd3-11eb-9bff-9be49d005594.png)

### Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Getting the error "_<Integration hacs/integration> Could not read manifest.json [encoding without a string argument]_", 

supervisor logs say "_ERROR (MainThread) [supervisor.store.git] Can't clone https://github.com/home-assistant/addons repository: Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules --progress https://github.com/home-assistant/addons /data/addons/core." and "ERROR (MainThread) [supervisor.store.repository] Can't remove built-in repositories!"_
 
All custom components are working fine except HACS itself - just says HACS is starting up in the UI for the past week or two and through multiple updates to HA core and supervisor.  The weird thing is that for the updates listed in the screenshot if I check the manifest.json for each they are actually already on the version it says to update to.  Tried to keep HACS up to date but seems maybe an update got interrupted to cause HA to not be able to read the HACS manifest.json.  Not too worried but I know I've seen the warnings to not remove HACS if you want to use in the future so my basic question is how should I get my HACS back to normal and back to the latest version without messing everything up.  Should I just drop the most recent version of HACS into the shared samba folder and delete the current HACS files? Will this affect all the current custom components I have set-up? Just want to make sure I don't royally screw things up and also haven't seen any reports of the issue I'm having so trying to document best I can.  Will follow up on discord chat also.  Thanks in advance everyone!  Running V 1.11.3 not by choice - but had to check the box saying running latest to submit this issue - hope that's acceptable.

### Reproduction steps

1. Added a version to Wyze sense manifest.json to keep HA happy since version must be listed for 2021.6
2. Updated HA supervisor and core and then updated some HACS custom integrations.
3. Result is everything is working fine integrations-wise except HACS is stuck on an older version and stuck on "HACS is starting up"
...

### Screenshots

![Screen Shot 2021-05-08 at 8 15 25 AM](https://user-images.githubusercontent.com/69597117/117542398-bc7aee80-afd5-11eb-9e4e-cb6a9b025ca8.png)
![Screen Shot 2021-05-08 at 8 15 38 AM](https://user-images.githubusercontent.com/69597117/117542400-bf75df00-afd5-11eb-89f1-738ea50e8112.png)
![Screen Shot 2021-05-08 at 7 50 55 AM](https://user-images.githubusercontent.com/69597117/117542404-c43a9300-afd5-11eb-9fb9-22af9bffeab4.png)

### Javascript logs from your browser console

```text
Array(3)
0:
categories: ["integration"]
core: true
iconPath: "M20.5,11H19V7C19,5.89 18.1,5 17,5H13V3.5A2.5,2.5 0 0,0 10.5,1A2.5,2.5 0 0,0 8,3.5V5H4A2,2 0 0,0 2,7V10.8H3.5C5,10.8 6.2,12 6.2,13.5C6.2,15 5,16.2 3.5,16.2H2V20A2,2 0 0,0 4,22H7.8V20.5C7.8,19 9,17.8 10.5,17.8C12,17.8 13.2,19 13.2,20.5V22H17A2,2 0 0,0 19,20V16H20.5A2.5,2.5 0 0,0 23,13.5A2.5,2.5 0 0,0 20.5,11Z"
id: "integrations"
info: "This is where you find custom integrations (custom_components)"
name: "Integrations"
path: "/hacs/integrations"
__proto__: Object
1:
categories: Array(2)
0: "plugin"
1: "theme"
length: 2
__proto__: Array(0)
core: true
iconPath: "M17.5,12A1.5,1.5 0 0,1 16,10.5A1.5,1.5 0 0,1 17.5,9A1.5,1.5 0 0,1 19,10.5A1.5,1.5 0 0,1 17.5,12M14.5,8A1.5,1.5 0 0,1 13,6.5A1.5,1.5 0 0,1 14.5,5A1.5,1.5 0 0,1 16,6.5A1.5,1.5 0 0,1 14.5,8M9.5,8A1.5,1.5 0 0,1 8,6.5A1.5,1.5 0 0,1 9.5,5A1.5,1.5 0 0,1 11,6.5A1.5,1.5 0 0,1 9.5,8M6.5,12A1.5,1.5 0 0,1 5,10.5A1.5,1.5 0 0,1 6.5,9A1.5,1.5 0 0,1 8,10.5A1.5,1.5 0 0,1 6.5,12M12,3A9,9 0 0,0 3,12A9,9 0 0,0 12,21A1.5,1.5 0 0,0 13.5,19.5C13.5,19.11 13.35,18.76 13.11,18.5C12.88,18.23 12.73,17.88 12.73,17.5A1.5,1.5 0 0,1 14.23,16H16A5,5 0 0,0 21,11C21,6.58 16.97,3 12,3Z"
id: "frontend"
info: "This is where you find themes, custom cards and other elements for lovelace"
name: "Frontend"
path: "/hacs/frontend"
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
2:
categories: Array(3)
0: "python_script"
1: "appdaemon"
2: "netdaemon"
length: 3
__proto__: Array(0)
concat: ƒ concat()
constructor: ƒ Array()
copyWithin: ƒ copyWithin()
entries: ƒ entries()
every: ƒ every()
fill: ƒ fill()
filter: ƒ filter()
find: ƒ find()
findIndex: ƒ findIndex()
flat: ƒ flat()
flatMap: ƒ flatMap()
forEach: ƒ forEach()
includes: ƒ includes()
indexOf: ƒ indexOf()
join: ƒ join()
keys: ƒ keys()
lastIndexOf: ƒ lastIndexOf()
length: 0
map: ƒ map()
pop: ƒ pop()
push: ƒ push()
reduce: ƒ reduce()
reduceRight: ƒ reduceRight()
reverse: ƒ reverse()
shift: ƒ shift()
slice: ƒ slice()
some: ƒ some()
sort: ƒ sort()
splice: ƒ splice()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
unshift: ƒ unshift()
values: ƒ values()
Symbol(Symbol.iterator): ƒ values()
Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}
__proto__: Object
core: true
iconPath: "M12,2A2,2 0 0,1 14,4C14,4.74 13.6,5.39 13,5.73V7H14A7,7 0 0,1 21,14H22A1,1 0 0,1 23,15V18A1,1 0 0,1 22,19H21V20A2,2 0 0,1 19,22H5A2,2 0 0,1 3,20V19H2A1,1 0 0,1 1,18V15A1,1 0 0,1 2,14H3A7,7 0 0,1 10,7H11V5.73C10.4,5.39 10,4.74 10,4A2,2 0 0,1 12,2M7.5,13A2.5,2.5 0 0,0 5,15.5A2.5,2.5 0 0,0 7.5,18A2.5,2.5 0 0,0 10,15.5A2.5,2.5 0 0,0 7.5,13M16.5,13A2.5,2.5 0 0,0 14,15.5A2.5,2.5 0 0,0 16.5,18A2.5,2.5 0 0,0 19,15.5A2.5,2.5 0 0,0 16.5,13Z"
id: "automation"
info: "This is where you find python_scripts, AppDaemon apps and NetDaemon apps"
name: "Automation"
path: "/hacs/automation"
__proto__: Object
length: 3
__proto__: Array(0)
```

**Comment by ludeeus** [comment]
Update HACS with the install script

**Comment by MikiZed** [comment]
> Update HACS with the install script

Can you elaborate on this?

**Comment by ludeeus** [comment]
Identical to how you install it
