### ISSUE TITLE
The main 'lit-element' module entrypoint is deprecated.

### ISSUE THREAD

**Issue by Delta1977** [hacs/integration#2073]
### Web browser

Google Chrome 

### Web browser version

91

## System Health

version | core-2021.6.0b4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.12.4
Stage | running
Available Repositories | 825
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.0.rc3
-- | --
update_channel | beta
supervisor_version | supervisor-2021.05.4
docker_version | 20.10.6
disk_total | 57.8 GB
disk_used | 21.3 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.1), InfluxDB (4.1.1), Nginx Proxy Manager (0.11.0), SSH & Web Terminal (8.2.3), Node-RED (9.1.3), MariaDB (2.3.0), AirSonos (3.1.0), Grafana (6.3.5), WireGuard (0.5.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 0
views | 2
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

https://github.com/lit/lit-element 
LEGACY REPO. This repository is for maintenance of the legacy LitElement library. The LitElement base class is now part of the Lit library, which is developed in the lit monorepo.

### Reproduction steps

HA With HACS

### Screenshots

![image](https://user-images.githubusercontent.com/1581154/120344935-55153d80-c2fa-11eb-8647-91806ecd7c09.png)

### Javascript logs from your browser console

```text
no logs vavailable
```

**Comment by ludeeus** [comment]
The hacs frontend runs in an iframe, and has not started migration to lit.
I'm guessing this is not from havs but from HA itself.
Potentially in the custom panel code.

**Comment by Delta1977** [comment]
I had only hacs addons without custom cards. 
HA had already migrated to new lit, I didn’t found any references in HA gut for old version. 

Im HACS frontend are 34 references for lit-element.

**Comment by ludeeus** [comment]
That does not matter, even if it's not imported directly in HA, it's used by things like buttons, and polyfills.

You see references in HACS, because it has not migrated, but also since it's using an older version, it can not print the messages you see, so it has to be from somewhere else (like HA itself)
