### ISSUE TITLE
HACS not themed correctly when using a custom theme which supports dark and light modes

### ISSUE THREAD

**Issue by gadgetchnnel** [hacs/integration#2078]
### Web browser

Google Chrome

### Web browser version

91.0.4472.77

## System Health

version | core-2021.6.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.4.79-v7l+
arch | armv7l
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4389
Installed Version | 1.12.4
Stage | running
Available Repositories | 841
Installed Repositories | 44

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 20 June 2021, 1:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 13
-- | --
resources | 52
views | 33
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

When using a theme supporting dark mode ([introduced in 2016.6.0](https://www.home-assistant.io/integrations/frontend/#dark-mode-support)) HACS does not use the correct theme

### Reproduction steps

1. Apply a theme supporting dark mode (see example below, taken from the documentation)
2. Open HACS

```yaml
day_and_night:
  primary-color: coral
  modes:
    light:
      secondary-text-color: olive
    dark:
      secondary-text-color: slategray
```

### Screenshots

![image](https://user-images.githubusercontent.com/2099542/121223977-00387080-c880-11eb-91a4-4e17a393036a.png)

### Javascript logs from your browser console

```text
No Javascript errors
```

**Comment by ludeeus** [comment]
Has already been fixed and pending release
![image](https://user-images.githubusercontent.com/15093472/121318254-5dc5cf00-c90b-11eb-980a-4236c8980235.png)
