### ISSUE TITLE
Appdaemon-Xiaomi-Smart-Button - GitHub returned 404

### ISSUE THREAD

**Issue by johncolet** [hacs/integration#2080]
### System Health details

Logger: custom_components.hacs
Source: custom_components/hacs/operational/factory.py:58
Integration: HACS (documentation, issues)
First occurred: 9:53:42 PM (4 occurrences)
Last logged: 9:53:42 PM

nickneos/Appdaemon-Xiaomi-Smart-Button - GitHub returned 404 for https://api.github.com/repos/nickneos/Appdaemon-Xiaomi-Smart-Button
nickneos/Appdaemon-Xiaomi-Doorbell - GitHub returned 404 for https://api.github.com/repos/nickneos/Appdaemon-Xiaomi-Doorbell
nickneos/Appdaemon-ZHA-Xiaomi-Aqara-Switch - GitHub returned 404 for https://api.github.com/repos/nickneos/Appdaemon-ZHA-Xiaomi-Aqara-Switch
Petro31/ad_multizone_media_control - Repository is archived.

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Logger: custom_components.hacs
Source: custom_components/hacs/operational/factory.py:58
Integration: HACS (documentation, issues)
First occurred: 9:53:42 PM (4 occurrences)
Last logged: 9:53:42 PM

nickneos/Appdaemon-Xiaomi-Smart-Button - GitHub returned 404 for https://api.github.com/repos/nickneos/Appdaemon-Xiaomi-Smart-Button
nickneos/Appdaemon-Xiaomi-Doorbell - GitHub returned 404 for https://api.github.com/repos/nickneos/Appdaemon-Xiaomi-Doorbell
nickneos/Appdaemon-ZHA-Xiaomi-Aqara-Switch - GitHub returned 404 for https://api.github.com/repos/nickneos/Appdaemon-ZHA-Xiaomi-Aqara-Switch
Petro31/ad_multizone_media_control - Repository is archived.

### Reproduction steps

1.No idea
2.
3.
...

### Debug logs

```text
Logger: custom_components.hacs
Source: custom_components/hacs/operational/factory.py:58

nickneos/Appdaemon-Xiaomi-Smart-Button - GitHub returned 404 for https://api.github.com/repos/nickneos/Appdaemon-Xiaomi-Smart-Button
nickneos/Appdaemon-Xiaomi-Doorbell - GitHub returned 404 for https://api.github.com/repos/nickneos/Appdaemon-Xiaomi-Doorbell
nickneos/Appdaemon-ZHA-Xiaomi-Aqara-Switch - GitHub returned 404 for https://api.github.com/repos/nickneos/Appdaemon-ZHA-Xiaomi-Aqara-Switch
Petro31/ad_multizone_media_control - Repository is archived.
```

**Comment by ludeeus** [comment]
@nickneos <https://hacs.xyz/docs/publish/remove>
