### ISSUE TITLE
Double scrollbar on repository information

### ISSUE THREAD

**Issue by MrBartusek** [hacs/integration#2086]
### Web browser

Vivaldi

### Web browser version

3.6.2165.49

## System Health

version | core-2021.6.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.4.83-v7l
arch | armv7l
timezone | Europe/Warsaw

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4905
Installed Version | 1.12.4
Stage | running
Available Repositories | 832
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.0
docker_version | 19.03.15
disk_total | 27.7 GB
disk_used | 5.9 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.1), ESPHome (1.18.0), Terminal & SSH (9.1.1), Home Assistant Google Drive Backup (0.104.3), Mosquitto broker (6.0.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 4
views | 2
mode | storage

</details>

<details><summary>meteoalarmeu</summary>

Reach API endpoint | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Information view of repository have a double scrollbar

### Reproduction steps

1. Install repository
2. Click 3 dots
3. Click information
4. See Error

### Screenshots

![image](https://user-images.githubusercontent.com/23432278/121775929-945d4d00-cb8a-11eb-85ba-7c8cd08e11de.png)

### Javascript logs from your browser console

```text
N/A
```

**Comment by ludeeus** [comment]
What OS and resolution are this with?

**Comment by MrBartusek** [comment]
Windows 1886x954
