### ISSUE TITLE
HACS integration fails with error "'auto-gen' is not a valid LovelaceMode", tried multiple times, even flashed HA from scratch.

### ISSUE THREAD

**Issue by videv-lab** [hacs/integration#2088]
## System Health

version | core-2021.6.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Asia/Calcutta

<details><summary>Home Assistant Community Store</summary>

error | failed to load: unknown
-- | --

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.0
docker_version | 20.10.6
disk_total | 28.6 GB
disk_used | 2.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), File editor (5.3.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

I setup HACS but everything succeeded but when I add hacs integration it fails with error
![image](https://user-images.githubusercontent.com/85816163/121805364-a57c8b80-cc68-11eb-8506-7202d0f13e88.png)

I have re run the setup many times, I even flashed HA and started from scratch, but this issue persists, unable to integrate hacs.

### Reproduction steps

1. Copy hacs files as documented
2. Restart the server
3. Hacs appears under integrations as expected.
4. When adding hacs integration, it fails with error
...

### Debug logs

```text
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/hacs/operational/setup.py:140
Integration: HACS (documentation, issues)
First occurred: 16:52:20 (1 occurrences)
Last logged: 16:52:20

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/hacs/operational/reload.py", line 10, in async_reload_entry
await async_setup_entry(hass, config_entry)
File "/config/custom_components/hacs/operational/setup.py", line 74, in async_setup_entry
return await async_startup_wrapper_for_config_entry()
File "/config/custom_components/hacs/operational/setup.py", line 98, in async_startup_wrapper_for_config_entry
startup_result = await async_hacs_startup()
File "/config/custom_components/hacs/operational/setup.py", line 140, in async_hacs_startup
hacs.core.lovelace_mode = LovelaceMode(lovelace_info.get("mode", "yaml"))
File "/usr/local/lib/python3.8/enum.py", line 339, in call
return cls.new(cls, value)
File "/usr/local/lib/python3.8/enum.py", line 662, in new
raise ve_exc
ValueError: 'auto-gen' is not a valid LovelaceMode
```

**Comment by ludeeus** [comment]
Fixed in <https://github.com/hacs/integration/commit/c22a13aaa32a4ae97a6d0fe04dd1f8620356eec8>
Workaround: Take control of lovelace <https://www.home-assistant.io/lovelace/>
