### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by noobJayharris** [hacs/integration#2089]
## System Health

version | core-2021.6.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.42
arch | x86_64
timezone | America/New_York

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | July 16, 2021, 8:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.3
docker_version | 20.10.6
disk_total | 30.8 GB
disk_used | 3.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.0.1), Visual Studio Code (3.4.1), Samba share (9.5.1), Tor (3.0.5), Google Assistant SDK (2.5.0), Example (4.1.0), SSH & Web Terminal (8.2.4)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 0
views | 3
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Trying to install HACS on HA hosted on Virtual machine(Virtual box). 

I ended up copying the files manually to the config folder through samba. Now, I could search HACS but when I try to install it it gives me the above error. 

I tried restarting my vm, HA, PC, 
I made sure the updated version of hacs file is downloaded. 

### Reproduction steps

1. I tried restarting my vm, HA, PC, 
2. I made sure the updated version of hacs file is downloaded. 
3.
...

### Debug logs

```text
aa
```

**Comment by jvdpas** [comment]
[home-assistant.log](https://github.com/hacs/integration/files/6671040/home-assistant.log)
Same here see log 
2021-06-17 16:28:49 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration hacs: cannot import name 'QueueManager' from 'queueman' (/usr/local/lib/python3.8/site-packages/queueman/__init__.py)

**Comment by ludeeus** [comment]
Restart home assistant a few times, if that does not help run `ha rebuild`

**Comment by yaroto98** [comment]
Same issue here, also @ludeeus  - there is no rebuild command for ha when I ssh into my pi.

**Comment by ludeeus** [comment]
That's for supervised/OS only

**Comment by yaroto98** [comment]
Awesome, well I encountered this issue on a system where I'm unable to execute that command.

**Comment by ludeeus** [comment]
Rebuild it another way then 🤷‍♂️, a dependency is missing/broken

**Comment by almera8** [comment]
I had a similar issue, for me it was resolved by installing another integration.
https://community.home-assistant.io/t/hacs-installing-problem-via-integration-error-config-flow-could-not-be-loaded/314501/7?u=almera8

**Comment by allenrobberson** [comment]
I have tried to x this issue with all of the ways said above and no luck at all.

this all i see in the log file

`2021-06-20 09:20:23 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

**Comment by ludeeus** [comment]
If that's all, you have changed the default `logger` config, there should be a lot more.
<https://www.home-assistant.io/integrations/logger/>
I recommend <https://hacs.xyz/docs/basic/logs>

ProTip: It's not HACS that will log anything useful, since it's not HACS that's having issues.

**Comment by jeeftor** [comment]
I ran into the same issue today

**Comment by aygee** [comment]
It looks like the installation process takes a long time. If you are accessing the home assistant using reverse proxy, the reverse proxy would throw 504 Gateway Time-out. You can see this on the devtool's Network tab. And you'll see the error "Config flow could not be loaded"

**Comment by ludeeus** [comment]
Great! that makes sense @aygee 👍 
so for anyone else that gets this, use local access with an IP address, or try multiple times.
