### ISSUE TITLE
I have a problem with ha_philips_android_tv Component for Philips TV android after core_2021.5.5

### ISSUE THREAD

**Issue by peshoteslata2** [hacs/integration#2091]
### System Health details

I have a problem with ha_philips_android_tv  Component for Philips TV android. Updates after core Release 2021.5.5 - Release 2021.6.1, Release 2021.6.2, Release 2021.6.3, Release 2021.6.4 and Release 2021.6.5 components for Philips TV and Philips TV ambilight dosen't work ("Entity not available: media_player.tv"). Core Release 2021.5.5 component works ok.

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

I have a problem with ha_philips_android_tv  Component for Philips TV android. Updates after core Release 2021.5.5 - Release 2021.6.1, Release 2021.6.2, Release 2021.6.3, Release 2021.6.4 and Release 2021.6.5 components for Philips TV and Philips TV ambilight dosen't work ("Entity not available: media_player.tv"). Core Release 2021.5.5 component works ok.

### Reproduction steps

1. Install 2021.6....
2. testing component
3. Restore 2021.5.5
...

### Debug logs

```text
...
```

**Comment by ludeeus** [comment]
Open an issue with the author of that integration.
