### ISSUE TITLE
Error while loading page entry on Safari

### ISSUE THREAD

**Issue by GaoMax** [hacs/integration#2094]
### Web browser

Safari

### Web browser version

14.1.1 

## System Health

version | core-2021.6.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.42
arch | x86_64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 3678
Installed Version | 1.13.0
Stage | running
Available Repositories | 918
Installed Repositories | 29

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.0
-- | --
update_channel | beta
supervisor_version | supervisor-2021.06.3
docker_version | 20.10.6
disk_total | 97.7 GB
disk_used | 71.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.1), Terminal & SSH (9.1.3), Duck DNS (1.12.5), NGINX Home Assistant SSL proxy (3.0.1), deCONZ (6.9.0), AirCast (3.1.1), Check Home Assistant configuration (3.7.1), Node-RED (9.1.4), ESPHome (1.19.0), Samba share (9.5.1), Frigate NVR (1.13), AdGuard Home (4.1.6), Mosquitto broker (6.0.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 8
-- | --
resources | 18
views | 93
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

After updating to 1.13.0, HACS Frontend stopped working on Safari (cache reset, on both macOS and iOS). A reinstall of HACS and reboots on the host and end devices did not help. Chrome works fine.

### Reproduction steps

1. Update to 1.13.0
2. When using Safari "Error while loading page entry." appears when trying to access the frontend
3.
...

### Screenshots

![Screen Shot 2021-06-20 at 14 34 48](https://user-images.githubusercontent.com/18214226/122674271-abc4b780-d1d4-11eb-8d9a-ac636a81a78a.png)

### Javascript logs from your browser console

```text
[Error] Error loading page – "entry"
SyntaxError: Invalid regular expression: invalid group specifier name
parseModule
[native code]
asyncFunctionResume
[native code]
promiseReactionJobWithoutPromise
	(anonymous function) (main-b9893c22.js:1538:522683)
	promiseReactionJob
```

**Comment by weitheng** [comment]
Does not seem to work even after resetting frontend-cache on the HA app

**Comment by marcusrugger** [comment]
I get the same thing from the iOS mobile app.  I don't know if that should be entered as a separate issue, or just acknowledged in this one.

I updated to 1.13, and now HACS won't load in the mobile app, as described above.

**Comment by weitheng** [comment]
> I get the same thing from the iOS mobile app. I don't know if that should be entered as a separate issue, or just acknowledged in this one.
> 
> I updated to 1.13, and now HACS won't load in the mobile app, as described above.

I suspect it's the update. Doesn't work on desktop browsers as well ever since updating it

**Comment by Reynders1** [comment]
@ludeeus Sorry, but it still doesn't work. I removed the integration, cleared the cache, restarted the core (and even the host), reinstalled the integration and still get the same message "Error while loading page entry."
Anything I can try? Thanks for your support.

**Comment by ludeeus** [comment]
update

**Comment by Reynders1** [comment]
Sorry, I can't see the option to do it. Where is it?

**Comment by GaoMax** [comment]
Update to 1.13.1 using Google Chrome or update through SSH 
`wget -q -O https://install.hacs.xyz | bash -`

**Comment by marcusrugger** [comment]
It's working for me.  Thanks.

**Comment by Reynders1** [comment]
Same for me now. Many thanks!

**Comment by Dominik-1980** [comment]
I can confirm updating to 1.13.1 works.

For me your bash command didn’t work. It was missing an -
I did type this:

wget -q -O - https://install.hacs.xyz | bash -
