### ISSUE TITLE
HACS is deactivated and cannot be reinstalled

### ISSUE THREAD

**Issue by Pirol62** [hacs/integration#2095]
### System Health details

cannot be provided
HASSIO 2021.6.4
Rasb3+
OS 3.11

Logger: homeassistant
Source: custom_components/hacs/system_health.py:24
Integration: HACS (documentation, issues)
First occurred: 14:42:26 (6 occurrences)
Last logged: 14:52:14

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 104, in handle_info
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 69, in get_integration_info
    data = await registration.info_callback(hass)
  File "/config/custom_components/hacs/system_health.py", line 24, in system_health_info
    rate_limit = await client.github.get_rate_limit()
  File "/usr/local/lib/python3.8/site-packages/aiogithubapi/github.py", line 102, in get_rate_limit
    await self.client.get(endpoint=_endpoint)
  File "/usr/local/lib/python3.8/site-packages/aiogithubapi/client.py", line 49, in get
    response = await async_call_api(
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/aiogithubapi/helpers.py", line 79, in async_call_api
    raise AIOGitHubAPIAuthenticationException(HttpStatusCode.UNAUTHORIZED)
aiogithubapi.common.exceptions.AIOGitHubAPIAuthenticationException: HttpStatusCode.UNAUTHORIZED

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

HACS is not available after restart. Cannot be installed again

### Reproduction steps

1. Recreate Access Token Github via Link provided in Mail
2. Delete HACS
3. Restart HA

![image](https://user-images.githubusercontent.com/48820003/122674924-7ec5d400-d1d7-11eb-8ee0-37b762caef00.png)

![image](https://user-images.githubusercontent.com/48820003/122674912-6fdf2180-d1d7-11eb-9727-f3f9b917d341.png)

### Debug logs

```text
benutzerdefinierte

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:123
Integration: HACS (documentation, issues)
First occurred: 14:16:29 (3 occurrences)
Last logged: 14:46:30

HACS is disabled - HacsDisabledReason.INVALID_TOKEN

benutzerdefinierte

Logger: custom_components.hacs
Source: custom_components/hacs/operational/setup.py:159
Integration: HACS (documentation, issues)
First occurred: 14:16:29 (3 occurrences)
Last logged: 14:46:30

Your GitHub token is not valid

benutzerdefinierte

Logger: custom_components.hacs
Source: custom_components/hacs/helpers/functions/remaining_github_calls.py:14
Integration: HACS (documentation, issues)
First occurred: 14:16:29 (3 occurrences)
Last logged: 14:46:30

HttpStatusCode.UNAUTHORIZED
```

**Comment by ludeeus** [comment]
Update your configuration with the new token.
ref https://github.com/hacs/integration/issues/2014

**Comment by Pirol62** [comment]
Hi @ludeeus. But where can I enter the token when HA avoids to setup Hacs new. See screenshot above "only a single instance....."

**Comment by ludeeus** [comment]
Wherever you added the configuration for it.

**Comment by Pirol62** [comment]
Hacs was installed via config flow. I have no configuration file or yaml. I do not have the hacs integration available. There is no object/card in the integrations view

**Comment by Pirol62** [comment]
Sorry, I rechecked the configuration and detected, that the token was still configured there. Sorry for causing stress on sunday.
Thanks for your patience
