### ISSUE TITLE
Orphaned repositories can´t be uninstalled

### ISSUE THREAD

**Issue by bcutter** [hacs/integration#2098]
## System Health

version | core-2021.6.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4589
Installed Version | 1.13.1
Stage | running
Available Repositories | 910
Installed Repositories | 66

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.3
docker_version | 20.10.6
disk_total | 57.8 GB
disk_used | 27.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), deCONZ (6.9.0), Node-RED (9.1.4), CEC Scanner (2.4), AppDaemon 4 (0.6.2), Home Panel (2.2.1), motionEye (0.14.0), SQLite Web (3.1.0), Let's Encrypt (4.11.0), Portainer (1.5.1), Hey Ada! (1.1.1), Terminal & SSH (9.1.3), Almond (1.1.2), File editor (5.3.1), Grafana (7.0.1), Log Viewer (0.11.0), MariaDB (2.4.0), Samba Backup (4.5.0), InfluxDB (4.1.1), Visual Studio Code (3.4.1), Glances (0.12.2), SSH & Web Terminal (8.2.4), Check Home Assistant configuration (3.7.1), room-assistant (2.18.4), AirCast (3.1.1), UniFi Controller (0.23.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 4
-- | --
resources | 33
views | 50
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Two orphaned repositories cannot be deleted. Ran uninstall several times including HA restart, nothing changed. Removing those repos using the UI is not possible.

![grafik](https://user-images.githubusercontent.com/13799156/122687327-1b0ecb80-d216-11eb-8f9f-ddadc0a610c6.png)

https://github.com/hacs/integration/issues/2080

### Reproduction steps

1. Install an integration/automation/...
2. Wait until it get´s removed (doesn´t exist anymore
3. Try to remove it from HACS.

### Debug logs

```text
Will follow shortly
```

**Comment by ludeeus** [comment]
Remove them from <https://hacs.xyz/docs/faq/custom_repositories>

**Comment by bcutter** [comment]
> 
> 
> Remove them from https://hacs.xyz/docs/faq/custom_repositories

Perfect, this solved it finally. Too easy 👍
