### ISSUE TITLE
Request for removal of ljmerza/light-entity-card

### ISSUE THREAD

**Issue by PhyberApex** [hacs/integration#2109]
### Repository

ljmerza/light-entity-card

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

No longer works and is not maintained (Mentioned in the README)

### Link to issue

https://github.com/ljmerza/light-entity-card/issues/65

**Comment by ljmerza** [comment]
chill dude its only been a day. some people have lives outside home assistant

**Comment by PhyberApex** [comment]
Uhhh that's totally my bad. I just tried to use it ad it didn't work. Probably did something wrong and just found that issue and I could have legit sworn there was a mention in your readme that you no longer maintain the repo. No maintance -> no fix to be expected. I guess I mixed stuff up. That's why I just put this up. Sorry again!

~Cheers

**Comment by ljmerza** [comment]
I already use my own internal lit so the blog post never applied to me. I use the cards myself and have never had issues am currently on july RC and everything works fine. I just checked on june and it still works. I went into details in the issue itself.
