### ISSUE TITLE
4 repositories to archive

### ISSUE THREAD

**Issue by Bastiencc** [hacs/integration#2115]
## System Health

version | core-2021.7.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.10.17-v7
arch | armv7l
timezone | Europe/Paris

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4876
Installed Version | 1.13.2
Stage | running
Available Repositories | 844
Installed Repositories | 19

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 228.5 GB
disk_used | 4.2 GB
healthy | true
supported | true
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.2), Samba share (9.5.1), Zigbee2mqtt (1.20.0-1), Mosquitto broker (6.0.1), Terminal & SSH (9.1.3), ESPHome (1.19.4), Let's Encrypt (4.11.0), Check Home Assistant configuration (3.8.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 14
views | 8
mode | yaml

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

4 repositories to archive : 
    bieniu/ha-airly - Repository is archived.
    thomasloven/lovelace-dummy-entity-row - Repository is archived.
    thomasloven/lovelace-gap-card - Repository is archived.
    thomasloven/lovelace-gui-sandbox - Repository is archived.

### Reproduction steps

Install hacs

### Debug logs

```text
Logger: custom_components.hacs
Source: custom_components/hacs/operational/factory.py:58
Integration: HACS (documentation, issues)
First occurred: 09:20:54 (4 occurrences)
Last logged: 09:20:55

    bieniu/ha-airly - Repository is archived.
    thomasloven/lovelace-dummy-entity-row - Repository is archived.
    thomasloven/lovelace-gap-card - Repository is archived.
    thomasloven/lovelace-gui-sandbox - Repository is archived.
```

**Comment by MrAlucardDante** [comment]
This issue is still a thing, even though the original post (https://github.com/hacs/integration/issues/1789) was closed.

It happened again today, and this is not normal. It shouldn't trigger errors on HA instances when a repo is archived.

2021-07-14 23:25:10 ERROR (MainThread) [custom_components.hacs] troykelly/hacs-amberelectric - Repository is archived.

**Comment by MrAlucardDante** [comment]
Some new exemples popped in.

2021-07-25 12:45:26 ERROR (MainThread) [custom_components.hacs] robmarkcole/Hue-sensors-HASS - Repository is archived.
2021-07-25 12:55:06 ERROR (MainThread) [custom_components.hacs] xlcnd/meteoalarmeu - Repository is archived.

**Comment by rob1303-hub** [comment]
Still happening for me, everytime I restart HA:

This error originated from a custom integration.

_Logger: custom_components.hacs
Source: custom_components/hacs/operational/factory.py:58
Integration: HACS (documentation, issues)
First occurred: 10:28:53 (3 occurrences)
Last logged: 10:28:53

thomasloven/lovelace-dummy-entity-row - Repository is archived.
thomasloven/lovelace-gui-sandbox - Repository is archived.
thomasloven/lovelace-gap-card - Repository is archived._

**Comment by RubenKelevra** [comment]
> Some new exemples popped in.

> 2021-07-25 12:55:06 ERROR (MainThread) [custom_components.hacs] xlcnd/meteoalarmeu - Repository is archived.

This feels wrong. I'm actively using it with the DWD service which is also supported. @xlcnd can you maybe unarchive it? I doubt that DWD will change their API anytime soon. :)

**Comment by rob1303-hub** [comment]
> Still happening for me, everytime I restart HA:
> 
......
> 
> thomasloven/lovelace-dummy-entity-row - Repository is archived.
> thomasloven/lovelace-gui-sandbox - Repository is archived.
> thomasloven/lovelace-gap-card - Repository is archived._

@ludeeus 
Can confirm these no longer appear in the log - thank you.

**Comment by jhallenb** [comment]
Why is gapcard archived?
It is great to force equal sizes in horizontal cards.

**Comment by gersilex** [comment]
> > Some new exemples popped in.
> 
> > 2021-07-25 12:55:06 ERROR (MainThread) [custom_components.hacs] xlcnd/meteoalarmeu - Repository is archived.
> 
> This feels wrong. I'm actively using it with the DWD service which is also supported. @xlcnd can you maybe unarchive it? I doubt that DWD will change their API anytime soon. :)

meteoalarm.eu is now deprecated and stays empty. Current data is at meteoalarm.org and might need an API reimplementation.

**Comment by GuitarSkater** [comment]
> Why is gapcard archived?
> It is great to force equal sizes in horizontal cards.

Right? I was wondering the same thing
