### ISSUE TITLE
Request for removal of xMrVizzy/button-toolbar

### ISSUE THREAD

**Issue by Eddym83** [hacs/integration#2120]
### Repository

xMrVizzy/button-toolbar

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

I can't remove it and it keeps giving me errors in home assistant can anyone help me?

### Link to issue

z

**Comment by ludeeus** [comment]
This was removed a long time ago, if you still have it remove it from your custom repos <https://hacs.xyz/docs/faq/custom_repositories>
