### ISSUE TITLE
FRITZ!Box Tools

### ISSUE THREAD

**Issue by chemelli74** [hacs/integration#2121]
### Repository

https://github.com/mammuth/ha-fritzbox-tools

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

FRITZ!Box Tools - part of HomeAssistant >= 2021.7.0

As of HA core 2021.7.0 all functionalities of this integration are part of HA core. This custom integration is not maintained anymore, as a result. Thanks for supporting us with this custom integration.

This custom integration is now deprecated because is fully merged into HomeAssistant core.

CC @mammuth

### Link to issue

https://github.com/mammuth/ha-fritzbox-tools/blob/master/README.md

**Comment by mammuth** [comment]
Great, thanks!
