### ISSUE TITLE
Custom icon set not loading until I reselect the lovelace dashboard

### ISSUE THREAD

**Issue by arallsopp** [hacs/integration#2123]
### Web browser

Chrome on Mac

### Web browser version

Version 92.0.4515.107 (Official Build) (x86_64)

## System Health

version | core-2021.7.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.9.16
arch | aarch64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.13.2
Stage | running
Available Repositories | 843
Installed Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 113.9 GB
disk_used | 6.4 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), File editor (5.3.3), RPC Shutdown (2.2), Home Assistant Google Drive Backup (0.103.1), Terminal & SSH (9.1.3), Visual Studio Code (3.6.0), ngrok Client (2.1.6), ESPHome (1.20.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 4
-- | --
resources | 4
views | 10
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

I am using a hacs frontend script to add custom icons to my dashboard. When I load home assistant, the script supporting that icon set does not appear to load until I manually re-select the lovelace dashboard. Having the icons in use on my default view means no icons show up until I click into another lovelace dash or system page, then reselect the one I started with.

### Reproduction steps

1. Add the HACS default frontend script at https://github.com/arallsopp/hass-hue-icons to add icons. 
2. Employ these icons in a dashboard that is set as your default view.
3. Refresh or load Home Assistant in the browser.
4. Observe the custom icons are absent.
5. Select another dashboard or Map, Logbook, history, etc.
6. Select the dashboard again to see the icons in place.

If the icons are not used in the default view, the issue is impossible to detect, as a manual click on the dashboard menu seems to fix it.

Video recording of issue in [this unlisted youtube clip](https://www.youtube.com/watch?v=gTEwUlD8u5U).

* Disclaimer: I am the author of that icon script. 

## Before manual selection of the dashboard
hass and mdi:icons are visible, but the custom icons used to inform the first bank of lights is not shown.
![image](https://user-images.githubusercontent.com/2462104/128001957-d137a24a-2377-4a21-9a4a-23a9cb5a7541.png)

## After manual (re)selection of this dashboard
hass and mdi:icons are accompanied by the custom icons.
![image](https://user-images.githubusercontent.com/2462104/128001842-0eea60cd-d0c9-4aa0-a247-1299a1c6add3.png)

### Javascript logs from your browser console

```text
app.62541dd1.js:13499 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.
55704 @ app.62541dd1.js:13499
s @ app.62541dd1.js:36082
53918 @ app.62541dd1.js:1279
s @ app.62541dd1.js:36082
(anonymous) @ app.62541dd1.js:36082
(anonymous) @ app.62541dd1.js:42188
(anonymous) @ app.62541dd1.js:42188
hass-hue-icons.js?hacstag=3844345221040:359  HASS-HUE-ICONS    Version 1.0.40    
slider-entity-row.js?hacstag=1448997001710:59 SLIDER-ENTITY-ROW 17.1.0 IS INSTALLED 
swipe-navigation.js?hacstag=183995552136:51 ≡ swipe-navigation      ⋮ version 1.3.6            
fold-entity-row.js?hacstag=1507819942004:42 FOLD-ENTITY-ROW 20.0.4 IS INSTALLED
```

**Comment by ludeeus** [comment]
You request them before they can be used.

Use `frontend.extra_module_url` for icons like (https://github.com/elax46/custom-brand-icons) or register it with an integration (like https://github.com/thomasloven/hass-fontawesome)

**Comment by arallsopp** [comment]
Thanks for this @ludeeus. I've looked through the source of https://github.com/elax46/custom-brand-icons and am struggling to find any difference in the way we build our icon sets or way to tell HACS that this should be loaded using frontend.extra_module_url

Reading around it looks like I'd have to add the lines below to configuration.yaml? 

```
frontend:
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js
``` 

Is there a way to instruct HACS to do this when we click 'Install this repository in HACS' or should I just update the installation instructions?

**Comment by ludeeus** [comment]
That is correct, no HACS can not and should not manage that configuration, so you would have to do that manually.

**Comment by arallsopp** [comment]
Perfect. Thank you.
