### ISSUE TITLE
Hacs integrations (SonOff) stopped working after recent Core 2021.8.0 update

### ISSUE THREAD

**Issue by sgbossinga** [hacs/integration#2126]
### Web browser

chrome

### Web browser version

latest

### System Health details

n/a

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

HACS entities have exclamation marks as a status after updating HA Core from 2021.7.4 to 2021.8.0 today

### Reproduction steps

1.
2.
3.
...

### Screenshots

n/a

### Javascript logs from your browser console

```text
n/a
```

**Comment by ludeeus** [comment]
This is not related to HACS at all

**Comment by sgbossinga** [comment]
> This is not related to HACS at all

why not and if so what is causing this?

**Comment by ludeeus** [comment]
Ask the author of it

**Comment by sgbossinga** [comment]
> Ask the author of it

ok issue has just been reported, thanks
