### ISSUE TITLE
Request for removal of AlexxIT/XiaomiGateway3

### ISSUE THREAD

**Issue by yuche119** [hacs/integration#2128]
### Repository

AlexxIT/XiaomiGateway3

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Due to a system error, the entire home assistant was reset

### Link to issue

https://github.com/hacs/integration/issues/new?assignees=ludeeus&labels=flag&template=removal.yml&repo=AlexxIT/XiaomiGateway3&title=Request%20for%20removal%20of%20AlexxIT/XiaomiGateway3

**Comment by aex351** [comment]
This seems invalid. This integration is key to get a lot of Xiaomi products working within Home Assistant. Next to this, on AlexxIT/XiaomiGateway3 there is no mention of any 'bug' that leads to an entire home assistant reset.
