### ISSUE TITLE
Unable to setup integration, config flow could not be loaded

### ISSUE THREAD

**Issue by wtahler** [hacs/integration#2131]
## System Health

version | core-2021.8.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | America/New_York

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.2
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 6.6 GB
disk_used | 4.8 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS (0.1.34), Duck DNS (1.13.0), File editor (5.3.3), NGINX Home Assistant SSL proxy (3.0.2), Node-RED (9.2.1), SSH & Web Terminal (9.0.0), Home Assistant Google Drive Backup (0.104.3), Samba share (9.5.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

After following installation instructions I am not able to add the HACS integration to Home Assistant. After selecting it from the "add integration" UI I get the "please wait while HACS is being setup" followed eventually by "Error: Config flow could not be loaded".  I have removed HACS following the removal instructions 2 times (including restarting HA twice each time) and completely followed installation instructions again.  I have cleared the browser cache and tried an incognito window as well, same outcome.  The home assistant logs give no information for the failure, and I have been having this issue over several versions of Home Assistant (I retry completely removing and re-installing HACS each time, same final "config flow could not be loaded" error).  

### Reproduction steps

1. Connect to terminal via ssh
2. Run the HACS install script, copied from installation instructions.
3. Restart Home Assistant (terminal message tells me to do that after install script finishes)
4. Go to configuration-->integrations page of home assistant
4.  ctrl+shift+R to reload (or open in incognito)
5. Click "add integration"
6. Scroll down to find HACS and click on it
7. Wait while "please wait while HACS is being setup" message displays
8. Message "error: config flow could not be loaded"
...

### Debug logs

```text
HACS integration is not installed, no debug logs available for HACS.
```

**Comment by ludeeus** [comment]
Use http://IP:8123 and not go though a proxy
Default config for proxies times out after 1min

**Comment by wtahler** [comment]
Thank you!
