### ISSUE TITLE
Last element in list has floating button in front of options button, preventing user from being able to select options in menu

### ISSUE THREAD

**Issue by briangunderson** [hacs/integration#2135]
### Web browser

HA app on IoS 

### Web browser version

Most recent

### System Health details

N/A

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

![0B2C3C51-05E2-47F4-9B3A-85764B890891](https://user-images.githubusercontent.com/1896394/129421261-23840d9f-8a19-4e66-8943-194f8f4614cd.png)

### Reproduction steps

See screenshot 

### Screenshots

![275AE2B7-DDD0-411C-BBF1-668F1563521C](https://user-images.githubusercontent.com/1896394/129421294-51eccb00-a923-42d4-872c-4f9ba88cf8dd.png)

### Javascript logs from your browser console

```text
NA
```

**Comment by briangunderson** [comment]
The “explore & add repositories” button blocks the menu of the bottom-most item in the list

**Comment by ludeeus** [comment]
missing required issue information
