### ISSUE TITLE
Unable to dismiss Minecraft Version and Philips AirPurifier repositories

### ISSUE THREAD

**Issue by circa1741** [hacs/integration#2148]
### Web browser

Firefox

### Web browser version

91.0 (64-bit)

## System Health

version | core-2021.8.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.53
arch | x86_64
timezone | America/Chicago

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4831
Installed Version | 1.13.2
Stage | running
Available Repositories | 928
Installed Repositories | 15

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.2
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 62.3 GB
disk_used | 11.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | UniFi Controller (1.0.0), Duck DNS (1.13.0), SSH & Web Terminal (9.0.1), chrony (2.2.0), Portainer (1.5.2), AdGuard Home (4.1.9), Vaultwarden (Bitwarden) (0.12.2), ESPHome (1.20.4), WireGuard (0.5.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 11
views | 6
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

I have tried individually dismissing the Minecraft Version and Philips AirPurifier repositories, as well as, clicking "Dismiss all new repositories." The 2 repositories pop up again after a reboot.

### Reproduction steps

1. Dismiss the Minecraft Version and Philips AirPurifier repositories.
2. Observe that it is dismissed.
3. Now, reboot the system.
4. Observe that the 2 repositories pop up again.

There were a lot of new repositories that popped up a few days ago and those were successfully dismissed. Why were those dismissed successfully but the 2 above would keeps popping up again?

### Screenshots

![image](https://user-images.githubusercontent.com/8772586/129652765-1166975e-e38c-49a0-8229-56d4ea6d8b97.png)

### Javascript logs from your browser console

```text
WebExtensions: reset-default-search: starting. api.js:183
WebExtensions: reset-default-search: has already ran once and saw panel, exit. api.js:210
LoginManagerPrompter: _getShortDisplayHost couldn't process https://192.168.1.25:7277 3 LoginManagerPrompter.jsm:983:11
e is undefined h0-main.js:1
Unchecked lastError value: Error: Invalid window ID: 55 h0-main.js:1
TypeError: a.default.detectStore(...) is undefined 2 h1-check.js:1:1301
TypeError: a.default.detectStore(...) is undefined h1-check.js:1:1301
TypeError: a.default.detectStore(...) is undefined h1-check.js:1:1301
LoginManagerPrompter: _getShortDisplayHost couldn't process https://192.168.1.25:7277 LoginManagerPrompter.jsm:983:11
Use of nsIFile in content process is deprecated. 3 NetUtil.jsm:253:8
browser.ui.customized_widgets - The key length must be limited to 72 characters.
Use of nsIFile in content process is deprecated. 2 NetUtil.jsm:253:8
Use of nsIFile in content process is deprecated. NetUtil.jsm:253:8
```

**Comment by ludeeus** [comment]
They moved the repositories, it has been fixed in <https://github.com/hacs/integration/pull/2144>
