### ISSUE TITLE
tellerbop/havistapool - Repository is archived

### ISSUE THREAD

**Issue by birdie60** [hacs/integration#2152]
### Repository

tellerbop/havistapool

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Today I got this ERROR in my Home Assistant Log. I am not using this integration at all. I saw that the Githup repository tellerbop/havistapool was archived by its author. It was not possible to add an issue on that Github project.
I assume that I am not the only one getting this error in the log, so pls regard removing this repositöry from HACS.
[https://github.com/tellerbop/havistapool](url)

`Logger: custom_components.hacs`
`Source: custom_components/hacs/operational/factory.py:34`
`Integration: HACS (documentation, issues)`
`First occurred: 19. August 2021, 13:12:30 (1 occurrences)`
`Last logged: 19. August 2021, 13:12:30`
`tellerbop/havistapool - Repository is archived.`

### Link to issue

N/A

**Comment by short4bmoney** [comment]
Seconding this issue... is there a way to individually remove the repo or does this have to be done by HACS admins?
