### ISSUE TITLE
Problem with check version of plugin and HACS

### ISSUE THREAD

**Issue by maury77** [hacs/integration#2186]
### System Health details

![image](https://user-images.githubusercontent.com/35746732/131230797-22e529fb-f4c6-434e-a283-be4fd68da582.png)

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

The system notify the the version of hacs and 1 plugin is to upgrade 

![image](https://user-images.githubusercontent.com/35746732/131230828-ef63160d-9d43-4c45-911d-9227d8529f2f.png)

but the version is the last 

![image](https://user-images.githubusercontent.com/35746732/131230834-86fac111-5418-4b0e-9a47-30d578d3a41f.png)

If I try to click on update 

 [backoff] Backing off async_download_file(...) for 0.0s (asyncio.exceptions.TimeoutError)

I try to reinstall but the problem is the same

### Reproduction steps

1) click on upgrade
2)  [backoff] Backing off async_download_file(...) for 0.0s (asyncio.exceptions.TimeoutError)

### Debug logs

```text
[backoff] Backing off async_download_file(...) for 0.0s (asyncio.exceptions.TimeoutError)
```

**Comment by ludeeus** [comment]
Disable IPv6 and then update it.

**Comment by maury77** [comment]
> Disable IPv6 and then update it.

thanks!!!!!! I resolved with disable of IPv6

**Comment by MichaIng** [comment]
@ludeeus 
How did you know and why is IPv6 the issue?

**Comment by ludeeus** [comment]
Seen it before.
GitHub don't support ipv6

**Comment by MichaIng** [comment]
While this is true, and somehow embarrassing at the same time 😄, both `github.com` and `raw.githubusercontent.com` also do not have an AAAA DNS record, so why would any client even try to connect via IPv6? It somehow breaks all efforts to go forward with the necessary establishment of IPv6 if disabling it is required to run certain software, even that it is trivial to know when a host is reachable via IPv6 or not.

**Comment by ludeeus** [comment]
I don't, HACS uses the shared aiohttp client session from home assistant that all other integrations uses at well.

**Comment by MichaIng** [comment]
Thanks, so this is something we need to find and fix in HA core then.
