### ISSUE TITLE
Failed after snapshot restoration 

### ISSUE THREAD

**Issue by Gurgeh88** [hacs/integration#2195]
## System Health

version | core-2021.8.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.53
arch | x86_64
timezone | Australia/Melbourne

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | September 1, 2021, 10:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.2
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 30.8 GB
disk_used | 4.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | SSH & Web Terminal (9.0.1), File editor (5.3.3), Home Assistant Google Drive Backup (0.104.3), Check Home Assistant configuration (3.8.0), Mosquitto broker (6.0.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 4
views | 7
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Hi there,

I recently had to restore my Home Assistant OS install from a full snapshot.

At the time of writing, I'm using the latest version of Home Assion OS installed into a Virtual Box environment on Windows 10.

When HA came back online after the restoration, the HACS icon had disappeared from my quick access panel on the left of the screen.

I checked the HACS entry on the integration page and it says "! Not loaded" in the description.

So I searched high and low for a solution, finding lots of threads where users had similar problems but none of their suggestions have worked for me. DISCLAIMER: I am very new to Home Assistant with limited understanding of coding.

I really like HACS and would appreciate it if someone could help me to get it up and running again. Here is what I've tried so far:

-the error that shows on boot of HA regarding HACS is the following:

```
Logger: homeassistant.setup
Source: setup.py:173
First occurred: 03:02:52 (1 occurrences)
Last logged: 03:02:52

Setup failed for hacs: Unable to import component: cannot import name 'ACCEPT_HEADERS' from 'aiogithubapi.common.const' (/usr/local/lib/python3.9/site-packages/aiogithubapi/common/const.py)
```

-I followed the instructions on this page to remove the integration: https://hacs.xyz/docs/installation/remove
-I am a recent HA adopter so there was nothing in config
-when I click delete on the HACS integration in the UI, nothing happens - instead, I get the following error in my log:

```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/hacs/const.py:2
Integration: HACS (documentation, issues)
First occurred: 08:04:02 (1 occurrences)
Last logged: 08:04:02

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 89, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 70, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 809, in async_remove
    await entry.async_remove(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 467, in async_remove
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/hacs/__init__.py", line 9, in <module>
    from .const import DOMAIN
  File "/config/custom_components/hacs/const.py", line 2, in <module>
    from aiogithubapi.common.const import ACCEPT_HEADERS
ImportError: cannot import name 'ACCEPT_HEADERS' from 'aiogithubapi.common.const' (/usr/local/lib/python3.9/site-packages/aiogithubapi/common/const.py)
```

*** the above happened no matter how many times I restarted HA or whether or not I had clicked Disable on the integration (which seems to work as it shows as Disabled)
-I tried at this point to delete the custom_components folder using the File Editor add-on (with the integration both disabled or enabled) but it gave me the following error (both times)

![ee1b06a362c0e66db2c899a03806014ff7e87be9_2_690x122](https://user-images.githubusercontent.com/86870554/131275325-3ceec319-dc55-4e1c-9d4c-7488d4936799.png)

-so I tried renaming the hacs folder in custom_components to "temp_hacs" and then used the following command in the terminal to reinstall HACS:

`wget -q -O - https://install.hacs.xyz | bash -`

-this showed as successfully installing HACS so I restarted Home Assistant but alas the same thing happened and now I am stuck having tried all of the above without success

My wondering is why can I not use the File Editor to delete the folder in custom_components? And why is nothing happening when I click delete on the integration in the UI?

I've tried to include as much information as possible here but please let me know if you need anything extra.

Many thanks :slight_smile:

### Reproduction steps

Please see issue description for greater detail.
1) restored from full snapshot
2) HACS did not load upon restoration
3) tried to follow the HACS removal instruction but could not complete the delete action OR delete the folder in custom components
4) renamed HACS folder in custom components so I could reinstall using the command for install in terminal
5) install seemed to work fine but still can't use or remove HACS

### Debug logs

```text
Logger: homeassistant.setup
Source: setup.py:173
First occurred: 03:02:52 (1 occurrences)
Last logged: 03:02:52

Setup failed for hacs: Unable to import component: cannot import name 'ACCEPT_HEADERS' from 'aiogithubapi.common.const' (/usr/local/lib/python3.9/site-packages/aiogithubapi/common/const.py)
```

```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/hacs/const.py:2
Integration: HACS (documentation, issues)
First occurred: 08:04:02 (1 occurrences)
Last logged: 08:04:02

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 89, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 70, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 809, in async_remove
    await entry.async_remove(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 467, in async_remove
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/hacs/__init__.py", line 9, in <module>
    from .const import DOMAIN
  File "/config/custom_components/hacs/const.py", line 2, in <module>
    from aiogithubapi.common.const import ACCEPT_HEADERS
ImportError: cannot import name 'ACCEPT_HEADERS' from 'aiogithubapi.common.const' (/usr/local/lib/python3.9/site-packages/aiogithubapi/common/const.py)
```
```

**Comment by ludeeus** [comment]
The short answer is that you have an old version of `aiogithubapi` installed.
Restart Home Assistant multiple times to retrigger that installation.

As for why fileeditor can't remove :man_shrugging: maybe it's hiding files

**Comment by Gurgeh88** [comment]
> The short answer is that you have an old version of `aiogithubapi` installed.
> Restart Home Assistant multiple times to retrigger that installation.
> 
> As for why fileeditor can't remove 🤷‍♂️ maybe it's hiding files

Thanks so much for the reply ludeeus. Since this problem first occurred I've restarted my Home Assistant numerous times but it hasn't changed the result. Is there a way to manually update "aiogithubapi"? Also, in my Googling, I've noticed that some people use FTP to access their Home Assistant in order to delete the folder. I tested it and I can also login and view the folders but didn't want to delete it that way yet before I get a response here. Would it be worth trying that to delete the custom_components folder for HACS?

**Comment by ludeeus** [comment]
Use the visual studio code add-on or SSH.

As for manually installing it, unless you know your way around docker and containers, no not really.
If you have a "deps" folder in your configuration, remove it.

**Comment by Gurgeh88** [comment]
> Use the visual studio code add-on or SSH.

What are you referring to here? Use it for what?
Have deleted "deps" folder (which appeared empty FYI). Will restart and report back.

**Comment by ludeeus** [comment]
Visual studio code add-on or SSH is better to manage your files.

**Comment by Gurgeh88** [comment]
Ah OK thank you.
No change after deleting the "deps" folder FYI.
I have the "SSH & Web Terminal" add-on installed. When I first installed Home Assistant, I followed a bunch of recommendations for Add-Ons and integrations etc. That was one of them. However, I haven't used it yet.

I was able to use the "WinSCP" program on my PC to access using my details from "SSH & Web Terminal" though. Is this the recommended way to use that add-on to manage my files in Home Assistant? Should I use this to delete my HACS folder? If so, should I disable HACS first (disabling action seems to work OK, just not delete)?

Sorry for the million and one questions and I really appreciate the support.

**Comment by ludeeus** [comment]
I don't know "WinSCP" so can't tell you :shrug: 
`rm -rf /config/custom_components/hacs`  should take care of it.
When the folder is completely removed, restart homeassistant 2 times with the CLI `ha core restart` (Not the UI!)
When you have had 2 successful starts without the hacs folder, run the installation script again.

**Comment by Gurgeh88** [comment]
OK that worked wonderfully to delete the folders thank you.
Now, I have restarted HA using that command twice.
The HACS error still shows up and the integration is still in my integrations page as not loaded though.
With that in mind, should I proceed with the installation script?

**Comment by ludeeus** [comment]
What error?

**Comment by Gurgeh88** [comment]
Oh, my apologies! This showed up and I didn't look closely enough:
```
Logger: homeassistant.setup
Source: setup.py:173
First occurred: 17:13:40 (1 occurrences)
Last logged: 17:13:40

Setup failed for hacs: Integration not found.
```
I'll try running the install script now :)

**Comment by ludeeus** [comment]
That's perfectly fine, and completely expect 👍

**Comment by Gurgeh88** [comment]
The installation script appeared to run fine and I restarted using the ha core restart command but the error has shown up again on the reboot:
```
Logger: homeassistant.setup
Source: setup.py:173
First occurred: 17:28:44 (1 occurrences)
Last logged: 17:28:44

Setup failed for hacs: Unable to import component: cannot import name 'ACCEPT_HEADERS' from 'aiogithubapi.common.const' (/usr/local/lib/python3.9/site-packages/aiogithubapi/common/const.py)
```
What do you recommend I do next? The HACS icon is still missing from the quick access panel on the left of HA and the integration page still shows HACS as "! Not loaded".
I haven't tried the delete or disable function yet.

**Comment by ludeeus** [comment]
`ha core rebuild`

**Comment by Gurgeh88** [comment]
Oh.Em.Gee!
I think we are cooking with gas now ludeeus :)
HACS has appeared in the side panel, it is no longer showing as not loaded on the integrations page and there is no sign of an error!
When I click on HACS, it now shows this:
![image](https://user-images.githubusercontent.com/86870554/131305292-4f2e4a25-757e-44ae-ade3-9cad12f57887.png)
I'm confused, why is it telling me to upgrade to an older version of HACS?

**Comment by ludeeus** [comment]
Click the "update information" in the menu on the card for it

**Comment by Gurgeh88** [comment]
When I click System Options, Update on the HACS integration card nothing changes.

**Comment by ludeeus** [comment]
right...
Inside hacs -> integrations, not config -> integrations

**Comment by Gurgeh88** [comment]
Okiedokie, it worked that time :)
HACS seems to be back up and running normally now! Hooray :)
Is there some way you recommend testing to make sure this is permanently fixed? Just do "ha core restart" again and see if it comes up ok?

**Comment by Gurgeh88** [comment]
Either way, thanks so much for your help. Your instructions were very clear and easy to follow for a noob :)
