### ISSUE TITLE
Updater Error: System tries to Downgrade HACS? 

### ISSUE THREAD

**Issue by Nicao** [hacs/integration#2203]
## System Health

version | core-2021.8.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.53
arch | x86_64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4825
Installed Version | 1.15.1
Stage | running
Available Repositories | 876
Installed Repositories | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.2
-- | --
update_channel | stable
supervisor_version | supervisor-2021.08.1
docker_version | 20.10.6
disk_total | 109.3 GB
disk_used | 16.6 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.8.0), Grocy (0.15.0), deCONZ (6.8.0), File editor (5.3.3), Samba share (9.5.1), Dnsmasq (1.4.4), Node-RED (10.0.0), Log Viewer (0.11.1), Home Assistant Google Drive Backup (0.104.3), Terminal & SSH (9.1.3), Let's Encrypt (4.11.0), Portainer (2.0.0), Visual Studio Code (3.6.2), Grafana (7.2.0), TasmoAdmin (0.15.0), Duck DNS (1.13.0), MariaDB (2.4.0), Nginx Proxy Manager (0.11.0), Vaultwarden (Bitwarden) (0.13.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 8
views | 3
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

![image](https://user-images.githubusercontent.com/6112811/131837483-86f44f72-6322-4ee8-a5ef-f152f6c59950.png)

Persistent after restart.

### Reproduction steps

1. Going into HACS, being offered to Downgrade instead of Upgrade when running the latest version

### Debug logs

```text
I am on the run, have to provide those logs at a later point if needed. Please comment if required.
```

**Comment by unlucio** [comment]
Same issue for me, it's trying to "upgrade" my 1.15.2 to 1.13.2:
<img width="803" alt="Screenshot 2021-09-07 at 14 49 53" src="https://user-images.githubusercontent.com/778799/132347803-87cdca60-cd78-4804-aec8-192f4b3c70d1.png">

Last time I checked 15 was > 13, if someone updated how math works I didn't get the memo 😅

**Comment by mpolivanov** [comment]
I had the same issue, which goes away after I've enabled debug to find out the reason. HACS updated the repository and then the message goes away.

**Comment by bmcclure** [comment]
I am running into the same issue with it trying to downgrade from 1.15.2 to 1.12.3. Have not solved it yet.
