### ISSUE TITLE
Removed integration (Youless) can not be deleted from HACS

### ISSUE THREAD

**Issue by pdwonline** [hacs/integration#2213]
### System Health details

Versie | core-2021.9.5
Type installatie | Home Assistant Container
Ontwikkeling | false
Supervisor | false
Docker | true
Gebruiker | root
Virtuele omgeving | false
Python-versie | 3.9.6
Besturingssysteem | Linux
Versie van het besturingssysteem | 5.4.0-80-generic
CPU-architectuur | x86_64
Tijdzone | Europe/Amsterdam

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

The Youless integration has been merged in core. Therefore, the repository of this integration has been removed and the URL for that repository  will return a 404 (https://github.com/reharmsen/hass-youless-component).  Since I wanted to use the core integration, the custom integration should be removed. Selecting 'Remove' in HACS doesn't give an error, but it does not remove the repository. I removed the component manually from the custom_components directory and was able to install the core integration. However, it is still listed in HACS and generates a warning in the log saying that the URL for the repository returns a 404.  

It seems that HACS is not able to remove this repository. Can I remove it from HACS manually?

### Reproduction steps

1. Have an installed integration (youless in my case)
2. Remove the repository for the integration so it would return 404 (https://github.com/reharmsen/hass-youless-component)
3. Try to uninstall the integration using the HACS UI
...

### Debug logs

```text
.
```

**Comment by ludeeus** [comment]
Remove it from custom repos
https://hacs.xyz/docs/faq/custom_repositories

**Comment by pdwonline** [comment]
> Remove it from custom repos
> https://hacs.xyz/docs/faq/custom_repositories

Thanks! that solved it for me
