### ISSUE TITLE
Query - Github doesn't show any OAuth applications after registering HACS?

### ISSUE THREAD

**Issue by andystewart999** [hacs/integration#2220]
### System Health details

n/a

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Not an issue, more of a query for my own sanity.  Having registered the most recent version of HACS via the GUI, and therefore I'm using OAuth, wouldn't I expect to see HACS appear in my GitHub Developer Apps page?

![image](https://user-images.githubusercontent.com/18434441/133954596-31114871-d4cd-4a76-a39d-956fdfa4e888.png)

Thanks for your continue efforts in making it so easy to include and manage 3rd party integrations into Home Assistant, it's appreciated!

### Reproduction steps

n/a

### Debug logs

```text
n/a
```

**Comment by ludeeus** [comment]
That's for applications you manage.
Applications you grant access to lives under <https://github.com/settings/applications>

**Comment by andystewart999** [comment]
Great!  Thanks for the confirmation and for getting back to me.
Andy
