### ISSUE TITLE
Improve the `hacs.json` check

### ISSUE THREAD

**Issue by MrBartusek** [hacs/integration#2223]
### Describe the issue

The current check for `hacs.json` is quite primitive and only check for the `name` key. So, I made a couple of json templates that can be used:

| File | Description |
| --- | ------------- |
| [hacs-schema.json](https://gist.github.com/MrBartusek/2d4ecd1c86f58326260d899afbda08be) | The general schema for use as `$schema` property. |
| [hacs-schema-integration.json](https://gist.github.com/MrBartusek/ff90c68e481b9ab9379f04db8e866741) | The schema for use in check when validating integration. |
| [hacs-schema-single-file.json](https://gist.github.com/MrBartusek/aa6552e395e0580a884994065d09b28c) | The schema for use in check when validating a single file. |

The best practice is to keep actual files in a repo such as https://github.com/hacs/schemas so they can be PR-able.

The main advantage of this solution is the check will fail when there are invalid keys, invalid countries or HA versions even.

Another thing is that documentation can prompt users to optionally add the `$schema` key to their files. If they do, their editor will detect mistakes while writing their files:

![image](https://user-images.githubusercontent.com/23432278/134779768-bb5f0613-b5bd-44e6-a2d8-34e980fc61af.png)

![image](https://user-images.githubusercontent.com/23432278/134779781-aa56c61f-28c3-4d84-82a8-2d9807bdb12c.png)

### Link to action run

n/a

### Link to action configuration

n/a

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
What is the issue?

If more validation is needed, that should be handled here <https://github.com/hacs/integration/pull/2175/files#diff-91949ac5dd3b92eb39f5212e2e9eb170bf1534e115a9d46fddec76483b796dddR32> and with `voluptuous` like all others.

**Comment by MrBartusek** [comment]
@ludeeus My point is that https://github.com/hacs/action/blob/main/checks/hacsjson just lacks the proper validation.

**Comment by ludeeus** [comment]
Nothing more is strictly needed, and it should not be "reinvented".
