### ISSUE TITLE
Errors in fresh installation

### ISSUE THREAD

**Issue by Hamsterman** [hacs/integration#2230]
### System Health details

Fresh system install.

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

I have just done a fresh installation and got these errors in the log.
I am not sure if that is or problem or not just yet but errors at initial installation does not look great :)

Log Details (ERROR)
 This error originated from a custom integration.
Logger: custom_components.hacs
Source: custom_components/hacs/operational/factory.py:58
Integration: HACS (documentation, issues)
First occurred: 3:38:41 PM (3 occurrences)
Last logged: 3:40:38 PM

mampfes/hacs_wiffi - Repository is archived.
PTST/O365-HomeAssistant - Repository is archived.
atomic7777/atomic_calendar - Repository is archived.

### Reproduction steps

Fresh install

### Debug logs

```text
Nope
```

**Comment by ludeeus** [comment]
Restart and they are gone
