### ISSUE TITLE
Request for removal of PTST/O365-HomeAssistant

### ISSUE THREAD

**Issue by Antoni-Czaplicki** [hacs/integration#2239]
### Repository

PTST/O365-HomeAssistant

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Reopo is archived and integration is not working

### Link to issue

Repo is archived

**Comment by ludeeus** [comment]
<https://github.com/hacs/default/pull/1103>
