### ISSUE TITLE
how to set HACS download file use  http proxy 

### ISSUE THREAD

**Issue by chestarss** [hacs/integration#2240]
### System Health details

how to set HACS download file use  http proxy 

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

how to set HACS download file use  http proxy 

### Reproduction steps

how to set HACS download file use  http proxy 

### Debug logs

```text
how to set HACS download file use  http proxy
```

**Comment by ludeeus** [comment]
HACS does not have proxy configuration options.
