### ISSUE TITLE
error loading https://<my_hasurl>/hacsfiles/iconset.js

### ISSUE THREAD

**Issue by pdwonline** [hacs/integration#2256]
## System Health

version | core-2021.10.7
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.4.0-84-generic
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4872
Installed Version | 1.15.2
Stage | running
Available Repositories | 888
Installed Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 11
views | 6
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Not a blocking issue, but in the browser console I see this message:

Error loading 'https://<myhacsurl>/hacsfiles/iconset.js'    (I substituted my url in this example for <myhacsurl>)

### Reproduction steps

1. Install HACS
2. Open developer tools - console in your broser
3. load hacs url

### Debug logs

```text
n.a.
```

**Comment by ludeeus** [comment]
Does that file exist?

**Comment by pdwonline** [comment]
As far as I could see no, this file does not exist.

**Comment by ludeeus** [comment]
Then someone has removed it, reinstall HACS, this fine is part of the integration
