### ISSUE TITLE
Wrong HACS icon sizes in Firefox 

### ISSUE THREAD

**Issue by Eyco1981** [hacs/integration#2259]
### Web browser

Firefox

### Web browser version

94.0.1 (64-Bit

## System Health

version | core-2021.11.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.75
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 3504
Installed Version | 1.16.0
Stage | running
Available Repositories | 962
Installed Repositories | 76

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 18. November 2021, 01:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 113.9 GB
disk_used | 14.7 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | SSH & Web Terminal (9.0.1), CEC Scanner (3.0), Check Home Assistant configuration (3.9.0), MariaDB (2.4.0), RPC Shutdown (2.2), Samba share (9.5.1), AirCast (3.1.1), motionEye (0.15.1), Visual Studio Code (3.6.2), Mosquitto broker (6.0.1), phpMyAdmin (0.5.0), deCONZ (6.10.0), Zigbee2mqtt (1.22.0-2), Z-Wave JS to MQTT (0.28.0), Z-Wave JS (0.1.45), AppDaemon 4 (0.7.0), Vaultwarden (Bitwarden) (0.13.0), Node-RED (10.0.1), Let's Encrypt (4.11.0), WireGuard (0.5.1), ESPHome (2021.10.3), Home Assistant Google Drive Backup (0.105.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 5
-- | --
resources | 30
views | 24
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

The HACS icon is scaling bigger in the sidebar and e.g. as icon in entity and element cards when using Firefox. In Chrome and the HA mobile app the icons look as expected. Wiping of browser cache and deleting HA related cookies did not change that behavior.

### Reproduction steps

1. Load HA web interface via IP address, homeassistant.local or the Nabu Casa URL
2. Login
3. (additional) Use sensor.hacs in entity or element cards
...

### Screenshots

View in Firefox:
![firefox](https://user-images.githubusercontent.com/88980079/140355248-d11f833d-1eca-4522-80b0-7d076689d128.png)

Same view in Chrome
![chrome](https://user-images.githubusercontent.com/88980079/140355922-fd5ba0af-86bf-48bf-b357-15ecee22b224.png)

### Javascript logs from your browser console

```text
Unbekannte Eigenschaft '-moz-osx-font-smoothing'.  Deklaration ignoriert. entry:1:60
Fehler beim Verarbeiten des Wertes für 'padding-left'.  Deklaration ignoriert. entry:120:25
Fehler beim Verarbeiten des Wertes für 'padding-left'.  Deklaration ignoriert. entry:218:25
Unbekannte Eigenschaft '-moz-osx-font-smoothing'.  Deklaration ignoriert. entry:1:362
Übereinstimmende Elemente mit Selektor: .material-icons
NodeList []
The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information. main-add588c4.js:1217:436039
Die Ressource unter "http://homeassistant:8123/static/fonts/roboto/Roboto-Regular.woff2" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. entry
Die Ressource unter "http://homeassistant:8123/static/fonts/roboto/Roboto-Medium.woff2" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. entry

​
```

**Comment by ludeeus** [comment]
I can't replecate with the same browser version.
Try with private window.

**Comment by Eyco1981** [comment]
Same icon sizes with Firefox in a private window.

**Comment by ludeeus** [comment]
Can you see `hacs:hacs` in the icon picker?

**Comment by Eyco1981** [comment]
Yes, but it is also much bigger than the other selectable icons (in Firefox).

**Comment by Eyco1981** [comment]
Additional info: 
Same problem when using Firefox 93.2.0 on Android phone.

**Comment by ludeeus** [comment]
I see other people have this with other icons as well.
I think this is from a custom card you have.
And is something that needs to be guarded in the Home Assistant frontend.

**Comment by dlupsa** [comment]
I have this problem too (Firefox)

![slika](https://user-images.githubusercontent.com/43806497/140601981-a8bdab86-cc9f-4e35-9600-43245e935136.png)

**Comment by ludeeus** [comment]
Closing here as you have opened the same in the home assistant frontend repo.
