### ISSUE TITLE
Can't intergrate snapcast to HACS 

### ISSUE THREAD

**Issue by RStaes** [hacs/integration#2261]
## HACS version
1.16.0

## System Health

version | core-2021.11.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.75
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4942
Installed Version | 1.16.0
Stage | running
Available Repositories | 889
Installed Repositories | 9

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 30.8 GB
disk_used | 6.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS (0.1.45), File editor (5.3.3), AirCast (3.1.1), Terminal & SSH (9.2.1), Duck DNS (1.14.0), Dnsmasq (1.4.4), FTP (4.2.1), Mosquitto broker (6.0.1), UniFi Controller (1.0.0), NGINX Home Assistant SSL proxy (3.0.2), Node-RED (10.0.1), Samba share (9.5.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 2
views | 7
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

When a try to add with 'custom repositories' I get the message "Repostitory structure for v0.25.0 is not compliant" when a click the add button.

### Reproduction steps

1. Go to HACS in Home Assistant
2. Go to 'Integrations'
3. Click on the 3 dots in the right upper corner of the screen and click on 'Custom repositories'
4. Add the URL 'https://github.com/badaix/snapcast'
5. Choose category 'Integration' and click on ADD
6. Now the error 'Repostitory structure for v0.25.0 is not compliant' pops up.

### Debug logs

```text
2021-11-06 13:54:54 DEBUG (MainThread) [custom_components.hacs] <Integration badaix/snapcast> Checking repository.
2021-11-06 13:54:55 DEBUG (MainThread) [custom_components.hacs] <Integration badaix/snapcast> Running checks against v0.25.0
```

**Comment by ludeeus** [comment]
That is not an integration, that is host software and the repository is not in a format that HACS knows, there is nothing for HACS to track/manage.
