### ISSUE TITLE
Request for removal of marksie1988/atomic-calendar-revive

### ISSUE THREAD

**Issue by axute** [hacs/integration#2265]
### Repository

marksie1988/atomic-calendar-revive

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

new URL 
`https://github.com/totaldebug/atomic-calendar-revive`

### Link to issue

https://github.com/totaldebug/atomic-calendar-revive

**Comment by ludeeus** [comment]
This is not a valif reason for removal

**Comment by axute** [comment]
But the Update function is broken ....

**Comment by ludeeus** [comment]
Then open a bug with debug logs.
