### ISSUE TITLE
Request for removal of schmittx/home-assistant-eero

### ISSUE THREAD

**Issue by Wolbyworld** [hacs/integration#2267]
### Repository

schmittx/home-assistant-eero

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

The repository seems to be abandoned. Users are reporting not being able to set up and the author has not responded nor updated in months. The Home Assistant community thread is also abandoned (https://community.home-assistant.io/t/new-custom-component-eero-integration/244583/17) 

### Link to issue

https://github.com/schmittx/home-assistant-eero/issues/12

**Comment by ludeeus** [comment]
This was never a default repo in HACS, nothing to remove here.
