### ISSUE TITLE
Cannot uninstall a now 404'ing repository

### ISSUE THREAD

**Issue by jasonmadigan** [hacs/integration#2269]
### System Health details

All OK.

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

A previouslly installed repo (<Integration USA-RedDragon/badnest> GitHub returned 404 for https://api.github.com/repos/USA-RedDragon/badnest) no longer exists. There's a warning about this in the logs. Removing the now non-existant repo fails (no error, the item just doesn't actually remove), and results in an error In the logs:

`Could not use repository with ID 210963640 ('NoneType' object has no attribute 'get_releases')`

### Reproduction steps

1. Uninstall a non-existent repository
2.
3.
...

### Debug logs

```text
`Could not use repository with ID 210963640 ('NoneType' object has no attribute 'get_releases')`
```

**Comment by ludeeus** [comment]
Remove from custom repositories
