### ISSUE TITLE
Unable to uninstall integrations

### ISSUE THREAD

**Issue by ranrinc** [hacs/integration#2271]
## System Health

version | core-2021.11.2
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.0-9-cloud-amd64
arch | x86_64
timezone | Asia/Jakarta

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4417
Installed Version | 1.16.0
Stage | running
Available Repositories | 918
Installed Repositories | 30

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 17, 2021, 7:00 AM
relayer_connected | true
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
remote_server | ap-southeast-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.10
disk_total | 49.8 GB
disk_used | 6.9 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2021.10.3), Visual Studio Code (3.6.2), Node-RED (10.0.1), Home Assistant Google Drive Backup (0.105.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 19
-- | --
resources | 13
views | 34
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Want to remove one integration called remote home-assistant and this is not possible.

![Screen Shot 2021-11-11 at 11 15 27 AM](https://user-images.githubusercontent.com/15801696/141237112-f2b910ef-5707-4fa0-afe1-ac5f4e6bd745.png)

redirections to integrations show nothing since the setting already being deleted.

### Reproduction steps

1. go to hacs
2. go to integrations
3. choose the integration that want to be uninstall
4. choose options to uninstall
5. redirect to integrations pages which the integrations already non-existance
6. restart, removing .storage/hacs/xxxxxxxx.hacs does not resolve the problem
7. 
...

### Debug logs

```text
N/A
```

**Comment by ludeeus** [comment]
If you get that, then you have a config entry with the same domain.
It can be configured, ignored or disabled, but it is there.

Check your filters.
