### ISSUE TITLE
Notification Update Required ??

### ISSUE THREAD

**Issue by 3ative** [hacs/integration#2289]
### Web browser

Chrome

### Web browser version

Latest (95.0.4638.69)

### System Health details

N/A

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Just a li'one....
Text refers to an outdated process... New Text Link on same line now.
![image](https://user-images.githubusercontent.com/51385971/141697445-b9646408-4752-4f9c-b9a4-78ac6505ebe8.png)

### Reproduction steps

1. Open HACS
2. Look at the Screen
3. Notice Text instructions.
...

### Screenshots

![image](https://user-images.githubusercontent.com/51385971/141697498-2c796388-0ffd-4b33-a92b-16eba92e7729.png)

### Javascript logs from your browser console

```text
N/A
```

**Comment by ludeeus** [comment]
The default (english) text is correct, so this is from a translation.
British I'm guessing?
Anyway, all translations are handled in lokalise👍

**Comment by 3ative** [comment]
@ludeeus 
Not a translation issue. Text states, "...use the 3 Dots" menu however, that doesn't contain a 'Clear Option' anymore. Instead to clear new items, there's a Text button (on same line as the notification. 
:)

**Comment by ludeeus** [comment]
@3ative You are wrong.
This is what's the default: https://github.com/hacs/frontend/blob/main/src/localize/languages/en.json#L168
This is the British translation <https://app.lokalise.com/project/854515055f679055040b37.42677693/?view=single&reference_lang_id=640&single_lang_id=610&search=new_repositories_note>
![image](https://user-images.githubusercontent.com/15093472/141699250-b73c6cfc-3cff-4d29-a856-9596c59db5a0.png)
So yeah.. Translation issue.

**Comment by 3ative** [comment]
@ludeeus There is **NO Dismiss** in the 3 Dots menu! 
![image](https://user-images.githubusercontent.com/51385971/141699351-87ade045-eb31-4c94-8448-0c223f8da6ad.png)

Text IS wrong

**Comment by ludeeus** [comment]
LIKE I SAID THE TRANSLATION IS WRONG.
