### ISSUE TITLE
Issue when downloading a frontend repository

### ISSUE THREAD

**Issue by kaizersoje** [hacs/integration#2294]
### Web browser

Chrome

### Web browser version

Version 95.0.4638.69 

## System Health

version | core-2021.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v7
arch | armv7l
timezone | Australia/Sydney

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4286
Installed Version | 1.17.2
Stage | running
Available Repositories | 993
Installed Repositories | 111

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 219.4 GB
disk_used | 20.0 GB
healthy | true
supported | failed to load: Unsupported
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Dropbox Sync (1.3.0), SQLite Web (2.3.2), AppDaemon 4 (0.4.4), File editor (5.3.3), Check Home Assistant configuration (3.9.0), MQTT Server & Web client (1.2.0), Log Viewer (0.12.1), AirCast (3.2.0), Glances (0.14.0), Home Assistant Google Drive Backup (0.105.2), Grafana (7.3.1), Terminal & SSH (9.2.1), Duck DNS (1.14.0), Let's Encrypt (4.11.0), InfluxDB (4.3.0), AdGuard Home (4.2.0), SSH & Web Terminal (9.1.0), Signal Messenger (0.42.0), Portainer (2.0.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 7
-- | --
resources | 62
views | 46
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

I have noticed that when I am trying to install a frontend repository, the icon just keeps going round and round after clicking the download or remove buttons. This does not occur when I am installing an integration repository.

### Reproduction steps

1. Open HACS and click on Frontend.
2. Select any repository to download (does not matter new or existing)
3. Click on download. The icon keeps going round and round.
...

### Screenshots

![image](https://user-images.githubusercontent.com/54566217/141975770-47ceda58-dd60-4eec-a442-e6e81274c2e6.png)

### Javascript logs from your browser console

```text
c.e523f276.js:53 Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
value @ c.e523f276.js:53
await in value (async)
handleEvent @ main-8113c4f2.js:1
```

**Comment by b-reich** [comment]
Same Issue for me
![grafik](https://user-images.githubusercontent.com/1573025/142060393-1637e54a-dbaf-4fb0-8aa2-e2f391aa83d4.png)

![grafik](https://user-images.githubusercontent.com/1573025/142060435-c4bc0231-3e9b-4ca3-a64f-d9d9f6507911.png)

**Comment by ludeeus** [comment]
@b-reich your issue is unrelated, you have communication issues to GitHub.

**Comment by Pirol62** [comment]
I have exactly the same issue like @kaizersoje and @b-reich . 
HA 2021.10.6 and latest HACS version. 
When I can call the description of not updated components, do I have issues with GITHUb then?

**Comment by ludeeus** [comment]
Impossible to say without logs.
Until @kaizersoje adds their logs, do not use this issue. Create a separate one.

**Comment by kaizersoje** [comment]
@ludeeus I have added the log after hitting the download button.

**Comment by ludeeus** [comment]
Your lovelace configuration is bad.
You also have an error in your Home Assistant log file.
Your lovelace _thinks_ you are running in storage. But you are using YAML.
![image](https://user-images.githubusercontent.com/15093472/142200228-c6f5d359-e550-4197-86c5-f2172d89a142.png)

My guess is that you are doing both?
You have some in the UI and some in YAML, and the lovelace config is confused.
Change it so you exclusively only use YAML or UI and it will start working again after a restart.

**Comment by kaizersoje** [comment]
Well, my main dashboard is YAML. I have a DEV dashboard, where the mode is UI.

**Comment by ludeeus** [comment]
That is most likely why it is confused.
As long as you have dashboards in YAML, and it says "mode: storage" in the system health card you will have this problem.

**Comment by kaizersoje** [comment]
I would have assumed it would take the mode from the main lovelace panel, which in this case is `yaml`. The [article](https://www.home-assistant.io/lovelace/dashboards/) here does not mention that you can have only one `mode` for all the dashboards.

**Comment by ludeeus** [comment]
It's a bug in Home Assistant, it has been fixed and will be released in 2021.12

**Comment by kaizersoje** [comment]
That's good to know. So if you dont mind me asking, does that mean I can create a UI dashboard after 2021.12 and HACS will not encounter any JS errors?

**Comment by ludeeus** [comment]
HACS is not confused, HACS uses whatever mode lovelace says it has, and yes that is the part that was fixed.

**Comment by kaizersoje** [comment]
Thanks @ludeeus
