### ISSUE TITLE
Request for removal of kayjei/ica_shopping_list

### ISSUE THREAD

**Issue by denmol** [hacs/integration#2307]
### Repository

kayjei/ica_shopping_list

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

No longer supported

### Link to issue

https://github.com/kayjei/ica_shopping_list/issues/3

**Comment by ludeeus** [comment]
This is not a default HACS repo and can not be removed <https://hacs.xyz/default_repositories>
Remove it as a custom repo <https://hacs.xyz/docs/faq/custom_repositories>
