### ISSUE TITLE
Running dev in 2021.12 produces warning about HACSSensor class

### ISSUE THREAD

**Issue by Petro31** [hacs/integration#2309]
## System Health

version | core-2021.12.0.dev20211124
-- | --
installation_type | Home Assistant Supervised
dev | true
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 4.19.0-6-amd64
arch | x86_64
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4450
Installed Version | 1.17.2
Stage | running
Available Repositories | 972
Installed Repositories | 43

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | dev
supervisor_version | supervisor-2021.11.dev1703
docker_version | 19.03.5
disk_total | 220.0 GB
disk_used | 21.8 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Terminal & SSH (9.2.1), NGINX Home Assistant SSL proxy (3.0.2), Portainer (1.5.2), ESPHome (2021.11.1), Mosquitto broker (6.0.1), Duck DNS (1.14.0), Z-Wave JS to MQTT (0.30.0), Network UPS Tools (0.9.0), Samba Backup (5.0.0), Frigate NVR Beta (0.10.0) (3.0), AdGuard Home (4.2.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 22
views | 61
mode | yaml

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Home assistant dev complains about using device_state_attributes and suggests reporting it to the owner of the custom integration.

```
 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.hacs (<class 'custom_components.hacs.sensor.HACSSensor'>) implements device_state_attributes. Please report it to the custom component author.
```

### Reproduction steps

1.  Upgrade to dev
2.  Use hacs
3.  ????
4.  Profit

### Debug logs

```text
2021-11-25 06:05:18 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.hacs (<class 'custom_components.hacs.sensor.HACSSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-11-25 06:05:18 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.hacs (<class 'custom_components.hacs.sensor.HACSSensor'>) implements device_state_attributes. Please report it to the custom component author.
```
```

**Comment by ludeeus** [comment]
Fixed in https://github.com/hacs/integration/pull/2305
