### ISSUE TITLE
Update available wrongly reported as available if version ends with "-beta"

### ISSUE THREAD

**Issue by gadgetchnnel** [hacs/integration#2310]
## System Health

version | core-2021.11.5
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.52-v7l+
arch | armv7l
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 3781
Installed Version | 1.17.2
Stage | waiting
Available Repositories | 932
Installed Repositories | 47

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 20 December 2021, 00:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-west-2-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 15
-- | --
resources | 53
views | 36
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

For some repositories,which have beta releases with version numbers ending with "-beta", for example the [ble_monitor](https://github.com/custom-components/ble_monitor), I am notified that there is an update to the same version I already have installed:

![image](https://user-images.githubusercontent.com/2099542/143473488-5d6f30ce-dcfd-4880-a39f-6a41f58b5177.png)

It looks like this may because `AwesomeVersion("6.1.0-beta") > AwesomeVersion("6.1.0-beta")` actually returns True instead of False.

### Reproduction steps

1. Install ble_monitor integration via HACS
2. Enable beta releases
3. Update to the latest beta release
...

### Debug logs

```text
2021-11-25 16:05:00 DEBUG (MainThread) [custom_components.hacs] Running update for custom-components/ble_monitor
2021-11-25 16:05:00 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/ble_monitor> Getting repository information
2021-11-25 16:05:01 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/ble_monitor> Running checks against 6.1.0-beta
2021-11-25 16:05:03 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-11-25 16:05:03 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-11-25 16:05:03 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.repositories'. Content did not change
```

**Comment by ludeeus** [comment]
Just ending it with `-beta` is not a valid version string, it has to have a number after it like `-beta2`.
However, this is fixed in newer versions of `AwesomeVersion`

```
>>> AwesomeVersion("6.1.0-beta") > AwesomeVersion("6.1.0-beta")
False
```
