### ISSUE TITLE
Top Header Inactive Tabs color broken in Default Theme

### ISSUE THREAD

**Issue by arenasa70** [hacs/integration#2316]
### Web browser

Chrome

### Web browser version

Version 96.0.4664.45 (Official Build) (64-bit)

## System Health

version | core-2021.11.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.75
arch | x86_64
timezone | America/Curacao

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4885
Installed Version | 1.18.0
Stage | running
Available Repositories | 984
Installed Repositories | 19

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 62.3 GB
disk_used | 9.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (3.7.0), Mosquitto broker (6.0.1), Node-RED (10.1.1), MariaDB (2.4.0), NGINX Home Assistant SSL proxy (3.0.2), SSH & Web Terminal (9.1.1), Samba share (9.5.1), DHCP server (1.2), Dnsmasq (1.4.4)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 13
views | 7
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

The non selected tabs can't be seen properly in the Light Default Theme.
The problem is the color for the inactive tabs is set to be app-header-text-color.  
Home Assistant Supervisor uses sidebar-text-color for those tabs, and it's readable in both Light and Dark versions of the theme.

### Reproduction steps

1.  Set Lovelace to the Light version of the Default Theme
2. Go to HACS 
2. Click on Integrations 
3. You will see [Integrations] selected.  But the other 2 tabs [Front End] and [Automation] are unreadable because the color is white.

### Screenshots

![image](https://user-images.githubusercontent.com/46388511/143954538-68248e08-2925-4f73-b120-e5fe4d2a1bcd.png)

It should look like this:

![image](https://user-images.githubusercontent.com/46388511/143954730-c47bfc3a-d900-4e4f-a890-802226a27309.png)

### Javascript logs from your browser console

```text
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
```

**Comment by pspeirs** [comment]
I'm experiencing the same behaviour after upgrading from 1.17.2 to 1.18.0
