### ISSUE TITLE
typo in error message when adding non-compliant repository

### ISSUE THREAD

**Issue by SteffanH** [hacs/integration#2318]
### Web browser

Chrome

### Web browser version

96.0.4664.45 (Official Build) (64-bit)

## System Health

version | core-2021.11.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4953
Installed Version | 1.18.0
Stage | running
Available Repositories | 910
Installed Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 28.6 GB
disk_used | 5.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS (0.1.49), Terminal & SSH (9.2.1), Studio Code Server (3.7.0), Let's Encrypt (4.12.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 0
views | 3
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

When adding a non-compliant repository, the error message is
Repos**t**itory structure for <x> is not compliant.

There is a superfluous T after Repos

### Reproduction steps

1. Find a non-compliant repository
2. Try to add it as a custom repository
3. see error message about non-compliance
...

### Screenshots

![image](https://user-images.githubusercontent.com/866619/144005675-32596ec0-cfcc-4858-8327-d167b91d43d4.png)

### Javascript logs from your browser console

```text
N/A
```

**Comment by ludeeus** [comment]
There are no superfluous T in your image.

**Comment by SteffanH** [comment]
Hi @ludeeus , the T is in the error message:
![image](https://user-images.githubusercontent.com/866619/144014501-6d3ec326-1d73-4295-a71f-cbd6256741c0.png)

**Comment by SteffanH** [comment]
Thanks !
