### ISSUE TITLE
sections.pending_repository_upgrade doesn't translate for British English

### ISSUE THREAD

**Issue by drthanwho** [hacs/integration#2325]
### Web browser

Google Chrome

### Web browser version

Version 96.0.4664.45

## System Health

version | core-2021.12.0b0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Athens

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4526
Installed Version | 1.18.0
Stage | running
Available Repositories | 931
Installed Repositories | 70

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | dev
supervisor_version | supervisor-2021.12.dev0202
docker_version | 20.10.8
disk_total | 109.3 GB
disk_used | 46.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), AdGuard Home (4.2.0), Glances (0.14.0), Let's Encrypt (4.12.0), Mosquitto broker (6.0.1), Node-RED (10.0.0), Spotify Connect (0.10.0), Terminal & SSH (9.2.1), WireGuard (0.6.0), deCONZ (6.10.0), Studio Code Server (3.7.0), Grafana (7.3.1), Home Assistant Google Drive Backup (0.105.2), MariaDB (2.4.0), Assistant Relay (0.7.4), InfluxDB (4.3.0), VSCode Remote (6541b8e), Network UPS Tools (0.9.0), SSH & Web Terminal (9.1.1), File editor (5.3.3), chrony (2.2.1), Nginx Proxy Manager (0.11.0), TasmoAdmin (0.16.0), Scrutiny (0.3.13-2), phpMyAdmin (0.6.0), Frigate NVR Proxy (1.3), Zigbee2mqtt (1.22.0-2), Double Take Proxy (1.0.0), ESPHome (2021.11.2), VLC (0.1.3), Duck DNS (1.14.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 10
-- | --
resources | 51
views | 59
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

The box for available updates shows `sections.pending_repository_upgrade` rather than translating to the description of the update. For British English at least (changing to forbidden English works)

### Reproduction steps

1. Open HACS
2. See updates
3.
...

### Screenshots

![image](https://user-images.githubusercontent.com/22405505/144674909-6bd4949a-ef76-4998-9bfc-974bd92c7db5.png)

### Javascript logs from your browser console

```text
[HACS.localize] Translation problem with 'sections.pending_repository_upgrade' for 'en_GB'
error @ main-ff32767d.js:1166
```

**Comment by ludeeus** [comment]
This is not a frontend issue..
This is an issue with the translation which is handled on localize 

https://hacs.xyz/docs/developer/translation
