### ISSUE TITLE
HACS icon does not show in HA sidebar

### ISSUE THREAD

**Issue by davidrustingha** [hacs/integration#2336]
### Web browser

Chrome

### Web browser version

96.0.4664.93 (Official Build) (64-bit)

## System Health

version | core-2021.11.5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.0-9-amd64
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4268
Installed Version | 1.18.0
Stage | running
Available Repositories | 922
Installed Repositories | 58

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.1
docker_version | 20.10.11
disk_total | 226.7 GB
disk_used | 25.1 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), deCONZ (6.10.0), File editor (5.3.3), Studio Code Server (3.7.0), Terminal & SSH (9.2.1), VLC (0.1.3), FTP (4.3.0), Mosquitto broker (6.0.1), Duck DNS (1.14.0), ESPHome (2021.11.4), Spotify Connect (0.10.0), Double Take (1.7.0), Frigate NVR (2.3), Home Assistant Google Drive Backup (0.105.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 8
-- | --
resources | 46
views | 28
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

For some time now, the HACS icon isnt showing in the sidebar. It's not a big deal, but for OCD people like me it can be a bit annoying and since its probably an easy fix I thought I'd just create an issue.

### Reproduction steps

1. Install HACS
2. Check sidebar
3.
...

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/62120423/145682543-8856783a-637e-46df-a512-0e6fb67ff89f.jpg)

### Javascript logs from your browser console

```text
Not sure where to get those.
```

**Comment by ludeeus** [comment]
Refresh your browser.

**Comment by davidrustingha** [comment]
That was quick. I've done that a lot, this issue started a number of versions ago (I cant remember which one)

**Comment by davidrustingha** [comment]
My mouth actually fell open. Did you change something or was it just my inability to use Chrome?..

**Comment by ludeeus** [comment]
This is on your local system, I can't control that.

**Comment by davidrustingha** [comment]
Well, I'ts fixed. Thanks for the help!
