### ISSUE TITLE
Request for removal of Poeschl/Bring-shoping-list-component

### ISSUE THREAD

**Issue by MetziFetzi** [hacs/integration#2343]
### Repository

Poeschl/Bring-shoping-list-component

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

App isn't working and developer is not fixed it till January 2021

Check Link below and Timestamp on Projectiles 
https://github.com/Poeschl/Bring-shoping-list-component/issues/2

### Link to issue

https://github.com/Poeschl/Bring-shoping-list-component/issues/2

**Comment by ludeeus** [comment]
Not a default repository <https://hacs.xyz/default_repositories> nothing to remove.
