### ISSUE TITLE
Timeout of 20 reached while waiting for https://api.github.com/repos/hacs/default/contents/removed

### ISSUE THREAD

**Issue by vdiogo** [hacs/integration#2346]
### System Health details

System Health

version: core-2021.12.0
installation_type: Home Assistant Supervised
dev: false
hassio: true
docker: true
user: root
virtualenv: false
python_version: 3.9.7
os_name: Linux
os_version: 4.19.118-v7l+
arch: armv7l
timezone: Europe/Lisbon

GitHub API: ok
Github API Calls Remaining: 5000
Installed Version: 1.18.0
Stage: running
Available Repositories: 914
Installed Repositories: 15

can_reach_server: ok
remaining_requests: 26

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

host_os: Raspbian GNU/Linux 10 (buster)
update_channel: stable
supervisor_version: supervisor-2021.12.1
docker_version: 19.03.12
disk_total: 109.8 GB
disk_used: 62.6 GB
healthy: true
supported: failed to load: Unsupported
supervisor_api: ok
version_api: ok
installed_addons: Samba share (9.5.1), Check Home Assistant configuration (3.9.0), File editor (5.3.3), Glances (0.12.2), Mosquitto broker (6.0.1), Node-RED (10.0.0), SSH & Web Terminal (9.1.1), TasmoAdmin (0.16.0), WireGuard (0.5.0), deCONZ (6.10.0), InfluxDB (4.3.0), Grafana (7.3.2), ESPHome (2021.12.0)

api_endpoint_reachable: ok

dashboards: 1
resources: 3
views: 16
mode: storage

websocket_connection_state: connected
api_endpoint_reachable: ok

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

I am getting the following entry on my log:

Timeout of 20 reached while waiting for https://api.github.com/repos/hacs/default/contents/removed

### Reproduction steps

1. access home assistant logs

### Debug logs

```text
Logger: custom_components.hacs
Source: custom_components/hacs/helpers/functions/get_list_from_default.py:35
Integration: HACS (documentation, issues)
First occurred: 14 de dezembro de 2021 20:25:32 (1 occurrences)
Last logged: 14 de dezembro de 2021 20:25:32

Timeout of 20 reached while waiting for https://api.github.com/repos/hacs/default/contents/removed
```

**Comment by ludeeus** [comment]
Your setup is unsupported.

20s is well above what is needed for that call, which indicates that you have networking issues.
There is nothing that can or should be done in the integration to mitigate that.
