### ISSUE TITLE
Links not working in iFrame

### ISSUE THREAD

**Issue by eglia** [hacs/integration#2351]
### Web browser

Firefox

### Web browser version

95.0.2

## System Health

version | core-2021.12.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.83
arch | x86_64
timezone | Europe/Zurich

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4935
Installed Version | 1.18.0
Stage | running
Available Repositories | 985
Installed Repositories | 10

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 20.0 GB
disk_used | 12.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (10.2.1), Syncthing (1.13.0), Studio Code Server (3.7.0), deCONZ (6.11.1), SSH & Web Terminal (10.0.0), Z-Wave JS (0.1.50), Mosquitto broker (6.0.1), MQTT Explorer (latest)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 6
views | 4
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

I'm runing HA within an iFrame of another application. The parent app is on another subdomain. Some functionality of HACS is not working in this setup, e.g. reloading the UI or opening the repository of an installed integration.
When accessing HA directly (without iFrame), everything works fine.

### Reproduction steps

1. Open HA within an iFrame from another subdomain
2. Open HACS
3. Click "Integrations"
4. Click the 3-dot menu of any integration
5. Click "Repository"
6. See error in browser console

### Screenshots

n.a.

### Javascript logs from your browser console

```text
Uncaught DOMException: Permission denied to access property "open" on cross-origin object c.ad388125.js:513
    action https://home-assistant.example.com/hacsfiles/frontend/c.ad388125.js:513
    handleEvent https://home-assistant.example.com/hacsfiles/frontend/main-ff32767d.js:1
```

**Comment by ludeeus** [comment]
This is not a bug.
These are security features in your browser.

**Comment by eglia** [comment]
I'm no web developer, but it seems to me that HACS is trying to call window.open on the top level, which the browser rightfully blocks because it is a security issue when using cross-origin iFrames. What HACS should do is call window.open on the HA window object or the HACS window object.

![image](https://user-images.githubusercontent.com/17555261/146910322-461d8391-c6b3-4278-83fc-eaac5daabc33.png)

**Comment by ludeeus** [comment]
No it should not, that would replace the content, these are meant to be opened in a separate tab.

**Comment by eglia** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/open
seems to me that you can specify where to load the content. But again, my knowledge in these matters is very limited so I apologize if I get this all wrong.

By the way, HA itself had [similar problems](https://github.com/home-assistant/frontend/issues/9114) in the past, which they were able to fix.

**Comment by ludeeus** [comment]
That is not the same, that is for navigation inside HA, this is for new tabs to external.
