### ISSUE TITLE
When installing an integration the system don´t responce

### ISSUE THREAD

**Issue by Bach-Danielsson** [hacs/integration#2352]
### Describe the issue

When installing a new intergartion the system comes to "wating mode" the blue cirkel is roling around. It seems that the system are frozen at this point .

![HACS](https://user-images.githubusercontent.com/39077163/146934332-9752bc29-7fba-4344-85ed-e64a8ed6dd90.jpg)
.

### Link to action run

sorry , i don´t know how to add this 

### Link to action configuration

sorry , i don´t know how to add this 

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
Wait 1h

**Comment by Bach-Danielsson** [comment]
Hi

I have tried this several times for the last 24 h , still the same problem.

I have noticed the flag that the system are slow, I will try later  

Regards Tomas
