### ISSUE TITLE
Tesla Repository Broken/Unremovable/Un-addable

### ISSUE THREAD

**Issue by ideal2545** [hacs/integration#2383]
## System Health

version | core-2021.12.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.83
arch | x86_64
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4825
Installed Version | 1.18.0
Stage | running
Available Repositories | 935
Installed Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 23, 2022, 4:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-west-2-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 228.5 GB
disk_used | 128.7 GB
healthy | true
supported | failed to load: Unsupported
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), AppDaemon 3 (5.0.1), Terminal & SSH (9.2.2), AirCast (3.2.0), Check Home Assistant configuration (3.9.0), MariaDB (2.4.0), Mosquitto broker (6.0.1), Z-Wave JS to MQTT (0.32.1), rtl_433 MQTT Auto Discovery (0.2.1), Frigate NVR (2.3), Node-RED (10.2.2), Studio Code Server (3.7.0), ESPHome (2021.12.1), Portainer Addon v1.5.2 (1.5.2.2), Samba Backup (5.0.0), rtl_433 (0.1.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 14
views | 12
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

To start: I have the Tesla integration already installed from before. 

When going into HACS the tesla repository keeps randomly showing up whenever there are other new repositories or after a restart. It is dismiss-able (previously it was not dismiss-able but an update resolved this I believe) and if I try to download it, the modal pops up but the download button is gray. However, even though I have the integration installed it does not show up as an installed integration so its unremovable and when I search "tesla" and attempt to add it I can a spinning circle of death right when I click on it in the pick list. 

### Reproduction steps

1. Have tesla integration already installed
2. Visit HACS, see Tesla Integration as new repository
3. Attempt to re-install it by searching for it, but when clicking on the "Tesla" repository the modal comes up and then you get spinning wheel of death. 
...

### Debug logs

```text
sorry wasnt quite sure if there was a specific way to generate only HACS specific logs after adding custom log config but I searched "tesla" and found this:

2021-12-25 17:44:57 ERROR (MainThread) [custom_components.hacs] Did not find alandtse/tesla (362700564)
```

**Comment by ludeeus** [comment]
Fixed by <https://github.com/hacs/integration/pull/2326>

**Comment by ideal2545** [comment]
Thanks, so the issue is resolved but the HACS update hasn't rolled out yet?

**Comment by ludeeus** [comment]
correct
