### ISSUE TITLE
DEBUG logging with unexpected information about: No filter named 'timestamp_custom'

### ISSUE THREAD

**Issue by kongo09** [hacs/integration#2435]
## System Health

version | core-2021.12.8
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.63-v8+
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4973
Installed Version | 1.19.1
Stage | running
Available Repositories | 937
Downloaded Repositories | 43

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 10, 2022, 01:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-west-2-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | pending

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.12
disk_total | 117.0 GB
disk_used | 21.9 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.105.2), Studio Code Server (3.7.0), SSH & Web Terminal (10.0.1), Samba share (9.5.1), MariaDB (2.4.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 5
-- | --
resources | 29
views | 15
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Looking at the debug logging of HACS in the latest version, I noticed that it says:

```
2022-01-08 18:09:29 DEBUG (MainThread) [custom_components.hacs] <Integration kongo09/hass-hhs-vertretungsplan> Running checks against v0.1.3
2022-01-08 18:09:30 DEBUG (MainThread) [custom_components.hacs] No filter named 'timestamp_custom'.

```
It is not strictly a bug, but it suprised me so I thought I point it out. The only place where `timestamp_custom` is used in the integration is example Lovelace configuration yaml from the `README.md` file. Not sure why HACS would take not of that, espeically since `timestamp_custom` is a standard filter of HA: https://www.home-assistant.io/docs/configuration/templating/

Please simply close if this is intended or totally irrelevant.

### Reproduction steps

1. Enable HACS dubug logging
2. Ad custom repository for Integration kongo09/hass-hhs-vertretungsplan
3. Install "HHS Vertretungsplan" integration
4.  Observe log

### Debug logs

```text
2022-01-08 18:09:29 DEBUG (MainThread) [custom_components.hacs] <Integration kongo09/hass-hhs-vertretungsplan> Running checks against v0.1.3
2022-01-08 18:09:30 DEBUG (MainThread) [custom_components.hacs] No filter named 'timestamp_custom'.
```

**Comment by ludeeus** [comment]
Ignore this.
It’s logged with debug for development purposes
