### ISSUE TITLE
Can not download and update anything in HACS in China because 'github.com' is blocked here

### ISSUE THREAD

**Issue by muxiachuixue** [hacs/integration#2436]
### System Health details

arch: armv7
channel: stable
docker: 20.10.8
features:
- reboot
- shutdown
- services
- network
- hostname
- timedate
hassos: null
homeassistant: 2021.12.8
hostname: raspberrypi
logging: info
machine: raspberrypi4
operating_system: Raspbian GNU/Linux 10 (buster)
state: running
supervisor: 2021.12.2
supported: false
supported_arch:
- armv7
- armhf
timezone: Asia/Shanghai

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

The question:
Since `github.com` and `raw.githubusercontent.com` are blocked in China, it is not possible to download and update anything from HACS. There are many homeassistant users in China and we really nead HACS a lot. Unfortunately, it is really hard to set up a VPN for a new hand. In the older versions of HACS, I replaced the download url in the file `/config/custom_components/hacs/helpers/functions/download.py` from `github.com` to `hub.fastgit.org` and from `raw.githubusercontent.com` to `raw.fastgit.org` which are mirror websites of Github. Then HACS works perfectly. However, after updating to the latest version of HACS, the `download.py` file disappeared. So I can not download and update anything in HACS again.

My expectation:
To make it possible for Chinese users to download and update integrations in HACS, could you please add some mirror URLs of `github.com` and `raw.githubusercontent.com` in the codes or at least provide an option to let the users in China self-define mirror servers of Github.

### Reproduction steps

1. The IP is in China
2. With no proxy and VPN to connect to Github
3. Download or update integrations or fronted cards in HACS

### Debug logs

```text
Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:851
Integration: HACS (documentation, issues)
First occurred: 15:22:44 (10 occurrences)
Last logged: 15:40:57

[config_flow.py] was not downloaded.
[binary_sensor.py] was not downloaded.
[common.py] was not downloaded.
[cover.py] was not downloaded.
[strings.json] was not downloaded.
```

**Comment by ludeeus** [comment]
I'm sorry that this does not work in your country, but adding what you are asking is not something I will be comfortable doing.
These mirrors are not run by GitHub, so there is no telling what the mirrors collect and use about the traffic going through them.

You should use a proxy for network traffic on your host (or entire network) if you want to circumvent it (that is not something that should be implemented pr. integration)

Or you can do as you have so far by replacing the code (which I do not support), the content of the download.py file was moved to repositories/base.py

**Comment by muxiachuixue** [comment]
> I'm sorry that this does not work in your country, but adding what you are asking is not something I will be comfortable doing. These mirrors are not run by GitHub, so there is no telling what the mirrors collect and use about the traffic going through them.
> 
> You should use a proxy for network traffic on your host (or entire network) if you want to circumvent it (that is not something that should be implemented pr. integration)
> 
> Or you can do as you have so far by replacing the code (which I do not support), the content of the download.py file was moved to repositories/base.py

Thank a lot. I understand your concern. I have figured this issue out just now. Thanks again for your great work!
