### ISSUE TITLE
Package asyncio is not compatible with Python 3.8 standard library

### ISSUE THREAD

**Issue by petretiandrea** [hacs/integration#2450]
### Describe the issue

I'm trying to validate my custom integration at https://github.com/petretiandrea/home-assistant-tapo-p100/pull/118 which depends on another library (developed by me) `plugp100`. 

The HACS validation action report this error: `Package asyncio is not compatible with Python 3.8 standard library`. How can I fix it?

### Link to action run

https://github.com/petretiandrea/home-assistant-tapo-p100/pull/118

### Link to action configuration

https://github.com/petretiandrea/home-assistant-tapo-p100/blob/main/.github/workflows/validation.yml

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
Remove this <https://github.com/petretiandrea/plugp100/blob/main/requirements.txt#L9>

**Comment by petretiandrea** [comment]
Yes, but in this way I deny people to use plugp100 independently of Home Assistant. @ludeeus

**Comment by ludeeus** [comment]
No you do not.
It's a standard python lib, included in python itself
