### ISSUE TITLE
pyShelly.ws_client.WebSocket

### ISSUE THREAD

**Issue by dolenec** [hacs/integration#2454]
### System Health details

Logger: websocket
Source: /usr/local/lib/python3.9/site-packages/websocket/_logging.py:65
First occurred: 09:19:24 (635 occurrences)
Last logged: 19:55:47

error from callback <bound method WebSocket.on_message of <pyShelly.ws_client.WebSocket object at 0x7f8eea0fd0>>: 'result'

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

It seems that everything working fine, only this error appears..

### Reproduction steps

![image](https://user-images.githubusercontent.com/16633222/150001390-34a657e3-a043-497a-b994-88daad89c343.png)

### Debug logs

```text
/
```

**Comment by dolenec** [comment]
This was also reported on HA, but they figerout that this is HACS integration error...

**Comment by ludeeus** [comment]
It's not.

**Comment by dolenec** [comment]
Yes.. this is Shelly4HASS error.. my mistake.. sorry for bother..
