### ISSUE TITLE
Colored icon for sensor.hacs when HACS has updates

### ISSUE THREAD

**Issue by Jottlas** [hacs/integration#2455]
### Web browser

Chrome

### Web browser version

Version 97.0.4692.71 (Official Build) (64-bit)

## System Health

version | core-2021.12.9
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.88
arch | x86_64
timezone | Europe/Stockholm

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.19.3
Stage | running
Available Repositories | 937
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | pending

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 23.9 GB
disk_used | 6.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.9.0), Let's Encrypt (4.12.0), File editor (5.3.3), Samba share (9.5.1), Studio Code Server (4.1.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 5
-- | --
resources | 9
views | 13
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

When used in an entity card, the icon representing the sensor.hacs does not get "colored" when there is an update (or several) available.

### Reproduction steps

1. Use the sensor.hacs in an entity card
2. Make sure there is a update available for any of the repositories managed by hacs
3. The entity card shows nr of available updates, but does not indicating this with a colored icon.  See screenshots and compare with the Home Assistant icon that turns blue (in my case) when a update is available.

### Screenshots

![image](https://user-images.githubusercontent.com/35530660/150006636-13d7e98f-7e19-41b9-8268-ca169c8b4c3b.png)
![image](https://user-images.githubusercontent.com/35530660/150006802-c42d4905-7c40-481c-89de-5286016e65d5.png)

### Javascript logs from your browser console

```text
I'm not sure what to provide here.. :(
```

**Comment by ludeeus** [comment]
It's a sensor, only binary_sensors have that capability.
