### ISSUE TITLE
Request for removal of robert-alfaro/xfinity-usage

### ISSUE THREAD

**Issue by hubertron** [hacs/integration#2458]
### Repository

robert-alfaro/xfinity-usage

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

There are a number of issues with this plugin that will take major rework from the author in order to work. The most relevant issue is that Xfinity is now blocking his approach from fetching this data and without a better scraping engine like Selenium this project will no longer function. Issues have been listed in detail on the authors GH and hasn't had a response from the author in over a year. 

### Link to issue

https://github.com/robert-alfaro/xfinity-usage/issues

**Comment by ludeeus** [comment]
Your statement is not true.
<https://github.com/robert-alfaro/xfinity-usage/issues/12#issuecomment-985168468> This was last month.
Ping @robert-alfaro

**Comment by robert-alfaro** [comment]
I will admit, there has been a small amount of negligence with this integration.

I was holding out in hopes that someone could help fix the integration without the use of chromedriver or the like.  However, it's looking like that is the only option.  So, I can update the integration to use chromedriver like others I believe have done.

**Comment by ludeeus** [comment]
Thanks for responding, closing this issue for now :+1:
