### ISSUE TITLE
Cannot remove Aftership sensor

### ISSUE THREAD

**Issue by Dinth** [hacs/integration#2465]
## System Health

version | core-2021.12.10
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 4.19.0-18-amd64
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4679
Installed Version | 1.19.3
Stage | running
Available Repositories | 984
Downloaded Repositories | 49

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 17, 2022, 12:00 AM
relayer_connected | true
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
remote_server | eu-west-2-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.dev1001
docker_version | 19.03.14
disk_total | 125.9 GB
disk_used | 41.5 GB
healthy | failed to load: Unhealthy
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | InfluxDB (4.3.0), Mosquitto broker (6.0.1), Terminal & SSH (9.3.0), Studio Code Server (4.1.0), ESPHome (2022.1.1), Z-Wave JS to MQTT (0.34.1), Samba Backup (5.0.0), Zigbee2mqtt (1.22.2-1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 32
views | 19
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

A while ago i have added a new Aftership integration to HACS. It seems that a day or two later, the Aftership integration has been blacklisted from HACS and i started receiving a dialog box (on HACS main page) asking me to remove Aftership.
Unfortunately, i have tried removing it - either by clicking Remove in that dialog box, or manually finding Aftership on the list of installed integrations - and it doesnt work.

### Reproduction steps

1. Install Aftership sensor on an HA instance through HACS 
2. Blacklist and remove Aftership sensor's repository from HACS repositories

### Debug logs

```text
2022-01-23 06:32:02 DEBUG (MainThread) [custom_components.hacs] Running uninstall for custom-components/sensor.custom_aftership
2022-01-23 06:32:02 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/sensor.custom_aftership> Getting repository information
2022-01-23 06:32:03 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/sensor.custom_aftership> Running checks against 0.4.0
2022-01-23 06:32:03 INFO (MainThread) [custom_components.hacs] <Integration custom-components/sensor.custom_aftership> Uninstalling
2022-01-23 06:32:03 ERROR (MainThread) [custom_components.hacs] <Integration custom-components/sensor.custom_aftership> Missing domain
2022-01-23 06:32:03 ERROR (MainThread) [custom_components.hacs] Could not uninstall
```
```

**Comment by ludeeus** [comment]
That integration has not been updated in 3 years and is not a valid repository to use with HACS.
It is also not usable with HA for the past 6 months (at least)
Your reproduction is not possible to follow as HACS will not allow for this to be downloaded.

HACS will not be able to remove this as it is missing the required information needed for proper removal.
Can you upload the `/config/.storage/hacs.repositories` file to this issue?

**Comment by Dinth** [comment]
Yes, i fully understand, my problem is only about not being able to remove the repository which was added through HACS (not even as a custom repo) 
Here is the hacs.repositories file: https://zerobin.net/?1ada7d03ae777599#8mhVaL4Z5fFKraaLCVoz3299MVU4oppFwybuSQieG6A=
