### ISSUE TITLE
Remove heinoldenhuis/home_assistant_omnik_solar -> archived

### ISSUE THREAD

**Issue by hultenvp** [hacs/integration#2474]
### Repository

heinoldenhuis/home_assistant_omnik_solar

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Author has stopped maintenance, see [readme](https://github.com/heinoldenhuis/home_assistant_omnik_solar/blob/master/README.md)

I'll take over maintenance from my [fork](https://github.com/hultenvp/home_assistant_omnik_solar). Will create PR for adding my repo.

Owner has also deleted all issues. Copy from last issue update via mail as proof of attention:

[GMX - Re_ [heinoldenhuis_home_assistant_omnik_solar] New HA Energy Dashboard (#14).pdf](https://github.com/hacs/integration/files/7957906/GMX.-.Re_.heinoldenhuis_home_assistant_omnik_solar.New.HA.Energy.Dashboard.14.pdf)

### Link to issue

https://github.com/heinoldenhuis/home_assistant_omnik_solar/blob/master/README.md

**Comment by ludeeus** [comment]
Removed in https://github.com/hacs/default/pull/1221
