### ISSUE TITLE
Feature request: badges in the man lhs menu

### ISSUE THREAD

**Issue by orandasoft** [hacs/integration#2480]
### Web browser

iOS app

### Web browser version

15.3

### System Health details

NA

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

This is a feature request.

Currently, HACS shows the integrations / updates available on the main HACS page. It would be nice if there is a badge in the main Lhasa menu indicating HACS has updates available.

### Reproduction steps

1. Go to main menu
2. Go to main HACS page
3. Confirm updates are available
...

### Screenshots

NA

### Javascript logs from your browser console

```text
NA
```

**Comment by ludeeus** [comment]
It is not possible for custom panels to provide that.
You can use the `sensor.hacs` entity to indicate when there are updates.
