### ISSUE TITLE
can't install hacs

### ISSUE THREAD

**Issue by ren9821** [hacs/integration#2486]
## System Health

version | core-2022.2.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.91
arch | x86_64
timezone | Asia/Shanghai

<details><summary>Home Assistant Community Store</summary>

error | failed to load: unknown
-- | --

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | failed to load: unreachable
can_reach_cloud_auth | failed to load: unreachable
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 11.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), AirSonos (3.1.1), File editor (5.3.3), Mosquitto broker (6.0.1), Node-RED (10.0.1), SSH & Web Terminal (9.0.1), Visual Studio Code (3.6.2), Zigbee2mqtt (1.22.1-1), ESPHome (2021.10.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 12
views | 4
mode | storage

</details>

<details><summary>Xiaomi MIoT</summary>

logged_in | true
-- | --
can_reach_micloud_server | ok
accounts_count | 1
account_devices_count | 29
added_devices | 3

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

After the hacs is installed, it keeps showing that the setup failed

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
此错误来自自定义集成。

Logger: homeassistant.config_entries
Source: custom_components/hacs/tasks/setup_frontend.py:11
Integration: HACS (documentation, issues)
First occurred: 18:30:27 (1 occurrences)
Last logged: 18:30:27

Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hacs/__init__.py", line 167, in async_setup_entry
    return await async_initialize_integration(hass=hass, config_entry=config_entry)
  File "/config/custom_components/hacs/__init__.py", line 103, in async_initialize_integration
    await hacs.tasks.async_load()
  File "/config/custom_components/hacs/tasks/manager.py", line 42, in async_load
    await asyncio.gather(*[_load_module(task) for task in task_modules])
  File "/config/custom_components/hacs/tasks/manager.py", line 38, in _load_module
    task_module = import_module(f"{__package__}.{module}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/hacs/tasks/setup_frontend.py", line 11, in <module>
    from ..hacs_frontend import locate_dir
ModuleNotFoundError: No module named 'custom_components.hacs.hacs_frontend'
```

**Comment by ludeeus** [comment]
How did you "install" it?

**Comment by ren9821** [comment]
I had a problem after installing the hacs upgrade system before, so I deleted it (delete both the &nbsp;directory and the .storage directory)


1. Download the hacs archive on github&nbsp;
2. Put the hacs folder in the custom_components directory 3. Restart the system&nbsp;
4. Add in the integration
I install hacs a lot, so there should be no issues with the installation process, with reboots at every step.



------------------ Original ------------------
From: Joakim Sørensen ***@***.***&gt;
Date: Thu,Feb 3,2022 6:41 PM
To: hacs/integration ***@***.***&gt;
Cc: Shwan ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [hacs/integration] can't install hacs (Issue #2486)





 
How did you "install" it?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ludeeus** [comment]
What exactly do you mean by "hacs archive"?
`hacs.zip` which you need to use does include that module so I'm guessing you did not do that?
Use <https://hacs.xyz/docs/setup/download> for instructions on how to download.

**Comment by ren9821** [comment]
Logger: homeassistant.components.system_health
Source: custom_components/hacs/system_health.py:22
Integration: 系统状态 (documentation, issues)
First occurred: 18:36:58 (1 occurrences)
Last logged: 18:36:58


Error fetching info
Traceback (most recent call last):
&nbsp; File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 68, in get_integration_info
&nbsp; &nbsp; data = await registration.info_callback(hass)
&nbsp; File "/config/custom_components/hacs/system_health.py", line 22, in system_health_info
&nbsp; &nbsp; response = await hacs.githubapi.rate_limit()
AttributeError: 'NoneType' object has no attribute 'rate_limit'







------------------ Original ------------------
From: Joakim Sørensen ***@***.***&gt;
Date: Thu,Feb 3,2022 6:41 PM
To: hacs/integration ***@***.***&gt;
Cc: Shwan ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [hacs/integration] can't install hacs (Issue #2486)





 
How did you "install" it?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ren9821** [comment]
yes, no errors





------------------ Original ------------------
From: Joakim Sørensen ***@***.***&gt;
Date: Thu,Feb 3,2022 6:51 PM
To: hacs/integration ***@***.***&gt;
Cc: Shwan ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [hacs/integration] can't install hacs (Issue #2486)





 
What exactly do you mean by "hacs archive"?
 hacs.zip which you need to use does include that module so I'm guessing you did not do that?
 Use https://hacs.xyz/docs/setup/download for instructions on how to download.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ludeeus** [comment]
yes? to what?

**Comment by ren9821** [comment]
I used this command to install it.wget -O - https://get.hacs.xyz | bash -





------------------ Original ------------------
From: Joakim Sørensen ***@***.***&gt;
Date: Thu,Feb 3,2022 6:53 PM
To: hacs/integration ***@***.***&gt;
Cc: Shwan ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [hacs/integration] can't install hacs (Issue #2486)





 
yes? to what?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ludeeus** [comment]
[That is not what you said at all](https://github.com/hacs/integration/issues/2486#issuecomment-1028856818).
Paste the output of that command.

**Comment by remkolems** [comment]
> I used this command to install it.wget -O - https://get.hacs.xyz | bash -
> […](#)
> ------------------ Original ------------------ From: Joakim Sørensen ***@***.***&gt; Date: Thu,Feb 3,2022 6:53 PM To: hacs/integration ***@***.***&gt; Cc: Shwan ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [hacs/integration] can't install hacs (Issue #2486) yes? to what? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Use the following:

`wget -O - https://raw.githubusercontent.com/hacs/get/main/get | bash -`

With the other command I couldn't get HACS into the integration list. hacs directory was present at the/config/custom_componets though.

Software versions:
- Home Assistant OS 7.2 x64
- supervisor-2022.01.1
- core-2022.2.1
