### ISSUE TITLE
Error Logs from HACS

### ISSUE THREAD

**Issue by thorrrr** [hacs/integration#2499]
## System Health

version | core-2022.2.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.96
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.22.0
Stage | running
Available Repositories | 977
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 18.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Check Home Assistant configuration (3.9.0), SSH & Web Terminal (10.0.2), Home Assistant Google Drive Backup (0.105.2), Studio Code Server (4.1.0), MariaDB (2.4.0), InfluxDB (4.3.0), Grafana (7.4.1), Mosquitto broker (6.0.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 16
views | 75
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Getting an error log
This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/tasks/base.py:34
Integration: HACS (documentation, issues)
First occurred: 8 February 2022, 20:50:25 (1 occurrences)
Last logged: 8 February 2022, 20:50:25

HacsTask<update_critical_repositories> failed: <Integration custom-components/sensor.custom_aftership> Repository has been requested to be removed.

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
https://0bin.net/paste/MXpULZdR#2uob2M+w9ZSJ336L-pzf3VQzttM4ft9+zhOT969dbSl
```

**Comment by ludeeus** [comment]
Debug logs are missing.

**Comment by thorrrr** [comment]
I thought the new Diagonostic Download was superseding that. That what i got from the live stream to stop users having to mess around with grabbing logs!!!
The new streamlining processes of getting HA more user friendly

**Comment by ludeeus** [comment]
If that was the case, it would not have been part of the issue template.

**Comment by thorrrr** [comment]
I thought the new Diagonostic Download was superseding that. That what i got from the live stream to stop users having to mess around with grabbing logs!!!
The new streamlining processes of getting HA more user friendly

**Comment by thorrrr** [comment]
No worries so you're not streamlining, and the Diagonostic Download is of no use!
