### ISSUE TITLE
Hacs cannot be installed

### ISSUE THREAD

**Issue by LoEnzo** [hacs/integration#2500]
### Describe the issue

Inheritance searches for HACS as a blank line
Click on the error as follows

 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading config flow for integration hacs: cannot import name 'EVENT_HOMEASSISTANT_STARTED'

For help

### Link to action run

hacs

### Link to action configuration

hacs

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
You need Home Assistant version 2021.9.0 or newer
