### ISSUE TITLE
Blocking call warning since 2022.2

### ISSUE THREAD

**Issue by HepoH3** [hacs/integration#2503]
## System Health

version | core-2022.2.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.98
arch | x86_64
timezone | Europe/Moscow

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4864
Installed Version | 1.22.0
Stage | running
Available Repositories | 987
Downloaded Repositories | 23

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 15.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.0.1), Samba share (9.5.1), room-assistant (2.19.0), Studio Code Server (4.1.0), SSH & Web Terminal (10.0.2), ESPHome (2022.1.4), Home Assistant Git Exporter (1.12.1), motionEye (0.17.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 11
views | 11
mode | yaml

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.5.2
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 26

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

After upgrading to 2022.2 core gives a bunch of warnings about blocking calls, one of them related to HACS:

### Reproduction steps

As far as I understand, you need wait untill hacs will update information about new repositories, but it's not for sure.

### Debug logs

```text
Detected blocking call inside the event loop. This is causing stability issues. Please report issue to the custom component author for hacs doing blocking calls at custom_components/hacs/repositories/base.py, line 901: repository = await github.get_repo(self.data.full_name, etag)
```

**Comment by ludeeus** [comment]
This is wrong. There is nothing blocking about that.
Please add diagnostics dump <https://hacs.xyz/docs/basic/diagnostics>

**Comment by HepoH3** [comment]
> This is wrong. There is nothing blocking about that. Please add diagnostics dump https://hacs.xyz/docs/basic/diagnostics
[config_entry-hacs-1cec46a4ab9ef2907a286d66ed016ed9.json.txt](https://github.com/hacs/integration/files/8052992/config_entry-hacs-1cec46a4ab9ef2907a286d66ed016ed9.json.txt)

**Comment by ludeeus** [comment]
You have a good amount of custom integrations.
Start by disabling all of them except for HACS, then run `ha core rebuild` to restart with a clean container.

**Comment by HepoH3** [comment]
> You have a good amount of custom integrations. Start by disabling all of them except for HACS, then run `ha core rebuild` to restart with a clean container.

Sorry, it's seems to be very inconvenient for me, because I need to disable a lot of config with disabling integrations. If I need to find broken one, I need to enable them one by one, and since I can't reproduce warning by myself (it's just occure sometimes and repeats itself about twenty times at once), I can't be for sure that another integration is good and I can enable next one.

If that's warning is not hacs problem we can close this issue. Sorry for wasting your time, I just thought I could help with pointing to a problem part of code.

**Comment by HepoH3** [comment]
> out of curiosity, are you using the `debugpy` integration? If so, can you disable that and see if it gets better?

Nope

**Comment by ludeeus** [comment]
Don't have it or did not help?
The message you posted only happens when `time.sleep` and `HTTPConnection.putrequest` are called, none of which are called from HACS, and given the other issues you opened that would explain it since `debugpy` and other debuggers uses `time.sleep`

**Comment by HepoH3** [comment]
> Don't have it or did not help? The message you posted only happens when `time.sleep` and `HTTPConnection.putrequest` are called, none of which are called from HACS, and given the other issues you opened that would explain it since `debugpy` and other debuggers uses `time.sleep`

Oh, sry. I don't have this one. At least I did not install it manually. All I have is:
![](https://puu.sh/IIFre/3238e70c6e.png)
I install Start Time to check how much time spent on staring ha, that's the only intgeration i've install for the debug sake. I'll try to disable it and see what happens.

**Comment by ludeeus** [comment]
Some of your issues was correct as some of your integrations like the map extractor thingy do have time.sleep <https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/blob/master/custom_components/xiaomi_cloud_map_extractor/camera.py#L301>
