### ISSUE TITLE
Problem with repository

### ISSUE THREAD

**Issue by gfelisberto** [hacs/integration#2509]
### System Health details

After an upgrade do HA and HACS I am currently getting:

```
homeassistant  | 2022-02-13 21:35:06 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package deebotozmo==3.0.1: warning: missing-index-doctype
homeassistant  |
homeassistant  | × The package index page being used does not have a proper HTML doctype declaration.
homeassistant  | ╰─> Problematic URL: https://wheels.home-assistant.io/alpine-3.14/armv7/
homeassistant  |
homeassistant  | note: This is an issue with the page at the URL mentioned above.
homeassistant  | hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context.
homeassistant  | ERROR: Cannot install deebotozmo==3.0.1 because these package versions have conflicting dependencies.
homeassistant  | ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Already stated

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
N/A
```

**Comment by ludeeus** [comment]
This has nothing to do with HACS.

**Comment by gfelisberto** [comment]
Is the error not with an issue with the repository?
