### ISSUE TITLE
HACS asks for oauth access to my *github acount*. /What/?

### ISSUE THREAD

**Issue by fake-name** [hacs/integration#2511]
### System Health details

N/A

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

I'm attempting to install HACS.

However, the HACS install process *wants to access my github account*?

....... What?

There is zero reason what is effectively a package manager should need that. And frankly, **no**. 

------

Why this is even a thing is additionally not documented anywhere. The FAQ is empty (really!), and looking around elsewhere /why/ this needs github access isn't explained anywhere else either.. 

I use homeassistant because I try very hard to *avoid* dependencies on cloud crap. Frankly, I generally wall my hass install off from the internet entirely except when I need to update (primarily because I don't trust IoT stuff I can't flash, so it all gets it's own VLAN). 

### Reproduction steps

1. Atttempt to use HACS
2. No, I won't give you an unrelated account.

### Debug logs

```text
N/A
```

### Diagnostics dump

N/A

**Comment by ludeeus** [comment]
It uses the GitHub API to fetch information.

**Comment by fake-name** [comment]
That...... tells me nothing.
