### ISSUE TITLE
Request for removal of cyberjunky/home-assistant-hvcgroep

### ISSUE THREAD

**Issue by olipayne** [hacs/integration#2530]
### Repository

cyberjunky/home-assistant-hvcgroep

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

No longer works, no support on open issue for 1 month

### Link to issue

https://github.com/cyberjunky/home-assistant-hvcgroep/issues/7

**Comment by ronaldtveen** [comment]
Stating that it no longer works is not correct. 
It has been working flawlessly for me for quite a while now. On a second Home Assistant instance I've installed it about a week or two back and that has been running just fine too. 

The integration seems to work. I'm just an end-user though, not the developer.

**Comment by ludeeus** [comment]
Thanks @ronaldtveen, will close this for now :+1:
