### ISSUE TITLE
HACS 已禁用 - HACS 无法加载

### ISSUE THREAD

**Issue by jiumoshou** [hacs/integration#2548]
### System Health details

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:479
Integration: HACS ([documentation](https://hacs.xyz/docs/configuration/start), [issues](https://github.com/hacs/integration/issues))
First occurred: 20:54:30 (1 occurrences)
Last logged: 20:54:30

Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.github.com'. (_ssl.c:1129)")]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 428, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 479, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.github.com'. (_ssl.c:1129)")]

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

HACS 已禁用 - HACS 无法加载,。This problem looks like an SSL problem

### Reproduction steps

1.install
2.Unable to load after installation
3.
...

### Debug logs

```text
Looks like a debug log for startup

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:479
Integration: HACS ([documentation](https://hacs.xyz/docs/configuration/start), [issues](https://github.com/hacs/integration/issues))
First occurred: 20:54:30 (1 occurrences)
Last logged: 20:54:30

Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.github.com'. (_ssl.c:1129)")]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 428, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 479, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.github.com'. (_ssl.c:1129)")]
```

**Comment by ludeeus** [comment]
This is not an issue with HACS, someone/something is messing with certificates on your network.
Contact your network administrator.
