### ISSUE TITLE
Download guide should suggest Shift+Insert as a Workaround für Ctrl+V

### ISSUE THREAD

**Issue by cremor** [hacs/integration#2555]
### Describe the issue

Neither Ctrl+V nor Ctrl+Shift+V works for me to paste the download command to the SSH Web Terminal. But Shift+Insert works. So this should be suggested in the download guide in the troubleshooting section.

Home Assistant 2022.3.4
SSH & Web Terminal 10.0.2
Firefox 98.0

### Screenshots

![grafik](https://user-images.githubusercontent.com/116314/158137891-49707675-7489-4ebc-95f4-a3c26909996e.png)

**Comment by Forge36** [comment]
Issue with hacs/documentation not hacs/integration

https://github.com/hacs/documentation/blob/40233aac6877ec324ea8c1d9414c68b50d062816/documentation/setup/download.mdx

Proposed fix in:
https://github.com/hacs/documentation/compare/main...Forge36:patch-1

**Comment by cremor** [comment]
> Issue with hacs/documentation not hacs/integration

Yes, but there are multiple places that say you should only report issues in hacs/integration:
- https://hacs.xyz/docs/issues mentiones "[First lets start out by stating that ALL issues should be reported here](https://github.com/hacs/integration/issues)" (links to hacs/integration)
- hacs/integration has a "Documentation" issue template.
- hacs/documentation doesn't even allow me to open issues, it just provides a link to https://github.com/hacs/integration/issues
