### ISSUE TITLE
Request for removal of denysdovhan/vacuum-card

### ISSUE THREAD

**Issue by harddistortion** [hacs/integration#2557]
### Repository

denysdovhan/vacuum-card

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Dear github moderators or other persons who will check this request.

I would like to leave a complaint about the author of this repository. The author uses the repository for the purpose of inciting hatred on a national basis among all those who use this repository in one way or another, which is a violation of the International Convention on the Elimination of All Forms of Racial Discrimination adopted by the UN. The author writes on the title page of his repository about "thousands" of people killed by "intruders from Russia" and murdered children... Yesterday, on 03/14/2022, the troops of the armed forces of Ukraine used a missile strike on the civilian population of Donbass, but not a single media outlet in the "democratic world" found it necessary to voice this act. But people and children, including, really died there. But it's probably other people... the value of their lives for the "civilized" world is zero. I ask you to issue a warning to the author of this repository so that he removes all appeals inciting racial and other types of hatred, in particular towards Russian people.

With the best regards,
Di.

### Link to issue

https://github.com/denysdovhan/vacuum-card/issues/339

**Comment by ludeeus** [comment]
Follow this <https://docs.github.com/en/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam> to report things to GitHub 👍

**Comment by harddistortion** [comment]
Hi Ludeeus,

Ok, clear, thank you for checking this, and have a nice day.
