### ISSUE TITLE
Request for removal of bbbenji/synthwave-hass

### ISSUE THREAD

**Issue by alkenes** [hacs/integration#2560]
### Repository

bbbenji/synthwave-hass

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

The readme and maintenance badge state that the theme hasn't been maintained since October 2020. I haven't actually opened an issue but I thought the readme was enough to satisfy that requirement.

### Link to issue

https://github.com/bbbenji/synthwave-hass

**Comment by ludeeus** [comment]
It's not enough of a reason.
