### ISSUE TITLE
update says: You are running version 1.19.3, version 1.19.2 is available

### ISSUE THREAD

**Issue by patrickcoombe** [hacs/integration#2563]
### Web browser

Chrome

### Web browser version

Version 99.0.4844.82 (Official Build) (64-bit)

## System Health

version | core-2022.3.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.92-v8
arch | aarch64
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.19.3
Stage | running
Available Repositories | 1004
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.5
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.5
docker_version | 20.10.9
disk_total | 232.2 GB
disk_used | 6.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS (0.1.55), File editor (5.3.3), Terminal & SSH (9.3.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 0
views | 2
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

small issue, but it says: 

You are running version 1.19.3, version 1.19.2 is available

when it should say

You are running version 1.19.2, version 1.19.3 is available

unless I'm missing something

### Reproduction steps

1. go to your install then /hacs/entry
2. view update at top

### Screenshots

![hacs](https://user-images.githubusercontent.com/5524641/159626541-8b3fd9c0-5179-48ed-8575-e764d5ef3a89.JPG)

### Javascript logs from your browser console

```text
not needed
```

**Comment by ManCaveMedia** [comment]
I'm not sure, but I believe this issue was solved in version 1.20.0 (#2464)
Unfortunately because of issue #2556 you can not update past 1.19.3 using the normal update method at the moment.

**Comment by ludeeus** [comment]
That's correct, https://github.com/hacs/integration/pull/2464 does indeed fix this.
