### ISSUE TITLE
Brands check failes for PRs

### ISSUE THREAD

**Issue by Bouni** [hacs/integration#2565]
### Describe the issue

I submited a PR and the HACS action fails for the PR branch (https://github.com/Bouni/abfallplus/runs/5673311421) but works on the main branch (https://github.com/Bouni/abfallplus/runs/5675892161)

On the PR branch I see 

❌  is not added to https://github.com/home-assistant/brands (more-info: https://hacs.xyz/docs/publish/include#check-brands )

On the main branch

✅ abfallplus is added to https://github.com/home-assistant/brands NICE!

The source of the HACS action, more specifcally the brands check (https://github.com/hacs/action/blob/main/checks/brands) prints these two messages depending on the check fails or not.
But It should include the domain in both cases which does not seem to be true for my PR branch.

"❌  is not added ..." is printed from `checkError "$domain is not added ...`

`$domain` comes from the manifest `domain=$(jq .domain -r "$GITHUB_ACTION_PATH/data/manifest.json")`

As the manifest in the PR branch clearly exists https://github.com/Bouni/abfallplus/blob/async-rewrite/custom_components/abfallplus/manifest.json#L2 

So next I forked the hacs/action repo and put in two `ls -la` in the brands check to validate that the path is correct and the manifest is there. https://github.com/Bouni/action/blob/main/checks/brands#L13-L14

If I check the output of that forked action on the **main** branch I see this:

```sh
  total 52
  drwxr-xr-x 2 runner docker 4096 Mar 24 13:16 .
  drwxr-xr-x 8 runner docker 4096 Mar 24 13:16 ..
  -rw-r--r-- 1 runner docker   17 Mar 24 13:16 action_repository
  -rw-r--r-- 1 runner docker   12 Mar 24 13:16 category
  -rw-r--r-- 1 runner docker   71 Mar 24 13:16 hacs.json
  -rw-r--r-- 1 runner docker    1 Mar 24 13:16 ignore
  -rw-r--r-- 1 runner docker 5764 Mar 24 13:16 info
  -rw-r--r-- 1 runner docker  394 Mar 24 13:16 manifest.json
  -rw-r--r-- 1 runner docker   40 Mar 24 13:16 path
  -rw-r--r-- 1 runner docker   17 Mar 24 13:16 repository
  -rw-r--r-- 1 runner docker   41 Mar 24 13:16 token
  -rw-r--r-- 1 runner docker   90 Mar 24 13:16 topics
```

On the PR branch I see the same output, but the manifest.json is 0 bytes in size:

```sh
   total 48
  drwxr-xr-x 2 runner docker 4096 Mar 24 13:25 .
  drwxr-xr-x 8 runner docker 4096 Mar 24 13:25 ..
  -rw-r--r-- 1 runner docker   17 Mar 24 13:25 action_repository
  -rw-r--r-- 1 runner docker   12 Mar 24 13:25 category
  -rw-r--r-- 1 runner docker   71 Mar 24 13:25 hacs.json
  -rw-r--r-- 1 runner docker    1 Mar 24 13:25 ignore
  -rw-r--r-- 1 runner docker 5764 Mar 24 13:25 info
  -rw-r--r-- 1 runner docker    0 Mar 24 13:25 manifest.json
  -rw-r--r-- 1 runner docker   40 Mar 24 13:25 path
  -rw-r--r-- 1 runner docker   17 Mar 24 13:25 repository
  -rw-r--r-- 1 runner docker   41 Mar 24 13:25 token
  -rw-r--r-- 1 runner docker   90 Mar 24 13:25 topics
```

So I digged a little deeper and found that the previos check `manifest` locates the actual `manifest.json` https://github.com/Bouni/action/blob/main/checks/manifest#L21-L22 
It then copys the content to a `manifest.json` outside the actual repo using `jq` https://github.com/Bouni/action/blob/main/checks/manifest#L29

I reproduced these steps locally and got this error `parse error: Expected another array element at line 11, column 3`
This is caused by a comma at the last element of the requirements array in the manifest:

https://github.com/Bouni/abfallplus/blob/692272657488895179f5ddbfd0c299aa5ab341a3/custom_components/abfallplus/manifest.json#L10

After removing this comma, the action ran as expected.

I totally understand that this was caused by me being carelesly, but I think the manifest should be validated before an action uses it, furthermore the error apeared way before the actual `brands` check but didn't trigger anything until that check which made it quite hard to figure out where to look for the error!

Maybe the output of `jq` can be used to determin if the `manifest.json` is valid: https://github.com/hacs/action/blob/main/checks/manifest#L29

### Link to action run

https://github.com/Bouni/abfallplus/runs/5673311421

### Link to action configuration

https://github.com/Bouni/abfallplus/blob/master/.github/workflows/hacs.yml

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
That is not something the HACS action should need to be concerned about.
You should use `hassfest` to validate the manifest.json file https://github.com/home-assistant/actions#hassfest
