### ISSUE TITLE
Hacs not updating 

### ISSUE THREAD

**Issue by yousaf465** [hacs/integration#2567]
### System Health details

![image](https://user-images.githubusercontent.com/83491212/160224731-21a94d4e-e85b-4e92-a8ec-bd90495026e5.png)

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

![image](https://user-images.githubusercontent.com/83491212/160224724-04963ad3-e9db-4009-a2f5-dfc82cbf12cc.png)
after trying to update all these integration through HACS I manually updated these. I have restarted HA core multiple times after this but these are still listed updates available. 

### Reproduction steps

Open HACS 
check for updates 

### Debug logs

```text
enabled.
```

**Comment by ludeeus** [comment]
Please update your issue with the missing information.

**Comment by yousaf465** [comment]
how I can post the log?

**Comment by ludeeus** [comment]
That's up to you, you can paste content, or upload a file.
Just make sure you remove any personal information from it.

**Comment by ManCaveMedia** [comment]
I'm guessing here, but you might want to take a look an #2519. I stumbled upon it only after I reported #2566.

**Comment by bmangodt** [comment]
Same issue here, running integration version 1.13.2 and trying to update to 1.24.0. Full delete and reinstall does nothing. Also none of the Frontend or Integrations can be installed. Home Assistant logs have no errors and I am running core-2022.3.8 with supervisor-2022.03.5.
