### ISSUE TITLE
hacs update from 1.5.2 to 1.24.0 fails after HA core update to 2022.3.8

### ISSUE THREAD

**Issue by SamuelCarson** [hacs/integration#2577]
### Describe the issue

Updated OS to 7.5 and Supervisor to 2022.3.8. HACS is at 1.15.2. Update needed to 1.24.0. Updated HACS and restarted Supervisor (as instructed). After restart HACS still says update needed 1.15.2-->1.24.0.

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS bot.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

**Comment by ludeeus** [comment]
Downgrade HA and then upgrade HACS.
Or use download script from website
