### ISSUE TITLE
Request for removal of filipvh/hass-nhc2

### ISSUE THREAD

**Issue by thomas-svrts** [hacs/integration#2579]
### Repository

filipvh/hass-nhc2

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

please replace with with joleys/niko-home-control-II

see issue:
https://github.com/filipvh/hass-nhc2/issues/43
https://github.com/filipvh/hass-nhc2/issues/41
https://github.com/filipvh/hass-nhc2/issues/38

### Link to issue

https://github.com/filipvh/hass-nhc2/issues/38

**Comment by ludeeus** [comment]
Fix was merged yesterday https://github.com/filipvh/hass-nhc2/pull/39
