### ISSUE TITLE
ImportError: cannot import name 'PLATFORMS' from 'custom_components.hacs.const'

### ISSUE THREAD

**Issue by shoaaaib** [hacs/integration#2580]
## System Health

version | core-2022.3.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.92-v8
arch | aarch64
timezone | Asia/Dubai

<details><summary>Home Assistant Community Store</summary>

error | failed to load: unknown
-- | --

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.5
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.5
docker_version | 20.10.9
disk_total | 116.7 GB
disk_used | 13.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.10.0), Duck DNS (1.14.0), MariaDB (2.4.0), NGINX Home Assistant SSL proxy (3.1.1), Samba share (9.5.1), Node-RED (11.1.1), Studio Code Server (4.2.0), File editor (5.3.3), Terminal & SSH (9.3.0), Let's Encrypt (4.12.0), Home Assistant Google Drive Backup (0.106.2), Dnsmasq (1.4.4)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 13
views | 9
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Hacs not loading 

### Reproduction steps

1.restarted many times
2.deleted and installed hacs
3.replaced the file manually
...

### Debug logs

```text
2022-03-30 21:48:36 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-30 21:48:49 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for hacs
File "/config/custom_components/hacs/__init__.py", line 168, in async_setup_entry
File "/config/custom_components/hacs/__init__.py", line 104, in async_initialize_integration
await hacs.tasks.async_load()
File "/config/custom_components/hacs/tasks/manager.py", line 42, in async_load
File "/config/custom_components/hacs/tasks/manager.py", line 38, in _load_module
File "/config/custom_components/hacs/tasks/setup_sensor.py", line 8, in <module>
ImportError: cannot import name 'PLATFORMS' from 'custom_components.hacs.const' (/config/custom_components/hacs/const.py)
```

**Comment by shoaaaib** [comment]
what does not exist?

**Comment by ludeeus** [comment]
PLATFORMS

**Comment by jzeeman01** [comment]
I'm getting the same issue - what was the solution?
can you explain: Run the download script from the website?
thx

**Comment by stepri** [comment]
Same question here. How did you manage to fix this?
