### ISSUE TITLE
"new" obsolete header in HACS

### ISSUE THREAD

**Issue by Tyrian81** [hacs/integration#2581]
### Web browser

chrome and HA companion

### Web browser version

Versie 100.0.4896.60 (Officiële build) (64-bits)

## System Health

version | core-2022.3.8
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.13.0-39-generic
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4725
Installed Version | 1.24.0
Stage | running
Available Repositories | 1007
Downloaded Repositories | 44

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 28
views | 11
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The most recent HACS update gave me a new header; Add-ons
Which is not supported in docker containers as far as I know 
The link does not take me anywhere....
Running HA for a few years now and this is the first time this pops up.

### Reproduction steps

1.Update HACS to latest version
2.New link present Add-ons
3.
...

### Screenshots

https://imgur.com/a/Kwc6Hgv

### Javascript logs from your browser console

```text
CARD-MOD 3.1.4 IS INSTALLED
card-mod.js?hacstag=190927524314:5 You may not be getting optimal performance out of card-mod.
See https://github.com/thomasloven/lovelace-card-mod#performance-improvements
mini-graph-card-bundle.js?hacstag=1512800620110:1  MINI-GRAPH-CARD  0.11.0 
kiosk-mode.js?hacstag=303101606172:64 ≡ kiosk-mode            ⋮ 
version 1.7.2            
slider-entity-row.js?hacstag=1448997001721:1 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
(anonymous) @ slider-entity-row.js?hacstag=1448997001721:1
slider-entity-row.js?hacstag=1448997001721:59 SLIDER-ENTITY-ROW 17.2.1 IS INSTALLED 
simple-thermostat.js:204 simple-thermostat: 0.38.0
bar-card.js:4855   BAR-CARD   Version 3.1.7    
entities.js:28   SPOTIFY-CARD   Version 2.4.0    
swipe-navigation.js?hacstag=183995552136:51 ≡ swipe-navigation      ⋮ 
version 1.3.6            
button-card.js:425   BUTTON-CARD   Version 3.4.2 
utils.ts:1  BATTERY-STATE-CARD  2.1.1
card.js?hacstag=2153271951110:295 
  RGB Light Card  v1.11.0  
light-entity-card.js?hacstag=168744428500:6868   LIGHT-ENTITY-CARD     Version 5.0.0       
meteoalarm-card.js?hacstag=3612056631141:285  METEOALARM-CARD  1.14.1 
slider-button-card.js?hacstag=3754399611103:497   SLIDER-BUTTON-CARD  v1.10.3 
alarmo-card.js?hacstag=391372854130:877   ALARMO-CARD    Version: v1.3.0 
frigate-hass-card.js?hacstag=394082552300:21563   FRIGATE-HASS-CARD   Version 3.0.0    
multiple-entity-row.js?hacstag=178921037441:1  MULTIPLE-ENTITY-ROW  4.4.1 
mushroom.js?hacstag=444350375130:1877 🍄 Mushroom 🍄 - 1.3.0
2:8123/lovelace/default_view:1 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mushroom-badge-icon" has already been used with this registry
neerslag-card.js?cache=1648703668.7076747:867  NEERSLAG-CARD  2022.02.10.0
```

**Comment by ludeeus** [comment]
Fixed in https://github.com/hacs/frontend/pull/576
