### ISSUE TITLE
HACS won't update after upgrading HA 

### ISSUE THREAD

**Issue by adv0r** [hacs/integration#2582]
### Web browser

chrome

### Web browser version

latest

### System Health details

Just to raise awareness

Posts of people reporting the issue in the HA forum [one](https://community.home-assistant.io/t/update-to-latest-core-caused-major-issues-with-hacs/370273)
and [two](https://community.home-assistant.io/t/updated-to-core-2022-3-2-cant-update-hacs-supervisor-disappeared-from-menu/400015/2)

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

See the forum

### Reproduction steps

1.upgrade HA
2. try to upgrade HACS
3.
...

### Screenshots

no need

### Javascript logs from your browser console

```text
js.log
```

**Comment by ludeeus** [comment]
Run the download script from the website if you have new HA and old HACS.
