### ISSUE TITLE
Broken link to FAQ in /hacs/entry

### ISSUE THREAD

**Issue by CloCkWeRX** [hacs/integration#2590]
### Describe the issue

Visit /hacs/entry
Click on the FAQ link

Expected:
I'm taken to an FAQ; such as https://hacs.xyz/docs/faq/addons

Actual:
404 - https://hacs.xyz/docs/faq/what

### Screenshots

![image](https://user-images.githubusercontent.com/365751/161410275-efe8c53e-08f3-4a2c-981a-7fcec292ae3c.png)

![image](https://user-images.githubusercontent.com/365751/161410279-c4d50931-b2d8-4442-a0e5-ce284d002ae0.png)

**Comment by ludeeus** [comment]
Website redirect has been adjusted.
