### ISSUE TITLE
HACS not able to update integrations 

### ISSUE THREAD

**Issue by yousaf465** [hacs/integration#2601]
## System Health

version | core-2022.4.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.15.32-v8
arch | aarch64
timezone | Asia/Karachi

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4469
Installed Version | 1.24.3
Stage | running
Available Repositories | 1013
Downloaded Repositories | 23

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.0.rc1
-- | --
update_channel | beta
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.12
disk_total | 29.0 GB
disk_used | 25.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), File editor (5.3.3), Home Assistant Google Drive Backup (0.106.2), InfluxDB (4.4.1), Grafana (7.5.2), Glances (0.15.0), ZeroTier One (0.13.2), SSH & Web Terminal (10.1.1), Check Home Assistant configuration (3.10.0), CEC Scanner (3.0), ESPHome (2022.3.1), Log Viewer (0.13.0), MariaDB (2.4.0), Tautulli (2.3.0), Webhook Relay - Remote Access (2.4.3), Tailscale (1.22.2.0), AdGuard Home (4.5.0), Samba Backup (5.0.0), ADS-B Multi-Portal Feeder (1.0.3), Angry IP Scanner (0.1.0), CUPS Print Server (1.0.0-alpha.25), Tailscale (0.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 10
views | 15
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I am unable to update these integrations from HACS UI. 
pre-update
![image](https://user-images.githubusercontent.com/83491212/162556898-fdaa69c3-a005-4fa9-ae71-99dc359d76d4.png)
post-update pre restart. 
![image](https://user-images.githubusercontent.com/83491212/162557085-437ced3f-01de-42ab-96ed-9ef5eb837823.png)
Post-update Post-restart 
![image](https://user-images.githubusercontent.com/83491212/162558098-0a922e59-2cb8-41af-8d82-48c299681a3c.png)

### Reproduction steps

1.Open HACS 
2. Try to update any of these integrations, it will ask you to restart HA. 
3. Restart and the same old version will be there. 
...

### Debug logs

```text
https://www.codepile.net/pile/KryRP0An
```

### Diagnostics dump

[config_entry-hacs-68dfba7f30ee8effc973e96e69690487.json.txt](https://github.com/hacs/integration/files/8456282/config_entry-hacs-68dfba7f30ee8effc973e96e69690487.json.txt)

**Comment by schwarzenbergf** [comment]
I have probably the same issue with this integrations:

- Node-RED Companion
- Scheduler Component

What I find in the logs is:
_This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:947
Integration: HACS (documentation, issues)
First occurred: 12:21:34 PM (4 occurrences)
Last logged: 12:21:34 PM

[services.yaml] was not downloaded.
[manifest.json] was not downloaded.
[switch.py] was not downloaded.
[store.py] was not downloaded._

It is possible to download manually and to fix it temporarily, but the problem comes back.

**Comment by MGBRunner** [comment]
Exact same issue here...

**Comment by mattwynharris** [comment]
yip exact same for me tried different things but no luck

**Comment by schwarzenbergf** [comment]
Same here.

**Comment by yousaf465** [comment]
@ludeeus this will be fixed in next version?

**Comment by bronder** [comment]
This has been going on for me for about a month now.  I keep hoping an update will fix it, but nothing yet.  I have 4 things stuck in old versions.  Govee, Blue Iris, Wyze and something I can't recall

**Comment by TommisGR** [comment]
Same issue download fails with message:
"check the network on the host running Home Assistant. This is not a problem with HACS but how your host communicates with GitHub"
HA 2022.4
Lattest HACS
BLE and sonoffLAN

**Comment by schwarzenbergf** [comment]
I have the same still here, for a long time already.
It started with the 
Scheduler component and now
I have NodeRED with the same issue since a week or so.
Download fails with the same message as shown by @TommisGR .
I downloaded  and upgraded the components manually. The Scheduler component shows me the new version but HACS claims still to see the old version and wants to update, which finally does not work.
I have latest HACS and HA 2022.4 .

**Comment by MGBRunner** [comment]
Just update HA 2022.4.2 and no joy yet....

**Comment by wvoigt** [comment]
I also see this with:

- Scheduler component
- Raspberry Pi GPIO

**Comment by TommisGR** [comment]
I can also confirm that  HACS 1.24.5 upgrade fixed the issue.

**Comment by schwarzenbergf** [comment]
Yes, it's working with HACS 1.24.5 and HA 2022.4.3. Thank you !!!

**Comment by gitthangbaby** [comment]
but how to update it, it also fails. following guides, GUI doesn't remotely look like the instructions. Stuck at v1.14.1.

**Comment by yousaf465** [comment]
> but how to update it, it also fails. following guides, GUI doesn't remotely look like the instructions. Stuck at v1.14.1.

reinstall hacs https://hacs.xyz/docs/setup/download.
In summary run this command in ssh
```
wget -O - https://get.hacs.xyz | bash -
```

**Comment by MGBRunner** [comment]
Thanks so much for the simple HACS update command!  Worked
