### ISSUE TITLE
Error level logging regarding "has been requested to be removed"

### ISSUE THREAD

**Issue by koying** [hacs/integration#2602]
## System Health

version | core-2022.4.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.63-v7l+
arch | armv7l
timezone | Europe/Brussels

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4157
Installed Version | 1.24.3
Stage | running
Available Repositories | 1011
Downloaded Repositories | 27

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 13
views | 16
error | /config/notexist.yaml not found
mode | yaml

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Basically a continuation of #2499 

As of today, I get this in my logs:
```
2022-04-09 10:51:26 ERROR (MainThread) [custom_components.hacs] HacsTask<prosess_queue> failed: <Integration r-renato/hass-xiaomi-mi-flora-and-flower-care> Repository has been requested to be removed.
```

Are, me as I user or you, as HACS, we supposed to act on this error?
Is it actually more a notice, or does someone actually have to take action?

If it's a notice, it'd probably best to lower the log level.
If an action is actually to be taken, I have no clue which by whom ;)

### Reproduction steps

1. (Re)start HA. Randomly displayed for random custom integrations

### Debug logs

```text
2022-04-09 10:51:26 ERROR (MainThread) [custom_components.hacs] HacsTask<prosess_queue> failed: <Integration r-renato/hass-xiaomi-mi-flora-and-flower-care> Repository has been requested to be removed.
```

**Comment by gigideveloper** [comment]
I also have this message

**Comment by REH-dev** [comment]
I have exactly the same issue

**Comment by LaCruz75** [comment]
Same on  core-2022.4.5
Logger: custom_components.hacs
Source: custom_components/hacs/tasks/base.py:34
Integration: HACS ([documentation](https://hacs.xyz/docs/configuration/start), [issues](https://github.com/hacs/integration/issues))
First occurred: 17:29:46 (1 occurrences)
Last logged: 17:29:46

<HacsTask prosess_queue> failed: <Integration r-renato/hass-xiaomi-mi-flora-and-flower-care> Repository has been requested to be removed.

**Comment by Opontios** [comment]
The same for me. But no solution given, as I see.

**Comment by Mick51** [comment]
`Cette erreur provient d'une intégration personnalisée

Logger: custom_components.hacs
Source: custom_components/hacs/tasks/base.py:34
Integration: HACS (documentation, issues)
First occurred: 11:35:53 (1 occurrences)
Last logged: 11:35:53

<HacsTask prosess_queue> failed: <Integration custom-components/sensor.custom_aftership> Repository has been requested to be removed.`
