### ISSUE TITLE
Overlapping icon / menu item too wide

### ISSUE THREAD

**Issue by emufan** [hacs/integration#2614]
### Web browser

Vivaldi

### Web browser version

5.2.2623.26

## System Health

version | core-2022.4.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.108
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.24.4
Stage | running
Available Repositories | 1026
Downloaded Repositories | 40

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 30. April 2022, 02:00
relayer_connected | true
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | false
remote_server | eu-west-2-2.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.9
disk_total | 113.9 GB
disk_used | 11.2 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), File editor (5.3.3), Check Home Assistant configuration (3.10.0), Samba Backup (5.0.0), Studio Code Server (4.2.0), SSH & Web Terminal (10.1.1), Mosquitto broker (6.0.1), Eufy Security Add-on (0.8.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 26
views | 15
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The text is overlapping the icon / width of the div is too wide

![image](https://user-images.githubusercontent.com/22775515/162919638-e83ddf8c-8dba-4551-a51d-4432607eb047.png)

Same, but not directly visiable in about-div

![image](https://user-images.githubusercontent.com/22775515/162919729-c85e43ff-4968-4c75-92e8-4d77e08a42db.png)

### Reproduction steps

1. Open HACS menu

### Screenshots

see above

### Javascript logs from your browser console

```text
none
```

**Comment by ludeeus** [comment]
This was fixed in <https://github.com/hacs/frontend/pull/579>

**Comment by emufan** [comment]
@ludeeus Hm, if I look there https://github.com/hacs/frontend/pull/579/files only the Icon has been removed. But the div/text would be still too long/wide, wouldn't it? See screenshots above.
