### ISSUE TITLE
Remove usage of the term "Lovelace" since it is no longer used by the HA team

### ISSUE THREAD

**Issue by bdr99** [hacs/integration#2631]
### Web browser

N/A

### Web browser version

N/A

### System Health details

N/A

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

As stated in the [2022.4 release notes](https://www.home-assistant.io/blog/2022/04/06/release-20224/#goodbye-lovelace-hello-dashboards), HA has renamed "Lovelace" to "Dashboards". All instances of "Lovelace" have been removed from the HA frontend. However, there are still places in HACS where "Lovelace" is used. These should be removed and replaced with "Dashboard" or another relevant term.

### Reproduction steps

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/2292715/163693578-2dcb7ec4-f24e-472a-8918-28f224c55455.png)

### Javascript logs from your browser console

```text
N/A
```

**Comment by bdr99** [comment]
@ludeeus May I ask why this was closed?

**Comment by ludeeus** [comment]
It's not an issue.
There is a Feature Request for it <https://github.com/hacs/integration/discussions/2600>
