### ISSUE TITLE
error when update repository 

### ISSUE THREAD

**Issue by matteos1** [hacs/integration#2635]
### Describe the issue

after last update of hacs this issue appears
Attività in background in sospeso
Alcuni repository potrebbero non essere visualizzati fino al completamento

Pending background activity
Some repositories may not be displayed until completed

and stop update

### Link to action run

after some minutes after restart of ha

### Link to action configuration

after some minutes after restart of ha

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue)![image](https://user-images.githubusercontent.com/16237822/164498711-bd5bf29b-d867-42e6-9af7-9d3d39110c64.png)

**Comment by antoweb** [comment]
Same problem here

**Comment by tarokker** [comment]
same

**Comment by ludeeus** [comment]
This has nothing to do with the action.
Please fill out the template for backend/integration.
https://github.com/hacs/integration/issues/new?assignees=&labels=issue%3Abackend&template=a_integration.yml
