### ISSUE TITLE
sensor.custom_aftership

### ISSUE THREAD

**Issue by Mick51** [hacs/integration#2636]
### System Health details

`Cette erreur provient d'une intégration personnalisée

Logger: custom_components.hacs
Source: custom_components/hacs/tasks/base.py:34
Integration: HACS (documentation, issues)
First occurred: 13:55:20 (1 occurrences)
Last logged: 13:55:20

<HacsTask prosess_queue> failed: <Integration custom-components/sensor.custom_aftership> Repository has been requested to be removed.`

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Cette erreur provient d'une intégration personnalisée

Logger: custom_components.hacs
Source: custom_components/hacs/tasks/base.py:34
Integration: HACS (documentation, issues)
First occurred: 13:55:20 (1 occurrences)
Last logged: 13:55:20

<HacsTask prosess_queue> failed: <Integration custom-components/sensor.custom_aftership> Repository has been requested to be removed.

### Reproduction steps

1. ????
2.
3.
...

### Debug logs

```text
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.hacs
Source: custom_components/hacs/tasks/base.py:34
Integration: HACS (documentation, issues)
First occurred: 13:55:20 (1 occurrences)
Last logged: 13:55:20

<HacsTask prosess_queue> failed: <Integration custom-components/sensor.custom_aftership> Repository has been requested to be removed.
```

**Comment by ludeeus** [comment]
https://github.com/hacs/integration/issues/2602

**Comment by Mick51** [comment]
`Cette erreur provient d'une intégration personnalisée

Logger: custom_components.hacs
Source: custom_components/hacs/tasks/base.py:34
Integration: HACS (documentation, issues)
First occurred: 11:35:53 (1 occurrences)
Last logged: 11:35:53

<HacsTask prosess_queue> failed: <Integration custom-components/sensor.custom_aftership> Repository has been requested to be removed.`
