### ISSUE TITLE
Safari 15.4 does not render the HACS icon

### ISSUE THREAD

**Issue by jfroy** [hacs/integration#2639]
### Web browser

Safari macOS

### Web browser version

Safari 15.4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15

## System Health

version | core-2022.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103-v8
arch | aarch64
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4631
Installed Version | 1.24.5
Stage | running
Available Repositories | 1100
Downloaded Repositories | 19

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | May 7, 2022, 17:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-west-2-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.9
disk_total | 237.6 GB
disk_used | 15.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.106.2), Mosquitto broker (6.0.1), Network UPS Tools (0.10.0), Node-RED (11.1.1), Studio Code Server (5.0.0), Terminal & SSH (9.3.0), Z-Wave JS to MQTT (0.38.0)

</details>

<details><summary>keymaster</summary>

zwave_integration | zwave_js
-- | --
network_status | on

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 16
views | 7
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Safari does not render the HACS icon whereas Chrome does.

Both browsers see the same source page. Using the inspector, this is the shadow DOM svg icon element:

```html
<svg preserveAspectRatio="xMidYMid meet" focusable="false" role="img" aria-hidden="true" viewBox="0 0 24 24">
      <g>
      <!--?lit$570956009$--><path d="m 20.064849,22.306912 c -0.0319,0.369835 -0.280561,0.707789 -0.656773,0.918212 -0.280572,0.153036 -0.605773,0.229553 -0.950094,0.229553 -0.0765,0 -0.146661,-0.0064 -0.216801,-0.01275 -0.605774,-0.05739 -1.135016,-0.344329 -1.402827,-0.7588 l 0.784304,-0.516495 c 0.0893,0.146659 0.344331,0.312448 0.707793,0.34433 0.235931,0.02551 0.471852,-0.01913 0.637643,-0.108401 0.101998,-0.05101 0.172171,-0.127529 0.17854,-0.191295 0.0065,-0.08289 -0.0255,-0.369835 -0.733293,-0.439975 -1.013854,-0.09565 -1.645127,-0.688661 -1.568606,-1.460214 0.0319,-0.382589 0.280561,-0.714165 0.663153,-0.930965 0.331571,-0.172165 0.752423,-0.25506 1.166895,-0.210424 0.599382,0.05739 1.128635,0.344329 1.402816,0.7588 l -0.784304,0.510118 c -0.0893,-0.140282 -0.344331,-0.299694 -0.707782,-0.331576 -0.235932,-0.02551 -0.471863,0.01913 -0.637654,0.10202 -0.0956,0.05739 -0.165791,0.133906 -0.17216,0.191295 -0.0255,0.293317 0.465482,0.420847 0.726913,0.439976 v 0.0064 c 1.020234,0.09565 1.638757,0.66953 1.562237,1.460213 z m -7.466854,-0.988354 c 0,-1.192401 0.962855,-2.155249 2.15525,-2.155249 0.599393,0 1.179645,0.25506 1.594117,0.707789 l -0.695033,0.624895 c -0.235931,-0.25506 -0.561133,-0.401718 -0.899084,-0.401718 -0.675903,0 -1.217906,0.542 -1.217906,1.217906 0,0.66953 0.542003,1.217908 1.217906,1.217908 0.337951,0 0.663153,-0.140283 0.899084,-0.401718 l 0.695033,0.631271 c -0.414472,0.452729 -0.988355,0.707788 -1.594117,0.707788 -1.192395,0 -2.15525,-0.969224 -2.15525,-2.148872 z M 8.6573365,23.461054 10.353474,19.14418 h 0.624893 l 1.568618,4.316874 H 11.52037 L 11.265308,22.734136 H 9.964513 l -0.274192,0.726918 z m 1.6833885,-1.68339 h 0.580263 L 10.646796,21.012487 Z M 8.1089536,19.156932 v 4.297745 H 7.1461095 v -1.645131 h -1.606867 v 1.645131 H 4.5763876 v -4.297745 h 0.9628549 v 1.696143 h 1.606867 V 19.156932 Z M 20.115859,4.2997436 C 20.090359,4.159461 19.969198,4.0574375 19.822548,4.0574375 H 14.141102 10.506516 4.8250686 c -0.14665,0 -0.2678112,0.1020202 -0.2933108,0.2423061 L 3.690064,8.8461703 c -0.00651,0.01913 -0.00651,0.03826 -0.00651,0.057391 v 1.5239797 c 0,0.165789 0.133911,0.299694 0.2996911,0.299694 H 4.5762579 20.0711 20.664112 c 0.165781,0 0.299691,-0.133905 0.299691,-0.299694 V 8.8971848 c 0,-0.01913 0,-0.03826 -0.0065,-0.05739 z M 4.5763876,17.358767 c 0,0.184917 0.1466608,0.331577 0.3315819,0.331577 h 5.5985465 3.634586 0.924594 c 0.184911,0 0.331571,-0.14666 0.331571,-0.331577 v -4.744098 c 0,-0.184918 0.146661,-0.331577 0.331582,-0.331577 h 2.894913 c 0.184921,0 0.331582,0.146659 0.331582,0.331577 v 4.744098 c 0,0.184917 0.146661,0.331577 0.331571,0.331577 h 0.446363 c 0.18491,0 0.331571,-0.14666 0.331571,-0.331577 v -5.636804 c 0,-0.184918 -0.146661,-0.331577 -0.331571,-0.331577 H 4.9079695 c -0.1849211,0 -0.3315819,0.146659 -0.3315819,0.331577 z m 1.6578879,-4.852498 h 5.6495565 c 0.15303,0 0.280561,0.12753 0.280561,0.280564 v 3.513438 c 0,0.153036 -0.127531,0.280566 -0.280561,0.280566 H 6.2342755 c -0.1530412,0 -0.2805719,-0.12753 -0.2805719,-0.280566 v -3.513438 c 0,-0.159411 0.1275307,-0.280564 0.2805719,-0.280564 z M 19.790657,3.3879075 H 4.8569594 c -0.1530412,0 -0.2805718,-0.1275296 -0.2805718,-0.2805642 V 1.3665653 C 4.5763876,1.2135296 4.7039182,1.086 4.8569594,1.086 H 19.790657 c 0.153041,0 0.280572,0.1275296 0.280572,0.2805653 v 1.740778 c 0,0.1530346 -0.127531,0.2805642 -0.280572,0.2805642 z"></path>
      </g>
    </svg>
```

Isolating that svg in a simple html file does not show any problems (both browsers render it fine), which suggests this is probably a layout issue.

And indeed, looking at the elements with the inspector in Safari, the `ha-svg-icon` element for HACS (under the `ha-icon` element) has no `:host` stylesheet, which applies a `width` and `height` style, collapsing the `ha-icon` parent to 0 height.

<img width="821" alt="Screen Shot 2022-04-23 at 23 42 10" src="https://user-images.githubusercontent.com/49554/164960263-d8e7f1ed-9ea3-4497-9521-8552b3aabcda.png">

This is not the case for all the other sidebar icons (picking the following icon for example):

<img width="1009" alt="Screen Shot 2022-04-23 at 23 43 01" src="https://user-images.githubusercontent.com/49554/164960307-34750d75-beec-40bc-bd36-0a11c8a1aa62.png">

Under Chrome, HACS's `ha-svg-icon` element does have its `:host` stylesheet.

### Reproduction steps

1. Install the latest macOS (at time of writing 12.3.1 (21E258)) and Safari (at time of writing 15.4 (17613.1.17.1.13))
2. Load HASS UI using either local or remote URL, makes no difference.
3. Install HACS if not already done.
4. Notice icon is missing in sidebar.
5. Load same HASS instance in Chrome. Notice icon is present.

### Screenshots

Safari:
<img width="132" alt="Screen Shot 2022-04-23 at 23 16 11" src="https://user-images.githubusercontent.com/49554/164959417-6a9286e0-3d5f-42bb-9ab5-25b44a599a01.png">

Chrome (at time of writing 100.0.4896.75):
<img width="125" alt="Screen Shot 2022-04-23 at 23 16 53" src="https://user-images.githubusercontent.com/49554/164959436-f2328657-2f1a-4d9c-9c87-ce8a4373c2b6.png">

### Javascript logs from your browser console

```text
N/A (no log entry at all)
```

### Diagnostics dump

[config_entry-hacs-1abbc928126232bd0bfb0e55810bb682.json.txt](https://github.com/hacs/integration/files/8549105/config_entry-hacs-1abbc928126232bd0bfb0e55810bb682.json.txt)

**Comment by ludeeus** [comment]
HACS only provides the icon, it's Home Assistant that uses/displays it.
If you have issues with the HACS icon, I assume you have issues with all custom icons?
I have no issues displaying it myself with Safari 15.4

**Comment by jfroy** [comment]
I have several other add-ons (Node-RED, Studio Code Server, Z-Wave JS) and they all have their icon.

**Comment by ludeeus** [comment]
None of those are custom icons

**Comment by jfroy** [comment]
Ah, right. I'll install a few more integrations from HACS with custom sidebar icon (not sure which ones do).

When I did my testing, I did make sure to disable all Safari extensions and content blockers, empty cache, hard refresh, all the usual things.
