### ISSUE TITLE
Link to restart Home Assistant following HACS upgrade is broken

### ISSUE THREAD

**Issue by stinkyfromusc** [hacs/integration#2645]
### Web browser

Chrome 

### Web browser version

100.0.4896.127

## System Health

version | core-2022.5.0b0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.15.35
arch | aarch64
timezone | America/Toronto

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 44

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | May 26, 2022, 8:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.0.rc3
-- | --
update_channel | beta
supervisor_version | supervisor-2022.04.3
docker_version | 20.10.14
disk_total | 113.9 GB
disk_used | 60.4 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Mosquitto broker (6.0.1), File editor (5.3.3), Duck DNS (1.14.0), Lutron Certificate (0.7.0), Spotify Connect (0.11.0), Let's Encrypt (4.12.0), NGINX Home Assistant SSL proxy (3.1.1), Ring-MQTT with Video Streaming (4.9.1), Terminal & SSH (9.3.0), IDE (2.2.0), Home Assistant Google Drive Backup (0.106.2), Log Viewer (0.13.0), VLC (0.1.3), AppDaemon (0.8.2), Studio Code Server (5.0.0), ESPHome (2022.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 16
views | 25
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I am running Home Assistant Core 2022.5.0b0

When I click on Navigate it takes me to https://XXX.ui.nabu.casa/config/server_control which seems to be a dead link now.

The new core version has some new menus, and this must have deprecated the server_control link.

### Reproduction steps

1. Upgraded to Home Assistant Core 2022.5.0b0
2. updated HACS integrations and upgraded HACS to latest version
3. clicked on NAVIGATE to reboot my Home Assistant
...

### Screenshots

![image](https://user-images.githubusercontent.com/26009445/165630197-a21e512c-7d44-4660-98e6-1980a81f6b1f.png)

### Javascript logs from your browser console

```text
n/a
```

**Comment by ludeeus** [comment]
Was adjusted in 2022.5.0b2

**Comment by icicimov** [comment]
Hello,

I have the same issue being sent to `/config/server_control` that does not exist anymore. I'm on
```
Home Assistant Core 2022.5.3
Home Assistant Supervisor 2022.05.1
Home Assistant OS 7.6
Kernel version 5.10.108
Agent version 1.2.1
```
so wonder if the mentioned update was released?
