### ISSUE TITLE
Navigate button does not work anymore with new Server Controls

### ISSUE THREAD

**Issue by wrt54g** [hacs/integration#2647]
### Web browser

Chrome

### Web browser version

101.0.4951.41

## System Health

version | core-2022.5.0b2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.15.32-v7l
arch | armv7l
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4870
Installed Version | 1.24.5
Stage | running
Available Repositories | 1027
Downloaded Repositories | 15

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.0.rc3
-- | --
update_channel | beta
supervisor_version | supervisor-2022.04.4
docker_version | 20.10.14
disk_total | 13.9 GB
disk_used | 10.0 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), AdGuard Home (4.5.1), Terminal & SSH (9.3.0), Node-RED (11.1.1), Samba share (9.6.0), Mosquitto broker (6.0.2), ESPHome (beta) (2022.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 6
views | 16
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When the Navigate button is clicked on the front page (I mean the Navigate button from the notification that I need to restart my Home Assistant after an update), it does not work. It just takes me to a blank page.
![image](https://user-images.githubusercontent.com/85389871/165922404-26f2d6ae-a0ba-448b-be25-f182d7bd0bca.png)
This is probably because in the 2022.5.0 version of Home Assistant Core, the server controls changed

### Reproduction steps

In the HACS main page, if an update has completed it shows that navigate to server controls button. When I click the button, it would take me to a blank page.

### Screenshots

![image](https://user-images.githubusercontent.com/85389871/165924032-b937cca2-a4e3-4d8d-b895-7f9e38e257a5.png)

![image](https://user-images.githubusercontent.com/85389871/165923955-16ff0ec5-d1ce-4e31-bc6d-162c6a2b7686.png)

### Javascript logs from your browser console

```text
CARD-MOD 3.1.4 IS INSTALLED
card-mod.js?hacstag=190927524314:5 You may not be getting optimal performance out of card-mod.
See https://github.com/thomasloven/lovelace-card-mod#performance-improvements
hass-hue-icons.js?hacstag=3844345221215:1246  HASS-HUE-ICONS  Version 1.2.15 
button-card.js?hacstag=146194325342:425   BUTTON-CARD   Version 3.4.2 
digital-clock.js?hacstag=373832981122:186   Digital-Clock   Version 1.2.1    
mushroom.js?hacstag=444350375163:2349 🍄 Mushroom 🍄 - 1.6.3
browser_mod.js:145 BROWSER_MOD 1.5.3 IS INSTALLED
```

**Comment by ludeeus** [comment]
B4 fixed that.
