### ISSUE TITLE
Can't Update Several HACS Integrations - Github seems unreachable for days - Seems to have started after upgrade to 1.24.5

### ISSUE THREAD

**Issue by Trebacz** [hacs/integration#2648]
## System Health

version | core-2022.4.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103-v8
arch | aarch64
timezone | America/Phoenix

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | failed to load: unreachable
GitHub Web | ok
GitHub API Calls Remaining | 4804
Installed Version | 1.24.5
Stage | running
Available Repositories | 1099
Downloaded Repositories | 25

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.9
disk_total | 439.4 GB
disk_used | 9.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.6.1), Terminal & SSH (9.3.0), InfluxDB (4.4.1), Home Assistant Google Drive Backup (0.106.2), Spotify Connect (0.11.0), ESPHome (2022.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 11
views | 9
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

For the past several days I have not been able to update several integrations - after a recent update to hacs. Both HACS and the integrations had been working fine. The "GitHub Content" is listed as "unreachable" under Home Assistant Community Store. The are many instances of this in the log: 

### Reproduction steps

1. Try and update an integration
2. Clicking it spins for a bit ad then a quick error message shows
3.  Integration is not updated

### Debug logs

```text
Download failed - Cannot connect to host raw.githubusercontent.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 528, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)

The above exception was the direct cause of the following exception:
```

### Diagnostics dump

[config_entry-hacs-3536adcdbf098bf829a9726d84012f74.json.txt](https://github.com/hacs/integration/files/8597579/config_entry-hacs-3536adcdbf098bf829a9726d84012f74.json.txt)

**Comment by ludeeus** [comment]
Someone or something is intercepting your SSL traffic and injecting a certificate most likely to monitor/control it.
This is not an issue with HACS, but how your host access internet.
If you need help with general network connectivity issue, try asking on the home assistant discord server 👍

**Comment by Trebacz** [comment]
Turns out my PFSense firewall DNS Block List was blocking access. Temporarily disabled and everything worked as expected. @ludeeus Thanks tor the hint. Not sure why the domain is/was on the list....
