### ISSUE TITLE
Spurious error in logs for custom_components/None/manifest.json

### ISSUE THREAD

**Issue by sam-ward** [hacs/integration#2652]
## System Health

version | core-2022.4.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.108
arch | x86_64
timezone | Australia/Perth

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4998
Installed Version | 1.24.5
Stage | running
Available Repositories | 1102
Downloaded Repositories | 37

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | May 25, 2022, 8:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | ap-southeast-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.9
disk_total | 109.3 GB
disk_used | 30.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.6.1), Check Home Assistant configuration (3.10.0), Terminal & SSH (9.4.0), Log Viewer (0.6.4), SSH & Web Terminal (10.1.3), ESPHome (2022.3.2), Portainer (2.0.0), File editor (5.3.3), Mosquitto broker (6.0.2), InfluxDB (4.4.1), Glances (0.15.0), Grafana (7.5.2), Samba Backup (5.0.0), MariaDB (2.4.0), AirSonos (3.3.0), AppDaemon (0.8.2), phpMyAdmin (0.7.1), RTSPtoWeb - WebRTC (1.2.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 21
views | 36
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Shortly after restarting my HA instance, I find I get the following error in the logs"
```
2022-04-28 11:59:12 ERROR (MainThread) [custom_components.hacs] <HacsTask prosess_queue> failed: No manifest.json file found 'custom_components/None/manifest.json'
```
But I do not have a custom component called None. 

The log file is attached here as Github was telling me my issue was too long to submit.

[home-assistant.log.txt](https://github.com/hacs/integration/files/8608671/home-assistant.log.txt)

### Reproduction steps

1. Restart Home Assistant
2. After the restart is complete, open the home-assistant.log file and observe the line:
```
<HacsTask prosess_queue> failed: No manifest.json file found 'custom_components/None/manifest.json'
```

### Debug logs

```text
Please see the issue description above for the attached log file as github was telling me my issue body was too long.
```

### Diagnostics dump

[config_entry-hacs-69d966041c888f365e9392080187cc65.json.txt](https://github.com/hacs/integration/files/8608676/config_entry-hacs-69d966041c888f365e9392080187cc65.json.txt)

**Comment by ludeeus** [comment]
Your debug log does not include that message.
Please provide debug logs from the same timeframe if this still happens.

**Comment by ludeeus** [comment]
This is caused by `codingcyclist/ha_strava` which you have added as a custom repository, remove it from HACS as that is not usable with the version you have of Home Assistant anyway.
(have not been usable since at least 2021.6)

**Comment by sam-ward** [comment]
Thank you for the quick response.

Can I ask how you managed to identify that the ha_strava integration was the source of the custom_components/None/manifest.json message??  I am interested so I can troubleshoot this myself should it occur again in the future.

**Comment by ludeeus** [comment]
It was the only integration listed before the line that does not have a manifest file

**Comment by sam-ward** [comment]
> It was the only integration listed before the line that does not have a manifest file

ok thank you.
