### ISSUE TITLE
Is it possible to copy the yaml of homekit in hacs

### ISSUE THREAD

**Issue by MagicStarTrace** [hacs/integration#2653]
### System Health details

OS:ubuntu 18.04 
HACSversion: The latest version of

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I want to use manageable homekit to maintain homekit yaml configuration！

At present, the homekit discovered by HACS is often stuck in the update, and does not support modifying yaml. How to copy yaml config and apply it to standalone deployed homekit (homebridge)?

### Reproduction steps

no need to reproduce

### Debug logs

```text
no data
```

**Comment by ludeeus** [comment]
HACS has nothing to do with homekit
