### ISSUE TITLE
Restart shortcut not working in HA 2022.5

### ISSUE THREAD

**Issue by tigers75** [hacs/integration#2655]
### Web browser

HA official app

### Web browser version

Latest

## System Health

version | core-2022.5.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103-v7l+
arch | armv7l
timezone | Europe/Rome

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4788
Installed Version | 1.24.5
Stage | running
Available Repositories | 1037
Downloaded Repositories | 31

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 20
views | 19
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

After updating custom components that need a restart of the system there’s a shortcut on top right. After the 2022.5 system menu revamp the shortcut no longer works and points to an empty page. 

### Reproduction steps

1. Update a custom component
2. Click on the navigate button on top right

### Screenshots

No need

### Javascript logs from your browser console

```text
None
```

**Comment by OldShaterhan** [comment]
Already solved: https://github.com/hacs/frontend/commit/7b65f18e2b1e0ebff3ecfb0f5638c529aac58ab0 - needs only to release new version by @ludeeus
