### ISSUE TITLE
Disable/Enable Integration

### ISSUE THREAD

**Issue by pickonedev** [hacs/integration#2668]
### System Health details

There is any way to disable/enable integration (like in the default HA integrations?), but still, the integration should keep updating if there is a new update, only to keep HA logs clean when I don't use a device from an integration. I always get errors in HA logs, because of not powering my AC, and I want to have the possibility to disable a specific integration, if I won't use it for a period of time. Of course, if you can even do some automations with this, to disable/enable integration, it will be very good, but for me, it is enough even with a disable/enable integration and a HA restart after.

Thank you!

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

It is not an issue, it is a feature request:

The possibility to disable/enable integration (like in the default HA integrations?), but still, the integration should keep updating if there is a new update.

### Reproduction steps

1. Open HACS
2. Go to Integrations
3. There is no enable/disable option for the integrations
...

### Debug logs

```text
No logs, sorry!
```

**Comment by ludeeus** [comment]
It can be disabled like core integrations.
All integrations can.
While disabled, nothing will work, an integration can not be enabled and disabled at the same time.
