### ISSUE TITLE
Request for removal of itchannel/fordpass-ha

### ISSUE THREAD

**Issue by GerdRuetten** [hacs/integration#2676]
### Repository

itchannel/fordpass-ha

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

The repository is not supported from the author

### Link to issue

https://github.com/itchannel/fordpass-ha/issues/174

**Comment by ludeeus** [comment]
https://github.com/itchannel/fordpass-ha/commit/849071b96217eda40fee98fa99816b6ca599cdf2
Last commit was 2 days before your issue which is only 3 weeks old at this point.
Its too early for this.
