### ISSUE TITLE
Not Updating

### ISSUE THREAD

**Issue by remirr** [hacs/integration#2682]
### System Health details

 Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.hacs
Source: custom_components/hacs/helpers/methods/installation.py:92
Integration: HACS (documentation, issues)
First occurred: 17:49:53 (1 occurrences)
Last logged: 17:49:53

Download was not completed

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Cannot update HACS or any of the integrations using the update feature in Home assistant, get the above errow

### Reproduction steps

1. Click on on HACS
2. Select any integration or the HACS 
3. Click update
4. restart
5. update still showing
...

### Debug logs

```text
Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.hacs
Source: custom_components/hacs/helpers/methods/installation.py:92
Integration: HACS (documentation, issues)
First occurred: 17:49:53 (1 occurrences)
Last logged: 17:49:53

Download was not completed

Logger: backoff
Source: /usr/local/lib/python3.9/site-packages/backoff/_common.py:119
First occurred: 17:49:53 (1 occurrences)
Last logged: 17:49:53

Giving up async_download_file(...) after 5 tries (TypeError: timeout() got an unexpected keyword argument 'loop')
```

**Comment by ludeeus** [comment]
Search for timeout in closed issues
