### ISSUE TITLE
Queue is stuck in an already running state and rate limiting is not occurring

### ISSUE THREAD

**Issue by jrhubott** [hacs/integration#2684]
## System Health

version | core-2022.5.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.15.41
arch | x86_64
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4998
Installed Version | 1.24.5
Stage | running
Available Repositories | 1072
Downloaded Repositories | 64

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.1
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.2
docker_version | 20.10.14
disk_total | 62.3 GB
disk_used | 47.2 GB
healthy | true
supported | failed to load: Unsupported
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (11.1.2), Studio Code Server (5.0.4), ESPHome (2022.3.1), Log Viewer (0.13.0), InfluxDB (4.4.1), Mosquitto broker (6.1.2), SSH & Web Terminal (10.1.3), Grafana (7.5.2), Glances (0.15.0), Samba share (9.6.1), MariaDB (2.4.0), Check Home Assistant configuration (3.10.0), Bookstack (1.1.0), RPC Shutdown (2.2), File editor (5.3.3), SONOS AudioClip TTS (2.0.3), Z-Wave JS to MQTT (0.40.0), AppDaemon (0.8.2), Portainer Addon v1.5.2 (1.5.2.2), phpMyAdmin (0.7.1), OctoPrint Proxy (1.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 44
views | 30
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

After a random period of time HACS no longer processes it's tasks queue.  The log just shows the following:

2022-05-21 20:31:45 DEBUG (MainThread) [custom_components.hacs] <HacsTask prosess_queue> Executing task
2022-05-21 20:31:45 DEBUG (MainThread) [custom_components.hacs] <HacsTask prosess_queue> Queue is already running
2022-05-21 20:31:45 DEBUG (MainThread) [custom_components.hacs] <HacsTask prosess_queue> took 0.000 seconds to complete

Rate limiting is not occurring.  The only other interesting thing that I can see in the logs is the following log statement:

2022-05-21 11:52:04 ERROR (MainThread) [custom_components.hacs] <HacsTask prosess_queue> failed: No manifest.json file found 'custom_components/None/manifest.json'

### Reproduction steps

1. Start Home Assistant
2. Wait for 2+ hours and check HACS status - it will show "Background tasks pending"
3.
...

### Debug logs

```text
Attached
```

### Diagnostics dump

[config_entry-hacs-7a0b4f0eadd3600a3fc36bc375be9775.json.txt](https://github.com/hacs/integration/files/8749711/config_entry-hacs-7a0b4f0eadd3600a3fc36bc375be9775.json.txt)

**Comment by jrhubott** [comment]
Log file attached.

[logs.txt](https://github.com/hacs/integration/files/8749716/logs.txt)

**Comment by ludeeus** [comment]
From your log, "update_downloaded_repositories" are still running.
But this does not matter much now, this has been removed completely in the version that is coming later today.

**Comment by jrhubott** [comment]
Thanks for the update. I will look at that as I didn't see something not completing.
