### ISSUE TITLE
Wrong link to the server restart

### ISSUE THREAD

**Issue by koles142** [hacs/integration#2691]
### Web browser

Chrome

### Web browser version

101.0.4951.67

### System Health details

<html>
<body>

Wersja | core-2022.5.5
-- | --
Typ instalacji | Home Assistant OS
Wersja deweloperska | false
Supervisor | true
Docker | true
Użytkownik | root
Środowisko wirtualne | false
Wersja Pythona | 3.9.9
Rodzina systemu operacyjnego | Linux
Wersja systemu operacyjnego | 5.15.41
Architektura procesora | x86_64
Strefa czasowa | Europe/Warsaw

</body>
</html>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

After update HACS it show sinformation about restart system. When you will click "navigate" it redirect to the server control page. In Home Assistant 2022.5.x restart option is in a different place.

### Reproduction steps

1.Update HACS
2.Click "navigate"
3.At new HA it shows only blank page
...

### Screenshots

none

### Javascript logs from your browser console

```text
none
```

**Comment by ludeeus** [comment]
Update HACS.
