### ISSUE TITLE
You have 1 Lovelace elements that are not loaded properly in Lovelace.

### ISSUE THREAD

**Issue by pattisonmichael** [hacs/integration#2693]
### Web browser

Firefox

### Web browser version

100.0.2 (64-bit)

## System Health

version | core-2022.5.5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.0-13-amd64
arch | x86_64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.25.1
Stage | running
Available Repositories | 1132
Downloaded Repositories | 62

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.3
docker_version | 20.10.14
disk_total | 232.7 GB
disk_used | 38.8 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.0.4), NGINX Home Assistant SSL proxy (3.1.1), Let's Encrypt (4.12.2), File editor (5.3.3), Terminal & SSH (9.4.0), Custom deps deployment (1.3.1), Grocy (0.17.0), Zigbee2mqtt (1.25.1-1), Mosquitto broker (6.1.2), Z-Wave JS to MQTT (0.40.0), AppDaemon (0.8.2), ESPHome (2022.3.1), AdGuard Home (4.5.1), InfluxDB (4.4.1), Genie (3.0.0), Log Viewer (0.13.0), SQLite Web (3.4.0), Node-RED (11.1.2), JupyterLab (0.7.0), WireGuard (0.6.0), Samba Backup (5.0.0), MariaDB (2.4.0), phpMyAdmin (0.7.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 14
-- | --
resources | 37
views | 26
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I get the above warning but no context to which item it refers to.
The log files don't show any errors and I couldn't find anything in my dashboard not working.

As HACS is able to detect "something" is wrong, it would be great if it could be more specific.
This started to appear a few days ago and I don't think i changed anything in the dashboard recently, only updates in HACS of existing components.

### Reproduction steps

1. Go to HCAS
2. Look at warning
3.
...

### Screenshots

![image](https://user-images.githubusercontent.com/17926363/170071142-2670fdc7-3f97-4b70-8255-34839c0570a8.png)

### Javascript logs from your browser console

```text
Error: Promised response from onMessage listener went out of scope 2 background.js:842:170
Error: Promised response from onMessage listener went out of scope 4 background.js:842:170
```

**Comment by ludeeus** [comment]
Look at the "Frontend" section.
More info here <https://hacs.xyz/docs/faq/status_not_loaded>
