### ISSUE TITLE
Request for removal of maykar/kiosk-mode

### ISSUE THREAD

**Issue by hugobloem** [hacs/integration#2707]
### Repository

maykar/kiosk-mode

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Repository has been archived by the author. Opening an issue to request removal from the author is therefore not possible.

### Link to issue

https://github.com/maykar/kiosk-mode/

**Comment by szafran81** [comment]
same thing with:
https://github.com/maykar/lovelace-swipe-navigation

**Comment by tbarbette** [comment]
Why is it archived? Can't find any information...
