### ISSUE TITLE
Action runs only on main/master branch and not pull request source

### ISSUE THREAD

**Issue by TheRealWaldo** [hacs/integration#2708]
### Describe the issue

The action does not run on pull-requests source branches.  Instead, it runs on the main/master branch (seemingly the `github.base_ref` context) or target branch.

Expected would be to run off of the context `github.head_ref` (see https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)

Likely this is due to a relatively recent change in github contexts.

```
  ##[debug] <Integration TheRealWaldo/ha-optimal-humidity> Checking repository.
  ##[debug] <Integration TheRealWaldo/ha-optimal-humidity> Running checks against main
```

### Link to action run

https://github.com/TheRealWaldo/ha-optimal-humidity/runs/6631914547

### Link to action configuration

https://github.com/TheRealWaldo/ha-optimal-humidity/blob/main/.github/workflows/pull.yaml

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
Cant reproduce on main

**Comment by TheRealWaldo** [comment]
@ludeeus main is not yet tagged as a release; when will it be released?

**Comment by ludeeus** [comment]
Dont know

**Comment by TheRealWaldo** [comment]
I confirmed it is now working against 22.5.0 released today.

However is it a known bug that the action no longer posts/updates comments in this version?

```
##[debug] <Integration TheRealWaldo/thermal> Checking repository.
##[debug] <Integration TheRealWaldo/thermal> Running checks against release
```

**Comment by ludeeus** [comment]
It was not ported over, it was flawed at best and a hack I'm no longer willing to maintain.
