### ISSUE TITLE
Error after action migrated to docker

### ISSUE THREAD

**Issue by claha** [hacs/integration#2710]
### Describe the issue

Since the hacs/action migrated to docker I'm getting validation error on hacsjson which I don't understand at all. 

### Link to action run

https://github.com/custom-components/sensor.avanza_stock/runs/6633879088?check_suite_focus=true

### Link to action configuration

https://github.com/custom-components/sensor.avanza_stock/blob/main/.github/workflows/cron.yaml

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
https://github.com/custom-components/sensor.avanza_stock/blob/main/hacs.json#L3

domains (and iot_class) is not valid in that file.

**Comment by claha** [comment]
I tried to remove that in this PR but got the same error 
https://github.com/custom-components/sensor.avanza_stock/pull/138, I will try and re-run the ci (seems you made some tweaks to the commit during the last days).
