### ISSUE TITLE
Button to restart Home Assistant is redirecting to wrong URL

### ISSUE THREAD

**Issue by xaviml** [hacs/integration#2711]
### Web browser

Chrome

### Web browser version

Version 101.0.4951.64 (Official Build) (64-bit)

## System Health

version | core-2022.5.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.15.41
arch | aarch64
timezone | Europe/Madrid

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4768
Installed Version | 1.25.2
Stage | running
Available Repositories | 1107
Downloaded Repositories | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.1
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.3
docker_version | 20.10.14
disk_total | 113.9 GB
disk_used | 37.6 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | AppDaemon (0.8.2), Duck DNS (1.14.0), File editor (5.3.3), Home Assistant Google Drive Backup (0.107.2), MariaDB (2.4.0), Mosquitto broker (6.1.2), NGINX Home Assistant SSL proxy (3.1.1), Samba share (9.6.1), Check Home Assistant configuration (3.10.0), Zigbee2mqtt (1.25.1-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 11
views | 14
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When a new Integration is updated, a message is shown on top of the page. This message contains a button called "Navigate". This button redirects to "/server_controls" when it should redirect to "/config/system" where the "Restart" button is present.

### Reproduction steps

1. Update an integration (any)  to allow the message to pop up on the top
2. Click to the "Navigate" button
3. You are not redirected where you are expected to be.

### Screenshots

![Screenshot from 2022-05-28 13-59-53](https://user-images.githubusercontent.com/3974003/170824573-430e83d2-52af-4c7e-82f5-2de83e697706.png)

### Javascript logs from your browser console

```text
-
```

**Comment by ludeeus** [comment]
That button navigates to /developer-tools/yaml where your can restart.
If it does not do that for you update HACS (or clear browser cache)
