### ISSUE TITLE
Auto-removal on archived packages

### ISSUE THREAD

**Issue by goyney** [hacs/integration#2714]
### System Health details

Not applicable

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I'm referring to this PR: https://github.com/hacs/default/pull/1373

There was no warning, no deprecation notice, no nothing. HACS just automatically removed packages in which my setup relies heavily on. This is not good user experience and I'm a bit set back by just how bad this was handled.

Might I suggest you properly indicate when packages have been archived to allow people chance to prepare for breaking changes instead of having them automatically removed from our configurations? Or give people the ability to keep what is already installed, installed with proper warnings or indications that there will no longer be updates?

This whole process really needs some well documented steps and expectations moving forward.

### Reproduction steps

Not applicable

### Debug logs

```text
Not applicable
```

**Comment by goyney** [comment]
This was so absolutely mishandled. Autoremoval of code/features with no warnings, no deprecations, no nothing is not something I will tolerate.

HACS needs to put proper process around this. They are NOT the gatekeepers of my instance and should not be able to automatically remove things without MY intervention. If they do not address this immediately, I will be removing it and going back to manually adding custom components and integrations.

This is completely unacceptable.

**Comment by DanPatten** [comment]
I agree, depreciation exists for this exact reason. Upgrading software needs to be backwards compatible and at least give warnings in a version before removal.

**Comment by scooper1** [comment]
there needs to be a way of accepting the warning about archived content, not just blanket remove 
Due to this issue, I now have packages that should be tracked by hacs but have to remove another directory to stop hacs  moaning about them in a very visible manner

This system should also handle using out of date packages that have to be continued to be used due to hardware not being able to handle the newer versions  
 
a small icon against the packages would do to indicate that it has been accepted that these packages may cause problems and are not maintained  or have later incompatible versions that may stop working or cause system issues

**Comment by ludeeus** [comment]
If it did that, then that is a bug.
Its designed to warn and give you the option to ignore the action.

**Comment by ludeeus** [comment]
I have tested this now with `maykar/kiosk mode` (which is one of them in the PR you are referring)
Nothing is removed.

I get a log entry with this content:
> WARNING (MainThread) [custom_components.hacs] You have 'maykar/kiosk-mode' installed with HACS this repository has been removed from HACS, please consider removing it. Removal reason (Repository is archived)

And in the HACS UI I have:
![image](https://user-images.githubusercontent.com/15093472/170858274-b33b9998-548a-4ec5-81f5-b65737160dd4.png)
When I click "SHOW" I get:
![image](https://user-images.githubusercontent.com/15093472/170858282-33c89434-0508-40b4-ae9a-960d8c9434f0.png)

And here I can remove (which will remove the file) or I can "IGNORE" and HACS will never bother me about it again.

So what was removed?
What did the logs say?

**Comment by shbatm** [comment]
Confirming @ludeeus's test. Was removed from the store but not uninstalled on my instance. 

![Screenshot_20220529-041924_Home Assistant](https://user-images.githubusercontent.com/18057952/170861077-52a3f1aa-de87-43a7-a762-4c3a6b3da53f.jpg)

**Comment by shbatm** [comment]
After a reboot, I'm seeing that kiosk mode is still there, but not working. 

Console error:

```shell
Uncaught (in promise) https://myurl/hacsfiles/kiosk-mode/null?hacstag=3031016065295
in mwc-list-item-base.ts:224
```

Not sure if this is a HACS cache tagging issue, kiosk issue, or combo of the two.

**Comment by ludeeus** [comment]
That could happen if you updated it while it had the bad version number (5c29a5a).
What you did works, or you could also use the "redownload" feature.
