### ISSUE TITLE
Theme not applied on HACS frontend

### ISSUE THREAD

**Issue by timbrueggenthies** [hacs/integration#2724]
### Web browser

Chrome

### Web browser version

102.0.5005.62

## System Health

version | core-2022.5.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.15.41
arch | x86_64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.25.4
Stage | running
Available Repositories | 1042
Downloaded Repositories | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 13. Juni 2022, 02:00
relayer_connected | true
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
remote_server | eu-west-2-4.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.1
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.3
docker_version | 20.10.14
disk_total | 30.8 GB
disk_used | 7.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.1.2), Node-RED (11.1.2), SSH & Web Terminal (10.1.3), File editor (5.3.3), Zigbee2mqtt (1.25.1-2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 10
views | 7
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The custom theme is not applied the to HACS frontend.
The default Theme is applied correctly (light as well as dark theme)

Used theme: https://github.com/aFFekopp/noctis

### Reproduction steps

1. Install noctis Theme via HACS (see link in issue description)
2. Select noctis Theme in Home Assistant
3. Open HACS

### Screenshots

![image](https://user-images.githubusercontent.com/32687085/170887528-e8687e26-0b11-499e-937e-fd3aeab4800b.png)

### Javascript logs from your browser console

```text
No log entries available
```

**Comment by ludeeus** [comment]
Update HACS

**Comment by timbrueggenthies** [comment]
Thanks, the 1.25.5 just landed in my hass instance. Fixed now.
