### ISSUE TITLE
Request for removal of custom-cards/upcoming-media-card

### ISSUE THREAD

**Issue by rursache** [hacs/integration#2727]
### Repository

custom-cards/upcoming-media-card

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Repo is now read-only

### Link to issue

-

**Comment by ludeeus** [comment]
Has already been removed
