### ISSUE TITLE
HACS Action does not escape # character

### ISSUE THREAD

**Issue by alandtse** [hacs/integration#2730]
### Describe the issue

HACS Action has started failing for branches named with a `#`. It appears to be related to not url escaping the branch name. This may be a result of a recent change as I have been naming branches with `#` for years now.

```
Error:  GitHub returned 404 for https://api.github.com/repos/alandtse/alexa_media_player/git/trees/#1620
```

Correct url should be url escaped:
https://api.github.com/repos/alandtse/alexa_media_player/git/trees/%231620

### Link to action run

https://github.com/custom-components/alexa_media_player/runs/6736313440?check_suite_focus=true

### Link to action configuration

https://github.com/custom-components/alexa_media_player/blob/dev/.github/workflows/validate.yaml#L25-L28

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
HACS action does not care, it passes along whatever GitHub says it is.
The reason it worked before is that the action did not work in branches.

This can probably be worked around in [`aiogithubapi`](https://github.com/ludeeus/aiogithubapi) but should really be an issue for GitHub itself I think (No other things need escaping).

**Comment by alandtse** [comment]
Oh ok. Just so we're on the same page, the action isn't running on a source branch. It's running on a [PR ](https://github.com/custom-components/alexa_media_player/pull/1625) for a pull request.

The checkout action is on the merge. 
```
Checking out the ref
  /usr/bin/git checkout --progress --force refs/remotes/pull/1625/merge
```

Shouldn't the HACS action be targeting the merge (e.g., destination branch after the PR is applied) and not the source branch of the PR?

**Comment by ludeeus** [comment]
Yes, and it does that now.
Before there was a bug so the branch in the PR was never actually used.
