### ISSUE TITLE
Can't update HACS past 1.15 -  I understand I should do it manually, but don't know how

### ISSUE THREAD

**Issue by nirchen** [hacs/integration#2731]
I've searched and found out that fix #2464 solves the problem and I need to update HACS manually but I don't know how to do this without breaking existing integrations via HACS

Thanks

I'm not sure, but I believe this issue was solved in version 1.20.0 (#2464)
Unfortunately because of issue #2556 you can not update past 1.19.3 using the normal update method at the moment.

_Originally posted by @ManCaveMedia in https://github.com/hacs/integration/issues/2563#issuecomment-1078927405_

**Comment by ludeeus** [comment]
Identical to how you flest downloader it.
