### ISSUE TITLE
Error: 2022-06-05 07:44:27 ERROR (MainThread) [frontend.js.latest.202206010] http://192.168.1.198:8123/hacsfiles/lovelace-header-cards/lovelace-header-cards.js:1:3080 Uncaught TypeError: Cannot set properties of null (setting ‘hass’)

### ISSUE THREAD

**Issue by browetd** [hacs/integration#2732]
### Web browser

Firefox

### Web browser version

101.0 (64 bits)

## System Health

version | core-2022.6.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.12
os_name | Linux
os_version | 5.15.41
arch | x86_64
timezone | Europe/Paris

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4329
Installed Version | 1.25.5
Stage | running
Available Repositories | 1044
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.1
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.3
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 457.7 GB
disk_used | 21.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | MariaDB (2.4.0), Check Home Assistant configuration (3.10.0), Duck DNS (1.15.0), File editor (5.3.3), Home Assistant Google Drive Backup (0.108.2), Log Viewer (0.13.0), NGINX Home Assistant SSL proxy (3.1.1), SSH & Web Terminal (10.1.3), Samba share (9.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 13
views | 15
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 29 mai 2022 à 20:22
-- | --
current_recorder_run | 5 juin 2022 à 08:30
estimated_db_size | 1093.23 MiB
database_engine | mysql
database_version | 10.4.19

</details>

<details><summary>Sonoff</summary>

version | 3.0.5 (200f243)
-- | --
cloud_online | 7 / 8
local_online | 7 / 7

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I have ton's of this error (a few every seconds coming in home-assistant.log), I presume this is related to HACS:

2022-06-05 07:44:27 ERROR (MainThread) [frontend.js.latest.202206010] http://192.168.1.198:8123/hacsfiles/lovelace-header-cards/lovelace-header-cards.js:1:3080 Uncaught TypeError: Cannot set properties of null (setting ‘hass‘)

### Reproduction steps

1. This happened after upgrading to HA 2022.6 but not sure it is related as I upgraded another instance of HA and the latest has not this problem....
2.
3.
...

### Screenshots

![Sans titre](https://user-images.githubusercontent.com/46415133/172039437-9adf9d5c-4226-4077-96a7-db38d3b05e0d.png)

### Javascript logs from your browser console

```text
This error appears in home-assistant.log and mentionned as a front-end issue... Everything else is just working fine: lovelace, browser interface, entity updates... HA seems to work perfectly...
```

### Diagnostics dump

I do not have this option in Hacs menu...

**Comment by ludeeus** [comment]
It is not related to HAVS.
Report it to the author of the custom card

**Comment by browetd** [comment]
But I removed the card (header card) from HACS, reloaded HACS and I still have the issue ...  strange...

**Comment by browetd** [comment]
after removing the card (and the resource) and a couple of HA restart, the problem was fixed...
