### ISSUE TITLE
Polling update while polling disabled

### ISSUE THREAD

**Issue by Vebryn** [hacs/integration#2734]
### System Health details

```
This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:505
Integration: HACS (documentation, issues)
First occurred: 02:55:21 (19 occurrences)
Last logged: 05:55:22

Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 451, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 505, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
```

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I disable polling on hacs integration. Despite polling disabled, it shows error on joining github domain.

### Reproduction steps

1. Disable polling on hacs integration
2. Disable Internet connection to issue DNS errors into hacs

### Debug logs

```text
Cf. logs on top
```

**Comment by ludeeus** [comment]
Disabling polling is only for the entities, an none of the entities HACS provides do polling so that setting does nothing for HACS.

**Comment by Vebryn** [comment]
Thanks for your explanation, is there a way do disable github queries ?

**Comment by ludeeus** [comment]
No
