### ISSUE TITLE
hacsjson failing unexpectedly

### ISSUE THREAD

**Issue by tykeal** [hacs/integration#2735]
### Describe the issue

The recent change to do more stringent checking of the hacs.json file is all well and good, but my PR https://github.com/tykeal/homeassistant-rental-control/pull/100 to fix the errors on my own repository are still failing in the exact same way as what caused me to look into the failing test stating that extra keys `data["domains"]` The thing is my change is removing the domains key along with the iot_class key so it should be passing and not failing this check!

### Link to action run

https://github.com/tykeal/homeassistant-rental-control/runs/6758204993?check_suite_focus=true

### Link to action configuration

https://github.com/tykeal/homeassistant-rental-control/blob/main/.github/workflows/hacs.yaml

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
<https://github.com/tykeal/homeassistant-rental-control/runs/6748166202?check_suite_focus=true> it runs fine for the pull_request trigger on your PR.
Its the push event that fails (its designed to run against the default branch if not in a PR)

**Comment by ludeeus** [comment]
It should take the pushed branch so this is still an issue.
