### ISSUE TITLE
HACS does not allow adding a "Archived" repository

### ISSUE THREAD

**Issue by rsnodgrass** [hacs/integration#2738]
### System Health details

Not necessary. Latest HACS on latest 2022.06.04 release.

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Sometimes projects mark a integration/lovelace frontend github repo as "archived", but that doesn't mean it isn't still working or useful. HACS seems to not allow adding that repo anymore even if you manually want to.

I found someone who forked that project that didn't archive it, so that worked, but that is more risky because they could delete it any day. It is more likely an archived project will stay around and not be deleted, just that the owner doesn't want to maintain it anymore. We should be allowed to use that project in HACS manually though.

### Reproduction steps

1. Add https://github.com/youdroid/upcoming-media-card as a custom repo.

### Debug logs

```text
Not necessary.
```

**Comment by ludeeus** [comment]
This is done on purpose and is not considered an issue.

When a repository is archived, it will no longer get any updates.
The main purpose of HACS is to handle updates. This makes archived repositories rather useless to support in HACS, and will only cause useless API calls.

If you want to use an archived repository you should handle that manually.

**Comment by rsnodgrass** [comment]
I get that is a big goal of HACS: updates.  However, isn't another main
goal of HACS to make it easy to install repos?  From a customer experience
perspective, it seems like you can have archived still as an installable
repo...the useless API calls should not be a huge overhead. Especially
since the customer has explicitly added these repos.
