### ISSUE TITLE
HACS/action not working for tag refs

### ISSUE THREAD

**Issue by xaviml** [hacs/integration#2741]
### Describe the issue

In a pipeline I have for [ControllerX](https://github.com/xaviml/controllerx), I have a [HACS validation step](https://github.com/xaviml/controllerx/blob/main/.github/workflows/cicd.yaml#L58-L65) for every commit made in `main`, `tags` or PRs. I have not encountered any problems with it until I released a new version, and the pipeline is failing because of the HACS validation step. I enabled debugging and this is what I see:
```
##[debug] Using selector: EpollSelector
::INFO:: Category: appdaemon
::INFO:: Repository: xaviml/controllerx@refs/tags/v4.21.0
##[debug] <Appdaemon xaviml/controllerx> Checking repository.
##[debug] <Appdaemon xaviml/controllerx> Running checks against refs/v4.21.0
Error:  Repository structure for refs/v4.21.0 is not compliant
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Run hacs/action@main
```
This is the run: https://github.com/xaviml/controllerx/runs/6845533101?check_suite_focus=true
This is another run but executed on the same commit (ad73d654e37a77286e9bbdb93a7b30d0c9d42309): https://github.com/xaviml/controllerx/runs/6845513169?check_suite_focus=true

The first one is failing and the second one is passing.

Note that this was working 2 days ago when I released 4.21.0b2: https://github.com/xaviml/controllerx/runs/6818622344?check_suite_focus=true

The debugging messages did not help me figure out why this is happening, but I am guessing this is related to work done in 
https://github.com/hacs/integration/pull/2740 and https://github.com/hacs/integration/pull/2737

For now, I will disable HACS validation from the pipeline, but I will keep you updated if I found what is causing it.

Thank you for your hard work!

### Link to action run

https://github.com/xaviml/controllerx/runs/6845533101?check_suite_focus=true

### Link to action configuration

https://github.com/xaviml/controllerx/blob/main/.github/workflows/cicd.yaml#L58-L65

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by xaviml** [comment]
What I see from the debugging logs is that "tags" is removed later in the logs and only show "refs/v4.21.0". Maybe related to this part of the code: https://github.com/hacs/integration/blob/cd6c19c295c31d7fc3815d4e84d9ca388051f560/custom_components/hacs/repositories/base.py#L619

Maybe this causes to not find the code to download, hence failing the validation.

**Comment by ludeeus** [comment]
It was "working" before since it always used the default branch regardless of how it was triggered.
Now it uses the ref in the event data if present.

It was never designed to run on anything other than push/PR events.

**Comment by xaviml** [comment]
Hi @ludeeus,

Thank you for the response. Does that mean that this is a "won't fix"? Otherwise, would you be accepting a PR for the fix? I have been investigating and the problem seems to be from the following line, since the exception logs the error I see in the debug logs.

https://github.com/hacs/integration/blob/main/custom_components/hacs/repositories/appdaemon.py#L40

However, it seems that this calls the `aiogithubapi` library. I have checked the following code:

```python
from aiogithubapi import GitHub
import asyncio
TOKEN = "my_token"

async def foo():
    async with GitHub(TOKEN) as github:
        repository = await github.get_repo("xaviml/controllerx")
        contents = await repository.get_contents("apps/controllerx", "refs/tags/v4.21.0")
        print(contents)

asyncio.run(foo())
```

and it fails giving a 404. It seems that is removing "tags/" from reference, which I also seen in the integration repository quite a lot

https://github.com/ludeeus/aiogithubapi/blob/main/aiogithubapi/objects/repository/__init__.py#L108

I have removed that from the `get_contents` code and I am getting a response with no failure.

Why is the `ref.replace("tags/", "")` all around the `aiogithubapi` and `hacs/integration` code? I do not see the point of removing tags from the ref for the following reasons:
- Tag refs will not work
- any branch that contains `tags/` will not work (e.g. `fix-tags/`)

Regards,
Xavi M.

**Comment by ludeeus** [comment]
`ref.replace("tags/", "")` is needed for raw downloads.
If this were to be "fixed", `v4.21.0` needs to be used in `action/action.py` as ref.

But honestly, it has no real use.
You base your tags on a branch where it has already run.

**Comment by xaviml** [comment]
Hi @ludeeus ,

Thank you for looking into this. You are correct, the HACS validation has already executed in the other execution from the branch, and I am aware of it.

Another solution is to pass the commit hash in `action/action.py` as a ref instead of the ref from the run. The commit should work as a ref as well.

Let me know what you think.

Regards,
Xavi M.

**Comment by ludeeus** [comment]
Using commit would be confusing to anyone seeing it, I don't want that.

**Comment by xaviml** [comment]
I understand. Would you be accepting a PR with the following change around [this line](https://github.com/hacs/integration/blob/main/action/action.py#L125)?
```
diff --git a/action/action.py b/action/action.py
index d84e00e..325b0c2 100644
--- a/action/action.py
+++ b/action/action.py
@@ -124,6 +124,10 @@ async def preflight():
                     # For push events
                     ref = event_data["ref"]
 
+                    # For tag events
+                    if ref.startswith("refs/tags/"):
+                        ref = event_data["ref"].split("/")[-1]
+
         logger.info(f"Category: {category}")
         logger.info(f"Repository: {repository}{f'@{ref}' if ref else ''}")
```

Regards,
Xavi M.

**Comment by xaviml** [comment]
> If this were to be "fixed", v4.21.0 needs to be used in action/action.py as ref.

Note that I proposed this because you suggested it. I also confirm that it is working with this code snippet:

```python
from aiogithubapi import GitHub
import asyncio
TOKEN = "my_token"

async def foo():
    async with GitHub(TOKEN) as github:
        repository = await github.get_repo("xaviml/controllerx")
        contents = await repository.get_contents("apps/controllerx", "v4.21.0")
        print(contents)

asyncio.run(foo())
```

Regards,

**Comment by ludeeus** [comment]
```
+                    # For tag events
+                    if ref.startswith("refs/tags/"):
+                        ref = ref.split("/")[-1]
```
Adding that is fine, as that will only affect you

**Comment by xaviml** [comment]
Thank you, I will create PR when I get chance.
