### ISSUE TITLE
Error to upgrade HACS version

### ISSUE THREAD

**Issue by GiulioFattoretto** [hacs/integration#2742]
## System Health

version | core-2022.6.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.12
os_name | Linux
os_version | 5.15.32-v8
arch | aarch64
timezone | Europe/Rome

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4473
Installed Version | 1.13.2
Stage | running
Available Repositories | 1050
Installed Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 23 giugno 2022, 02:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-3.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.1
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.3
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 28.6 GB
disk_used | 9.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Check Home Assistant configuration (3.10.2), Google Assistant SDK (2.5.0), Samba share (9.6.1), deCONZ (6.14.1), Mosquitto broker (6.1.2), Duck DNS (1.15.0), NGINX Home Assistant SSL proxy (3.1.1), Spotify Connect (0.11.0), AirSonos (3.2.0), Terminal & SSH (9.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 15
views | 23
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 4 giugno 2022, 06:39
-- | --
current_recorder_run | 12 giugno 2022, 12:48
estimated_db_size | 154.64 MiB
database_engine | sqlite
database_version | 3.34.1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Is not possible to upgrade the HACS version and install new integration or front-end.
I tried several times, with a lot of reboot, but it is not possible to solve.

### Reproduction steps

1. Reboot System
2. HACS starts
3. Not possible to upgrade version
4. Not possible to install new components / front-end

### Debug logs

```text
2022-06-12 12:48:43 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-12 12:49:04 WARNING (MainThread) [homeassistant.setup] Setup of hacs is taking over 10 seconds.
2022-06-12 13:14:23 ERROR (MainThread) [custom_components.hacs] Download was not completed
2022-06-12 13:26:33 ERROR (MainThread) [custom_components.hacs] Download was not completed
```

**Comment by ludeeus** [comment]
Downgrade Home Assistant or rerun the download script for HACS.

**Comment by GiulioFattoretto** [comment]
> owngrade Home Assistant or rerun the download script for HACS.

Which is the last release to use to have a stable HACS version?
