### ISSUE TITLE
Remove fred-oranje/rituals-genie

### ISSUE THREAD

**Issue by breakthestatic** [hacs/integration#2748]
### Repository

https://github.com/fred-oranje/rituals-genie

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

The repository https://github.com/fred-oranje/rituals-genie appears to have been deleted. Getting errors in the HACS logs (I'm not a user of this repo, but it is throwing these errors regardless):
```
2022-06-16 11:02:27 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
```
Since the repo has completely disappeared, I'm not able to actually contact the owner.

### Link to issue

UNAVAILABLE

**Comment by andrefriasribeiro** [comment]
I just got the same error.

`2022-06-17 23:16:28 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-17 23:17:08 ERROR (MainThread) [custom_components.hacs] HACS is disabled - HacsDisabledReason.RATE_LIMIT`

**Comment by smarthomefamilyverrips** [comment]
Same error here, please remove integration from list.
