### ISSUE TITLE
Can't update HACS or any component

### ISSUE THREAD

**Issue by GinjNinj** [hacs/integration#2749]
### System Health details

<html>
<body>

ersion | core-2022.6.6
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.12
Operating System Family | Linux
Operating System Version | 5.15.32-v8
CPU Architecture | aarch64
Timezone | Europe/London

</body>
</html>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Cannot update HACS or any custom_components. 

Click update, appears to work. Status goes to "pending restart", but update button is still available and after restart it will still be on old version (1.15.2)

![image](https://user-images.githubusercontent.com/73911246/174433160-9054d26d-c3df-4b50-83be-143c39fbff9f.png)

Tried removing HACS from integration and reconnecting to Git etc. All still the same after that.

Issue also applies to custom_component Alexa Media Player, its also stuck on old version. 

### Reproduction steps

1. Click update on HACS or custom component
2. Asks for restart
3. Reboot server
4. HACS still on old version

### Debug logs

```text
Error handling request
10:55:53 – (ERROR) loader.py - message first occurred at 10:47:49 and shows up 2 times
Unexpected exception importing component custom_components.alexa_media
10:55:53 – (ERROR) Alexa Media Player (custom integration) - message first occurred at 10:46:54 and shows up 3 times 
10:46:55 – (WARNING) Spotify
Setup failed for custom integration alexa_media: Unable to import component: Exception importing custom_components.alexa_media
10:46:46 – (ERROR) Home Assistant Supervisor - message first occurred at 10:46:46 and shows up 2 times
/addons return code 500
10:46:46 – (ERROR) Home Assistant Supervisor - message first occurred at 10:46:46 and shows up 2 times
```

**Comment by ludeeus** [comment]
Downgrade Home Assistnat or use the script from the website as you used when you first downloaded HACS.

**Comment by GinjNinj** [comment]
Thank you so much, sorry im a N00B on this stuff! Thanks for all you work on this, it's great!
