### ISSUE TITLE
<Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie

### ISSUE THREAD

**Issue by KitHubek** [hacs/integration#2750]
## System Health

version | core-2022.6.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.12
os_name | Linux
os_version | 5.15.32-v8
arch | aarch64
timezone | Europe/Warsaw

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4945
Installed Version | 1.25.5
Stage | running
Available Repositories | 1060
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>GIOŚ</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.3
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 113.7 GB
disk_used | 19.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (12.0.2), Studio Code Server (5.1.1), Mosquitto broker (6.1.2), Zigbee2mqtt (1.25.2-1), Samba share (9.7.0), Zigbee2mqtt Edge (edge), Duck DNS (1.14.0), NGINX Home Assistant SSL proxy (3.1.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 2
views | 20
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 10 czerwca 2022, 19:29
-- | --
current_recorder_run | 15 czerwca 2022, 08:54
estimated_db_size | 2796.65 MiB
database_engine | sqlite
database_version | 3.34.1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

just see this error at log

### Reproduction steps

just see error at log

### Debug logs

```text
Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:1040
Integration: HACS (documentation, issues)
First occurred: 16 czerwca 2022, 10:01:14 (5 occurrences)
Last logged: 14:01:14

<Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
```

**Comment by ludeeus** [comment]
Removed
