### ISSUE TITLE
Adding HACS integration fails with "No module named 'custom_components.enums'"

### ISSUE THREAD

**Issue by GregWoods** [hacs/integration#2752]
## System Health

version | core-2022.5.5
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 4.4.180+
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 0
views | 2
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Installation Details

I am running HA in Docker on a Synology DS420+
The installation script does not work on this system due to unzip not being installed on the Synology, and no package manager is available to easily install unzip.  So I examined the installation script and performed the steps manually, substituting `7z e` for `unzip`

My exact installation commands are in the "Reproduction steps" section

Steps

### Attempt to add the Integration

Settings -> Devices & Services -> Add Integration -> Search for 'HACS'
HACS is in the list, so some part of the installation was successful.

Modal Dialog reports:

```
Error
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.
```

The error in the log is...

```
Logger: homeassistant.config_entries
Source: config_entries.py:745
First occurred: 23:25:43 (2 occurrences)
Last logged: 23:37:46

Error occurred loading configuration flow for integration hacs: No module named 'custom_components.enums'
```

### Reproduction steps

1. Starting with a working HA Docker container on a Synology DS420+
2. I have attempted to follow the same steps as the script obtained from: https://get.hacs.xyz/, but with my own system's folder names, and substituting `7z e` for `unzip`.
3. cd /volume1/docker/homeassistant
4. mkdir custom_components
5. cd custom_components
6. mkdir hacs
7. cd hacs 
8. wget https://github.com/hacs/integration/releases/latest/download/hacs.zip
9. 7z e hacs.zip 
10. tree .    lists 164 files and 6 directories in the hacs folder
11. rm hacs.zip
12. restart home assistant from the web UI
13. Attempt to add the HACS integration through the web UI, which fails

[home-assistant.log](https://github.com/hacs/integration/files/8971928/home-assistant.log)

### Debug logs

```text
attached in the "steps" section, as they exceeded 64Kb
```

### Diagnostics dump

Not available, because the HACS integration has not been added yet

**Comment by ludeeus** [comment]
You have files and/or folders in places they should not be which messes with relative imports.

1) remove your custom_components dir
2) exec into the container
3) run the download script inside the container
4) restart Home Assistant
