### ISSUE TITLE
Actions fails on every PR due to ``Repository structure is not compliant``

### ISSUE THREAD

**Issue by MrBartusek** [hacs/integration#2754]
### Describe the issue

Hey, every PR in my repo stated failing due to HACS action. This happens only on PRs since the same changes merged to the master passes.

Pr: https://github.com/MrBartusek/MeteoalarmCard/runs/6980444111?check_suite_focus=true
Pr commit: https://github.com/MrBartusek/MeteoalarmCard/runs/7015066185?check_suite_focus=true

The error i get is:
```
::INFO:: Category: plugin
::INFO:: Repository: martin131/MeteoalarmCard@fix_czech_lang
Error:  Repository structure for fix_czech_lang is not compliant
```

The latest passing PR I can find is 7 April https://github.com/MrBartusek/MeteoalarmCard/runs/5873280500?check_suite_focus=true
First failing one 8 June https://github.com/MrBartusek/MeteoalarmCard/runs/6800392450?check_suite_focus=true

### Link to action run

https://github.com/MrBartusek/MeteoalarmCard/runs/6980444111?check_suite_focus=true

### Link to action configuration

https://github.com/MrBartusek/MeteoalarmCard/blob/master/.github/workflows/validate.yml

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
Your repository is using a bundler for the card which makes the card only show on releases.
Forks do not have releases, which then makes those repositories not valid to use.
The reason it "worked" before is that there was a bug in the code that checked the default branch on the origin repo regardless of how it ran.
You should disable running that action for forks.
