### ISSUE TITLE
Request for removal of custom-components/authenticated

### ISSUE THREAD

**Issue by nhadler** [hacs/integration#2769]
### Repository

custom-components/authenticated

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Depreciated.

### Link to issue

https://github.com/custom-components/authenticated

**Comment by DavidFW1960** [comment]
> Depreciated.

So what? It still works fine.

**Comment by ludeeus** [comment]
Unmaintained repositories should be removed from HACS to prevent new installations.
