### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by Foltifeki** [hacs/integration#2774]
### System Health details

System Health

version: core-2022.7.1
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
user: root
virtualenv: false
python_version: 3.10.5
os_name: Linux
os_version: 5.15.45
arch: x86_64
timezone: Europe/Budapest
config_dir: /config

GitHub API: ok
GitHub Content: pending
GitHub Web: ok
GitHub API Calls Remaining: 4689
Installed Version: 1.25.5
Stage: running
Available Repositories: 1070
Downloaded Repositories: 1

logged_in: false
can_reach_cert_server: pending
can_reach_cloud_auth: pending
can_reach_cloud: ok

host_os: Home Assistant OS 8.2
update_channel: stable
supervisor_version: supervisor-2022.07.0
agent_version: 1.2.1
docker_version: 20.10.14
disk_total: 54.3 GB
disk_used: 5.0 GB
healthy: true
supported: true
board: generic-x86-64
supervisor_api: ok
version_api: pending
installed_addons: Duck DNS (1.15.0), Samba NAS (9.7.0-nas2), File editor (5.3.3), Node-RED (12.0.2), Studio Code Server (5.1.2), Mosquitto broker (6.1.2), ESPHome (2022.6.2), Terminal & SSH (9.6.0)

dashboards: 1
resources: 0
mode: auto-gen

oldest_recorder_run: 2022. július 8. 21:18
current_recorder_run: 2022. július 9. 00:35
estimated_db_size: 0.64 MiB
database_engine: sqlite
database_version: 3.38.5

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I can't download anything
![Képernyőkép 2022-07-09 010250](https://user-images.githubusercontent.com/73016755/178080208-b0e97e4a-534c-4cf8-b32b-2ceeae5f5695.png)

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
https://www.mediafire.com/file/5pyn4ufxnepxruw/home-assistant.log/file
```

### Diagnostics dump

[config_entry-hacs-cad43b62f6304cdfca34cdaf6fb9c98f.json.txt](https://github.com/hacs/integration/files/9075407/config_entry-hacs-cad43b62f6304cdfca34cdaf6fb9c98f.json.txt)

**Comment by ludeeus** [comment]
You have network issues, try disabling IPv6.
