### ISSUE TITLE
HACS three dot menu actions completely missing

### ISSUE THREAD

**Issue by dwd1** [hacs/integration#2780]
### Web browser

Firefox/Chrome

### Web browser version

latest

### System Health details

Version 	core-2022.7.2
Installation Type 	Home Assistant OS
Development 	false
Supervisor 	true
Docker 	true
User 	root
Virtual Environment 	false
Python Version 	3.10.5
Operating System Family 	Linux
Operating System Version 	5.15.45
CPU Architecture 	x86_64
Timezone 	Europe/Budapest
Configuration Directory 	/config
Home Assistant Community Store
GitHub API 	ok
GitHub Content 	ok
GitHub Web 	ok
GitHub API Calls Remaining 	4889
Installed Version 	1.26.0
Stage 	running
Available Repositories 	1072
Downloaded Repositories 	14
Home Assistant Cloud
Logged In 	false
Reach Certificate Server 	ok
Reach Authentication Server 	ok
Reach Home Assistant Cloud 	ok
Home Assistant Supervisor
Host Operating System 	Home Assistant OS 8.2
Update Channel 	stable
Supervisor Version 	supervisor-2022.07.0
Agent Version 	1.2.1
Docker Version 	20.10.14
Disk Total 	30.8 GB
Disk Used 	10.0 GB
Healthy 	true
Supported 	true
Board 	ova
Supervisor API 	ok
Version API 	ok

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Title says it all. See attached picture.

### Reproduction steps

Tried delete cache/logout-login/ha restart. Nothing.

### Screenshots

![image](https://user-images.githubusercontent.com/3084630/178136456-f35e8c7f-8438-4b97-9335-842606309734.png)

### Javascript logs from your browser console

```text
empty
```

**Comment by ludeeus** [comment]
It's not missing, it's moved to inside each repository page.
