### ISSUE TITLE
Problem loading certain integrations since 2022.7 update (rollback does not fix)

### ISSUE THREAD

**Issue by roabyd** [hacs/integration#2791]
### System Health details

Version | core-2022.7.4
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.10.5
Operating System Family | Linux
Operating System Version | 5.15.32-v8
CPU Architecture | aarch64
Timezone | Australia/Brisbane
Configuration Directory | /config

Version	core-2022.7.4
Installation Type	Home Assistant OS
Development	false
Supervisor	true
Docker	true
User	root
Virtual Environment	false
Python Version	3.10.5
Operating System Family	Linux
Operating System Version	5.15.32-v8
CPU Architecture	aarch64
Timezone	Australia/Brisbane
Configuration Directory	/config
Home Assistant Community Store
GitHub API	ok
GitHub Content	ok
GitHub Web	**unreachable** – [more info](https://www.githubstatus.com/)
GitHub API Calls Remaining	4905
Installed Version	1.26.2
Stage	running
Available Repositories	1072
Downloaded Repositories	14
Home Assistant Cloud
Logged In	true
Subscription Expiration	July 23, 2022 at 10:00 AM
Relayer Connected	true
Remote Enabled	true
Remote Connected	true
Alexa Enabled	false
Google Enabled	true
Remote Server	ap-southeast-1-1.ui.nabu.casa
Reach Certificate Server	ok
Reach Authentication Server	ok
Reach Home Assistant Cloud	ok
Home Assistant Supervisor
Host Operating System	Home Assistant OS 8.2
Update Channel	stable
Supervisor Version	supervisor-2022.07.0
Agent Version	1.2.1
Docker Version	20.10.14
Disk Total	111.1 GB
Disk Used	8.6 GB
Healthy	true
Supported	true
Board	rpi4-64
Supervisor API	ok
Version API	**unreachable**
Installed Add-ons	ESPHome (2022.6.2), Home Assistant Google Drive Backup (0.108.2), MariaDB (2.5.0), Mosquitto broker (6.1.2), Samba share (10.0.0), Studio Code Server (5.1.2), Terminal & SSH (9.6.0), Zigbee2MQTT (1.26.0-1)
Dashboards
Dashboards	1
Resources	7
Views	5
Mode	storage
Recorder
Oldest Run Start Time	July 6, 2022 at 1:55 AM
Current Run Start Time	July 15, 2022 at 10:06 AM
Estimated Database Size (MiB)	172.41 MiB
Database Engine	mysql
Database Version	10.6.8
Spotify
Spotify API endpoint reachable	ok

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Since updating to 2022.7.* I am having problems with certain HACS integrations. This first happened when updating from 2022.6.7 to 2022.7.0, and I noticed that a couple of my HACS integrations stopped working due to the python 3.10 update. Once I realised this was the issue I tried to roll back to a backup point where everything was working, however once that restore was complete, I was still recieving errors for the same integrations.

Since that time, these integrations have been updated to support Python 3.10, and I have updated those and again updated HA core in hopes that all would have been fixed, however I have still been getting the same error:
![image](https://user-images.githubusercontent.com/55369460/179122088-02b7d84c-ce62-4cb6-92c3-be6be284078a.png)

If I check the system logs I see the following:
![image](https://user-images.githubusercontent.com/55369460/179123594-03ddf61e-4fac-4958-a564-50b0c8a0c39d.png)

I have tried removing the integrations, reintstalling a bunch of times, countless restarts through the UI, via "ha core restart" and "ha core restart," deleteing and downloading the hacs folder, deleteing and re downloading the individual integrations folders, I'm running out of ideas. I have even done 2 fresh installs on my ssd (using rpi4 8GB +SSD) and restored a known working backup, and the issue still persists! 

The most painful thing, is sometimes, some combination of the above steps seems to resolve the issue, however I have not been able to find a pattern on something repeatable to fix the issue. Each time I think I have finally fixed the issue, the next time a ha core update comes out, I do a full backup and install, and without fail this error comes back. Again if I roll back, it does not fix the issue

### Reproduction steps

1. Update Home Assistant Core to any 2022.7.* version
2. Once HA comes back up the error is there
3. Trying to restore a previously working backup does not fix the issue

### Debug logs

```text
Logs too long to add to issue, I have copied the log file into the diagnostic dump section below
```

### Diagnostics dump

[config_entry-hacs-d68630f5f8f0e9098c3e8b618f239253.json.txt](https://github.com/hacs/integration/files/9116755/config_entry-hacs-d68630f5f8f0e9098c3e8b618f239253.json.txt)
[homeassistant-logs.txt](https://github.com/hacs/integration/files/9116783/homeassistant-logs.txt)

**Comment by DavidFW1960** [comment]
This is nothing to do with HACS. You need to raise an issue with the individual integrations

**Comment by roabyd** [comment]
I have done some further digging to find the following:

- The problem appears to stem from the ha core update or restore functionality. From what I understand, because I am running Home Assistant OS, with each core update the homeassistant container is cleared and rebuilt, and in the process of doing so, the 'required' files from the manifest.json within each custom_component are cleared, and re downloaded during the startup (am I correct in assuming this also happens after a restore?)
- The required files do exist, however HA can't seem to download them (tries 4 times and then gives up) "**Unable to install package reolink==0.0.61: WARNING: Retrying**"
- reports the failure - "**ERROR: Could not find a version that satisfies the requirement reolink==0.0.61 (from versions: none)
ERROR: No matching distribution found for reolink==0.0.61**"
- Then at some random point in the future the download is successful, and then everything works again.
- This is happening for all of the listed integrations listed in the description, however the only thing they have in common is they were the most recently installed. Each component has been confirmed (be me and others) as working with the new Python update, so that is not the problem

So why would some files and not others not be downloadable? Apparently if i try to access the container and use pip to install the files manually, they will be wiped with the next update anyway, so how can I fix this permanently?

**Comment by ludeeus** [comment]
HACS do not manage requirements.
