### ISSUE TITLE
Can’t start discussion

### ISSUE THREAD

**Issue by timia2109** [hacs/integration#2799]
### System Health details

Not required

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Hi,
I can’t open a discussion to submit my feature request. 

On the GitHub websites nothing happens when I click on new. 
on the GitHub app, I got a “No permission” error (see attachment)

### Reproduction steps

1. Start a discussion as a non project member

![873ACED8-5020-4A9C-A3D7-ABCA72D0D0FE](https://user-images.githubusercontent.com/6303931/180448262-e3e41e95-c9d0-4f44-92fc-9dbcd58f5743.jpeg)

### Debug logs

```text
null
```

**Comment by ludeeus** [comment]
It's disabled on purpose.
Github currently does not support discussion templates, and copy+paste from the instructions was never done.
So until I find a suitable solution it will remain disabled.

**Comment by timia2109** [comment]
Confusing documentation 🌈
