### ISSUE TITLE
Themes Are Missing

### ISSUE THREAD

**Issue by spencerthayer** [hacs/integration#2800]
### Web browser

Chrome

### Web browser version

Version 103.0.5060.134 (Official Build) (x86_64)

### System Health details

version | core-2022.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.32-v8
arch | aarch64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4970
Installed Version | 1.26.2
Stage | running
Available Repositories | 1073
Downloaded Repositories | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 2, 2022 at 5:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-west-2-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.07.0
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 118.5 GB
disk_used | 10.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS (0.1.64), Home Assistant Google Drive Backup (0.108.2), Node-RED (12.0.2), AdGuard Home (4.6.0), Tailscale (0.7.0), Studio Code Server (5.1.2), Traccar (0.17.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 18
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 13, 2022 at 6:44 PM
-- | --
current_recorder_run | July 22, 2022 at 2:41 PM
estimated_db_size | 189.88 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Themes are missing.

### Reproduction steps

Going to HACS looking for a theme.

### Screenshots

<img width="899" alt="Screen Shot 2022-07-23 at 11 57 08 AM" src="https://user-images.githubusercontent.com/1019815/180619277-23adad9a-ca98-426a-a119-60632bc2dab1.png">

### Javascript logs from your browser console

```text
Nothing.
```

**Comment by ludeeus** [comment]
Then you have not downloaded anyø.
