### ISSUE TITLE
I can no longer return to HACS search results after viewing a repo

### ISSUE THREAD

**Issue by markmonroy** [hacs/integration#2807]
### Web browser

Safari

### Web browser version

15.6 (17613.3.9.1.5)

## System Health

version | core-2022.7.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.55
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4813
Installed Version | 1.26.2
Stage | running
Available Repositories | 1075
Downloaded Repositories | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.07.0
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 228.5 GB
disk_used | 41.5 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), SSH & Web Terminal (11.0.2), Portainer (2.0.0), InfluxDB (4.5.0), Grafana (7.6.0), Mosquitto broker (6.1.2), Studio Code Server (5.2.0), Glances (0.16.0), Nginx Proxy Manager (0.12.1), MariaDB (2.5.1), Orange and Rockland Utility to MQTT Bridge (0.4.0), Home Assistant Google Drive Backup (0.108.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 20
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 22, 2022, 9:57 AM
-- | --
current_recorder_run | July 31, 2022, 10:11 AM
estimated_db_size | 413.11 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Hi,

In earlier versions of HACS, I was able to browse available repositories like this:

1. Click the + button in the lower right (currently labeled Explore & Download Repositories)
2. Change sorting method and/or filter available repositories by typing in the search bar
3. Click on a repository to view its details
4. Click "X" in the corner of the details window to return to my search results.

In fact, this interface is still shown in the screenshot on https://github.com/hacs/integration.

With the current interface, however, the X in the corner has been replaced by a back arrow, and when I click it, it does not return to my search results. Instead it returns to my repos. If I click "Explore & Download Repositories," my previous text filter is active, but I've lost my place in the results (it's back at the top) and the sorting defaults to "Stars" regardless of how I had it sorted previously.

### Reproduction steps

1. Open HACS from the sidebar
2. Click "Explore & Download Repositories"
3. Change "Sort" from "Stars" to "Last Updated" or "Name"
4. Click on a repo to view its details
5. Click the back arrow in the upper left. At this point I'd like to see the old behavior where it returns to my search results rather than my installed repos
6. Click "Explore & Download Repositories" again. Search results have been reset to default, with the exception of it retaining any search text I may have entered.

### Screenshots

![mm_hacs_report](https://user-images.githubusercontent.com/32033503/182040702-44ee7b54-c71a-4cde-a9ca-c84d17ec5e6e.gif)

### Javascript logs from your browser console

```text
No logs generated while browsing HACS.
```

**Comment by ludeeus** [comment]
Before it was a dialog on top of a dialog.
Now it’s a dedicated page.

**Comment by markmonroy** [comment]
That's correct. So this is a feature request to please find some way to return to previous search results when clicking the back arrow. Thanks.
