### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by edsmith323** [hacs/integration#2813]
### System Health details

Home Assistant 2022.8.1
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220802.0 - latest

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I've had HACS installed previously, but since HA version 2022.7.7 it disappeared from the lefthand list.

I cleared the browser cache, but this made no difference. I followed the steps to uninstall, and reinstall including revoking oauth access through GitHub.
Ive tried to reinstall, but once installed I check the integration and i get the message failed to setup check logs

[HA debug log.docx](https://github.com/hacs/integration/files/9271296/HA.debug.log.docx)
.

### Reproduction steps

1. install HACS
2. reboot HA instance
3. check inegrations
...

### Debug logs

```text
Log attached to comments section, it was too long to paste here.
```

### Diagnostics dump

The option to download diagnostics is not available, possibly as the integration has failed to setup.

**Comment by ludeeus** [comment]
Your `/config/.storage/hacs.repositories` file has been corrupted, restore it from a backup.
