### ISSUE TITLE
Error “Custom element doesn’t exist: (...)” on older versions of iOS

### ISSUE THREAD

**Issue by A-E-M-Wiz** [hacs/integration#2814]
### Web browser

Safari and HA App

### Web browser version

Safari as well as in Home Assistant app v 2022.3, running on IOS 12.5.4.

## UA Info on browser

**UA Info Safari:** Mozilla/5.0 (iPad; CPU OS 12_5_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1

## System Health

version | core-2022.7.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.32-v8
arch | aarch64
timezone | UTC
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4910
Installed Version | 1.26.2
Stage | running
Available Repositories | 1140
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.07.0
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 14.1 GB
disk_used | 3.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.0), File editor (5.3.3), Duck DNS (1.15.0), SQLite Web (3.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 3
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 5, 2022 at 9:38 PM
-- | --
current_recorder_run | August 6, 2022 at 2:34 AM
estimated_db_size | 12.12 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The card cannot render on older versions of the iPad, and returns error “Custom element doesn’t exist: (..name-of-card..)”. The card works on both PC and Android, so the configuration of the card is correct.

This issue is observed several times:
https://community.home-assistant.io/t/custom-cards-not-working/189629

### Reproduction steps

1. Install any lovelave card through HACS
2. Add it to a dashboard
3. Verify the configuration of the card is valid on a modern PC and looks as expected.
4. Use an old iPad (I have verfied using iPad Air 1st gen)
5. Use either Safari, Chrome or the HA App: The card will fail with error code _Custom element doesn’t exist_

Setup
iPad Air (1st gen) running IOS 12.5.4.
Tested and failed on Chrome v 87.0.4280.77, Safari as well as in Home Assistant app v 2022.3.

### Screenshots

Issue on iPad:
![image](https://user-images.githubusercontent.com/11346733/183261837-4e6e2ebe-98ab-4b05-9e44-9df395c3c6c0.png)

Working setup on PC, Android and newer versions of IOS
![image](https://user-images.githubusercontent.com/11346733/183261867-c542a497-4091-4ad0-8857-8266adffee1a.png)

### Javascript logs from your browser console

```text
n/a
```

### Diagnostics dump

[config_entry-hacs-ffa2af505e221b366643611ae8904af5.json.txt](https://github.com/hacs/integration/files/9275596/config_entry-hacs-ffa2af505e221b366643611ae8904af5.json.txt)

**Comment by ludeeus** [comment]
Report that to the author of the card(s)
