### ISSUE TITLE
https://get.hacs.xyz gives a 503 service unavailable

### ISSUE THREAD

**Issue by brandonmeredyk** [hacs/integration#2820]
### Describe the issue

https://get.hacs.xyz gives a 503 service unavailable

**Comment by ludeeus** [comment]
Maybe you are blocked by cloudflare or github had issues when you tried.

<https://hacs.xyz/docs/setup/download#troubleshooting>
Use `https://raw.githubusercontent.com/hacs/get/main/get` instead
