### ISSUE TITLE
"Add" button in HACS "Custom repositories" is greyed out and does not allow adding new integrations

### ISSUE THREAD

**Issue by philjmaier** [hacs/integration#2825]
### Web browser

Safari

### Web browser version

15.5 (15613.2.7.1.9, 15613)

## System Information

version | core-2022.8.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.32-v8
arch | aarch64
timezone | America/Toronto
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4961
Installed Version | 1.26.2
Stage | running
Available Repositories | 1140
Downloaded Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.08.3
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 111.1 GB
disk_used | 7.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.2.1), Grafana (7.6.0), ESPHome (2022.6.3), MariaDB (2.5.1), InfluxDB (4.5.0), SSH & Web Terminal (12.0.1), File editor (5.3.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 11, 2022, 5:08 PM
-- | --
current_recorder_run | August 11, 2022, 5:22 PM
estimated_db_size | 6.38 MiB
database_engine | mysql
database_version | 10.6.8

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

"Add" button in HACS "Custom repositories" is greyed out and does not allow adding new integrations

### Reproduction steps

1. HACS
2. Integrations
3. 3 dots in upper right
4. Custom repositories

### Screenshots

![Screen Shot 2022-08-11 at 5 37 29 PM](https://user-images.githubusercontent.com/55792472/184246844-e72c92f9-feb3-4ff1-b5f7-8fd1dbc24459.png)

### Javascript logs from your browser console

```text
Don't know where to get this..
```

### Diagnostics dump

[config_entry-hacs-85edfccf30e2f1799ce2583b8cc21668.json.txt](https://github.com/hacs/integration/files/9312284/config_entry-hacs-85edfccf30e2f1799ce2583b8cc21668.json.txt)

**Comment by ludeeus** [comment]
You are missing the input fields.
![image](https://user-images.githubusercontent.com/15093472/184318069-a9489ba6-6ea1-494b-8c8f-742812f30052.png)

Clear browser cache or try a different browser
