### ISSUE TITLE
Config option not appearing after installing Deebot addin

### ISSUE THREAD

**Issue by ctaggmk** [hacs/integration#2827]
### Web browser

Chrome

### Web browser version

Version 104.0.5112.79 (Official Build) (x86_64)

### System Health details

I can't find this in the HACS GUI any more! 

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

HACS is not showing any buttons for the Deebot integration. I found via a search and have downloaded the integration. Teh directory has successfully been created. 

root@photon-machine [ /usr/homeassist/custom_components ]# ls -al
total 20
drwxr-xr-x  5 root root 4096 Aug 15 14:21 .
drwxr-x--- 10 root root 4096 Aug 15 14:22 ..
drwxr-xr-x  3 root root 4096 Aug 15 14:21 deebot
drwxr-xr-x  9 root root 4096 Aug 15 13:11 hacs
drwxr-xr-x  3 root root 4096 Aug 14 15:03 reolink_rest

But there is never a Configure option, which is what should pop up next according to the Documentation of the integration. I then restarted HA using the System/Restart option. Still no configure option but red banner has gone from HACS page. 

I've cleared browser cache. I've tried Safari and Firefox. I've restarted HA multiple times. Nothing seems to enable any buttons or menu options from the "double dots"
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/66094563/184657594-379a8785-5ccd-49c4-8413-d6a4a089dc3d.png">

### Reproduction steps

1. find the Deebot 4 integration in repository
2. Download via button in bottom right of documentation page
3. restart HA
4. go back to HACS and see if there is a Configure option anywhere
5. 
...

### Screenshots

done above in the descriptions

### Javascript logs from your browser console

```text
Loading module from “http://192.168.50.114:8123/local/community/tesla-style-solar-power-card/tesla-style-solar-power-card.js” was blocked because of a disallowed MIME type (“text/plain”).
lovelace
Loading failed for the module with source “http://192.168.50.114:8123/local/community/tesla-style-solar-power-card/tesla-style-solar-power-card.js”. lovelace:1:1
Uncaught (in promise) http://192.168.50.114:8123/local/community/tesla-style-solar-power-card/tesla-style-solar-power-card.js
Loading module from “http://192.168.50.114:8123/local/community/button-card/button-card.js” was blocked because of a disallowed MIME type (“text/plain”).
lovelace
Loading failed for the module with source “http://192.168.50.114:8123/local/community/button-card/button-card.js”. lovelace:1:1
Uncaught (in promise) http://192.168.50.114:8123/local/community/button-card/button-card.js
Loading module from “http://192.168.50.114:8123/localc/community/vacuum-card/vacuum-card.js” was blocked because of a disallowed MIME type (“text/plain”).
lovelace
Loading failed for the module with source “http://192.168.50.114:8123/localc/community/vacuum-card/vacuum-card.js”. lovelace:1:1
Uncaught (in promise) http://192.168.50.114:8123/localc/community/vacuum-card/vacuum-card.js
 VACUUM-CARD  2.6.2 vacuum-card.js:4:17736
 HISTORY-EXPLORER-CARD  Version 1.0.23 history-explorer-card.js:68:887
The resource at “http://192.168.50.114:8123/static/fonts/roboto/Roboto-Regular.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. integrations
The resource at “http://192.168.50.114:8123/static/fonts/roboto/Roboto-Medium.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. integrations
Firefox can’t establish a connection to the server at ws://192.168.50.114:8123/api/websocket. 5 core.f2e094cd.js:1:6225
Uncaught (in promise) 
Object { code: "unknown_command", message: "Unknown command." }
5
Source map error: Error: request failed with status 404
Resource URL: null
Source Map URL: mdc.chips.min.css.map
```

### Diagnostics dump

{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2022.8.4",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "5.10.78-4.ph4-esx",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.26.2",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "deebot": {
      "version": "1.4.1",
      "requirements": [
        "deebot-client==1.5.1",
        "numpy>=1.21.2"
      ]
    },
    "reolink_rest": {
      "version": "0.5.5",
      "requirements": [
        "async-reolink.rest==0.5.8"
      ]
    }
  },
  "integration_manifest": {
    "codeowners": [
      "@ludeeus"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "websocket_api",
      "frontend",
      "persistent_notification",
      "lovelace"
    ],
    "documentation": "https://hacs.xyz/docs/configuration/start",
    "domain": "hacs",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/hacs/integration/issues",
    "name": "HACS",
    "requirements": [
      "aiogithubapi>=22.2.4"
    ],
    "version": "1.26.2",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "090978c3492a9000ee9c9d102f76370e",
      "version": 1,
      "domain": "hacs",
      "title": "",
      "data": {
        "token": "**REDACTED**"
      },
      "options": {
        "sidepanel_title": "HACS",
        "sidepanel_icon": "hacs:hacs",
        "release_limit": 5,
        "country": "ALL",
        "appdaemon": true,
        "netdaemon": true,
        "debug": true,
        "experimental": false
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "hacs": {
      "stage": "running",
      "version": "1.26.2",
      "disabled_reason": null,
      "new": false,
      "startup": false,
      "categories": [
        "plugin",
        "theme",
        "netdaemon",
        "appdaemon",
        "integration"
      ],
      "renamed_repositories": {
        "PepegaBruh/CryptoTracker": "BigNocciolino/CryptoTracker",
        "9a4gl/hass-peltec": "9a4gl/hass-centrometal-boiler",
        "78wesley/Darkish-Theme": "78wesley/Home-Assistant-Darkish-Theme",
        "KartoffelToby/ai_thermostat": "KartoffelToby/better_thermostat",
        "nbogojevic/homeassistant-midea-dehumidifier-lan": "nbogojevic/homeassistant-midea-air-appliances-lan",
        "nikrolls/homeassistant-goldair-climate": "nicole-ashley/homeassistant-goldair-climate",
        "ulic75/power-distribution-card": "ulic75/power-flow-card",
        "wills106/homsassistant-solax-modbus": "wills106/homeassistant-solax-modbus",
        "dmitry-k/yandex_smart_home": "dext0r/yandex_smart_home",
        "uvjustin/alarmdotcom": "pyalarmdotcom/alarmdotcom",
        "wernerhp/appdaemon_aqara_motion_sensors": "wernerhp/ha.appdaemon.aqara_motion_sensors",
        "wernerhp/appdaemon_wasp": "wernerhp/ha.appdaemon.wasp",
        "wernerhp/ha_integration_load_shedding": "wernerhp/ha.integration.load_shedding"
      },
      "archived_repositories": [
        "estevez-dev/extended-banner-card",
        "ppanagiotis/pymusiccast",
        "Kraineff/philips-airpurifier",
        "jensweimann/awb",
        "briis/smartweather",
        "KoljaWindeler/kaco",
        "dr1rrb/ha-twinkly",
        "heinoldenhuis/home_assistant_omnik_solar",
        "DSorlov/hasl-platform",
        "iantrich/aftership-card",
        "And3rsL/Deebot-for-Home-Assistant",
        "nagyrobi/home-assistant-custom-components-pfsense-gateways",
        "pippyn/Home-Assistant-Sensor-Groningen-Afvalwijzer",
        "custom-cards/upcoming-media-card",
        "maykar/lovelace-swipe-navigation",
        "maykar/kiosk-mode",
        "custom-components/sensor.plex_recently_added",
        "custom-components/sensor.radarr_upcoming_media",
        "custom-components/sensor.sonarr_upcoming_media",
        "maykar/plex_assistant",
        "custom-components/wienerlinien",
        "GeorgeSG/lovelace-folder-card",
        "KTibow/lovelace-dark-soft-ui-theme",
        "KTibow/lovelace-light-soft-ui-theme",
        "eavanvalkenburg/sia",
        "Cyr-ius/hass-hue-service-advanced",
        "Cyr-ius/hass-cozytouch",
        "georgezhao2010/climate_ewelink"
      ],
      "ignored_repositories": [],
      "lovelace_mode": "storage",
      "configuration": {
        "appdaemon": true,
        "country": "ALL",
        "debug": true,
        "dev": false,
        "experimental": false,
        "netdaemon": true,
        "python_script": false,
        "release_limit": 5,
        "theme": false
      }
    },
    "custom_repositories": [
      "GeorgeSG/lovelace-folder-card",
      "KTibow/lovelace-dark-soft-ui-theme",
      "KTibow/lovelace-light-soft-ui-theme",
      "custom-components/wienerlinien",
      "Cyr-ius/hass-hue-service-advanced",
      "Cyr-ius/hass-cozytouch",
      "eavanvalkenburg/sia",
      "georgezhao2010/climate_ewelink",
      "KoljaWindeler/kaco"
    ],
    "repositories": [
      {
        "data": {
          "archived": false,
          "authors": [
            "@ludeeus"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "main",
          "description": "HACS gives you a powerful UI to handle downloads of all your custom needs.",
          "domain": "hacs",
          "downloads": 81116,
          "etag_repository": "W/\"84897f9a95567aa22f834ff0cd928cb858c31a4dfb029f45ea06d310d7f2ffc5\"",
          "file_name": "",
          "first_install": false,
          "full_name": "hacs/integration",
          "hide": false,
          "has_issues": true,
          "id": "172733314",
          "installed_commit": "6dc933d",
          "installed_version": "1.26.2",
          "installed": true,
          "last_commit": "6dc933d",
          "last_updated": "2022-08-13T15:20:13Z",
          "last_version": "1.26.2",
          "manifest_name": "HACS",
          "new": false,
          "open_issues": 7,
          "published_tags": [
            "1.26.2",
            "1.26.1",
            "1.26.0",
            "1.25.5",
            "1.25.4"
          ],
          "pushed_at": "2022-08-13T15:20:13",
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 2816,
          "topics": [
            "community",
            "package-manager"
          ]
        },
        "integration_manifest": {
          "codeowners": [
            "@ludeeus"
          ],
          "config_flow": true,
          "dependencies": [
            "http",
            "websocket_api",
            "frontend",
            "persistent_notification",
            "lovelace"
          ],
          "documentation": "https://hacs.xyz/docs/configuration/start",
          "domain": "hacs",
          "iot_class": "cloud_polling",
          "issue_tracker": "https://github.com/hacs/integration/issues",
          "name": "HACS",
          "requirements": [
            "aiogithubapi>=22.2.4"
          ],
          "version": "0.0.0"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "hacs.zip",
          "hacs": "0.19.0",
          "hide_default_branch": true,
          "homeassistant": "2022.4.0",
          "manifest": {
            "name": "HACS",
            "zip_release": true,
            "hide_default_branch": true,
            "homeassistant": "2022.4.0",
            "hacs": "0.19.0",
            "filename": "hacs.zip"
          },
          "name": "HACS",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": "1.26.2",
        "paths": {
          "localpath": "/config/custom_components/hacs",
          "local": "/config/custom_components/hacs",
          "remote": "custom_components/hacs"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "config_flow": false,
          "default_branch": "master",
          "description": "Vacuum cleaner card for Home Assistant Lovelace UI",
          "domain": "",
          "downloads": 17014,
          "etag_repository": "W/\"0b857f71ab00f808f3fbe9853501b63cf335bd74702cad5be7269b250dc8e5ae\"",
          "file_name": "vacuum-card.js",
          "first_install": false,
          "full_name": "denysdovhan/vacuum-card",
          "hide": false,
          "has_issues": true,
          "id": "261291295",
          "installed_commit": "77417d3",
          "installed_version": "v2.6.3",
          "installed": true,
          "last_commit": "6483109",
          "last_updated": "2022-08-08T11:05:58Z",
          "last_version": "v2.6.3",
          "manifest_name": null,
          "new": false,
          "open_issues": 44,
          "published_tags": [
            "v2.6.3",
            "v2.6.2",
            "v2.6.1",
            "v2.6.0",
            "v2.5.3"
          ],
          "pushed_at": "2022-08-08T11:05:58",
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 588,
          "topics": [
            "robot-vacuum",
            "vacuum"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "vacuum-card.js",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": null,
          "manifest": {
            "name": "Vacuum Card",
            "render_readme": true,
            "filename": "vacuum-card.js"
          },
          "name": "Vacuum Card",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": "v2.6.3",
        "paths": {
          "localpath": "/config/www/community/vacuum-card",
          "local": "/config/www/community/vacuum-card",
          "remote": "release"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@DeebotUniverse",
            "@edenhaus"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "dev",
          "description": "Home Assistant integration for deebot vacuums",
          "domain": "deebot",
          "downloads": 3422,
          "etag_repository": "W/\"597e64edc1059971d75f5a950c2f565e333214f7112433dd0af765b7f42969d2\"",
          "file_name": "",
          "first_install": false,
          "full_name": "DeebotUniverse/Deebot-4-Home-Assistant",
          "hide": false,
          "has_issues": true,
          "id": "422954081",
          "installed_commit": "f85fa94",
          "installed_version": "1.4.1",
          "installed": true,
          "last_commit": "f85fa94",
          "last_updated": "2022-08-15T11:46:13Z",
          "last_version": "1.4.1",
          "manifest_name": "Deebot 4 Home Assistant",
          "new": false,
          "open_issues": 15,
          "published_tags": [
            "1.4.1",
            "1.4.0",
            "1.3.2",
            "1.3.1",
            "1.3.0"
          ],
          "pushed_at": "2022-08-15T11:46:13",
          "releases": true,
          "selected_tag": null,
          "show_beta": true,
          "stargazers_count": 74,
          "topics": [
            "deebot",
            "ecovacs",
            "vacuum"
          ]
        },
        "integration_manifest": {
          "codeowners": [
            "@DeebotUniverse",
            "@edenhaus"
          ],
          "config_flow": true,
          "documentation": "https://deebot.readthedocs.io/integrations/home-assistant",
          "domain": "deebot",
          "iot_class": "cloud_polling",
          "issue_tracker": "https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues",
          "name": "Deebot 4 Home Assistant",
          "requirements": [
            "deebot-client==1.5.1",
            "numpy>=1.21.2"
          ],
          "version": "v0.0.0"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "deebot.zip",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2022.7.0b0",
          "manifest": {
            "filename": "deebot.zip",
            "homeassistant": "2022.7.0b0",
            "name": "Deebot 4 Home Assistant",
            "render_readme": true,
            "zip_release": true
          },
          "name": "Deebot 4 Home Assistant",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": true
        },
        "ref": "1.4.1",
        "paths": {
          "localpath": "/config/custom_components/deebot",
          "local": "/config/custom_components/deebot",
          "remote": "custom_components/deebot"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "config_flow": false,
          "default_branch": "main",
          "description": "A card for Home Assistant Lovelace for exploring the history of your entities interactively and in real time.",
          "domain": "",
          "downloads": 3365,
          "etag_repository": "W/\"681170fd288211939c8d6143ee383aa245131e66c3632f45b8193a967edae99d\"",
          "file_name": "history-explorer-card.js",
          "first_install": false,
          "full_name": "alexarch21/history-explorer-card",
          "hide": false,
          "has_issues": true,
          "id": "440374794",
          "installed_commit": "ee6f5f1",
          "installed_version": "v1.0.23",
          "installed": true,
          "last_commit": "ee6f5f1",
          "last_updated": "2022-07-18T11:39:49Z",
          "last_version": "v1.0.23",
          "manifest_name": null,
          "new": false,
          "open_issues": 10,
          "published_tags": [
            "v1.0.23",
            "v1.0.22",
            "v1.0.21",
            "v1.0.20",
            "v1.0.19"
          ],
          "pushed_at": "2022-07-18T11:39:49",
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 96,
          "topics": [
            "history"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "history-explorer-card.js",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": null,
          "manifest": {
            "name": "history-explorer-card",
            "filename": "history-explorer-card.js"
          },
          "name": "history-explorer-card",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": false
        },
        "ref": "v1.0.23",
        "paths": {
          "localpath": "/config/www/community/history-explorer-card",
          "local": "/config/www/community/history-explorer-card",
          "remote": "release"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "config_flow": false,
          "default_branch": "master",
          "description": "Home Assistant custom lovelace sonos card",
          "domain": "",
          "downloads": 1245,
          "etag_repository": "W/\"45742dff5c16314b09bcc7941cd7edf43e349fe15fb03f067f8d7cbec213bee4\"",
          "file_name": "custom-sonos-card.js",
          "first_install": false,
          "full_name": "johanfrick/custom-sonos-card",
          "hide": false,
          "has_issues": true,
          "id": "449416816",
          "installed_commit": "8364ff5",
          "installed_version": "v5.7.0",
          "installed": true,
          "last_commit": "8364ff5",
          "last_updated": "2022-08-09T20:44:59Z",
          "last_version": "v5.7.0",
          "manifest_name": null,
          "new": false,
          "open_issues": 3,
          "published_tags": [
            "v5.7.0",
            "v5.6.0",
            "v5.5.1",
            "v5.5.0",
            "v5.4.0"
          ],
          "pushed_at": "2022-08-09T20:44:59",
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 31,
          "topics": [
            "lovelace-custom-card",
            "media-player",
            "sonos"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "custom-sonos-card.js",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": null,
          "manifest": {
            "name": "Sonos Card",
            "render_readme": true,
            "filename": "custom-sonos-card.js"
          },
          "name": "Sonos Card",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": "v5.7.0",
        "paths": {
          "localpath": "/config/www/community/custom-sonos-card",
          "local": "/config/www/community/custom-sonos-card",
          "remote": "release"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@xannor"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "main",
          "description": "ReoLink REST/Web Camera Integration for Home Assistant",
          "domain": "reolink_rest",
          "downloads": 0,
          "etag_repository": "W/\"09582f3206d84a942c4e8118752f3cf35845978b3ec784333e5ca3300077867a\"",
          "file_name": "",
          "first_install": false,
          "full_name": "xannor/ha_reolink_rest",
          "hide": false,
          "has_issues": true,
          "id": "464303052",
          "installed_commit": "df148b5",
          "installed_version": null,
          "installed": true,
          "last_commit": "df148b5",
          "last_updated": "2022-07-27T19:37:02Z",
          "last_version": null,
          "manifest_name": "Reolink IP Device",
          "new": false,
          "open_issues": 3,
          "published_tags": [],
          "pushed_at": "2022-07-27T19:37:02",
          "releases": false,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 3,
          "topics": [
            "component"
          ]
        },
        "integration_manifest": {
          "domain": "reolink_rest",
          "name": "Reolink IP Device",
          "documentation": "https://github.com/xannor/ha_reolink_rest",
          "issue_tracker": "https://github.com/xannor/ha_reolink_rest/issues",
          "version": "0.5.5",
          "iot_class": "local_polling",
          "requirements": [
            "async-reolink.rest==0.5.8"
          ],
          "dependencies": [
            "camera"
          ],
          "after_dependencies": [
            "stream",
            "webhook",
            "reolink_discovery"
          ],
          "codeowners": [
            "@xannor"
          ],
          "config_flow": true
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2022.2.6",
          "manifest": {
            "name": "Reolink IP Devices",
            "homeassistant": "2022.2.6"
          },
          "name": "Reolink IP Devices",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": false
        },
        "ref": "main",
        "paths": {
          "localpath": "/config/custom_components/reolink_rest",
          "local": "/config/custom_components/reolink_rest",
          "remote": "custom_components/reolink_rest"
        }
      }
    ],
    "rate_limit": {
      "resources": {
        "core": {
          "limit": 5000,
          "used": 323,
          "remaining": 4677,
          "reset": 1660574470
        },
        "search": {
          "limit": 30,
          "used": 0,
          "remaining": 30,
          "reset": 1660574083
        },
        "graphql": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1660577623
        },
        "integration_manifest": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1660577623
        },
        "source_import": {
          "limit": 100,
          "used": 0,
          "remaining": 100,
          "reset": 1660574083
        },
        "code_scanning_upload": {
          "limit": 1000,
          "used": 0,
          "remaining": 1000,
          "reset": 1660577623
        },
        "actions_runner_registration": {
          "limit": 10000,
          "used": 0,
          "remaining": 10000,
          "reset": 1660577623
        },
        "scim": {
          "limit": 15000,
          "used": 0,
          "remaining": 15000,
          "reset": 1660577623
        }
      },
      "rate": {
        "limit": 5000,
        "used": 323,
        "remaining": 4677,
        "reset": 1660574470
      }
    }
  }
}

**Comment by ludeeus** [comment]
HACS has never done configuration for integrations (or other things)
