### ISSUE TITLE
HACS REFUSES to update "You are running version 1.14.0, version 1.27.1 is available"

### ISSUE THREAD

**Issue by drewmmiranda** [hacs/integration#2840]
### Web browser

Chrome

### Web browser version

104

## System Information

version | core-2022.8.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.32-v8
arch | aarch64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4933
Installed Version | 1.14.0
Stage | running
Available Repositories | 1105
Installed Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.08.5
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 28.6 GB
disk_used | 5.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.1), File editor (5.3.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 11, 2022 at 3:30 PM
-- | --
current_recorder_run | September 1, 2022 at 4:15 PM
estimated_db_size | 18.39 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Attempting to updated HACS is stuck in an infinite loop.

1. "You are running version 1.14.0, version 1.27.1 is available"
2. Click, Update
3. the UX appears to indicate its updating...
4. Pending restart
5. Restart
6. Back to step 1

Logs:

```
Giving up async_download_file(...) after 5 tries (TypeError: timeout() got an unexpected keyword argument 'loop')

Download was not completed
```

The pending restart card links to a page that doesn't exist: `/config/server_control` which truly appears to be `/hassio/system` now. (unrelated, read a long forum post about how HA removed the ability to reach this page via UX)

### Reproduction steps

1.
2.
3.
...

### Screenshots

![image](https://user-images.githubusercontent.com/12700525/188015481-58a17891-299f-44cc-9ad4-61688d14a22f.png)

### Javascript logs from your browser console

```text
n/a
```

**Comment by drewmmiranda** [comment]
Note that i couldn't submit this without checking ALL the checkboxes , but i clearly am not running the latest version because it refuses to update (and gives no indication as to why)

**Comment by ludeeus** [comment]
Downgrade Home Assistant or use download script from HACS website
