### ISSUE TITLE
Resource Links do not work

### ISSUE THREAD

**Issue by greghesp** [hacs/integration#2842]
### Describe the issue

The following resource links on the documentation lead to a 404:

[GitHub](https://hacs.xyz/github)
[Discord](https://hacs.xyz/discord)
[Code of Conduct](https://hacs.xyz/coc)

Assuming its because of [this commit](https://github.com/hacs/documentation/commit/0776f100791ba454d2c2e4a4a679429384993666#diff-a038096cbdea434999e1dce5ab497212f1fe18204dde1a027ce3bdd663261a2a)

**Comment by ludeeus** [comment]
It's because it was changed from netlify to GitHub pages, and GitHub does not support redirects

**Comment by ludeeus** [comment]
No, but I will not use any third party apps for this anymore anyway.

**Comment by r4v5** [comment]
They could be done as a client-side redirect using the docusaurus/client-side-redirects plugin the project uses, right? theoretically, adding those routes to [this list](https://github.com/hacs/documentation/blob/141a5cfd96f7853dec9970e117b6c5633d26ae6c/docusaurus.config.js#L96-L124) should do the redirection required.

**Comment by ludeeus** [comment]
It doesn't work for external links
