### ISSUE TITLE
The repository does not have issues enabled 

### ISSUE THREAD

**Issue by marcokreeft87** [hacs/integration#2843]
### Describe the issue

The action says: 
The repository does not have issues enabled 

But my repo cleary does have them enabled. As you can see here: https://github.com/marcokreeft87/room-card/issues

### Link to action run

https://github.com/marcokreeft87/room-card/actions/runs/2991193759

### Link to action configuration

https://github.com/marcokreeft87/room-card/blob/master/.github/workflows/tests.yml

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
Text was wrong, this is the one that failed: <https://hacs.xyz/docs/publish/include#check-images>

**Comment by marcokreeft87** [comment]
@ludeeus What do you mean?

**Comment by ludeeus** [comment]
Look at the linked commit.

**Comment by marcokreeft87** [comment]
Ah now I see! Ok thnx I can work with that :)
