### ISSUE TITLE
Description of custom brand icons repository shows broken images on right side of a table

### ISSUE THREAD

**Issue by Sholofly** [hacs/integration#2850]
### Web browser

Chrome, Firefox, Edge

### Web browser version

105.0.5195.102, 104.0.2, 105.0.1343.33

## System Information

version | core-2022.9.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.60
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.27.2
Stage | running
Available Repositories | 1117
Downloaded Repositories | 50

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 8 oktober 2022 om 02:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.5
-- | --
update_channel | beta
supervisor_version | supervisor-2022.09.0
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 62.3 GB
disk_used | 12.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), Mosquitto broker (6.1.3), MariaDB (2.5.1), AdGuard Home (4.7.3), Studio Code Server (5.3.0), SSH & Web Terminal (12.0.2), Vaultwarden (Bitwarden) (0.17.3), ESPHome (2022.8.3), Samba Backup (5.1.2), RTSPtoWeb - WebRTC (1.2.2), VLC (0.1.3), Nginx Proxy Manager (0.12.2), Dutch gas prices (2022.3.25.1), Shortumation (v0.7.6)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 39
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 13 september 2022 om 07:02
-- | --
current_recorder_run | 13 september 2022 om 09:02
estimated_db_size | 978.42 MiB
database_engine | mysql
database_version | 10.6.8

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

For the frontend repository 'Custom Brand Icons'  the repository description and the update card always show a table with  with the added icons. The update card has usually one column and the repository description two. In the repository description the example icon in the right column of this table, always show up as a broken image. In the update card all icons show up as a broken image.
In the src of the broken images the path is not complete but a relative path, however the readme of the repository on github all images contain a relative path.

I've posted [this issue on their repo](https://github.com/elax46/custom-brand-icons/issues/250#issuecomment-1245523090) too but the owner asked me to put it here.

### Reproduction steps

1. Open HACS
2. Show the repository information of Custom brand Icons

### Screenshots

![image](https://user-images.githubusercontent.com/901632/190097442-bba641fe-10af-4373-a56a-977e7063e03a.png)

### Javascript logs from your browser console

```text
CARD-MOD 3.1.5 IS INSTALLED
366862031:1 Mixed Content: The page at 'https://home.sholofly.nl/hacs/repository/366862031' was loaded over HTTPS, but requested an insecure image 'http://bytecrank.com/nastyox/reporoster/php/stargazersSVG.php?user=elax46&repo=custom-brand-icons'. This content should also be served over HTTPS.
366862031:1 Mixed Content: The page at 'https://home.sholofly.nl/hacs/repository/366862031' was loaded over HTTPS, but requested an insecure image 'http://bytecrank.com/nastyox/reporoster/php/stargazersSVG.php?user=elax46&repo=custom-brand-icons'. This content should also be served over HTTPS.
```

### Diagnostics dump

[config_entry-hacs-dc8ff2ea9bf16e6733c43cc264d82c16.json.txt](https://github.com/hacs/integration/files/9564181/config_entry-hacs-dc8ff2ea9bf16e6733c43cc264d82c16.json.txt)

**Comment by ludeeus** [comment]
The author needs to switch from relative to static URLs for them to ensure that the content properly works outside of github.com.
Nothing I can do about it.

**Comment by Sholofly** [comment]
Thanks for your reply @ludeeus!
