### ISSUE TITLE
Popup first, then load information

### ISSUE THREAD

**Issue by rirofal** [hacs/integration#2855]
### Web browser

Chrome

### Web browser version

105.0

### System Health details

N/A

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When the connection to GitHub is slow and you popup information on an updated integration the delay between the actual window popping up and the click is way to long.

My guess: the popup shows after GitHub info is loaded
If my guess is right, it would probably be better to popu first, show a spinner and then load the GitHub-info

### Reproduction steps

1. Download some large file with FTP or other lousy protocol that eats you bandwidth
2. Click on an update
...

### Screenshots

N/A

### Javascript logs from your browser console

```text
N/A
```

**Comment by rirofal** [comment]
> Popup?

The one when you click on one of the Updates...
In this case it takes about one second between the click on "Xiaomi Miot Auto" until the dialog is displayed (without me trying to download anything in the background).

![1](https://user-images.githubusercontent.com/3245006/191669892-aaa279ef-eb31-4632-ba20-69760cfc4949.png)

![2](https://user-images.githubusercontent.com/3245006/191669875-5b5bb354-5dda-455c-9f05-82ce2863e9af.png)

**Comment by rirofal** [comment]
Kind of hard to record... but I think you can see the time between the click and the dialogue.

![Demo](https://user-images.githubusercontent.com/3245006/191671542-93c33fff-ba40-498e-8728-b44f459a2080.gif)

**Comment by ludeeus** [comment]
Okey 👍 
This will not be fixed, that dialog and that listing of updates will be removed.

https://hacs.xyz/docs/entities/update_entities are the future
