### ISSUE TITLE
Mac OS Companion app HACS odd labels

### ISSUE THREAD

**Issue by SideTrackedResearch** [hacs/integration#2857]
### Web browser

N/A

### Web browser version

N/A

## System Information

version | core-2022.9.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.61-v8
arch | aarch64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.27.2
Stage | running
Available Repositories | 1188
Downloaded Repositories | 41

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.0
-- | --
update_channel | stable
supervisor_version | supervisor-2022.09.1
agent_version | 1.3.0
docker_version | 20.10.17
disk_total | 457.7 GB
disk_used | 7.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.1), File editor (5.4.1), ESPHome (2022.9.1), Z-Wave JS (0.1.72)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 31
views | 29
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 14, 2022 at 2:43 PM
-- | --
current_recorder_run | September 24, 2022 at 1:23 PM
estimated_db_size | 253.81 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Using the Mac OS companion app, the friendly names of the integrations, actions, buttons do not show.  Instead I see the labels of the buttons?
Instead of:

**Integrations**:
This is where you find custom integrations (custom_components)

I see this:

**sections.integrations.title**
sections.integrations.descriptions

This shows up on the first page, each section page, and the integration/frontend pages.
I do not have this problem in Firefox.

### Reproduction steps

1. Open the Mac OS companion app
2. Click on HACS
3.
...

### Screenshots

![image](https://user-images.githubusercontent.com/39178905/192113864-e148e8fd-74dd-4f1f-83dc-b102c1bc0e57.png)
![image](https://user-images.githubusercontent.com/39178905/192113907-7c3de425-6876-46b7-959f-3e3f77bf16fc.png)
![Screen Shot 2022-09-24 at 1 55 13 PM](https://user-images.githubusercontent.com/39178905/192114420-7d9f6028-b956-4fce-a5d1-351d8d415f9a.png)

### Javascript logs from your browser console

```text
N/A
```

### Diagnostics dump

[config_entry-hacs-1c715b6a55e4aaad7ad1da87847f7a5b.json.txt](https://github.com/hacs/integration/files/9639393/config_entry-hacs-1c715b6a55e4aaad7ad1da87847f7a5b.json.txt)

**Comment by ludeeus** [comment]
Clear cache.

**Comment by SideTrackedResearch** [comment]
Refreshed frontend cache in HA Companion app, restarted app, and same issue

**Comment by ludeeus** [comment]
What OS/safari version is it?

**Comment by SideTrackedResearch** [comment]
Mac OSX 10.15.7
Safari 15.6.1
Home Assistant Companion 2022.387
Home Assistant 2022.9.6
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2
HACS  1.27.2
    - Frontend version 20220906112053

**Comment by ludeeus** [comment]
OSX 10.15.7 came out over 2 years ago,  update it.

As this is not reproducible with newer versions I'm going to close it

**Comment by SideTrackedResearch** [comment]
I am unable to upgrade this computer.  So I am stuck with this issue?

**Comment by ludeeus** [comment]
You can update or use a different browser.
