### ISSUE TITLE
Feature Request: Show Update Counter in the Left HACS Menu

### ISSUE THREAD

**Issue by iosoft** [hacs/integration#2865]
### Web browser

Google Chrome

### Web browser version

Latest

### System Health details

NA

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When any component installed using HACS, if there is one or more updates, pls show Bubble Counter in the Left Menu HACS menu item.

### Reproduction steps

When any component installed using HACS, if there is one or more updates, pls show Bubble Counter in the Left Menu HACS menu item.

### Screenshots

![hacs-update-1](https://user-images.githubusercontent.com/349968/193080084-8f165f30-31c8-4fce-a772-7b2d3ae3561d.png)

### Javascript logs from your browser console

```text
NA
```

**Comment by ludeeus** [comment]
Can’t be done

**Comment by iosoft** [comment]
> Can’t be done

why?!
I mean, it can show HACS Update count in the Dashboard!
Then, why not in the menu like Home Assistant itself shows update count in the menu!

![image](https://user-images.githubusercontent.com/349968/193081481-65971d12-7b9b-403d-bf15-e35727ac48f3.png)

**Comment by ludeeus** [comment]
Because Home Assistant does not allow panels to add it.
That part is outside of custom panels control.

**Comment by iosoft** [comment]
Oh ok 😔
