### ISSUE TITLE
FAQ is empty; could answer "What is available with HACS?"

### ISSUE THREAD

**Issue by mjray** [hacs/integration#2866]
### Describe the issue

https://hacs.xyz/docs/faq/ looks like an empty page.

The most frequently-asked question may be "what is available with HACS?" and I didn't yet find an answer on the website. I don't know the answer yet, so can't suggest a patch.

**Comment by ludeeus** [comment]
I will not add that back, companies threatens legal actions when it was there.

**Comment by mjray** [comment]
What legal action was threatened? I struggle to see how any simple answer could upset any company, except possibly Nabu Casa.

Even just a simple description of how HACS finds things to show would help avoid the need for ordinary users to go digging in the code or searching various forum discussions to figure out what the heck HACS might do for them.

**Comment by ludeeus** [comment]
The company claimed improper use of trademarks (showing their name basically), and while I do not believe that to be the case, I will not waste my time fighting it.

**Comment by mjray** [comment]
Well, that sucks and I'm not sure they've any legs to stand on (it would be honest use of a trademark, which is not a right that can be restricted in any jurisdiction I've seen yet), but I can understand you not wanting to waste time fighting a nuisance claim.

Even so, isn't there some answer to this most-frequently-asked question without mentioning a trademark? Like explain how HACS decides what to show in the store. Then potential users could maybe figure out what to search for.

**Comment by ludeeus** [comment]
HACS does not decide to show anything.
The authors of the repositories request their repository to be shown.

**Comment by mjray** [comment]
Cool. You see, there's an answer. I now know more than I did before.

Obvious next question: what do authors do to request that?

**Comment by ludeeus** [comment]
<https://hacs.xyz/docs/publish/start>
<https://hacs.xyz/docs/publish/include>
