### ISSUE TITLE
7z instead of unzip - Unable to install on Docker on Synology NAS - Integration not showing up in list

### ISSUE THREAD

**Issue by robot-army** [hacs/integration#2871]
## System Information

version | core-2022.10.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 3.10.105
arch | x86_64
timezone | America/Vancouver
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 6, 2022 at 5:03 AM
-- | --
current_recorder_run | October 5, 2022 at 11:02 PM
estimated_db_size | 0.29 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I'm not able to find the HACS integration in the list of integrations in the Home Assistant web UI. 

I'm running in a HA docker container on a Synology NAS after following the instructions here: https://www.home-assistant.io/installation/alternative/#synology-nas

I've installed HACS following the steps here: https://hacs.xyz/docs/setup/download/ with a modification to the script to replace unzip with 7z (per instructions here: https://www.reddit.com/user/j9111/ ). 

Those instructions were wrong, and I ended up unzipping it manually and now I can find the integration. 

The installation script could fail over to 7z if it doesn't find unzip, as it appears to be the utility available on this NAS. 

The installation script could also check for the existence of the files at the end of the process, to be sure that the thing actually worked?

### Reproduction steps

1. Try to run the installation script on a system without unzip
2. Try to find the integration in the list in the HA web UI and fail. 
3.
...

### Debug logs

```text
Github says I can't put it here 'cos it exceeds 65535 characters. I'll attach a file instead.
```

**Comment by robot-army** [comment]
[home-assistant.log](https://github.com/hacs/integration/files/9721841/home-assistant.log)

**Comment by ludeeus** [comment]
For container installation, you have 2 options host/container.
This definitely works inside the container <https://hacs.xyz/docs/setup/download>.

**Comment by robot-army** [comment]
Weird, I'm sure I tried from inside the container as well, but maybe not! Looking now, unzip is provided by busybox inside the container, so it would have worked! 

Thanks!
