### ISSUE TITLE
Screenshots not up to date for core-2022.10.0

### ISSUE THREAD

**Issue by robot-army** [hacs/integration#2872]
### Describe the issue

The screenshots here https://hacs.xyz/docs/configuration/options don't look like my web UI, and the instructions don't match up, leaving me guessing. 

I have to click 'settings' not 'configuration', then 'devices and services', then 'configure' to get the window that's presented. 

### Screenshots

![image](https://user-images.githubusercontent.com/4554056/194232369-b246d54d-9b60-4603-a9ce-bc557f8461a5.png)

**Comment by ludeeus** [comment]
The instructions match, they do not say any of them.
Use the my link and it takes you there every time no matter how much it changes
