### ISSUE TITLE
Github OAUTH link not described in sufficient detail. 

### ISSUE THREAD

**Issue by robot-army** [hacs/integration#2873]
### Describe the issue

During the configuration steps here: https://hacs.xyz/docs/configuration/basic - my github accont and HACS are linked. Why? What's this for? 

A bit more clarity here would be helpful.

**Comment by ludeeus** [comment]
<https://hacs.xyz/docs/faq/github_account>

**Comment by robot-army** [comment]
Ahh great, thanks. Maybe a link in the box that asks for this would make it more obvious, I missed it in the FAQ (oops!)
