### ISSUE TITLE
no custom repositories can be added

### ISSUE THREAD

**Issue by Ludy87** [hacs/integration#2880]
### Web browser

Chrome

### Web browser version

105

## System Information

version | core-2022.10.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.67
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4771
Installed Version | 1.28.0
Stage | running
Available Repositories | 1128
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.0
-- | --
update_channel | stable
supervisor_version | supervisor-2022.09.1
agent_version | 1.3.0
docker_version | 20.10.17
disk_total | 30.8 GB
disk_used | 16.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.4.1), Terminal & SSH (9.6.1), Studio Code Server (5.4.0), Grafana (8.0.2), InfluxDB (4.5.0), Simple Scheduler (0.64), Duck DNS (1.15.0), MariaDB (2.5.1), Nginx Proxy Manager (0.12.2), WireGuard Client (0.2.0), Let's Encrypt (4.12.7), ESPHome (2022.9.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 29, 2022 at 06:03
-- | --
current_recorder_run | October 9, 2022 at 19:26
estimated_db_size | 261.45 MiB
database_engine | mysql
database_version | 10.6.8

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

no custom repositories can be added

### Reproduction steps

1. install HACS  1.28.0
2. try add custom repositories

### Screenshots

no screenshot

### Javascript logs from your browser console

```text
null
```

### Diagnostics dump

[config_entry-hacs-e871d90e7d53e60ab66489f174122777.json.txt](https://github.com/hacs/integration/files/9742234/config_entry-hacs-e871d90e7d53e60ab66489f174122777.json.txt)

**Comment by ludeeus** [comment]
Fixed with <https://github.com/hacs/frontend/pull/616>
Use my links or disable experimental if you need it before its released.
