### ISSUE TITLE
HACS 1.28.0 is broken

### ISSUE THREAD

**Issue by IgorSimic** [hacs/integration#2882]
### Web browser

chromium

### Web browser version

Version 105.0.5195.102 (Official Build) Built on Ubuntu , running on LinuxMint 19.3 (64-bit)

## System Information

version | core-2022.10.1
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | homeassistant
virtualenv | true
python_version | 3.9.14
os_name | Linux
os_version | 5.15.0-48-generic
arch | x86_64
timezone | Europe/Vienna
config_dir | /home/homeassistant/.homeassistant

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.28.0
Stage | running
Available Repositories | 1194
Downloaded Repositories | 61

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 48
views | 29
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 9, 2022 at 2:39 AM
-- | --
current_recorder_run | October 9, 2022 at 9:23 PM
estimated_db_size | 1511.39 MiB
database_engine | sqlite
database_version | 3.37.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Frontend looks just like table.

### Reproduction steps

1. Install 1.28.0
2. Restart HA

### Screenshots

![Screenshot_2022-10-09_21-43-23](https://user-images.githubusercontent.com/44424256/194776937-e2993067-a661-4e3b-aabd-0de28bb07eab.jpg)

### Javascript logs from your browser console

```text
N/A
```

### Diagnostics dump

?

**Comment by ludeeus** [comment]
Wrong assumption.
It's as expected.

**Comment by IgorSimic** [comment]
In mine case it starts to work properly after i reloaded integration.
Strange, restart HA didn't help, but integration reload did.


----------
Igor Simić
----------
________________________________

**Comment by vlad36N** [comment]
Have the same, restart HA didn't help and integration reload didn't help also.

![hacs](https://user-images.githubusercontent.com/30022288/195455216-1c1360f0-1260-4bcb-9e15-4efbd9b3aa1d.png)

HACS version 1.28.0
Home Assistant 2022.10.3 
Supervisor 2022.10.0 
Operating System 9.2 
Frontend 20221010.0 - latest 

Diagnostics dump attached:

[config_entry-hacs-5e0871f134f9db81585d413a9a99e415.json.txt](https://github.com/hacs/integration/files/9768903/config_entry-hacs-5e0871f134f9db81585d413a9a99e415.json.txt)
