### ISSUE TITLE
Scrolling Bug in Integration Browser

### ISSUE THREAD

**Issue by shanespringer** [hacs/integration#2885]
### Web browser

safari

### Web browser version

18614.2.9.1.4

## System Information

version | core-2022.10.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.0-48-generic
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.28.0
Stage | running
Available Repositories | 1119
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 8, 2022 at 8:13 PM
-- | --
current_recorder_run | October 9, 2022 at 10:42 PM
estimated_db_size | 1.41 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When the list of integrations is loading, scrolling to the end before it's loaded additional entries makes the window unscrollable until closed (with the still responsive close button) and reopened.

https://user-images.githubusercontent.com/18318249/194806356-8d5a770b-99c3-4bfc-9441-9b54cfc22662.mp4

### Reproduction steps

1. Open HACS Integration browser
2. Hard scroll in window

### Screenshots

https://user-images.githubusercontent.com/18318249/194806550-66c2de80-255a-46c0-b00d-91e68c0e6da5.mp4

### Javascript logs from your browser console

```text
nothing in logs
```

### Diagnostics dump

{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2022.10.2",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/Los_Angeles",
    "os_name": "Linux",
    "os_version": "5.15.0-48-generic",
    "run_as_root": true
  },
  "custom_components": {
    "frigate": {
      "version": "3.0.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.28.0",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "mail_and_packages": {
      "version": "0.3.4-2",
      "requirements": [
        "imageio>=2.9.0",
        "python-resize-image>=1.1.19"
      ]
    },
    "meross_lan": {
      "version": "2.6.2",
      "requirements": []
    },
    "mass": {
      "version": "2022.8.4",
      "requirements": [
        "music-assistant==1.8.7"
      ]
    }
  },
  "integration_manifest": {
    "codeowners": [
      "@ludeeus"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "websocket_api",
      "frontend",
      "persistent_notification",
      "lovelace",
      "repairs"
    ],
    "documentation": "https://hacs.xyz/docs/configuration/start",
    "domain": "hacs",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/hacs/integration/issues",
    "name": "HACS",
    "requirements": [
      "aiogithubapi>=22.2.4"
    ],
    "version": "1.28.0",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "9cc98eb2a8b8cd7f9fad753691d0e148",
      "version": 1,
      "domain": "hacs",
      "title": "",
      "data": {
        "token": "**REDACTED**"
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "hacs": {
      "stage": "running",
      "version": "1.28.0",
      "disabled_reason": null,
      "new": false,
      "startup": false,
      "categories": [
        "theme",
        "integration",
        "plugin"
      ],
      "renamed_repositories": {
        "9a4gl/hass-peltec": "9a4gl/hass-centrometal-boiler",
        "DarkSir23/sensor.mylar": "WillowMist/sensor.mylar",
        "78wesley/Darkish-Theme": "78wesley/Home-Assistant-Darkish-Theme",
        "dmitry-k/yandex_smart_home": "dext0r/yandex_smart_home",
        "nikrolls/homeassistant-goldair-climate": "nicole-ashley/homeassistant-goldair-climate",
        "wernerhp/ha_integration_load_shedding": "wernerhp/ha.integration.load_shedding",
        "nbogojevic/homeassistant-midea-dehumidifier-lan": "nbogojevic/homeassistant-midea-air-appliances-lan",
        "wills106/homsassistant-solax-modbus": "wills106/homeassistant-solax-modbus"
      },
      "archived_repositories": [],
      "ignored_repositories": [],
      "lovelace_mode": "auto-gen",
      "configuration": {
        "appdaemon": false,
        "country": "ALL",
        "debug": false,
        "dev": false,
        "experimental": false,
        "netdaemon": false,
        "python_script": false,
        "release_limit": 5,
        "theme": false
      }
    },
    "custom_repositories": [
      "home-assistant-libs/python-matter-server",
      "elupus/hass_nibe"
    ],
    "repositories": [
      {
        "data": {
          "archived": false,
          "authors": [
            "@ludeeus"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "main",
          "description": "HACS gives you a powerful UI to handle downloads of all your custom needs.",
          "domain": "hacs",
          "downloads": 4618,
          "etag_repository": "W/\"cdc349aa38750f3fd3471cc39301105dbc885ddf262786993d4361a50108bf38\"",
          "file_name": "",
          "first_install": false,
          "full_name": "hacs/integration",
          "hide": false,
          "has_issues": true,
          "id": "172733314",
          "installed_commit": null,
          "installed_version": "1.28.0",
          "installed": true,
          "last_commit": "8c71acb",
          "last_updated": "2022-10-09T16:53:39Z",
          "last_version": "1.28.0",
          "manifest_name": "HACS",
          "new": false,
          "open_issues": 3,
          "published_tags": [
            "1.28.0",
            "1.27.2",
            "1.27.1",
            "1.27.0",
            "1.26.2"
          ],
          "pushed_at": "2022-10-09T16:53:39",
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 2956,
          "topics": [
            "community",
            "package-manager"
          ]
        },
        "integration_manifest": {
          "codeowners": [
            "@ludeeus"
          ],
          "config_flow": true,
          "dependencies": [
            "http",
            "websocket_api",
            "frontend",
            "persistent_notification",
            "lovelace",
            "repairs"
          ],
          "documentation": "https://hacs.xyz/docs/configuration/start",
          "domain": "hacs",
          "iot_class": "cloud_polling",
          "issue_tracker": "https://github.com/hacs/integration/issues",
          "name": "HACS",
          "requirements": [
            "aiogithubapi>=22.2.4"
          ],
          "version": "0.0.0"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "hacs.zip",
          "hacs": "0.19.0",
          "hide_default_branch": true,
          "homeassistant": "2022.10.0",
          "manifest": {
            "name": "HACS",
            "zip_release": true,
            "hide_default_branch": true,
            "homeassistant": "2022.10.0",
            "hacs": "0.19.0",
            "filename": "hacs.zip"
          },
          "name": "HACS",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": "1.28.0",
        "paths": {
          "localpath": "/config/custom_components/hacs",
          "local": "/config/custom_components/hacs",
          "remote": "custom_components/hacs"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@moralmunky",
            "@firstof9"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "master",
          "description": "Home Assistant integration providing day of package counts and USPS informed delivery images.",
          "domain": "mail_and_packages",
          "downloads": 4495,
          "etag_repository": "W/\"b08f374c8a20cfdeb00900b42c440db1b98769813cd9d41650bb73dd82ebf033\"",
          "file_name": "",
          "first_install": false,
          "full_name": "moralmunky/Home-Assistant-Mail-And-Packages",
          "hide": false,
          "has_issues": true,
          "id": "188106531",
          "installed_commit": "6abdb93",
          "installed_version": "0.3.4-2",
          "installed": true,
          "last_commit": "6abdb93",
          "last_updated": "2022-09-21T22:25:44Z",
          "last_version": "0.3.4-2",
          "manifest_name": "Mail and Packages",
          "new": false,
          "open_issues": 3,
          "published_tags": [
            "0.3.4-2",
            "0.3.4-1"
          ],
          "pushed_at": "2022-09-21T22:25:44",
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 359,
          "topics": [
            "home-assistant-config",
            "lovelace-card",
            "lovelace-custom-card"
          ]
        },
        "integration_manifest": {
          "domain": "mail_and_packages",
          "name": "Mail and Packages",
          "documentation": "https://github.com/moralmunky/Home-Assistant-Mail-And-Packages",
          "issue_tracker": "https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues",
          "dependencies": [],
          "codeowners": [
            "@moralmunky",
            "@firstof9"
          ],
          "config_flow": true,
          "requirements": [
            "imageio>=2.9.0",
            "python-resize-image>=1.1.19"
          ],
          "iot_class": "cloud_polling",
          "version": "0.0.0-dev"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "mail_and_packages.zip",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "0.109.0",
          "manifest": {
            "name": "Mail and Packages",
            "homeassistant": "0.109.0",
            "zip_release": true,
            "filename": "mail_and_packages.zip"
          },
          "name": "Mail and Packages",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": "tags/0.3.4-2",
        "paths": {
          "localpath": "/config/custom_components/mail_and_packages",
          "local": "/config/custom_components/mail_and_packages",
          "remote": "custom_components/mail_and_packages"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@krahabb"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "master",
          "description": "Home Assistant integration for Meross devices",
          "domain": "meross_lan",
          "downloads": 0,
          "etag_repository": "W/\"cd0060d9c37f9bc6c801d81e03a1208fd969ef35d529ecad22b436fe156ffdf7\"",
          "file_name": "",
          "first_install": false,
          "full_name": "krahabb/meross_lan",
          "hide": false,
          "has_issues": true,
          "id": "341500126",
          "installed_commit": "43c3b84",
          "installed_version": "v2.6.2",
          "installed": true,
          "last_commit": "43c3b84",
          "last_updated": "2022-09-30T12:00:33Z",
          "last_version": "v2.6.2",
          "manifest_name": "Meross LAN",
          "new": false,
          "open_issues": 17,
          "published_tags": [
            "v2.6.2",
            "v2.6.1",
            "v2.5.7",
            "v.2.5.4",
            "v2.4.3"
          ],
          "pushed_at": "2022-09-30T12:00:33",
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 155,
          "topics": [
            "meross",
            "meross-devices",
            "meross-homeassistant",
            "meross-lan"
          ]
        },
        "integration_manifest": {
          "domain": "meross_lan",
          "name": "Meross LAN",
          "config_flow": true,
          "iot_class": "local_polling",
          "documentation": "https://github.com/krahabb/meross_lan",
          "issue_tracker": "https://github.com/krahabb/meross_lan/issues",
          "requirements": [],
          "dhcp": [
            {
              "hostname": "*",
              "macaddress": "48E1E9*"
            },
            {
              "hostname": "*",
              "macaddress": "34298F1*"
            }
          ],
          "dependencies": [
            "recorder"
          ],
          "after_dependencies": [
            "mqtt",
            "dhcp"
          ],
          "codeowners": [
            "@krahabb"
          ],
          "version": "2.6.2"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [
            "IT",
            "GB",
            "US",
            "JP",
            "ES",
            "FR",
            "DE"
          ],
          "filename": null,
          "hacs": "1.6.0",
          "hide_default_branch": false,
          "homeassistant": "2022.1.0",
          "manifest": {
            "name": "Meross LAN",
            "render_readme": true,
            "country": [
              "IT",
              "GB",
              "US",
              "JP",
              "ES",
              "FR",
              "DE"
            ],
            "homeassistant": "2022.1.0",
            "persistent_directory": "traces",
            "hacs": "1.6.0"
          },
          "name": "Meross LAN",
          "persistent_directory": "traces",
          "render_readme": true,
          "zip_release": false
        },
        "ref": "tags/v2.6.2",
        "paths": {
          "localpath": "/config/custom_components/meross_lan",
          "local": "/config/custom_components/meross_lan",
          "remote": "custom_components/meross_lan"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@blakeblackshear"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "master",
          "description": "Frigate integration for Home Assistant",
          "domain": "frigate",
          "downloads": 0,
          "etag_repository": "W/\"b192bc73a9cd2b180e8f4fc5a1b08f1c8b2621128cbdb17421cbefd41774c218\"",
          "file_name": "",
          "first_install": false,
          "full_name": "blakeblackshear/frigate-hass-integration",
          "hide": false,
          "has_issues": true,
          "id": "311536795",
          "installed_commit": "5f31ea8",
          "installed_version": "v3.0.0",
          "installed": true,
          "last_commit": "5f31ea8",
          "last_updated": "2022-10-05T07:42:48Z",
          "last_version": "v3.0.0",
          "manifest_name": "Frigate",
          "new": false,
          "open_issues": 19,
          "published_tags": [
            "v3.0.0",
            "v2.3",
            "v2.2.2",
            "v2.2.1",
            "v2.2.0"
          ],
          "pushed_at": "2022-10-05T07:42:48",
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 293,
          "topics": [
            "ai",
            "camera",
            "frigate",
            "nvr",
            "object-detection"
          ]
        },
        "integration_manifest": {
          "domain": "frigate",
          "documentation": "https://github.com/blakeblackshear/frigate",
          "name": "Frigate",
          "version": "3.0.0",
          "issue_tracker": "https://github.com/blakeblackshear/frigate-hass-integration/issues",
          "dependencies": [
            "http",
            "media_source",
            "mqtt"
          ],
          "config_flow": true,
          "codeowners": [
            "@blakeblackshear"
          ],
          "requirements": [],
          "iot_class": "local_push"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": "1.6.0",
          "hide_default_branch": false,
          "homeassistant": "2022.4.5",
          "manifest": {
            "hacs": "1.6.0",
            "name": "Frigate",
            "homeassistant": "2022.4.5"
          },
          "name": "Frigate",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": false
        },
        "ref": "tags/v3.0.0",
        "paths": {
          "localpath": "/config/custom_components/frigate",
          "local": "/config/custom_components/frigate",
          "remote": "custom_components/frigate"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@marcelveldt"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "main",
          "description": "Turn your Home Assistant instance into a jukebox, hassle free streaming of your favorite media to Home Assistant media players.",
          "domain": "mass",
          "downloads": 7722,
          "etag_repository": "W/\"5cc8f79a6a86114d5e255b7f717696650ed245b3ddbdd8a6b053176a9c97d9ae\"",
          "file_name": "",
          "first_install": false,
          "full_name": "music-assistant/hass-music-assistant",
          "hide": false,
          "has_issues": true,
          "id": "476357279",
          "installed_commit": "030dd6c",
          "installed_version": "2022.8.4",
          "installed": true,
          "last_commit": "030dd6c",
          "last_updated": "2022-10-07T01:42:53Z",
          "last_version": "2022.8.4",
          "manifest_name": "Music Assistant",
          "new": false,
          "open_issues": 31,
          "published_tags": [
            "2022.8.4",
            "2022.8.3",
            "2022.8.2",
            "2022.8.1",
            "2022.8.0"
          ],
          "pushed_at": "2022-10-07T01:42:53",
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 354,
          "topics": [
            "music-library",
            "music-player"
          ]
        },
        "integration_manifest": {
          "domain": "mass",
          "name": "Music Assistant",
          "version": "2022.8.4",
          "documentation": "https://github.com/music-assistant/hass-music-assistant",
          "issue_tracker": "https://github.com/music-assistant/hass-music-assistant/issues",
          "requirements": [
            "music-assistant==1.8.7"
          ],
          "codeowners": [
            "@marcelveldt"
          ],
          "dependencies": [
            "http",
            "panel_custom"
          ],
          "after_dependencies": [
            "media_source",
            "media_player",
            "cast",
            "group"
          ],
          "config_flow": true,
          "iot_class": "local_push",
          "loggers": [
            "music_assistant"
          ]
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "mass.zip",
          "hacs": null,
          "hide_default_branch": true,
          "homeassistant": "2022.7.0",
          "manifest": {
            "name": "Music Assistant",
            "render_readme": true,
            "zip_release": true,
            "filename": "mass.zip",
            "hide_default_branch": true,
            "homeassistant": "2022.7.0"
          },
          "name": "Music Assistant",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": true
        },
        "ref": "tags/2022.8.4",
        "paths": {
          "localpath": "/config/custom_components/mass",
          "local": "/config/custom_components/mass",
          "remote": "custom_components/mass"
        }
      }
    ],
    "rate_limit": {
      "resources": {
        "core": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1665385990
        },
        "search": {
          "limit": 30,
          "used": 0,
          "remaining": 30,
          "reset": 1665382450
        },
        "graphql": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1665385990
        },
        "integration_manifest": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1665385990
        },
        "source_import": {
          "limit": 100,
          "used": 0,
          "remaining": 100,
          "reset": 1665382450
        },
        "code_scanning_upload": {
          "limit": 1000,
          "used": 0,
          "remaining": 1000,
          "reset": 1665385990
        },
        "actions_runner_registration": {
          "limit": 10000,
          "used": 0,
          "remaining": 10000,
          "reset": 1665385990
        },
        "scim": {
          "limit": 15000,
          "used": 0,
          "remaining": 15000,
          "reset": 1665385990
        }
      },
      "rate": {
        "limit": 5000,
        "used": 0,
        "remaining": 5000,
        "reset": 1665385990
      }
    }
  }
}

**Comment by ludeeus** [comment]
This will not be fixed.
This section does not exist in the experimental view that were released yesterday.
