### ISSUE TITLE
visual hacs after update hassio 

### ISSUE THREAD

**Issue by riddik14** [hacs/integration#2888]
### Web browser

chrome

### Web browser version

Versione 105.0.5195.125 (Build ufficiale) (x86_64)

### System Health details

Release 2022.10.3 - October 10
Bump pyhiveapi to 0.5.14 ([@KJonline](https://github.com/KJonline) - [#79530](https://github.com/home-assistant/core/pull/79530)) ([hive docs](https://www.home-assistant.io/integrations/hive/)) (dependency)
Bump bluetooth-auto-recovery to 0.3.4 ([@bdraco](https://github.com/bdraco) - [#79971](https://github.com/home-assistant/core/pull/79971)) ([bluetooth docs](https://www.home-assistant.io/integrations/bluetooth/)) (dependency)
Bump pySwitchbot to 0.19.15 ([@bdraco](https://github.com/bdraco) - [#79972](https://github.com/home-assistant/core/pull/79972)) ([switchbot docs](https://www.home-assistant.io/integrations/switchbot/)) (dependency)
Update to pygtfs 0.1.7 ([@molisani](https://github.com/molisani) - [#79975](https://github.com/home-assistant/core/pull/79975)) ([gtfs docs](https://www.home-assistant.io/integrations/gtfs/)) (dependency)
Update frontend to 20221010.0 ([@bramkragten](https://github.com/bramkragten) - [#79994](https://github.com/home-assistant/core/pull/79994)) ([frontend docs](https://www.home-assistant.io/integrations/frontend/))
Remove system marker from Supervisor integration ([@frenck](https://github.com/frenck) - [#79997](https://github.com/home-assistant/core/pull/79997)) ([hassio docs](https://www.home-assistant.io/integrations/hassio/))
Fix Eve Thermo always showing as heating in homekit_controller even when off ([@Jc2k](https://github.com/Jc2k) - [#80019](https://github.com/home-assistant/core/pull/80019)) ([homekit_controller docs](https://www.home-assistant.io/integrations/homekit_controller/))
Fix armed extra state attribute in fibaro entity ([@rappenze](https://github.com/rappenze) - [#80034](https://github.com/home-assistant/core/pull/80034)) ([fibaro docs](https://www.home-assistant.io/integrations/fibaro/))
Bump aiounifi to v39 ([@Kane610](https://github.com/Kane610) - [#80043](https://github.com/home-assistant/core/pull/80043)) ([unifi docs](https://www.home-assistant.io/integrations/unifi/)) (dependency)
Fix Netatmo device trigger ([@cgtobi](https://github.com/cgtobi) - [#80047](https://github.com/home-assistant/core/pull/80047)) ([netatmo docs](https://www.home-assistant.io/integrations/netatmo/))
Bump ZHA dependencies ([@puddly](https://github.com/puddly) - [#80049](https://github.com/home-assistant/core/pull/80049)) ([zha docs](https://www.home-assistant.io/integrations/zha/)) (dependency)

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

after update Release 2022.10.3 - October 10 hacs repo show as listed

### Reproduction steps

1. update hassio 
2. go in hacs menu
3. show listed repo
...

### Screenshots

![Schermata 2022-10-11 alle 16 52 08](https://user-images.githubusercontent.com/37450907/195125866-51e1b4aa-8a69-4ed2-bb6c-64ec220f8178.png)

### Javascript logs from your browser console

```text
no
```

**Comment by ludeeus** [comment]
Expected
