### ISSUE TITLE
Custom Repository Dialog does not open

### ISSUE THREAD

**Issue by panhans** [hacs/integration#2889]
### Web browser

Firefox / Chrome

### Web browser version

105.0.3 / 105.0.5195.125

### System Health details

Can't find it anymore. Not discribed well in docs.

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The dialog to see or add custom repositories doesn't show up anymore.

### Reproduction steps

1. Open HACS
2. Klick 3 dots menu
3. Klick Custom Repositories
4. nothing happens

### Screenshots

-

### Javascript logs from your browser console

```text
-
```

### Diagnostics dump

-

**Comment by ludeeus** [comment]
Duplicate of #2887

**Comment by marcokreeft87** [comment]
So this issie is not fixed.. In 2880 the reporter said it isnt fixed and I can confirm that it is not fixed by disabling expiremental features.
