### ISSUE TITLE
Platform hacs does not generate unique IDs. ID xyz already exists - ignoring sensor.hacs

### ISSUE THREAD

**Issue by tompijls** [hacs/integration#2893]
### System Health details

Upon reboot, following error shows in the HA logs:

`
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:520
Integration: Sensor (documentation, issues)
First occurred: 14:40:34 (1 occurrences)
Last logged: 14:40:34

Platform hacs does not generate unique IDs. ID 0717a0cd-745c-48fd-9b16-c8534c9704f9-bc944b0f-fd42-4a58-a072-ade38d1444cd already exists - ignoring sensor.hacs
`

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I have an error upon starting home assistant. This error prevents me now from upgrading home assistant (system unhealthy)

`
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:520
Integration: Sensor (documentation, issues)
First occurred: 16:54:15 (1 occurrences)
Last logged: 16:54:15

Platform hacs does not generate unique IDs. ID 0717a0cd-745c-48fd-9b16-c8534c9704f9-bc944b0f-fd42-4a58-a072-ade38d1444cd already exists - ignoring sensor.hacs
`

### Reproduction steps

1. just reboot home assistant will trigger the error

### Debug logs

```text
see next post (body too long error)
```

### Diagnostics dump

[config_entry-hacs-022a17b313c615e6c29994a490c0c302.json (1).txt](https://github.com/hacs/integration/files/9778115/config_entry-hacs-022a17b313c615e6c29994a490c0c302.json.1.txt)

**Comment by tompijls** [comment]
HA log 
[HA.log.txt](https://github.com/hacs/integration/files/9778137/HA.log.txt)

**Comment by ludeeus** [comment]
That entity has already been removed in experimental and will be removed for all later.

**Comment by tompijls** [comment]
apologies if I'm ignorant. So I just wait for a new release of HACS to fix this? In the meantime I cant upgrade HA?

**Comment by ludeeus** [comment]
It does not affect anything, upgrade HA when you want.
- You can enable experimental
- You can wait until its removed for all (That will take months)
