### ISSUE TITLE
Integration can not be removed ("unknown_command")

### ISSUE THREAD

**Issue by bcutter** [hacs/integration#2894]
### Web browser

Firefox (also tried other browsers, HA Companion app on iOS etc.)

### Web browser version

105.0.3

### System Health details

I don't have that copy button according to https://www.home-assistant.io//more-info/system-health#github-issues yet (HA Core 2022.6.7), therefore this way:

<html><body>

Version | core-2022.6.7
-- | --
Installationstyp | Home Assistant OS
Entwicklung | false
Supervisor | true
Docker | true
Benutzer | root
Virtuelle Umgebung | false
Python-Version | 3.9.12
Betriebssystemfamilie | Linux
Betriebssystem-Version | 5.15.61-v8
CPU-Architektur | aarch64
Zeitzone | Europe/Berlin

</body>
</html>

<html><body>
<h3>Home Assistant Community Store</h3>
                
GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4973
Installed Version | 1.26.2
Stage | running
Available Repositories | 1187
Downloaded Repositories | 82

</body>
</html>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

A specific integration (ShellyForHASS) can not be removed using the UI.

When clicking the remove/uninstall button, nothing happens:

![grafik](https://user-images.githubusercontent.com/13799156/195640902-669c5253-0cbe-4c91-bbff-0c37b7136a35.png)

The browser logs this error on every click at remove/uninstall: (see "Javascript logs from your browser console" section below)

See also https://github.com/StyraHem/ShellyForHASS/issues/712 (one month and no reaction at all - that's one of many reasons I need to urgently remove this custom integration!).

Please note there's an update pending for that integration.
- Installed: 1.0.1
- Available: 1.0.2

### Reproduction steps

1. Go to integrations
2. Go to "ShellyForHass (Shelly integration)"
3. click on the burger menu, select remove/uninstall - nothing will happen

### Screenshots

![grafik](https://user-images.githubusercontent.com/13799156/195640902-669c5253-0cbe-4c91-bbff-0c37b7136a35.png)

![grafik](https://user-images.githubusercontent.com/13799156/195643177-09b628b3-01fe-41b3-aa56-d97ea71d5c3e.png)
(clicked remove/uninstall 4 times)

### Javascript logs from your browser console

```text
Short:

{
  "code": "unknown_command",
  "message": "Unknown command."
}
```

Detailled (note I replaced my actual url by "https://my-home-assistant"):
```
Uncaught (in promise) 
Object { code: "unknown_command", message: "Unknown command." }
c.bad50d60.js:131:739
    value https://my-home-assistant/hacsfiles/frontend/c.bad50d60.js:131
    AsyncFunctionThrow self-hosted:811
    (Async: async)
    action https://my-home-assistant/hacsfiles/frontend/c.bad50d60.js:89
    handleEvent https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    (Async: EventListener.handleEvent)
    _$AI https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    m https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    T https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    _$AI https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    A https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    _$AI https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    m https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    T https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    _$AI https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    m https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    T https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    _$AI https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    Q https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    update https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    performUpdate https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    scheduleUpdate https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    _$EC https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    AsyncFunctionNext self-hosted:807
    (Async: async)
    requestUpdate https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    o https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    x https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    _e https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    F https://my-home-assistant/hacsfiles/frontend/c.eb4f9da9.js:1
    p https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    T https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    _$AI https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    Q https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    update https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    performUpdate https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    scheduleUpdate https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    _$EC https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    AsyncFunctionNext self-hosted:807
    (Async: async)
    requestUpdate https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    set https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    value https://my-home-assistant/hacsfiles/frontend/c.bad50d60.js:77
    InterpretGeneratorResume self-hosted:1819
    AsyncFunctionNext self-hosted:807
    (Async: async)
    value https://my-home-assistant/hacsfiles/frontend/c.bad50d60.js:77
    _$AE https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    performUpdate https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    scheduleUpdate https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    _$EC https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    InterpretGeneratorResume self-hosted:1819
    AsyncFunctionNext self-hosted:807
    (Async: async)
    requestUpdate https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    o https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    x https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
    _e https://my-home-assistant/hacsfiles/frontend/main-7bc9a818.js:1
```
```


### Diagnostics dump

_No response_

**Comment by ludeeus** [comment]
Update HACS before doing anything else https://github.com/hacs/integration/releases/tag/1.28.0

**Comment by ludeeus** [comment]
You need Home Assistant 2022.10 +
I'll close this issue until it can be retested with the new version.
I will not guide you to do this manually.
