### ISSUE TITLE
New HACs view (?) visible after disabling experimental features

### ISSUE THREAD

**Issue by dunxd** [hacs/integration#2895]
### Web browser

HA Android Companion App

### Web browser version

2022.10.0-full

## System Information

version | core-2022.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.61-v7l
arch | armv7l
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4768
Installed Version | 1.28.0
Stage | running
Available Repositories | 1186
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.0
agent_version | 1.4.1
docker_version | 20.10.17
disk_total | 28.5 GB
disk_used | 21.3 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.1), File editor (5.4.1), Duck DNS (1.15.0), Crowdsec (1.4.1-ha1), Crowdsec Firewall Bouncer (v0.0.24)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 6
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 6 October 2022 at 13:17
-- | --
current_recorder_run | 14 October 2022 at 10:51
estimated_db_size | 849.48 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

On opening HACS today I noticed the new interface(which I don't particularly like). I saw in the Release Notes for the latest update that a new interface was made available to those with Experimental Features enabled. I checked in the HACS integration options and saw I had this ticked. I unticked, and returned to HACS but still got the new interface. I reloaded the integration, but still got new interface. I restarted HA but still getting new HACS interface.
I checked on my laptop, and I see the old view, but on my Android, I still see the different view. I've force restarted the HA Companion App.

### Reproduction steps

1. Disable Experimental Features
2. Reload HACS integration
3. Restart HACS
4. Force stop HA Companion App

### Screenshots

![Screenshot_20221014-110444](https://user-images.githubusercontent.com/16608541/195821107-9d863e2b-2cb6-4a32-8ed6-fcaf8556384f.png)

### Javascript logs from your browser console

```text
Not accessible in HA Companion App
```

**Comment by ludeeus** [comment]
You have to restart Home Assistant and then clear the browser cache when changing modes.
