### ISSUE TITLE
/hacsfiles/ isn't accessible after adding integration until hass is restarted.

### ISSUE THREAD

**Issue by rct** [hacs/integration#2898]
### Describe the issue

It seems like Home Assistant needs to be restarted after adding the HACS integration if you want to use HACS for front end components, but I don't see a mention of that on `https://hacs.xyz/docs/configuration/basic` 

In two recent installations against 2022.10.x, I noticed after adding the HACS integration, HACS seems to work, but adding and trying to use front end components won't work yet because `/hacsfiles/` returns a 404 until after Home Assistant is restarted.  Once restarted a `403: Forbidden` is returned, indicating that it recognizes it as a directory.

I'm guessing this would only trip up someone who wants to add front end components and use them right away.  If you add an integration, you need to restart hass anyway, so you'd never notice this.

### Screenshots

```
$ curl -i http://...:8123/hacsfiles/
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Content-Length: 14
Date: Sun, 16 Oct 2022 22:26:16 GMT
Server: Python/3.10 aiohttp/3.8.1
```

**Comment by ludeeus** [comment]
That is not correct

**Comment by ludeeus** [comment]
HACS itself is served from /hacsfiles
Closing as this is not something that should be documented.

**Comment by rct** [comment]
Curiously `/hacsfiles/frontend/*` does work before a restart, but the resources HACS installed `/hacsfiles/*.js` don't appear to be accessible until after restart. 

Can access frontend file:
```
$ curl --head http://...:8123/hacsfiles/frontend/c.f6611997.js
HTTP/1.1 200 OK
Content-Type: application/javascript
Etag: "171c71372c437800-2b9d3"
Last-Modified: Sun, 09 Oct 2022 15:47:24 GMT
Content-Length: 178643
Accept-Ranges: bytes
Date: Sun, 16 Oct 2022 23:16:51 GMT
Server: Python/3.10 aiohttp/3.8.1
```

Resource installed by HACS, 404.
```
$ curl -i http://hass.whb.r-t.org:8123/hacsfiles/history-explorer-card/history-explorer-card.js?hacstag=4403747941027
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Content-Length: 14
Date: Sun, 16 Oct 2022 23:12:57 GMT
Server: Python/3.10 aiohttp/3.8.1

404: Not Found
```

Frontend directory 403 as expected
```
$ curl -i http://hass.whb.r-t.org:8123/hacsfiles/frontend/
HTTP/1.1 403 Forbidden
Content-Type: text/plain; charset=utf-8
Content-Length: 14
Date: Sun, 16 Oct 2022 23:11:48 GMT
Server: Python/3.10 aiohttp/3.8.1

403: Forbidden
```

Dashboard resources:

![image](https://user-images.githubusercontent.com/38770/196063597-10669481-8896-44f5-a174-19aee7a77e92.png)




Once hass has been restarted post HACS integration install, the front end resource installed by HACS is now available:

```
$ curl --head http://hass.whb.r-t.org:8123/hacsfiles/history-explorer-card/history-explorer-card.js?hacstag=4403747941027
HTTP/1.1 200 OK
Cache-Control: public, max-age=2678400
Content-Type: application/javascript
Etag: "171eaa8c5a6089b7-459f0"
Last-Modified: Sun, 16 Oct 2022 21:40:32 GMT
Content-Length: 285168
Accept-Ranges: bytes
Date: Sun, 16 Oct 2022 23:28:26 GMT
Server: Python/3.10 aiohttp/3.8.1
```

So if that's not the expected behavior, is this an issue with HACS?
