### ISSUE TITLE
Hacs integration no loading cards offline

### ISSUE THREAD

**Issue by molly200** [hacs/integration#2904]
### System Health details

System is healthy

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

hacks does not load cards after a reboot and HA is offline (no internet). If the host lost power and after a restore hacs no longer loads-up the installed cards. The internet connection to HA needs to be restored in order for hacs to load the cards.

### Reproduction steps

1. Stop the internet connection to Home assistant
2. Reboot host or restart Home assistant
3. Upon HA restart hacs display a message of a number of cards no being loaded. The frontend cards are all red
4. Upon restoring the internet connection the cards are properly loaded
5.
...

### Debug logs

```text
N/A
```

### Diagnostics dump

N/A

**Comment by ludeeus** [comment]
It’s in the requirements.

**Comment by molly200** [comment]
Hi there

I don't know I understand the message. What is "in the requirements" mean? Is this an integration requirement or HA requirement?

Should not this integration work offline?  Does this mean that it is not supported by home assistant and in order to be offline, I need to install and update the sources manualy?

Thanks

**Comment by ludeeus** [comment]
This integration requires internet, that is stated in its requirements.
https://hacs.xyz/docs/setup/prerequisites

**Comment by molly200** [comment]
Ok, thanks!
