### ISSUE TITLE
display hidden repositories

### ISSUE THREAD

**Issue by realfire23** [hacs/integration#2906]
### Web browser

chrome

### Web browser version

 106.0.5249.119 

### System Health details

f

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Hi,

I accidentaly disable / hide a repo but Iam unable to activate it anymore.

Didnt find anything about that in the documentation / forums.

Sorry to bug here

### Reproduction steps

1. disable repo
2. try to find / enable it
3.
...

### Screenshots

f

### Javascript logs from your browser console

```text
f
```

**Comment by ludeeus** [comment]
HACS does not offer the possibility to hide repositories, so what you did was not in HACS.

**Comment by realfire23** [comment]
> 
![image](https://user-images.githubusercontent.com/26832574/196612548-fc891b0a-8ef7-410f-86fb-5bf510741574.png)

that is hacs it say "ausblenden" which I translated with hide

**Comment by ludeeus** [comment]
That's "ignore" (use English UI when reporting issues).
That only hides the "new" flag on it, you can still search it like any other new repo

**Comment by realfire23** [comment]
Ok then I should open an issue about wrong translation. Whatever. 

Is there way to show ignored repos ?

Help is appreciated

![image](https://user-images.githubusercontent.com/26832574/196613004-0bc6c77e-f8bb-4651-9480-8cd745f38d74.png)

**Comment by ludeeus** [comment]
you do **not** ignore repositories, you ignore the **new** tag on them
You find them the EXACT same way as all others.

**Comment by realfire23** [comment]
Hi I really appreciate the help, Oh fuck Iam an Idiot the repo had two similar names...

Sorry for taking your time, your help is appreciated
