### ISSUE TITLE
Experimental Frontend: The category filter(s) are not retained after opening a repository

### ISSUE THREAD

**Issue by RosemaryOrchard** [hacs/integration#2907]
### Web browser

Safari/Edge/Firefox

### Web browser version

Safari 16, latest Edge and Firefox

## System Information

version | core-2022.10.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.72
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 3642
Installed Version | 1.28.2
Stage | running
Available Repositories | 1211
Downloaded Repositories | 206

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.2
-- | --
update_channel | beta
supervisor_version | supervisor-2022.10.0
agent_version | 1.4.1
docker_version | 20.10.17
disk_total | 234.0 GB
disk_used | 92.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | eWeLink Smart Home (1.3.3), Studio Code Server (5.4.0), Mosquitto broker (6.1.3), InfluxDB (4.5.0), Grafana (8.0.2), Zigbee2MQTT (1.28.0-1), Eufy Security Add-on (0.9.4), RTSP Simple Server Add-on (v0.17.6), MariaDB (2.5.1), SSH & Web Terminal (12.0.2), Log Viewer (0.14.0), WireGuard (0.7.0), Home Assistant Git Exporter (1.13.0), Git pull (7.13.1), tydom2mqtt (2.6.1), Samba share (10.0.0), Check Home Assistant configuration (3.11.0), Caddy 2 (1.2.5), Samba Backup (5.1.2), Z-Wave JS UI (1.1.0), mitmproxy (1.2.0), Scrypted (v0.3.6), ESPHome (2022.10.0), chrony (2.4.0), Network UPS Tools (0.11.0), Simple Scheduler (0.64), wgeasy (7), Node-RED (13.4.0), Zigbee2MQTT Edge (edge)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 110
views | 24
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 10 October 2022, 11:06
-- | --
current_recorder_run | 18 October 2022, 20:52
estimated_db_size | 5840.06 MiB
database_engine | mysql
database_version | 10.6.8

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

In the experimental frontend you can filter out certain types of repositories, but after you visit a repository and return to the list the filter is lost.

### Reproduction steps

1. Filter (out) one kind of repository
2. Open the repository
3. Go back to the list (e.g. after you delete a repository you are automatically redirected back)

### Screenshots

<img width="245" alt="The filter options" src="https://user-images.githubusercontent.com/16113535/196691063-2186fabb-eede-47a8-bd9c-e051ac5e0fec.png">

### Javascript logs from your browser console

```text
None
(After loading HACs I deleted the console logs, no more were generated as part of this).
```

**Comment by ludeeus** [comment]
Currently, nothing is retained at all, that will be added in a future version.

**Comment by RosemaryOrchard** [comment]
Thank you for answering :)
