### ISSUE TITLE
Safari - Error while loading page entry

### ISSUE THREAD

**Issue by smulle48** [hacs/integration#2910]
### Web browser

Safari

### Web browser version

14.1.2

## System Information

version | core-2022.10.5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.10.0-18-amd64
arch | x86_64
timezone | Europe/Copenhagen
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.28.3
Stage | running
Available Repositories | 1191
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.0
agent_version | 1.2.2
docker_version | 20.10.19
disk_total | 232.2 GB
disk_used | 27.6 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.1.3), File editor (5.4.1), ESPHome (2022.10.0), AirCast (3.4.1), MariaDB (2.5.1), phpMyAdmin (0.8.1), Zigbee2MQTT (1.28.0-1), InfluxDB (4.5.0), Cloudflared (3.1.4), Node-RED (13.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 4
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 22. juni 2022 15.56
-- | --
current_recorder_run | 22. oktober 2022 23.23
estimated_db_size | 6618.50 MiB
database_engine | mysql
database_version | 10.6.8

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

After the latest update, I get the "Error while loading page entry" error when trying to open HACS.

I have cleared cache, history, rebooted machine, but nothing works.

I have tested it in Firefox, and there it works without any problems.

### Reproduction steps

1. Update to latest HACS
2. Clear cache, history and reboot
3. Nothing works.
4. Test in firefox = success

### Screenshots

![Skærmbillede 2022-10-22 kl  23 39 22](https://user-images.githubusercontent.com/24297824/197363509-f5b9ea67-4ee5-41fe-868b-4bd6fea1aad4.png)

### Javascript logs from your browser console

```text
[Error] Error loading page – "entry"
SyntaxError: Unexpected identifier 'K'
parseModule
[native code]
asyncFunctionResume
[native code]
promiseReactionJobWithoutPromise
promiseReactionJob
	(anonym funktion) (main-ec7846c8.js:1513:485162)
	promiseReactionJob
```

### Diagnostics dump

[config_entry-hacs-67ea7b739db646712849fe9066e1080f.json.txt](https://github.com/hacs/integration/files/9845299/config_entry-hacs-67ea7b739db646712849fe9066e1080f.json.txt)

**Comment by ludeeus** [comment]
Upgrade safari.

**Comment by ludeeus** [comment]
Closing as unsupported.

**Comment by smulle48** [comment]
> Upgrade safari.

I'm already running latest Safari on OS X 11.7

**Comment by smulle48** [comment]
> Upgrade safari.

After update to Safari 16.0 same error, but different JavaScript log

```
[Error] Error loading page – "entry"
TypeError: a.translations is not an Object. (evaluating 'e in a.translations')
I — c.aaeac12d.js:1:17160
(anonym funktion) — c.aaeac12d.js:1:19330
(anonym funktion) — c.aaeac12d.js:1:19384
promiseReactionJob
	(anonym funktion) (main-ec7846c8.js:1513:1708)
	promiseReactionJob
```

**Comment by mundschenk-at** [comment]
I am on Safari 16.0 as well and the error is unfortunately still there on macOS (no issue on iOS).

**Comment by mundschenk-at** [comment]
@ludeeus I just updated to the latest Safari 16.0.1 on macOS, but the error still occurs (things do work on iOS/iPadOS).
