### ISSUE TITLE
Repository Name list and other list super small 

### ISSUE THREAD

**Issue by randrcomputers** [hacs/integration#2911]
### Web browser

chrome

### Web browser version

106.0.5249.119

### System Health details

<html>
<body>
<div class="mdc-dialog__container" style="display: flex; flex-direction: row; align-items: var(--vertial-align-dialog, center); justify-content: space-around; box-sizing: border-box; height: 975px; transform: none; opacity: 1; pointer-events: none; color: rgb(225, 225, 225); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="mdc-dialog__surface" style="box-shadow: var(--mdc-dialog-box-shadow, 0px 11px 15px -7px rgba(0, 0, 0, 0.2), 0px 24px 38px 3px rgba(0, 0, 0, 0.14), 0px 9px 46px 8px rgba(0, 0, 0, 0.12)); position: var(--dialog-surface-position, relative); display: flex; flex-direction: column; flex-grow: 0; flex-shrink: 0; box-sizing: border-box; max-width: var(--mdc-dialog-max-width, 560px); max-height: var(--mdc-dialog-max-height, calc(100% - 32px)); pointer-events: auto; overflow-y: auto; background-color: var(--mdc-theme-surface, #fff); border-radius: var(--ha-dialog-border-radius, 28px); min-width: var(--mdc-dialog-min-width, 280px); top: var(--dialog-surface-top); margin-top: var(--dialog-surface-margin-top); min-height: var(--mdc-dialog-min-height, auto);"><div id="content" class="mdc-dialog__content" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-body1-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-body1-font-size, 1rem); line-height: var(--mdc-typography-body1-line-height, 1.5rem); font-weight: var(--mdc-typography-body1-font-weight, 400); letter-spacing: var(--mdc-typography-body1-letter-spacing, 0.03125em); text-decoration: var(--mdc-typography-body1-text-decoration, inherit); text-transform: var(--mdc-typography-body1-text-transform, inherit); flex-grow: 1; box-sizing: border-box; margin: 0px; overflow: auto; color: var(--mdc-dialog-content-ink-color, rgba(0, 0, 0, 0.6)); padding: var(--dialog-content-padding, 24px); position: var(--dialog-content-position, relative);"><div><div>

Version | core-2022.10.4
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.10.5
Operating System Family | Linux
Operating System Version | 5.15.61-v8
CPU Architecture | aarch64
Timezone | America/Chicago
Configuration Directory | /config

</div><div><h3>Core Metrics</h3><ha-metric><ha-settings-row style="display: flex; padding: 0px; align-content: normal; align-self: auto; align-items: center; height: 54px; width: 535px;"><div class="prefix-wrap" style="display: var(--settings-row-prefix-display);"><slot name="prefix"></slot><paper-item-body two-line="" style="overflow: hidden; display: var(--layout-vertical_-_display); flex-direction: var(--layout-vertical_-_flex-direction); justify-content: var(--layout-center-justified_-_justify-content); flex: 1 1 0%; min-height: calc( var(--paper-item-body-two-line-min-height, 72px) - 16px ); padding: 8px 16px 8px 0px;"><slot><slot name="heading"><span slot="heading" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">Processor Usage</span></slot><div secondary="" style="overflow: hidden; text-overflow: ellipsis; white-space: normal; font-family: var(--paper-font-body1_-_font-family); -webkit-font-smoothing: var(--paper-font-body1_-_-webkit-font-smoothing); font-size: var(--paper-font-body1_-_font-size); font-weight: var(--paper-font-body1_-_font-weight); line-height: var(--paper-font-body1_-_line-height); color: var(--paper-item-body-secondary-color, var(--secondary-text-color));"><slot name="description"><div slot="description" title="" style="white-space: normal; color: var(--secondary-text-color); display: flex; justify-content: space-between;"><span class="value" style="width: 48px; padding-right: 4px; flex-shrink: 0;">0.9<span> </span>%</span><ha-bar class="  " style="--ha-bar-primary-color: var( --metric-bar-ok-color, var(--success-color) );"><svg><g><rect></rect><rect width="0.9%"></rect></g></svg></ha-bar></div></slot></div></slot></paper-item-body></div><div class="content" style="display: var(--settings-row-content-display, flex); justify-content: flex-end; flex: 1 1 0%; padding: 16px 0px;"><slot></slot></div></ha-settings-row></ha-metric><ha-metric><ha-settings-row style="display: flex; padding: 0px; align-content: normal; align-self: auto; align-items: center; height: 54px; width: 535px;"><div class="prefix-wrap" style="display: var(--settings-row-prefix-display);"><slot name="prefix"></slot><paper-item-body two-line="" style="overflow: hidden; display: var(--layout-vertical_-_display); flex-direction: var(--layout-vertical_-_flex-direction); justify-content: var(--layout-center-justified_-_justify-content); flex: 1 1 0%; min-height: calc( var(--paper-item-body-two-line-min-height, 72px) - 16px ); padding: 8px 16px 8px 0px;"><slot><slot name="heading"><span slot="heading" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">Memory Usage</span></slot><div secondary="" style="overflow: hidden; text-overflow: ellipsis; white-space: normal; font-family: var(--paper-font-body1_-_font-family); -webkit-font-smoothing: var(--paper-font-body1_-_-webkit-font-smoothing); font-size: var(--paper-font-body1_-_font-size); font-weight: var(--paper-font-body1_-_font-weight); line-height: var(--paper-font-body1_-_line-height); color: var(--paper-item-body-secondary-color, var(--secondary-text-color));"><slot name="description"><div slot="description" title="" style="white-space: normal; color: var(--secondary-text-color); display: flex; justify-content: space-between;"><span class="value" style="width: 48px; padding-right: 4px; flex-shrink: 0;">9.8<span> </span>%</span><ha-bar class="  " style="--ha-bar-primary-color: var( --metric-bar-ok-color, var(--success-color) );"><svg><g><rect></rect><rect width="9.8%"></rect></g></svg></ha-bar></div></slot></div></slot></paper-item-body></div><div class="content" style="display: var(--settings-row-content-display, flex); justify-content: flex-end; flex: 1 1 0%; padding: 16px 0px;"><slot></slot></div></ha-settings-row></ha-metric><h3>Supervisor Metrics</h3><ha-metric><ha-settings-row style="display: flex; padding: 0px; align-content: normal; align-self: auto; align-items: center; height: 54px; width: 535px;"><div class="prefix-wrap" style="display: var(--settings-row-prefix-display);"><slot name="prefix"></slot><paper-item-body two-line="" style="overflow: hidden; display: var(--layout-vertical_-_display); flex-direction: var(--layout-vertical_-_flex-direction); justify-content: var(--layout-center-justified_-_justify-content); flex: 1 1 0%; min-height: calc( var(--paper-item-body-two-line-min-height, 72px) - 16px ); padding: 8px 16px 8px 0px;"><slot><slot name="heading"><span slot="heading" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">Processor Usage</span></slot><div secondary="" style="overflow: hidden; text-overflow: ellipsis; white-space: normal; font-family: var(--paper-font-body1_-_font-family); -webkit-font-smoothing: var(--paper-font-body1_-_-webkit-font-smoothing); font-size: var(--paper-font-body1_-_font-size); font-weight: var(--paper-font-body1_-_font-weight); line-height: var(--paper-font-body1_-_line-height); color: var(--paper-item-body-secondary-color, var(--secondary-text-color));"><slot name="description"><div slot="description" title="" style="white-space: normal; color: var(--secondary-text-color); display: flex; justify-content: space-between;"><span class="value" style="width: 48px; padding-right: 4px; flex-shrink: 0;">0.1<span> </span>%</span><ha-bar class="  " style="--ha-bar-primary-color: var( --metric-bar-ok-color, var(--success-color) );"><svg><g><rect></rect><rect width="0.1%"></rect></g></svg></ha-bar></div></slot></div></slot></paper-item-body></div><div class="content" style="display: var(--settings-row-content-display, flex); justify-content: flex-end; flex: 1 1 0%; padding: 16px 0px;"><slot></slot></div></ha-settings-row></ha-metric><ha-metric><ha-settings-row style="display: flex; padding: 0px; align-content: normal; align-self: auto; align-items: center; height: 54px; width: 535px;"><div class="prefix-wrap" style="display: var(--settings-row-prefix-display);"><slot name="prefix"></slot><paper-item-body two-line="" style="overflow: hidden; display: var(--layout-vertical_-_display); flex-direction: var(--layout-vertical_-_flex-direction); justify-content: var(--layout-center-justified_-_justify-content); flex: 1 1 0%; min-height: calc( var(--paper-item-body-two-line-min-height, 72px) - 16px ); padding: 8px 16px 8px 0px;"><slot><slot name="heading"><span slot="heading" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">Memory Usage</span></slot><div secondary="" style="overflow: hidden; text-overflow: ellipsis; white-space: normal; font-family: var(--paper-font-body1_-_font-family); -webkit-font-smoothing: var(--paper-font-body1_-_-webkit-font-smoothing); font-size: var(--paper-font-body1_-_font-size); font-weight: var(--paper-font-body1_-_font-weight); line-height: var(--paper-font-body1_-_line-height); color: var(--paper-item-body-secondary-color, var(--secondary-text-color));"><slot name="description"><div slot="description" title="" style="white-space: normal; color: var(--secondary-text-color); display: flex; justify-content: space-between;"><span class="value" style="width: 48px; padding-right: 4px; flex-shrink: 0;">2.7<span> </span>%</span><ha-bar class="  " style="--ha-bar-primary-color: var( --metric-bar-ok-color, var(--success-color) );"><svg><g><rect></rect><rect width="2.7%"></rect></g></svg></ha-bar></div></slot></div></slot></paper-item-body></div><div class="content" style="display: var(--settings-row-content-display, flex); justify-content: flex-end; flex: 1 1 0%; padding: 16px 0px;"><slot></slot></div></ha-settings-row></ha-metric></div></div></div><footer id="actions" class=" mdc-dialog__actions " style="display: flex; position: relative; flex-shrink: 0; flex-wrap: wrap; align-items: center; justify-content: var(--justify-action-buttons, flex-end); box-sizing: border-box; min-height: 52px; margin: 0px; padding: 0px 24px 24px; border-top: 1px solid transparent;"><span style="flex: var(--secondary-action-button-flex, unset);"><slot name="secondaryAction"></slot></span><span style="flex: var(--primary-action-button-flex, unset);"><slot name="primaryAction"><mwc-button slot="primaryAction" style="display: inline-flex; outline: none; -webkit-tap-highlight-color: transparent; vertical-align: top; margin-left: 8px; margin-right: 0px; max-width: 100%; text-align: right;"><button id="button" class="mdc-button   " aria-label="Copy" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-button-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-button-font-size, 0.875rem); line-height: inherit; font-weight: var(--mdc-typography-button-font-weight, 500); letter-spacing: var(--mdc-typography-button-letter-spacing, 0.0892857em); text-decoration: var(--mdc-typography-button-text-decoration, none); text-transform: var(--mdc-typography-button-text-transform, uppercase); position: relative; display: inline-flex; align-items: center; justify-content: center; box-sizing: border-box; min-width: 64px; border: none; outline: none; user-select: none; appearance: none; overflow: hidden; vertical-align: middle; background: transparent; padding-top: 0px; padding-right: var(--mdc-button-horizontal-padding, 8px); padding-bottom: 0px; padding-left: var(--mdc-button-horizontal-padding, 8px); height: 36px; border-radius: var(--mdc-shape-small, 4px); flex: 1 1 auto; color: var(--mdc-theme-primary, #6200ee);"><span class="leading-icon"><slot name="icon"></slot></span><span class="mdc-button__label" style="position: relative;">COPY</span><span class="slot-container   " style="display: inline-flex; align-items: center; justify-content: center;"><slot></slot></span><span class="trailing-icon"><slot name="trailingIcon"></slot></span></button></mwc-button></slot></span></footer></div></div><br class="Apple-interchange-newline">
</body>
</html>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

seems the menu system in hacs last couple releases has made menus for Repository Name, add new/explore/downloaded are all single row small text no longer "card style" is this a change on purpose or is something messed up on my install?

### Reproduction steps

1.open hacs
2.look at selection menu
3.it is very small
...

### Screenshots

![image](https://user-images.githubusercontent.com/12483668/197365117-89df9890-1559-41cd-a528-f99f6e9370e1.png)

### Javascript logs from your browser console

```text
not needeed
```

**Comment by ludeeus** [comment]
This is by design.

**Comment by FragMenthor** [comment]
> ### Web browser
> chrome
> 
> ### Web browser version
> 106.0.5249.119
> 
> ### System Health details
> Version	core-2022.10.4
> Installation Type	Home Assistant OS
> Development	false
> Supervisor	true
> Docker	true
> User	root
> Virtual Environment	false
> Python Version	3.10.5
> Operating System Family	Linux
> Operating System Version	5.15.61-v8
> CPU Architecture	aarch64
> Timezone	America/Chicago
> Configuration Directory	/config
> ### Core Metrics
> Processor Usage
> 0.9 %
> Memory Usage
> 9.8 %
> ### Supervisor Metrics
> Processor Usage
> 0.1 %
> Memory Usage
> 2.7 %
> COPY
> 
> ### Checklist
> * [x]  I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
> * [x]  I have filled out the issue template to the best of my ability.
> * [x]  I have read https://hacs.xyz/docs/issues
> * [x]  This issue is related to the frontend of HACS.
> * [x]  This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
> * [x]  This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).
> 
> ### Describe the issue
> seems the menu system in hacs last couple releases has made menus for Repository Name, add new/explore/downloaded are all single row small text no longer "card style" is this a change on purpose or is something messed up on my install?
> 
> ### Reproduction steps
> 1.open hacs 2.look at selection menu 3.it is very small ...
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/12483668/197365117-89df9890-1559-41cd-a528-f99f6e9370e1.png)
> 
> ### Javascript logs from your browser console
> ```
> not needeed
> ```
> 
> ### Diagnostics dump
> _No response_

Did you manage to get to the old format, with the categories ? Also liked much better, all in one place is pure chaos, if it is by design (definitely new), i think it got worse... I can get to the old format if I disable experimental features, but I lose update sensors for the integration in HACS. Any good solution? Thanks.
