### ISSUE TITLE
No icons in HACS after update to hacs 1.28.3

### ISSUE THREAD

**Issue by hugalafutro** [hacs/integration#2912]
### Web browser

Vivaldi (chrome)

### Web browser version

5.5.2805.38 (Chrome/106.0.0.0)

### System Health details

I have never seen the card mentioned nor do I have any idea how to access it. The link just shows the card I never seen without providing instructions how to open it.

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

No icons in HACS see screenshot

### Reproduction steps

1. update hacs to 1.28.3
2. restart ha
3. look in the hacs menu and despair

### Screenshots

![image](https://user-images.githubusercontent.com/30209689/197383226-c7597ca9-7d8d-48c2-aa0e-9f98f1985e1a.png)

### Javascript logs from your browser console

```text
No idea what that is/how to get it.
```

### Diagnostics dump

https://o.o5.ddns.net/inYiA

**Comment by ludeeus** [comment]
Your client cannot access brands.home-assistant.io

**Comment by hugalafutro** [comment]
But the client can access it ok, it just don't work in HA

```
pi@pi-docker:~ $ dig brands.home-assistant.io

; <<>> DiG 9.16.33-Debian <<>> brands.home-assistant.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27835
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;brands.home-assistant.io.      IN      A

;; ANSWER SECTION:
brands.home-assistant.io. 300   IN      A       104.26.4.238
brands.home-assistant.io. 300   IN      A       172.67.68.90
brands.home-assistant.io. 300   IN      A       104.26.5.238

;; Query time: 47 msec
;; SERVER: 192.168.1.101#53(192.168.1.101)
;; WHEN: Sun Oct 23 10:01:41 BST 2022
;; MSG SIZE  rcvd: 101

pi@pi-docker:~ $ wget https://github.com/home-assistant/brands/blob/master/core_brands/amazon/icon.png
--2022-10-23 10:02:14--  https://github.com/home-assistant/brands/blob/master/core_brands/amazon/icon.png
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘icon.png’

icon.png                                                                  [ <=>                                                                                                                                                                     ] 133.33K  --.-KB/s    in 0.06s

2022-10-23 10:02:15 (2.35 MB/s) - ‘icon.png’ saved [136530]

```

**Comment by hugalafutro** [comment]
Ok If I go and right click on each icon and Image/Relaod it loads, but it's troublesome. I have cleared Browser cache beforehand and restarted the browser for good measure too.
