### ISSUE TITLE
Error with every custom repo tried - Repository structure for v4.24.0 is not compliant

### ISSUE THREAD

**Issue by c0nt4x** [hacs/integration#2916]
## System Information

version | core-2022.10.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.72
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4996
Installed Version | 1.28.3
Stage | running
Available Repositories | 1142
Downloaded Repositories | 28

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 1, 2018 at 12:00 AM
relayer_connected | false
remote_enabled | true
remote_connected | false
alexa_enabled | false
google_enabled | false
remote_server | null
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.0
agent_version | 1.4.1
docker_version | 20.10.17
disk_total | 234.0 GB
disk_used | 6.3 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), Terminal & SSH (9.6.1), File editor (5.4.1), AdGuard Home (4.7.4), AirCast (3.4.1), Grafana (8.0.2), Home Panel (2.5.0), InfluxDB (4.5.0), Tor (4.0.2), WireGuard (0.7.0), Git pull (7.13.1), AppDaemon (0.9.3), Mosquitto broker (6.1.3), Home Assistant Google Drive Backup (0.108.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 10
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 14, 2022 at 4:17 PM
-- | --
current_recorder_run | October 24, 2022 at 9:24 AM
estimated_db_size | 340.84 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Each time I try and add any custom repo from github I receive the error - Repository structure for v4.24.0 is not compliant

This has only started to happen recently in the last couple of weeks.

### Reproduction steps

1. Explore & Download Repositories
2. Click the 3 dots
3. Custom Repositories
4. Paste link from github repo
5. Select Category
6. Select Add

![Untitled](https://user-images.githubusercontent.com/70321584/197488939-2cf00e4f-7a38-4ad0-bd5d-36ae1fb116aa.png)

### Debug logs

```text
I have the hacs debug logging set up in my configuration.yaml but can't locate where the logs are as the documentation doesn't state the location and I've looked in HA logs drop down but HACS is not an option.
```

### Diagnostics dump

[config_entry-hacs-195264a99441d6c595e411f45571b6e8.json.txt](https://github.com/hacs/integration/files/9850336/config_entry-hacs-195264a99441d6c595e411f45571b6e8.json.txt)

**Comment by ludeeus** [comment]
HACS requires a specific structure for each category, it’s up to the author to make it compliant or not.
