### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by JachinY** [hacs/integration#2918]
## System Information

version | core-2022.10.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.61-v8
arch | aarch64
timezone | Asia/Shanghai
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | failed to load: unreachable
GitHub Web | ok
GitHub API Calls Remaining | 4780
Installed Version | 1.28.3
Stage | running
Available Repositories | 1135
Downloaded Repositories | 35

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.0
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 57.8 GB
disk_used | 10.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), Simple Proxy (1.0.6), tunnel2local (1.0.10), File editor (5.4.1), NGINX Home Assistant SSL proxy (3.1.5), Mosquitto broker (6.1.3), Terminal & SSH (9.6.1), ESPHome (2022.10.0), Node-RED (13.5.0), Raw WireGuard (0.1.2), SSH & Web Terminal (12.0.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 14
-- | --
resources | 16
views | 23
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 2022年10月21日 16:55
-- | --
current_recorder_run | 2022年10月28日 00:18
estimated_db_size | 197.41 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Xiaomi Gateway 3</summary>

version | 2.1.2 (5794f47)
-- | --

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.0
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 34

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Unable to update integration

### Reproduction steps

Update Integration

### Debug logs

```text
Logger: custom_components.hacs
Source: custom_components/hacs/base.py:691
Integration: HACS (documentation, issues)
First occurred: 00:21:09 (63 occurrences)
Last logged: 15:15:08

Download failed - Cannot connect to host raw.githubusercontent.com:443 ssl:default [Connect call failed ('::', 443, 0, 0)]
Download failed - Cannot connect to host raw.githubusercontent.com:443 ssl:default [Connect call failed ('0.0.0.0', 443)]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('::', 443, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 691, in async_download_file
    request = await self.session.get(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [Connect call failed ('::', 443, 0, 0)]
```

**Comment by ludeeus** [comment]
Broken network, not integration issue.
