### ISSUE TITLE
Entering into a repository and going back to explore repository page causes UI to jump to top position and not position of the last repository entered

### ISSUE THREAD

**Issue by duan-dt** [hacs/integration#2921]
### Web browser

Edge, Safari

### Web browser version

Edge 107.0.1418.26, Safari (iOS 16.1 (20B82)

## System Information

version | core-2022.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.74
arch | x86_64
timezone | Africa/Johannesburg
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4696
Installed Version | 1.28.3
Stage | running
Available Repositories | 1131
Downloaded Repositories | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 17, 2022 at 2:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | ap-southeast-1-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | pending
can_reach_cloud | pending

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 457.7 GB
disk_used | 13.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.4.1), ESPHome (2022.10.2), Studio Code Server (5.4.0), JupyterLab (0.9.1), AdGuard Home (4.7.4), Terminal & SSH (9.6.1), Z-Wave JS (0.1.74), UniFi Network Application (2.4.0), Vaultwarden (Bitwarden) (0.17.3), Uptime Kuma (0.3.0), motionEye (0.18.0), InfluxDB (4.5.0), Glances (0.16.0), Folding@home (0.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 10
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 26, 2022 at 7:51 PM
-- | --
current_recorder_run | November 5, 2022 at 7:15 PM
estimated_db_size | 234.04 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Sonoff</summary>

version | 3.3.1 (b20e33c)
-- | --
cloud_online | 0 / 9
local_online | 0 / 0

</details>

<details><summary>Xiaomi MIoT</summary>

logged_in | true
-- | --
can_reach_micloud_server | pending
accounts_count | 1
account_devices_count | 0

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Selecting and entering a repository from the repository explorer and then going back to the repository explorer causes the page position to jump back to top and not at the last position before entering the repository.  This makes it hard to find the previous position again.  

Example in iOS shown but the same is experienced on other platforms

### Reproduction steps

1.Open HACS in Home Assistant
2.Select "+" or "Explore and Download Repositories".
3.Scroll down to any repository
4. Enter repository
5. Go back by pressuing "<-"
6. Position will return to top and not to last position prior to entering the repository
...

### Screenshots

https://user-images.githubusercontent.com/63410825/200134208-d7738726-c186-45e2-8727-d5f2e22fbb03.mov

### Javascript logs from your browser console

```text
Compatibility
'content-type' header charset value should be 'utf-8'.
'content-type' header media type value should be 'image/png', not 'text/html'.
Performance
A 'cache-control' header is missing or empty.
Resource should use cache busting but URL does not match configured patterns.
Static resources should use a 'cache-control' header with 'max-age=31536000' or more.
Static resources should use a 'cache-control' header with the 'immutable' directive.
Security
Response should include 'x-content-type-options' header.
The 'Expires' header should not be used, 'Cache-Control' should be preferred.
The 'server' header should only contain the server name.
Other
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
```

**Comment by ludeeus** [comment]
It does not keep position.
That is a missing feature not a bug.
