### ISSUE TITLE
Retain execution permission from files

### ISSUE THREAD

**Issue by felipecrs** [hacs/integration#2923]
### System Health details

N/A

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I have a custom integration which comes with a script, which can be reused by users without having to create their own:

https://github.com/felipecrs/hass-expose-camera-stream-source/blob/master/custom_components/expose_camera_stream_source/get_stream.sh

The script above has execution permission set (`chmod +x`/`git add --chmod=+x`), but when HACS installs it, the execution permission is lost.

### Reproduction steps

Install my custom component, and try to run:

```console
/config/custom_components/expose_camera_stream_source/get_stream.sh
```

It will fail with permission denied.

If you instead clone the repository by ourself, you won't get permission denied.

### Debug logs

```text
N/A
```

### Diagnostics dump

N/A

**Comment by felipecrs** [comment]
I have skipped some parts of the issue template since I don't think they're applicable.

**Comment by ludeeus** [comment]
HACS download files by using the API, not git CLI.
If you need that, then HACS is not usable for that repository.

**Comment by felipecrs** [comment]
Would you accept a PR to fix this? I suppose I can use the API to fetch whether the file has execution permission or not and properly restore it as well.

**Comment by ludeeus** [comment]
No, that is not something I’m willing to support

**Comment by felipecrs** [comment]
I understand.

There's another thing. If you use API to download the repository archive as a tarball, and then extract the tarball, the execution permission should be retained as well.

What do you think?
