### ISSUE TITLE
Request for removal of robert-alfaro/xfinity-usage

### ISSUE THREAD

**Issue by hubertron** [hacs/integration#2925]
### Repository

robert-alfaro/xfinity-usage

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Multiple tickets as far back as 2020 that this this plugin no longer works. There have been plenty of changes to HA recently and this one just hasnt made it through the times.

### Link to issue

https://github.com/robert-alfaro/xfinity-usage/issues/14

**Comment by ludeeus** [comment]
This is not included in HACS, so there is nothing to remove.
