### ISSUE TITLE
Error while loading page entry

### ISSUE THREAD

**Issue by FPF92** [hacs/integration#2929]
### Web browser

Safari

### Web browser version

16.1 (16614.2.9.1.13, 16614)

## System Information

version | core-2022.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.61-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4509
Installed Version | 1.28.3
Stage | running
Available Repositories | 1210
Downloaded Repositories | 18

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 116.7 GB
disk_used | 19.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba Backup (5.2.0), File editor (5.4.2), Node-RED (13.5.2), SSH & Web Terminal (12.1.2), UniFi Network Application (2.4.1), deCONZ (6.17.0), Samba share (10.0.0), Check Home Assistant configuration (3.11.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 14
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 8, 2022, 19:54
-- | --
current_recorder_run | November 17, 2022, 08:54
estimated_db_size | 537.44 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Sonoff</summary>

version | 3.3.1 (b20e33c)
-- | --
cloud_online | 1 / 1
local_online | 0 / 0

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

HACS page doesn't display content. 

"Error while loading page entry." is shown

### Reproduction steps

1.
2.
3.
...

### Screenshots

<img width="1424" alt="Bildschirmfoto 2022-11-17 um 09 10 20" src="https://user-images.githubusercontent.com/48443887/202391531-8e617665-78b1-4f9a-b8db-d9527f6737d6.png">

### Javascript logs from your browser console

```text
[Info] CARD-MOD 3.1.5 IS INSTALLED (card-mod.js, line 5)
[Info] You may not be getting optimal performance out of card-mod. (card-mod.js, line 5)
See https://github.com/thomasloven/lovelace-card-mod#performance-improvements
[Info] BROWSER_MOD 2.1.3 IS INSTALLED (browser_mod.js, line 373)
    BrowserID: d3e7ae85-847b9470
[Warning] The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information. (slider-entity-row.js, line 1)
[Info] SLIDER-ENTITY-ROW 17.2.1 IS INSTALLED – "" (slider-entity-row.js, line 59)
[Log] AUTO-ENTITIES 1.11.0 IS INSTALLED (auto-entities.js, line 172)
[Log] Readme: – "https://github.com/thomasloven/lovelace-auto-entities" (auto-entities.js, line 172)
[Info]   BUTTON-CARD   (button-card.js, line 425)
 Version 3.4.2 
[Info]  MINI-GRAPH-CARD  0.11.0  (mini-graph-card-bundle.js, line 1)
[Info]   LIGHT-ENTITY-CARD    (light-entity-card.js, line 6868)
  Version 5.0.0       
[Info]   SLIDER-BUTTON-CARD  v1.10.9  (slider-button-card.js, line 497)
[Info]   ---- MY-SLIDER ----  (my-cards.js, line 186)
  Version 3.0.3    
[Info]   ---- MY-SLIDER-V2 ----  (my-cards.js, line 356)
  Version 3.0.3    
[Info] HELLO FROM SLIDER-V2 (my-cards.js, line 356)
[Info]   ---- MY-BUTTON ----  (my-cards.js, line 375)
  Version 1.0.0    
[Info]   ---- MY-CARDS ----  (my-cards.js, line 436)
  Version 2.0.1    
[Info]    XIAOMI-VACUUM-MAP-CARD    (xiaomi-vacuum-map-card.js, line 903)
   Version v2.1.2           
[Info]   SIDEBAR-CARD             (sidebar-card.js, line 661)
  Version: 0.1.8.4        
[Error] Error: Failed to execute 'define' on 'CustomElementRegistry': the name "sidebar-card" has already been used with this registry
	(anonyme Funktion) (app.0706b45e.js:850:114175)
	Modulcode (sidebar-card.js:412:13324)
	evaluate
	moduleEvaluation
[Error] Error loading page – "entry"
TypeError: a.translations is not an Object. (evaluating 'e in a.translations')
I — c.aaeac12d.js:402
(anonyme Funktion) — c.aaeac12d.js:492
(anonyme Funktion) — c.aaeac12d.js:495
promiseReactionJob
	(anonyme Funktion) (main-ec7846c8.js:1513:1708)
	promiseReactionJob
```

**Comment by ludeeus** [comment]
Clear cache/use another browser

**Comment by FPF92** [comment]
> Clear cache/use another browser

I already did this. But it doesn’t work. With other browsers I don’t have the issue

**Comment by flappysquirrel** [comment]
I did this, as well. Cleared cache, used my local ip instead of 

`http://homeassistant.local:8123/hacs`.

Opening a random repository like 

`http://homeassistant.local:8123/hacs/repository/241706284`

used to help, but not anymore.

I also tried deleting cookies for Home Assistant, https://hacs.xyz, and Github.

**Comment by ericmharris** [comment]
Not sure if this will help but I found the following in the logs:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/websocket/repositories.py:68
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 6:53:13 AM (3 occurrences)
Last logged: 6:56:26 AM

[139749141617568] Error handling message: Unknown error (unknown_error) from ::ffff:9a15:14d5 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.10.8/lib/python3.10/site-packages/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/opt/homeassistant/custom_components/hacs/websocket/repositories.py", line 68, in hacs_repositories_list
    for repo in hacs.repositories.list_all
AttributeError: 'NoneType' object has no attribute 'repositories'
```

After updating repositories.py (custom_components/hacs/websocket/repositories.py:35) with some logging (same approach as in base.py ... log.info(bla, bla) ) for  hacs_repositories_list() I restarted homeassistant ... and the problem went away.  Must be some sort of caching issue?
