### ISSUE TITLE
HACS won't start, uninstalled and reinstalled.  same issue

### ISSUE THREAD

**Issue by samsiam** [hacs/integration#2931]
## System Information

version | core-2022.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.74
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.28.3
Stage | null
Available Repositories | 0
Downloaded Repositories | 0
Disabled | restore

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 30.8 GB
disk_used | 10.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.1.3), Grafana (8.1.0), File editor (5.4.2), ESPHome (2022.11.1), Samba share (10.0.0), Terminal & SSH (9.6.1), InfluxDB (4.5.0), FTP (4.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 11, 2022 at 6:51 PM
-- | --
current_recorder_run | November 19, 2022 at 5:01 PM
estimated_db_size | 79.65 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Working in HA, I noticed HACS disappeared from menu side bar.  Checked and found it failed to start with following errors below.  I searched and found a suggestion to uninstall, delete folder, restart HA 2x and de-auth.  I then tried reinstalling and get the same errors in log (below) after "fresh" install.  I do find an error referring to HACS but am not sure what it is referring to - see debug log line 1.

HACS is disabled - HacsDisabledReason.RESTORE
4:33:26 AM – (ERROR) HACS (custom integration) - message first occurred at November 19, 2022 at 5:01:55 PM and shows up 94 times
Could not read /config/.storage/hacs.repositories, restore the file from a backup - unexpected character: line 14690 column 20 (char 488454)
4:33:26 AM – (ERROR) HACS (custom integration) - message first occurred at November 19, 2022 at 5:01:55 PM and shows up 94 times
Could not parse JSON content: /config/.storage/hacs.repositories
4:33:26 AM – (ERROR) util/json.py - message first occurred at November 19, 2022 at 5:01:55 PM and shows up 94 times

### Reproduction steps

1. Not really sure what I did to cause this.  I did install or configure UnPnP to get stats from my Google WIFI but I am unsure when the issue occurred, before - during - or after.
2.
3.
...

### Debug logs

```text
* CANNOT PASTE FULL LOG *  ISSUE SUBMISSION FAILS FOR BEING TOO LONG

HACS is disabled - HacsDisabledReason.RESTORE
4:56:24 AM – (ERROR) HACS (custom integration)
Could not read /config/.storage/hacs.repositories, restore the file from a backup - unexpected character: line 14690 column 20 (char 488454)
4:56:24 AM – (ERROR) HACS (custom integration)
Could not parse JSON content: /config/.storage/hacs.repositories
```

### Diagnostics dump

I have no option for diagnostics dump.

![image](https://user-images.githubusercontent.com/71104315/202898532-e358d301-47db-4ca9-bea4-faadcde8b5f4.png)

**Comment by ludeeus** [comment]
Your `/config/.storage/hacs.repositories` file is corrupt, restore it from a backup.

**Comment by samsiam** [comment]
> Your `/config/.storage/hacs.repositories` file is corrupt, restore it from a backup.

ah.  i missed the /.storage - did not realize it was a folder.
thanks!  restored and it started
