### ISSUE TITLE
'sections.pending_repository_upgrade' shown

### ISSUE THREAD

**Issue by mediocaballero** [hacs/integration#2932]
### Web browser

Chrome

### Web browser version

107.0.5304.107

### System Health details

n/a

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

On my HACS installation (updated to latest release) it seems like there's some incorrect key or placeholder for the Spanish translation... I checked on lokalise and it seems it's 100% so maybe it's a wrong text key or something?
It reads 'sections.pending_repository_upgrade' under the updateable custom components... 

https://i.imgur.com/VTL9A0x.png

### Reproduction steps

1. Load HACS with Spanish as the frontend language
2. Have repositories pending upgrade

### Screenshots

![image](https://user-images.githubusercontent.com/12327380/202938304-50d8dde3-598c-404f-a064-b3bd5de1bd0b.png)

### Javascript logs from your browser console

```text
n/a
```

**Comment by ludeeus** [comment]
Translations should not change placeholder text.
But this part does not exist anymore.
Enable experimental features or wait for new UI to fix it.
