### ISSUE TITLE
Automation tab sometimes disappears, re-appearing with non-installed scripts

### ISSUE THREAD

**Issue by vingerha** [hacs/integration#2945]
### Web browser

Edge

### Web browser version

latest

## System Information

version | core-2022.11.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.0-53-generic
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4698
Installed Version | 1.28.4
Stage | running
Available Repositories | 1169
Downloaded Repositories | 43

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 39

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 30
views | 22
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 22 November 2022 at 00:00
-- | --
current_recorder_run | 1 December 2022 at 10:09
estimated_db_size | 1098.06 MiB
database_engine | mysql
database_version | 10.6.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

From time to time the third tab 'Automations' disappears and when it appears again it does not recognize the scripts already installed...who are indeed still in config/python_scripts.
It is not urgent but just odd

### Reproduction steps

cannot reproduce so I know this might not be of any help to solve

### Screenshots

This appeared later today, earlier it did nt show the Automations tab. I again clicked on the entities script but it was already there in the folder
![image](https://user-images.githubusercontent.com/44190435/205122004-19c4a85f-e4a7-4492-b71a-b0c0b64b5d25.png)

### Javascript logs from your browser console

```text
n.a.
```

### Diagnostics dump

n.a.

**Comment by ludeeus** [comment]
It will diapers when the python integration in home assistant fails to load.
