### ISSUE TITLE
Cannot get non-experimental UI

### ISSUE THREAD

**Issue by elad-bar** [hacs/integration#2947]
### Web browser

Chrome

### Web browser version

latest

## System Information

version | core-2022.11.5
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.0-52-generic
arch | x86_64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 3685
Installed Version | 1.28.4
Stage | running
Available Repositories | 1159
Downloaded Repositories | 33

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 19
views | 16
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 30, 2022 at 8:20 AM
-- | --
current_recorder_run | December 2, 2022 at 12:37 PM
estimated_db_size | 773.00 MiB
database_engine | mysql
database_version | 10.10.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

UI of HACS is the experimental one although I turned off the `experimental` flag in configuration.

Attempts to change consisted with:
- Turn of the experimental flag
- Removing it from the core entities directly
- Removing and reinstall HACS (after cleaning all the hacs data in .storage)
- Incognito mode, still getting experimental UI.

In 2nd environment of testing, works with non experimental UI.

### Reproduction steps

1.
2.
3.
...

### Screenshots

![image](https://user-images.githubusercontent.com/3207137/205275197-345a090e-d580-4ced-b1e5-00aba6658e79.png)

### Javascript logs from your browser console

```text
no logs in console (all clean)
```

**Comment by elad-bar** [comment]
Link to the HA forum with additional people experiencing the same issue:
https://community.home-assistant.io/t/hacs-as-a-list/474050/8

**Comment by ludeeus** [comment]
You have to restart home assistant and clear cache after

**Comment by elad-bar** [comment]
Why did you close the issue, i have done it and wrote that i have done it
