### ISSUE TITLE
HACS in Dark mode loads white page for a moment

### ISSUE THREAD

**Issue by Chupaka** [hacs/integration#2957]
### Web browser

Chrome

### Web browser version

108

## System Information

version | core-2022.12.1
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | homeassistant
virtualenv | true
python_version | 3.10.9
os_name | Linux
os_version | 5.4.0-1035-oracle
arch | x86_64
timezone | Europe/Minsk
config_dir | /home/homeassistant/.homeassistant

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4996
Installed Version | 1.28.4
Stage | running
Available Repositories | 1156
Downloaded Repositories | 5

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 32

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 0
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 9, 2022 at 12:36
-- | --
current_recorder_run | December 10, 2022 at 22:47
estimated_db_size | 301.38 MiB
database_engine | sqlite
database_version | 3.31.1

</details>

<details><summary>Xiaomi Gateway 3</summary>

version | 2.1.2 (4894b05)
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When Home Assistant dark mode in effect and I open HACS, it first loads a blank white page for a moment (or even more if it wasn't recently accessed). That's not very pleasant for eyes when it's dark everywhere :)

### Reproduction steps

1. Open Home Assistant in Dark mode in a dark room (in your browser or in Android app).
2. Open HACS tab.
3. Close your eyes for a moment because of the bright light.

### Screenshots

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/3432808/207038853-2084fa6a-8919-46c0-943b-a5de6e2bbb45.png">

### Javascript logs from your browser console

```text
Irrelevant
```

**Comment by ludeeus** [comment]
This looks like a Home Assistant issue.

**Comment by xZetsubou** [comment]
This is a common issue in chrome and some other browsers called `WhiteFlash` it been more then 10yrs yet they still didn't fix it, you can fix this by force dark mode in chrome [chrome://flags/#enable-force-dark](chrome://flags/#enable-force-dark) but it might break the UI in some websites tho there might be better way to fix it,

**Comment by Chupaka** [comment]
Well, at least going to any dashboards, or Settings, or Logbook etc does not produce the same blinking...

**Comment by Chupaka** [comment]
So, the possible solution is https://css-tricks.com/prevent-white-flash-iframe/ or some other `<iframe style="opacity: 0;" onload="this.style.opacity = 1;">`?..
