### ISSUE TITLE
Add Repository Dialog changing size when typing

### ISSUE THREAD

**Issue by dklemm** [hacs/integration#2966]
### Web browser

Chrome

### Web browser version

108.0.5359.124 

## System Information

version | core-2022.12.7
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 4.19.0-12-amd64
arch | x86_64
timezone | Europe/London
config_dir | /config

<summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4741
Installed Version | 1.29.0
Stage | running
Available Repositories | 1200
Downloaded Repositories | 28

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When searching in the Add Repository Dialog the size of the dialog changes size are you type to accommodate the results.  

### Reproduction steps

1. Open Explore & Download Repositories (AKA Add Repository Dialog)
2. Start typing in Search for repository input 
3.
...

### Screenshots

<img width="1248" alt="Screenshot 2022-12-21 at 15 55 45" src="https://user-images.githubusercontent.com/2111972/208947622-789ea794-23d9-4d7c-98e2-e22764264666.png">
<img width="1244" alt="Screenshot 2022-12-21 at 15 55 54" src="https://user-images.githubusercontent.com/2111972/208947624-65c842ca-a199-486d-98d8-8de7e10f5129.png">
<img width="1243" alt="Screenshot 2022-12-21 at 15 56 02" src="https://user-images.githubusercontent.com/2111972/208947626-48982786-7c77-465c-b539-5a5e4dc3ad38.png">

### Javascript logs from your browser console

```text
N/A
```

**Comment by ludeeus** [comment]
This will not be changed as this has been removed in the upcoming (now experimental) UI.
