### ISSUE TITLE
Tile Overflow Issues

### ISSUE THREAD

**Issue by KyleStilkey** [hacs/integration#2967]
### Web browser

Chrome

### Web browser version

108.0.5359.125

## System Information

version | core-2022.12.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v8
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4779
Installed Version | 1.29.0
Stage | running
Available Repositories | 1199
Downloaded Repositories | 31

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.2
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 116.8 GB
disk_used | 25.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), Grocy (0.18.3), Studio Code Server (5.5.0), Mosquitto broker (6.1.3), Samba share (10.0.0), Terminal & SSH (9.6.1), Ring-MQTT with Video Streaming (5.0.5), ESPHome (2022.12.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 14
-- | --
resources | 18
views | 17
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 11, 2022 at 8:02 PM
-- | --
current_recorder_run | December 20, 2022 at 6:39 PM
estimated_db_size | 2119.36 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Sonoff</summary>

version | 3.3.1 (b20e33c)
-- | --
cloud_online | 1 / 4
local_online | 1 / 1

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

It seems like there is a tile overflow issue that causes some text and buttons to overlap each other causing a visual issue and sometimes hard to interact with them like dismissing a new integration due to the dismiss button being placed behind another integration tile.

### Reproduction steps

1. Open up HACS
2. Check the tiles and see that there are some integrations that overflow

### Screenshots

![image](https://user-images.githubusercontent.com/6766223/208972762-21b2cfca-9310-4af1-bd20-a9dacdb526a9.png)
![image](https://user-images.githubusercontent.com/6766223/208972881-a74d20ce-c56c-4cc2-9cee-dd20db947678.png)

### Javascript logs from your browser console

```text
/hacsfiles/banner-card/banner-card.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
/hacsfiles/mini-graph-card/mini-graph-card-bundle.js?hacstag=1512800620110:1          Failed to load resource: the server responded with a status of 404 (Not Found)
/hacsfiles/mini-media-player/mini-media-player-bundle.js?hacstag=1485208381164:1          Failed to load resource: the server responded with a status of 404 (Not Found)
/hacsfiles/lovelace-mushroom/mushroom.js?hacstag=444350375188:1          Failed to load resource: the server responded with a status of 404 (Not Found)
/hacsfiles/button-card/button-card.js?hacstag=146194325342:1          Failed to load resource: the server responded with a status of 404 (Not Found)
/hacsfiles/lovelace-thermostat-dark-card/thermostat-dark-card.js?hacstag=139634406005:1          Failed to load resource: the server responded with a status of 404 (Not Found)
/hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js?hacstag=142051833042:1          Failed to load resource: the server responded with a status of 404 (Not Found)
room-card.js?hacstag=45444094910705:26  ROOM-CARD  1.07.05
roku-card.js?hacstag=164367214124:187   ROKU-CARD       Version 1.3.0 
layout-card.js?hacstag=156434866244:228 LAYOUT-CARD 2.4.4 IS INSTALLED
mwc-list-item-base.ts:224 Uncaught (in promise) https://stilkdog.duckdns.org/hacsfiles/banner-card/banner-card.js
mwc-list-item-base.ts:224 Uncaught (in promise) https://stilkdog.duckdns.org/hacsfiles/mini-graph-card/mini-graph-card-bundle.js?hacstag=1512800620110
mwc-list-item-base.ts:224 Uncaught (in promise) https://stilkdog.duckdns.org/hacsfiles/mini-media-player/mini-media-player-bundle.js?hacstag=1485208381164
mwc-list-item-base.ts:224 Uncaught (in promise) https://stilkdog.duckdns.org/hacsfiles/lovelace-mushroom/mushroom.js?hacstag=444350375188
mwc-list-item-base.ts:224 Uncaught (in promise) https://stilkdog.duckdns.org/hacsfiles/button-card/button-card.js?hacstag=146194325342
mwc-list-item-base.ts:224 Uncaught (in promise) https://stilkdog.duckdns.org/hacsfiles/lovelace-thermostat-dark-card/thermostat-dark-card.js?hacstag=139634406005
mwc-list-item-base.ts:224 Uncaught (in promise) https://stilkdog.duckdns.org/hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js?hacstag=142051833042
vacuum-card.js?hacstag=261291295263:4  VACUUM-CARD  2.6.2 
clock-weather-card.js?hacstag=522634019109:171   CLOCK-WEATHER-CARD  Version: 1.0.9
swiss-army-knife-card.js?hacstag=2147861121003:1    SWISS-ARMY-KNIFE-CARD     Public Release Candidate      Version 1.0.0-rc.3    
index.js:126 Uncaught (in promise) Error: entity not found.
    at e.formatTrackingNumbers (index.js:126:1)
    at e.render (index.js:46:1)
    at e.value (lit-element.ts:217:33)
    at e.value (updating-element.ts:704:14)
    at e.<anonymous> (updating-element.ts:653:27)
    at s (runtime.js:45:15)
    at Generator._invoke (runtime.js:271:1)
    at t.<computed> [as throw] (runtime.js:97:1)
    at ft (shady-render.ts:150:65)
    at a (updating-element.ts:207:1)
DevTools failed to load source map: Could not load content for https://stilkdog.duckdns.org/local/community/swiss-army-knife-card/dist/svg-injector.map.js: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by ludeeus** [comment]
This will not be changed as this has been removed in the upcoming (now experimental) UI.
