### ISSUE TITLE
[Feature] It would be amazing to disable a plug-in without removing it

### ISSUE THREAD

**Issue by zanna-37** [hacs/integration#2971]
### System Health details

_N/A_

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The only way to disable a plugin is removing it. It would be handy to have a way to disable it while keeping it on the list of installed components. This should be similar to how Home Assistant manages integrations.

-----

Note: _Found no other way to suggest a feature, if such a place exist, maybe it should also be stated in https://hacs.xyz/docs/issues. The discussion page is currently disabled._

### Reproduction steps

_N/A_

### Debug logs

```text
_N/A_
```

**Comment by ludeeus** [comment]
If anything this needs to be added to home assistant not have.

**Comment by zanna-37** [comment]
I think you understood it wrong.
I'm talking about disabling frontend and integration repositories.

To be clearer, I'm referring to this menu, which is HACS.
![immagine](https://user-images.githubusercontent.com/43404980/209547831-8eee53d6-eeb1-47e1-9880-feec7e9afa35.png)

**Comment by ludeeus** [comment]
No, I understand fine.
It's just not something that can be done, as HACS does not load it, home assistant does.

**Comment by zanna-37** [comment]
Sure, but you could move the files in another folder so that they are no more loaded.

Think about a frontend plug in. It's loaded because it stays in a particular folder that HA reads.

You could implement the disable button that does the same thing the "remove button" does. But instead of deleting files, they are moved to another folder.

**Comment by zanna-37** [comment]
Would it be viable?

**Comment by ludeeus** [comment]
Not for HACS.
