### ISSUE TITLE
info.md Template missing

### ISSUE THREAD

**Issue by dt215git** [hacs/integration#2972]
### Describe the issue

On the https://hacs.xyz/docs/publish/start page, the "See the templates section..." link doesn't go anywhere, the https://hacs.xyz/docs/publish/start#templates endpoint seems to be missing.

I was hoping there'd be some guidance on how to structure the info.md file, especially when it comes to linking images to include.
Thanks

### Screenshots

![image](https://user-images.githubusercontent.com/86194065/209718984-095b8869-dfdb-4607-9aba-5db718c804a2.png)

**Comment by ludeeus** [comment]
Reference removed in <https://github.com/hacs/documentation/commit/9ae435bf789048a4046ef1bc56ac46673038be23>
Side note, do not use `info.md`, set `"render_readme": true,` in `hacs.json` instead.
