### ISSUE TITLE
FR: When browsing addons

### ISSUE THREAD

**Issue by deanfourie1** [hacs/integration#2973]
### System Health details

Healthy, no issues.

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

This is more of a feature request i guess then a issue, but I often just browse through the third party addons and look for stuff to install and play with etc.

One thing ive noticed is that every time I open a addon and view the details and screenshots etc, when I go back to the addons it has exited the menu and I have to re open the addons mean and scroll right back down to where I was.

Not sure if this is anything you will invest time in, but its really annoying having to scroll all the way back down to where I was after checking the information on each addon.

Is it possible to maybe implement a fix for this?

Love your work!

### Reproduction steps

Open a addon details, 

Go back and the search/browse windows has closed.

Open it again, and you need to start again from the top.

### Debug logs

```text
None required.
```

**Comment by ludeeus** [comment]
Noted. Maybe for future.
