### ISSUE TITLE
Hacs install stuck

### ISSUE THREAD

**Issue by ravebp** [hacs/integration#2976]
### System Health details

System is ok

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I had hacs on my system  (raspberry 3),but than it disappeared.wheb trying to reinstall I got stock with the screenshot aarached
![Screenshot_20221230_185243_Home Assistant](https://user-images.githubusercontent.com/73950492/210099418-5e3cc715-7d94-4a9e-bce1-e8bf3f844109.jpg)

### Reproduction steps

1.reinstall from ssh
2.reboot
3. Adding integration 
...

### Debug logs

```text
No log
```

### Diagnostics dump

Got error when receiving: timed out
7:00:14 PM – (ERROR) /usr/local/lib/python3.10/site-packages/miio/miioprotocol.py - message first occurred at 3:50:43 PM and shows up 738 times
Update of sensor.csepegteto_zone_history is taking over 10 seconds
7:00:05 PM – (WARNING) helpers/entity.py - message first occurred at 3:50:34 PM and shows up 758 times
Disconnected from MQTT server core-mosquitto:1883 (7)
6:59:53 PM – (WARNING) MQTT - message first occurred at 6:57:07 PM and shows up 2 times
Updating xiaomi_miio switch took longer than the scheduled update interval 0:00:30
6:57:19 PM – (WARNING) Switch - message first occurred at 6:55:47 PM and shows up 4 times
Error fetching hassio data: Error on Supervisor API:
6:57:05 PM – (ERROR) Home Assistant Supervisor
Timeout on /addons/e92a3241_paradox_alarm_interface/stats request
6:57:03 PM – (ERROR) Home Assistant Supervisor - message first occurred at 3:54:26 PM and shows up 252 times
Updating bhyve sensor took longer than the scheduled update interval 0:00:30
6:56:56 PM – (WARNING) Sensor - message first occurred at 6:56:56 PM and shows up 3 times
Updating xiaomi_miot select took longer than the scheduled update interval 0:00:30
6:56:56 PM – (WARNING) Select

**Comment by ludeeus** [comment]
Your system is not ok...
You get timeouts everywhere, fix that before trying HACS.
If it still show like that, clear browser cache (it's home assistant not HACS that provides that text)

**Comment by ravebp** [comment]
Also tried that .tried withcdifferent browsers phone app and everything.
Also tried to restore without success.

Joakim Sørensen ***@***.***> ezt írta (időpont: 2022. dec.
30., Pén 19:21):
