### ISSUE TITLE
HACS GitHub API usage

### ISSUE THREAD

**Issue by larsxschneider** [hacs/integration#2977]
### Describe the issue

👋 Hello HACS team 😊 !

We, GitHub, have noticed increased traffic against `*/*-card` repositories recently. Are you aware of recent changes in the way HACS is using GitHub? Can you help us understand how you are using the GitHub API?

Thank you! :bow:

**Comment by ludeeus** [comment]
Hi @larsxschneider 👋 
There have not really been any changes around that, most changes in the past few months have been UI related only.
I had a longer conversation about this with Wissam Abirached (@github) about 1,5 years ago.

Feel free to contact me by email to set up a meeting or to further discuss 😃 

- Joakim
