### ISSUE TITLE
Wrong text for ui.card.climate.preset_mode

### ISSUE THREAD

**Issue by lesourcil** [hacs/integration#2980]
### Web browser

Chrome

### Web browser version

Version 108.0.5359.125 (Official Build) (64-bit)

## System Information

version | core-2023.1.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.80
arch | x86_64
timezone | America/Toronto
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4994
Installed Version | 1.29.1
Stage | running
Available Repositories | 1207
Downloaded Repositories | 19

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.12.1
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 30.8 GB
disk_used | 11.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.1.3), Z-Wave JS (0.1.74), Samba share (10.0.0), Terminal & SSH (9.6.1), pyhydroquebec Add-on (0.12), File editor (5.4.2), Frigate NVR Proxy (1.3), ESPHome (2022.12.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 12
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 3, 2023 at 10:57 PM
-- | --
current_recorder_run | January 6, 2023 at 1:40 AM
estimated_db_size | 242.93 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The text of ui.card.climate.preset_mode is wrong.

### Reproduction steps

1. Add the card to your home assistant
2.
3.
...

### Screenshots

![image](https://user-images.githubusercontent.com/31264791/211100059-db5b7a9e-3888-4546-be79-bbc4aa7c259e.png)

### Javascript logs from your browser console

```text
REALLY ?
```

**Comment by ludeeus** [comment]
Not HACS

**Comment by lesourcil** [comment]
what do you mean not hacs ?

**Comment by lesourcil** [comment]
Ho boo me.  Im in hacs repo and not the card repo. Sorry !

**Comment by ludeeus** [comment]
You screenshot is not HACS.
There are no HACS card.

So your issue can not be with HACS.
