### ISSUE TITLE
No submit button for HACS connection

### ISSUE THREAD

**Issue by Morriz** [hacs/integration#2981]
### Web browser

Ios Safari

### Web browser version

Latest from 16.2

### System Health details

Not found in latest home assistant for ios (are docs up to date?)

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

In the docs it shows a submit button with the text “When you have done that click submit” and showing a submit button.

on my screen that is not there however, and after successful connection I am not able to redirect for completion of the flow. 

### Reproduction steps

1.follow HACS install docs
2.
3.
...

### Screenshots

![B76DD43F-0D07-47BC-BDC5-5C74D18C4CC9](https://user-images.githubusercontent.com/941865/211165870-db442662-010f-4fe1-8250-61bce1d5131a.png)

### Javascript logs from your browser console

```text
Ios
```

**Comment by ludeeus** [comment]
The docs are wrong, there is no submit.
It will wait on that screen until you completed the steps on GitHub.

**Comment by Morriz** [comment]
Ok, then why does it never complete? Can we reopen and change title? Or would this become a dupe? I suggest bringing baclk the title for better UX (it might fail and now users don’t have any option to act)

**Comment by ludeeus** [comment]
If you complete on github and it does not go further, you need to open a bug against the backend with the relevant logs as requested in that template.

**Comment by Morriz** [comment]
Just for reference: this only happens on my iphone, and desktop proceeds as expected.

**Comment by JonLaliberte** [comment]
Same issue here. Also safari /iOS
