### ISSUE TITLE
Connection flow never finishes

### ISSUE THREAD

**Issue by Morriz** [hacs/integration#2982]
### Web browser

Ios Safari

### Web browser version

Ios 16.2

### System Health details

Not found in ios app

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The last step (with the spinner) never completes

### Reproduction steps

1. Follow instructions 
2.
3.
...

### Screenshots

![2C6422E2-690F-42A5-BA72-B9D7A17E4B24](https://user-images.githubusercontent.com/941865/211166636-e2185c8a-3207-4744-a590-d255c03ac883.png)

### Javascript logs from your browser console

```text
Ios
```

**Comment by ludeeus** [comment]
This is not what I said...

**Comment by Morriz** [comment]
Can you relabel then? Or at least explain before closing. I found that rather rude

**Comment by Morriz** [comment]
@ludeeus hello?
