### ISSUE TITLE
Icon color not working in 2023.1

### ISSUE THREAD

**Issue by kristianolofsson** [hacs/integration#2987]
### Web browser

Safari

### Web browser version

Latest

### System Health details

Docker install

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Icon color is no longer working in 2023.1. The same attribute worked in latest 2022

### Reproduction steps

1. Reload of cust and template 
2.
3.
...

### Screenshots

![B0995E77-DFA3-4FE7-B6FF-A3FE8037543C](https://user-images.githubusercontent.com/7191232/211393231-06a8d46f-2469-48e1-8f11-67c04f8b4991.jpeg)

### Javascript logs from your browser console

```text
-
```

**Comment by ludeeus** [comment]
That has nothing to do with HACS.
Raise it with the author of what you use.
