### ISSUE TITLE
Custom fonts not displayed in the HACS frontend

### ISSUE THREAD

**Issue by GregoryKowalik** [hacs/integration#2995]
### Web browser

Chrome

### Web browser version

108.0.5359.126

## System Information

version | core-2023.1.4
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.10.0-15-amd64
arch | x86_64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4987
Installed Version | 1.29.1
Stage | running
Available Repositories | 1206
Downloaded Repositories | 23

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>GIOŚ</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.12.1
agent_version | 1.2.2
docker_version | 20.10.17
disk_total | 218.1 GB
disk_used | 17.0 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Let's Encrypt (4.12.7), Mosquitto broker (6.1.3), Samba share (10.0.0), Network UPS Tools (0.11.0), Studio Code Server (5.5.1), Zigbee2MQTT (1.29.1-1), Samba Backup (5.2.0), Terminal & SSH (9.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 16
views | 24
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3 stycznia 2023 07:02
-- | --
current_recorder_run | 13 stycznia 2023 10:40
estimated_db_size | 1739.80 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I'm using custom font in HA added to the Resources tab as CSS style with Comfortaa font downloaded from Google. The font is used within my theme and it's working fine with HA frontend. But if it comes to HACS frontend I see text font reverted to default sans-serif, I guess. The interesting thing is if I open DevTools from the browser and highlight any text within HACS frontend then I see font-family inherits my custom font properly but for some reasons it's not displayed properly on the html page. 
If I set my font-famili variable in my theme to something standard, for example Tahoma, then the font is displayed properly.
Looks that HACS frontend does not accept custom fonts not natively installed in the system. At least that's what I suspect. 

### Reproduction steps

1. Add custom font to the Resources as CSS style
2. Select that font in current theme 
3. Reload themes
4. Reload HACS page
5. See that fonts on HACS frontend is different then that set for the HA dashboard
...

### Screenshots

This is my dashboard with my custom font displayed properly
![image](https://user-images.githubusercontent.com/46071076/212336621-fb0fc959-add6-4c80-802d-33c2e5ac1a5e.png)
This is HACS frontend with wrong font
![image](https://user-images.githubusercontent.com/46071076/212336931-386c6b3d-a2e7-4d96-aa6f-8ee5ae67c2b0.png)
This is what DevTools shows for the highlighted text
![image](https://user-images.githubusercontent.com/46071076/212337141-3f153231-2172-4ab0-ab74-3ec1fa135fcb.png)
This is what I have in my Resources
![image](https://user-images.githubusercontent.com/46071076/212337771-97c13e8c-1e87-45e8-92fc-8ac7efea7311.png)
And part of my theme
![image](https://user-images.githubusercontent.com/46071076/212338013-e8c2f1af-23c9-404b-9937-8610e884438f.png)

### Javascript logs from your browser console

```text
msgport.js:70 {"notify":"init_tab"}
entry:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'msg')
    at chrome-extension://fjccjnfkdkdmjohojoggodkigkjkkjhl/contentscript.js:41:11
entry:1 Unchecked runtime.lastError: The message port closed before a response was received.
entry:1          GET https://176.120.120.150.telemedia.pl/local/custom-ui/custom-ui.js net::ERR_ABORTED 404 (Not Found)
(anonimowa) @ entry:1
entry:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://176.120.120.150.telemedia.pl/local/custom-ui/custom-ui.js
27668eba.js:1 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
value @ 27668eba.js:1
value @ 27668eba.js:1
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$EC @ styles.ts:372
light-entity-card.js?hacstag=168744428500:6868   LIGHT-ENTITY-CARD     Version 5.0.0       
vacuum-card.js?hacstag=261291295263:4  VACUUM-CARD  2.6.2 
power-distribution-card.js?hacstag=283578257257:918  POWER-DISTRIBUTION-CARD  2.5.6 
mini-graph-card-bundle.js?hacstag=1512800620110:1  MINI-GRAPH-CARD  0.11.0 
custom-ui.js?hacstag=26755814820221115:7   Custom-ui    Version 20221115 adapted for HA 2022.4 + 
card-mod.js?hacstag=190927524320:5 CARD-MOD 3.2.0 IS INSTALLED
card-mod.js?hacstag=190927524320:5 You may not be getting optimal performance out of card-mod.
See https://github.com/thomasloven/lovelace-card-mod#performance-improvements
custom-header.js?v=0.0.1:146 ☰  CUSTOM HEADER 1.8.3                 ⋮ 
User's Name: Greg                        
User ID: 12ecc2acd2bf48fabea7bcb736fd9e41
Device ID: 03fd420d-befd4ed1             
apexcharts-card.js?hacstag=331701152202:835  APEXCHARTS-CARD  v2.0.2 
embed.windy.com/js/leaflet140_patched_tileLayer.v14.js:5 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
gt @ embed.windy.com/js/leaflet140_patched_tileLayer.v14.js:5
mt @ embed.windy.com/js/leaflet140_patched_tileLayer.v14.js:5
addHooks @ embed.windy.com/js/leaflet140_patched_tileLayer.v14.js:5
enable @ embed.windy.com/js/leaflet140_patched_tileLayer.v14.js:5
addHandler @ embed.windy.com/js/leaflet140_patched_tileLayer.v14.js:5
e @ embed.windy.com/js/leaflet140_patched_tileLayer.v14.js:5
o.callInitHooks @ embed.windy.com/js/leaflet140_patched_tileLayer.v14.js:5
o.callInitHooks @ embed.windy.com/js/leaflet140_patched_tileLayer.v14.js:5
initialize @ embed.windy.com/js/leaflet140_patched_tileLayer.v14.js:5
e @ embed.windy.com/js/leaflet140_patched_tileLayer.v14.js:5
(anonimowa) @ embed.windy.com/v/19.10.8.emb.7c49/embed2.js:105
a @ embed.windy.com/v/19.10.8.emb.7c49/embed2.js:9
e.require @ embed.windy.com/v/19.10.8.emb.7c49/embed2.js:9
embedMap @ embed.windy.com/v/19.10.8.emb.7c49/embed2.js:116
(anonimowa) @ embed.windy.com/v/19.10.8.emb.7c49/embed2.js:116
vertical-slider-cover-card.js?hacstag=276636213015:8  [konnected.vn] Vertical Slider Cover Card   Version v0.1.5
embed.windy.com/v/19.10.8.emb.7c49/embed2.js:62 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
_init @ embed.windy.com/v/19.10.8.emb.7c49/embed2.js:62
_init @ embed.windy.com/v/19.10.8.emb.7c49/embed2.js:59
_init @ embed.windy.com/v/19.10.8.emb.7c49/embed2.js:73
instance @ embed.windy.com/v/19.10.8.emb.7c49/embed2.js:12
(anonimowa) @ embed.windy.com/v/19.10.8.emb.7c49/embed2.js:77
a @ embed.windy.com/v/19.10.8.emb.7c49/embed2.js:9
e.loadOrphanedModules @ embed.windy.com/v/19.10.8.emb.7c49/embed2.js:9
embedMap @ embed.windy.com/v/19.10.8.emb.7c49/embed2.js:116
(anonimowa) @ embed.windy.com/v/19.10.8.emb.7c49/embed2.js:116
embed.windy.com/v/19.10.8.emb.7c49/embed2.js:116 [Violation] 'DOMContentLoaded' handler took 201ms
[Violation] Forced reflow while executing JavaScript took 100ms
embed2.html:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'msg')
    at chrome-extension://fjccjnfkdkdmjohojoggodkigkjkkjhl/contentscript.js:41:11
embed2.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
embed2.js:87 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
c.onload @ VM18 embed2.js:87
load (asynchronicznie)
(anonimowa) @ VM18 embed2.js:87
r.load @ VM18 embed2.js:87
loadTile @ VM18 embed2.js:87
createTile @ VM18 embed2.js:86
_addTile @ VM16 leaflet140_patched_tileLayer.v14.js:5
_update @ VM16 leaflet140_patched_tileLayer.v14.js:5
_setView @ VM16 leaflet140_patched_tileLayer.v14.js:5
_resetView @ VM16 leaflet140_patched_tileLayer.v14.js:5
onAdd @ VM16 leaflet140_patched_tileLayer.v14.js:5
onAdd @ VM18 embed2.js:86
_layerAdd @ VM16 leaflet140_patched_tileLayer.v14.js:5
whenReady @ VM16 leaflet140_patched_tileLayer.v14.js:5
addLayer @ VM16 leaflet140_patched_tileLayer.v14.js:5
addTo @ VM16 leaflet140_patched_tileLayer.v14.js:5
onopen @ VM18 embed2.js:89
onopen @ VM18 embed2.js:89
(anonimowa) @ VM18 embed2.js:83
Promise.then (asynchronicznie)
(anonimowa) @ VM18 embed2.js:83
open @ VM18 embed2.js:83
(anonimowa) @ VM18 embed2.js:90
(anonimowa) @ VM18 embed2.js:90
emit @ VM18 embed2.js:16
d @ VM18 embed2.js:50
(anonimowa) @ VM18 embed2.js:50
Promise.then (asynchronicznie)
(anonimowa) @ VM18 embed2.js:50
Promise.then (asynchronicznie)
(anonimowa) @ VM18 embed2.js:50
a @ VM18 embed2.js:9
e.loadOrphanedModules @ VM18 embed2.js:9
embedMap @ VM18 embed2.js:116
(anonimowa) @ VM18 embed2.js:116
27668eba.js:1 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
value @ 27668eba.js:1
value @ 27668eba.js:1
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$EC @ styles.ts:372
entry:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

**Comment by ludeeus** [comment]
HACS is running inside an iframe in the Home Assistant UI, so it does not have access to custom resources.

**Comment by GregoryKowalik** [comment]
I see, thanks for quick response. Is there any option to copy the font file inside HACS repo and force it to pick it up when displaying text in the iframe?

**Comment by ludeeus** [comment]
Not in a good/safe way.

**Comment by GregoryKowalik** [comment]
So maybe I could add the custom font to the system fonts, because I noticed they work fine with HACS frontend. Then my custom font should be accessible natively...

**Comment by ludeeus** [comment]
That only works on the client you do that on

**Comment by GregoryKowalik** [comment]
I was rather thinking on adding the font to the hassio instance instead of my computer/client...

**Comment by ludeeus** [comment]
It would need to be on the client visiting.
Anyway, I'm going to close this as this is not something I'm willing to pursue inside HACS 👍

**Comment by GregoryKowalik** [comment]
Sure thing, thanks
