### ISSUE TITLE
Can not update HACS - Error - Pending restart "You have 1 integration for which a restart of HA is required"

### ISSUE THREAD

**Issue by SrekerGER** [hacs/integration#3019]
### System Health details

can not find the card - sorry for that

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I want to update HACS from 1.13.2 to 1.29.2. If I start the Update I receice a message "Pending restart" - "You have one integration that requires a restart of HA.  You can do that ..."

I restartet each integration manually, restartet HA, restarted the server. Nothing helps.
I tried to figure out which integration requires the restart, but i do not find anything.

### Reproduction steps

1. Just tried to install the update
2.
3.
...

### Debug logs

```text
Download was not completed
10:45:12 – (ERROR) HACS (custom integration)
Giving up async_download_file(...) after 5 tries (TypeError: timeout() got an unexpected keyword argument 'loop')

This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/helpers/methods/installation.py:29
Integration: HACS (documentation, issues)
First occurred: 10:45:12 (1 occurrences)
Last logged: 10:45:12

Download was not completed


10:45:12 – (ERROR) HACS (custom integration)

This error originated from a custom integration.
Logger: backoff
Source: custom_components/hacs/helpers/classes/repository.py:315
Integration: HACS (documentation, issues)
First occurred: 10:45:12 (1 occurrences)
Last logged: 10:45:12

Giving up async_download_file(...) after 5 tries (TypeError: timeout() got an unexpected keyword argument 'loop')
```

### Diagnostics dump

-d

**Comment by ludeeus** [comment]
You are using a too-old version, you need to re-run the download script to update.
