### ISSUE TITLE
Getting started with frontend development

### ISSUE THREAD

**Issue by elmar-hinz** [hacs/integration#3020]
### Describe the issue

First off all, there is no matching issue template. The frontend issue tracker is redirecting here. I like to document the issues I encounter while trying to set up the development container from inside VS Code. Thats the recommended path and it is not a happy experience.

1.) There are submodules:

It took me some time to figure out, I have to clone the repo with submodules to get the `homeassistant-frontend` subfolder. That's not documented, neither in the README of the frontend repo nor in the docs.

2.) The yarn installation sucks:

### Screenshots

When first starting the Container out of VS Code i get this error.

<img width="843" alt="Screenshot 2023-01-16 at 18 20 34" src="https://user-images.githubusercontent.com/1227339/212736905-083e4922-6e64-467b-be4d-3675b8279a88.png">

I can run `yarn start` nonetheless and `localhost:5000` does answer.

To figure out the reason I ran `yarn install`

It takes  time to download 62277 files. I assume the ESOCKETTIMEOUT is already resulting here.

<img width="1251" alt="Screenshot 2023-01-16 at 18 44 07" src="https://user-images.githubusercontent.com/1227339/212738899-bdaffb15-43fa-46c2-8ba1-e538a5deb2e3.png">

`yarn install` itself runs on without timeout. It takes a lot of time. Then it tries to compile something. There it gets worse. It takes eons and still does not finish.  I don't think this is normal. You could compile a whole linux kernel within shorter time. 

<img width="981" alt="Screenshot 2023-01-16 at 19 08 33" src="https://user-images.githubusercontent.com/1227339/212743252-8138c78a-3cf4-4374-bc2a-c288e095a190.png">

Update: `yarn install` did successfully finished after more than one hour.

It may be related to do compiling within a docker container. I don't know. However, I think a step, that takes so long, should not be part of the initial setup of the development container. And as shown this leads to a timeout error within the standard setup.  Many people will give up a this point.

**Comment by ludeeus** [comment]
This is what I use myself and do not have any issues.

**Comment by ludeeus** [comment]
Usually just a few minutes

**Comment by elmar-hinz** [comment]
Wonder if you could reduce this, by shipping more recent software with a fresh container.

**Comment by elmar-hinz** [comment]
It finally finished. Took a good hour.
