### ISSUE TITLE
dummylabs/watchman removed in PR 1674

### ISSUE THREAD

**Issue by livehybrid** [hacs/integration#3022]
### System Health details

Hi,
dummylabs/watchman was removed in https://github.com/hacs/default/pull/1674 however the repo is still being maintained, it was last updated within the last 24 hours (https://github.com/dummylabs/thewatchman/issues/75)

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Hi,
dummylabs/watchman was removed in https://github.com/hacs/default/pull/1674 however the repo is still being maintained, it was last updated within the last 24 hours (https://github.com/dummylabs/thewatchman/issues/75)

### Reproduction steps

HACS has removed dummylabs/watchman

### Debug logs

```text
NA
```

**Comment by ludeeus** [comment]
`dummylabs/thewatchman` is not `dummylabs/watchman`
