### ISSUE TITLE
after new installation icon is missing in sidepanel

### ISSUE THREAD

**Issue by TMoersch** [hacs/integration#3029]
### Web browser

Firefox, Edge

### Web browser version

latest Version

### System Health details

not relevant

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

icon hacs:hacs seem not to exist

### Reproduction steps

Install everything new from scratch with todays latest version

### Screenshots

not relevant

### Javascript logs from your browser console

```text
not relevant
```

### Diagnostics dump

not relevant

**Comment by ludeeus** [comment]
Clear browser cache.
