### ISSUE TITLE
"My Home Assistant" documentation example invalid

### ISSUE THREAD

**Issue by mdeweerd** [hacs/integration#3036]
### Describe the issue

https://github.com/hacs/documentation/edit/main/documentation/basic/my.md

Either provides an invalid redirect example or the integration is broken.

https://my.home-assistant.io/redirect/hacs_repository/?owner=hacs&repository=integration results in a repository that is not found on the target.

I tried to create a shortcut to a custom integration I manage, it gives the same result.
(Custom integration : https://github.com/mdeweerd/zha-toolkit ).

At this time I suppose that the instructions have to be updated.

### Screenshots

![image](https://user-images.githubusercontent.com/1504752/214346005-07694619-b78c-415a-b1b8-1bf4ebf5961b.png)

**Comment by ludeeus** [comment]
Both the docs and <https://my.home-assistant.io/redirect/hacs_repository/?owner=mdeweerd&repository=zha-toolkit&category=integration> (your example) work for me.
So then you are not using new enough versions, or you have some issue on your system.
The documentation is correct.

**Comment by mdeweerd** [comment]
Thank you for your prompt reply.

Somthing does work apparently, which is a good thing.

However, but:
1. The example button [![Open your Home Assistant instance and open a repository inside the Home Assistant Community Store.](https://my.home-assistant.io/badges/hacs_repository.svg)](https://my.home-assistant.io/redirect/hacs_repository/?owner=hacs&repository=integration) does not work;
2. This link does not work: https://ha.de-weerd.name/hacs/repository?owner=mdeweerd&repository=zha-toolkit .   The page says that the category is only needed for "Custom repositories" and zha-toolkit is a default repository.
