### ISSUE TITLE
Updates intermittently not displaying until restart

### ISSUE THREAD

**Issue by JasSmiths** [hacs/integration#3042]
### Web browser

Safari

### Web browser version

16.3

## System Information

version | core-2023.1.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.80
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4858
Installed Version | 1.30.1
Stage | running
Available Repositories | 1197
Downloaded Repositories | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 18 February 2023 at 12:00 am
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-west-2-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 116.7 GB
disk_used | 13.9 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.5.0), Home Assistant Google Drive Backup (0.110.1), Mosquitto broker (6.1.3), Zigbee2MQTT (1.29.2-1), Ring-MQTT with Video Streaming (5.0.5), Eufy Security Add-on (1.3.0), RTSP Simple Server Add-on (v0.17.6), SSH & Web Terminal (13.0.2), Glances (0.17.2), ESPHome (2022.12.8), MariaDB (2.5.1), phpMyAdmin (0.8.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 6
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 26 January 2023 at 5:12 pm
-- | --
current_recorder_run | 27 January 2023 at 10:13 pm
estimated_db_size | 98.03 MiB
database_engine | mysql
database_version | 10.6.8

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I've observed updates to HACS Integrations and Front End's intermittently not showing until HA is restarted, then they show up instantly on boot up.

This behaviour is observed on all browsers and the HA companion app.

### Reproduction steps

1. Leave HA running for 24hrs+ without restarting
2. Have an update come through for an installed HACS integration
3. If the update does not show in HACS then reboot HA 
4. Observe that the update now shows in HACS
...
Obviously this one is quite difficult to give reproduction steps for with it being intermittent.

### Screenshots

<img width="1231" alt="Screenshot 2023-01-27 at 10 46 28 pm" src="https://user-images.githubusercontent.com/34107308/215220491-19fba48c-65f1-48f5-afb9-fabb663645b6.png">

### Javascript logs from your browser console

```text
[Info] Mushroom - 2.5.2 (mushroom.js, line 2960)
[Log] ⚡ Power Flow Card v2.6.1 is installed (power-flow-card.js, line 69)
[Log] Readme: – "https://github.com/ulic75/power-flow-card" (power-flow-card.js, line 69)
```

### Diagnostics dump

[config_entry-hacs-c0cafbbdea55fd52f17153a14b26f5b9.json.txt](https://github.com/hacs/integration/files/10523677/config_entry-hacs-c0cafbbdea55fd52f17153a14b26f5b9.json.txt)

**Comment by ludeeus** [comment]
It takes up to 48h.
You can enable experimental features which drops it to 6h.

**Comment by JasSmiths** [comment]
> It takes up to 48h.
> You can enable experimental features which drops it to 6h.

Thanks for letting me know - Apologies for the unneeded issue report.
