### ISSUE TITLE
integration: deletion blocked

### ISSUE THREAD

**Issue by herveaurel** [hacs/integration#3043]
## System Information

version | core-2023.1.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.30.1
Stage | running
Available Repositories | 1199
Downloaded Repositories | 31

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 6 février 2023 à 01:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-central-1-2.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 219.4 GB
disk_used | 21.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.5.0), Samba share (10.0.0), Home Assistant Google Drive Backup (0.110.1), AppDaemon (0.11.0), ADB - Android Debug Bridge (0.8.0), AdGuard Home (4.8.0), VLC (0.1.3), FTP (4.6.2), Terminal & SSH (9.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 27
views | 30
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 19 janvier 2023 à 09:41
-- | --
current_recorder_run | 29 janvier 2023 à 01:28
estimated_db_size | 1263.44 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Sonoff</summary>

version | 3.3.1 (b20e33c)
-- | --
cloud_online | 1 / 1
local_online | 0 / 0

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Three years ago I installed in "integrations": LG WebOS Remote Control (https://github.com/madmicio/LG-WebOS-Remote-Control).
a year ago, no longer needing this integration, I wanted to delete it, I got some error messages, I didn't understand.
Today, hacs tells me an update is permanently available, but I can't do anything, if I click I get the message "unknown error".

### Reproduction steps

1. installation : LG WebOS Remote Control (https://github.com/madmicio/LG-WebOS-Remote-Control)
2. deletion not possible: error

### Debug logs

```text
This error comes from a custom integration

Logger: custom_components.hacs
Source: custom_components/hacs/utils/queue_manager.py:71 
Integration: HACS (documentation, issues) 
First occurred: 01:30:40 (2 occurrences) 
Last logged: 11:28:06

<QueueManager> No manifest.json file found 'manifest.json'
```

**Comment by ludeeus** [comment]
That is not an integration.
Add debug logs as instructed in the issue template.

**Comment by herveaurel** [comment]
> That is not an integration.
> Add debug logs as instructed in the issue template.

I know it but at the time it seems to me that it was an integration and it is blocked in integration

**Comment by ludeeus** [comment]
It has never been <https://github.com/madmicio/LG-WebOS-Remote-Control/commits/master?after=0eb329ac66fcaf7994b1c5e7919c56eb4a115862+174&branch=master&qualified_name=refs%2Fheads%2Fmaster>

**Comment by herveaurel** [comment]
> It has never been https://github.com/madmicio/LG-WebOS-Remote-Control/commits/master

Oh I made a big mistake then! It's stuck in integrations!

**Comment by ludeeus** [comment]
Right...
> Add debug logs as instructed in the issue template.

And the diagnostics dump..

**Comment by herveaurel** [comment]
> Right...
> 
> > Add debug logs as instructed in the issue template.
> 
> And the diagnostics dump..

Sorry, I did not understand where to see this information

**Comment by herveaurel** [comment]
> It has never been https://github.com/madmicio/LG-WebOS-Remote-Control/commits/master

![image](https://user-images.githubusercontent.com/64784541/215324289-114c598c-2187-4d14-8298-fb7867061edc.png)
