### ISSUE TITLE
TypeError: undefined is not an object

### ISSUE THREAD

**Issue by sephrioth** [hacs/integration#3050]
### Web browser

Chrome on macOS

### Web browser version

Version 109.0.5414.119 (Official Build) (x86_64)

### System Health details

<div class="mdc-dialog__container" style="display: flex; flex-direction: row; align-items: var(--vertical-align-dialog, center); justify-content: space-around; box-sizing: border-box; height: 1136px; transform: none; opacity: 1; pointer-events: none; color: rgba(0, 0, 0, 0.6); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="mdc-dialog__surface" style="box-shadow: var(--mdc-dialog-box-shadow, 0px 11px 15px -7px rgba(0, 0, 0, 0.2), 0px 24px 38px 3px rgba(0, 0, 0, 0.14), 0px 9px 46px 8px rgba(0, 0, 0, 0.12)); position: var(--dialog-surface-position, relative); display: flex; flex-direction: column; flex-grow: 0; flex-shrink: 0; box-sizing: border-box; max-width: var(--mdc-dialog-max-width, 560px); max-height: var(--mdc-dialog-max-height, calc(100% - 32px)); pointer-events: auto; overflow-y: auto; background-color: var(--mdc-theme-surface, #fff); border-radius: var(--ha-dialog-border-radius, 28px); min-width: var(--mdc-dialog-min-width, 280px); top: var(--dialog-surface-top); margin-top: var(--dialog-surface-margin-top); min-height: var(--mdc-dialog-min-height, auto);"><h2 id="title" class="mdc-dialog__title" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-headline6-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-headline6-font-size, 1.25rem); line-height: var(--mdc-typography-headline6-line-height, 2rem); font-weight: var(--mdc-typography-headline6-font-weight, 500); letter-spacing: var(--mdc-typography-headline6-letter-spacing, 0.0125em); text-decoration: var(--mdc-typography-headline6-text-decoration, inherit); text-transform: var(--mdc-typography-headline6-text-transform, inherit); display: block; position: relative; flex-shrink: 0; box-sizing: border-box; margin: 0px 0px 1px; padding: 24px 24px 0px; color: var(--mdc-dialog-heading-ink-color, rgba(0, 0, 0, 0.87));"><div class="header_title" style="margin-right: 32px; margin-inline-end: 32px; margin-inline-start: initial; direction: var(--direction);">System information</div><ha-icon-button dialogaction="close" class="header_button" style="display: inline-block; outline: none; position: absolute; right: 16px; top: 14px; text-decoration: none; color: inherit; inset-inline-start: initial; inset-inline-end: 16px; direction: var(--direction);"><mwc-icon-button title="Close" style="display: inline-block; outline: none; --mdc-ripple-color: currentcolor; -webkit-tap-highlight-color: transparent; vertical-align: top; --mdc-theme-on-primary: currentColor; --mdc-theme-text-disabled-on-light: var(--disabled-text-color);"><button class="mdc-icon-button mdc-icon-button--display-flex" aria-label="Close" style="font-size: 24px; width: var(--mdc-icon-button-size, 48px); height: var(--mdc-icon-button-size, 48px); padding: calc( (var(--mdc-icon-button-size, 48px) - var(--mdc-icon-size, 24px)) / 2 ); display: inline-flex; position: relative; box-sizing: border-box; border: none; outline: none; background-color: transparent; fill: currentcolor; color: inherit; text-decoration: none; cursor: pointer; user-select: none; z-index: 0; overflow: visible; align-items: center; justify-content: center; vertical-align: top;"><span><slot><ha-svg-icon style="display: block; align-items: center; justify-content: center; position: relative; vertical-align: middle; fill: currentcolor; width: var(--mdc-icon-size, 24px); height: var(--mdc-icon-size, 24px);"><svg preserveAspectRatio="xMidYMid meet" focusable="false" role="img" aria-hidden="true" viewBox="0 0 24 24"><g><path d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></g></svg></ha-svg-icon></slot></span></button></mwc-icon-button></ha-icon-button></h2><div id="content" class="mdc-dialog__content" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-body1-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-body1-font-size, 1rem); line-height: var(--mdc-typography-body1-line-height, 1.5rem); font-weight: var(--mdc-typography-body1-font-weight, 400); letter-spacing: var(--mdc-typography-body1-letter-spacing, 0.03125em); text-decoration: var(--mdc-typography-body1-text-decoration, inherit); text-transform: var(--mdc-typography-body1-text-transform, inherit); flex-grow: 1; box-sizing: border-box; margin: 0px; overflow: auto; color: var(--mdc-dialog-content-ink-color, rgba(0, 0, 0, 0.6)); padding: var(--dialog-content-padding, 24px); position: var(--dialog-content-position, relative);"><slot id="contentSlot" style="margin-top: 0px; margin-bottom: 0px;"><div><div>

Version | core-2023.2.0
-- | --
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
User | root
Virtual Environment | false
Python Version | 3.10.7
Operating System Family | Linux
Operating System Version | 4.4.59+
CPU Architecture | x86_64
Timezone | Asia/Shanghai
Configuration Directory | /config

</div></div></slot></div><footer id="actions" class=" mdc-dialog__actions " style="display: flex; position: relative; flex-shrink: 0; flex-wrap: wrap; align-items: center; justify-content: var(--justify-action-buttons, flex-end); box-sizing: border-box; min-height: 52px; margin: 0px; padding: 0px 24px 24px; border-top: 1px solid transparent;"><span style="flex: var(--secondary-action-button-flex, unset);"><slot name="secondaryAction"></slot></span><span style="flex: var(--primary-action-button-flex, unset);"><slot name="primaryAction"><mwc-button slot="primaryAction" style="display: inline-flex; outline: none; -webkit-tap-highlight-color: transparent; vertical-align: top; margin-left: 8px; margin-right: 0px; max-width: 100%; text-align: right;"><button id="button" class="mdc-button   " aria-label="Copy" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-button-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-button-font-size, 0.875rem); line-height: inherit; font-weight: var(--mdc-typography-button-font-weight, 500); letter-spacing: var(--mdc-typography-button-letter-spacing, 0.0892857em); text-decoration: var(--mdc-typography-button-text-decoration, none); text-transform: var(--mdc-typography-button-text-transform, uppercase); position: relative; display: inline-flex; align-items: center; justify-content: center; box-sizing: border-box; min-width: 64px; border: none; outline: none; user-select: none; appearance: none; overflow: hidden; vertical-align: middle; background: transparent; padding-top: 0px; padding-right: var(--mdc-button-horizontal-padding, 8px); padding-bottom: 0px; padding-left: var(--mdc-button-horizontal-padding, 8px); height: 36px; border-radius: var(--mdc-shape-small, 4px); flex: 1 1 auto; color: var(--mdc-theme-primary, #6200ee);"><span class="leading-icon"><slot name="icon"></slot></span><span class="mdc-button__label" style="position: relative;">COPY</span><span class="slot-container   " style="display: inline-flex; align-items: center; justify-content: center;"><slot></slot></span><span class="trailing-icon"><slot name="trailingIcon"></slot></span></button></mwc-button></slot></span></footer></div></div><br class="Apple-interchange-newline">

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

After upgrade to HA 2023.02, this error flooded my log and won't stop.

http://xxxx:8123/hacsfiles/custom-ui/custom-ui.js?hacstag=26755814820221115:206:14 TypeError: undefined is not an object (evaluating 'entities['sensor.crypto_btc_24hours_change'].state')

I tried :
- disable this particular entity
- remove custom-ui

But still no lucky.

### Reproduction steps

1. Restart
2. 
3.
...

### Screenshots

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/4231328/216265914-68eea826-8f16-4daa-bc5d-6951377eaa14.png">

### Javascript logs from your browser console

```text
N/A
```

**Comment by ludeeus** [comment]
Take that up with the author of custom-ui.

**Comment by sephrioth** [comment]
I understand, but the problem is even I removed custom-ui (and then restart HA), this error still exists, so is still custom-ui issue?

**Comment by ludeeus** [comment]
yes.

**Comment by sephrioth** [comment]
> yes.

Finally we(custom-ui owner and me) found the issue, somehow HACS is not quite right on my HA, it only shows in side menu, but not show in Devices/Integration, it reminds me I can only add one HACS device when I try to integrate again.

So I use the HACS install command to re-install, and then the issue is gone. But I still can't find it in Devices/Integration page. Any hints?
