### ISSUE TITLE
Stuck on waiting activation

### ISSUE THREAD

**Issue by wopch** [hacs/integration#3053]
## System Information

version | core-2023.2.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.90
arch | x86_64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 30.8 GB
disk_used | 4.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | UniFi Network Application (2.5.0), File editor (5.5.0), Terminal & SSH (9.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3 février 2023 à 12:41
-- | --
current_recorder_run | 4 février 2023 à 16:01
estimated_db_size | 5.58 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

After starting the integration installation. Hacs requires authentication in order to connect to my GitHub account. After following the instructions and allowing access, Hacs gets stuck on the same page "Waiting for Device activation". I try to change browser, another device, always the same thing. 
![Capture d’écran 2023-02-04 162733](https://user-images.githubusercontent.com/124432637/216775643-26f253ca-ec68-4dd1-b6a3-8aa412d41877.png)

### Reproduction steps

1. Follow hacs install guide
2.
3.
...

### Debug logs

```text
Cette erreur provient d'une intégration personnalisée

Logger: homeassistant
Source: custom_components/hacs/config_flow.py:62
Integration: HACS (documentation, issues)
First occurred: 16:03:10 (1 occurrences)
Last logged: 16:03:10

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/config_flow.py", line 62, in _wait_for_activation
    response = await self.device.activation(device_code=self._login_device.device_code)
  File "/usr/local/lib/python3.10/site-packages/aiogithubapi/device.py", line 142, in activation
    response = await self._client.async_call_api(
  File "/usr/local/lib/python3.10/site-packages/aiogithubapi/client.py", line 111, in async_call_api
    raise GitHubConnectionException(
aiogithubapi.exceptions.GitHubConnectionException: Timeout of 20 reached while waiting for https://github.com/login/oauth/access_token
```

**Comment by ludeeus** [comment]
If you do not get a response in 20s, you have network issues.
Once you fix that it will work.
