### ISSUE TITLE
HACS Problems

### ISSUE THREAD

**Issue by cryd-s** [hacs/integration#3054]
### System Health details

Hi,

i am using a mini pc with hass os (no proxmox or something like that)

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Want to ask in discord but link on hacs.xyz doesnt work i get a error 

![image](https://user-images.githubusercontent.com/47699362/216837151-0d3f505f-fb4b-4c05-91da-d0d0ebe19efc.png)

I have not the normal view of hacs and i dont know how to change it to default.

![image](https://user-images.githubusercontent.com/47699362/216837183-4fbd7b3d-d572-4bd1-a627-d48333f8e6f4.png)

### Reproduction steps

1. after a restart it was like this
2.
3.
...

### Debug logs

```text
...
```

**Comment by ludeeus** [comment]
That is the normal view when you run experimental.

**Comment by cryd-s** [comment]
but how can i get the normal one ? deinstalled hacs several times but no change :(

**Comment by jurasjo** [comment]
I think you can change it in: Settings > Devices&Services > HACS (Configure > untick "Enable experimental features")

**Comment by nitrokart** [comment]
> I think you can change it in: Settings > Devices&Services > HACS (Configure > untick "Enable experimental features")

Then clear broswer cache!
