### ISSUE TITLE
Install script does not work due to wrong file names

### ISSUE THREAD

**Issue by SuPuL** [hacs/integration#3062]
### Describe the issue

Hi,
I tried to install HACS on a docker-based system on macOS. Or better via a network connection on a Synology NAS. The install script stopped in this step:

`INFO: Unpacking HACS...`

I guess this is related to the file name of the zip file. The unzip steps expect the zip named `unzip "$haPath/custom_components/hacs.zip" -d "$haPat...`.

But for some reason both provided URLs do a 302 redirect. This result is the very long cryptic filename. 

The solution is to use the `-o` flag of `wget` to ensure always the correct name:

`wget "https://github.com/hacs/integration/releases/latest/download/hacs.zip" -o hacs.zip`

greetings

**Comment by SuPuL** [comment]
Ok this is not the problem. Sry for writing to early. Will report back.

**Comment by ludeeus** [comment]
And what _exactly_ happened? what _exactly_ was the output? What _exactly_ was the result?
Forcing the filename is not a solution as that will hide issues (where you download a error HTML page instead of a zip file.

**Comment by SuPuL** [comment]
Hi,
as said the download results in a cryptic name like see in the screen. 

<img width="668" alt="image" src="https://user-images.githubusercontent.com/2278426/218305935-2b61d1e7-455d-41f4-97c6-99797da07461.png">

And as said wget seems to use the rename. I just tried the download manually and it worked:

`wget -O hacs.zip "https://github.com/hacs/integration/releases/latest/download/hacs.zip"`

**Comment by SuPuL** [comment]
` wget --content-disposition` does also work. So no explicit filename is used.

**Comment by ludeeus** [comment]
What version of `wget` is that? pre 1.15?

**Comment by SuPuL** [comment]
`GNU Wget 1.21.3 built on darwin20.6.0.`

**Comment by ludeeus** [comment]
That should be fine, you tried on the host.
If you jump inside the container I assume it just works?
