### ISSUE TITLE
404 from the get.hacs.xyz script

### ISSUE THREAD

**Issue by Wassini** [hacs/integration#3069]
### System Health details

-

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

This line in the script fails:
    wget "https://github.com/hacs/integration/releases/latest/download/hacs.zip"

### Reproduction steps

1. wget -O - https://get.hacs.xyz | bach -

### Debug logs

```text
.
```

**Comment by ludeeus** [comment]
The repository was accidentally deleted for a while.
It works again now.
