### ISSUE TITLE
HACS main menu does not show up

### ISSUE THREAD

**Issue by RuudKapteijn** [hacs/integration#3070]
### Web browser

Chrome 

### Web browser version

110.0.5481.104

## System Information

version | core-2023.2.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.30.1
Stage | running
Available Repositories | 1279
Downloaded Repositories | 5
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 22, 2024 at 1:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-west-2-3.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 28.6 GB
disk_used | 5.7 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.1), Studio Code Server (5.5.2), Mosquitto broker (6.1.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 3
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 13, 2023 at 3:55 PM
-- | --
current_recorder_run | February 19, 2023 at 11:46 PM
estimated_db_size | 343.05 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When I click the HACS icon in the sidebar I do not get the HACS main menu (Integrations, Frontend, Automation, Add-ons, About):
![Screenshot 2023-02-20 000112](https://user-images.githubusercontent.com/44146047/219980542-b7a813ab-d0c5-4f30-bfd1-c751ae0b27df.jpg)

Instead I get the Home Assistant Community Store screen: 
![Screenshot 2023-02-20 000423](https://user-images.githubusercontent.com/44146047/219980645-adcfb17b-47fb-4ead-9867-74f25d34baae.jpg)

### Reproduction steps

1. Click HACS sidebar icon
2. Home Assistant Community Store window opens

### Screenshots

Home Assistant Community Store window (what I get):
![Screenshot 2023-02-20 000423](https://user-images.githubusercontent.com/44146047/219980723-70a12e20-0fac-4186-9c7d-e75fded34ab8.jpg)

Main menu (what I expected):
![Screenshot 2023-02-20 000112](https://user-images.githubusercontent.com/44146047/219980750-ff466750-56e7-4ea3-865d-0120f72835df.jpg)

### Javascript logs from your browser console

```text
I am not sure what is required here.
```

### Diagnostics dump

[config_entry-hacs-465f62ed3df707fec69723dce29915e3.json.txt](https://github.com/hacs/integration/files/10778210/config_entry-hacs-465f62ed3df707fec69723dce29915e3.json.txt)

**Comment by ludeeus** [comment]
That is the new UI that is enabled when you enable experimental features.

**Comment by RuudKapteijn** [comment]
ok Thank you for the explanation.
Can it be reversed? Just unclicking "Enable experimental features" and a restart does not do it.

**Comment by ludeeus** [comment]
That + clear browser cache.
But its temporary, everyone will get that in HACS 2.0

**Comment by RuudKapteijn** [comment]
OK Thank you for your help!
Kind regards, Ruud.
