### ISSUE TITLE
Lovelace Change to Dashobard

### ISSUE THREAD

**Issue by milandzuris** [hacs/integration#3076]
### Web browser

*

### Web browser version

*

### System Health details

*

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Please Change Category Lovelace to Dashboard
![image](https://user-images.githubusercontent.com/42905545/221299057-7400f3aa-9b20-4884-aa20-70e6d6c671c0.png)

### Reproduction steps

*

### Screenshots

*

### Javascript logs from your browser console

```text
*
```

**Comment by ludeeus** [comment]
Not a bug

**Comment by milandzuris** [comment]
> Not a bug

ok and what is it?
