### ISSUE TITLE
6h / 48h Update checker not flagging updates

### ISSUE THREAD

**Issue by toddstar** [hacs/integration#3077]
## System Information

version | core-2023.3.0b0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.90
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4998
Installed Version | 1.30.1
Stage | running
Available Repositories | 1306
Downloaded Repositories | 54
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | beta
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 43.6 GB
disk_used | 39.2 GB
healthy | true
supported | failed to load: Unsupported
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (14.0.3), Mosquitto broker (6.1.3), Samba share (10.0.0), MariaDB (2.5.2), Studio Code Server (5.5.2), Home Assistant Google Drive Backup (0.110.1), Duck DNS (1.15.0), Double Take (1.13.1), SSH & Web Terminal (13.0.2), UniFi Network Application (2.5.0), ESPHome (2023.2.4), Vaultwarden (Bitwarden) (0.19.0), TasmoAdmin (0.23.0), Portainer (2.17.0), Frigate (Full Access) Beta (0.12.0) (0.12.0-beta8)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 28
views | 22
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15 February 2023 at 12:30
-- | --
current_recorder_run | 23 February 2023 at 10:47
estimated_db_size | 1443.59 MiB
database_engine | mysql
database_version | 10.6.10

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Logs for discord chat https://discord.com/channels/606225571898327139/606225572485398550/1077608514580660275 about 6 hours not working correctly (/ sometimes having to manually open integrations to see updates.)

Attached log files 
[home-assistant - 2023.02.21 - 2023-02-23.log](https://github.com/hacs/integration/files/10832288/home-assistant.-.2023.02.21.-.2023-02-23.log) -  Its from after the opnsense integration pictures as, per discord, i didn't have debug turned on.
[home-assistant 2023.02.23 - 2023.02.25 PART1.log](https://github.com/hacs/integration/files/10832289/home-assistant.2023.02.23.-.2023.02.25.PART1.log) & [home-assistant 2023.02.23 - 2023.02.25 PART2.log](https://github.com/hacs/integration/files/10832290/home-assistant.2023.02.23.-.2023.02.25.PART2.log)  (split into 2 as over size limit) - restarting hacs today at 2023-02-25 19:59:27 (part 2 file) has correctly flagged that i have 2 updates available this time. However (update 1) https://github.com/zanna-37/hass-swipe-navigation/releases/v1.10.2 was released 2023-02-22 23:11 so should have already been flagged and not required a restart as well over 48 hours? (update 2) https://github.com/bramstroker/homeassistant-powercalc/releases/tag/v1.3.7 was released 2023-02-24 08:26 so well over 6 hours but is under 48 if it fallen to that method
[home-assistant 2023.02.25.log](https://github.com/hacs/integration/files/10832291/home-assistant.2023.02.25.log) - restart so above has shutdown log and this has start up logs (didn't update either of the 2 items)

### Reproduction steps

1. HA running for a few days
2. Restart hacs integration
3. Updates now flagged but upgrade released over 6 / 48 hours ago

### Debug logs

[home-assistant - 2023.02.21 - 2023-02-23.log](https://github.com/hacs/integration/files/10832288/home-assistant.-.2023.02.21.-.2023-02-23.log)
[home-assistant 2023.02.23 - 2023.02.25 PART1.log](https://github.com/hacs/integration/files/10832289/home-assistant.2023.02.23.-.2023.02.25.PART1.log)
[home-assistant 2023.02.23 - 2023.02.25 PART2.log](https://github.com/hacs/integration/files/10832290/home-assistant.2023.02.23.-.2023.02.25.PART2.log)
[home-assistant 2023.02.25.log](https://github.com/hacs/integration/files/10832291/home-assistant.2023.02.25.log)

### Diagnostics dump

[config_entry-hacs-2c41d147547bb964c10f56a5071ff8e0.json.txt](https://github.com/hacs/integration/files/10832282/config_entry-hacs-2c41d147547bb964c10f56a5071ff8e0.json.txt)

**Comment by ludeeus** [comment]
Thanks @toddstar 👍 
It seems updating works fine, it just never told the entities to refresh their data...

**Comment by toddstar** [comment]
> Thanks @toddstar 👍 It seems updating works fine, it just never told the entities to refresh their data...

Working correctly again now thanks 👍 (just got an update alert for integration updated 6 hours ago)
