### ISSUE TITLE
HA WARNING "NetDaemon in HACS is deprectaded."

### ISSUE THREAD

**Issue by sokai** [hacs/integration#3080]
## System Information

version | core-2023.3.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4948
Installed Version | 1.31.0
Stage | running
Available Repositories | 1310
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 457.7 GB
disk_used | 8.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | SSH & Web Terminal (13.0.2), File editor (5.5.0), Z-Wave JS (0.1.76), SQLite Web (3.7.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 3
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 24, 2023 at 19:00
-- | --
current_recorder_run | March 4, 2023 at 10:07
estimated_db_size | 871.23 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I see this 1 WARNING in my HA Core logs (without any extra debug logging enabled).

```log
This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:783
Integration: HACS (documentation, issues)
First occurred: 10:08:15 (1 occurrences)
Last logged: 10:08:15

NetDaemon in HACS is deprectaded. It will stop working in the future. Please remove all your current NetDaemon repositories from HACS and download them manually if you want to continue using them.
```

I create this issue JFYI, I have no problems or any other failures …

### Reproduction steps

1. Reboot (whole system)
2. Look at the HA Core logs

### Debug logs

```text
none
```

### Diagnostics dump

none

**Comment by ludeeus** [comment]
This is expected, see release notes..
Remove the netdaemon apps you have in HACS and it will stop warning you about it.

**Comment by sokai** [comment]
:-o I didn't read [that](https://github.com/hacs/integration/releases/tag/1.31.0). #sry for bothering you!
