### ISSUE TITLE
Could not authenticate with Github

### ISSUE THREAD

**Issue by SuperMaximus1984** [hacs/integration#3087]
### System Health details

![image](https://user-images.githubusercontent.com/62514634/224249992-bdbe9f89-3185-4a99-9720-0b9232c10ab0.png)
Fresh HA Docker installation. No matter what I do (reboot HA or the whole Host) it cannot authenticate and move further. Where to dig?

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Could not authenticate with Github during HACS integration setup in Home Assistant 2023.3.1

### Reproduction steps

1. Installed HACS by wget as in instruction
2. Ticked all ticks
3. Pressed SUBMIT
Received the error.

### Debug logs

```text
I cannot reach this stage.
```

**Comment by ludeeus** [comment]
Network problem

**Comment by SuperMaximus1984** [comment]
> Network problem

No network problems at all here. All internet-dependent services are working fine.

**Comment by emanueletocci** [comment]
Same problem....

**Comment by darklordoftheabyss** [comment]
Have a similar issue.

In the HA UI I don't see a submit button ![image](https://user-images.githubusercontent.com/127606879/224489707-658dc044-8183-49e4-80f9-353756401649.jpeg)

I can authorise and everything is fine but in the HA UI it just sits there waiting

**Comment by lmdc45** [comment]
same... any ways around it?

**Comment by lmdc45** [comment]
so it turns out github was bloking the ip address from the vps I use. can ping github but cannot get any reply from http server. getting a different ip and it worked
