### ISSUE TITLE
Request for removal of music-assistant/hass-music-assistant

### ISSUE THREAD

**Issue by tinuva** [hacs/integration#3090]
### Repository

music-assistant/hass-music-assistant

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

As of HA 2023.3.1 this integration does not work anymore.

In issue [hass-music-assistant/issues/1104](https://github.com/music-assistant/hass-music-assistant/issues/1104) the author mention it will not be fixed, at this [comment](https://github.com/music-assistant/hass-music-assistant/issues/1104#issuecomment-1441685040). The author also mentions that there is a new 2.x beta version, which is not a custom integration but a custom addon. Eg. difference place to be added for installation, the addon store instead of hacs.

### Link to issue

https://github.com/music-assistant/hass-music-assistant/issues/1104#issuecomment-1441685040

**Comment by OzGav** [comment]
You aren’t understanding what is happening. For users that are <= HA 2023.2.x then MA1 works fine. For that reason alone the component would remain in HACS.
Additionally, there will soon be a new integration for HA which allows interfacing with MA2. This will initially be supplied through HACS but pinned to >= HA2023.3.x. Eventually the plan is to have the MA2 HA integration rolled into HA core. When that happens in a few months then we could look to see if anyone is still wanting to use MA1 and then talk about whether the component stays in HACS.

**Comment by marcelveldt** [comment]
@tinuva isn't it a bit rude to do this request without asking me ?

**Comment by tinuva** [comment]
@marcelveldt  If you want to be emotional about then I guess it may seem rude, however that was not the intention.

Right now however it doesn't work on the latest version of HA and having no ETA on when 2.0 will be out of beta is not really an answer.

I'd say OzGav's answer was much better thank you. He pointed out that I do not see the whole picture.

**Comment by OzGav** [comment]
@tinuva you ticked the box indicating you tried to get the authors attention when you didn’t. So maybe a bit more respect for the process and for the amount of effort Marcel is putting into this project is in order.

**Comment by ludeeus** [comment]
Closing as I deem this to be premature.
