### ISSUE TITLE
Ignore button for archived repository not working

### ISSUE THREAD

**Issue by TomBrien** [hacs/integration#3092]
### Web browser

Chrome

### Web browser version

 111.0.5563.65

## System Information

version | core-2023.3.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.90
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.31.0
Stage | running
Available Repositories | 1315
Downloaded Repositories | 23

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 5 April 2023 at 01:00
relayer_connected | true
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | false
remote_server | eu-west-2-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 219.4 GB
disk_used | 50.3 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), File editor (5.5.0), Check Home Assistant configuration (3.11.0), Duck DNS (1.15.0), SSH & Web Terminal (13.0.3), Mosquitto broker (6.1.3), deCONZ (6.18.0), Studio Code Server (5.5.3), Grafana (8.2.0), Glances (0.18.0), texecom2mqtt (1.2.3), Frigate NVR (3.1), Log Viewer (0.14.0), SQLite Web (3.7.0), chrony (2.5.0), AdGuard Home (4.8.3), RTSPtoWeb - WebRTC (1.4.0), Nginx Proxy Manager (0.12.3), MariaDB (2.5.2), ESPHome (2023.2.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 13
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3 March 2023 at 18:07
-- | --
current_recorder_run | 14 March 2023 at 08:23
estimated_db_size | 680.68 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When clicking the "ignore" button on the modal for an archived repository, nothing happens. 

### Reproduction steps

1. Have a archived repository installed (i.e. AitorDB/home-assistant-sun-card)
2. Click "Show" on warning in HACS
3. Click "ignore"

### Screenshots

![image](https://user-images.githubusercontent.com/12411302/225386675-0bdbdae7-85d2-4306-bbe9-52806d834e5c.png)

### Javascript logs from your browser console

```text
c.bdf06437.js:30 Uncaught (in promise) {code: 'unknown_error', message: 'Unknown error'}code: "unknown_error"message: "Unknown error"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
value @ c.bdf06437.js:30
await in value (async)
handleEvent @ main-ad130be7.js:1


===================

HA Core log:

2023-03-15 17:04:24.650 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140495617944368] Error handling message: Unknown error (unknown_error) XXXXX from XXX.XXX.XXX.XXX (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
await func(hass, connection, msg)
File "/config/custom_components/hacs/websocket/repository.py", line 106, in hacs_repository_ignore
hacs.common.ignored_repositories.append(repository.data.full_name)
AttributeError: 'NoneType' object has no attribute 'data'
```

### Diagnostics dump

[config_entry-hacs-53f20951767ccea867c3c33971fa50a0.json.txt](https://github.com/hacs/integration/files/10982809/config_entry-hacs-53f20951767ccea867c3c33971fa50a0.json.txt)

**Comment by ludeeus** [comment]
Workaround for now, enable experimental features in HACS and restart Home Assistant.

**Comment by sacofpotatoes** [comment]
I have this same issue. But I accidentally removed the repository, is there anyway I can get it back. I have tried to re-add it as a custom repository, but to no avail.

**Comment by ludeeus** [comment]
no

**Comment by TomBrien** [comment]
> Workaround for now, enable experimental features in HACS and restart Home Assistant.

This work around clear the warning in the native Settings menu (which only shows with experimental settings on) but not in HACS own frontend

**Comment by ludeeus** [comment]
It does not exist in the HACS frontend when that is enabled, if you see it you have not cleared the browser cache.
It should look like the images here <https://experimental.hacs.xyz/>
