### ISSUE TITLE
How to add icon next to a component

### ISSUE THREAD

**Issue by ThomDietrich** [hacs/integration#3095]
### Describe the issue

Hey, I couldn't find this anywhere in documentation and it should probably be added.

How do I add the icon for a component to be presented on the left side of the HACS store:

![image](https://user-images.githubusercontent.com/2870104/225671830-75699cb0-98e3-4181-81cb-2d4ffc9f32bb.png)

**Comment by ludeeus** [comment]
That uses HA brands repo like all other parts of HA itself.

https://github.com/home-assistant/brands

https://hacs.xyz/docs/publish/include#check-brands

**Comment by ludeeus** [comment]
Not possible, only integrations can have that.

**Comment by ThomDietrich** [comment]
I got that. Would you like to discuss whether it SHOULD be made possible? :)
