### ISSUE TITLE
Overwritten integration 

### ISSUE THREAD

**Issue by FL550** [hacs/integration#3096]
### System Health details

Not relevant

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

A new integration was added to HACS with the exact same name: [https://github.com/hacs/default/pull/1649](https://github.com/hacs/default/pull/1649) 
My integration: [https://github.com/FL550/dwd_weather](https://github.com/FL550/dwd_weather)
This results in overwriting the older integration and existing users unable to update.
![Screenshot_20230321-184237](https://user-images.githubusercontent.com/36160004/226735292-bc574a33-ddf4-49c2-a171-90899347d4e3.png)

### Reproduction steps

1. search for dwd 
2. only find newest integration, missing FL550/dwd_weather

### Debug logs

```text
Not relevant
```

**Comment by tjorim** [comment]
I don't see the issue, users can still find and install your version:
![Screenshot_20230321-221620.png](https://user-images.githubusercontent.com/1294876/226742870-c1a1cb4e-dc05-4b0f-82cb-5a383209e48e.png)

They won't be able to install both at the same time but that's just how integrations work in Home Assistant.

**Comment by ludeeus** [comment]
Many integration share both name and domains, there is nothing I want to block that, if that is an “issue” the authors of the integration should collaborate in making a good integration for all users (or even better contribute it to the HA core)

**Comment by FL550** [comment]
Ok, I see. Then this was my fault for not checking the integration_list correctly. 

Nevertheless, I find this indication suboptimal: 
![Screenshot_20230322_074614](https://user-images.githubusercontent.com/36160004/226823747-97d5698f-1b56-4c4b-9ba2-9368909e4d71.png)

But I guess it's then hacs/ui and not hacs/integration?

**Comment by ludeeus** [comment]
You control that.. https://github.com/FL550/dwd_weather/blob/v1.2.24/info.md
