### ISSUE TITLE
Is HACS dead ?

### ISSUE THREAD

**Issue by rexave** [hacs/integration#3098]
### Describe the issue

There are PR pending since mid january. 
It seems that all "new" contributors are stuck on PR for no reason (no comment, no answer ...)
Can we help somehow ?

**Comment by ludeeus** [comment]
You are wrong...
Check commit history before next time...

**Comment by rexave** [comment]
PR didn't move **for months** and when i finally decide to ask it just did 5h ago ... 
Sorry about that.
