### ISSUE TITLE
Request for removal of bruxy70/Garbage-Collection

### ISSUE THREAD

**Issue by corvus2606** [hacs/integration#3109]
### Repository

bruxy70/Garbage-Collection

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

No Longer maintained by the Author, no longer works in 2023.4

https://github.com/bruxy70/Garbage-Collection#end-of-support

### Link to issue

https://github.com/bruxy70/Garbage-Collection/issues/459

**Comment by nickrout** [comment]
This does work in 2023.4.1

**Comment by Sudo-Rob** [comment]
For me, it's not populating Calendar but otherwise working okay.
