### ISSUE TITLE
Config icons missing

### ISSUE THREAD

**Issue by jovoud** [hacs/integration#3131]
### Web browser

Chrome

### Web browser version

113.0.5672.126 (Official Build) (64-bit)

## System Information

version | core-2023.5.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.25
arch | x86_64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4835
Installed Version | 1.32.1
Stage | running
Available Repositories | 1350
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 48.5 GB
disk_used | 20.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.0), Log Viewer (0.15.1), UniFi Network Application (2.6.0), Node-RED (14.2.0), Grafana (8.3.0), Mosquitto broker (6.2.1), MariaDB (2.6.1), InfluxDB (4.7.0), Zigbee2MQTT (1.30.4-1), File editor (5.6.0), ESPHome (2023.5.1), Traccar (0.19.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15 May 2023 at 21:49
-- | --
current_recorder_run | 21 May 2023 at 17:58
estimated_db_size | 1024.44 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The hacs config buttons are missing.
My previously configured integrations in hacs are still running fine.

### Reproduction steps

No idea, had this before and the only way of getting it back was to completely reinstall HA + import backup

### Screenshots

https://ibb.co/kmBZkqz

### Javascript logs from your browser console

```text
page.js:192 Trace Protections
page.js:211  Protection is not enabled: Pref_AudioFingerprint
page.js:233 Pref_BatteryApi has run on: 192.168.1.64
page.js:233 Pref_CanvasFingerprint has run on: 192.168.1.64
page.js:233 Pref_ClientRects has run on: 192.168.1.64
page.js:233 Pref_HardwareSpoof has run on: 192.168.1.64
page.js:211  Protection is not enabled: Pref_NativeFunctions
page.js:211  Protection is not enabled: Pref_NetworkInformation
page.js:233 Pref_PingBlock has run on: 192.168.1.64
page.js:211  Protection is not enabled: Pref_PluginHide
page.js:211  Protection is not enabled: Pref_ReferHeader
page.js:211  Protection is not enabled: Pref_ScreenRes
page.js:211  Protection is not enabled: Pref_UserAgent
page.js:211  Protection is not enabled: Pref_WebGLFingerprint
page.js:233 Pref_WebRTC has run on: 192.168.1.64
loaded.js:18  [TracePage] Page loaded 
:8123/config/repairs:1 Uncaught (in promise) Object
 Trace Protections
 %c Protection is not enabled: Pref_AudioFingerprint font-size:1em;line-height:1.5em;color:amber;
 %cPref_BatteryApi has run on: 192.168.1.64 font-size:1em;line-height:1.5em;color:green;
 %cPref_CanvasFingerprint has run on: 192.168.1.64 font-size:1em;line-height:1.5em;color:green;
 %cPref_ClientRects has run on: 192.168.1.64 font-size:1em;line-height:1.5em;color:green;
 %cPref_HardwareSpoof has run on: 192.168.1.64 font-size:1em;line-height:1.5em;color:green;
 %c Protection is not enabled: Pref_NativeFunctions font-size:1em;line-height:1.5em;color:amber;
 %c Protection is not enabled: Pref_NetworkInformation font-size:1em;line-height:1.5em;color:amber;
 %cPref_PingBlock has run on: 192.168.1.64 font-size:1em;line-height:1.5em;color:green;
 %c Protection is not enabled: Pref_PluginHide font-size:1em;line-height:1.5em;color:amber;
 %c Protection is not enabled: Pref_ReferHeader font-size:1em;line-height:1.5em;color:amber;
 %c Protection is not enabled: Pref_ScreenRes font-size:1em;line-height:1.5em;color:amber;
 %c Protection is not enabled: Pref_UserAgent font-size:1em;line-height:1.5em;color:amber;
 %c Protection is not enabled: Pref_WebGLFingerprint font-size:1em;line-height:1.5em;color:amber;
 %cPref_WebRTC has run on: 192.168.1.64 font-size:1em;line-height:1.5em;color:green;
 %c [TracePage] Page loaded  font-size:1em;line-height:1.5em;color:#1a1a1a;background-color:#fff;border:.1em solid #00af00;
 Trace Protections
 %c Protection is not enabled: Pref_AudioFingerprint font-size:1em;line-height:1.5em;color:amber;
 %cPref_BatteryApi has run on: 192.168.1.64 font-size:1em;line-height:1.5em;color:green;
 %cPref_CanvasFingerprint has run on: 192.168.1.64 font-size:1em;line-height:1.5em;color:green;
 %cPref_ClientRects has run on: 192.168.1.64 font-size:1em;line-height:1.5em;color:green;
 %cPref_HardwareSpoof has run on: 192.168.1.64 font-size:1em;line-height:1.5em;color:green;
 %c Protection is not enabled: Pref_NativeFunctions font-size:1em;line-height:1.5em;color:amber;
 %c Protection is not enabled: Pref_NetworkInformation font-size:1em;line-height:1.5em;color:amber;
 %cPref_PingBlock has run on: 192.168.1.64 font-size:1em;line-height:1.5em;color:green;
 %c Protection is not enabled: Pref_PluginHide font-size:1em;line-height:1.5em;color:amber;
 %c Protection is not enabled: Pref_ReferHeader font-size:1em;line-height:1.5em;color:amber;
 %c Protection is not enabled: Pref_ScreenRes font-size:1em;line-height:1.5em;color:amber;
 %c Protection is not enabled: Pref_UserAgent font-size:1em;line-height:1.5em;color:amber;
 %c Protection is not enabled: Pref_WebGLFingerprint font-size:1em;line-height:1.5em;color:amber;
 %cPref_WebRTC has run on: 192.168.1.64 font-size:1em;line-height:1.5em;color:green;
 %c [TracePage] Page loaded  font-size:1em;line-height:1.5em;color:#1a1a1a;background-color:#fff;border:.1em solid #00af00;
```

### Diagnostics dump

Can't do this because those buttons are missing...

**Comment by ludeeus** [comment]
You are confused, HACS has never done integration configuration.
That's on the integration panel of HA.
