### ISSUE TITLE
HACS is disabled - rate_limit

### ISSUE THREAD

**Issue by woempiej** [hacs/integration#3133]
## System Information

version | core-2023.5.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.25
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 1008
Installed Version | 1.32.1
Stage | setup
Available Repositories | 1287
Downloaded Repositories | 38
Disabled | rate_limit

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 687.0 GB
disk_used | 20.0 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Terminal & SSH (9.7.0), Samba share (10.0.1), Let's Encrypt (4.12.8), NGINX Home Assistant SSL proxy (3.5.0), Mosquitto broker (6.2.1), Frigate (0.12.0), ha-sip (2.9)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 25
views | 14
mode | storage

</details>

<details><summary>Miele</summary>

component_version | 0.1.13
-- | --
reach_miele_cloud | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 13 mei 2023 om 22:45
-- | --
current_recorder_run | 23 mei 2023 om 19:49
estimated_db_size | 435.75 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Hi,

HACS does not start anymore.

### Reproduction steps

1. Restart HA the normal way
2. Restart HA Machine
3. Checked older issues like https://github.com/hacs/integration/issues/1864

### Debug logs

```text
Logger: custom_components.hacs
Source: custom_components/hacs/base.py:473
Integration: HACS (documentation, issues)
First occurred: 19:49:47 (1 occurrences)
Last logged: 19:49:47
HACS is disabled - rate_limit
```

**Comment by ludeeus** [comment]
Wait 1h
