### ISSUE TITLE
Request for removal of catppuccin/home-assistant

### ISSUE THREAD

**Issue by labaland** [hacs/integration#3136]
### Repository

catppuccin/home-assistant

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

No longer active on github and not updating things missing in theme, like sliders are missing in theme.
see github:

### Link to issue

https://github.com/catppuccin/home-assistant/issues

**Comment by ludeeus** [comment]
Was active < 2 month ago.
It's too early to remove.
