### ISSUE TITLE
HACS crashed/freezes HA when enabling experimental features

### ISSUE THREAD

**Issue by AJediIAm** [hacs/integration#3137]
## System Information

version | core-2023.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4496
Installed Version | 1.32.1
Stage | running
Available Repositories | 1288
Downloaded Repositories | 37
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | xxxx
relayer_connected | true
relayer_region | xxxx
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | xxxx
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 229.2 GB
disk_used | 33.0 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | MariaDB (2.6.1), Home Assistant Google Drive Backup (0.110.4), Studio Code Server (5.6.0), ...

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 24
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 28, 2023 at 12:16
-- | --
current_recorder_run | May 28, 2023 at 12:39
estimated_db_size | 2212.52 MiB
database_engine | mysql
database_version | 10.6.12

</details>## System Information

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I enabled the Experimental features in HACS and HA crashed/froze. 
I forced a reboot by pulling the power after 5 minutes. 

After the reboot, everything seemed to work fine. 
There were some updates which I installed already in the past. It was no problem to install them again. 

I'm not very tempted to try to reproduce the issue, but let me know if I can help with further troubleshooting. 

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
I did not have debug logs enabled at the time of the crash.
I was unable to find any HACS related errors after the reboot in the log files.
```

**Comment by ludeeus** [comment]
Without logs here and/or profiler there is not much to go on.
