### ISSUE TITLE
Request for removal of mtrab/clever

### ISSUE THREAD

**Issue by MTrab** [hacs/integration#3142]
### Repository

mtrab/clever

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

I have requested removal via PR https://github.com/hacs/default/pull/1924 which get auto-closed

### Link to issue

https://github.com/hacs/default/issues/1925

**Comment by ludeeus** [comment]
Should be fixed now <https://github.com/hacs/bot/commit/abd2282a15b6cd8a9b36a72b121f588892de41fa>
