### ISSUE TITLE
Request for removal of jeroenterheerdt/HAsmartirrigation

### ISSUE THREAD

**Issue by ByronAP** [hacs/integration#3143]
### Repository

jeroenterheerdt/HAsmartirrigation

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

No longer updated and requires modifications to function correctly.

### Link to issue

https://github.com/jeroenterheerdt/HAsmartirrigation/issues

**Comment by ludeeus** [comment]
<https://github.com/jeroenterheerdt/HAsmartirrigation/issues/130#issuecomment-1589525696>
