### ISSUE TITLE
Request for removal of J-Lindvig/Gasprices_DK

### ISSUE THREAD

**Issue by kasper-leFevre** [hacs/integration#3147]
### Repository

J-Lindvig/Gasprices_DK

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

is does not exist anymore

### Link to issue

none the repository is gone

**Comment by ludeeus** [comment]
<https://github.com/hacs/default/blob/master/integration#L415> It does not exist in HACS default.
