### ISSUE TITLE
Request for removal of ha0y/xiaomi_miot_raw

### ISSUE THREAD

**Issue by an56gh** [hacs/integration#3159]
### Repository

ha0y/xiaomi_miot_raw

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

The project has not been updated for over a year (latest commit at 2022-04-10) and the maintainer cannot be reached. It also does not work in recent versions of HA. The following are some serious bugs that have not been fixed:

- https://github.com/ha0y/xiaomi_miot_raw/issues/519
- https://github.com/ha0y/xiaomi_miot_raw/issues/518
- https://github.com/ha0y/xiaomi_miot_raw/issues/516

### Link to issue

https://github.com/ha0y/xiaomi_miot_raw/issues/518

**Comment by aserno** [comment]
Is there an alternative? Mine is still working. I need this for my yeelight dual control switches
