### ISSUE TITLE
Notification of new integrations

### ISSUE THREAD

**Issue by lukyjay** [hacs/integration#3167]
### Web browser

Home assistant app

### Web browser version

Latest in google play

## System Information

version | core-2023.6.0
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | root
virtualenv | true
python_version | 3.10.8
os_name | Linux
os_version | 5.15.107-2-pve
arch | x86_64
timezone | Australia/Perth
config_dir | /root/.homeassistant

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4994
Installed Version | 1.32.1
Stage | running
Available Repositories | 1285
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 14, 2024 at 8:00 AM
relayer_connected | true
relayer_region | ap-southeast-1
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | ap-southeast-1-1.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 1
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 8, 2023 at 5:24 AM
-- | --
current_recorder_run | June 15, 2023 at 6:06 AM
estimated_db_size | 358.60 MiB
database_engine | sqlite
database_version | 3.34.1

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

In the past opening HACS would show new integrations and add-ons added to the repository but I haven't seen any appear in a few months. Is there any way to reenable this feature?

### Reproduction steps

1. Open HACS interface 
2. Select a category 
3. (Used to see new add-ons in green at the top)

### Screenshots

No screenshot to show 

### Javascript logs from your browser console

```text
Using android app
```

**Comment by ludeeus** [comment]
Nothing has been added.
