### ISSUE TITLE
Request for removal of Kibibit/hass-kibibit-theme

### ISSUE THREAD

**Issue by labaland** [hacs/integration#3171]
### Repository

Kibibit/hass-kibibit-theme

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Not answering question ppl ask questions about it and things that must be changed.
se url for example

### Link to issue

https://github.com/Kibibit/hass-kibibit-theme/issues/121

**Comment by ludeeus** [comment]
Removed here https://github.com/hacs/default/commit/9dffc402397f6a7f7894133c8d541edf3e07a69d
