### ISSUE TITLE
HACS not getting installed

### ISSUE THREAD

**Issue by MatessakCZE** [hacs/integration#3172]
## System Information

version | core-2023.5.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 5.10.0-23-amd64
arch | x86_64
timezone | Europe/Prague
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | failed to load: unreachable
can_reach_cloud_auth | failed to load: unreachable
can_reach_cloud | failed to load: unreachable

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 4
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 19, 2023 at 1:44 PM
-- | --
current_recorder_run | June 25, 2023 at 8:57 PM
estimated_db_size | 414.07 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I got an unknown error while trying to install some integrations. So i tried to reinstall it, deleted hacs directory and now I was trying to install it through the normal integrations installer but it shows Could not authenticate with GitHub, try again later.

### Reproduction steps

1. Uninstall HACS
2. Remove HACS directory
3. Install HACS through wget installer
4. install HACS through integrations installer
5.
...

### Debug logs

```text
Logger: custom_components.hacs
Source: custom_components/hacs/config_flow.py:49
Integration: HACS (documentation, issues)
First occurred: 8:58:24 PM (1 occurrences)
Last logged: 8:58:24 PM

Request exception for 'https://github.com/login/device/code' with - Cannot connect to host github.com:443 ssl:default [Try again]
```

**Comment by ludeeus** [comment]
It's not HACS.
When you fix your network issues HACS and other things can work.

**Comment by MatessakCZE** [comment]
Wdym by network issues? Well it is true that it stopped working after I changed our main router at home that I forgot to mention, but I also restarted the whole pc that it is running on. How can I fix this?
