### ISSUE TITLE
Update 1.06 to 1,07 does not end and even always offers after delete the package hikvision NRV/IP camera

### ISSUE THREAD

**Issue by ashkii7** [hacs/integration#3178]
### Describe the issue

1 - Update 1.06 to 1,07 from Hikvision NVR/IP Camera does not end, it turns endless
2 - I deleted hacs from the "custom_comnents" file even after having restarted Ha, he always offers me the update.
# - I reinstalled hacs with the latest version (1.32.1) but it always asks me to update Hikvisionnvr/IP Camera of 1.06. to 1.07.
what can I do ?
Sorry for my english, google trad is my friend ...

### Link to action run

?

### Link to action configuration

?

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
Ask the author of it.

**Comment by ashkii7** [comment]
who is, how can i do this ?

**Comment by ashkii7** [comment]
OK please delete this issue
