### ISSUE TITLE
HACS entities have no unique_id

### ISSUE THREAD

**Issue by doosterkamp** [hacs/integration#3202]
## System Information

version | core-2023.7.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.34
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4987
Installed Version | 1.32.1
Stage | running
Available Repositories | 1339
Downloaded Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 234.0 GB
disk_used | 8.2 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.8.2), MariaDB (2.6.1), Home Assistant Google Drive Backup (0.111.1), Advanced SSH & Web Terminal (15.0.4), InfluxDB (4.7.0), Mosquitto broker (6.2.1), Samba share (10.0.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 13 juli 2023 om 13:09
-- | --
current_recorder_run | 20 juli 2023 om 17:16
estimated_db_size | 33.77 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The entities generated by HACS have no unique id, so they can't be renamed or be hidden

### Reproduction steps

1. Just try to rename the hacs update entity
2.
3.
...

### Debug logs

```text
n.a.
```

### Diagnostics dump

n.a.

**Comment by ludeeus** [comment]
You need to enable experimental features for that.
