### ISSUE TITLE
Request for removal of hasscc/yeelight-pro

### ISSUE THREAD

**Issue by GZM4587** [hacs/integration#3205]
### Repository

hasscc/yeelight-pro

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Impact apple HomeKit usage

### Link to issue

No url

**Comment by KTibow** [comment]
- this is your first issue ever
- you did not "try to get the authors attention to the reason for removal"
- "Impact apple HomeKit usage" is extremely vague
