### ISSUE TITLE
Telenet not found

### ISSUE THREAD

**Issue by Krispkiwi** [hacs/integration#3206]
## System Information

version | core-2023.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Pacific/Auckland
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4987
Installed Version | 1.32.1
Stage | running
Available Repositories | 1260
Downloaded Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 109.3 GB
disk_used | 7.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (15.0.5), File editor (5.6.0), Studio Code Server (5.9.0), MariaDB (2.6.1), Samba share (10.0.2), Home Assistant Google Drive Backup (0.111.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 30, 2023 at 2:52 AM
-- | --
current_recorder_run | July 30, 2023 at 6:16 PM
estimated_db_size | 1.59 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Integration geertmeersman/telenet> GitHub returned HttpStatusCode.NOT_FOUND for https://api.github.com/repos/geertmeersman/telenet in logs

### Reproduction steps

1. Install hacs from terminal
2. restart home assistant
3. add hacs integration from integrations
4. Check logs

### Debug logs

```text
Shouldn't be necessary, repo github hacs relies on appears to be down.
```

**Comment by tjorim** [comment]
Related PR: https://github.com/hacs/default/pull/1991

**Comment by Krispkiwi** [comment]
Apologies, I looked at the issue page but only saw #3205 so didn't see that one.
