### ISSUE TITLE
Removed repository 'geertmeersman/telenet' message keeps displaying : ignore does not work

### ISSUE THREAD

**Issue by eddysteurs** [hacs/integration#3211]
### Repository

 'geertmeersman/telenet'

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

the repository has been removed (not reason why?) on github, when using the delete button in HACS pressed it keeps running, manually deleted 'integration' and folder (custom ), restarted HA but message keeps displaying , pressing 'ignore' does nothing

### Link to issue

.

**Comment by ludeeus** [comment]
This has been removed.
If you have a bug fill in the backend bug issue template.
