### ISSUE TITLE
Removed repository: button to ignore or remove custom component does not work

### ISSUE THREAD

**Issue by XalaTheShepard** [hacs/integration#3212]
### Web browser

Google Chrome / Mozilla Firefox / Chromium

### Web browser version

Latest

## System Information

version | core-2023.8.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.39
arch | x86_64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4987
Installed Version | 1.32.1
Stage | running
Available Repositories | 1343
Downloaded Repositories | 50

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 49

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 97.7 GB
disk_used | 22.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), File editor (5.6.0), AppDaemon (0.13.3), Spotify Connect (0.12.4), Terminal & SSH (9.7.1), Home Assistant Google Drive Backup (0.111.1), Node-RED (14.4.3), AdGuard Home (4.8.13), Samba share (10.0.2), Studio Code Server (5.10.0), UniFi Network Application (2.7.0), Mosquitto broker (6.2.1), PS5 MQTT (1.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 16
views | 21
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 26, 2023 at 2:02 PM
-- | --
current_recorder_run | August 3, 2023 at 2:22 PM
estimated_db_size | 518.96 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

After updating to the latest HA core release (not related) I got the message in HACS that one of my repositories has been deleted. 
I have opened this message by pressing on show. 
Since I wanted to keep that custom component, I have selected the button "ignore". 
Both on my smartphone as on my pc, this button does nothing and the message remains. 
I have made a copy of the folder of the custom component and pressed the button remove. 
But this button also does nothing in both the Android application of HA and in the web browser on my pc. 

### Reproduction steps

1. Have a custom component installed of which the repository has been removed
2. Open HACS and click on the button "Show" in the error message. 
3. Try the buttons "Ignore" or "Remove" that do not respond.
...

### Screenshots

![image](https://github.com/hacs/integration/assets/69390987/4993414a-d0d1-4fee-9c75-99708c947558)

### Javascript logs from your browser console

```text
﻿
github-entity-row.js…stag=184658908210:1 Uncaught ReferenceError: Polymer is not defined
    at github-entity-row.js…g=184658908210:1:31
```

### Diagnostics dump

https://xala-the-shepherd.synology.me:8123/hacsfiles/lovelace-github-entity-row/github-entity-row.js?hacstag=184658908210:1:31 Uncaught ReferenceError: Polymer is not defined
6:05:09 PM – (ERROR) components/system_log/__init__.py - message first occurred at August 3, 2023 at 2:40:50 PM and shows up 15 times
[140534264650944] Error handling message: Unknown error (unknown_error) Robin De Becker from 2a02:1811:2d2d:2b00:d8a6:e1c7:369c:8f12 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36)
4:55:39 PM – (ERROR) Home Assistant WebSocket API (custom integration) - message first occurred at August 3, 2023 at 2:44:50 PM and shows up 3 times
[140536262029248] Error handling message: Unknown error (unknown_error) Robin De Becker from 192.168.0.1 (Mozilla/5.0 (Linux; Android 10; VOG-L29 Build/HUAWEIVOG-L29; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Mobile Safari/537.36 Home Assistant/2023.7.5-10506 (Android 10; VOG-L29))
4:36:18 PM – (ERROR) Home Assistant WebSocket API (custom integration) - message first occurred at 4:33:58 PM and shows up 3 times
<Integration geertmeersman/telenet> GitHub returned HttpStatusCode.NOT_FOUND for https://api.github.com/repos/geertmeersman/telenet
4:36:18 PM – (ERROR) HACS (custom integration) - message first occurred at August 3, 2023 at 2:26:10 PM and shows up 4 times
https://xala-the-shepherd.synology.me:8123/hacsfiles/lovelace-github-entity-row/github-entity-row.js?hacstag=184658908210:1:31 Uncaught ReferenceError: Polymer is not defined
7:50:00 AM – (ERROR) components/system_log/__init__.py
<QueueManager> No manifest.json file found 'custom_components/None/manifest.json'
August 3, 2023 at 2:26:19 PM – (ERROR) HACS (custom integration)

**Comment by ludeeus** [comment]
Post diagostics,

**Comment by XalaTheShepard** [comment]
https://xala-the-shepherd.synology.me:8123/hacsfiles/lovelace-github-entity-row/github-entity-row.js?hacstag=184658908210:1:31 Uncaught ReferenceError: Polymer is not defined
6:05:09 PM – (ERROR) components/system_log/__init__.py - message first occurred at August 3, 2023 at 2:40:50 PM and shows up 15 times
[140534264650944] Error handling message: Unknown error (unknown_error) Robin De Becker from 2a02:1811:2d2d:2b00:d8a6:e1c7:369c:8f12 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36)
4:55:39 PM – (ERROR) Home Assistant WebSocket API (custom integration) - message first occurred at August 3, 2023 at 2:44:50 PM and shows up 3 times
[140536262029248] Error handling message: Unknown error (unknown_error) Robin De Becker from 192.168.0.1 (Mozilla/5.0 (Linux; Android 10; VOG-L29 Build/HUAWEIVOG-L29; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Mobile Safari/537.36 Home Assistant/2023.7.5-10506 (Android 10; VOG-L29))
4:36:18 PM – (ERROR) Home Assistant WebSocket API (custom integration) - message first occurred at 4:33:58 PM and shows up 3 times
<Integration geertmeersman/telenet> GitHub returned HttpStatusCode.NOT_FOUND for https://api.github.com/repos/geertmeersman/telenet
4:36:18 PM – (ERROR) HACS (custom integration) - message first occurred at August 3, 2023 at 2:26:10 PM and shows up 4 times
https://xala-the-shepherd.synology.me:8123/hacsfiles/lovelace-github-entity-row/github-entity-row.js?hacstag=184658908210:1:31 Uncaught ReferenceError: Polymer is not defined
7:50:00 AM – (ERROR) components/system_log/__init__.py
<QueueManager> No manifest.json file found 'custom_components/None/manifest.json'
August 3, 2023 at 2:26:19 PM – (ERROR) HACS (custom integration)

**Comment by ludeeus** [comment]
That is not diagnostics

**Comment by XalaTheShepard** [comment]
Could you please inform me how I can get the diagnostics? I really don't know what it could otherwise be

**Comment by Qusse** [comment]
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/websocket/repository.py:106
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: August 4, 2023 at 17:45:54 (11 occurrences)
Last logged: 10:24:51

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 106, in hacs_repository_ignore
    hacs.common.ignored_repositories.add(repository.data.full_name)
                                         ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
```

This is the error logged when pressing "ignore" button.

**Comment by garry0garry** [comment]
Home Assistant 2023.8.4, Home Assistant Community Store 1.32.1.

Removed https://github.com/JimStar/reolink_cctv integration from GitHub. **How to remove this integration from HACS?** There is no "three dots" menu.

![изображение](https://github.com/hacs/integration/assets/95581374/72866557-66e3-4e88-83d3-1aaf935fd7f8)

```
Logger: custom_components.hacs
Source: custom_components/hacs/utils/queue_manager.py:71
Integration: HACS (documentation, issues)
First occurred: 13:28:07 (1 occurrences)
Last logged: 13:28:07

<QueueManager> No manifest.json file found 'custom_components/None/manifest.json'
```
```
Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:519
Integration: HACS (documentation, issues)
First occurred: 13:28:05 (2 occurrences)
Last logged: 13:28:24

<Integration JimStar/reolink_cctv> GitHub returned HttpStatusCode.NOT_FOUND for https://api.github.com/repos/JimStar/reolink_cctv
```
