### ISSUE TITLE
Failed to call service button/press

### ISSUE THREAD

**Issue by GithRS** [hacs/integration#3216]
## System Information

version | core-2023.8.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.39
arch | aarch64
timezone | Europe/Tallinn
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.32.1
Stage | running
Available Repositories | 1266
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 114.1 GB
disk_used | 6.7 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), File editor (5.6.0), ESPHome (2023.7.1), Mosquitto broker (6.2.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 1
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 29, 2023 at 09:30
-- | --
current_recorder_run | August 7, 2023 at 11:04
estimated_db_size | 118.61 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When pressing reflux power slider it usually slides back to zero, sometimes stays where do I slide it. If I press reflux control button system gives an error: failed to call service button/press. H' format requires 0 <= number <= 65535.

### Reproduction steps

1. can write anything here
2.
3.
...

### Debug logs

```text
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/solax_modbus/__init__.py:412
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:19:36 (5 occurrences)
Last logged: 22:47:47

[281473060336576] 'H' format requires 0 <= number <= 65535
[281472893216448] 'H' format requires 0 <= number <= 65535
[281472925164992] 'H' format requires 0 <= number <= 65535
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 124, in _async_press_action
    await self.async_press()
  File "/config/custom_components/solax_modbus/button.py", line 86, in async_press
    if res: self._hub.write_registers_multi(unit=self._modbus_addr, address=self._register, payload=res)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solax_modbus/__init__.py", line 412, in write_registers_multi
    if   typ == REGISTER_U16: builder.add_16bit_uint(value)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymodbus/payload.py", line 162, in add_16bit_uint
    self._payload.append(pack(fstring, value))
                         ^^^^^^^^^^^^^^^^^^^^
struct.error: 'H' format requires 0 <= number <= 65535
```

### Diagnostics dump

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.8.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Tallinn",
    "os_name": "Linux",
    "os_version": "6.1.39",
    "supervisor": "2023.07.1",
    "host_os": "Home Assistant OS 10.4",
    "docker_version": "23.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "solarman": {
      "version": "1.0.0",
      "requirements": [
        "pyyaml"
      ]
    },
    "dwd": {
      "version": "2023.2.0",
      "requirements": []
    },
    "nordpool": {
      "version": "0.0.14",
      "requirements": [
        "nordpool>=0.2",
        "backoff"
      ]
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "apex": {
      "version": "1.14",
      "requirements": []
    },
    "solax_modbus": {
      "version": "2023.08.3",
      "requirements": [
        "pymodbus>=2.5.3",
        "pymodbus<=3.3.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "hacs",
    "name": "HACS",
    "codeowners": [
      "@ludeeus"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "websocket_api",
      "frontend",
      "persistent_notification",
      "lovelace",
      "repairs"
    ],
    "documentation": "https://hacs.xyz/docs/configuration/start",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/hacs/integration/issues",
    "requirements": [
      "aiogithubapi>=22.10.1"
    ],
    "version": "1.32.1",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "b410563bc207c181dc09011748e00756",
      "version": 1,
      "domain": "hacs",
      "title": "",
      "data": {
        "token": "**REDACTED**"
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "hacs": {
      "stage": "running",
      "version": "1.32.1",
      "disabled_reason": null,
      "new": false,
      "startup": false,
      "categories": [
        "plugin",
        "theme",
        "integration"
      ],
      "renamed_repositories": {
        "Farfar/homeassistant-skodaconnect": "skodaconnect/homeassistant-skodaconnect",
        "lendy007/homeassistant-skodaconnect": "skodaconnect/homeassistant-skodaconnect",
        "mtarjoianu/ha_lektrico": "Lektrico/ha_lektrico",
        "JoshuaMulliken/ha-wyzeapi": "SecKatie/ha-wyzeapi"
      },
      "archived_repositories": [
        "robmarkcole/HASS-Deepstack-face",
        "JuanMTech/green_light_mode",
        "JuanMTech/green_dark_mode",
        "cgarwood/homeassistant-fullykiosk",
        "walthowd/ha-automower",
        "bieniu/ha-zadnego-ale",
        "robmarkcole/HASS-Deepstack-object",
        "Raukze/home-assistant-fitx",
        "AitorDB/home-assistant-sun-card",
        "JuanMTech/orange_dark",
        "peternijssen/home-assistant-jumbo",
        "nagyrobi/home-assistant-custom-components-cover-rf-time-based",
        "JuanMTech/orange_light",
        "JuanMTech/amoled_blue"
      ],
      "ignored_repositories": [],
      "lovelace_mode": "storage",
      "configuration": {
        "appdaemon": false,
        "country": "ALL",
        "debug": false,
        "dev": false,
        "experimental": false,
        "netdaemon": false,
        "python_script": false,
        "release_limit": 5,
        "theme": false
      }
    },
    "custom_repositories": [],
    "repositories": [
      {
        "data": {
          "archived": false,
          "authors": [
            "@StephanJoubert"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "main",
          "description": "Home Assistant component for Solarman collectors used with a variety of inverters.  ",
          "domain": "solarman",
          "downloads": 0,
          "etag_repository": "W/\"0e6fc4f290a180bdae617e882c0bb84812ff16e1ad2cc63a34282a68f80283ab\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "StephanJoubert/home_assistant_solarman",
          "hide": false,
          "has_issues": true,
          "id": "427902632",
          "installed_commit": "f3b8031",
          "installed_version": "v1.4.3",
          "installed": true,
          "last_commit": "45d55ea",
          "last_updated": "2023-08-04T16:50:45Z",
          "last_version": "v1.4.3",
          "manifest_name": "Solarman",
          "new": false,
          "open_issues": 152,
          "published_tags": [
            "v1.4.3",
            "v1.4.2",
            "v1.4.1",
            "v1.4.0",
            "v1.3.0"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 350,
          "topics": [
            "deye",
            "energy",
            "inverter",
            "sofar",
            "sol-ark",
            "solar",
            "solarman",
            "solis",
            "sunsynk"
          ]
        },
        "integration_manifest": {
          "domain": "solarman",
          "name": "Solarman",
          "documentation": "https://github.com/StephanJoubert/home_assistant_solarman/blob/main/README.md",
          "version": "1.0.0",
          "config_flow": true,
          "dependencies": [],
          "codeowners": [
            "@StephanJoubert"
          ],
          "issue_tracker": "https://github.com/StephanJoubert/home_assistant_solarman/issues",
          "requirements": [
            "pyyaml"
          ],
          "iot_class": "local_polling"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": null,
          "manifest": {
            "name": "Solarman Integration"
          },
          "name": "Solarman Integration",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": false
        },
        "ref": "v1.4.3",
        "paths": {
          "localpath": "/config/custom_components/solarman",
          "local": "/config/custom_components/solarman",
          "remote": "custom_components/solarman"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@itchannel"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "master",
          "description": "Local Neptune Apex HA Integration (Aquarium Controller)",
          "domain": "apex",
          "downloads": 0,
          "etag_repository": "W/\"244cdc1c20b3cb413326d2d6512f97570c64248bf0019f2443995b32b3795d7c\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "itchannel/apex-ha",
          "hide": false,
          "has_issues": true,
          "id": "517642950",
          "installed_commit": "2e66e4f",
          "installed_version": "1.14-Release",
          "installed": true,
          "last_commit": "2e66e4f",
          "last_updated": "2023-08-04T11:26:42Z",
          "last_version": "1.14-Release",
          "manifest_name": "Apex",
          "new": false,
          "open_issues": 15,
          "published_tags": [
            "1.14-Release",
            "1.13-Release",
            "1.12-Release",
            "1.11-Release",
            "1.10-Release"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 8,
          "topics": [
            "aquarium",
            "aquarium-controller"
          ]
        },
        "integration_manifest": {
          "domain": "apex",
          "name": "Apex",
          "codeowners": [
            "@itchannel"
          ],
          "config_flow": true,
          "dependencies": [],
          "documentation": "https://github.com/itchannel/apex-ha",
          "homekit": {},
          "integration_type": "device",
          "iot_class": "local_polling",
          "issue_tracker": "https://github.com/itchannel/apex-ha/issues",
          "loggers": [
            "custom_components.apex"
          ],
          "requirements": [],
          "ssdp": [],
          "version": "1.14",
          "zeroconf": []
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": null,
          "manifest": {
            "name": "Apex"
          },
          "name": "Apex",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": false
        },
        "ref": "1.14-Release",
        "paths": {
          "localpath": "/config/custom_components/apex",
          "local": "/config/custom_components/apex",
          "remote": "custom_components/apex"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@hellowlol"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "master",
          "description": "This component allows you to pull in the energy prices into Home-Assistant.",
          "domain": "nordpool",
          "downloads": 0,
          "etag_repository": "W/\"0fd53e5113a85d53c678fc4ce822844687a858c6a88ad8398cf390344a5b2a25\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "custom-components/nordpool",
          "hide": false,
          "has_issues": true,
          "id": "201805130",
          "installed_commit": "649bf97",
          "installed_version": "0.0.14",
          "installed": true,
          "last_commit": "649bf97",
          "last_updated": "2023-08-04T11:37:05Z",
          "last_version": "0.0.14",
          "manifest_name": "Nord Pool",
          "new": false,
          "open_issues": 20,
          "published_tags": [
            "0.0.14",
            "0.0.13",
            "0.0.12",
            "0.0.11",
            "0.0.10"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 334,
          "topics": [
            "energy-prices",
            "nordpool"
          ]
        },
        "integration_manifest": {
          "domain": "nordpool",
          "name": "Nord Pool",
          "after_dependencies": [
            "http"
          ],
          "codeowners": [
            "@hellowlol"
          ],
          "config_flow": true,
          "dependencies": [],
          "documentation": "https://github.com/custom-components/nordpool/",
          "iot_class": "cloud_polling",
          "issue_tracker": "https://github.com/custom-components/nordpool/issues",
          "requirements": [
            "nordpool>=0.2",
            "backoff"
          ],
          "version": "0.0.14"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": null,
          "manifest": {
            "name": "nordpool",
            "render_readme": true
          },
          "name": "nordpool",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": "0.0.14",
        "paths": {
          "localpath": "/config/custom_components/nordpool",
          "local": "/config/custom_components/nordpool",
          "remote": "custom_components/nordpool"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "config_flow": false,
          "default_branch": "master",
          "description": "\ud83d\udcc8 A Lovelace card to display advanced graphs and charts based on ApexChartsJS for Home Assistant",
          "domain": "",
          "downloads": 47204,
          "etag_repository": "W/\"34cbec7e7a13713d46d48516770366aeb13dab35fee46c2ece074ad695ab1b13\"",
          "etag_releases": null,
          "file_name": "apexcharts-card.js",
          "first_install": false,
          "full_name": "RomRider/apexcharts-card",
          "hide": false,
          "has_issues": true,
          "id": "331701152",
          "installed_commit": "1b63c0f",
          "installed_version": "v2.0.4",
          "installed": true,
          "last_commit": "1b63c0f",
          "last_updated": "2023-08-06T11:56:29Z",
          "last_version": "v2.0.4",
          "manifest_name": null,
          "new": false,
          "open_issues": 50,
          "published_tags": [
            "v2.0.4",
            "v2.0.3",
            "v2.0.2",
            "v2.0.1",
            "v2.0.0"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 770,
          "topics": [
            "apexcharts",
            "iot"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": null,
          "manifest": {
            "name": "apexcharts-card",
            "render_readme": true
          },
          "name": "apexcharts-card",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": "v2.0.4",
        "paths": {
          "localpath": "/config/www/community/apexcharts-card",
          "local": "/config/www/community/apexcharts-card",
          "remote": "release"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@wills106"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "main",
          "description": "SolaX Power Modbus custom_component for Home Assistant (Supports some Ginlong Solis, Growatt, Sofar Solar & Qcells Q.Volt Hyb)",
          "domain": "solax_modbus",
          "downloads": 0,
          "etag_repository": "W/\"55a2ccf6fbf37dd3243a8452b22008f5a7230ef9d15509e4d0a8c5a16d0093b6\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "wills106/homeassistant-solax-modbus",
          "hide": false,
          "has_issues": true,
          "id": "394704821",
          "installed_commit": "b7e95ff",
          "installed_version": "2023.08.3",
          "installed": true,
          "last_commit": "b7e95ff",
          "last_updated": "2023-08-02T08:55:59Z",
          "last_version": "2023.08.3",
          "manifest_name": "SolaX Inverter Modbus",
          "new": false,
          "open_issues": 28,
          "published_tags": [
            "2023.08.3",
            "2023.08.2",
            "2023.08.1",
            "2023.07.3",
            "2023.07.2"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 142,
          "topics": [
            "ginlong-solis",
            "growatt",
            "modbus",
            "modbus-rtu",
            "modbus-serial",
            "modbus-tcp",
            "qcells",
            "qvolt-inverter",
            "rs485",
            "sofar",
            "sofar-hyd",
            "sofarsolar",
            "solax",
            "solis"
          ]
        },
        "integration_manifest": {
          "domain": "solax_modbus",
          "name": "SolaX Inverter Modbus",
          "codeowners": [
            "@wills106"
          ],
          "config_flow": true,
          "dependencies": [],
          "documentation": "https://github.com/wills106/homsassistant-solax-modbus",
          "integration_type": "hub",
          "iot_class": "local_polling",
          "issue_tracker": "https://github.com/wills106/homsassistant-solax-modbus/issues",
          "requirements": [
            "pymodbus>=2.5.3",
            "pymodbus<=3.3.1"
          ],
          "version": "2023.08.3"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": null,
          "manifest": {
            "name": "SolaX Inverter Modbus",
            "render_readme": true
          },
          "name": "SolaX Inverter Modbus",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": "2023.08.3",
        "paths": {
          "localpath": "/config/custom_components/solax_modbus",
          "local": "/config/custom_components/solax_modbus",
          "remote": "custom_components/solax_modbus"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@hg1337"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "main",
          "description": "Custom component for Home Assistant that integrates weather data (measurements and forecasts) of Deutscher Wetterdienst (DWD).",
          "domain": "dwd",
          "downloads": 0,
          "etag_repository": "W/\"cf0ac8131ba2acafac2930fbdf4fd8e721d699b8063461d2524e74931aa1ee9e\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "hg1337/homeassistant-dwd",
          "hide": false,
          "has_issues": true,
          "id": "324913968",
          "installed_commit": "30e80f8",
          "installed_version": "2023.2.0",
          "installed": true,
          "last_commit": "aac93db",
          "last_updated": "2023-08-06T17:38:40Z",
          "last_version": "2023.8.1",
          "manifest_name": "Deutscher Wetterdienst",
          "new": false,
          "open_issues": 0,
          "published_tags": [
            "2023.8.1",
            "2023.8.0",
            "2023.2.0",
            "2023.1.3",
            "2023.1.2"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 45,
          "topics": [
            "deutscher-wetterdienst",
            "dwd",
            "hacs-custom",
            "home-assistant-component",
            "home-assistant-custom-component",
            "home-assistant-integration",
            "home-assistant-weather",
            "homeassistant-component",
            "homeassistant-custom-component",
            "homeassistant-weather",
            "weather",
            "wetter"
          ]
        },
        "integration_manifest": {
          "domain": "dwd",
          "name": "Deutscher Wetterdienst",
          "codeowners": [
            "@hg1337"
          ],
          "config_flow": true,
          "documentation": "https://github.com/hg1337/homeassistant-dwd",
          "iot_class": "cloud_polling",
          "issue_tracker": "https://github.com/hg1337/homeassistant-dwd/issues",
          "requirements": [],
          "version": "2023.8.1"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2023.8.0",
          "manifest": {
            "name": "Deutscher Wetterdienst (by hg1337)",
            "homeassistant": "2023.8.0",
            "render_readme": true
          },
          "name": "Deutscher Wetterdienst (by hg1337)",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": "2023.8.1",
        "paths": {
          "localpath": "/config/custom_components/dwd",
          "local": "/config/custom_components/dwd",
          "remote": "custom_components/dwd"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@ludeeus"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "main",
          "description": "HACS gives you a powerful UI to handle downloads of all your custom needs.",
          "domain": "hacs",
          "downloads": 335644,
          "etag_repository": "W/\"c48d0c73f92f4cc37ae36c93aefc272347e613b605fdfbda7bab862c871973a8\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "hacs/integration",
          "hide": false,
          "has_issues": true,
          "id": "172733314",
          "installed_commit": "bec1933",
          "installed_version": "1.32.1",
          "installed": true,
          "last_commit": "5ba94d9",
          "last_updated": "2023-08-02T04:50:44Z",
          "last_version": "1.32.1",
          "manifest_name": "HACS",
          "new": false,
          "open_issues": 3,
          "published_tags": [
            "1.32.1",
            "1.32.0",
            "1.31.0",
            "1.30.1",
            "1.30.0"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 3808,
          "topics": [
            "community",
            "package-manager"
          ]
        },
        "integration_manifest": {
          "domain": "hacs",
          "name": "HACS",
          "codeowners": [
            "@ludeeus"
          ],
          "config_flow": true,
          "dependencies": [
            "http",
            "websocket_api",
            "frontend",
            "persistent_notification",
            "lovelace",
            "repairs"
          ],
          "documentation": "https://hacs.xyz/docs/configuration/start",
          "iot_class": "cloud_polling",
          "issue_tracker": "https://github.com/hacs/integration/issues",
          "requirements": [
            "aiogithubapi>=22.10.1"
          ],
          "version": "0.0.0"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "hacs.zip",
          "hacs": "0.19.0",
          "hide_default_branch": true,
          "homeassistant": "2022.11.0",
          "manifest": {
            "name": "HACS",
            "zip_release": true,
            "hide_default_branch": true,
            "homeassistant": "2022.11.0",
            "hacs": "0.19.0",
            "filename": "hacs.zip"
          },
          "name": "HACS",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": "1.32.1",
        "paths": {
          "localpath": "/config/custom_components/hacs",
          "local": "/config/custom_components/hacs",
          "remote": "custom_components/hacs"
        }
      }
    ],
    "rate_limit": {
      "resources": {
        "core": {
          "limit": 5000,
          "used": 14,
          "remaining": 4986,
          "reset": 1691441036
        },
        "search": {
          "limit": 30,
          "used": 0,
          "remaining": 30,
          "reset": 1691438421
        },
        "graphql": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1691441961
        },
        "integration_manifest": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1691441961
        },
        "source_import": {
          "limit": 100,
          "used": 0,
          "remaining": 100,
          "reset": 1691438421
        },
        "code_scanning_upload": {
          "limit": 1000,
          "used": 0,
          "remaining": 1000,
          "reset": 1691441961
        },
        "actions_runner_registration": {
          "limit": 10000,
          "used": 0,
          "remaining": 10000,
          "reset": 1691441961
        },
        "scim": {
          "limit": 15000,
          "used": 0,
          "remaining": 15000,
          "reset": 1691441961
        }
      },
      "rate": {
        "limit": 5000,
        "used": 14,
        "remaining": 4986,
        "reset": 1691441036
      }
    }
  }
}

**Comment by ludeeus** [comment]
You need to report that to solax_modbus
