### ISSUE TITLE
removing broken integration not possible

### ISSUE THREAD

**Issue by davidm-glitch** [hacs/integration#3222]
## System Information

version | core-2023.8.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.39
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4688
Installed Version | 1.32.1
Stage | running
Available Repositories | 1271
Downloaded Repositories | 19

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 20. November 2023 um 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-5.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 80.0 GB
disk_used | 69.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (14.4.5), Studio Code Server (5.10.0), Samba Backup (5.2.0), Mosquitto broker (6.2.1), Grafana (9.0.3), InfluxDB (4.7.0), Zigbee2MQTT (1.32.2-1), ESPHome (2023.7.1), Log Viewer (0.15.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 7
views | 18
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 10. März 2023 um 06:13
-- | --
current_recorder_run | 16. August 2023 um 19:13
estimated_db_size | 20843.08 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Solcast PV Forecast</summary>

can_reach_server | ok
-- | --
remaining_requests | 15
rooftop_site_count | 1
polling_hours | 6 -> 21 and once at midnight

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I have a broken installation of a custom integration from a custom repository. The repository works now on a fresh HACS install but on my machine its broken somehow. When I click on the (still installed) integration it shows "unknown error" and thats it. I dont have the possibility to remove it. I tried deleting the folder from the custom_components folder but this did not help. 

It is about the eheim-digital integration. How can I remove or freshly install this integration?

### Reproduction steps

I dont know what happened exactly, so I dont know how to reproduce it. 

### Debug logs

```text
log is too long to post here, uploaded it here:
https://hastebin.com/share/ivararuyeg.yaml
```

### Diagnostics dump

dump is too long to post here, uploaded it here:
https://hastebin.com/share/idahogubeb.swift

**Comment by ludeeus** [comment]
Your repository had releases in the past, which you now have removed.
The way I see it, there are 3 options:
a) Enable experimental features in HACS, it uses a new data model so might be fixed there.
b) Release a new version of your repo.
c) Wait until a fix is added to HACS, then wait until that is released, then update it.
