### ISSUE TITLE
Remove mac-zhou/midea-ac-py from default list

### ISSUE THREAD

**Issue by mill1000** [hacs/integration#3225]
### Repository

mac-zhou/midea-ac-py 

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

- Project hasn't seen any activity in the prior year. 
- Current release is broken and manifest references a non-existent PyPi package version.  
  - https://github.com/mac-zhou/midea-ac-py/issues/182, https://github.com/mac-zhou/midea-ac-py/issues/183, and https://github.com/mac-zhou/midea-ac-py/issues/197
- Multiple outstanding issues and PRs have not been responded.
  - https://github.com/mac-zhou/midea-ac-py/pull/214, https://github.com/mac-zhou/midea-ac-py/pull/177, https://github.com/mac-zhou/midea-ac-py/pull/179, and https://github.com/mac-zhou/midea-ac-py/pull/195

### Link to issue

See listed PRs above

**Comment by mill1000** [comment]
Thanks!

**Comment by cconnoruk** [comment]
Not sure what ‘this’ page means. But I do know that I have this live and working in my HA instance. So please don’t delete it as I wont have easy access to my AC units anymore.

**Comment by mill1000** [comment]
The integration won't (I assume) be removed from your HA instance, it's just no longer part of the default list.

Shameless plug. I'm maintaining a fork: [mill1000/midea-ac-py](https://github.com/mill1000/midea-ac-py), while it's not part of the default list yet (https://github.com/hacs/default/pull/2023) you can add it as a custom repo.

@tm24fan8 you may also be interested
