### ISSUE TITLE
Integration wont update

### ISSUE THREAD

**Issue by ThatOldDad** [hacs/integration#3228]
## System Information

version | core-2023.6.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.39
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4976
Installed Version | 1.24.5
Stage | running
Available Repositories | 1349
Downloaded Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | July 11, 2024 at 7:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-9.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 234.0 GB
disk_used | 155.6 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), File editor (5.6.0), Mosquitto broker (6.2.0), Z-Wave JS (0.1.79), Samba Backup (5.2.0), ESPHome (2023.8.2), Silicon Labs Multiprotocol (2.3.1), Node-RED (14.0.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 7
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 17, 2023 at 4:43 AM
-- | --
current_recorder_run | August 16, 2023 at 11:43 PM
estimated_db_size | 795.61 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When I try to update the HACS integration I get this error

No RepositoryFile.MAINIFEST_JSON file found 'custom_components/hacs/RepositoryFile.MAINIFEST_JSON'

at least one other hacs integration (node red helper) also behaves similarly

### Reproduction steps

1.just trying to update hacs in the UI
2.
3.
...

### Debug logs

```text
looking for a quick comment
```

**Comment by michelbalzer** [comment]
Is it really mainifest, not manifest?
