### ISSUE TITLE
Cannot connect to host Github

### ISSUE THREAD

**Issue by tomlulofs** [hacs/integration#3230]
## System Information

version | core-2023.8.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.45
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | failed to load: unreachable
can_reach_cloud_auth | failed to load: unreachable
can_reach_cloud | failed to load: unreachable

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 14.0 GB
disk_used | 4.2 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | failed to load: unreachable
installed_addons | Advanced SSH & Web Terminal (15.0.7), File editor (5.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 20 August 2023 at 18:58
-- | --
current_recorder_run | 23 August 2023 at 11:34
estimated_db_size | 1.14 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I'm trying to install HACS. But constantly get the same error "Cannot connect to host Github"

### Reproduction steps

1. Download HACS through SSD
2. Add HACS through the integrations section in HA
3. Opt in for all the checkboxes.

### Debug logs

```text
This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/config_flow.py:49
Integration: HACS (documentation, issues)
First occurred: 11:36:11 (7 occurrences)
Last logged: 15:46:09

Request exception for 'https://github.com/login/device/code' with - Cannot connect to host github.com:443 ssl:default [Try again]
```

**Comment by ludeeus** [comment]
Look at your other integrations, you have a network issue.
Not a HACS issue.
