### ISSUE TITLE
Missing Getting Started Menu

### ISSUE THREAD

**Issue by dlindnegm** [hacs/integration#3240]
### Web browser

Chrome

### Web browser version

116.0.5845.141 (Official Build) (64-bit)

## System Information

version | core-2023.8.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4958
Installed Version | 1.32.1
Stage | running
Available Repositories | 1276
Downloaded Repositories | 21
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 116.7 GB
disk_used | 15.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Duck DNS (1.15.0), NGINX Home Assistant SSL proxy (3.5.0), Samba share (10.0.2), Advanced SSH & Web Terminal (15.0.7), Node-RED (14.4.5), Home Assistant Google Drive Backup (0.111.1), Network UPS Tools (0.12.0), Z-Wave JS UI (1.15.8), MariaDB (2.6.1), Mosquitto broker (6.3.0), ESPHome (2023.8.2), Samba Backup (5.2.0), AWNET to HASS (1.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 8
views | 18
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 27, 2023 at 4:29 AM
-- | --
current_recorder_run | September 2, 2023 at 9:09 AM
estimated_db_size | 671.50 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Not sure at what point it happened, or if it's an issue at all, but I no longer have the normal "Getting Started" menu under the HACS integration that shows the Integrations, Automation, Add-Ons and About menu.  

I've recently been testing multiple beta versions of an integration available via HACS https://github.com/jeroenterheerdt/HAsmartirrigation which involves multiple uninstall/restart/reinstall/restart actions for that integration.  At some point When I tried to install different versions of that integration it would no longer show any of the production or beta versions available for download.   I've completely uninstalled, restarted, and deleted the HACS folder under custom_components multiple times, but HACS still does not show the normal menu.  I'm not sure if this is an issue with HACS at all, or related to the issue with not seeing the beta versions for Smart Irrigation.  I've also restored HA entirely from a backup but the HACS menu still doesn't show the Getting Started Menu.  

This also happens in the Edge browser, so it doesn't appear to be a Chrome issue.

### Reproduction steps

1.  Completely uninstall HACS per the documentation
2. Reinstall HACS per the documentation
3. Getting Started HACS menu does not appear
...

### Screenshots

![image](https://github.com/hacs/integration/assets/24968305/c9086a64-38d1-4fa7-a84b-740875add4a3)

### Javascript logs from your browser console

```text
Not sure how to access or save this log info...
:8123/webrtc/webrtc-camera.js?v3.0.0:1     Failed to load resource: the server responded with a status of 404 (Not Found)
load_resource.ts:13 Uncaught (in promise) http://192.168.0.115:8123/webrtc/webrtc-camera.js?v3.0.0
auto-entities.js?hacstag=1677445841121:172 AUTO-ENTITIES 1.12.1 IS INSTALLED
card-mod.js?hacstag=190927524322:5 CARD-MOD 3.2.2 IS INSTALLED
card-mod.js?hacstag=190927524322:5 You may not be getting optimal performance out of card-mod.
See https://github.com/thomasloven/lovelace-card-mod#performance-improvements
mini-graph-card-bundle.js?hacstag=1512800620110:1  MINI-GRAPH-CARD  0.11.0 
weather-radar-card.js?hacstag=487680971210:1291   WEATHER-RADAR-CARD   Version 2.1.0    
ha-teamtracker-card.js?hacstag=526408682080:9  TEAMTRACKER-CARD v0.9.0 IS INSTALLED
5A soft navigation has been detected: <URL>
```

### Diagnostics dump

[config_entry-hacs-c9472f51901c84b4592625cc714139fb.json.txt](https://github.com/hacs/integration/files/12504122/config_entry-hacs-c9472f51901c84b4592625cc714139fb.json.txt)

**Comment by ludeeus** [comment]
You have enabled experimental features, the UI you see now is the new one which is used there.
