### ISSUE TITLE
No option 'Show beta versions' when downloading an extension

### ISSUE THREAD

**Issue by gatonero** [hacs/integration#3241]
### Describe the issue

I wanted to install a beta version for the extension 'Smart Irrigationon a brand new HA and HACS instance with nothing else installed beside Terminal and HACS.

[HAsmartirrigation](https://github.com/jeroenterheerdt/HAsmartirrigation)

I didn't get the option 'Show beta versions'. Until yesterday I got the option.

![Smart_Irrigation](https://github.com/hacs/integration/assets/8248255/1f25e5e2-cd87-431d-b4da-603e8803dcc4)

For 'Better Thermostat' I'm getting this option.

![Better_Thermostat](https://github.com/hacs/integration/assets/8248255/ad321b4c-2078-417b-9fcd-824e814bf73d)

### Link to action run

http://192.168.178.28:8123/hacs/repository/263179176

### Link to action configuration

http://192.168.178.28:8123/hacs/repository/263179176

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
This has nothing to do with the action.
Open an issue with the backend template.
