### ISSUE TITLE
No option 'Show beta versions' when downloading an extension

### ISSUE THREAD

**Issue by gatonero** [hacs/integration#3242]
## System Information

version | core-2023.8.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.45
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4991
Installed Version | 1.32.1
Stage | running
Available Repositories | 1272
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 43.6 GB
disk_used | 30.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Samba share (10.0.2), Samba Backup (5.2.0), Mosquitto broker (6.3.0), ESPHome (2023.8.2), NGINX Home Assistant SSL proxy (3.5.0), InfluxDB (4.7.0), Grafana (9.0.3), Log Viewer (0.15.1), Advanced SSH & Web Terminal (15.0.7), WireGuard (0.8.1), Filebrowser (2.24.2), Glances (0.19.2), MQTT Explorer (browser-1.0.1), motionEye (0.19.1), MariaDB (2.6.1), Studio Code Server (5.10.1), Piper (1.3.2), Whisper (1.0.0), phpMyAdmin (0.8.7), Simple Scheduler (2.11), Zigbee2MQTT (1.33.0-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 5
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 27, 2023 at 13:11
-- | --
current_recorder_run | September 2, 2023 at 19:30
estimated_db_size | 800.52 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I wanted to install a beta version for the extension 'Smart Irrigationon a brand new HA and HACS instance with nothing else installed beside Terminal and HACS.

[HAsmartirrigation](https://github.com/jeroenterheerdt/HAsmartirrigation)

I didn't get the option 'Show beta versions'. Until yesterday I got the option.

![Smart_Irrigation](https://github.com/hacs/integration/assets/8248255/1f25e5e2-cd87-431d-b4da-603e8803dcc4)

For 'Better Thermostat' I'm getting this option.

![Better_Thermostat](https://github.com/hacs/integration/assets/8248255/ad321b4c-2078-417b-9fcd-824e814bf73d)

### Reproduction steps

1.Try to install a beta version of [HAsmartirrigation](https://github.com/jeroenterheerdt/HAsmartirrigation)

### Debug logs

```text
enabled but none
```

**Comment by gatonero** [comment]
With the new release of Smart Irrigation 0.0.82 this is resolved but I don't know why?

**Comment by ludeeus** [comment]
There was too many beta versions, so a regular version was not found, so it falled back to commit only.
You can increase the number in HACS options.

https://hacs.xyz/docs/configuration/options

**Comment by gatonero** [comment]
@ludeeus Thanks a lot! :-)
