### ISSUE TITLE
Support adding custom repositories in gitea

### ISSUE THREAD

**Issue by ymj0424** [hacs/integration#3246]
## System Information

version | core-2023.7.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 4.18.16-1.el7.elrepo.x86_64
arch | x86_64
timezone | Asia/Shanghai
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4936
Installed Version | 1.32.1
Stage | running
Available Repositories | 1279
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | pending
can_reach_cloud | pending

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 2023年8月27日 10:53
-- | --
current_recorder_run | 2023年9月5日 13:17
estimated_db_size | 37.51 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Xiaomi Gateway 3</summary>

version | 3.3.2 (4efeaee)
-- | --

</details>

<details><summary>Xiaomi MIoT</summary>

logged_in | true
-- | --
can_reach_micloud_server | ok
accounts_count | 1
account_devices_count | 14
added_devices | 1

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Currently HACS only supports adding custom repositories in GitHub, is it planned to support adding custom repositories in other platform such as self-hosted gitea?

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
N/A
```

**Comment by ludeeus** [comment]
No, only the public facing GitHub will be supported.
