### ISSUE TITLE
Clarify "No repositories found matching your filter" message when all results may already be installed

### ISSUE THREAD

**Issue by reedy** [hacs/integration#3248]
### Web browser

Firefox

### Web browser version

117.0

## System Information

version | core-2023.9.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4970
Installed Version | 1.32.1
Stage | running
Available Repositories | 1279
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.3
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 28.3 GB
disk_used | 8.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), Modbus TCP to Modbus RTU Gateway Add-on (2021.10.1), Mosquitto broker (6.3.1), File editor (5.6.0), TasmoAdmin (0.25.0), Sunsynk/Deye Inverter Add-on (multi) (0.5.9), Syncthing (1.16.3), Filebrowser (2.24.2), Home Assistant Git Exporter (1.16.0), Portainer (2.18.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 4
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 29 August 2023 at 22:23
-- | --
current_recorder_run | 7 September 2023 at 15:09
estimated_db_size | 402.30 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The message "No repositories found matching your filter" can be a little misleading in some cases.

If you add the only repository that matches your results, and then search for the same term again, the message "No repositories found matching your filter" is incorrect. There are repositories, but you already have them installed, so they're being filtered out.

I'm not sure if it makes sense to show results that are already installed (though, you could, and annotate them as such), but the message suggests there are no repositories at all that match (which could be correct for many search terms, if indeed there were no results, or the filters exclude them), not that there are no repositories that match that can be currently installed, because they are already installed.

### Reproduction steps

1. Click "Export & Download Repositories"
2. Search for vehicle
3. Add the "Charger Card" repository
4. Click "Export & Download Repositories" again
5. Search for vehicle again

### Screenshots

![Screenshot 2023-09-08 at 12 54 47](https://github.com/hacs/integration/assets/67615/83ef1765-5230-4b1f-a688-b0d11b952ea6)

![Screenshot 2023-09-08 at 12 55 25](https://github.com/hacs/integration/assets/67615/5bbe6d3b-e375-443e-b41d-3f3bea61f7fb)

### Javascript logs from your browser console

```text
n/a
```

**Comment by ludeeus** [comment]
This has been corrected in the new UI you can get by enabling experimental features.

**Comment by reedy** [comment]
> This has been corrected in the new UI you can get by enabling experimental features.

Thanks!

I'm presuming this will become "stable"/not experimental at some point in the future?

For reference for others (if they come across this)... Docs on how to enable experimental features are at https://hacs.xyz/docs/configuration/options/

See also: https://experimental.hacs.xyz/

**Comment by ludeeus** [comment]
Eventually
