### ISSUE TITLE
UI element overlap when searching for frontend repositories

### ISSUE THREAD

**Issue by reedy** [hacs/integration#3249]
### Web browser

Firefox

### Web browser version

117.0

## System Information

version | core-2023.9.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4940
Installed Version | 1.32.1
Stage | running
Available Repositories | 1279
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.3
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 28.3 GB
disk_used | 8.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), Modbus TCP to Modbus RTU Gateway Add-on (2021.10.1), Mosquitto broker (6.3.1), File editor (5.6.0), TasmoAdmin (0.25.0), Sunsynk/Deye Inverter Add-on (multi) (0.5.9), Syncthing (1.16.3), Filebrowser (2.24.2), Home Assistant Git Exporter (1.16.0), Portainer (2.18.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 4
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 29 August 2023 at 22:23
-- | --
current_recorder_run | 7 September 2023 at 15:09
estimated_db_size | 402.30 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Noticed when filing #3248.

If you search for "vehicle" (or "veh") when looking for frontend repos, the size of the box changes. If there is a long (ish) text for the description, it is possible that the "Theme" or "Lovelace" labels on the right hand side of the results overlap with the description text

### Reproduction steps

1. Click "Explore & Download Repositories" on the Frontend tab of HACS
2. Search for "vehicle" (or "veh")

### Screenshots

![Screenshot 2023-09-08 at 12 54 47](https://github.com/hacs/integration/assets/67615/363275b2-7a98-4b38-b7f3-fcb443f130fc)

![Screenshot 2023-09-08 at 13 04 50](https://github.com/hacs/integration/assets/67615/98c00227-3670-409b-8fdd-73ed393a0075)

### Javascript logs from your browser console

```text
n/a
```

**Comment by ludeeus** [comment]
This has been corrected in the new UI you can get by enabling experimental features.
