### ISSUE TITLE
Save scroll state/position on search page

### ISSUE THREAD

**Issue by reedy** [hacs/integration#3251]
### Web browser

Firefox

### Web browser version

117.0

## System Information

version | core-2023.9.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4865
Installed Version | 1.32.1
Stage | running
Available Repositories | 1282
Downloaded Repositories | 16
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.3
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 28.3 GB
disk_used | 8.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), Modbus TCP to Modbus RTU Gateway Add-on (2021.10.1), Mosquitto broker (6.3.1), File editor (5.6.0), TasmoAdmin (0.25.0), Sunsynk/Deye Inverter Add-on (multi) (0.5.9), Syncthing (1.16.3), Filebrowser (2.24.2), Home Assistant Git Exporter (1.16.0), Portainer (2.18.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 7
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 29 August 2023 at 22:23
-- | --
current_recorder_run | 8 September 2023 at 13:30
estimated_db_size | 402.30 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

This is related to the experimental UI.

Especially relevant with a large list of results. If you scroll down the long list of repositories, click on one to learn more about it, decide not to install it, and click the back arrow, you're taken back to the top of the list, losing your scroll position. You then have to remember where you were, and scroll back to that spot again.

This the case if you download the repo, but don't refresh the page; because you're going to download more before doing any restarting etc.

This works fine on similar list UIs such as the Devices list from HA itself.

Not sure if this should be expected to keep the scroll position if you did hard refresh the page; and doesn't on the Device list either. So I guess this case we don't need to worry about either

### Reproduction steps

1. Go to the HACS page in HA
2. Turn off the Downloaded filter
3. Scroll down the list of results (do at least a couple of screens/pages)
4. Click on one result in the list
5. Click the back arrow at the top left
6. Be scrolled back to the top of the repository list

### Screenshots

https://github.com/hacs/integration/assets/67615/f504ba64-ff62-441a-b64b-b7cdee1a9909

### Javascript logs from your browser console

```text
n/a
```

**Comment by ludeeus** [comment]
This is the same list component (inpoeted from HA) as supervisor backups? Does it work there?

**Comment by reedy** [comment]
I don't have that many backups... But clicking on a backup doesn't change the navigation, just pops up another sub window.

It works on `config/devices/dashboard`


https://github.com/hacs/integration/assets/67615/01011ef2-6fe9-4d89-8993-dd11c850af5c

There is this in the browser console logs, but it's on the Devices page too

>This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features!

Nothing else appears while scrolling the HACS list, nor when I click into an item in the list and back again

**Comment by ludeeus** [comment]
Ah yes.. i remembered wrong.
My suspicion is that this component does not work properly in iframes (like HACS and Supervisor panels)

I forgot also that i have actually added a workaround for it in HACS <https://github.com/hacs/frontend/pull/674>

**Comment by reedy** [comment]
Sorry, it's a little unclear on the state of this issue...

The workaround was committed a few months ago (to main); should this be on the experimental version?

**Comment by ludeeus** [comment]
No, it has not been included in a release.

**Comment by reedy** [comment]
Aha, ok, perfect.

Any idea when the next (experimental) release is due?

**Comment by ludeeus** [comment]
Hopefully in 1.5 weeks, but it depends on time available

**Comment by reedy** [comment]
Completely understand. I'll keep an eye out, just wanted to make sure I wasn't missing anything obvious.

Thanks!
