### ISSUE TITLE
Menu's missing

### ISSUE THREAD

**Issue by gmum4d** [hacs/integration#3258]
### Web browser

Safari and Homeassintant.app on MacOS

### Web browser version

17.0

## System Information

version | core-2023.9.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1353
Downloaded Repositories | 17
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 26 September 2023 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-11.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.09.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 113.7 GB
disk_used | 7.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), NGINX Home Assistant SSL proxy (3.5.0), Studio Code Server (5.10.2), Samba share (10.0.2), Terminal & SSH (9.7.1), eufy-security-ws (1.6.4), RTSP Simple Server Add-on (v0.17.6), Matter Server (4.9.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 8
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 8 September 2023 at 12:45
-- | --
current_recorder_run | 13 September 2023 at 22:25
estimated_db_size | 130.48 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When clicking on HACS is the side menu I no Longer see the menu for Integrations, Frontend, Automation, Add-ons & About.  I just see a list in already installed Repositorys.

I understand that this may be a bug in my setup only rather than a but for every install, But I'm new to HA and HACS and don't know where else I can get help from.

### Reproduction steps

1. Click the HACS icon in the side menu

### Screenshots

<img width="1448" alt="Screenshot 2023-09-14 at 08 40 42" src="https://github.com/hacs/integration/assets/16610988/0b5add36-c67d-4dbe-8c4a-50f1010ef0ef">

### Javascript logs from your browser console

```text
ResizeObserver loop completed with undelivered notifications.
```

### Diagnostics dump

[config_entry-hacs-917066685b204bccda102594ee1195ab.json.txt](https://github.com/hacs/integration/files/12606193/config_entry-hacs-917066685b204bccda102594ee1195ab.json.txt)

**Comment by ludeeus** [comment]
This is not a bug.
This is the new UI you get when you enable experimental features.

**Comment by gmum4d** [comment]
Thank you very much.  Apologies, I’m new to HA and HACS so I didn’t realise.
