### ISSUE TITLE
Request for removal of moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card

### ISSUE THREAD

**Issue by trentjw** [hacs/integration#3264]
### Repository

moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Will not cleanly Uninstall when trying to remove from home assistant even with no files no log files either still tries to update 

### Link to issue

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/847

**Comment by ludeeus** [comment]
Issue is 7h old.

**Comment by trentjw** [comment]
The original issue that prompted removing this integration was never resolved https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/809
