### ISSUE TITLE
Enable Indonesian in Lokalise

### ISSUE THREAD

**Issue by lunmay** [hacs/integration#3266]
## System Information

version | core-2023.9.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4867
Installed Version | 1.32.1
Stage | running
Available Repositories | 1289
Downloaded Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 1 Maret 2024 pukul 01.00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-4.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.09.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 146.0 GB
disk_used | 22.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Samba share (10.0.2), Remote Backup (2023.3.0), Advanced SSH & Web Terminal (15.0.8), Z-Wave JS UI (1.16.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 6
views | 18
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 12 September 2023 pukul 03.59
-- | --
current_recorder_run | 22 September 2023 pukul 14.38
estimated_db_size | 438.93 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Please enable Indonesian in Lokalise

### Reproduction steps

1. Open https://app.lokalise.com/public/854515055f679055040b37.42677693/
2. Indonesian is not available for translation

### Debug logs

```text
-
```

**Comment by ludeeus** [comment]
Added https://app.lokalise.com/project/854515055f679055040b37.42677693/?view=single&reference_lang_id=640&single_lang_id=757
