### ISSUE TITLE
HACS upgrade clears the admin for automations

### ISSUE THREAD

**Issue by erkr** [hacs/integration#3273]
## System Information

version | core-2023.9.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1304
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.09.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 219.4 GB
disk_used | 61.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Mosquitto broker (6.3.1), MariaDB (2.6.1), Network UPS Tools (0.12.1), Home Assistant Google Drive Backup (0.111.1), InfluxDB (4.7.0), FTP (4.7.2), phpMyAdmin (0.8.8), Advanced SSH & Web Terminal (15.0.8), VLC (0.2.0), Filebrowser (2.25.0), Music Assistant BETA (2.0.0b73)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 18
views | 19
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 22, 2023 at 22:53
-- | --
current_recorder_run | September 25, 2023 at 17:14
estimated_db_size | 371.20 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Once is in a while, when there is HACS upgrade, the administration of installed automation is lost (while integrations and frontend are preserved).
I have only the Hass_entities script installed, but after the upgrade, all automation repositories are presented as ‘new’ including hass_entities (the script folder for hass entities is still there and working. It’s only the HACS administration that is cleared).
After I dismissed all automations and re-downloaded hass entities, the administration is correct again, till the next update.

### Reproduction steps

Upgrade HACs

### Debug logs

```text
Enabling debug login after it happened doesn’t contain anything suspicious.
```

### Diagnostics dump

Can’t download that on my iPhone. If required I will provide it later

**Comment by ludeeus** [comment]
This has nothing to do with automations or HACS updates.

what you are describing can happen if during restarts the `python_scripts` integration fails.

at which point HACS does not know that you want/need that.

**Comment by erkr** [comment]
Hi @ludeeus maybe I misunderstand but if Python_script fails during startup it gets disabled (so would not function till I restart whiteout a failure). But python script is still there and works.
Best Eric

**Comment by ludeeus** [comment]
Yeah, but you would not notice it in HACS until after it has happened, it does not have to be the same start.
