### ISSUE TITLE
Unable to build/compile latest Frontend

### ISSUE THREAD

**Issue by emandtf** [hacs/integration#3276]
### Web browser

Firefox

### Web browser version

117

### System Health details

/*nothing*/

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I'm unable to build due to this error:
`Error: /home/NodeJS/hacs-frontend/src/localize/languages/translationMetadata.json: ENOENT: no such file or directory, open '/home/NodeJS/hacs-frontend/src/localize/languages/translationMetadata.json'
    at readFileSyncUtf8 (node:internal/fs/read/utf8:20:3)
    at Object.readFileSync (node:fs:466:12)
    at Object.readFileSync (/home/NodeJS/hacs-frontend/node_modules/jsonfile/index.js:50:22)
    at file:///home/NodeJS/hacs-frontend/script/gulp/translations.js:12:32
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
    at async Promise.all (index 1)
    at async file:///home/NodeJS/hacs-frontend/gulpfile.js:11:1 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/NodeJS/hacs-frontend/src/localize/languages/translationMetadata.json'
}`

In fact "src/localize/languages/translationMetadata.json" file is not present in the source.....

### Reproduction steps

1. git clone...
2. npm install
3. ./script/build

### Screenshots

/*nothing*/

### Javascript logs from your browser console

```text
/*nothing*/
```

**Comment by ludeeus** [comment]
Do not use `npm install`, run `make init` instead.

**Comment by emandtf** [comment]
> `npm install`, run `make init`

I started again from scratch but after "make init" same "" file still not present.

Below the "make init" log:
`make init
git submodule update --init;
yarn;
➤ YN0000: ┌ Resolution step
➤ YN0002: │ hacs-frontend@workspace:. doesn't provide @octokit/core (pe31f1), requested by @octokit/plugin-retry
➤ YN0002: │ hacs-frontend@workspace:. doesn't provide component-emitter (p4ddc9), requested by vis-network
➤ YN0002: │ hacs-frontend@workspace:. doesn't provide keycharm (p36b7c), requested by vis-network
➤ YN0002: │ hacs-frontend@workspace:. doesn't provide timsort (p641dc), requested by vis-network
➤ YN0002: │ hacs-frontend@workspace:. doesn't provide uuid (p990f7), requested by vis-data
➤ YN0002: │ hacs-frontend@workspace:. doesn't provide uuid (p317f3), requested by vis-network
➤ YN0002: │ hacs-frontend@workspace:. doesn't provide vis-util (pab9e3), requested by vis-data
➤ YN0002: │ hacs-frontend@workspace:. doesn't provide vis-util (p1ed95), requested by vis-network
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 679ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs@npm:16.2.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:17.7.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:7.1.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ ylru@npm:1.3.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 9s 521ms
➤ YN0000: ┌ Link step
➤ YN0007: │ core-js@npm:3.31.0 must be built because it never has been before or the last one failed
➤ YN0007: │ tsparticles-engine@npm:2.10.1 must be built because it never has been before or the last one failed
➤ YN0007: │ vis-data@npm:7.1.6 [ce82f] must be built because it never has been before or the last one failed
➤ YN0007: │ @vaadin/vaadin-usage-statistics@npm:2.1.2 must be built because it never has been before or the last one failed
➤ YN0007: │ normalize-diacritics@npm:2.14.0 must be built because it never has been before or the last one failed
➤ YN0007: │ @reallyland/esm@npm:0.0.1 must be built because it never has been before or the last one failed
➤ YN0007: │ es5-ext@npm:0.10.62 must be built because it never has been before or the last one failed
➤ YN0007: │ vis-network@npm:9.1.6 [ce82f] must be built because it never has been before or the last one failed
➤ YN0007: │ lit-ntml@npm:2.20.0 must be built because it never has been before or the last one failed
➤ YN0007: │ nodemod@npm:2.8.4 must be built because it never has been before or the last one failed
➤ YN0007: │ app-datepicker@npm:5.1.1 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 2m 36s
➤ YN0000: Done with warnings in 2m 47s`

Then running "_./script/build_" gives me same error as before due to same file missing.

**Comment by ludeeus** [comment]
oh yeah.. you need `script/bootstrap` as well.

**Comment by emandtf** [comment]
> oh yeah.. you need `script/bootstrap` as well.

Thx for your help, the file not is well created.

I think that two lines of instructions in README.md would help since each NodeJS project seems requires a different initialization ;)
Morover this project has package.json and Yarn.lock together with MakeFile...so it's a bit confusing how to start, especially the need to execute something else before "build".

**Comment by ludeeus** [comment]
Most of it will just work when you use the included devcontainer.
The fact is that for the 4-5 years this has existed (with a very few exceptions (like maybe once every 2 years)) I have been the only one wanting to do this, so docs for it has not been much needed.

**Comment by emandtf** [comment]
Thx again for your fast support.
