### ISSUE TITLE
Request for removal of cerebrate/home-assistant-sun-card

### ISSUE THREAD

**Issue by bluenazgul** [hacs/integration#3278]
### Repository

cerebrate/home-assistant-sun-card

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Repo dont longer exist

### Link to issue

N/A

**Comment by ludeeus** [comment]
It's not a part of the HACS default repositories.
