### ISSUE TITLE
Different UI - Missing Integrations, Front End - Error while loading page repository.

### ISSUE THREAD

**Issue by chessmaster82** [hacs/integration#3281]
### Web browser

Chrome

### Web browser version

117.0.5938.132 (Official Build) (64-bit)

## System Information

version | core-2023.9.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4938
Installed Version | 1.33.0
Stage | running
Available Repositories | 1297
Downloaded Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.09.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 439.4 GB
disk_used | 6.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (14.5.0), Advanced SSH & Web Terminal (15.0.8), File editor (5.6.0), Mosquitto broker (6.3.1), Sunsynk/Deye Inverter Add-on (multi) (0.6.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 30 September 2023 at 19:29
-- | --
current_recorder_run | 30 September 2023 at 22:45
estimated_db_size | 0.90 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

New install on Pi4 with home assist running HACS **doesnt** load with the normal view showing integrations, frontend, add ons and about

When clicking on the repository HACS, I get this error message "Error while loading page repository."

See screenshots:

### Reproduction steps

1. Make SSD USB bootable
2. Install Home Assist using Raspberry Pi image loader
3. 
4.Install HAC as new integration
5. Link to Github account
...

### Screenshots

![image](https://github.com/hacs/integration/assets/146565076/f30691c0-805c-4b37-90cb-50dffad49386)
![image](https://github.com/hacs/integration/assets/146565076/c9ddfce0-4770-4bec-b342-1c9351b2c53b)

### Javascript logs from your browser console

```text
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.9.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.09.2",
    "host_os": "Home Assistant OS 10.5",
    "docker_version": "23.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "hacs",
    "name": "HACS",
    "codeowners": [
      "@ludeeus"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "websocket_api",
      "frontend",
      "persistent_notification",
      "lovelace",
      "repairs"
    ],
    "documentation": "https://hacs.xyz/docs/configuration/start",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/hacs/integration/issues",
    "requirements": [
      "aiogithubapi>=22.10.1"
    ],
    "version": "1.33.0",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "bff25eecb434ca1852b1d801f004b6e2",
      "version": 1,
      "domain": "hacs",
      "title": "",
      "data": {
        "token": "**REDACTED**"
      },
      "options": {
        "sidepanel_title": "HACS",
        "sidepanel_icon": "hacs:hacs",
        "release_limit": 5,
        "country": "ALL",
        "appdaemon": false,
        "netdaemon": false,
        "debug": false,
        "experimental": false
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "hacs": {
      "stage": "running",
      "version": "1.33.0",
      "disabled_reason": null,
      "new": false,
      "startup": false,
      "categories": [
        "integration",
        "plugin",
        "theme"
      ],
      "renamed_repositories": {},
      "archived_repositories": [],
      "ignored_repositories": [],
      "lovelace_mode": "auto-gen",
      "configuration": {
        "appdaemon": false,
        "country": "ALL",
        "debug": false,
        "dev": false,
        "experimental": false,
        "netdaemon": false,
        "python_script": false,
        "release_limit": 5,
        "theme": false
      }
    },
    "custom_repositories": [],
    "repositories": [
      {
        "data": {
          "archived": false,
          "authors": [
            "@ludeeus"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "main",
          "description": "HACS gives you a powerful UI to handle downloads of all your custom needs.",
          "domain": "hacs",
          "downloads": 41075,
          "etag_repository": "W/\"9bd43b441c260722c8bc4ad423ebef0ed1033de336c4c1d864246399abb01f14\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "hacs/integration",
          "hide": false,
          "has_issues": true,
          "id": "172733314",
          "installed_commit": null,
          "installed_version": "1.33.0",
          "installed": true,
          "last_commit": "50d9a19",
          "last_updated": "2023-09-29T14:35:59Z",
          "last_version": "1.33.0",
          "manifest_name": "HACS",
          "new": false,
          "open_issues": 12,
          "published_tags": [
            "1.33.0",
            "1.32.1",
            "1.32.0",
            "1.31.0",
            "1.30.1"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 3925,
          "topics": [
            "community",
            "package-manager"
          ]
        },
        "integration_manifest": {
          "domain": "hacs",
          "name": "HACS",
          "codeowners": [
            "@ludeeus"
          ],
          "config_flow": true,
          "dependencies": [
            "http",
            "websocket_api",
            "frontend",
            "persistent_notification",
            "lovelace",
            "repairs"
          ],
          "documentation": "https://hacs.xyz/docs/configuration/start",
          "iot_class": "cloud_polling",
          "issue_tracker": "https://github.com/hacs/integration/issues",
          "requirements": [
            "aiogithubapi>=22.10.1"
          ],
          "version": "0.0.0"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "hacs.zip",
          "hacs": "0.19.0",
          "hide_default_branch": true,
          "homeassistant": "2023.6.0",
          "manifest": {
            "name": "HACS",
            "zip_release": true,
            "hide_default_branch": true,
            "homeassistant": "2023.6.0",
            "hacs": "0.19.0",
            "filename": "hacs.zip"
          },
          "name": "HACS",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": "1.33.0",
        "paths": {
          "localpath": "/config/custom_components/hacs",
          "local": "/config/custom_components/hacs",
          "remote": "custom_components/hacs"
        }
      }
    ],
    "rate_limit": {
      "resources": {
        "core": {
          "limit": 5000,
          "used": 63,
          "remaining": 4937,
          "reset": 1696113922
        },
        "search": {
          "limit": 30,
          "used": 0,
          "remaining": 30,
          "reset": 1696113756
        },
        "graphql": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1696117296
        },
        "integration_manifest": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1696117296
        },
        "source_import": {
          "limit": 100,
          "used": 0,
          "remaining": 100,
          "reset": 1696113756
        },
        "code_scanning_upload": {
          "limit": 1000,
          "used": 0,
          "remaining": 1000,
          "reset": 1696117296
        },
        "actions_runner_registration": {
          "limit": 10000,
          "used": 0,
          "remaining": 10000,
          "reset": 1696117296
        },
        "scim": {
          "limit": 15000,
          "used": 0,
          "remaining": 15000,
          "reset": 1696117296
        }
      },
      "rate": {
        "limit": 5000,
        "used": 63,
        "remaining": 4937,
        "reset": 1696113922
      }
    }
  }
}
```

### Diagnostics dump

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.9.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.09.2",
    "host_os": "Home Assistant OS 10.5",
    "docker_version": "23.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "hacs",
    "name": "HACS",
    "codeowners": [
      "@ludeeus"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "websocket_api",
      "frontend",
      "persistent_notification",
      "lovelace",
      "repairs"
    ],
    "documentation": "https://hacs.xyz/docs/configuration/start",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/hacs/integration/issues",
    "requirements": [
      "aiogithubapi>=22.10.1"
    ],
    "version": "1.33.0",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "bff25eecb434ca1852b1d801f004b6e2",
      "version": 1,
      "domain": "hacs",
      "title": "",
      "data": {
        "token": "**REDACTED**"
      },
      "options": {
        "sidepanel_title": "HACS",
        "sidepanel_icon": "hacs:hacs",
        "release_limit": 5,
        "country": "ALL",
        "appdaemon": false,
        "netdaemon": false,
        "debug": false,
        "experimental": false
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "hacs": {
      "stage": "running",
      "version": "1.33.0",
      "disabled_reason": null,
      "new": false,
      "startup": false,
      "categories": [
        "integration",
        "plugin",
        "theme"
      ],
      "renamed_repositories": {},
      "archived_repositories": [],
      "ignored_repositories": [],
      "lovelace_mode": "auto-gen",
      "configuration": {
        "appdaemon": false,
        "country": "ALL",
        "debug": false,
        "dev": false,
        "experimental": false,
        "netdaemon": false,
        "python_script": false,
        "release_limit": 5,
        "theme": false
      }
    },
    "custom_repositories": [],
    "repositories": [
      {
        "data": {
          "archived": false,
          "authors": [
            "@ludeeus"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "main",
          "description": "HACS gives you a powerful UI to handle downloads of all your custom needs.",
          "domain": "hacs",
          "downloads": 41075,
          "etag_repository": "W/\"9bd43b441c260722c8bc4ad423ebef0ed1033de336c4c1d864246399abb01f14\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "hacs/integration",
          "hide": false,
          "has_issues": true,
          "id": "172733314",
          "installed_commit": null,
          "installed_version": "1.33.0",
          "installed": true,
          "last_commit": "50d9a19",
          "last_updated": "2023-09-29T14:35:59Z",
          "last_version": "1.33.0",
          "manifest_name": "HACS",
          "new": false,
          "open_issues": 12,
          "published_tags": [
            "1.33.0",
            "1.32.1",
            "1.32.0",
            "1.31.0",
            "1.30.1"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 3925,
          "topics": [
            "community",
            "package-manager"
          ]
        },
        "integration_manifest": {
          "domain": "hacs",
          "name": "HACS",
          "codeowners": [
            "@ludeeus"
          ],
          "config_flow": true,
          "dependencies": [
            "http",
            "websocket_api",
            "frontend",
            "persistent_notification",
            "lovelace",
            "repairs"
          ],
          "documentation": "https://hacs.xyz/docs/configuration/start",
          "iot_class": "cloud_polling",
          "issue_tracker": "https://github.com/hacs/integration/issues",
          "requirements": [
            "aiogithubapi>=22.10.1"
          ],
          "version": "0.0.0"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "hacs.zip",
          "hacs": "0.19.0",
          "hide_default_branch": true,
          "homeassistant": "2023.6.0",
          "manifest": {
            "name": "HACS",
            "zip_release": true,
            "hide_default_branch": true,
            "homeassistant": "2023.6.0",
            "hacs": "0.19.0",
            "filename": "hacs.zip"
          },
          "name": "HACS",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": "1.33.0",
        "paths": {
          "localpath": "/config/custom_components/hacs",
          "local": "/config/custom_components/hacs",
          "remote": "custom_components/hacs"
        }
      }
    ],
    "rate_limit": {
      "resources": {
        "core": {
          "limit": 5000,
          "used": 63,
          "remaining": 4937,
          "reset": 1696113922
        },
        "search": {
          "limit": 30,
          "used": 0,
          "remaining": 30,
          "reset": 1696113756
        },
        "graphql": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1696117296
        },
        "integration_manifest": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1696117296
        },
        "source_import": {
          "limit": 100,
          "used": 0,
          "remaining": 100,
          "reset": 1696113756
        },
        "code_scanning_upload": {
          "limit": 1000,
          "used": 0,
          "remaining": 1000,
          "reset": 1696117296
        },
        "actions_runner_registration": {
          "limit": 10000,
          "used": 0,
          "remaining": 10000,
          "reset": 1696117296
        },
        "scim": {
          "limit": 15000,
          "used": 0,
          "remaining": 15000,
          "reset": 1696117296
        }
      },
      "rate": {
        "limit": 5000,
        "used": 63,
        "remaining": 4937,
        "reset": 1696113922
      }
    }
  }
}

**Comment by ludeeus** [comment]
That’s the new UI.

**Comment by chessmaster82** [comment]
Perhaps, although it doesnt appear to be working correctly? 
![image](https://github.com/hacs/integration/assets/146565076/92d06406-35e1-4d60-b9a1-5189ac89829e)
![image](https://github.com/hacs/integration/assets/146565076/7a06ffc7-e89a-45cb-8619-f550787f5f61)
