### ISSUE TITLE
Unabel to see sections in HACS (ie Integration, Frontend and Add-ons)

### ISSUE THREAD

**Issue by rpg1886** [hacs/integration#3285]
### Web browser

Chrome

### Web browser version

Version 117.0.5938.132 (Official Build) (arm64)

## System Information

version | core-2023.9.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.45
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | failed to load: timeout
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.33.0
Stage | running
Available Repositories | 1305
Downloaded Repositories | 1
HACS Data | failed to load: timeout

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | failed to load: timeout
can_reach_cloud_auth | failed to load: timeout
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.09.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 30.8 GB
disk_used | 8.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | failed to load: timeout
installed_addons | Mosquitto broker (6.3.1), File editor (5.6.0), Zigbee2MQTT (1.33.0-1), Terminal & SSH (9.7.1), Frigate (Full Access) (0.12.1), Matter Server (4.9.0), Studio Code Server (5.11.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 2, 2023 at 11:21 AM
-- | --
current_recorder_run | October 4, 2023 at 11:11 PM
estimated_db_size | 0.39 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I have installed HASOS in a VM using Virtualbox in Windows 10 laptop

I have installed hacs using thise installation guide https://hacs.xyz/docs/setup/download 

After installation i cannot see the section "Integrations", "Frontend" and "Add-ons" all i can see is the documentation of HACS

### Reproduction steps

1.  Inastalled HACS using installation guide in 
2. Restarted HA, Refreshed and deleted cache of my browser
3. Clicked on HACS in my sidebar and unable to see sections (Integration, Frontend and Add-ons)
...

### Screenshots

![image](https://github.com/hacs/integration/assets/146563133/494d4185-2e34-4f6b-a705-137c7005eb23)

### Javascript logs from your browser console

```text
A form field element should have an id or name attribute
A form field element has neither an id nor a name attribute. This might prevent the browser from correctly autofilling the form.
To fix this issue, add a unique id or name attribute to a form field. This is not strictly needed, but still recommended even if you have an autocomplete attribute on the same element.

Incorrect use of <label for=FORM_ELEMENT>
The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.

No label associated with a form field
A <label> isn't associated with a form field.
To fix this issue, nest the <input> in the <label> or provide a for attribute on the <label> that matches a form field id.
To fix this issue, make sure the label's for attribute references the correct id of a form field.
```

### Diagnostics dump

[config_entry-hacs-900adb0b77b02e9244677b10da54fabf.json.txt](https://github.com/hacs/integration/files/12805366/config_entry-hacs-900adb0b77b02e9244677b10da54fabf.json.txt)

**Comment by schneider-de-com** [comment]
I have the same issue with a raspberry Pi 4 (Homeassistant OS).

**Comment by rpg1886** [comment]
@schneider-de-com there is actually no issue. it looks like UI has changed. Click the filter button at the upper right and you will see all of the sections.
