### ISSUE TITLE
Request for removal of RodBr/miflora-card

### ISSUE THREAD

**Issue by atus** [hacs/integration#3286]
### Repository

RodBr/miflora-card

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Not functional. 
Hasn't been updated in years. 
Issues warning owner has been open since May 2023 

### Link to issue

https://github.com/RodBr/miflora-card/issues/25

**Comment by ludeeus** [comment]
That issue is a result of using an unreleased configuration.
<https://github.com/RodBr/miflora-card/tree/0.1.0> is what's released and does not fail that way.
