### ISSUE TITLE
Could not authenticate with github while installing hacs

### ISSUE THREAD

**Issue by fritomnky** [hacs/integration#3288]
## System Information

version | core-2023.10.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.45
arch | x86_64
timezone | America/Winnipeg
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | failed to load: unreachable
can_reach_cloud_auth | failed to load: unreachable
can_reach_cloud | failed to load: unreachable

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.0
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 116.7 GB
disk_used | 5.9 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | failed to load: unreachable
installed_addons | Advanced SSH & Web Terminal (15.0.8)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 29, 2023 at 7:32 PM
-- | --
current_recorder_run | October 6, 2023 at 4:09 PM
estimated_db_size | 5.32 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Cannot get the program to add 

### Reproduction steps

1.add integration
2.click all boxes
3.get error message
...

### Debug logs

```text
None to get as I can't install it
```

**Comment by ludeeus** [comment]
Look at your other integrations, you clearly have network problems.
Try again when you have fixed that.

**Comment by fritomnky** [comment]
Yes I’m definitely having some network issues but nothing seems to be working to fix it. I’m not sure what I need to do to get it running and I’ve tried the Discord and nobody has helped yet

**Comment by fritomnky** [comment]
@ludeeus so my wiz integration works just fine, and can see my ipad and iphone stats. But I can't get HACS installed, I can't integrate tuya, and i cannot get the home assistant cloud to connect. I have IPV6 disabled on my router, and nothing else seems to be working....can you point me in any directions?
