### ISSUE TITLE
Request for removal of custom-cards/light-entity-row

### ISSUE THREAD

**Issue by 12213** [hacs/integration#3289]
### Repository

custom-cards/light-entity-row

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Not working.

### Link to issue

Not working

**Comment by tjorim** [comment]
Already done: https://github.com/hacs/default/commit/b479a8ea0329790f19dae4318ce9f79dc791346e
