### ISSUE TITLE
Request for removal of Makin-Things/platinum-weather-card

### ISSUE THREAD

**Issue by Scoop2389** [hacs/integration#3290]
### Repository

Makin-Things/platinum-weather-card

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

This card has not been touched by the author since December of 2022 (in this commit https://github.com/Makin-Things/platinum-weather-card/commit/4c3d6b8257fd930fed3d7e51afad66ad04cf254d). The repository also has a "Maintained: NO (as of 2022)" chip in its description. In that time many severe issues have been opened without any developer response such as https://github.com/Makin-Things/platinum-weather-card/issues/85, https://github.com/Makin-Things/platinum-weather-card/issues/86, https://github.com/Makin-Things/platinum-weather-card/issues/96, and https://github.com/Makin-Things/platinum-weather-card/issues/101.  This card is expected to completely stop working when old weather entities (without forecast attributes) are depreciated and removed. 

### Link to issue

 https://github.com/Makin-Things/platinum-weather-card/issues/101

**Comment by serge62300** [comment]
bonjour ?HACSne foctionne pas ,quand je clic dessus je tombe sur le logo ,une ligne ,comment puije faire?
il est bien noté a gauchei ,terminal aussi merci
