### ISSUE TITLE
Request for removal of moralmunky/Home-Assistant-Mail-And-Packages

### ISSUE THREAD

**Issue by trentjw** [hacs/integration#3291]
### Repository

moralmunky/Home-Assistant-Mail-And-Packages

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

does not uninstall cleanly even after uninstall updates for it persist Author chose to ignore multi request to fix this issue

### Link to issue

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/847

**Comment by ludeeus** [comment]
If it does not uninstall there is a bug.
That is not a reason to block it for everyone.

**Comment by trentjw** [comment]
Owner is blaming HACs for the bug yet none of my other integrations have found this so called bug in hacs he refuses to fix it maybe if it gets removed he may find the incentive to fix it
