### ISSUE TITLE
After HACS install, only see "read.me" info.  Do not see the "integrations"/"Front end" selections.

### ISSUE THREAD

**Issue by lschapker** [hacs/integration#3292]
### Describe the issue

Install HACS via link: https://hacs.xyz/docs/configuration/basic
When I click on the "HACS" in the left screen panel, I get:

![image](https://github.com/hacs/integration/assets/25398003/1fed67ce-1385-4a55-825e-d26fc487f9a0)

When I click the "HACS" row, I get:
![image](https://github.com/hacs/integration/assets/25398003/1c35fb1c-518a-45e6-bb30-b5fe4ab01d73)
(Not the 
![image](https://github.com/hacs/integration/assets/25398003/260f0782-78a2-4a1c-a699-64b3abae73dc)
I was expecting.
I have downloaded the "Debug config" here

[config_entry-hacs-74ce9b3d38b84a71d7247723825068dc.json.txt](https://github.com/hacs/integration/files/12842293/config_entry-hacs-74ce9b3d38b84a71d7247723825068dc.json.txt)

I'm sorry, but I'm a newbie to HACS.  I'm not sure what is expected for the "action to run" or "Action configuration"

### Link to action run

I don't know what is expected for this.

### Link to action configuration

I don't know what is expected for this.

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by lschapker** [comment]
I have removed the HACS integration multiple times.  Flushed my buffer cache also multiple times.  I presume that I'm missing something very simple as this type of error shouldn't be this difficult.

**Comment by ludeeus** [comment]
https://experimental.hacs.xyz/docs/basic/dashboard
