### ISSUE TITLE
HACS doesnt show integration catalog 

### ISSUE THREAD

**Issue by Leey0** [hacs/integration#3299]
### Web browser

Chrome

### Web browser version

Version 118.0.5993.71

## System Information

version | core-2023.10.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v7+
arch | armv7l
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.33.0
Stage | running
Available Repositories | 1310
Downloaded Repositories | 1
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 11, 2023 at 3:03 AM
-- | --
current_recorder_run | October 12, 2023 at 4:03 PM
estimated_db_size | 1.58 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I've tried to install HACS twice and it all looks successful but when i got to actually use the integration i just shows me the GitHub webpage body for HACS instead of the catalog. 

### Reproduction steps

1.Install Hacs
2.Click Hacs in side bar
3.See github page
...

### Screenshots

![Screenshot 2023-10-12 160855](https://github.com/hacs/integration/assets/41033143/69619d56-b93b-4d56-aab0-942b37cfa5e0)
![Screenshot 2023-10-12 1609482](https://github.com/hacs/integration/assets/41033143/bb20148d-e95f-4691-a64a-74e4f14130db)
![Screenshot 2023-10-12 161004](https://github.com/hacs/integration/assets/41033143/494f1c25-b3bb-4e04-9244-f44bdfa2f998)

### Javascript logs from your browser console

```text
:8123/config/integrations/integration/hacs:1 The file at 'http://192.168.0.126:8123/api/diagnostics/config_entry/00631ae993c05ed1ee7acb1109906797?authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIwZDUzNmM5NmRjNGI0NmI1YjIzOTJkYTFiNWYzZTk1ZSIsInBhdGgiOiIvYXBpL2RpYWdub3N0aWNzL2NvbmZpZ19lbnRyeS8wMDYzMWFlOTkzYzA1ZWQxZWU3YWNiMTEwOTkwNjc5NyIsInBhcmFtcyI6W10sImlhdCI6MTY5NzA4NzU3NCwiZXhwIjoxNjk3MDg3NjA0fQ.1ySGG9uM6akOvN3cGbVg04BsgIOL10J3kc8Oay8EOL4' was loaded over an insecure connection. This file should be served over HTTPS.
```

### Diagnostics dump

[config_entry-hacs-00631ae993c05ed1ee7acb1109906797.json.txt](https://github.com/hacs/integration/files/12877319/config_entry-hacs-00631ae993c05ed1ee7acb1109906797.json.txt)

**Comment by tjorim** [comment]
Because it is not an issue...

**Comment by galad2003** [comment]
So just showing the read me is 'working as intended?'

**Comment by tjorim** [comment]
If you click on the HACS repo in the list (2nd screenshot) then yes.

**Comment by Leey0** [comment]
@galad2003 i figured it out. When you click HACs in the sidebar it will bring up the integrations list bit its filtered. Just clear the filter and you'll see the list.

@tjorim could have told us that but seems to be in a bad mood and not wanna be helpful
