### ISSUE TITLE
Request for removal of thomasloven/hass-fontawesome

### ISSUE THREAD

**Issue by KJThaDon** [hacs/integration#3300]
### Repository

thomasloven/hass-fontawesome

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Requesting for removal. Hasn't been updated in 2+ years and isn't functional. Author appears to have abandoned this.

### Link to issue

https://github.com/thomasloven/hass-fontawesome/issues/71

**Comment by thomasloven** [comment]
The integration is functional.

**Comment by KJThaDon** [comment]
> The integration is functional.

Sure, It may be now with the update
