### ISSUE TITLE
Request for removal of arjenvrh/audi_connect_ha

### ISSUE THREAD

**Issue by irlam** [hacs/integration#3314]
### Repository

arjenvrh/audi_connect_ha

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Not maintained anymore

Please can we use this instead, it is currently being maintained

 https://github.com/cyr-ius/hass-audiconnect

Regards

Chris

### Link to issue

https://github.com/arjenvrh/audi_connect_ha#maintainers-wanted

**Comment by ludeeus** [comment]
Last update was < 1 month ago.
