### ISSUE TITLE
The search box for installing repositories is constantly resizing itself to new content after every key press

### ISSUE THREAD

**Issue by adamzimnyy** [hacs/integration#3315]
### Web browser

Chrome

### Web browser version

118.0.5993.71

## System Information

version | core-2023.10.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.56
arch | x86_64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1319
Downloaded Repositories | 33

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.0
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.0
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 62.3 GB
disk_used | 25.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Grafana (9.0.2), Node-RED (14.4.2), Studio Code Server (5.9.0), Check Home Assistant configuration (3.8.0), Terminal & SSH (9.7.1), InfluxDB (4.8.0), Home Assistant Google Drive Backup (0.111.1), Duck DNS (1.15.0), Samba share (10.0.2), FTP (4.7.1), Log Viewer (0.15.1), MariaDB (2.6.1), ESPHome (2023.10.3), Mosquitto broker (6.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 29
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 21 października 2023 08:56
-- | --
current_recorder_run | 24 października 2023 19:29
estimated_db_size | 1067.61 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The search box for installing repositories is constantly resizing itself to new content after every key press. This is very annoying because it's impossible to follow, the text you're typing can be in a different position on the screen every time. 

### Reproduction steps

1. Go to <home-assistant>/hacs/integrations
2. Click Add repository button
3. Start typing in the search bar 
...

### Screenshots

No text: 
![image](https://github.com/hacs/integration/assets/14812161/e75520d6-5504-4834-9658-6c458bad3abd)

search results for `LO`:
![image](https://github.com/hacs/integration/assets/14812161/4bcf3425-5352-473c-9078-163ff9215609)

search results for `LOC`:
![image](https://github.com/hacs/integration/assets/14812161/948fff87-e9ba-4a50-9f3f-6aaf52b365fd)

search results for `LOCAL`: 
![image](https://github.com/hacs/integration/assets/14812161/460a6bcb-5191-47f2-ad12-c9951b76502b)

search result for `LOCALL`: 
![image](https://github.com/hacs/integration/assets/14812161/2b33555e-9bbd-4ae2-bea4-b09316c5f412)

These should not all be a different size. Please make the box stay the same size always, regardless of content. 

### Javascript logs from your browser console

```text
not relevant
```

**Comment by ludeeus** [comment]
This will not be fixed as this has been removed in the upcoming UI.

you can test out the new one already by enabling experimental features.
