### ISSUE TITLE
Can't install hacs

### ISSUE THREAD

**Issue by DrR0X-glitch** [hacs/integration#3333]
## System Information

version | core-2023.11.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 5.15.90.1-microsoft-standard-WSL2
arch | x86_64
timezone | Australia/Brisbane
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 2 November 2023 at 08:52
-- | --
current_recorder_run | 5 November 2023 at 15:30
estimated_db_size | 0.56 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When I try to run the install script from the HACS website I get the following readout:

/config# wget -O - https://raw.githubusercontent.com/hacs/get/main/get | bash -
Connecting to raw.githubusercontent.com (185.199.108.133:443)
writing to stdout
100% |************************************************************************|  3988  0:00:00 ETA
written to stdout
INFO: Trying to find the correct directory...
INFO: Found Home Assistant configuration directory at '/config'
INFO: Changing to the custom_components directory...
INFO: Downloading HACS
Connecting to github.com (20.248.137.48:443)
Connecting to github.com (20.248.137.48:443)
wget: bad address 'objects.githubusercontent.com'

I have used HACS before on a RPi installation but this is my first time with docker.

### Reproduction steps

I feel like this issues is related to my system not everyone installing but here's what I did.
1. Attached a bash terminal to my homeassistant container: `docker exec -it homeassistant bash`
2. Ran `wget -O - https://get.hacs.xyz | bash -`
3. Also tried https://raw.githubusercontent.com/hacs/get/main/get, no change

### Debug logs

```text
I don't have any HACS logs as I haven't got past the install.
```

**Comment by ludeeus** [comment]
You have network problems on that host.
Till you solve that, HACS will not work for you.

**Comment by DrR0X-glitch** [comment]
Sort of what I suspected, why does it successfully download the script though? It downloads from raw.githubusercontent.com but not objects.githubusercontent.com. Just seems a bit weird. Especially when my HASS can connect to the internet perfectly fine.

**Comment by DrR0X-glitch** [comment]
> You have network problems on that host. Till you solve that, HACS will not work for you.

Sort of what I suspected, why does it successfully download the script though? It downloads from raw.githubusercontent.com but not objects.githubusercontent.com. Just seems a bit weird. Especially when my HASS can connect to the internet perfectly fine.

**Comment by ludeeus** [comment]
They are on different servers/CDNs.
It could be proxy settings, could be DNS, could be routing issues, could be anything network.

**Comment by DrR0X-glitch** [comment]
> They are on different servers/CDNs. It could be proxy settings, could be DNS, could be routing issues, could be anything network.

Okay ill take a look at my network setup at make a post on the docker reddit. Thx for your help.
