### ISSUE TITLE
HACS downloads wrong version

### ISSUE THREAD

**Issue by DigiLive** [hacs/integration#3345]
## System Information

version | core-2023.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4378
Installed Version | 1.33.0
Stage | running
Available Repositories | 1333
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.3
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 457.7 GB
disk_used | 9.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.7.0), AdGuard Home (4.8.17), Duck DNS (1.15.0), Terminal & SSH (9.8.1), ESPHome (2023.11.0), Broadlink Manager (5.8.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 4
views | 18
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 6 november 2023 om 07:58
-- | --
current_recorder_run | 13 november 2023 om 19:15
estimated_db_size | 174.98 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When I choose to re-download a front-end repository and choose an alternative version, the downloaded version is still the same.

E.g.
https://homeassistant.com:8123/hacs/repository/619284862
or [![Open your Home Assistant instance and open a repository inside the Home Assistant Community Store.](https://my.home-assistant.io/badges/hacs_repository.svg)](https://my.home-assistant.io/redirect/hacs_repository/?owner=AalianKhan&repository=mushroom-strategy&category=frontend).

Downloaded version: v1.0.1
Requested version: main
Version after download: V1.0.1

### Reproduction steps

Having repository "Auto Generating Mushroom dashboard strategy" downloaded...

1. Goto HACS
2. Goto Frontend
3. Search/Goto Auto Generating Mushroom dashboard strategy.
4. Notice the downloaded version (E.g. v1.0.1).
5. Goto overlay menu (3 dots) > Redownload.
6. Choose another version (e.g. `main`) and download.
7. Choose Reload.
8. Notice the downloaded version (E.g. v1.0.1 instead of `main`).

[![Open your Home Assistant instance and open a repository inside the Home Assistant Community Store.](https://my.home-assistant.io/badges/hacs_repository.svg)](https://my.home-assistant.io/redirect/hacs_repository/?owner=AalianKhan&repository=mushroom-strategy&category=frontend)

### Debug logs

```text
2023-11-15 19:28:47.146 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-15 19:28:47.148 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nest_protect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-15 19:30:56.912 DEBUG (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Getting repository information
2023-11-15 19:30:57.563 DEBUG (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Running checks against v1.0.1
2023-11-15 19:31:03.236 DEBUG (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Getting repository information
2023-11-15 19:31:03.789 DEBUG (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Running checks against v1.0.1
2023-11-15 19:31:04.663 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
2023-11-15 19:31:07.541 DEBUG (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Getting repository information
2023-11-15 19:31:08.110 DEBUG (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Running checks against v1.0.1
2023-11-15 19:31:08.831 DEBUG (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Getting repository information
2023-11-15 19:31:08.961 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
2023-11-15 19:31:09.616 DEBUG (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Running checks against v1.0.1
2023-11-15 19:31:10.701 INFO (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Running pre installation steps
2023-11-15 19:31:10.701 INFO (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Pre installation steps completed
2023-11-15 19:31:10.701 INFO (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Running installation steps
2023-11-15 19:31:10.701 DEBUG (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Getting repository information
2023-11-15 19:31:11.273 DEBUG (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Running checks against v1.0.1
2023-11-15 19:31:12.118 DEBUG (SyncWorker_6) [custom_components.hacs] Backup for /config/www/community/mushroom-strategy, created in /tmp/hacs_backup/mushroom-strategy
2023-11-15 19:31:12.119 DEBUG (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Local path is set to /config/www/community/mushroom-strategy
2023-11-15 19:31:12.119 DEBUG (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Remote path is set to dist
2023-11-15 19:31:12.119 DEBUG (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> mushroom-strategy.js
2023-11-15 19:31:12.119 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Checking out tasks to execute
2023-11-15 19:31:12.119 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Starting queue execution for 1 tasks
2023-11-15 19:31:12.120 DEBUG (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Downloading mushroom-strategy.js
2023-11-15 19:31:12.121 DEBUG (MainThread) [custom_components.hacs] Downloading https://raw.githubusercontent.com/AalianKhan/mushroom-strategy/v1.0.1/dist/mushroom-strategy.js
2023-11-15 19:31:12.579 INFO (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Download of mushroom-strategy.js completed
2023-11-15 19:31:13.582 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Queue execution finished for 1 tasks finished in 1.46 seconds
2023-11-15 19:31:13.585 DEBUG (SyncWorker_7) [custom_components.hacs] Backup dir /tmp/hacs_backup/ cleared
2023-11-15 19:31:13.587 INFO (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Installation steps completed
2023-11-15 19:31:13.588 INFO (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Running post installation steps
2023-11-15 19:31:13.593 INFO (MainThread) [custom_components.hacs] <Plugin AalianKhan/mushroom-strategy> Post installation steps completed
2023-11-15 19:31:13.593 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
```

### Diagnostics dump

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.11.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Amsterdam",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.11.3",
    "host_os": "Home Assistant OS 11.1",
    "docker_version": "24.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "nest_protect": {
      "version": "0.3.12",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "hacs",
    "name": "HACS",
    "codeowners": [
      "@ludeeus"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "websocket_api",
      "frontend",
      "persistent_notification",
      "lovelace",
      "repairs"
    ],
    "documentation": "https://hacs.xyz/docs/configuration/start",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/hacs/integration/issues",
    "requirements": [
      "aiogithubapi>=22.10.1"
    ],
    "version": "1.33.0",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "1cb3cf95f9aa0543c282b92af71c4855",
      "version": 1,
      "domain": "hacs",
      "title": "",
      "data": {
        "token": "**REDACTED**"
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "hacs": {
      "stage": "running",
      "version": "1.33.0",
      "disabled_reason": null,
      "new": false,
      "startup": false,
      "categories": [
        "theme",
        "integration",
        "plugin"
      ],
      "renamed_repositories": {
        "78wesley/Darkish-Theme": "78wesley/Home-Assistant-Darkish-Theme",
        "9a4gl/hass-peltec": "9a4gl/hass-centrometal-boiler",
        "DarkSir23/sensor.mylar": "WillowMist/sensor.mylar",
        "nikrolls/homeassistant-goldair-climate": "nicole-ashley/homeassistant-goldair-climate",
        "nbogojevic/homeassistant-midea-dehumidifier-lan": "nbogojevic/homeassistant-midea-air-appliances-lan",
        "dmitry-k/yandex_smart_home": "dext0r/yandex_smart_home",
        "wills106/homsassistant-solax-modbus": "wills106/homeassistant-solax-modbus",
        "uvjustin/alarmdotcom": "pyalarmdotcom/alarmdotcom",
        "wernerhp/ha_integration_load_shedding": "wernerhp/ha.integration.load_shedding",
        "TheLastProject/lovelace-valetudo-map-card": "Hypfer/lovelace-valetudo-map-card",
        "fuatakgun/kia_uvo": "Hyundai-Kia-Connect/kia_uvo",
        "jadson179/consul": "gtjadsonsantos/consul",
        "Farfar/homeassistant-skodaconnect": "skodaconnect/homeassistant-skodaconnect",
        "lendy007/homeassistant-skodaconnect": "skodaconnect/homeassistant-skodaconnect",
        "mtarjoianu/ha_lektrico": "Lektrico/ha_lektrico",
        "JoshuaMulliken/ha-wyzeapi": "SecKatie/ha-wyzeapi",
        "jvitkauskas/homeassistant_salus": "epoplavskis/homeassistant_salus",
        "Wibias/hass-variables": "enkama/hass-variables"
      },
      "archived_repositories": [
        "Sholofly/arrisdcx960",
        "DavidMStraub/homeassistant-homeconnect",
        "NemesisRE/lovelace-swipe-navigation",
        "gerardag/person-entity-card",
        "lukich48/hass_mqtt_template_switch",
        "JuanMTech/green_dark_mode",
        "robmarkcole/HASS-Deepstack-face",
        "marcomow/ble-bulb-card",
        "ThomasPrior/EthermineInfo",
        "custom-components/sensor.untappd",
        "spycle/microbot_push",
        "JuanMTech/green_light_mode",
        "DCSBL/ha-homewizard-energy",
        "Cyr-ius/hass-cozytouch",
        "gjohansson-ST/stl",
        "peternijssen/home-assistant-jumbo",
        "JuanMTech/orange_dark",
        "frenck/home-assistant-theme-outline",
        "cgarwood/homeassistant-fullykiosk",
        "custom-components/wienerlinien",
        "robmarkcole/HASS-Deepstack-object",
        "clayauld/lovelace-darksky-card",
        "JuanMTech/amoled_blue",
        "walthowd/ha-automower",
        "eavanvalkenburg/sia",
        "JuanMTech/orange_light",
        "natekspencer/hacs-litterrobot",
        "jessevl/homeassistant-greenchoice",
        "georgezhao2010/climate_ewelink",
        "thebino/rki_covid",
        "KTibow/lovelace-light-soft-ui-theme",
        "marrobHD/firetv-card",
        "KTibow/lovelace-dark-soft-ui-theme",
        "GeorgeSG/lovelace-folder-card",
        "Cyr-ius/hass-hue-service-advanced"
      ],
      "ignored_repositories": [],
      "lovelace_mode": "storage",
      "configuration": {
        "appdaemon": false,
        "country": "ALL",
        "debug": false,
        "dev": false,
        "experimental": false,
        "netdaemon": false,
        "python_script": false,
        "release_limit": 5,
        "theme": false
      }
    },
    "custom_repositories": [
      "AlexxIT/DashCast",
      "home-assistant-libs/python-matter-server"
    ],
    "repositories": [
      {
        "data": {
          "archived": false,
          "authors": [
            "@ludeeus"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "main",
          "description": "HACS gives you a powerful UI to handle downloads of all your custom needs.",
          "domain": "hacs",
          "downloads": 213250,
          "etag_repository": "W/\"f421dfe05739127d1bf76b9954733955a49d92674abba7c292c9f8f7bfd8ba6c\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "hacs/integration",
          "hide": false,
          "has_issues": true,
          "id": "172733314",
          "installed_commit": "98eeb42",
          "installed_version": "1.33.0",
          "installed": true,
          "last_commit": "63b2c41",
          "last_updated": "2023-11-05T12:07:11Z",
          "last_version": "1.33.0",
          "manifest_name": "HACS",
          "new": false,
          "open_issues": 7,
          "published_tags": [
            "1.33.0",
            "1.32.1",
            "1.32.0",
            "1.31.0",
            "1.30.1"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 4053,
          "topics": [
            "community",
            "package-manager"
          ]
        },
        "integration_manifest": {
          "domain": "hacs",
          "name": "HACS",
          "codeowners": [
            "@ludeeus"
          ],
          "config_flow": true,
          "dependencies": [
            "http",
            "websocket_api",
            "frontend",
            "persistent_notification",
            "lovelace",
            "repairs"
          ],
          "documentation": "https://hacs.xyz/docs/configuration/start",
          "iot_class": "cloud_polling",
          "issue_tracker": "https://github.com/hacs/integration/issues",
          "requirements": [
            "aiogithubapi>=22.10.1"
          ],
          "version": "0.0.0"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "hacs.zip",
          "hacs": "0.19.0",
          "hide_default_branch": true,
          "homeassistant": "2023.6.0",
          "manifest": {
            "name": "HACS",
            "zip_release": true,
            "hide_default_branch": true,
            "homeassistant": "2023.6.0",
            "hacs": "0.19.0",
            "filename": "hacs.zip"
          },
          "name": "HACS",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": "1.33.0",
        "paths": {
          "localpath": "/config/custom_components/hacs",
          "local": "/config/custom_components/hacs",
          "remote": "custom_components/hacs"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "config_flow": false,
          "default_branch": "main",
          "description": "A strategy to automatically generate a dashboard using mushroom cards",
          "domain": null,
          "downloads": 4052,
          "etag_repository": "W/\"6c954d27a21afeade00f421a7b9513aedf9930428099eababb2603df7334a98f\"",
          "etag_releases": null,
          "file_name": "mushroom-strategy.js",
          "first_install": false,
          "full_name": "AalianKhan/mushroom-strategy",
          "hide": false,
          "has_issues": true,
          "id": "619284862",
          "installed_commit": "c1d6558",
          "installed_version": "v1.0.1",
          "installed": true,
          "last_commit": "c1d6558",
          "last_updated": "2023-11-13T16:00:07Z",
          "last_version": "v1.0.1",
          "manifest_name": null,
          "new": false,
          "open_issues": 16,
          "published_tags": [
            "v1.0.1",
            "v1.0.0",
            "1.0.0-alpha.2",
            "1.0.0-alpha.1",
            "0.15"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": true,
          "stargazers_count": 159,
          "topics": [
            "mushroom-strategy",
            "strategy"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "mushroom-strategy.js",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": null,
          "manifest": {
            "name": "Auto generating Mushroom dashboard strategy",
            "render_readme": true,
            "filename": "mushroom-strategy.js"
          },
          "name": "Auto generating Mushroom dashboard strategy",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": "tags/v1.0.1",
        "paths": {
          "localpath": "/config/www/community/mushroom-strategy",
          "local": "/config/www/community/mushroom-strategy",
          "remote": "dist"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@imicknl"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "main",
          "description": "Nest Protect integration for Home Assistant. This will allow you to integrate your smoke, heat, co and occupancy status real-time in HA.",
          "domain": "nest_protect",
          "downloads": 0,
          "etag_repository": "W/\"b9c4a16f3547e48d52ef60f89b082c709218df440e03102d17fd5a0e5fab923c\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "iMicknl/ha-nest-protect",
          "hide": false,
          "has_issues": true,
          "id": "448323715",
          "installed_commit": "72cdce6",
          "installed_version": "v0.3.12",
          "installed": true,
          "last_commit": "e7731e6",
          "last_updated": "2023-11-13T17:37:35Z",
          "last_version": "v0.3.12",
          "manifest_name": "Nest Protect",
          "new": false,
          "open_issues": 50,
          "published_tags": [
            "v0.3.12",
            "v0.3.11",
            "v0.3.10",
            "v0.3.9",
            "v0.3.8"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 254,
          "topics": [
            "google",
            "nest",
            "nest-protect"
          ]
        },
        "integration_manifest": {
          "domain": "nest_protect",
          "name": "Nest Protect",
          "codeowners": [
            "@imicknl"
          ],
          "config_flow": true,
          "dhcp": [
            {
              "macaddress": "CCA7C1*"
            }
          ],
          "documentation": "https://github.com/imicknl/ha-nest-protect",
          "iot_class": "cloud_polling",
          "issue_tracker": "https://github.com/imicknl/ha-nest-protect/issues",
          "requirements": [],
          "version": "0.3.12"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2023.1.7",
          "manifest": {
            "name": "Nest Protect",
            "homeassistant": "2023.1.7",
            "render_readme": "true"
          },
          "name": "Nest Protect",
          "persistent_directory": null,
          "render_readme": "true",
          "zip_release": false
        },
        "ref": "v0.3.12",
        "paths": {
          "localpath": "/config/custom_components/nest_protect",
          "local": "/config/custom_components/nest_protect",
          "remote": "custom_components/nest_protect"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "config_flow": false,
          "default_branch": "master",
          "description": "Minimalistic graph card for Home Assistant Lovelace UI",
          "domain": "",
          "downloads": 263625,
          "etag_repository": "W/\"55eb6ca4d3939fe4d237c1e83c6370d24ee73e9f18af5dfc391ba9ecc5db6427\"",
          "etag_releases": null,
          "file_name": "mini-graph-card-bundle.js",
          "first_install": false,
          "full_name": "kalkih/mini-graph-card",
          "hide": false,
          "has_issues": true,
          "id": "151280062",
          "installed_commit": "88d91eb",
          "installed_version": "v0.11.0",
          "installed": true,
          "last_commit": "210fb4c",
          "last_updated": "2023-11-06T02:33:20Z",
          "last_version": "v0.11.0",
          "manifest_name": null,
          "new": false,
          "open_issues": 136,
          "published_tags": [
            "v0.11.0",
            "v0.10.0",
            "v0.9.4",
            "v0.9.3",
            "v0.9.2"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 2516,
          "topics": [
            "automation",
            "custom",
            "graph"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": null,
          "manifest": {
            "name": "mini-graph-card",
            "render_readme": true
          },
          "name": "mini-graph-card",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": "v0.11.0",
        "paths": {
          "localpath": "/config/www/community/mini-graph-card",
          "local": "/config/www/community/mini-graph-card",
          "remote": "release"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "config_flow": false,
          "default_branch": "main",
          "description": "Mushroom Cards - Build a beautiful dashboard easily \ud83c\udf44",
          "domain": "",
          "downloads": 36445,
          "etag_repository": "W/\"fc80c634dae13c403db1a56227e3ca4951344a5816fec8a03d10817850fa623d\"",
          "etag_releases": null,
          "file_name": "mushroom.js",
          "first_install": false,
          "full_name": "piitaya/lovelace-mushroom",
          "hide": false,
          "has_issues": true,
          "id": "444350375",
          "installed_commit": "115fea2",
          "installed_version": "v3.2.0",
          "installed": true,
          "last_commit": "3ffaa21",
          "last_updated": "2023-11-05T15:25:45Z",
          "last_version": "v3.2.2",
          "manifest_name": null,
          "new": false,
          "open_issues": 295,
          "published_tags": [
            "v3.2.2",
            "v3.2.0",
            "v3.1.0",
            "v3.0.5",
            "v3.0.3"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 2634,
          "topics": [
            "card",
            "mushroom"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "mushroom.js",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2023.7.0",
          "manifest": {
            "name": "Mushroom",
            "filename": "mushroom.js",
            "homeassistant": "2023.7.0",
            "render_readme": true
          },
          "name": "Mushroom",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": "v3.2.2",
        "paths": {
          "localpath": "/config/www/community/lovelace-mushroom",
          "local": "/config/www/community/lovelace-mushroom",
          "remote": "release"
        }
      }
    ],
    "rate_limit": {
      "resources": {
        "core": {
          "limit": 5000,
          "used": 133,
          "remaining": 4867,
          "reset": 1700076345
        },
        "search": {
          "limit": 30,
          "used": 0,
          "remaining": 30,
          "reset": 1700073285
        },
        "graphql": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1700076825
        },
        "integration_manifest": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1700076825
        },
        "source_import": {
          "limit": 100,
          "used": 0,
          "remaining": 100,
          "reset": 1700073285
        },
        "code_scanning_upload": {
          "limit": 1000,
          "used": 0,
          "remaining": 1000,
          "reset": 1700076825
        },
        "actions_runner_registration": {
          "limit": 10000,
          "used": 0,
          "remaining": 10000,
          "reset": 1700076825
        },
        "scim": {
          "limit": 15000,
          "used": 0,
          "remaining": 15000,
          "reset": 1700076825
        }
      },
      "rate": {
        "limit": 5000,
        "used": 133,
        "remaining": 4867,
        "reset": 1700076345
      }
    }
  }
}

**Comment by ludeeus** [comment]
This selector has been removed in favor of the update entities, this change is currently not yet released.
But that also mean there is nothing to fix here.
