### ISSUE TITLE
Request for removal of custom-components/alexa_media_player

### ISSUE THREAD

**Issue by omayhemo** [hacs/integration#3349]
### Repository

custom-components/alexa_media_player

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

The author refuses to interact with the community in a civil manner which has led to the integration being dysfunctional and the community devolving into nonsense.

### Link to issue

https://github.com/custom-components/alexa_media_player/issues/2103

**Comment by ludeeus** [comment]
Not going to remove this based on that.

**Comment by Doldak** [comment]
then please make sure that someone else takes care of it when the arrogant developer is fed up!
