### ISSUE TITLE
Compatibility with new addons_config folder

### ISSUE THREAD

**Issue by DJBenson** [hacs/integration#3351]
## System Information

version | core-2023.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.59
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1411
Downloaded Repositories | 87

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.3
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 251.3 GB
disk_used | 178.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.1.0), Studio Code Server (5.14.2), Mosquitto broker (6.3.1), Advanced SSH & Web Terminal (16.0.1), phpMyAdmin (0.8.9), Node-RED (16.0.2), TasmoAdmin (0.26.0), Let's Encrypt (4.12.9), rtl_433 MQTT Auto Discovery (0.7.0), rtl_433 (0.4.1), MariaDB (2.6.1), Portainer (2.19.1), AirSonos (4.0.0), Frigate (0.12.1), AppDaemon (0.14.0), Tuya Grab (0.8), Cloudflared (4.2.10), ESPHome (2023.11.1), InfluxDB (4.8.0), Grafana (9.1.1), Matter Server (4.10.2), EMHASS (0.4.2), Z-Wave JS (0.3.0), RTSPtoWeb - WebRTC (1.4.0), Piper (1.4.0), Whisper (1.0.0), Tailscale with features (0.13.1.4), OneDrive Backup (2.2.4), GivTCP (2.4.1), File editor (5.7.0), openWakeWord (1.8.2), porcupine1 (1.0.3), Zigbee2MQTT (1.33.2-1), TubesZB TI CC2652 FW Flasher (0.2.2), Scrypted (18-jammy-full.s6-v0.57.0), Network UPS Tools (0.12.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 50
views | 40
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 20, 2023 at 10:22
-- | --
current_recorder_run | November 17, 2023 at 13:07
estimated_db_size | 17405.47 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Solcast PV Forecast</summary>

can_reach_server | ok
-- | --
used_requests | 7
rooftop_site_count | 1

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The 0.15.0 version of the AppDaemon addon for Home Assistant moved to using the new addons_config folder for consolidated storage - this was something mandated by Nabu Casa so will eventually impact all addons which use external storage.

AppDaemon apps installed using HACS (example https://github.com/springfall2008/batpred) currently save their configuration to the /homeassistant/appdaemon/apps folder but this is no longer used by AppDaemon and needs to be overridden to get these apps up and running again.

Ideally all apps should support installation and updating of apps to the new directory but HACS is unable to see this directory.

I have tried to capture as much as possible but not sure everything is relevant as it's not strictly a bug but if I've missed anything please let me know.

### Reproduction steps

1. Install HACS
2. Install AppDaemon 0.14 addon
3. Install an AppDaemon app via HACS
4. Upgrade to AppDaemon 0.15

AppDaemon will move the config to the new location but HACS is unable to read/write that location so the app cannot be upgraded via HACS.

### Debug logs

```text
N/A
```

### Diagnostics dump

N/A

**Comment by ludeeus** [comment]
Check the appdaemon documentation on how to point to a different directory for apps.
This is not something HACS can change.

**Comment by DJBenson** [comment]
@ludeeus I'm aware of how to make AppDaemon point to different diretories - the issue is that Home Assistant is mandating files be stored outside of /config by default and HACS is seemingly unable to write outside of /config.
