### ISSUE TITLE
Request for removal of Villhellm/lovelace-animated-background

### ISSUE THREAD

**Issue by TRusselo** [hacs/integration#3353]
### Repository

Villhellm/lovelace-animated-background

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

The author has died, and the feature of animated backgrounds has been broken since 2023.04

working fork:
https://github.com/dreimer1986/lovelace-animated-background

author does not intend to be maintainer though...

### Link to issue

https://github.com/Villhellm/lovelace-animated-background/pull/59

**Comment by TRusselo** [comment]
i created a fork I am wiling to maintain.
https://github.com/TRusselo/lovelace-animated-background/

**Comment by tjorim** [comment]
It has already been removed: https://github.com/hacs/default/commit/18c906c6da6755f833c1947529b290800b747853
