### ISSUE TITLE
Request for removal of custom-components/alexa_media_player

### ISSUE THREAD

**Issue by gaffa** [hacs/integration#3354]
### Repository

custom-components/alexa_media_player

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

When setting up, users are moved into endless captchas.
The website that the captchas are displayed by is hosted under nabucasa url and not Amazon but it pretends to be Amazon.
There is a copyright 2006-2014 on the bottom of the page.
Also two links which are broken.
This seems like a spoofed website.
In combination of instructions on how to register as a 2fa app this is a dangerous attack scenario and I am afraid there may be malicious code somewhere.

I suggest temporarily delisting this until the matter is clarified.

### Link to issue

https://github.com/custom-components/alexa_media_player/issues/2103#issuecomment-1817416620

**Comment by ludeeus** [comment]
It is not hosted by Nabucasa.
The image you base this on shows the URL of the poster's own Home Assistant instance.
It is hosted by Amazon (<https://www.amazon.com/errors/validateCaptcha>). The integration uses a proxy to show it.
Why they have not updated the date, is something you would have to ask Amazon about.

**Comment by gaffa** [comment]
Okay. Thank you. This was really confusing and I hope you understand why I got mistaken.
Crazy!
The links are working in your provided link, though. And they seem not to be relative?

**Comment by ludeeus** [comment]
I do not use or know the alexa integration, my link is the base page for it.
But that in itself does nothing.
