### ISSUE TITLE
"<Validation images> failed" when there are images in the readme file

### ISSUE THREAD

**Issue by tonyroberts** [hacs/integration#3362]
### Describe the issue

I'm not too sure how to test what's going wrong with this so I thought I'd ask.. perhaps there is a way to enable more verbose debugging for the action?

The issue is that the image validation step is failing, saying there are no images in the readme file, but there are images. I'm not sure why it's not finding them.

I've been testing this on a branch of the repo with the problem, but so far I've not made much progress.

Things I've checked so far

- hacs.json has "render_readme" set to true
- the file README.md has both <img> tags and ![] images
- the images should not be excluded (i.e. are not badges etc)
- I've run the ``custom_components.hacs.validate.images.Validator`` locally using the readme file and that passes

I couldn't find an easy way to run the validations locally so I ended up modifying one of the unit tests (test_repository_has_images) to load the README.md file, and that passed.

I'm a bit lost as to why this check should work locally but not when run as an action, and I'm not sure how to go about debugging this further so any help would be appreciated.

Thanks!

### Link to action run

https://github.com/tonyroberts/scheduler-card/actions/runs/6944722330

### Link to action configuration

https://github.com/tonyroberts/scheduler-card/blob/main/.github/workflows/validate.yaml

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
As for making it more verbose, GitHub actions have native support for enabling debug.
https://github.blog/changelog/2022-05-24-github-actions-re-run-jobs-with-debug-logging/

**Comment by tonyroberts** [comment]
> As for making it more verbose, GitHub actions have native support for enabling debug. https://github.blog/changelog/2022-05-24-github-actions-re-run-jobs-with-debug-logging/

Ahh! thanks :) I re-ran that with debug logging and found this

```
##[debug] <Plugin tonyroberts/scheduler-card> Getting documentation for version=None,filename=README.md
Error:  <Validation images> failed:  The repository does not have images in the Readme file (More info: https://hacs.xyz/docs/publish/include#check-images )
```

Looks like it's finding the correct "README.md" filename, but do you think it's because version=None that it's not actually loading the file?

**Comment by ludeeus** [comment]
That is exactly whats happening.
Which then confirms my suspicions, thanks 👍

**Comment by ludeeus** [comment]
Once <https://github.com/hacs/integration/actions/runs/6946236123> completes, it should start working.

**Comment by tonyroberts** [comment]
Thanks! Yes, that's fixed it :)
