### ISSUE TITLE
Deleting a repository from Custom repositories modal causes the modal to collapse automatically

### ISSUE THREAD

**Issue by codyc1515** [hacs/integration#3364]
### Web browser

Edge

### Web browser version

119.0.0.0

## System Information

version | core-2023.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Pacific/Auckland
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4975
Installed Version | 1.33.0
Stage | running
Available Repositories | 1351
Downloaded Repositories | 27
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.3
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 116.5 GB
disk_used | 16.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2023.11.2), Tailscale (0.13.1), File editor (5.7.0), Scrypted (18-jammy-full.s6-v0.57.0), Node-RED (16.0.2), Terminal & SSH (9.8.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 19, 2023 at 15:44
-- | --
current_recorder_run | November 22, 2023 at 04:44
estimated_db_size | 246.77 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.13
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Deleting a repository from Custom repositories modal causes the modal to collapse automatically. This is unexpected for me as I may want to delete some other Custom repositories or maybe add some new ones.

### Reproduction steps

Add a Custom repository and close everything, then:

1. Browse to HACS
2. Hit the dots in top-right
3. Select Custom repositories
4. Press the delete button

You will see that the modal closed automatically.

### Screenshots

![image](https://github.com/hacs/integration/assets/50791984/89719835-52a3-48ff-8a71-7f2b6ca8b23f)

### Javascript logs from your browser console

```text
21A soft navigation has been detected: <URL>
brands.home-assistant.io/meridian_energy/dark_icon.png:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
Virtualizer.ts:741  Uncaught (in promise) TypeError: Cannot destructure property 'scrollTop' of 'this._scrollerController' as it is null.
    at y._correctScrollError (Virtualizer.ts:741:14)
    at y._finishDOMUpdate (Virtualizer.ts:546:10)
    at y._updateDOM (Virtualizer.ts:538:10)
    at y._handleLayoutMessage (Virtualizer.ts:603:12)
    at _._hostSink (Virtualizer.ts:441:44)
    at _._sendStateChangedMessage (BaseLayout.ts:478:10)
    at _._reflow (BaseLayout.ts:364:10)
    at _._reflow (flow.ts:491:11)
    at _.reflowIfNeeded (BaseLayout.ts:257:12)
    at y._updateLayout (Virtualizer.ts:563:21)
/unknown/src/Virtualizer.ts:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
/unknown/src/layouts/shared/BaseLayout.ts:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
/unknown/src/layouts/flow.ts:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
lit-html.ts:1883  The specified value "NaN" cannot be parsed, or is out of range.
j @ lit-html.ts:1883
lit-html.ts:1883  The specified value "NaN" cannot be parsed, or is out of range.
j @ lit-html.ts:1883
/api/config/automation/config/1698691404108:1 
        
        
        Failed to load resource: the server responded with a status of 400 (Bad Request)
ha-automation-editor.ts:752  Uncaught (in promise) Object
hui-image.ts:393  Uncaught (in promise) 3
```

**Comment by cociweb** [comment]
more over, you are not able to re-add it:
![image](https://github.com/hacs/integration/assets/1935413/78c42c63-740b-48a6-a310-d54eb7d7314b)

**Comment by codyc1515** [comment]
Still current.

**Comment by ludeeus** [comment]
This was changed in <https://github.com/hacs/frontend/pull/664/files> to stay open.

**Comment by codyc1515** [comment]
Sorry but this isn’t fixed (even in the latest experimental version). Go to Custom repo, add one, then click to remove - the whole modal closes, for example.

**Comment by ludeeus** [comment]
That PR has not been released yet.

**Comment by codyc1515** [comment]
For my education, why is that? It looks like it was merged six months ago but mustn’t be used.

**Comment by ludeeus** [comment]
I release things when needed, and I have time to do so.

**Comment by codyc1515** [comment]
It’s no trouble. I simply thought when it was merged that equaled released but it seems not.
