### ISSUE TITLE
Deleting a repository from Custom repositories does not delete that Integrations update entity

### ISSUE THREAD

**Issue by codyc1515** [hacs/integration#3365]
### Web browser

Edge

### Web browser version

119.0.0.0

## System Information

version | core-2023.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Pacific/Auckland
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4975
Installed Version | 1.33.0
Stage | running
Available Repositories | 1351
Downloaded Repositories | 27
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.3
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 116.5 GB
disk_used | 16.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2023.11.2), Tailscale (0.13.1), File editor (5.7.0), Scrypted (18-jammy-full.s6-v0.57.0), Node-RED (16.0.2), Terminal & SSH (9.8.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 19, 2023 at 15:44
-- | --
current_recorder_run | November 22, 2023 at 04:44
estimated_db_size | 246.77 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.13
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Deleting a repository from Custom repositories does not delete that Integrations `update` entity and so it gets marked as unavailable.

### Reproduction steps

1. Add Custom repository from Dots menu
2. Install custom integration
3. Restart HA
4. Remove Custom repository from Dots menu
5. Ignore warnings (if any)

The update entity becomes unavailable but should be either be removed (as it's no longer a HACS-managed integration) or retained (as the data may be available to HACS still).

### Debug logs

```text
TBC
```

### Diagnostics dump

[config_entry-hacs-4330f7139441a2d4cc704390da487e04.json.txt](https://github.com/hacs/integration/files/13432830/config_entry-hacs-4330f7139441a2d4cc704390da487e04.json.txt)

**Comment by ludeeus** [comment]
You need to restart Home Assistant for those to be added/removed.

**Comment by codyc1515** [comment]
Fairly sure I did do that as I only noticed it when creating some custom integrations which necessitates a lot of restarts. I’ll see if I can get a screen recording some other time.
