### ISSUE TITLE
Custom components and browser cache disabled

### ISSUE THREAD

**Issue by emandtf** [hacs/integration#3366]
### Web browser

Firefox and Chrome

### Web browser version

119.x for both

### System Health details

I'm using HA Core 2023.11.2 and there isn't any way to follow what is showed in "https://www.home-assistant.io//more-info/system-health#github-issues" for getting system info.

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

If browsers have Cache Disabled all custom components (I'm using vertical-stack-in-card, mini-graph-card and multi-entity-row) won't be recognized until I remove "_Disable cache_" flag from Development Panel.

Even the FIRST access from a different browser (like on a new device) doesn't recognize custom components even if in the Console Log their initialization seems completed (see attached file).
![20231123_console_log](https://github.com/hacs/integration/assets/13537385/4e60ccbe-4889-4843-aed6-a975695ae118)
Closing and re-opening tab/browser, after this FIRST visit with issues, seems let components working again.

It seems like custom components JS files are loaded just once and then retained in cache and served ONLY from it, so if it is disabled them won't work.

**PS**: After this test it was hard to let custom components work again (after cache enabled again) even doing normal page Refresh multiple times.
I have to close browser Tab and then open another one to have custom components working again.

### Reproduction steps

1. Open Developer Panel (F12 on Firefox and Chrome)
2. Switch to Network tab
3. Enable "_Disable cache_" checkbox
4. Refresh a Lovelace dashboard where an custom component is placed, or just do CTRL+SHIFT+R to refresh the page WITHOUT using already cached files
5. Then all custom components are not recognized and won't work

### Screenshots

![20231123_firefox_cache_disabled](https://github.com/hacs/integration/assets/13537385/2a7206d5-06ea-455c-b2cf-715846e7c870)

### Javascript logs from your browser console

```text
Already displayed in the screenshot above
```

**Comment by ludeeus** [comment]
Im confused, HACS does not load any of these.
That is all handled by Home Assistant.
Why is this opened here?

**Comment by ludeeus** [comment]
HACS downloads them. That is correct.
In some cases, it also registers the resources.
But that is all it does.
The actual loading of them is handled by the Home Assistant frontend.

It could be that one of your custom things are interfering with how that loading is handled.

**Comment by emandtf** [comment]
> It could be that one of your custom things are interfering with how that loading is handled.

I think it's the Service Worker of the browser doing advanced caching and doesn't reload custom components JS when really needed but only "once".
I'll open this issue in HA frontend page. 

Thx for the assistance.
