### ISSUE TITLE
HACS menu items are not visible

### ISSUE THREAD

**Issue by gclaas** [hacs/integration#3367]
### Web browser

chrome

### Web browser version

Versie 119.0.6045.160 (Officiële build) (64-bits)

## System Information

version | core-2023.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4986
Installed Version | 1.33.0
Stage | running
Available Repositories | 1409
Downloaded Repositories | 1
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.3
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 109.3 GB
disk_used | 8.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.111.1), ESPHome (2023.11.3), Samba share (12.1.0), InfluxDB (4.8.0), Grafana (9.1.1), SQLite Web (4.0.0), Studio Code Server (5.14.2), Advanced SSH & Web Terminal (16.0.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 22 november 2023 om 09:09
-- | --
current_recorder_run | 23 november 2023 om 14:56
estimated_db_size | 33.48 MiB
database_engine | sqlite
database_version | 3.41.2

</details>
![Schermafbeelding 2023-11-23 145319](https://github.com/hacs/integration/assets/122520614/2877a2e9-cc4b-4b4f-9dc8-65a25b0ef43f)

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

![Schermafbeelding 2023-11-23 145319](https://github.com/hacs/integration/assets/122520614/d4523f4e-1e28-4a84-8ee2-cf51ff2486ed)

### Reproduction steps

1. Problem occurred after an initial install. Don't know how te describe a way of reproducing
2. Sorry
3.
4.
...

### Screenshots

![Schermafbeelding 2023-11-23 145319](https://github.com/hacs/integration/assets/122520614/be532039-94ac-4016-b113-0ff6feb7c1cd)

### Javascript logs from your browser console

```text
how to reach the logs?
```

**Comment by ludeeus** [comment]
Nothing wrong there.
See docs https://experimental.hacs.xyz/docs/basic/dashboard for more details.

**Comment by gclaas** [comment]
Closed the record unfortunately
