### ISSUE TITLE
Overview clickable rows are not HTML links

### ISSUE THREAD

**Issue by Xyolyp** [hacs/integration#3371]
### Web browser

MS edge

### Web browser version

Version 119.0.2151.72 (Offizielles Build) (64-Bit)

## System Information

version | core-2023.11.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 4.19.0-24-amd64
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4979
Installed Version | 1.33.0
Stage | running
Available Repositories | 1347
Downloaded Repositories | 2
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 21. November 2023 um 19:18
-- | --
current_recorder_run | 28. November 2023 um 18:38
estimated_db_size | 247.15 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When browsing through the list of HACS integrations I would like to be able to use well known shortcuts (ctrl + left mouse click, middle mouse click/mouse wheel click) to interact with the "links" to the detail pages of the integrations. Sadly the list of integrations does not contain HTML links but some javascript way of making things clickable. That way you can not open an entry in a new tab to continue browsing. This is emphasised by the fact that the scroll position is not kept once one hits the browser back key after looking at an integration.

### Reproduction steps

1. Have a system with HACS installed 
2. Click on HACS in the sidebar on the left
3. Try middle mouse button/mouse wheel clicking an entry. It should open in a new tab but instead it opens in the same tab.

### Screenshots

Not applicable

### Javascript logs from your browser console

```text
Autofocus processing was blocked because a document already has a focused element.
/config/integrations/dashboard:1 [Intervention]Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113
```

**Comment by ludeeus** [comment]
This is correct.
I'm currently not taking any feature requests.
