### ISSUE TITLE
 Unable to log in to GitHub authorization, network iswork ,but throw Cannot connect to host github.com:443 ssl:defaut,Sugguest use web jsapi send auth request

### ISSUE THREAD

**Issue by lozn00** [hacs/integration#3372]
### System Health details

network iswork ,but throw Cannot connect to host github.com:443 ssl:defaut

## System Information

version | core-2023.11.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 5.15.104
arch | x86_64
timezone | Asia/Shanghai
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | failed to load: unreachable
can_reach_cloud_auth | failed to load: unreachable
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 2023年11月23日 13:50
-- | --
current_recorder_run | 2023年11月29日 13:32
estimated_db_size | 1.80 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.13
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 4

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

github error 
error_message is but throw Cannot connect to host github.com:443 ssl:defaut

network iswork ,but throw Cannot connect to host github.com:443 ssl:defaut

```
            async_call_later(self.hass, 1, _wait_for_activation)
            try:
                response = await self.device.register()
                self._login_device = response.data
                return self.async_show_progress(
                    step_id="device",
                    progress_action="wait_for_device",
                    description_placeholders={
                        "url": OAUTH_USER_LOGIN,
                        "code": self._login_device.user_code,
                    },
                )
            except GitHubException as exception:
                error_message = traceback.format_exc()
                self.log.setLevel(50)
                self.log.error(exception)
               # return self.async_abort(reason="github "+str(error_message))

```
![image](https://github.com/hacs/integration/assets/14260426/9d49d563-f146-47f6-9d41-35f1e7f6718a)

### Reproduction steps

docker环境，docker环境中可以ping通github.com
Docker environment, you can ping github.com in the Docker environment

https://github.com/ludeeus/aiogithubapi/issues/256

### Debug logs

```text
retries exceeded with url: /controller?action=capturescreen&compressrate=50&timestamp=1701236351530&opaque=4e9c898534a92f5583c6a54cc25d8ddb7ff72e37 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f83259ac9d0>, 'Connection to 10.10.10.100 timed out. (connect timeout=5)'))
2023-11-29 13:39:16.536 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 7.39s
2023-11-29 13:39:16.537 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2023-11-29 13:39:42.492 INFO (MainThread) [custom_components.xiaomi_miot.sensor] Mi AI Speaker II(xiaomi.wifispeaker.l06a): New xiaoai conversation: 444测
2023-11-29 13:44:48.149 ERROR (MainThread) [homeassistant.components.http.forwarded] A request from a reverse proxy was received from 172.17.0.1, but your HTTP integration is not set-up for reverse proxies
2023-11-29 13:45:26.794 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://github.com/login/device/code' with - Cannot connect to host github.com:443 ssl:default [None]
```

### Diagnostics dump

not

**Comment by ludeeus** [comment]
Im currently not taking feature requests.
If you need help with your network issues, you should ask on HA discord/forums.
