### ISSUE TITLE
HACS not showing the store

### ISSUE THREAD

**Issue by FrietbakkerThjeu** [hacs/integration#3373]
### Web browser

HA Android application

### Web browser version

2023.10.2-full

## System Information

version | core-2023.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.33.0
Stage | running
Available Repositories | 1414
Downloaded Repositories | 1
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.6
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 57.8 GB
disk_used | 5.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), File editor (5.6.0), Terminal & SSH (9.7.1), Mosquitto broker (6.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 22 november 2023 om 02:00
-- | --
current_recorder_run | 29 november 2023 om 13:16
estimated_db_size | 21.16 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When i open HACS in the home assistant tree it wont show the home assistant community store. I cannot see the "integrations", "Frontend", "automation" "Add-ons", "about".

When i click the HACS in the menu i get a new Window with "name of repository" and HACS is listed.  When i click that it brings up the github info page. I have adder a screenrecording of this issue.

https://github.com/hacs/integration/assets/150144319/26356eaf-388a-4ad6-a429-df8468b85424

### Reproduction steps

1. Started home assistant application
2. Clicked HACS on the left tree
3. Did not get to see integrations, Frontend, automation, add-ons, about
 See provider screen capture

### Screenshots

https://github.com/hacs/integration/assets/150144319/61993bae-e1d1-447c-9e6e-7c716df48943

### Javascript logs from your browser console

```text
Android app...
```

### Diagnostics dump

[config_entry-hacs-45cb366e9a365ad788181a7678e3246a.json](https://github.com/hacs/integration/files/13500808/config_entry-hacs-45cb366e9a365ad788181a7678e3246a.json)

**Comment by ludeeus** [comment]
https://experimental.hacs.xyz/docs/basic/dashboard
