### ISSUE TITLE
Request for removal of PiotrMachowski/Home-Assistant-custom-components-Google-Keep

### ISSUE THREAD

**Issue by dziban303** [hacs/integration#3376]
### Repository

PiotrMachowski/Home-Assistant-custom-components-Google-Keep

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

This integration has not worked for at least six months, possibly longer, and the dev has said he can't fix it. 

### Link to issue

https://github.com/PiotrMachowski/Home-Assistant-custom-components-Google-Keep/issues/31

**Comment by StefanoGiu** [comment]
It's working properly for me, with HA 2023.11.3... why you are removing it??? Can you please rollback this removal??

**Comment by StefanoGiu** [comment]
I could... but it is possible to remove the warning from HACS? It's annoying to see project removed...

**Comment by ludeeus** [comment]
Locking this now.
If the author want to see it returned it can be resubmitted.
Or an (active) fork can take its place.
