### ISSUE TITLE
Request for removal of aijayadams/hass-blueair

### ISSUE THREAD

**Issue by qamsys** [hacs/integration#3382]
### Repository

aijayadams/hass-blueair

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

I am submitting this request on behalf of all integration users... The integration has not worked since May 2023 and despite multiple users reporting this to the developer via the project repository (on GitHub), there have been no responses and no work done to resolve issues. The integration appears abandoned.

I suspect more HACS users than those who have raised issues have wasted time with the integration so removing it will at least benefit users in future. If the developer returns to his project, I presume he will quite easily be able to re-submit it when the integration is working.

Kind regards,

Ant.

### Link to issue

https://github.com/aijayadams/hass-blueair/issues/22

**Comment by christopherdriscoll** [comment]
I'm using this add-on with my BlueAir Classic 605 and it's been working mostly fine? I just used in five minutes ago to turn the device on.

Core 2023.12.2
Supervisor 2023.11.6
Operating System 11.2
Frontend 20231208.2

> ### Repository
> 
> aijayadams/hass-blueair
> ### Checklist
> 
>     * [x]  I understand that this form should only be used for repositories that needs to be removed from HACS
> 
>     * [x]  I understand that a bug is not reason enough to have a repository removed
> 
>     * [x]  The repository is currently shipped as a default repository in HACS
> 
>     * [x]  I have tried to get the authors attention to the reason for removal
> 
> 
> ### Why should this be removed?
> 
> I am submitting this request on behalf of all integration users... The integration has not worked since May 2023 and despite multiple users reporting this to the developer via the project repository (on GitHub), there have been no responses and no work done to resolve issues. The integration appears abandoned.
> 
> I suspect more HACS users than those who have raised issues have wasted time with the integration so removing it will at least benefit users in future. If the developer returns to his project, I presume he will quite easily be able to re-submit it when the integration is working.
> 
> Kind regards,
> 
> Ant.
> ### Link to issue
> 
> [aijayadams/hass-blueair#22](https://github.com/aijayadams/hass-blueair/issues/22)
