### ISSUE TITLE
HACS failing to install integration after running install script

### ISSUE THREAD

**Issue by AleAlejandrok** [hacs/integration#3384]
## System Information

version | core-2023.12.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.58-haos-raspi
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.6
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 57.5 GB
disk_used | 13.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.0), Advanced SSH & Web Terminal (16.0.2), Studio Code Server (5.10.0), Zigbee2MQTT (1.34.0-1), Scrypted (18-jammy-full.s6-v0.68.0), ESPHome (2023.11.6), Matter Server (5.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 27, 2023 at 8:02 AM
-- | --
current_recorder_run | December 6, 2023 at 4:06 PM
estimated_db_size | 31.87 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When installing the integration using the directions from https://hacs.xyz/docs/setup/download the integration successfully appears when searching for new integrations. When attempting to add the integration, the github authorization prompt appears a few times with new auth codes on each try until the install errors out.

### Reproduction steps

1. run the wget script on the download page via ssh
2. reboot HA
3. clear cache 
4. attempt to install the HACS integration

(sorry for poor resolution, here is video) 
https://github.com/hacs/integration/assets/79485148/abd6fca1-bffd-411a-9413-8a6cdb1228c1

### Debug logs

```text
https://pastebin.com/pYiSk0UQ
```

### Diagnostics dump

(hacs has failed to install no dump :( )

**Comment by chrism2015a** [comment]
+1

**Comment by tomlangham** [comment]
> Currently the configure part of HACS does not work on the latest version of Home Assistant. Workaround for now, downgrade Home Assistant to 2023.11.3
> 
> The download script has been updated to show this message (note that due to caching it can take a while to populate everywhere):
> 
> > ERROR: HACS will currently not work on 2023.12 versions of Home Assistant, latest known working version is 2023.11.3

Thank you ludeeus, I was wondering what was going on with my HACS install. I assume to get back to the previous version, we're just restoring the last backup?

Thanks,
Tom

**Comment by ludeeus** [comment]
That is the recommended way. For other ways look at the Home Assistant documentation for the installation type you are running.

**Comment by frenck** [comment]
Fixed in #3385

Also, temporary revered in home-assistant/frontend#18939 until we have researched impact.

../Frenck

**Comment by djdarlo** [comment]
How to I implement the this fix?

**Comment by ludeeus** [comment]
There is nothing yet to implement.

**Comment by thejtf** [comment]
+1，I'm having the same issue with authorization jumps!

**Comment by ludeeus** [comment]
Those of you waiting can now update to Home Assistant 2023.12.1. With that version, it will return to working again.
I have adjusted the download script to only block 2023.12.0 (due to cache, it can take some time to populate, so if it still complains about the version, try again a few minutes later).
