### ISSUE TITLE
Install Error waiting for GitHub

### ISSUE THREAD

**Issue by causefx** [hacs/integration#3387]
## System Information

version | core-2023.11.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 4.4.0-210-generic
arch | x86_64
timezone | America/Phoenix
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 19
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 23, 2023 at 12:01 PM
-- | --
current_recorder_run | December 8, 2023 at 10:51 AM
estimated_db_size | 153.89 MiB
database_engine | mysql
database_version | 10.6.13

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When installing the integration I see an error in the logs:

```
AttributeError: 'str' object has no attribute 'get'
2023-12-08 10:59:30.606 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/config_flow.py", line 83, in _wait_for_activation
    response = await self.device.activation(device_code=self._login_device.device_code)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiogithubapi/device.py", line 155, in activation
    if error := response.data.get("error"):
                ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

This causes HA to never pick up that code was verified. 

### Reproduction steps

1.  Install HACS
2. Try and integrate it
3.
...

### Debug logs

```text
na
```

**Comment by ludeeus** [comment]
You have reached a secondary rate limit, probably caused by trying on 2023.12.0 first.
Do it again in 2 hours and it will work.
