### ISSUE TITLE
Installation "Waiting for device activation"

### ISSUE THREAD

**Issue by cstackpole** [hacs/integration#3391]
## System Information

version | core-2023.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.6
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 116.7 GB
disk_used | 6.2 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.0.0), Mosquitto broker (6.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 7, 2023 at 3:39 AM
-- | --
current_recorder_run | December 9, 2023 at 2:07 PM
estimated_db_size | 43.83 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Doesn't matter what system, what brower, or anything I do. After Github authentication it's just stuck spinning "Waiting for device activation".

### Reproduction steps

Hard reboot HA and while it's rebooting - revoke Github token, clear cache. Before loading webpage, SSH into HA `rm -rf hacs` directory in custom_componets. Rerun HACS install script and verify latest version. reboot HA again. Now load web and install HACS, authorize key (get email saying key was authorized), and .... nothing but that stupid "Waiting for device activation". Absolutely nothing I do gets passed that.

### Debug logs

```text
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/hacs/config_flow.py:83
Integration: hacs (documentation, issues)
First occurred: 2:08:25 PM (1 occurrences)
Last logged: 2:08:25 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/config_flow.py", line 83, in _wait_for_activation
    response = await self.device.activation(device_code=self._login_device.device_code)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiogithubapi/device.py", line 155, in activation
    if error := response.data.get("error"):
                ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

**Comment by ludeeus** [comment]
You are rate limited, try again in 2 hours.

**Comment by cstackpole** [comment]
Many hours later, it worked. REALLY wish something had told me that it was rate limited....

Closing the issue. Thank you for the help!
