### ISSUE TITLE
Custom integration validation fails with a too generic reason

### ISSUE THREAD

**Issue by ankohanse** [hacs/integration#3392]
### Describe the issue

Am trying to get the repository for my custom integration accepted by validation hacs/action@main.
However the validation action fails with a 
```
::INFO:: Category: integration
::INFO:: Repository: ankohanse/hass-dab-pumps@refs/heads/main
Error:  <Integration ankohanse/hass-dab-pumps> Repository structure for refs/heads/main is not compliant
```

I've now spend a whole day trying to resolve the reason for this error and am not progressing. Must be someting stupid I am overlooking but I just do not see what it is. Raw logs do not provide additional information. I've compared my repo with the examples in cookiecutter-homeassistant-custom-component and in integration_blueprint and several other repos. Also no useful hits when googling if others encountered this issue and what file/directory caused it for them.

In my opinion, the error message is far too generic. Would be very helpfull to at least know what file/directory in the repository structure is not compliant.

### Link to action run

https://github.com/ankohanse/hass-dab-pumps/actions/runs/7162293892/job/19499054939

### Link to action configuration

https://github.com/ankohanse/hass-dab-pumps/actions/runs/7162323939/workflow

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
It has nothing to go by as the integration itself is not in the expected directory (`custom_components`) but instead in `custom_compoments`, because it can not even start to process it, there is nothing more to describe.
