### ISSUE TITLE
HACS sidebar selection not displaying list of options

### ISSUE THREAD

**Issue by givison1** [hacs/integration#3397]
### Web browser

chrome

### Web browser version

Version 120.0.6099.71 (Official Build) (64-bit)

## System Information

version | core-2023.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4986
Installed Version | 1.33.0
Stage | running
Available Repositories | 1421
Downloaded Repositories | 1
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.6
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 4.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.14.2), OneDrive Backup (2.2.4), Advanced SSH & Web Terminal (17.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 4 December 2023 at 14:59
-- | --
current_recorder_run | 13 December 2023 at 11:02
estimated_db_size | 1.39 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

After installation of HACS integration and authorisation via GitHub, HACS appears in the sidebar. However, when selecting the sidebar button, it just shows the repository name as shown on the image attached. 
![HACS Issue](https://github.com/hacs/integration/assets/153539501/1b15b797-7710-4f05-a259-2722bf6de3f0)

I am expecting it to display access to the HACS integrations, frontend, add-ons and about. Is there a problem with my install, or am I doing something incorrectly.

### Reproduction steps

1. Install HACS
2. Authorise via GitHub
3. Finish installation
4. Restart Home Assistant
5. Select HACS menu item from sidebar
...

### Screenshots

![HACS Issue 2](https://github.com/hacs/integration/assets/153539501/12819c79-db40-4640-b654-c5498fa4de66)
![HACS Issue 3](https://github.com/hacs/integration/assets/153539501/b45e6165-34aa-4c94-8155-eb7f6bde5dc0)

### Javascript logs from your browser console

```text
:8123/api/camera_proxy/camera.garden?authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmOWRhNGY2NDliZjI0YjUxYmJlYjAxMjQ1NDJjYzBjZSIsInBhdGgiOiIvYXBpL2NhbWVyYV9wcm94eS9jYW1lcmEuZ2FyZGVuIiwicGFyYW1zIjpbXSwiaWF0IjoxNzAyNDY0NzE2LCJleHAiOjE3MDI0NjQ3NDZ9.3zpDPLeCuQE71h-3J-PF4fnsAkO4XBU99QTLcpoc1qk&width=980&height=552:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:8123/api/camera_proxy_stream/camera.garden?token=75fc6d5bfb6cd6b7b5ad4f3a0c50f45b8ae89167ec9df735dadede57f20dfa23:1 
        
        
       Failed to load resource: the server responded with a status of 502 (Bad Gateway)
:8123/api/camera_proxy/camera.garden?authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmOWRhNGY2NDliZjI0YjUxYmJlYjAxMjQ1NDJjYzBjZSIsInBhdGgiOiIvYXBpL2NhbWVyYV9wcm94eS9jYW1lcmEuZ2FyZGVuIiwicGFyYW1zIjpbXSwiaWF0IjoxNzAyNDY0NzI2LCJleHAiOjE3MDI0NjQ3NTZ9.nlPDsAbBVBlfh56Z3CPuarSatSco8pnfU7dhCaj89dk&width=980&height=552:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.js:13 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at http://homeassistant.local:8123/frontend_latest/76144.YLWv924eVCo.js:2:5697
index.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8123/api/camera_proxy/camera.garden?token=75fc6d5bfb6cd6b7b5ad4f3a0c50f45b8ae89167ec9df735dadede57f20dfa23&width=80&height=80:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2index.js:13 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at http://homeassistant.local:8123/frontend_latest/76144.YLWv924eVCo.js:2:5697
:8123/api/camera_proxy/camera.garden?token=75fc6d5bfb6cd6b7b5ad4f3a0c50f45b8ae89167ec9df735dadede57f20dfa23&width=80&height=80:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.js:13 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at http://homeassistant.local:8123/frontend_latest/76144.YLWv924eVCo.js:2:5697
camera.garden:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
 [ttyd] websocket connection opened
 [ttyd] WebGL renderer loaded
socket.js:34 WebSocket connection to 'ws://homeassistant.local:8123/api/websocket' failed: 
u @ socket.js:34
Show 1 more frame
Show less
socket.js:34 WebSocket connection to 'ws://homeassistant.local:8123/api/websocket' failed: 
u @ socket.js:34
Show 1 more frame
Show less
socket.js:34 WebSocket connection to 'ws://homeassistant.local:8123/api/websocket' failed: 
u @ socket.js:34
Show 1 more frame
Show less
socket.js:34 WebSocket connection to 'ws://homeassistant.local:8123/api/websocket' failed: 
u @ socket.js:34
Show 1 more frame
Show less
:8123/config/system:1 Uncaught (in promise) Object
:8123/config/system:1 Uncaught (in promise) Object
:8123/config/system:1 Uncaught (in promise) Object
:8123/config/system:1 Uncaught (in promise) Object
:8123/config/system:1 Uncaught (in promise) Object
:8123/config/system:1 Uncaught (in promise) Object
:8123/config/system:1 Uncaught (in promise) Object
:8123/config/system:1 Uncaught (in promise) Object
:8123/config/system:1 Uncaught (in promise) Object
:8123/config/system:1 Uncaught (in promise) Object
:8123/config/system:1 Uncaught (in promise) Object
:8123/config/system:1 Uncaught (in promise) Object
 [ttyd] websocket connection opened
 [ttyd] WebGL renderer loaded
hacs:1 The file at 'http://homeassistant.local:8123/api/diagnostics/config_entry/0640de0c15e97a46888220b8024cb398?authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmOWRhNGY2NDliZjI0YjUxYmJlYjAxMjQ1NDJjYzBjZSIsInBhdGgiOiIvYXBpL2RpYWdub3N0aWNzL2NvbmZpZ19lbnRyeS8wNjQwZGUwYzE1ZTk3YTQ2ODg4MjIwYjgwMjRjYjM5OCIsInBhcmFtcyI6W10sImlhdCI6MTcwMjQ2NzA0OSwiZXhwIjoxNzAyNDY3MDc5fQ.Uemd2Odm8_gS2_ldIm1U9YIVjlfuBLbPCuS9zhB2Jls' was loaded over an insecure connection. This file should be served over HTTPS.
```

### Diagnostics dump

[config_entry-hacs-0640de0c15e97a46888220b8024cb398.json.txt](https://github.com/hacs/integration/files/13660142/config_entry-hacs-0640de0c15e97a46888220b8024cb398.json.txt)

**Comment by ludeeus** [comment]
https://experimental.hacs.xyz/docs/basic/dashboard
