### ISSUE TITLE
You have X Lovelace elements that are not loaded properly in Lovelace - but they work fine

### ISSUE THREAD

**Issue by vaderag** [hacs/integration#3398]
### Web browser

Bing

### Web browser version

119.0.2151.97

## System Information

version | core-2023.12.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1354
Downloaded Repositories | 22
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.6
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 109.3 GB
disk_used | 15.0 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (16.0.2), Advanced SSH & Web Terminal (17.0.0), File editor (5.7.0), Home Assistant Google Drive Backup (0.112.1), Cloudflared (4.2.12), Mosquitto broker (6.4.0), Zigbee2MQTT (1.34.0-1), RTSP Simple Server Add-on (v0.17.6), Z-Wave JS UI (3.0.2), ESPHome (2023.11.6), eufy-security-ws (1.7.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 10
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 8 December 2023 at 19:08
-- | --
current_recorder_run | 14 December 2023 at 11:44
estimated_db_size | 381.46 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.3 (a8c6d45)
-- | --
cloud_online | 0 / 1
local_online | 1 / 1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I understand this message, in some cases, is expected behaviour, but in this case it is not (I don't think)

While it says they’re not enabled, they ARE - I have dashboard that using some of the ones it’s highlighted (as [outlined here](https://hacs.xyz/docs/faq/status_not_loaded/)) yet the requisite frontend integrations work as expected

 If they were broken I’d just uninstall - but they’re working

Oddly - if I access HACS from my REMOTE url (via Cloudflare) then firstly the home page view is different (a list view rather than cards) I see no errors, and if click into the frontend addons that "aren’t working" in HACS and they suddenly appear as working in the local view… not a clue why… possibly something to do with remote being https but local not?

### Reproduction steps

Access Home Assistant on Local - frontend Lovelace cards show not loaded, even though they are

### Screenshots

![image](https://github.com/hacs/integration/assets/17175988/422292f5-87ec-4215-abc2-eb81b4ec32ae)

![image](https://github.com/hacs/integration/assets/17175988/58a5b260-1614-4a23-aeee-824ae6950f9f)

Remote View:
![image](https://github.com/hacs/integration/assets/17175988/b964145b-fb5c-4298-be12-99951c778b79)

### Javascript logs from your browser console

```text
No errors seen
```

### Diagnostics dump

[home-assistant_hacs_2023-12-14T12-04-11.922Z.log](https://github.com/hacs/integration/files/13672962/home-assistant_hacs_2023-12-14T12-04-11.922Z.log)

**Comment by ludeeus** [comment]
You have a stale front-end version,
Clear your browser cache.
It should look like it does when you use your remote.
