### ISSUE TITLE
Download script not working on HA OS due to not having bash or wget or unzip

### ISSUE THREAD

**Issue by washtubs** [hacs/integration#3400]
## System Information

version | core-2023.12.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.58-haos-raspi
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.6
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 28.0 GB
disk_used | 4.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.0), Zigbee2MQTT (1.34.0-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 14, 2023 at 10:19 PM
-- | --
current_recorder_run | December 14, 2023 at 5:19 PM
estimated_db_size | 0.52 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

HA OS does not have wget installed (anymore? I'm not sure, I just started using HA today, but I suspect they changed a bunch of stuff in a recent version) so for starters `wget -O - https://get.hacs.xyz | bash -` did not work. I did manage to cat it over ssh and get the script into `/mnt/data`.

BTW sorry if this is the wrong place for this issue. I was going to post an issue [here](https://github.com/hacs/get/issues) but ended up redirected here.

I did a bit of digging attempting to get the script to run in sh. Note that when running `bash` you can `echo $SHELL` and it shows `/bin/sh`. Eventually got it to work by:

1. Removing the declare lines
2. Found the new location for .HA_VERSION in `/mnt/data/supervisor/homeassistant/.HA_VERSION`. Hard-coded haPath in the script to the directory.
3. Removed the checkRequirement calls for both wget and unzip, neither are installed
4. Repackage hacs.zip as a hacs.tar
5. Instead of wget I downloaded them and cat'd the files over ssh like so: `cat hacs.tar| ssh -p 22222 root@homeassistant.local 'cat - > /mnt/data/hacs.tar'`. They do have curl I just noticed so you could probably just replace wget calls with that.

So my problem is """solved""" but feel free to close this and use what info I gathered to save some time updating your script.

### Reproduction steps

1. I flashed an RPI 4 with the latest home assistant OS today (2023.12.3)
2. SSH as root to the machine.
3. Try to get the install script to run, starting with `wget -O - https://get.hacs.xyz | bash -`

### Debug logs

```text
N/A
```

**Comment by ludeeus** [comment]
https://hacs.xyz/docs/setup/download
As the docs say, you should be using one of the add-ons, not the developer debug access.

**Comment by washtubs** [comment]
I see now. I followed this to set up my SSH beforehand: https://developers.home-assistant.io/docs/operating-system/debugging/

SSH add-on != SSH cause it comes with a whole-ass environment. Welp that was a waste of time...
