### ISSUE TITLE
Add title attribute in update entities

### ISSUE THREAD

**Issue by klatka** [hacs/integration#3401]
## System Information

version | core-2023.12.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4999
Installed Version | 1.33.0
Stage | running
Available Repositories | 1356
Downloaded Repositories | 67
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.6
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 23.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Git pull (7.13.1), Terminal & SSH (9.8.1), MariaDB (2.6.1), Matter Server (5.0.1), Grafana (9.1.1), InfluxDB (4.8.0), PS5 MQTT (1.3.1), Ring-MQTT with Video Streaming (5.6.3), Whisper (1.0.0), Piper (1.4.0), Genie (3.0.0), File editor (5.7.0), WireGuard (0.10.1), Cloudflared (4.2.12), Z-Wave JS UI (3.0.2), ESPHome (2023.11.6), Mosquitto broker (6.4.0), Tautulli (4.0.0), Node-RED (16.0.2), Zigbee2MQTT (1.34.0-1), Silicon Labs Multiprotocol (2.3.2), Let's Encrypt (5.0.6), openWakeWord (1.8.2), Music Assistant BETA (2.0.0b78), Google Assistant SDK (2.5.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 43
views | 12
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 13. November 2023 um 19:53
-- | --
current_recorder_run | 15. Dezember 2023 um 01:28
estimated_db_size | 2488.81 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

These are attributes of `update.hacs_update`:

```
auto_update: false
installed_version: 1.33.0
in_progress: false
latest_version: 1.33.0
release_summary: null
release_url: https://github.com/hacs/integration/releases/1.33.0
skipped_version: null
title: null
entity_picture: https://brands.home-assistant.io/_/hacs/icon.png
friendly_name: HACS update
supported_features: 21
```

Attribute `title` should be `HACS`.

### Reproduction steps

1. Enable experimental features in HACS integration
2. Show attributes of an update sensor created by HACS

### Debug logs

```text
not needed
```

**Comment by ludeeus** [comment]
Why?

**Comment by ludeeus** [comment]
https://developers.home-assistant.io/docs/core/entity/update
That is for when the entity is different from the device (service) which is not the case of the entities provided by HACS.
Adding that will be a bug, as it should not be there.
