### ISSUE TITLE
Different interface?

### ISSUE THREAD

**Issue by RoProAutomation** [hacs/integration#3407]
### System Health details

<img width="1610" alt="Screenshot 2023-12-22 190723" src="https://github.com/hacs/integration/assets/140804866/0fc0cbbf-1dee-40fe-958c-aef726c3360d">

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Hello, please look at the attached image:

Doesn’t HACS look different? I see no Integrations, Frontend and other sections anymore…
I can’t even add any custom integration anymore. If I click on the menu, it just doesn’t do anything.

I have tried reinstalling 10 times and it makes no difference 

### Reproduction steps

1.
2.
3.
...
<img width="1610" alt="Screenshot 2023-12-22 190723" src="https://github.com/hacs/integration/assets/140804866/cb6e1197-5d2c-4152-8d4a-67fb31fac895">

### Debug logs

```text
r
```

**Comment by ludeeus** [comment]
https://experimental.hacs.xyz/docs/basic/dashboard/
