### ISSUE TITLE
Support for new AppDaemon directory structure

### ISSUE THREAD

**Issue by springfall2008** [hacs/integration#3408]
### System Health details

n/a

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

AppDaemon change their default directory to addon_configs/a0d7b954_appdaemon so HACS now installs in the wrong location by default.

Can HACS have an option in hacs.json to specify the install directory so that appdaemon apps can be installed into the right location?

### Reproduction steps

1. Install latests appdaemon
2. Install any appdaemon apps with HACS 
3. Notice the app does not work by default
...

### Debug logs

```text
na
```

**Comment by ludeeus** [comment]
Not possible

**Comment by springfall2008** [comment]
> Not possible

Can you elaborate.

ssh is able to see this directory
appdaemon can see this directory
fileeditor can see this directory

Why can't HACS?

**Comment by ludeeus** [comment]
Because homeasaistant can't.
Home assistant runs HACS.

**Comment by springfall2008** [comment]
> Because homeasaistant can't. Home assistant runs HACS.

So you are saying HACS would have to be an 'add-on' to see this?

**Comment by ludeeus** [comment]
Yes

**Comment by springfall2008** [comment]
> Yes

Understood.

Can I ask your advice, should I try to make my appdaemon app self-updating or do you think changing apps_dir in appdaemon is the best plan?

**Comment by ludeeus** [comment]
I do not use or know appdaemon so can't say.
