### ISSUE TITLE
Hacs can’t be configured

### ISSUE THREAD

**Issue by jacumal** [hacs/integration#3411]
### Describe the issue

Hacs is unavailable because appear a message telling that Hacs can’t be configured. When I try to configure it, another message tells: Only a single configuration of HACS is allowed.

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS bot.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

**Comment by ludeeus** [comment]
Has nothing to do with the bit.
Use the integration template and fill out the required information.
