### ISSUE TITLE
HACS-bot closed relevant bug about the backlog of integrations waiting for review

### ISSUE THREAD

**Issue by binarydev** [hacs/integration#3414]
### Describe the issue

HACS-bot closed https://github.com/hacs/default/issues/1665, which was a valid issue on that repo that was buried due to the auto-closure. Perhaps it's worth considering the allowance of issues related to adding repos there OR add a template to this repo for the use of adding integrations since it already has a template for repo removal.

To the point of that PR though: there are 117 open PRs on the hacs/default repo, with [112 PRs](https://github.com/hacs/default/pulls?q=is%3Aopen+is%3Apr+label%3A%22New+default+repository%22) for new integrations. Is there anyone that can help you to review these in a more efficient way? Would you be willing to accept additional help to review them all? I'd be happy to help in any way that I can. Thanks!

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS bot.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

**Comment by ludeeus** [comment]
No
