### ISSUE TITLE
Why does my HACS not look like it does in the tutorials?

### ISSUE THREAD

**Issue by HACSBronte** [hacs/integration#3420]
### Web browser

Chrome

### Web browser version

.

### System Health details

.

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I followed the instructions and mine looks like this.  I watched a heap of youtube videos on how to install it and theirs looks different.  What did I do wrong?

Thanks

### Reproduction steps

1. Follow the instructions
2. Post issue on github
3.
...

### Screenshots

![image](https://github.com/hacs/integration/assets/154634610/6188886c-25c5-4906-8039-ab5e1f503adf)

### Javascript logs from your browser console

```text
.
```

### Diagnostics dump

.

**Comment by ludeeus** [comment]
https://experimental.hacs.xyz/docs/basic/dashboard/
