### ISSUE TITLE
Remove .vs. removal

### ISSUE THREAD

**Issue by HACS-bank** [hacs/integration#3424]
### Web browser

Companion app

### Web browser version

Current full

### System Health details

N/A

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

"Remove" is used in two menu items with very different meanings. 

I found this very confusing the first time I saw it. 

I don't have a suggestion for a better word; perhaps a longer phrase which says WHERE the removal is FROM would be more clear.

### Reproduction steps

1. Open an integration in HACS
2. Click in top right

### Screenshots

![Screenshot_20240101_100746_Home Assistant](https://github.com/hacs/integration/assets/84039996/4f4c1c06-dda8-4869-ad32-94dce27d3a26)

### Javascript logs from your browser console

```text
N/A
```

**Comment by HACS-bank** [comment]
Integration version:	1.33.0
Frontend version:	20220906112053

**Comment by ludeeus** [comment]
What is the bug?
You say 2 but mentions only 1?
This one also open a confirmation dialog

**Comment by HACS-bank** [comment]
"Remove" means discard the download from this HA/HACS instance

"Request removal" means report the supplier to the HACS team.

But for a first time user, the Request removal option could equally mean to request remove from this instance. 

I found this confusing, and for first time users, clicking each to see what it does is scary. I am very happy to try every option just to see, but I am told that most people don't dare do that :)

**Comment by ludeeus** [comment]
ah, okey 👍 

No matter what I put in here, some will be confused.
For now Ill keep it as-is.
