### ISSUE TITLE
Validation will only use the latest release version - not the branch I work in?

### ISSUE THREAD

**Issue by exetico** [hacs/integration#3428]
### Describe the issue

I noticed that the validation would only work with the latest release, and **not** the branch I'm working in.

Debug output:

```log
##[debug] <Plugin ExperienceLovelace/ha-floorplan> Getting documentation for version=1.0.41,filename=README.md
##[debug] Trying to download https://raw.githubusercontent.com/ExperienceLovelace/ha-floorplan/1.0.41/README.md
::INFO:: <Validation description> completed
::INFO:: <Validation topics> completed
::INFO:: <Validation information> completed
::INFO:: <Validation issues> completed
::INFO:: <Validation archived> completed
Error:  <Validation images> failed:  The repository does not have images in the Readme file (More info: https://hacs.xyz/docs/publish/include#check-images )
```

Here's the debug output where I'm working in a branch, _not tired to any specific release_.

I can see some work has been done related to #3362 in #3363, but I don't understand why the validation is tired to the latest release? 

_I even ended up trying another README.md from `tonyroberts/scheduler-card/main/README.md`, before I noticed the debug-run option.

As a developer I expected the run to validate the current repo. Not trying to fetch the latest release. I couldn't find anything related to that in the [docs](https://hacs.xyz/docs/publish/action/), so I'm not sure if I have missed something?

Have I originally implemented the validation it in a wrong way, or?

### Link to action run

https://github.com/ExperienceLovelace/ha-floorplan/actions/runs/7385800876/job/20091413836

### Link to action configuration

https://github.com/ExperienceLovelace/ha-floorplan/blob/hacs-verification-issues/.github/workflows/hacs-validation.yaml

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
It seems to be limited to the doc check, the rest is using the branch <https://github.com/ExperienceLovelace/ha-floorplan/actions/runs/7385800876/job/20091413836#step:4:26>
Ill take a look later today.

**Comment by exetico** [comment]
_I've made a release with the README.md in the root folder, so the problem are not vislble in the master branch anymore._

Thanks ludeeus 😄 !
