### ISSUE TITLE
UI 2.0  Updated field reporting bogus value

### ISSUE THREAD

**Issue by dkebler** [hacs/integration#3430]
### Web browser

chromium

### Web browser version

Version 119.0.6045.159 (Official Build) Arch Linux (64-bit)

## System Information

version | core-2024.1.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1371
Downloaded Repositories | 1
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 116.7 GB
disk_used | 6.1 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.8.1), Studio Code Server (5.14.2), EMQX (0.3.0), Node-RED (16.0.2), Caddy 2 (1.5.4), AdGuard Home (5.0.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 24, 2023 at 10:04 PM
-- | --
current_recorder_run | January 3, 2024 at 12:18 PM
estimated_db_size | 3.38 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Either UI is not getting proper updated data or backend data is bad but it is showing "updated" as 55 years ago for all themes.  I have cleared cache, tried in another instance of chromium.  Same issue

### Reproduction steps

1. Install HACS
2. Filter for Themes,  search for `theme`
3. See obvious problem
...

### Screenshots

![image](https://github.com/hacs/integration/assets/1316185/67f63dfa-97d4-4cdd-b40f-459e690be2f8)

### Javascript logs from your browser console

```text
none,

no errors in Network tab either
```

### Diagnostics dump

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.1.0",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/Los_Angeles",
    "os_name": "Linux",
    "os_version": "6.1.63-haos",
    "supervisor": "2023.12.0",
    "host_os": "Home Assistant OS 11.2",
    "docker_version": "24.0.7",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "hacs",
    "name": "HACS",
    "codeowners": [
      "@ludeeus"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "websocket_api",
      "frontend",
      "persistent_notification",
      "lovelace",
      "repairs"
    ],
    "documentation": "https://hacs.xyz/docs/configuration/start",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/hacs/integration/issues",
    "requirements": [
      "aiogithubapi>=22.10.1"
    ],
    "version": "1.33.0",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "18522f220d70b68a20be24dc5f329e28",
      "version": 1,
      "minor_version": 1,
      "domain": "hacs",
      "title": "",
      "data": {
        "token": "**REDACTED**"
      },
      "options": {
        "experimental": true
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "hacs": {
      "stage": "running",
      "version": "1.33.0",
      "disabled_reason": null,
      "new": false,
      "startup": false,
      "categories": [
        "template",
        "plugin",
        "integration",
        "theme"
      ],
      "renamed_repositories": {},
      "archived_repositories": [],
      "ignored_repositories": [],
      "lovelace_mode": "storage",
      "configuration": {
        "appdaemon": false,
        "country": "ALL",
        "debug": false,
        "dev": false,
        "experimental": true,
        "netdaemon": false,
        "python_script": false,
        "release_limit": 5,
        "theme": false
      }
    },
    "custom_repositories": [],
    "repositories": [
      {
        "data": {
          "archived": false,
          "authors": [
            "@ludeeus"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "main",
          "description": "HACS gives you a powerful UI to handle downloads of all your custom needs.",
          "domain": "hacs",
          "downloads": 380969,
          "etag_repository": "W/\"c018c1002abf9970086acb67fdd4f2fbf2db800566c213d4ea13d4c26d5abfd8\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "hacs/integration",
          "hide": false,
          "has_issues": true,
          "id": "172733314",
          "installed_commit": "94e66ed",
          "installed_version": "1.33.0",
          "installed": true,
          "last_commit": "94e66ed",
          "last_updated": "2024-01-02T19:11:36Z",
          "last_version": "1.33.0",
          "manifest_name": "HACS",
          "new": false,
          "open_issues": 16,
          "published_tags": [
            "1.33.0",
            "1.32.1",
            "1.32.0",
            "1.31.0",
            "1.30.1"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 4223,
          "topics": [
            "community",
            "package-manager"
          ]
        },
        "integration_manifest": {
          "domain": "hacs",
          "name": "HACS",
          "codeowners": [
            "@ludeeus"
          ],
          "config_flow": true,
          "dependencies": [
            "http",
            "websocket_api",
            "frontend",
            "persistent_notification",
            "lovelace",
            "repairs"
          ],
          "documentation": "https://hacs.xyz/docs/configuration/start",
          "iot_class": "cloud_polling",
          "issue_tracker": "https://github.com/hacs/integration/issues",
          "requirements": [
            "aiogithubapi>=22.10.1"
          ],
          "version": "0.0.0"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "hacs.zip",
          "hacs": "0.19.0",
          "hide_default_branch": true,
          "homeassistant": "2023.6.0",
          "manifest": {
            "name": "HACS",
            "zip_release": true,
            "hide_default_branch": true,
            "homeassistant": "2023.6.0",
            "hacs": "0.19.0",
            "filename": "hacs.zip"
          },
          "name": "HACS",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": "1.33.0",
        "paths": {
          "localpath": "/config/custom_components/hacs",
          "local": "/config/custom_components/hacs",
          "remote": "custom_components/hacs"
        }
      }
    ],
    "rate_limit": {
      "resources": {
        "core": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1704318542
        },
        "search": {
          "limit": 30,
          "used": 0,
          "remaining": 30,
          "reset": 1704315002
        },
        "graphql": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1704318542
        },
        "integration_manifest": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1704318542
        },
        "source_import": {
          "limit": 100,
          "used": 0,
          "remaining": 100,
          "reset": 1704315002
        },
        "code_scanning_upload": {
          "limit": 1000,
          "used": 0,
          "remaining": 1000,
          "reset": 1704318542
        },
        "actions_runner_registration": {
          "limit": 10000,
          "used": 0,
          "remaining": 10000,
          "reset": 1704318542
        },
        "scim": {
          "limit": 15000,
          "used": 0,
          "remaining": 15000,
          "reset": 1704318542
        }
      },
      "rate": {
        "limit": 5000,
        "used": 0,
        "remaining": 5000,
        "reset": 1704318542
      }
    }
  }
}

**Comment by ludeeus** [comment]
Seems there was issues fetching data, restart with debug logs enabled and post those.

**Comment by dkebler** [comment]
FYI, Once a theme as been downloaded/installed the fields including updated seem correct.

[home-assistant_hacs_2024-01-03T23-20-24.620Z.log](https://github.com/hacs/integration/files/13824315/home-assistant_hacs_2024-01-03T23-20-24.620Z.log)

**Comment by ludeeus** [comment]
There is a lot missing from those logs, it does not seem like you have restarted with this <https://hacs.xyz/docs/basic/logs>

**Comment by dkebler** [comment]
guess I don't know how to use your debug logging.  When I click enable on the integration page it does so.  Then I loaded the page in question. Then when I click again it asks to save a file which I then posted here which I assume is the debug log.  Otherwise I see no way to keep that enabled and yet access the logs.   I'll need more precise instructions obviously.

**Comment by ludeeus** [comment]
Look at the posted link.

**Comment by dkebler** [comment]
ok, but what's the point if having that setting in the integration UI if I have to manually edit my yaml?
![image](https://github.com/hacs/integration/assets/1316185/e4209fbe-260e-49d5-ba68-a5e0d586cfe5)

**Comment by dkebler** [comment]
I just updated to latest core 2024.x and now the issue is resolved
