### ISSUE TITLE
Error visual UI HACS

### ISSUE THREAD

**Issue by Spiderpork85** [hacs/integration#3432]
### Web browser

x

### Web browser version

x

### System Health details

x

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

i have that ui 
![Screenshot 2024-01-05 014937](https://github.com/hacs/integration/assets/61102810/fee0874d-ec9d-4919-b84a-04fde239a05c)

### Reproduction steps

1.
2.
3.
...

### Screenshots

![Screenshot 2024-01-05 014937](https://github.com/hacs/integration/assets/61102810/5493d36a-f423-4104-9923-717bd65543c6)

### Javascript logs from your browser console

```text
x
```

**Comment by Spiderpork85** [comment]
i don't see the normal ui where i can search hacs integration, can help me ?

**Comment by tjorim** [comment]
Go back to the previous page, you can just search at the top. Do not click the HACS repository. https://experimental.hacs.xyz/docs/basic/dashboard/
