### ISSUE TITLE
Entity None (<class 'custom_components.hacs.update.HacsRepositoryUpdateEntity'>) is using deprecated

### ISSUE THREAD

**Issue by misa1515** [hacs/integration#3441]
### System Health details

Core 2024.1.2
Supervisor 2023.12.0
Operating System 11.4
Frontend 20240104.0

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Found in HA log

![image](https://github.com/hacs/integration/assets/61636045/6d51a554-aa78-4834-97a9-8032d0140821)

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
not relevant
```

**Comment by misa1515** [comment]
@ludeeus it was reported wrongly, or something are missing?

**Comment by ludeeus** [comment]
Duplicate of resolved issue.
