### ISSUE TITLE
BETA: "SKIP Restart" Needed After Repository Update

### ISSUE THREAD

**Issue by xip0rt** [hacs/integration#3442]
### System Health details

<html><body>

Version | core-2024.1.1
-- | --
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.11.6
Operating System Family | Linux
Operating System Version | 6.1.21-v8+
CPU Architecture | aarch64

</body>
</html>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

(NOTE: BETA ENABLED)

After updating a repository that requires a restart to take effect, a notification appears under settings menu reminding you to restart (with the orange notification icon). The only way to clear this is to restart HA.

Many times I don't really care about the latest updates and do not plan on restarting (probably wait for the next HA release). But I cannot get rid of the notification, as the only option the notification gives is to restart now (which clears it upon restart).

We need an "ignore" action.

### Reproduction steps

1. Enable beta
2. Update a non-frontend repository
3. View notification on /config
...

### Debug logs

```text
*
```

**Comment by ludeeus** [comment]
You should not ignore that, once you have updated the files, restart.
If you do not it can lead to problems with missing references.
If you really want to delay restarting, don't update things u till tomorrow can do it.
