### ISSUE TITLE
No integrations or "Add-ins"  listed

### ISSUE THREAD

**Issue by riaandeyzel** [hacs/integration#3446]
### Web browser

Google Chrome

### Web browser version

120.0.6099.210

## System Information

version | core-2024.1.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Africa/Johannesburg
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.33.0
Stage | running
Available Repositories | 1443
Downloaded Repositories | 1
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 233.8 GB
disk_used | 12.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.2.0), File editor (5.7.0), Duck DNS (1.15.0), ESPHome (2023.12.5), openWakeWord (1.8.2), Terminal & SSH (9.8.1), NGINX Home Assistant SSL proxy (3.7.0), Assist Microphone (1.0.0), eWeLink Smart Home (1.4.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 0
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3 January 2024 at 09:25
-- | --
current_recorder_run | 12 January 2024 at 07:54
estimated_db_size | 2477.94 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I do not see any apps, "add-ons" or integrations  in HACS, only anbjnfo page.

### Reproduction steps

1. Reinstalled HACS
2.
3.
...

### Screenshots

![Screenshot_20240112-083933_Gallery](https://github.com/hacs/integration/assets/4225538/6cc95af3-66b5-483f-aeb3-913e392bc618)

### Javascript logs from your browser console

```text
Not relevant
```

**Comment by ludeeus** [comment]
https://experimental.hacs.xyz/docs/basic/dashboard/
