### ISSUE TITLE
Update entities do not work

### ISSUE THREAD

**Issue by sdschramm** [hacs/integration#3453]
## System Information

version | core-2024.1.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.71-haos
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4992
Installed Version | 1.33.0
Stage | running
Available Repositories | 1382
Downloaded Repositories | 21
HACS Data | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 116.7 GB
disk_used | 14.8 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.2.0), File editor (5.7.0), Node-RED (17.0.2), Terminal & SSH (9.8.1), Home Assistant Google Drive Backup (0.112.1), Z-Wave JS UI (3.1.0), Mosquitto broker (6.4.0), Zigbee2MQTT (1.35.1-1), VLC (0.3.0), Firefox (1.0.7), Network UPS Tools (0.13.0), Whisper (1.0.2), Piper (1.4.0)

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I have [experimental features](https://hacs.xyz/docs/configuration/options#options) enabled so that I can use the [Update entities](https://hacs.xyz/docs/entities/update_entities/). When I call the service `homeassistant.update_entity` and set the target to something, for example: `entity_id: update.mushroom_update` it does not do anyhting. 

### Reproduction steps

1. Enable experimental features
2. Go to Developer Tools > Services
3. Call the service `homeassistant.update_entity` and set the target to something, for example: `entity_id: update.mushroom_update
4. Service is called successfully but update does not occur.

### Debug logs

```text
Nothing related to this appears.
```

**Comment by starox** [comment]
I am not the author of the bug.
I was chasing for another bug (experimental mode ui worked only once ...)  
I use the latest docker container for hass:  

`docker.io/homeassistant/home-assistant  latest      288df4253337  4 days ago    2.09 GB`

I noticed a log which seems related:

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1524
First occurred: 22:36:34 (3 occurrences)
Last logged: 22:36:34

Entity None (<class 'custom_components.hacs.update.HacsRepositoryUpdateEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <UpdateEntityFeature.INSTALL|PROGRESS|RELEASE_NOTES: 21>, please create a bug report at https://github.com/hacs/integration/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
```

**Comment by ludeeus** [comment]
Not related. See recent closed issues.
Closing this as required information was not provided, and this is working on all setups.
