### ISSUE TITLE
Reword "No Add-Ons in HACS"

### ISSUE THREAD

**Issue by amizzo87** [hacs/integration#3461]
### Describe the issue

The documentation clearly states:

"**You are aware that there are no add-ons in HACS**" which seems...misleading at best. 

Isn't that the explicit purpose of HACS...? What am I missing here?

**Comment by ludeeus** [comment]
No
https://www.home-assistant.io/docs/glossary/#add-on

**Comment by ludeeus** [comment]
No it is not.
HACS have integrations, front-end resources, themes, appdaemon apps, Python scripts and templates.
No add-ons, add-ons are customized docked containers that can only be managed by the Home Assistant supervisor.

**Comment by amizzo87** [comment]
Gotcha. Ok thank you, I was not aware of that distinction re: dockerized containers.
