### ISSUE TITLE
UI looks different from documented UI

### ISSUE THREAD

**Issue by arnie257** [hacs/integration#3464]
### Web browser

chrome

### Web browser version

120.0.6099.224

## System Information

version | core-2024.1.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.71-haos
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1383
Downloaded Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 13.6 GB
disk_used | 5.4 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.2.0), File editor (5.7.0), Mosquitto broker (6.4.0), Terminal & SSH (9.8.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 0
views | 15
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 9 januari 2024 om 19:03
-- | --
current_recorder_run | 18 januari 2024 om 17:38
estimated_db_size | 113.17 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

downloaded the hacs library and integrated by the hacs integration. The resulting menu looks like the screenshot below.

### Reproduction steps

1. I followed exactly the steps as described in https://hacs.xyz/docs/configuration/basic except didn't enable experimental features. The result of the hacs download is in second screenshot 
2.
3.
...

### Screenshots

![image](https://github.com/hacs/integration/assets/157041136/287ac8e3-3434-476e-960b-2ad66eefc2c2)
![image](https://github.com/hacs/integration/assets/157041136/036f6ec5-829a-4ab0-92e3-5a7dc08edbb1)

### Javascript logs from your browser console

```text
couldn't find javascript logs
```

### Diagnostics dump

[config_entry-hacs-490028f1c246091ad44ddfc5b329b4ca.json.txt](https://github.com/hacs/integration/files/13980886/config_entry-hacs-490028f1c246091ad44ddfc5b329b4ca.json.txt)

**Comment by ludeeus** [comment]
You enabled experimental, there is no way you can see that if you did not.
As that is no longer enabled I assume you did that initially, then you removed it and tried again without it.
Clear your browser cache.
Or re-enable experimental, this is the docs: https://experimental.hacs.xyz/
