### ISSUE TITLE
Error when downloading some integrations

### ISSUE THREAD

**Issue by pcartwright81** [hacs/integration#3465]
## System Information

version | core-2024.2.0.dev20240118
-- | --
installation_type | Home Assistant OS
dev | true
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.73-haos
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4902
Installed Version | 1.33.0
Stage | running
Available Repositories | 1384
Downloaded Repositories | 7
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 28, 2024 at 7:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-3.ui.nabu.casa
certificate_status | ready
instance_id | 49a2b7c79e304a5496161e0c7954006d
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5.dev20240117
-- | --
update_channel | dev
supervisor_version | supervisor-2024.01.0.dev1702
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 457.7 GB
disk_used | 12.5 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Dnsmasq (1.6.0), Duck DNS (1.15.0), Home Assistant Google Drive Backup (0.112.1), Samba share (12.2.0), phpMyAdmin (0.9.1), MariaDB (2.6.1), ESPHome (2023.12.7), Advanced SSH & Web Terminal (17.0.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 3
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 8, 2024 at 7:47 PM
-- | --
current_recorder_run | January 18, 2024 at 8:05 PM
estimated_db_size | 407.69 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Can not seem to download certain integrations, but some still work.  The url works in chrome.  Started roughly 2 weeks ago.
Working example 
Alexa Media Player
Non-Working
Kia Uvo / Hyundai Bluelink
SmartThinQ LGE Sensors

### Reproduction steps

1. Open hacs and search
2. Click download and see spinner
3. View log

### Debug logs

```text
2024-01-18 20:24:44.654 DEBUG (MainThread) [custom_components.hacs] <Integration Hyundai-Kia-Connect/kia_uvo> Getting repository information
2024-01-18 20:24:45.189 DEBUG (MainThread) [custom_components.hacs] <Integration Hyundai-Kia-Connect/kia_uvo> Running checks against v2.18.2
2024-01-18 20:24:45.732 DEBUG (MainThread) [custom_components.hacs] <Integration Hyundai-Kia-Connect/kia_uvo> Getting repository information
2024-01-18 20:24:45.786 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
2024-01-18 20:24:45.832 DEBUG (MainThread) [custom_components.hacs] <HACSStore async_save_to_store> Did not store data for 'hacs.data'. Content did not change
2024-01-18 20:24:46.335 DEBUG (MainThread) [custom_components.hacs] <Integration Hyundai-Kia-Connect/kia_uvo> Running checks against v2.18.2
2024-01-18 20:24:46.943 INFO (MainThread) [custom_components.hacs] <Integration Hyundai-Kia-Connect/kia_uvo> Running pre installation steps
2024-01-18 20:24:46.943 INFO (MainThread) [custom_components.hacs] <Integration Hyundai-Kia-Connect/kia_uvo> Pre installation steps completed
2024-01-18 20:24:46.944 INFO (MainThread) [custom_components.hacs] <Integration Hyundai-Kia-Connect/kia_uvo> Running installation steps
2024-01-18 20:24:46.944 DEBUG (MainThread) [custom_components.hacs] <Integration Hyundai-Kia-Connect/kia_uvo> Getting repository information
2024-01-18 20:24:47.474 DEBUG (MainThread) [custom_components.hacs] <Integration Hyundai-Kia-Connect/kia_uvo> Running checks against v2.18.2
2024-01-18 20:24:48.056 DEBUG (MainThread) [custom_components.hacs] <Integration Hyundai-Kia-Connect/kia_uvo> Local path is set to /config/custom_components/kia_uvo
2024-01-18 20:24:48.056 DEBUG (MainThread) [custom_components.hacs] <Integration Hyundai-Kia-Connect/kia_uvo> Remote path is set to custom_components/kia_uvo
2024-01-18 20:24:48.057 INFO (MainThread) [custom_components.hacs] <Integration Hyundai-Kia-Connect/kia_uvo> Trying experimental download
2024-01-18 20:24:48.057 DEBUG (MainThread) [custom_components.hacs] Downloading https://api.github.com/repos/Hyundai-Kia-Connect/kia_uvo/zipball/v2.18.2
2024-01-18 20:24:48.527 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140203102360768] Error handling message: Unknown error (unknown_error) Patrick Cartwright from 192.168.1.2 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
await func(hass, connection, msg)
File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
await repository.async_install()
File "/config/custom_components/hacs/repositories/base.py", line 899, in async_install
await self.async_install_repository()
File "/config/custom_components/hacs/repositories/base.py", line 982, in async_install_repository
await self.download_content()
File "/config/custom_components/hacs/repositories/base.py", line 629, in download_content
await self.download_repository_zip()
File "/config/custom_components/hacs/repositories/base.py", line 686, in download_repository_zip
zip_file.extractall(self.content.path.local, extractable)
File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1721, in extractall
self._extract_member(zipinfo, path, pwd)
File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1762, in _extract_member
raise ValueError("Empty filename.")
ValueError: Empty filename.
2024-01-18 20:26:48.053 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2024-01-18 20:26:48.053 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2024-01-18 20:27:56.972 DEBUG (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> Getting repository information
2024-01-18 20:27:57.598 DEBUG (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> Running checks against v0.36.2
2024-01-18 20:28:00.559 DEBUG (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> Getting repository information
2024-01-18 20:28:01.029 DEBUG (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> Running checks against v0.36.2
2024-01-18 20:28:01.616 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
2024-01-18 20:28:01.661 DEBUG (MainThread) [custom_components.hacs] <HACSStore async_save_to_store> Did not store data for 'hacs.data'. Content did not change
2024-01-18 20:28:02.498 DEBUG (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> Getting repository information
2024-01-18 20:28:02.996 DEBUG (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> Running checks against v0.36.2
2024-01-18 20:28:03.582 INFO (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> Running pre installation steps
2024-01-18 20:28:03.582 INFO (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> Pre installation steps completed
2024-01-18 20:28:03.582 INFO (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> Running installation steps
2024-01-18 20:28:03.583 DEBUG (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> Getting repository information
2024-01-18 20:28:04.092 DEBUG (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> Running checks against v0.36.2
2024-01-18 20:28:04.736 DEBUG (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> Local path is set to /config/custom_components/smartthinq_sensors
2024-01-18 20:28:04.737 DEBUG (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> Remote path is set to custom_components/smartthinq_sensors
2024-01-18 20:28:04.737 INFO (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> Trying experimental download
2024-01-18 20:28:04.737 DEBUG (MainThread) [custom_components.hacs] Downloading https://api.github.com/repos/ollo69/ha-smartthinq-sensors/zipball/v0.36.2
2024-01-18 20:28:05.378 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140203102360768] Error handling message: Unknown error (unknown_error) Patrick Cartwright from 192.168.1.2 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
await func(hass, connection, msg)
File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
await repository.async_install()
File "/config/custom_components/hacs/repositories/base.py", line 899, in async_install
await self.async_install_repository()
File "/config/custom_components/hacs/repositories/base.py", line 982, in async_install_repository
await self.download_content()
File "/config/custom_components/hacs/repositories/base.py", line 629, in download_content
await self.download_repository_zip()
File "/config/custom_components/hacs/repositories/base.py", line 686, in download_repository_zip
zip_file.extractall(self.content.path.local, extractable)
File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1721, in extractall
self._extract_member(zipinfo, path, pwd)
File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1762, in _extract_member
raise ValueError("Empty filename.")
ValueError: Empty filename.
```

### Diagnostics dump

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.2.0.dev20240118",
    "dev": true,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.1",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/Chicago",
    "os_name": "Linux",
    "os_version": "6.1.73-haos",
    "supervisor": "2024.01.0.dev1702",
    "host_os": "Home Assistant OS 11.5.dev20240117",
    "docker_version": "24.0.7",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "emporia_vue": {
      "version": "0.8.3",
      "requirements": [
        "pyemvue==0.17.1"
      ]
    },
    "mail_and_packages": {
      "version": "0.3.19",
      "requirements": [
        "beautifulsoup4",
        "Pillow>=9.0"
      ]
    },
    "holidays": {
      "version": "1.9.10",
      "requirements": [
        "python-dateutil>=2.8.2",
        "holidays>=0.35"
      ]
    }
  },
  "integration_manifest": {
    "domain": "hacs",
    "name": "HACS",
    "codeowners": [
      "@ludeeus"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "websocket_api",
      "frontend",
      "persistent_notification",
      "lovelace",
      "repairs"
    ],
    "documentation": "https://hacs.xyz/docs/configuration/start",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/hacs/integration/issues",
    "requirements": [
      "aiogithubapi>=22.10.1"
    ],
    "version": "1.33.0",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "e53d4b8792073ab14e368200510685f0",
      "version": 1,
      "minor_version": 1,
      "domain": "hacs",
      "title": "",
      "data": {
        "token": "**REDACTED**"
      },
      "options": {
        "experimental": true
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "hacs": {
      "stage": "running",
      "version": "1.33.0",
      "disabled_reason": null,
      "new": false,
      "startup": false,
      "categories": [
        "integration",
        "theme",
        "template",
        "plugin"
      ],
      "renamed_repositories": {
        "xMrVizzy/Philips-AirPurifier": "kraineff/philips-airpurifier",
        "scottyphillips/mitsubishi_hass": "scottyphillips/echonetlite_homeassistant",
        "idittansikte/bootstrap-grid-card": "ownbee/bootstrap-grid-card",
        "custom-components/blueprint": "custom-components/integration_blueprint",
        "marksie1988/atomic-calendar-revive": "totaldebug/atomic-calendar-revive",
        "PepegaBruh/CryptoTracker": "BigNocciolino/CryptoTracker",
        "9a4gl/hass-peltec": "9a4gl/hass-centrometal-boiler",
        "78wesley/Darkish-Theme": "78wesley/Home-Assistant-Darkish-Theme",
        "KartoffelToby/ai_thermostat": "KartoffelToby/better_thermostat",
        "nbogojevic/homeassistant-midea-dehumidifier-lan": "nbogojevic/homeassistant-midea-air-appliances-lan",
        "nikrolls/homeassistant-goldair-climate": "nicole-ashley/homeassistant-goldair-climate",
        "DarkSir23/sensor.mylar": "WillowMist/sensor.mylar",
        "rj175/home-assistant-aws-codepipeline": "ohheyrj/home-assistant-aws-codepipeline",
        "ulic75/power-distribution-card": "ulic75/power-flow-card",
        "wills106/homsassistant-solax-modbus": "wills106/homeassistant-solax-modbus",
        "dmitry-k/yandex_smart_home": "dext0r/yandex_smart_home",
        "uvjustin/alarmdotcom": "pyalarmdotcom/alarmdotcom",
        "wernerhp/ha_integration_load_shedding": "wernerhp/ha.integration.load_shedding",
        "fuatakgun/kia_uvo": "Hyundai-Kia-Connect/kia_uvo",
        "jadson179/consul": "gtjadsonsantos/consul"
      },
      "archived_repositories": [
        "georgezhao2010/climate_ewelink",
        "maykar/plex_assistant",
        "custom-cards/state-element",
        "custom-components/sensor.sonarr_upcoming_media",
        "KTibow/lovelace-light-soft-ui-theme",
        "custom-components/sensor.tautulli",
        "custom-components/wienerlinien",
        "natekspencer/hacs-litterrobot",
        "custom-cards/favicon-counter",
        "custom-cards/state-attribute-element",
        "custom-cards/upcoming-media-card",
        "custom-components/custom_components",
        "maykar/lovelace-swipe-navigation",
        "DCSBL/ha-homewizard-energy",
        "custom-components/templatesensor",
        "DavidMStraub/homeassistant-homeconnect",
        "lukich48/hass_mqtt_template_switch",
        "marrobHD/firetv-card",
        "custom-components/sensor.plex_recently_added",
        "custom-cards/text-element",
        "maykar/kiosk-mode",
        "atomic7777/atomic_calendar",
        "custom-components/sensor.custom_components",
        "briis/smartweather",
        "custom-components/sensor.radarr_upcoming_media",
        "frenck/home-assistant-theme-outline",
        "heinoldenhuis/home_assistant_omnik_solar",
        "custom-components/unsplash",
        "PTST/O365-HomeAssistant",
        "Cyr-ius/hass-hue-service-advanced",
        "clayauld/lovelace-darksky-card",
        "DSorlov/hasl-platform",
        "custom-components/combined",
        "spycle/microbot_push",
        "dr1rrb/ha-twinkly",
        "ThomasPrior/EthermineInfo",
        "custom-components/sensor.yandex_maps",
        "ppanagiotis/pymusiccast",
        "KoljaWindeler/kaco",
        "eavanvalkenburg/sia",
        "jensweimann/awb",
        "iantrich/aftership-card",
        "custom-components/sensor.custom_aftership",
        "Kraineff/philips-airpurifier",
        "custom-cards/username-element",
        "Michsior14/ha-laser-egg",
        "Cyr-ius/hass-cozytouch",
        "KTibow/lovelace-dark-soft-ui-theme",
        "GeorgeSG/lovelace-folder-card",
        "custom-components/breaking_changes",
        "mampfes/hacs_wiffi",
        "Sholofly/arrisdcx960",
        "NemesisRE/lovelace-swipe-navigation",
        "estevez-dev/extended-banner-card",
        "custom-components/config_check",
        "pilotak/homeassistant-mikrotik",
        "marcomow/ble-bulb-card",
        "custom-cards/ext-weblink",
        "nagyrobi/home-assistant-custom-components-pfsense-gateways",
        "pippyn/Home-Assistant-Sensor-Groningen-Afvalwijzer"
      ],
      "ignored_repositories": [],
      "lovelace_mode": "storage",
      "configuration": {
        "appdaemon": false,
        "country": "ALL",
        "debug": false,
        "dev": false,
        "experimental": true,
        "netdaemon": false,
        "python_script": false,
        "release_limit": 5,
        "theme": false
      }
    },
    "custom_repositories": [
      "magico13/ha-emporia-vue",
      "moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card"
    ],
    "repositories": [
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "config_flow": false,
          "default_branch": null,
          "description": "\ud83d\udd39Automatically populate the entities-list of lovelace cards",
          "domain": null,
          "downloads": 0,
          "etag_repository": "W/\"94b39bd3ed3c7bcb6024cbeb2fb474e0f6f87819dbf6bafcd12f23ecc3d7a049\"",
          "etag_releases": null,
          "file_name": null,
          "first_install": false,
          "full_name": "thomasloven/lovelace-auto-entities",
          "hide": false,
          "has_issues": true,
          "id": "167744584",
          "installed_commit": "ddff759",
          "installed_version": "1.12.1",
          "installed": true,
          "last_commit": "ddff759",
          "last_updated": "2024-01-09T10:33:23Z",
          "last_version": "1.12.1",
          "manifest_name": null,
          "new": false,
          "open_issues": 0,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": true,
          "stargazers_count": 1037,
          "topics": []
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2022.3.0",
          "manifest": {
            "name": "auto-entities",
            "render_readme": true,
            "homeassistant": "2022.3.0"
          },
          "name": "auto-entities",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": null,
        "paths": {
          "localpath": "/config/www/community/lovelace-auto-entities",
          "local": "/config/www/community/lovelace-auto-entities",
          "remote": null
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "config_flow": false,
          "default_branch": null,
          "description": "\ud83d\udd39 Add sliders to entity cards",
          "domain": null,
          "downloads": 0,
          "etag_repository": "W/\"2977fad56ccef66bde9b353389b1c412bb92422212519d0952e157b37a6b08fb\"",
          "etag_releases": null,
          "file_name": null,
          "first_install": false,
          "full_name": "thomasloven/lovelace-slider-entity-row",
          "hide": false,
          "has_issues": true,
          "id": "144899700",
          "installed_commit": "7082021",
          "installed_version": "17.4.1",
          "installed": true,
          "last_commit": "7082021",
          "last_updated": "2023-12-25T23:36:54Z",
          "last_version": "17.4.1",
          "manifest_name": null,
          "new": false,
          "open_issues": 0,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 763,
          "topics": []
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": null,
          "manifest": {
            "name": "slider-entity-row",
            "render_readme": true
          },
          "name": "slider-entity-row",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": null,
        "paths": {
          "localpath": "/config/www/community/lovelace-slider-entity-row",
          "local": "/config/www/community/lovelace-slider-entity-row",
          "remote": null
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@magico13"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "Home Assistant Integration for Emporia Vue Energy Monitor",
          "domain": "emporia_vue",
          "downloads": 0,
          "etag_repository": "W/\"1f558befa5719eb87dcb4388ac43d2d75bfd62ee390cf19a061ceaf39ed50d8e\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "magico13/ha-emporia-vue",
          "hide": false,
          "has_issues": true,
          "id": "247362100",
          "installed_commit": "170d0af",
          "installed_version": "v0.8.3",
          "installed": true,
          "last_commit": "2853fd9",
          "last_updated": "2023-11-09T23:14:34Z",
          "last_version": "v0.8.3",
          "manifest_name": "Emporia Vue",
          "new": false,
          "open_issues": 0,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": true,
          "stargazers_count": 390,
          "topics": [
            "custom-integration",
            "home-assistant-integration"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2021.9.0",
          "manifest": {
            "name": "Emporia Vue",
            "render_readme": true,
            "homeassistant": "2021.9.0"
          },
          "name": "Emporia Vue",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/emporia_vue",
          "local": "/config/custom_components/emporia_vue",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@ludeeus"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "HACS gives you a powerful UI to handle downloads of all your custom needs.",
          "domain": "hacs",
          "downloads": 427530,
          "etag_repository": "W/\"f7cbb4a9dada3ab7c350bc3ef67730f1096275d86a2756d78fb4a9d3c6875e20\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "hacs/integration",
          "hide": false,
          "has_issues": true,
          "id": "172733314",
          "installed_commit": "7aaf86e",
          "installed_version": "1.33.0",
          "installed": true,
          "last_commit": "7aaf86e",
          "last_updated": "2024-01-15T19:31:00Z",
          "last_version": "1.33.0",
          "manifest_name": "HACS",
          "new": false,
          "open_issues": 0,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 4289,
          "topics": [
            "community",
            "package-manager"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "hacs.zip",
          "hacs": "0.19.0",
          "hide_default_branch": true,
          "homeassistant": "2023.6.0",
          "manifest": {
            "name": "HACS",
            "zip_release": true,
            "hide_default_branch": true,
            "homeassistant": "2023.6.0",
            "hacs": "0.19.0",
            "filename": "hacs.zip"
          },
          "name": "HACS",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/hacs",
          "local": "/config/custom_components/hacs",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@bruxy70"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "\ud83d\udcc5 Custom Home Assistant integration for public holidays - also used for garbage_collection integration to automatically move scheduled events that fall on a public holiday (by an automation blueprint)",
          "domain": "holidays",
          "downloads": 4073,
          "etag_repository": "W/\"5d1e6b4cb1d464be8b72bf02323aa28af3363cdb2a64e951d5822caf78843d10\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "bruxy70/Holidays",
          "hide": false,
          "has_issues": true,
          "id": "447307317",
          "installed_commit": "4b80604",
          "installed_version": "1.9.10",
          "installed": true,
          "last_commit": "3211800",
          "last_updated": "2023-12-28T13:12:10Z",
          "last_version": "1.9.10",
          "manifest_name": "Holidays",
          "new": false,
          "open_issues": 0,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 42,
          "topics": [
            "calendar",
            "country-holidays",
            "garbage-collection",
            "holidays",
            "public-holidays"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "holidays.zip",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2022.12.0",
          "manifest": {
            "name": "Holidays",
            "zip_release": true,
            "filename": "holidays.zip",
            "homeassistant": "2022.12.0"
          },
          "name": "Holidays",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/holidays",
          "local": "/config/custom_components/holidays",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "config_flow": false,
          "default_branch": null,
          "description": "A Custom Lovelace card to pull together the mail and packages sensors.",
          "domain": "",
          "downloads": 0,
          "etag_repository": "W/\"64ed4c4121f933bd1b72ae694bbba68e4ac29895fc335d20893d4c48041e2795\"",
          "etag_releases": null,
          "file_name": null,
          "first_install": false,
          "full_name": "moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card",
          "hide": false,
          "has_issues": true,
          "id": "240145420",
          "installed_commit": "a771689",
          "installed_version": "v0.8.0.0",
          "installed": true,
          "last_commit": "a771689",
          "last_updated": "2021-06-12T01:33:24Z",
          "last_version": "v0.8.0.0",
          "manifest_name": null,
          "new": false,
          "open_issues": 0,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": true,
          "stargazers_count": 67,
          "topics": []
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "Home-Assistant-Mail-And-Packages-Custom-Card.js",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2020.12.0",
          "manifest": {
            "name": "Mail and Packages Custom Card",
            "filename": "Home-Assistant-Mail-And-Packages-Custom-Card.js",
            "homeassistant": "2020.12.0"
          },
          "name": "Mail and Packages Custom Card",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": false
        },
        "ref": null,
        "paths": {
          "localpath": "/config/www/community/Home-Assistant-Mail-And-Packages-Custom-Card",
          "local": "/config/www/community/Home-Assistant-Mail-And-Packages-Custom-Card",
          "remote": null
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@moralmunky",
            "@firstof9"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "Home Assistant integration providing day of package counts and USPS informed delivery images.",
          "domain": "mail_and_packages",
          "downloads": 5456,
          "etag_repository": "W/\"b4e0a1b0f3d01eb9bbebd94af50067b73e384b199b8e41b5b237f0cd0f91b529\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "moralmunky/Home-Assistant-Mail-And-Packages",
          "hide": false,
          "has_issues": true,
          "id": "188106531",
          "installed_commit": "6abdb93",
          "installed_version": "0.3.19",
          "installed": true,
          "last_commit": "6abdb93",
          "last_updated": "2023-10-29T17:06:41Z",
          "last_version": "0.3.19",
          "manifest_name": "Mail and Packages",
          "new": false,
          "open_issues": 0,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": true,
          "stargazers_count": 509,
          "topics": [
            "home-assistant-config",
            "lovelace-card",
            "lovelace-custom-card"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "mail_and_packages.zip",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2022.4.0",
          "manifest": {
            "name": "Mail and Packages",
            "homeassistant": "2022.4.0",
            "zip_release": true,
            "filename": "mail_and_packages.zip"
          },
          "name": "Mail and Packages",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/mail_and_packages",
          "local": "/config/custom_components/mail_and_packages",
          "remote": "custom_components"
        }
      }
    ],
    "rate_limit": {
      "resources": {
        "core": {
          "limit": 5000,
          "used": 245,
          "remaining": 4755,
          "reset": 1705634525
        },
        "search": {
          "limit": 30,
          "used": 0,
          "remaining": 30,
          "reset": 1705632172
        },
        "graphql": {
          "limit": 5000,
          "used": 12,
          "remaining": 4988,
          "reset": 1705633566
        },
        "integration_manifest": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1705635712
        },
        "source_import": {
          "limit": 100,
          "used": 0,
          "remaining": 100,
          "reset": 1705632172
        },
        "code_scanning_upload": {
          "limit": 1000,
          "used": 0,
          "remaining": 1000,
          "reset": 1705635712
        },
        "actions_runner_registration": {
          "limit": 10000,
          "used": 0,
          "remaining": 10000,
          "reset": 1705635712
        },
        "scim": {
          "limit": 15000,
          "used": 0,
          "remaining": 15000,
          "reset": 1705635712
        }
      },
      "rate": {
        "limit": 5000,
        "used": 245,
        "remaining": 4755,
        "reset": 1705634525
      }
    }
  }
}

**Comment by ludeeus** [comment]
Fixed in https://github.com/hacs/integration/pull/3456
