### ISSUE TITLE
Entity None

### ISSUE THREAD

**Issue by Mike031981** [hacs/integration#3471]
### Describe the issue

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1524
First occurred: 07:56:51 (6 occurrences)
Last logged: 07:56:51

Entity None (<class 'custom_components.hacs.update.HacsRepositoryUpdateEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <UpdateEntityFeature.INSTALL|PROGRESS|RELEASE_NOTES: 21>, please create a bug report at https://github.com/hacs/integration/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

### Link to action run

https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

### Link to action configuration

I don´t know

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by Mike031981** [comment]
Is there anything that I can do to solve this behavior?

Thanks

**Comment by ludeeus** [comment]
Restore a backup of HA till before it started complaining, or update HACS when a new version is released.
