### ISSUE TITLE
Typo in default.repositiories

### ISSUE THREAD

**Issue by bartfailt** [hacs/integration#3475]
## System Information

version | core-2024.1.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Budapest
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4742
Installed Version | 1.34.0
Stage | running
Available Repositories | 1376
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 116.5 GB
disk_used | 8.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.8.1), Studio Code Server (5.15.0), InfluxDB (5.0.0), Grafana (9.1.2), Let's Encrypt (5.0.12)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 2
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 15, 2024 at 21:13
-- | --
current_recorder_run | January 22, 2024 at 11:50
estimated_db_size | 20.19 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The file `custom_components/hacs/utils/default.repositories` contains this segment:

```{"name": "Midea AC LAN", "render_readme": true, "homeassistant": 2022.5, "zip_release": true, "filename": "mieda_ac_lan.zip"}```

Notice the typo `mieda_ac_lan.zip` instead of `midea_ac_lan.zip`.

### Reproduction steps

1. In HACS / Integrations search for `Midea AC LAN`
2. Press `Download`. Nothing happens, just spinning
3. Check logs
...

### Debug logs

```text
2024-01-22 11:51:39.720 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/georgezhao2010/midea_ac_lan/releases/download/v0.3.22/mieda_ac_lan.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 730, in async_download_file
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/georgezhao2010/midea_ac_lan/releases/download/v0.3.22/mieda_ac_lan.zip
```

**Comment by ludeeus** [comment]
You should report that to the author of it.
<https://github.com/georgezhao2010/midea_ac_lan/blob/master/hacs.json#L6>
