### ISSUE TITLE
Integration page - Line break of the info

### ISSUE THREAD

**Issue by Milinator** [hacs/integration#3478]
### Web browser

Home Assistant Android App

### Web browser version

2024.1.2

## System Information

version | core-2024.1.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.71-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4795
Installed Version | 1.34.0
Stage | running
Available Repositories | 1456
Downloaded Repositories | 29

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 234.0 GB
disk_used | 38.9 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.2.0), Terminal & SSH (9.8.1), Mosquitto broker (6.4.0), Duck DNS (1.15.0), NGINX Home Assistant SSL proxy (3.7.0), CEC Scanner (3.0), File editor (5.7.0), Ring-MQTT with Video Streaming (5.6.3), Zigbee2MQTT (1.35.1-1), Home Assistant Google Drive Backup (0.112.1), Advanced SSH & Web Terminal (17.0.4), Studio Code Server (5.15.0), AppDaemon (0.16.3), DSS VoIP Notifier (4.0.0), ESPHome (2023.12.9)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 15
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15. Januar 2024 um 19:09
-- | --
current_recorder_run | 24. Januar 2024 um 09:17
estimated_db_size | 2387.11 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

If you open the integration tab in HACS the line break of the "new repositories"-info is pretty broken (at least in German). Maybe move the "Hide all new repositories" to the bottom of the info field under the text? 

### Reproduction steps

1. Open HACS
2. (Maybe change language to german - not sure though) 
3. Click on "integrations" 
4. Look at the line break
...

### Screenshots

![Screenshot_20240124_091856](https://github.com/hacs/integration/assets/67156976/4b88144b-1278-4625-a9d3-0ca742c95c65)

### Javascript logs from your browser console

```text
None
```

**Comment by ludeeus** [comment]
This is in the legacy UI and will not be fixed.
This does not exist in the new (experimental UI)
