### ISSUE TITLE
UI NOT LOADING

### ISSUE THREAD

**Issue by nileshkc** [hacs/integration#3482]
### Web browser

Home assistant app

### Web browser version

NA

### System Health details

Everything is fine 

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The front doesn’t seem to load

### Reproduction steps

1. I installed HACS as per instructions 
2. When I click on HACS the UI doesnr load
3.
...

### Screenshots

![image](https://github.com/hacs/integration/assets/7891130/d3caab26-3589-4f6c-8e85-acc5e7488481)

### Javascript logs from your browser console

```text
I use the companion iOS app
```

### Diagnostics dump

Cannot download using iOS app

**Comment by ludeeus** [comment]
Your screenshot show that it did load.

**Comment by nileshkc** [comment]
[Image.png]

Here is the screenshot on when I  click on HACS menu


Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
