### ISSUE TITLE
1.34 install never ends.. 

### ISSUE THREAD

**Issue by spanzetta** [hacs/integration#3491]
### System Health details

Anyone else with this problem?
Setup never ends.. 
Running HA OS on Pi3A+

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Setup never ends

### Reproduction steps

1. Just run the update (from 
2.
3.
...

### Debug logs

```text
No logs.. 
Just want to know if anyone else has the same problem
```

**Comment by ludeeus** [comment]
> No logs.. 
Just want to know if anyone else has the same problem

This is not a forum, use the fill-out the template properly.

**Comment by jorsto** [comment]
I had same problem, the HA system is on a remote location over a cellular connection and the IoT subscription only have 0.5Mbps downlink. 
It seems there is a 60 second timeout for the hacs update file download, so it fails if your system is on a slow connection.

The HA log showed:
A timeout of 60! seconds was encountered while downloading https://github.com/hacs/integration/releases/download/1.34.0/hacs.zip, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 0

Running the hacs download script in terminal and restarting HA seems to update hacs successfully also as a work around:
wget -O - https://get.hacs.xyz | bash -

**Comment by spanzetta** [comment]
> wget -O - https://get.hacs.xyz | bash -

@jorsto 
you are my hero ;-)
With this command I was able to update HACS to 1.34..

The strange thing is that I dont' have a slow connection.. so I can't understand why it was failing launching the update from the interface

Anyway.. I now solved thanks to your help!

Many thanks again
