### ISSUE TITLE
Request for removal of cyberjunky/home-assistant-p2000

### ISSUE THREAD

**Issue by Sweepr** [hacs/integration#3494]
### Repository

cyberjunky/home-assistant-p2000

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Doesn't work, no longer maintained.

### Link to issue

https://github.com/cyberjunky/home-assistant-p2000/issues/80

**Comment by ludeeus** [comment]
API seems to just be flaky, and author is still responding, ref https://github.com/cyberjunky/home-assistant-p2000/issues/82
