### ISSUE TITLE
HACS Integration local container stop suddenly

### ISSUE THREAD

**Issue by ardilsercan** [hacs/integration#3495]
### System Health details

Version: (latest-main branch)
Development: True
Docker: True
User: ardilsercan
Virtual Environment: True
Pyhton Version: 3.11.5
Operating System Family: macOS
Operating System Version: 14.0
CPU Architecture: arm64
Timezone: Europe/Istanbul

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I forked the final version of the integration repo to my own repo and I am trying to run it locally with a docker container. However, when I run it after building on the Dockerfile, the container ends with debug notes even though it does not appear as the error codes below.

And additionally, Dockerfile is updated as below(only added Github params)

```
FROM python:3.11-alpine

WORKDIR /hacs

RUN \
    apk add --no-cache \
        libffi-dev \
    \
    &&  apk add --no-cache --virtual .build-deps \
        bash \
        gcc \
        git \
        musl-dev \
    \
    && git clone --quiet --depth 1 https://github.com/ardilsercan/integration /hacs \
    \
    && bash /hacs/scripts/install/pip_packages setuptools wheel \
    \
    && bash /hacs/scripts/install/pip_packages homeassistant aiogithubapi async-timeout \
    \
    && bash /hacs/scripts/install/frontend \
    \
    && apk del --no-cache .build-deps > /dev/null 2>&1 \
    \
    && rm -rf /var/cache/apk/* \
    \
    && find /usr/local \( -type d -a -name test -o -name tests -o -name '__pycache__' \) -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) -exec rm -rf '{}' \;

COPY ./action.py /hacs/action.py

ENV GITHUB_TOKEN=<My token>
ENV GITHUB_REPOSITORY='ardilsercan/integration'
ENV GITHUB_ACTOR='ardilsercan'

ENTRYPOINT ["python3", "/hacs/action.py"]
```

### Reproduction steps

1. go to directory of /action
2. run command: **docker build -t hacs .**
3. run command: docker run hacs

P.S. For 2nd step: All requirements and operational successfully completed in container log.

### Debug logs

```text
::DEBUG:: Using selector: EpollSelector
::INFO:: Category: 
::INFO:: Repository: ardilsercan/integration
::DEBUG:: 'GitHubRepositoryModel' is missing key 'has_discussions' for <class 'bool'>
::DEBUG:: 'GitHubRepositoryModel' is missing key 'allow_forking' for <class 'bool'>
::DEBUG:: 'GitHubRepositoryModel' is missing key 'is_template' for <class 'bool'>
::DEBUG:: 'GitHubRepositoryModel' is missing key 'web_commit_signoff_required' for <class 'bool'>
::DEBUG:: 'GitHubRepositoryModel' is missing key 'visibility' for <class 'str'>
::DEBUG:: 'GitHubRepositoryModel' is missing key 'allow_update_branch' for <class 'bool'>
::DEBUG:: 'GitHubRepositoryModel' is missing key 'use_squash_pr_title_as_default' for <class 'bool'>
::DEBUG:: 'GitHubRepositoryModel' is missing key 'squash_merge_commit_message' for <class 'str'>
::DEBUG:: 'GitHubRepositoryModel' is missing key 'squash_merge_commit_title' for <class 'str'>
::DEBUG:: 'GitHubRepositoryModel' is missing key 'merge_commit_message' for <class 'str'>
::DEBUG:: 'GitHubRepositoryModel' is missing key 'merge_commit_title' for <class 'str'>
::DEBUG:: 'GitHubRepositoryModel' is missing key 'parent' for <class 'dict'>
::DEBUG:: 'GitHubRepositoryModel' is missing key 'source' for <class 'dict'>
::DEBUG:: 'GitHubRepositoryModel' is missing key 'security_and_analysis' for <class 'dict'>
::WARNING::  is not a valid repository category, ardilsercan/integration will not be registered.
```

**Comment by ludeeus** [comment]
You are missing variable for category.
This is also not documented to be working, and not something I'm going to support in the near future.

**Comment by ardilsercan** [comment]
Thanks for the quick response ludeeus. I will definitely look at the Category section. But I couldn't find a document or .md file to directly stand up the project. Please forgive me if I missed it, is there sufficient documentation on this subject?

It is a project that I like very much, but frankly I have a hard time unless I can work locally.

**Comment by ludeeus** [comment]
The action is not designed to be run locally, on in a github runner so no, there is not any documentation about it.

**Comment by ardilsercan** [comment]
I understand. Well, since the HASC project is open source, it can be divided into backend+frontend+core etc. I think there is definitely a way to run it locally as a whole, am I wrong?

**Comment by ludeeus** [comment]
HACS is not a standalone application.
It is an integration to Home Assistant.

What you tried above is just the repository validation action.

I was notified by GitHub that you posted an API key, I have removed that revision, but you need to revoke it.
