### ISSUE TITLE
Link wrong from HACS

### ISSUE THREAD

**Issue by baddino** [hacs/integration#3496]
### Web browser

firefox

### Web browser version

122.0 (64-bit)

## System Information

version | core-2024.1.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.71-haos
arch | x86_64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1379
Downloaded Repositories | 18

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 116.7 GB
disk_used | 5.9 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.0.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 2
views | 9
mode | storage

</details>

<details><summary>Miele</summary>

component_version | 2024.1.0
-- | --
reach_miele_cloud | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 24 gennaio 2024 alle ore 04:32
-- | --
current_recorder_run | 3 febbraio 2024 alle ore 19:13
estimated_db_size | 22.37 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.15
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 1

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Last release v0.3.22 of midea_ac_ln
it is not possible to update the new release from home assistant (or download it from HACS)

<Integration georgezhao2010/midea_ac_lan> Failed to download https://github.com/georgezhao2010/midea_ac_lan/releases/download/tags/v0.3.22/mieda_ac_lan.zip

The link is simply wrong
Thank you

### Reproduction steps

1.Download from hacs Midea_AC_LAN
2.link is wrong

### Screenshots

<img width="1133" alt="Screenshot 2024-02-03 alle 23 51 26" src="https://github.com/hacs/integration/assets/13237411/94a576e8-c180-48ab-b6bf-41517da78df5">

### Javascript logs from your browser console

```text
<Integration georgezhao2010/midea_ac_lan> Failed to download https://github.com/georgezhao2010/midea_ac_lan/releases/download/tags/v0.3.22/mieda_ac_lan.zip
21:48:44 – (ERRORE) HACS (integrazione personalizzata)
```

**Comment by tjorim** [comment]
Out of scope for HACS. The author of the custom integration set it like that. https://github.com/georgezhao2010/midea_ac_lan/blob/master/hacs.json#L6
