### ISSUE TITLE
new HACS in new HA UI problerm

### ISSUE THREAD

**Issue by pajikcz** [hacs/integration#3499]
### Web browser

last chrome

### Web browser version

121

### System Health details

last HAOS 

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

after install. instruction i got this, several reboots and no progress

![image](https://github.com/hacs/integration/assets/145907242/d5c40b22-f1bb-4999-8711-c43b1e2d6dc8)

### Reproduction steps

1.followed tutorials on YT
2.
3.
...

### Screenshots

![image](https://github.com/hacs/integration/assets/145907242/784a4267-53da-419a-8a19-17ffc16e9ca0)

### Javascript logs from your browser console

```text
dont know
```

**Comment by pajikcz** [comment]
how to fix it?

**Comment by ludeeus** [comment]
There is nothing to fix.

**Comment by pajikcz** [comment]
i want to see this
![image](https://github.com/hacs/integration/assets/145907242/775506ad-45de-496b-99ba-95e642f246a5)

**Comment by ludeeus** [comment]
I know you want that.
But that no longer exists in the mode you are running.
(and that is not something you really want anyway as that is just imaginary limitations.)

**Comment by pajikcz** [comment]
so my 1st screen is ok?

**Comment by ludeeus** [comment]
Yes, it matches the documentation I linked.

**Comment by pajikcz** [comment]
ok thx
