### ISSUE TITLE
Request for removal of mauro-midolo/homeassistant_electrolux_status

### ISSUE THREAD

**Issue by dscroft** [hacs/integration#3500]
### Repository

mauro-midolo/homeassistant_electrolux_status

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

The repository no longer exists and the python library that it depends/depended no longer works due to Electrolux API changes so a fork of the repository or last known version is not an option.

Dependency https://github.com/tomeko12/pyelectroluxconnect

### Link to issue

Not possible as repo has been removed.

**Comment by AdrianGarside** [comment]
@dscroft This integration still worked in the US region.
