### ISSUE TITLE
Feature request: hide updates option

### ISSUE THREAD

**Issue by bcutter** [hacs/integration#3501]
### Web browser

Firefox

### Web browser version

122.0

### System Health details

Very likely not needed for this FR

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Provide the possibility to hide updates. Like it is in Home Assistant for a long time.

This would allow to work around dependency issues with single integration releases, which can not be handled by the current requirements management abilities of HACS.

(following up on https://github.com/nielsfaber/alarmo/issues/891#issuecomment-1930634421)

### Reproduction steps

It's a feature request, see "describe the issue".

### Screenshots

Hide updates screen of HA itself (`/config/updates`) as a blueprint for a similar HACS implementation

![grafik](https://github.com/hacs/integration/assets/13799156/ad1ee918-4502-413c-89db-62486056c76f)

### Javascript logs from your browser console

```text
Very likely not needed for this FR
```

**Comment by ludeeus** [comment]
Enable experimental features and it works just like the rest of HA.

**Comment by ludeeus** [comment]
That is correct, that no longer exists.
ONly update entities <https://experimental.hacs.xyz/docs/entities/update_entities/>
