### ISSUE TITLE
Feature request: extend requirements/dependency management on single integration releases instead of the whole integration

### ISSUE THREAD

**Issue by bcutter** [hacs/integration#3502]
### System Health details

It's a feature request

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

According to https://hacs.xyz/docs/publish/integration/ and https://github.com/ludeeus/integration_blueprint/blob/main/requirements.txt integration developers can set a minimum HA version.

That is valid for the whole integration. Now single releases have different dependency requirements.

**FR core: allow to specify requirements for every single release of an integration.**

Following up on developer input at https://github.com/nielsfaber/alarmo/issues/891#issuecomment-1930634421

### Reproduction steps

It's a feature request

### Debug logs

```text
It's a feature request
```

**Comment by ludeeus** [comment]
This will not be implemented.

**Comment by bcutter** [comment]
...because?

Ahm, while I thankfully respect the speed of your reaction, I'd really like to understand WHY.

**Comment by ludeeus** [comment]
For two reasons:
- I will not add anything new to HACS soon (which is why you had to select an issue template and not a feature request template. Im not currently taking any requests as no new things will currently be added anyway)
- It is not really needed. HACS gets a min version of home assistant from the hacs.json file in the tag/branch you are trying to download.

**Comment by bcutter** [comment]
Thanks. While point one seems to be reasonable (personal reasons, we have to respect that 😃), I need to refer to reason number 2:
- True for new installs...
- ...but not for updates. Here people can update to versions not usable for their HA versions.

Not sure if you had the chance to look at https://github.com/nielsfaber/alarmo/issues/891#issuecomment-1930634421, so just adding developer feedback here directly:

> From my side it would be preferable if I could mark a required minimum HA version per Alarmo release.
That way a user would always see the latest updatable version that matches their HA installation.
But I don't believe this is possible in HACS currently.

Again - I'm not a dev and not really into those inner mechanics. I'm just saying what @nielsfaber wrote sounded logical to me.

**Comment by ludeeus** [comment]
What they write is how it works.
It uses hacs.json from the tag/branch that are getting viewed/downloaded.
So for 1.9.14 that is 2023.4.0b01<https://github.com/nielsfaber/alarmo/blob/v1.9.14/hacs.json#L7>
And for 1.8.7 there is no limit <https://github.com/nielsfaber/alarmo/blob/v1.8.7/hacs.json>

**Comment by bcutter** [comment]
I think I got it. So every release with the shipped `hacs.json` already specifies its own requirements.
Short: already possible today with HACS (if the `hacs.json` gets carefully revised and updated for every new release).

Did I got this right finally? :smile

**Comment by ludeeus** [comment]
yes but it has to be done before a release, not after.

**Comment by ludeeus** [comment]
"just all the cool new stuff, like a preview" is more fitting

1: Its safer and more stable, actually.
2: It could be 2 days, it could also be 2 years, I do not have a set timeframe for it.

**Comment by ludeeus** [comment]
They are shown because it exist, this is something that Home Assistant chooses and not something that I can do anything about.
If you skip that version, you can still find it in the update section you just need to show skipped (like all other update entities) again this is something that Home Assistant chooses and not something that I can do anything about.

**Comment by ludeeus** [comment]
/config (main menu) should only list updatable entities.

**Comment by bcutter** [comment]
Oh, indeed - it does. <del>So for custom dashboards (own update sections) it's impossible to use the HACS update entities. I'm not aware of the magic taken place in the `/config (main menu)` and if it's possible to copy that with a Jinja template.</del>

Maybe one can use this to replay that check. I'll have a look at it (like "`release_summary` does not contain `Requires` or `warning` etc.") trying to filter those:
![grafik](https://github.com/hacs/integration/assets/13799156/c8da755d-be2a-4286-acf0-cada615334bf)

Now I'll just need to find out how to ignore new integrations (the ones formerly shown in green).

**Thanks for all your really great help today. Totally awesome, many thumbs (I can give you two) up** 👍 👍 😃

**Comment by ludeeus** [comment]
That "release summary" will be removed at some point. its no longer used by HA.
I might needs to get fancy with supported features at some point.
But that will probably be for v3.

**Comment by bcutter** [comment]
I don't see another possibility to check for requirements currently. There'll hopefully be another option then...
