### ISSUE TITLE
Badly appearing backlight to window close button (X) on Safari

### ISSUE THREAD

**Issue by solarssk** [hacs/integration#3503]
### Web browser

Safari

### Web browser version

17.3 (19617.2.4.11.8)

## System Information

version | core-2024.2.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.74-haos
arch | x86_64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4983
Installed Version | 1.34.0
Stage | running
Available Repositories | 1387
Downloaded Repositories | 14

</details>

<details><summary>Airly</summary>

can_reach_server | ok
-- | --
requests_remaining | 8
requests_per_day | 100

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 24.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.0), Zigbee2MQTT (1.35.1-1), File editor (5.7.0), Terminal & SSH (9.8.1), MariaDB (2.6.1), Samba Backup (5.2.0), InfluxDB (5.0.0), ESPHome (2023.12.9)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 10
views | 31
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 31 stycznia 2024 o 14:50
-- | --
current_recorder_run | 8 lutego 2024 o 18:28
estimated_db_size | 1425.62 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

On the safari browser after opening a window with intention to update a particular add-on in Home Assistant, badly appears highlighting the closing of the window (the characteristic X in the right corner). 
On the Chrome browser, Brave - the highlight appears only after hovering over the X icon. On Safari, the backlight is fixed and badly marred by the X sign.

### Reproduction steps

1. Go to HACS
2. Open something add-on to update
3. Check backlight on the right corner with X button.

### Screenshots

Safari:
<img width="637" alt="Screenshot 2024-02-08 at 23 13 22" src="https://github.com/hacs/integration/assets/83293863/95974a7f-2278-4e6f-ad41-3a5b75b1e5ca">

Brave:
<img width="644" alt="Screenshot 2024-02-08 at 23 13 08" src="https://github.com/hacs/integration/assets/83293863/c2fff6c9-61a2-41b5-937e-38bf0ed3ed34">

### Javascript logs from your browser console

```text
n/a
```

### Diagnostics dump

[config_entry-hacs-6db579520edaec973874e0b618141532.json](https://github.com/hacs/integration/files/14215333/config_entry-hacs-6db579520edaec973874e0b618141532.json)

**Comment by ludeeus** [comment]
This will not be fixed as this only exist in the old UI.
If you want the new now, you can enable experimental features, or wait for 2.0.0
