### ISSUE TITLE
HACS Auto Updates do not work anymore

### ISSUE THREAD

**Issue by saschabrockel** [hacs/integration#3515]
## System Information

version | core-2024.2.2
-- | --
installation_type | Unsupported Third Party Container
dev | false
hassio | false
docker | true
user | abc
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.64-Unraid
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4999
Installed Version | 1.34.0
Stage | running
Available Repositories | 1404
Downloaded Repositories | 80
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 52
views | 52
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 12. Februar 2024 um 17:42
-- | --
current_recorder_run | 17. Februar 2024 um 04:03
estimated_db_size | 794.54 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Updates of HACS and its integrations are not found anymore. Only if I restart Home Assistant with the option to restart and not only reload config. Or restart the Docker container which is basically the same.

I waited more than 72 hours to be sure it was how it was for a while now. No updates are shown but when I restart Home Assistant they instantly pop up. I didn't change any major thing so I could say who would lead to this behavior.

### Reproduction steps

1. Install Docker version of Home Assistant
2. Install HACS and some integrations
3. Wait 48 hours until the updates should be shown but there are none even though there should be some
...

### Debug logs

```text
I cannot copy the logs because they contain 70MB. I can upload them somewhere else if needed.
```

### Diagnostics dump

[config_entry-hacs-e11c1166933ec658f501cf4d2d46504f.json](https://github.com/hacs/integration/files/14353041/config_entry-hacs-e11c1166933ec658f501cf4d2d46504f.json)

**Comment by saschabrockel** [comment]
As nobody seems to answer I provide the logs via Google Drive now:
https://drive.google.com/file/d/15iMaIZTbjhqjMVsmIl2NRZOPh6Yz3MiS/view?usp=sharing

**Comment by codyc1515** [comment]
Facing the same issue. What further information would help?

**Comment by rrooggiieerr** [comment]
I guess with Auto Updates you mean detecting of availability of new versions of an integration? HACS never automatically updates integrations.

Anyways, when _Enable experimental features_ is enabled in HACS updates for some integrations are detected and shown in Settings > System > Updates while some updates are nit shown. When _Enable experimental features_ is disabled new versions are not shown in Settings > System > Updates but are shown in the HACS dashboard

**Comment by robinhood-code** [comment]
I have the same issue. Update availability will not be shown under Settings I restart HA.

**Comment by ludeeus** [comment]
I see the problem, that's an annoying one…
Using the `homeassistant.update_entity` service might works as a workaround until it's fixed.

**Comment by rrooggiieerr** [comment]
@robinhood-code You should use entities that start with `update.`, like `update.apexcharts_card_update`

**Comment by lweberru** [comment]
Facing the same issue since a long time now. Only HA restart is showing new updates.
The idea with homeassistant.update_entity is no good workaround. I just want to see which new versions are available and I am having really tons of ha installed integrations…

**Comment by msaphoto06** [comment]
Same problem

**Comment by cpuks** [comment]
It's cumbersome but I go to HACS every 1-2 days and manually check installed addons for updates by pressing three dots (right top corner) and selecting download again, also going to integrations -> HACS -> three dots -> reload again helps sometimes too.
