### ISSUE TITLE
Repository version list is not comprehensive

### ISSUE THREAD

**Issue by erodewald** [hacs/integration#3518]
## System Information

version | core-2023.7.3
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | sc-homeassistant
virtualenv | true
python_version | 3.11.5
os_name | Linux
os_version | 4.4.302+
arch | x86_64
timezone | America/Chicago
config_dir | /volume1/@appdata/homeassistant/config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1396
Downloaded Repositories | 24

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 23

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 12, 2024 at 19:00
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | us-east-1-7.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 11
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 11, 2024 at 19:08
-- | --
current_recorder_run | February 20, 2024 at 18:42
estimated_db_size | 109.64 MiB
database_engine | sqlite
database_version | 3.42.0

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I am trying to install an older version of [card-mod@3.2.2](https://github.com/thomasloven/lovelace-card-mod/releases/tag/3.2.2) and the selector in HACS only shows the last few versions. My assumption is that the list is a static number defined by HACS.

![image](https://github.com/hacs/integration/assets/1534259/0f05072a-75d1-4e01-a247-abb839cd2ef5)

### Reproduction steps

1. Go to HACS
2. Go to Frontend
3. Explore repository "card-mod"
4. Open version selector and see only 5 versions + default branch

### Debug logs

```text
N/A
```

**Comment by ludeeus** [comment]
You can change that in the configuration options, default is 5.

**Comment by erodewald** [comment]
Thanks :)
