### ISSUE TITLE
Links in battery-state-card documentation just go to local HACS menu

### ISSUE THREAD

**Issue by pfurrie** [hacs/integration#3519]
### Describe the issue

**First:** This was already submitted to the "battery-state-card" Github issues page.  They said "This issue should be reported on the HACS side. The links in the doc are relative, not absolute"

**Next:** I'm unsure which issues section this should be filed.  Have opted for "Documentation" but am sure I'll hear about it if that is incorrect.

**Description:** 
Links in battery-state-card documentation just go to local HACS menu.

**How to reproduce**
1. Open _HACS_
2. Open _Frontend_
3. Search for and open _Battery State Card / Entity Row_
4. Scroll down to _Card config_ section
5. Click on any link.  For example:
![image](https://github.com/hacs/integration/assets/11449721/dab7c9b8-e380-4317-bd44-59fb94fefe2f)
6. Watch as you are whisked to the HACS main menu:
![image](https://github.com/hacs/integration/assets/11449721/603d7926-f69e-4ab2-a22a-ac3738a1bbc2)

**Expected behavior**
The user would be shown a page with information regarding the link that was clicked. As in the above example, something about entities.

**Version of the battery state card:**
3.2.1

**Version of HACS:**
![image](https://github.com/hacs/integration/assets/11449721/2c53efa9-0f7d-4482-8a68-104cec675c56)

**Version of Home Assistant:**
![image](https://github.com/hacs/integration/assets/11449721/0759a5c3-cf41-4542-85ee-cac850f71b80)

### Screenshots

This shows one of the addresses pointed to by a link. Each link does have a different address that looks like it should work, but doesn't do what you think it might do.
![image](https://github.com/hacs/integration/assets/11449721/1232fb61-f94c-43e3-9e12-3205cd63b641)

**Comment by ludeeus** [comment]
This will not be fixed in the UI variant you are using.
The links point correctly (like `http://127.0.0.1:8123/hacs/repository/256292682#entity-object`) in the UI variant you get with experimental features enabled.
But the markdown renderer in Home Assistant does not automatically anchor H1-5 tags. That is out of my hands.
