### ISSUE TITLE
Timeout issues in HACS

### ISSUE THREAD

**Issue by Alexithemia** [hacs/integration#3522]
## System Information

version | core-2024.2.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.74-haos
arch | aarch64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | failed to load: timeout
GitHub Web | ok
GitHub API Calls Remaining | 4958
Installed Version | 1.34.0
Stage | waiting
Available Repositories | 1402
Downloaded Repositories | 3
HACS Data | failed to load: timeout

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 4, 2024 at 6:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-5.ui.nabu.casa
certificate_status | ready
instance_id | 9feb1f47c65d479f9bf81c24a1826273
can_reach_cert_server | failed to load: timeout
can_reach_cloud_auth | failed to load: timeout
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.02.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 28.0 GB
disk_used | 7.2 GB
healthy | true
supported | true
board | green
supervisor_api | ok
version_api | failed to load: timeout
installed_addons | Studio Code Server (5.15.0), Terminal & SSH (9.9.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 15, 2024 at 10:28 PM
-- | --
current_recorder_run | February 23, 2024 at 11:24 PM
estimated_db_size | 26.68 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I am getting timeout errors in Home Assistant, all the issues seem to be with HACS.

Things sometimes work after a 5-6 minute delay.

I have only SmartThinQ LGE Sensors and Vivint installed through HACS and both have timeout issues in their logs

### Reproduction steps

1. Have HACS installed
2. Try to do anything with a custom integration
3. Sorry I really don't know how to recreate this
...

### Debug logs

```text
This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:866
Integration: HACS (documentation, issues)
First occurred: February 21, 2024 at 12:11:09 PM (22 occurrences)
Last logged: 11:07:27 PM

Could not update theme - Timeout of 60s reached
Could not update template - Timeout of 60s reached
Could not update integration - Timeout of 60s reached
```

### Diagnostics dump

[config_entry-hacs-942197019953307d7b5968c613e0a16a.json](https://github.com/hacs/integration/files/14391844/config_entry-hacs-942197019953307d7b5968c613e0a16a.json)

**Comment by ludeeus** [comment]
It's not just in HACS.
Disable IPv6
