### ISSUE TITLE
Integration in latest Home Assitant for Raspery does not work

### ISSUE THREAD

**Issue by LeOS-GSI** [hacs/integration#3531]
### Describe the issue

I have followed the tutuorial on your webseite for Core installation on my RPI4. in /homeassistant folder a index.html is existing so the wget command is failing. if I'm running the wget command in standard ssh folder `[core-ssh ~]` the index.html is created, but no HACS integration is available. I have delete cache several times, I have rebooted the rpi several times, still no HACS integration available.

### Screenshots

![Screenshot from 2024-02-29 12-31-20](https://github.com/hacs/integration/assets/2726574/858fee2a-0047-4957-9532-63394fe27e35)

**Comment by ludeeus** [comment]
You use `-o` (lowercase) instead of `-O` (uppercase), that will not work.

**Comment by LeOS-GSI** [comment]
> You use `-o` (lowercase) instead of `-O` (uppercase), that will not work.

it is lower case !!!

**Comment by LeOS-GSI** [comment]
OK, with UPPERCASE the script seems working
![Screenshot from 2024-02-29 12-43-28](https://github.com/hacs/integration/assets/2726574/7cef61aa-cfe3-4a31-af24-4553b8e64b85)

**Comment by LeOS-GSI** [comment]
But still no HACS available after clear cache and reboot complete system

**Comment by ludeeus** [comment]
Yes it IS lower, it NEEDS to be upper.

**Comment by LeOS-GSI** [comment]
OK, after second reboot, the HACS is avaialble

**Comment by LeOS-GSI** [comment]
> But still no HACS available after clear cache and reboot complete system

please correct your tutorial or make a remark
