### ISSUE TITLE
Backups implementations when using update.integration isn't clear. 

### ISSUE THREAD

**Issue by sca075** [hacs/integration#3538]
### Describe the issue

First of all, thanks for the great Job you are doing with HACS.

The version selector according to the frontend (experimental) will be soon deprecated (honestly it makes sense and understand the direction) I would update the code on my integration to comply before this happens.
https://experimental.hacs.xyz/docs/entities/update_entities/#install-service
HACS provide the update.install service.. from the integration downloaded with it and in the docs 
from HA docs, to manage the backup the backup.py should be setup with the following.
``` 
from homeassistant.core import HomeAssistant

async def async_pre_backup(hass: HomeAssistant) -> None:
    """Perform operations before a backup starts."""

async def async_post_backup(hass: HomeAssistant) -> None:
    """Perform operations after a backup finishes."""
```

It looks there is no config to do on HACS.json for it (the update.intgration_update service is provided by HACS).

From the code I understand HACS will care to backup only persistent_integrations or repositories there listed in general and looking at he code in HACS/untils there is a backup.py that is a complete different backup class from what home assistant use (therefore I suppose there is something I probably miss-understood / missed and would be nice a clarification). 

Although I can ask this on the discord.. either on HA and here in HACS docs isn't that clear how to proceed, of course it is probably on development roadmap if so an hint wold appreciated.

Thanks in advance for your time and understanding.      

### Screenshots

[https://experimental.hacs.xyz/docs/entities/update_entities/#install-service](url)
![Screenshot 2024-03-02 at 08 43 27](https://github.com/hacs/integration/assets/82227818/aee6f4d1-8710-40dd-8d66-6a822d20de97)
_Home Assistant Service Call in yaml_
![Screenshot 2024-03-02 at 09 43 32](https://github.com/hacs/integration/assets/82227818/365df2e3-c3db-46a4-b272-c6469eade099)

Without ticking backup the update process works as expected.

**Comment by ludeeus** [comment]
Backups are not supported by this integration for update entities, and I highly doubt it ever will be.
The developer tools, show all possible options even if they are supported or not, and even in the description of that kye it says "if supported by the integration"

That is mainly for the `hassio` integration.

**Comment by sca075** [comment]
> Backups are not supported by this integration for update entities, and I highly doubt it ever will be. The developer tools, show all possible options even if they are supported or not, and even in the description of that kye it says "if supported by the integration"
> 
> That is mainly for the `hassio` integration.

thanks a lot I thought so.. anyway a clear statements on the docs can would avoid this kind of "questions". Thanks for considering it as the update service did come out form the HACS (thanks for that). Will implement the backup service as per hassio specs.
