### ISSUE TITLE
Request for removal of tuya/tuya-smart-life

### ISSUE THREAD

**Issue by iamdabe** [hacs/integration#3541]
### Repository

tuya/tuya-smart-life

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

The HACS install has been moved into default HA integration and no longer supported in HACS

### Link to issue

x

**Comment by ludeeus** [comment]
Nt a default repository.
