### ISSUE TITLE
[FR] Allow ignoring an update

### ISSUE THREAD

**Issue by ildar170975** [hacs/integration#3546]
### System Health details

not needed

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ ] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Some updates are not needed / undesired.
Sometimes a plugin may only have changes in "readme".
Suggest to allow users to mark these updates somehow as "ignored".
Ignored updates will be not present in a `repositories` attribute of `sensor.hacs`.
A new update for a plugin whose update is ignored - is NOT automatically ignored as well.
Also, a possibility to "un-ignore" should be available for ignored updates of installed plugins.

### Reproduction steps

not needed

### Debug logs

```text
not needed
```

**Comment by tjorim** [comment]
You are still using the old/legacy HACS sensor. Turn on experimental and it will use native Home Assistant update entities which allow you to skip/ignore things.

**Comment by ildar170975** [comment]
Interesting, thank you.
Just have switched on experimental features & will see how it works.

I wonder - why it is called "experimental" since:
-- it creates "native" `update` entities;
-- with this feature OFF my HACS sensor is "old/legacy"
??? ))

**Comment by tjorim** [comment]
Maybe old is a bad description. It's just how HACS currently behaves. As Ludeeus already said elsewhere, at some point 'experimental' will become the new default (which includes a new layout as well). Documentation can be found here: https://experimental.hacs.xyz/docs/basic/dashboard

**Comment by ildar170975** [comment]
Think you, very useful.
I guess I can close the issue...
