### ISSUE TITLE
Search not showing intigrations to download from store

### ISSUE THREAD

**Issue by JSkye3293** [hacs/integration#3549]
### Web browser

Firefox/ HA App

### Web browser version

123.0.1 (64-bit)

## System Information

version | core-2024.2.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.6.16-haos
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1088
Downloaded Repositories | 2
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.02.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 8.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | RPC Shutdown (2.4), AirCast (4.2.0), Glances (0.21.0), Tailscale (0.16.1), Uptime Kuma (0.12.0), Network UPS Tools (0.13.0), Studio Code Server (5.15.0), Log Viewer (0.17.0), Let's Encrypt (5.0.15), MariaDB (2.6.1), phpMyAdmin (0.9.1), Advanced SSH & Web Terminal (17.2.0), File editor (5.8.0), Samba share (12.3.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 2, 2024 at 3:48 AM
-- | --
current_recorder_run | March 12, 2024 at 12:58 AM
estimated_db_size | 3.38 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When trying to find integrations or other items in the store I get a blank screen, this happens both in the app and in a browser. I try to manually add the Repos through the menu and it will say that there already available and to download them from the store. 
I mostly interact with HA through the app, and have another installation that has an older version of HACS but the same version of HA and it appears to be working as intended. Thank you!

### Reproduction steps

1. Open up the sidebar UI 
2. Start searching for an integration such as PFsense
3.
4.
...

### Screenshots

![image](https://github.com/hacs/integration/assets/35378464/a8fefd53-d834-4324-af5b-9bd7bc723473)
![image](https://github.com/hacs/integration/assets/35378464/a57088eb-2bbd-475b-9484-3da6b21e1ad9)

### Javascript logs from your browser console

```text
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features!
```

**Comment by ludeeus** [comment]
Paste your debug logs from startup of the integration

**Comment by CodeCommander** [comment]
I'm having a similar issue. I can find some integrations, but when I search for "dual" (I'm looking for this integration: https://github.com/custom-cards/dual-gauge-card ) I cannot find it. I tried filtering by lovelace and it doesn't show either. When I try to add this repo as a custom repo I get the error that tells me it is in the store, so I cannot add it. So I have to fork the repo, and then manually add my fork.

**Comment by tclemos** [comment]
> I'm having a similar issue. I can find some integrations, but when I search for "dual" (I'm looking for this integration: https://github.com/custom-cards/dual-gauge-card ) I cannot find it. I tried filtering by lovelace and it doesn't show either. When I try to add this repo as a custom repo I get the error that tells me it is in the store, so I cannot add it. So I have to fork the repo, and then manually add my fork.

I'm facing the same issue trying to add the `OpenMediaVault` integration

**Comment by grey773** [comment]
> I'm having a similar issue. I can find some integrations, but when I search for "dual" (I'm looking for this integration: https://github.com/custom-cards/dual-gauge-card ) I cannot find it. I tried filtering by lovelace and it doesn't show either. When I try to add this repo as a custom repo I get the error that tells me it is in the store, so I cannot add it. So I have to fork the repo, and then manually add my fork.

Same issue for me with https://github.com/mampfes/ha_freeair_connect

**Comment by douglaslinsmeyer** [comment]
Adding to the reported symptoms.. it looks it stops paginating and only shows the first set of things loaded.
