### ISSUE TITLE
Removed repo 'IGNORE' not working

### ISSUE THREAD

**Issue by myTselection** [hacs/integration#3551]
### Web browser

Chrome

### Web browser version

122.0.6261.95 (Official build) (64-bits)

## System Information

version | core-2024.3.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 5.4.0-173-generic
arch | x86_64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4393
Installed Version | 1.34.0
Stage | running
Available Repositories | 1409
Downloaded Repositories | 58

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 28
-- | --
resources | 41
views | 74
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 12, 2024 at 8:51 PM
-- | --
current_recorder_run | March 17, 2024 at 12:25 PM
estimated_db_size | 218.78 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Sonoff</summary>

version | 3.6.0 (8dd8af9)
-- | --
cloud_online | 11 / 16
local_online | 9 / 9

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When a repo is removed from HACS, a warning is shown at the top of the HACS screen. 
Within the warning, when clicking 'SHOW', the option 'IGNORE' and 'REMOVE' are available. Yet the 'IGNORE' option doesn't seem to work. The warning remains visible in HACS. Only logging that appears is eg:
2024-03-17 12:43:08.077 INFO (MainThread) [custom_components.hacs] Ignoring <reponame>

### Reproduction steps

1. add a hacs repo
2. the hacs repo get's removed from the official hacs repo list
3. a warning appears in hacs mentioning the repo has been removed
4. click 'SHOW'
5. click 'IGNORE'

### Screenshots

![Schermafbeelding 2024-03-17 124422](https://github.com/hacs/integration/assets/587940/64cc6f83-e6b6-4c11-ad52-9b39bea852de)
![image](https://github.com/hacs/integration/assets/587940/7a7f343f-21e0-4c59-a667-6181f7e04a36)

### Javascript logs from your browser console

```text
Uncaught (in promise) {code: 'repository_not_found', message: 'Repository with ID (djtimca/hagooglewifi) not found'}
```

### Diagnostics dump

{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2024.3.1",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Brussels",
    "os_name": "Linux",
    "os_version": "5.4.0-173-generic",
    "run_as_root": true
  },
  "custom_components": {
    "sonoff": {
      "version": "3.6.0",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "dash_cast": {
      "version": "1.0.0",
      "requirements": []
    },
    "entsoe": {
      "version": "0.0.1",
      "requirements": [
        "entsoe-py==0.5.8"
      ]
    },
    "pixometer": {
      "version": "2.1.2",
      "requirements": []
    },
    "youfone_be": {
      "version": "4.5.0",
      "requirements": []
    },
    "jnm": {
      "version": "1.4.0",
      "requirements": [
        "bs4",
        "requests"
      ]
    },
    "cozylife": {
      "version": "0.4.0",
      "requirements": []
    },
    "browser_mod": {
      "version": "2.3.0",
      "requirements": []
    },
    "techlife": {
      "version": "1.0",
      "requirements": [
        "paho-mqtt==1.6.1"
      ]
    },
    "jokes": {
      "version": "0.0.1",
      "requirements": []
    },
    "hass_cozylife_local_pull": {
      "version": "0.1.0",
      "requirements": []
    },
    "aria2": {
      "version": "0.4.1",
      "requirements": [
        "svgwrite==1.4",
        "aria2p==0.10.4"
      ]
    },
    "webrtc": {
      "version": "v3.5.1",
      "requirements": []
    },
    "localtuya": {
      "version": "5.2.1",
      "requirements": []
    },
    "totalenergiesclubcard": {
      "version": "1.2.1",
      "requirements": [
        "bs4",
        "requests"
      ]
    },
    "mass": {
      "version": "2024.3.1",
      "requirements": [
        "music-assistant==2.0.0b110"
      ]
    },
    "googlewifi": {
      "version": "0.1.34",
      "requirements": [
        "googlewifi==0.0.21"
      ]
    },
    "myenergy": {
      "version": "2.4.1",
      "requirements": [
        "bs4",
        "requests"
      ]
    },
    "ptz_camera": {
      "version": "1.0.0",
      "requirements": []
    },
    "bibliotheek_be": {
      "version": "1.6.11",
      "requirements": [
        "bs4",
        "html5lib",
        "httpx[http2]"
      ]
    },
    "hikconnect": {
      "version": "2.2.0",
      "requirements": [
        "hikconnect==1.2.0"
      ]
    },
    "config_editor": {
      "version": "4.3",
      "requirements": []
    },
    "neerslag": {
      "version": "2022.07.07.1",
      "requirements": []
    },
    "afvalbeheer": {
      "version": "5.3.0",
      "requirements": [
        "rsa",
        "pycryptodome"
      ]
    },
    "multiscrape": {
      "version": "6.5.0",
      "requirements": [
        "lxml>=4.9.1",
        "beautifulsoup4>=4.12.2"
      ]
    },
    "measureit": {
      "version": "0.5.0",
      "requirements": [
        "croniter==2.0.2"
      ]
    },
    "telenet_telemeter": {
      "version": "1.6.0",
      "requirements": [
        "beautifulsoup4",
        "html5lib"
      ]
    },
    "files": {
      "version": "1.5",
      "requirements": []
    },
    "hacs": {
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "holidays": {
      "version": "1.9.10",
      "requirements": [
        "python-dateutil>=2.8.2",
        "holidays>=0.35"
      ]
    },
    "spotcast": {
      "version": "v3.6.30",
      "requirements": []
    },
    "ssh_command": {
      "version": "1.0.0",
      "requirements": [
        "paramiko"
      ]
    },
    "audiconnect": {
      "version": "2021.1.1",
      "requirements": [
        "beautifulsoup4"
      ]
    },
    "mijntuin": {
      "version": "1.6.4",
      "requirements": [
        "bs4",
        "html5lib"
      ]
    },
    "carbu_com": {
      "version": "9.1.0",
      "requirements": [
        "bs4",
        "requests",
        "ratelimit"
      ]
    }
  },
... too long to submit in github

**Comment by ludeeus** [comment]
Enable experimental features, and this is moved to a "repair" like all other things in Home Assistant.
There it works.
