### ISSUE TITLE
"updated" column is misleading

### ISSUE THREAD

**Issue by ildar170975** [hacs/integration#3553]
### Web browser

Chrome

### Web browser version

122.0.6261.129

## System Information

version | core-2024.3.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 5.10.0-16-amd64
arch | x86_64
timezone | Europe/Moscow
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4948
Installed Version | 1.34.0
Stage | running
Available Repositories | 1419
Downloaded Repositories | 51
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 16
-- | --
resources | 37
views | 439
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 9, 2024 at 11:48
-- | --
current_recorder_run | March 18, 2024 at 22:32
estimated_db_size | 799.39 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The "update" column is misleading since it does not reflect a fact that a new release is issued:
Here all "red" plugins have "updated" like "2-3 days ago" - but in fact the last releases could be created a long time ago.

![изображение](https://github.com/hacs/integration/assets/71872483/3a3c827d-df02-4196-bf49-4a48c26839a3)

The new "experimental" presentation with default settings does not help users to see which plugins were updated and need to be re-downloaded.

### Reproduction steps

as above

### Screenshots

see above

### Javascript logs from your browser console

```text
none
```

**Comment by ludeeus** [comment]
Updated is not for when the <thing> was updated, it is when the repository was.
Once you need to update, the state of the update entities changes.

**Comment by ildar170975** [comment]
Since the "experimental" default presentation of HACS does not show a list of UPDATED plugins - I would call this "downgrading". Usability became worse than w/o enabling "experimental" features:

Here it is clearly visible which plugins were updated:

![изображение](https://github.com/hacs/integration/assets/71872483/6c8558b3-5e7e-4fde-b9e2-0d77eeb8a325)

![изображение](https://github.com/hacs/integration/assets/71872483/3efa2a7a-2087-425d-8e9f-e8f2f332a3f5)

Ofc a user can create an additional card filled with `update` entities - but it is bad that HACS is not able to show this info in a default configuration.

**Comment by ludeeus** [comment]
They show in the settings par of home assistant with all others.

**Comment by ildar170975** [comment]
If you mean "update entities are shown in Settings -> Entities":
this is rather not helpful - a user have to open EACH entity's more-info to see this entity's state:

![изображение](https://github.com/hacs/integration/assets/71872483/b94bb0a3-70be-4dcc-9036-e76f3c0286d0)

**Comment by ludeeus** [comment]
No…
They show at the top of the setting page.
And in the dedicated update panel.

**Comment by ludeeus** [comment]
Yes, that is how every update entity in home assistant show when there is an update.

**Comment by ildar170975** [comment]
> Yes, that is how every update entity in home assistant show when there is an update.

I see now.
I am using HA in Docker & never seen updates on this page; started seeing them only after switching experimental mode in HACS.
Thanks again!
