### ISSUE TITLE
HACS integration not completing.

### ISSUE THREAD

**Issue by jimm2905** [hacs/integration#3555]
## System Information

version | core-2024.3.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.74-haos
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 7.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | InfluxDB (5.0.0), Grafana (9.2.0), Node-RED (17.0.9), Advanced SSH & Web Terminal (17.2.0), File editor (5.8.0), ESPHome (2024.2.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 17, 2024 at 6:10 AM
-- | --
current_recorder_run | March 19, 2024 at 1:55 AM
estimated_db_size | 5.02 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Integration does not complete.  Getting success message but HA screen just stuck waiting.  Github shows Oauth token in place.

### Reproduction steps

1.
2.
3.
...
I have followed the standard method of installing this.  Please see the log entry below for for details.

### Debug logs

```text
Logger: homeassistant.data_entry_flow
Source: data_entry_flow.py:766
First occurred: 1:56:25 AM (1 occurrences)
Last logged: 1:56:25 AM

custom_components.hacs.config_flow::HacsFlowHandler calls async_show_progress without passing a progress task, this is not valid and will break in Home Assistant Core 2024.8. Please report it to the custom integration author
```

### Diagnostics dump

I cant get this far.

**Comment by ludeeus** [comment]
The provided logs are not the debug logs, that is just a single entry from the UI.

It looks like some network problem on your end, Is the GitHub integration working?

**Comment by jimm2905** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jimm2905** [comment]
Further investigation reveals that HACS would just not activate on a certain server hardware configuration.  Moving to a different
Proxmox server solved the problem.  HA seemed to run fine on the server in question but HACS would not activate.
