### ISSUE TITLE
Request for removal of Danielhiversen/home_assistant_min_renovasjon

### ISSUE THREAD

**Issue by kennethnilssen** [hacs/integration#3558]
### Repository

Danielhiversen/home_assistant_min_renovasjon

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Please read this, it does crash the entire HA
https://github.com/Danielhiversen/home_assistant_min_renovasjon/issues/20

### Link to issue

https://github.com/Danielhiversen/home_assistant_min_renovasjon/issues/20

**Comment by tjorim** [comment]
Not part of default HACS repository.
https://github.com/hacs/default/blob/master/integration
