### ISSUE TITLE
Husqvarna Automower in core HA

### ISSUE THREAD

**Issue by Kfrard** [hacs/integration#3560]
### Repository

Thomas55555/husqvarna_automower

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

The integration has been added to core HA (https://www.home-assistant.io/blog/2024/03/06/release-20243/#new-integrations), it is not possible to contact the author via issues because the project has been Archived and will not be developed further.
Author's Note: https://github.com/Thomas55555/husqvarna_automower/releases/tag/2024.2.0

### Link to issue

https://github.com/Thomas55555/husqvarna_automower

**Comment by renotp** [comment]
I got a message that the repository is archived, has been removed from HACS, Please visit the HACS Panel to remove it. 
Why would I get this message and what's the fix?

**Comment by ludeeus** [comment]
Because it is correct.
Remove or ignore it.
Up to you.
