### ISSUE TITLE
Request for removal of custom-components/sensor.trakt

### ISSUE THREAD

**Issue by bcutter** [hacs/integration#3561]
### Repository

custom-components/sensor.trakt

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Multiple reasons. In short: major issue, integration broken, integration not maintained.

During a major issue (https://github.com/custom-components/sensor.trakt/issues/72) it turned out this repository is unmaintained (former maintainer statement here: https://github.com/custom-components/sensor.trakt/issues/72#issuecomment-1967605941). PRs are not merged and there's no perspective on this integrations future. Because of the mentioned major issue - which could have been easily avoided months or even years ago - this integration is currently broken. Existing users are left with a broken integration, new users trying to use this integration should be protected running into the same situation.

There seems to be a basically working alternative (https://github.com/dylandoamaral/trakt-integration) which unfortunately currently lacks support for GUI based set up (https://github.com/dylandoamaral/trakt-integration/issues/94#issuecomment-1987116789) and therefore is not a straight recommendation (nowadays handling YAML really should not be the default).

### Link to issue

https://github.com/custom-components/sensor.trakt/issues/72

**Comment by tjorim** [comment]
Issue was resolved in June (version 3.0.0 and up).

**Comment by bcutter** [comment]
> Issue was resolved in June (version 3.0.0 and up).

Right. It [requires](https://github.com/custom-components/sensor.trakt/blob/master/hacs.json) HA 2024.6.0.
Sometimes all it needs is (a lot of) patience and a bit of pressure.
