### ISSUE TITLE
Removed repository 'custom-cards/upcoming-media-card' Repository is archived

### ISSUE THREAD

**Issue by mkanet** [hacs/integration#3625]
### Web browser

Microsoft Edge

### Web browser version

Version 123.0.2420.81 (Official build) (64-bit)

## System Information

version | core-2024.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.25-haos
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4652
Installed Version | 1.34.0
Stage | running
Available Repositories | 1402
Downloaded Repositories | 31

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | July 28, 2024 at 5:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-6.ui.nabu.casa
certificate_status | ready
instance_id | 2df203b5576e488bae56b0db1e7ed939
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 30.8 GB
disk_used | 14.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.13.0), Samba share (12.3.1), Mosquitto broker (6.4.0), File editor (5.8.0), Z-Wave JS (0.4.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 24
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 5, 2024 at 6:13 PM
-- | --
current_recorder_run | April 12, 2024 at 12:56 PM
estimated_db_size | 1117.03 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The Repo https://github.com/custom-cards/upcoming-media-card  was archived a couple of years ago due to inactivity; hence, was eventually removed from HACS.  **Recently, I unarchived the repo and submitted a new PR: https://github.com/hacs/default/pull/2372 to add this frontend card back to HACS.**

In the meantime, users are manually adding this repo to HACS in order to install/use it.  However, they are being prompted with the message below (which can be effectively/temporarily ignored)
![image](https://github.com/hacs/integration/assets/811008/9e7fbe2f-25da-4f42-aebc-b3b4e424570e)

The user will then click **SHOW**, followed by **IGNORE**
![image](https://github.com/hacs/integration/assets/811008/cbee80b5-ebb2-45a1-a6e1-dfde9cce696b)

**Could someone please kindly confirm that when https://github.com/hacs/default/pull/2372 is approved and merged officially (and Home Assistant is updated and restarted by the user), the above message will go away automatically; and, allow the card to be installed normally?**

If not, could someone please let me know what specifically I need to mitigate this issue?  Hopefully, it will be automatic.

### Reproduction steps

1.  Manually added `https://github.com/custom-cards/upcoming-media-card` to HACS custom repo
2. Installed it.
...

### Screenshots

![image](https://github.com/hacs/integration/assets/811008/1d3df66a-ed35-4944-82d1-e5e8dfc9c202)

### Javascript logs from your browser console

```text
N/A
```

**Comment by ludeeus** [comment]
It will be automatic.
