### ISSUE TITLE
HACS integrations are not working after HA update 2024.4.*

### ISSUE THREAD

**Issue by jf-64** [hacs/integration#3648]
### Describe the issue

**The issue:**
After I installed the update 2024.4.* series of HA, HACS integrations aren't working any more, such as:
- Alexa Media Player
- Deutscher Wetterdienst
- here_weather
- ...
- Sonoff
- Tuya

![image](https://github.com/hacs/integration/assets/76160396/54b6f11d-d6e3-496c-8fd3-b76c8a6f8696)

Even outstanding updates cannot be applied:
![image](https://github.com/hacs/integration/assets/76160396/a5ed0a6e-003b-49ff-97d6-cd2e67f431f9)
In the update dialog the button's arrow (in the bottom right) just "rotates", but nothing happens.

I think the problem started with one of the core_2024.4.0 or core_2024.3.3 updates.
Restoring the backup of the core_2024.3.3 update (partial, created by the HA update process) did not solve the issue. This is my oldest backup.
My oldest full backup was created _after_ core_2024.4.0, but restoring it didn't fix it either.

Anyone else experienced this?

All of my automations were made by Node RED, but currently nothing works. I really don't know how to fix it and I don't want to re-start from scratch...

**Current versions:**
- Home Assistant Community Store
  Integrations Version: 1.34.0
  Frontend Version: 20220906112053

- Home Assistant 
  Core
  2024.4.3
  Supervisor
  2024.04.0
  Operating System
  12.2
  Frontend
  20240404.2

**HACS debug log:**
[home-assistant_hacs_2024-04-15T17-15-20.717Z.log](https://github.com/hacs/integration/files/14983165/home-assistant_hacs_2024-04-15T17-15-20.717Z.log)

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS bot.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

**Comment by ludeeus** [comment]
Try asking on the Home Assistant Forum or discord server, this is not related to HACS.
