### ISSUE TITLE
Describe how bundling of extra folder and files feature works in documentation

### ISSUE THREAD

**Issue by ibz0q** [hacs/integration#3650]
### Describe the issue

There was an a feature requested to allow extra files (and folders?) to be bundled into a HACS package, it was answered here with https://github.com/hacs/integration/issues/924#issuecomment-586573599 suggesting it was now officially supported.

The nature of the plugin I'm working on requires folders and files, and bundling everything into JS would be infeasbile. (for reference: https://github.com/ibz0q/lovelace-bg-animation) 

Could documentation be added with information on how it works, with some examples and possible limitations?

Thank you in any case.

**Comment by ludeeus** [comment]
Using the dist directory would do that and it's all ready documented https://hacs.xyz/docs/publish/plugin#repository-structure

**Comment by ibz0q** [comment]
It seems to be working as expected! Sorry for my misunderstanding.

And Thank you for your work on HACS , the contributions are a great addition to HA.
