### ISSUE TITLE
Detected that custom integration 'hacs' accesses hass.helpers.event

### ISSUE THREAD

**Issue by TheZoker** [hacs/integration#3660]
## System Information

version | core-2024.5.0b0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.28-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4986
Installed Version | 1.34.0
Stage | running
Available Repositories | 1408
Downloaded Repositories | 21
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 28. November 2024 um 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-6.ui.nabu.casa
certificate_status | ready
instance_id | 1226553f75fe43dab92ab30487f01e1c
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3.rc1
-- | --
update_channel | beta
supervisor_version | supervisor-2024.04.4
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 30.8 GB
disk_used | 13.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Let's Encrypt (5.0.18), Terminal & SSH (9.13.0), MariaDB (2.7.1), FTP (5.0.2), WireGuard (0.10.2), Nginx Proxy Manager (1.0.1), Home Assistant Google Drive Backup (0.112.1), Advanced SSH & Web Terminal (17.2.0), Mosquitto broker (6.4.0), phpMyAdmin (0.9.1), ESPHome (2024.4.0), Studio Code Server (5.15.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 13
views | 29
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 24. April 2024 um 09:41
-- | --
current_recorder_run | 27. April 2024 um 00:11
estimated_db_size | 653.92 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Notice in logs since 2024.5 beta

### Reproduction steps

1. Update to latest 2024.5 beta

### Debug logs

```text
Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
```

**Comment by lordwizzard** [comment]
It has now made it into the general release of Home Assistant Core 2024.5.0 as of today. So there are now two issues that need attention.

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:190
First occurred: 4:57:07 PM (3 occurrences)
Last logged: 4:57:18 PM

Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues

Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

**Comment by lordwizzard** [comment]
Just some more information. There was another update to Home Assistant Core today, version 2024.5.1 and those issues are still in place.

**Comment by ludeeus** [comment]
Fixed in https://github.com/hacs/integration/pull/3608
