### ISSUE TITLE
HACS Setup: Integration does not activate

### ISSUE THREAD

**Issue by superpower10** [hacs/integration#3666]
## System Information

version | core-2024.5.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.4
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 234.0 GB
disk_used | 7.3 GB
healthy | true
supported | true
board | rpi5-64
supervisor_api | ok
version_api | ok
installed_addons | Matter Server (5.6.0), Advanced SSH & Web Terminal (17.2.0), Studio Code Server (5.15.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 2. Mai 2024 um 07:38
-- | --
current_recorder_run | 2. Mai 2024 um 15:13
estimated_db_size | 0.58 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Followed Instruction Word-by-Word

Activation of Hacs when setting up the integration doesn't complete.

### Reproduction steps

1. Installed has via Script on an absolute new Home Assistant. Nothing else installed on it
2. Restart Home Assistant 
3. Deleted Browser-Historie and everything else completly
4. Went to Settings - Integration - Add Integration - Filter with HACS - Click on Hats
5. Dialog with link to GitHub open
6. Click on Github-Link
7. Signed in by Github
8. Paste Code from Integration-Dialog
9. Hit accepted
10. Github-Dialog says that its now connected/allowed
11. Went back to Home Assistant 
12. Turning for minutes nothing happens

Tried it with Safari, Chrome and Opera.

Also waited for hours. Red all other issues. Did not help

### Debug logs

```text
Logger: homeassistant.data_entry_flow
Quelle: data_entry_flow.py:805
Erstmals aufgetreten: 15:14:12 (1 Vorkommnisse)
Zuletzt protokolliert: 15:14:12

custom_components.hacs.config_flow::HacsFlowHandler calls async_show_progress without passing a progress task, this is not valid and will break in Home Assistant Core 2024.8. Please report it to the custom integration author
```

### Diagnostics dump

None here. It is not installed.

**Comment by bealex** [comment]
Same problem. Can't install HACS :( It just waits for device activation forever, without ability to do anything (no "Submit" button is there in the dialog)

**Comment by jcasarini** [comment]
Hi, had the same problem, just solved it with a workaround:

1. Go to the Terminal and download the install script but do not execute it right away:
`wget -O hacs.sh - https://get.hacs.xyz`

2. Edit the hacs.sh file with your prefered text editor. 

3. In line 65 replace de download URL to version 1.33 and save: 
`wget "https://github.com/hacs/integration/releases/download/1.33.0/hacs.zip"`

4. Run the updated install script:
`bash hacs.sh`

5. Restart HomeAssistant.

6. Follow the usual steps for activation.

7. Update HACS in the usual manner.



> Same problem. Can't install HACS :( It just waits for device activation forever, without ability to do anything (no "Submit" button is there in the dialog)

**Comment by Onolisk** [comment]
another solution is to downgrade HA, install HACS, upgrade HA. Just did this now and it worked for me and others on reddit.
`ha core update --version 2024.1.0`

**Comment by kaford88** [comment]
> Hi, had the same problem, just solved it with a workaround:
> 
> 1. Go to the Terminal and download the install script but do not execute it right away:
>    `wget -O hacs.sh https://get.hacs.xyz`
> 2. Edit the hacs.sh file with your preferred text editor.
> 3. In line 65 replace de download URL to version 1.33.0 and save:
>    `wget "https://github.com/hacs/integration/releases/download/1.33.0/hacs.zip"`
> 4. Run the updated install script:
>    `bash hacs.sh`
> 5. Restart HomeAssistant.
> 6. Follow the usual steps for activation (About the "Submit" button you mentioned, the documentation is outdated, there's no such button anymore).
> 7. Update HACS in the usual manner.
> 
> > Same problem. Can't install HACS :( It just waits for device activation forever, without ability to do anything (no "Submit" button is there in the dialog)

genius.....ive spent all day on this until i saw this post. THanks so much.

**Comment by jcasarini** [comment]
I prefer downgrading the plugin rather than the whole platform honestly.

In any case I'm pretty sure [https://github.com/hacs/integration/issues/3555 ] mentioned by @DanielMazurFL4RE is related, possibly the same, @ainmosni. This is definitely not hardware related. 

As this was a new instance I'm installing for my brother I tried doing it in one of my hypervisors as it's recommended in that case but that didn't fix it. That's when I thought about examining the install script.


> another solution is to downgrade HA, install HACS, upgrade HA. Just did this now and it worked for me and others on reddit. `ha core update --version 2024.1.0`

**Comment by DB-HASS** [comment]
> Hi, had the same problem, just solved it with a workaround:
> 
Confirm this worked for me, too.  Right after everything installed, it prompted for an update to 1.34 which also went smoothly.

**Comment by superpower10** [comment]
Thank you very much. It works now!

P.S.: After the installation and update I had to completely restart the PI and clear Browser Cache again so HACS looks like it should

**Comment by ludeeus** [comment]
Home Assistant 2024.5.2 was released yesterday, which includes a fi for this.
Update to that version or newer before trying again.
