### ISSUE TITLE
Question - does "Enable experimental features" auto update?

### ISSUE THREAD

**Issue by sanderlv** [hacs/integration#3667]
## System Information

version | core-2024.4.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.25-haos
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4994
Installed Version | 1.34.0
Stage | running
Available Repositories | 1407
Downloaded Repositories | 47
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.4
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 235.5 GB
disk_used | 102.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Glances (0.21.1), Node-RED (17.0.12), Traccar (0.25.0), Grafana (9.2.2), InfluxDB (5.0.0), Portainer (2.0.0), Mosquitto broker (6.4.0), NoPWNed (2), Advanced SSH & Web Terminal (17.2.0), Studio Code Server (5.15.0), Z-Wave JS (0.5.0), Samba Backup (5.2.0), MariaDB (2.7.1), ESPHome (2024.4.0), SQLite Web (4.1.2), Samba share (12.3.1), MQTT Explorer (browser-1.0.1), Zigbee2MQTT (1.37.0-1), Piper (1.5.0), Whisper (2.0.0), RPC Shutdown (2.5), Paperless-ngx (2.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 12
-- | --
resources | 29
views | 25
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 24, 2024 at 04:58
-- | --
current_recorder_run | April 24, 2024 at 06:58
estimated_db_size | 4285.78 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

*** QUESTION ***

Since I ticked "Enable experimental features" all my entries auto update.

Before I had to do so manually each entry time to time.

I enabled experimental because I wanted to get a notification via the blueprint automation by using "update.hacs_update service in it. 

Is it normal behavior with "experimental features" tha HACS entries auto update???

The blueprint:
https://community.home-assistant.io/t/update-notifications-core-hacs-supervisor-and-addons-now-a-blueprint/182295

To be clear, I do not (at least I think) use a service to update HACS entries.

![image](https://github.com/hacs/integration/assets/16528916/7136a8ab-f2c6-4c76-b57b-cf65eeda7b66)
![image](https://github.com/hacs/integration/assets/16528916/4f499d89-5c44-44c8-80a2-711f089eb8e9)

I asked here at first:
https://community.home-assistant.io/t/hacs-auto-updates-did-i-miss-something/724164

### Reproduction steps

Not needed

### Debug logs

```text
not needed
```

**Comment by ludeeus** [comment]
No.
The “updated” is when yhe repository was updated on GitHub, not on your instance.

**Comment by sanderlv** [comment]
Clear, thanks. When then will I get the option to update on my instance? As before?

**Comment by ludeeus** [comment]
Yes

**Comment by sanderlv** [comment]
The question was "when then" :-)... I do not see any updates as before...?
