### ISSUE TITLE
 Request for removal of rospogrigio/localtuya

### ISSUE THREAD

**Issue by Shredder5262** [hacs/integration#3669]
### Repository

rospogrigio/localtuya

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Produces a lot of 
![2024-05-02 20_14_57-Settings – Home Assistant - Vivaldi](https://github.com/hacs/integration/assets/59770346/305cfdb7-da09-4d5c-b612-ce419582b574)
errors that do not relate to devices that i have and no response from dev.

### Link to issue

https://github.com/rospogrigio/localtuya/issues/1650

**Comment by ludeeus** [comment]
Still, over 6 months to that is a problem, and author is still active <https://github.com/rospogrigio/localtuya/commit/d2fa4dc2a0306a9721c5660f163a3bf84b075f28>
