### ISSUE TITLE
HACS github confirmation failing on  async_show_progress

### ISSUE THREAD

**Issue by MarkusWynand** [hacs/integration#3670]
### System Health details

Core
2024.5.1
Supervisor
2024.04.4
Operating System
11.5
Frontend
20240501.0

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

HACS is not currently loading into Homeassisant running supervisor on Pi5. Following error message discribes the error:

Logger: homeassistant.data_entry_flow
Source: data_entry_flow.py:805
First occurred: 5:35:11 PM (1 occurrences)
Last logged: 5:35:11 PM

custom_components.hacs.config_flow::HacsFlowHandler calls async_show_progress without passing a progress task, this is not valid and will break in Home Assistant Core 2024.8. Please report it to the custom integration author

This is found after trying to authenticate git device activation.

### Reproduction steps

1.New Homeassistant setup on Pi5 
2.New HACS instalation via SSH 
3.Device authentication via github

...

### Debug logs

```text
Logger: homeassistant.data_entry_flow
Source: data_entry_flow.py:805
First occurred: 5:35:11 PM (1 occurrences)
Last logged: 5:35:11 PM

custom_components.hacs.config_flow::HacsFlowHandler calls async_show_progress without passing a progress task, this is not valid and will break in Home Assistant Core 2024.8. Please report it to the custom integration author
```

**Comment by ARR4NN** [comment]
Anyone know a work around for this so i can install HACS?

**Comment by guenther-seifert** [comment]
I have the same problem

**Comment by Pinpin54** [comment]
Same problem

**Comment by 641i130** [comment]
Same problem

**Comment by rextor93** [comment]
same issue

**Comment by nguyenvanphuc0497** [comment]
I have the same problem
