### ISSUE TITLE
When accesing HACS google chrome (or other chromium browser) completly freezes

### ISSUE THREAD

**Issue by tdeboss** [hacs/integration#3671]
### Web browser

Google Chrome, Edge and Chromium

### Web browser version

124.0.6367.119 (64bit)

## System Information

version | core-2024.5.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.25-haos
arch | x86_64
timezone | Europe/Belgrade
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4981
Installed Version | 1.34.0
Stage | running
Available Repositories | 1399
Downloaded Repositories | 23
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.4
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 93.8 GB
disk_used | 9.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2024.4.2), Node-RED (17.0.12), Network UPS Tools (0.13.0), Z-Wave JS UI (3.6.0), Advanced SSH & Web Terminal (17.2.0), openWakeWord (1.10.0), Piper (1.5.0), Home Assistant Google Drive Backup (0.112.1), Studio Code Server (5.15.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 18
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 27, 2024 at 15:30
-- | --
current_recorder_run | May 5, 2024 at 22:53
estimated_db_size | 63.83 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When I try to do anything in HACS it completely freezes. Untill today afternoon, everything worked Ok, but even after multiple reboots of my host machine and my client machine nothing seems to work. The same happens even in incognito mode.
Everything else in HASS works as expected, but as soon as i enter HACS, all chrome windows freeze completely in max. 10 seconds and I need to kill Chrome process to close Chrome.

### Reproduction steps

1. Do normal things in Home Assistant
2. Enter HACS view
3. I tried with a few repositories for example: HUE icons etc.
4. Everything completely freezes, will not download, will not change tabs, will not close Chrome "the normal way", have to end task in windows.

### Screenshots

Nothing to screenshot, just a freezed chrome.

### Javascript logs from your browser console

```text
Can't do anything, since everything completely freezes
```

### Diagnostics dump

2024-05-05 22:53:45.404 DEBUG (MainThread) [custom_components.hacs] There are 6 scheduled recurring tasks
2024-05-05 22:53:45.404 INFO (MainThread) [custom_components.hacs] Loading removed repositories
2024-05-05 22:53:45.480 INFO (MainThread) [custom_components.hacs] Loading known repositories
2024-05-05 22:53:45.480 DEBUG (MainThread) [custom_components.hacs] Fetching updated content for theme
2024-05-05 22:53:45.480 DEBUG (MainThread) [custom_components.hacs] Fetching updated content for integration
2024-05-05 22:53:45.481 DEBUG (MainThread) [custom_components.hacs] Fetching updated content for template
2024-05-05 22:53:45.481 DEBUG (MainThread) [custom_components.hacs] Fetching updated content for plugin
2024-05-05 22:53:45.608 INFO (MainThread) [custom_components.hacs] Stage changed: running
2024-05-05 22:53:45.634 DEBUG (MainThread) [custom_components.hacs] <QueueManager> The queue is empty
2024-05-05 22:53:45.634 DEBUG (MainThread) [custom_components.hacs] <HACSStore async_save_to_store> Did not store data for 'hacs.critical'. Content did not change
2024-05-05 22:53:45.634 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue

**Comment by ludeeus** [comment]
Tried Chrome and Edge (current and beta) on MacOS and Windows 11. Im unable to reproduce this.
Please add a screen recording, and the last 10 websocket messages from the network tab.

**Comment by tdeboss** [comment]
Hi, thanks for the response. Will do in the afternoon.
Kind regards



V V pon., 6. maj 2024 ob 05:18 je oseba Joakim Sørensen <
***@***.***> napisala:
