### ISSUE TITLE
Ignore button in archived message not working

### ISSUE THREAD

**Issue by erkr** [hacs/integration#3677]
### Web browser

Safari

### Web browser version

Iphone iOS 17.14.1

## System Information

version | core-2024.5.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1402
Downloaded Repositories | 39

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 219.4 GB
disk_used | 63.8 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Mosquitto broker (6.4.0), MariaDB (2.7.1), Network UPS Tools (0.13.0), Home Assistant Google Drive Backup (0.112.1), InfluxDB (5.0.0), FTP (5.0.2), phpMyAdmin (0.9.1), Advanced SSH & Web Terminal (17.2.0), Music Assistant BETA (2.0.0b148), MQTT Explorer (browser-1.0.3), WireGuard (0.10.2), Grafana (9.2.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 28
views | 31
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 4, 2024 at 08:58
-- | --
current_recorder_run | May 8, 2024 at 22:47
estimated_db_size | 732.12 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Pressing ignore in this dialog does nothing. It should close the dialog and I hope make the message disappear 

### Reproduction steps

1. Press show to Open the dialog of an archived repository 
2.
3.
...

### Screenshots

![image](https://github.com/hacs/integration/assets/4363599/30f5ce5c-d8c9-4ef5-b55c-ab35c5388bbd)

### Javascript logs from your browser console

```text
Don't no how to get them in the ios companion app
```

**Comment by ludeeus** [comment]
This will not be fixed as it has been removed in the upcoming UI.
Enable experimental features if you want that now.

**Comment by erkr** [comment]
That is perfectly fine. I tried to enable experimental destroys in the past. But that was not working for me (can't recall exacted what failed but I lost my repositories in that mode. Invalid urls?!)
