### ISSUE TITLE
Notification for available updates missing

### ISSUE THREAD

**Issue by Juice47** [hacs/integration#3678]
### System Health details

Hi, i happens once in a while, that updates for HACS are needed to match HA updates. However there is no notification that updates are available without checking HACS itself. The problem is that some functions are not working and you have to investigate in problem determination.

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

incompatibility HACS and HA

### Reproduction steps

1.
2.
3.
...
N/A

### Debug logs

```text
N/A
```

### Diagnostics dump

N/A

**Comment by tjorim** [comment]
Have you enabled experimental options? That one changes to native Home Assistant update entities. Notifications can be created with an automation.

**Comment by tomlut** [comment]
I'm using the experimental option. 

The only way I get notification of available updates is if I restart Home Assistant or if I visit the integration's page in HACS.
