### ISSUE TITLE
Request for removal of websylv/homeassistant-meteoswiss

### ISSUE THREAD

**Issue by vinzent** [hacs/integration#3723]
### Repository

websylv/homeassistant-meteoswiss

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

I'm unable to add the integration. Settings -> Integrations -> Add integrations -> Meteo Swiss -> boom: ` Der Konfigurationsfluss konnte nicht geladen werden: 500 Internal Server Error Server got itself in trouble `

Reading the https://github.com/websylv/homeassistant-meteoswiss/issues/86 open since august 2023 it seems this won't be fixed. The comment here indicates https://github.com/websylv/homeassistant-meteoswiss/issues/88#issuecomment-1793449794 nobody is able to merge in this repo.

### Link to issue

https://github.com/websylv/homeassistant-meteoswiss/issues/86

**Comment by ludeeus** [comment]
Removed in https://github.com/hacs/default/pull/2682
