### ISSUE TITLE
Back in time after Re-Enabling experimental mode

### ISSUE THREAD

**Issue by erkr** [hacs/integration#3729]
## System Information

version | core-2024.5.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4994
Installed Version | 1.34.0
Stage | running
Available Repositories | 1407
Downloaded Repositories | 40
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 219.4 GB
disk_used | 62.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Mosquitto broker (6.4.0), MariaDB (2.7.1), Network UPS Tools (0.13.0), Home Assistant Google Drive Backup (0.112.1), InfluxDB (5.0.0), FTP (5.0.2), phpMyAdmin (0.9.1), Advanced SSH & Web Terminal (18.0.0), MQTT Explorer (browser-1.0.3), WireGuard (0.10.2), Grafana (10.0.0), Music Assistant (2.0.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 29
views | 32
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 24, 2024 at 11:03
-- | --
current_recorder_run | May 27, 2024 at 19:40
estimated_db_size | 712.92 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Well I went through the rabbit hole after re-enabling experimental mode today.
(Besides the need to clear the brower cache, to get rid of 'not loaded in lovelace' errors, and get rid off a mixed old vs experimental UI), I encountered a configuration bug when switching between these modes!
I'm convinced it is related  too the fact I had experimental mode enabled before!
During me previous attempt to enable the mode, the  "not loaded in lovelace" scared me off. So I Quickly decided to disable the experimental mode again.
When I re-enabled experimental mode today, I went 'administratively'  back in time! HACS loaded the config as it was during  my previous attempt: The UI showed the components and versions as present a year ago, instead of my current config. 
It is purely the administrative side that is wrong, as the right components and versions in the custom folders are still there (so HA kept at least running with the right  components)
In order to fix the HACS administration, I re-played all installs, update and removes as done after the previous attempt.
This is really not nice. The current configuring should be migrated.

### Reproduction steps

1. Enable the mode
2. Make config changes and likely a restart 
3. Disable the mode 
4. Make More changes and wait for Donnie updates
5. Re-enable the mode
6. Enjoy the mess
...

### Debug logs

```text
Na
```

### Diagnostics dump

Na

**Comment by ludeeus** [comment]
The current config is migrated, but not if you switch back and forth, it can not know that.

**Comment by erkr** [comment]
I'm disapointed.  in my case there was a year between switching. That is not a wierd scenario, but it horribly fails. 

The fix doesn't need to be complex!
Just flush any existing config for the new mode before migrating the old config to new. 
Not perfect but much better then reviving a config of a year ago!
