### ISSUE TITLE
FileNotFoundError in scripts/remove_repository

### ISSUE THREAD

**Issue by ElVit** [hacs/integration#3747]
## System Information

version | core-2024.5.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.29-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4998
Installed Version | 1.34.0
Stage | running
Available Repositories | 1468
Downloaded Repositories | 41
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 62.3 GB
disk_used | 30.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Matter Server (6.0.0), Samba share (12.3.1), ESPHome (2024.5.4), MariaDB (2.7.1), Bitwarden secrets for Home Assistant (1.4.6), Filebrowser (2.23.0_14), porcupine1 (1.2.0), Piper (1.5.0), vosk (1.6.0), Whisper (2.1.0), openWakeWord (1.10.0), Z-Wave JS UI (3.6.0), snowboy (1.2.1), Music Assistant (2.0.4), Zigbee2MQTT (1.37.1-1), Home Assistant Google Drive Backup (0.112.1), Mailserver (2.0.6), Mosquitto broker (6.4.1), Node-RED (17.0.12), Unraid API-RE (2.0), phpMyAdmin (0.9.1), Portainer (2.20.1), Samba server (1.3.1), Studio Code Server (5.15.0), WebDAV server (1.2.3), WebDAV server (1.2.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 26
views | 40
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 2. Mai 2024 um 06:11
-- | --
current_recorder_run | 29. Mai 2024 um 15:36
estimated_db_size | 5955.98 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I want to remove a netdaemon integration from hacs.
If I run the `remove_repository` I get the error `FileNotFoundError`.

I am not sure if this is the right place for this issue, but I could not find a better issue tpye.

### Reproduction steps

➜  scripts git:(remove_netdaemon-notify-on-update) ./remove_repository
Repository: ElVit/netdaemon-notify-on-update
Reason: netdaemon apps are deprecated
Removal type: remove
Link to more information: https://github.com/ElVit/netdaemon-notify-on-update/issues/5
ElVit/netdaemon-notify-on-update
netdaemon apps are deprecated
remove
https://github.com/ElVit/netdaemon-notify-on-update/issues/5
Traceback (most recent call last):
  File "/share/github/default/scripts/./remove_repo.py", line 55, in <module>
    with open(category, "r") as cat_file:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'appdaemon'

### Debug logs

```text
-
```

**Comment by ludeeus** [comment]
You need to be in the root of the repository when executing that, not in the scripts directory.

**Comment by ElVit** [comment]
Thanks for the hint. 
It worked now.
