### ISSUE TITLE
Unable to import component: No module named 'custom_components.hacs.hacs_frontend'

### ISSUE THREAD

**Issue by SABisset** [hacs/integration#3761]
## System Information

version | core-2024.5.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.29-haos
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 42

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 28.0 GB
disk_used | 4.9 GB
healthy | true
supported | true
board | green
supervisor_api | ok
version_api | ok
installed_addons | Matter Server (6.0.0), File editor (5.8.0), Samba share (12.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 24 May 2024 at 20:43
-- | --
current_recorder_run | 3 June 2024 at 17:40
estimated_db_size | 148.09 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Bare with me - I'm new to this!
I've installed HACS following the instructions, and set up the config in Configuartion.yaml 
hacs:
  token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

however this fails to load with the following - Setup failed for custom integration 'hacs': Unable to import component: No module named 'custom_components.hacs.hacs_frontend

log below.

### Reproduction steps

1. HACS downloaded and installed as per https://manifest--hacs.netlify.app/installation/manual/
2. HA restarted
3. token generated
4. configuration.yaml updated as above
5. HA reboot
6. error as described
...

### Debug logs

```text
Logger: homeassistant.setup
Source: setup.py:322
First occurred: 17:40:19 (1 occurrences)
Last logged: 17:40:19

Setup failed for custom integration 'hacs': Unable to import component: No module named 'custom_components.hacs.hacs_frontend'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 322, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1006, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 986, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1046, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 144, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/hacs/__init__.py", line 31, in <module>
    from .frontend import async_register_frontend
  File "/config/custom_components/hacs/frontend.py", line 10, in <module>
    from .hacs_frontend import VERSION as FE_VERSION, locate_dir
ModuleNotFoundError: No module named 'custom_components.hacs.hacs_frontend'
```

### Diagnostics dump

n/a - won't load

**Comment by ludeeus** [comment]
Try these instructions instead (they are actually valid)

https://experimental.hacs.xyz/docs/use/download/prerequisites/
