### ISSUE TITLE
Request for removal of UI-Lovelace-Minimalist/UI

### ISSUE THREAD

**Issue by awcab** [hacs/integration#3763]
### Repository

UI-Lovelace-Minimalist/UI

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Installing causes HA lock for several minutes then crash.  The project seems to be abandoned.  No response to issues.

### Link to issue

https://github.com/UI-Lovelace-Minimalist/UI/issues/1493

**Comment by wilbiev** [comment]
I fixed two issues of the UI Minimalist integration with my limited knowledge of Python and Home Assistant. You can find the modified files __init__.py and base.py in my GitHub repository https://github.com/wilbiev/UI/tree/main/custom_components/ui_lovelace_minimalist
The solved issues are the hanging (problem in the reload of the integration) and the log messages 'Detected blocking call'

**Comment by Luke15153** [comment]
There is a new release available fixing these issues. See [https://github.com/UI-Lovelace-Minimalist/UI/releases/tag/v1.3.10](url)

No need to remove UI-Lovelace-Minimalist/UI

**Comment by frenck** [comment]
Yup! https://github.com/UI-Lovelace-Minimalist/UI/releases/tag/v1.3.10
