### ISSUE TITLE
How to attach hacs-frontend to Home Assistant instance ?

### ISSUE THREAD

**Issue by EastWoodYang** [hacs/integration#3765]
### Describe the issue

After spin up the [devcontainer](https://hacs.xyz/docs/developer/devcontainer), and run `yarn start`,

I can't open `http://localhost:5000`, I guess I missed something. can anyone help me? 

How to attach hacs-frontend(http://localhost:5000) to Home Assistant instance ?

### Screenshots

<img width="2047" alt="image" src="https://github.com/hacs/integration/assets/9335046/fc11b9e1-44af-4222-bc75-df5219bb8394">

**Comment by ludeeus** [comment]
You use the `-f` argument to the integration develop script to point to the directory of the frontend.
Like `scripts/develop -f /workspaces/frontend`

<https://next.documentation-98o.pages.dev/docs/contribute/frontend/>

**Comment by EastWoodYang** [comment]
Hi @ludeeus,

I still can't attach development frontend to integration instance by using the `-f` flag.

`scripts/develop -f /workspaces/frontend` or `scripts/develop -f /Users/adong/Workspace/hacs/frontend`

`integration` local path: `/Users/adong/Workspace/hacs/integration`
`frontend` local path: `/Users/adong/Workspace/hacs/frontend`

thank you in advance !

![image](https://github.com/hacs/integration/assets/9335046/2f1384bb-96cd-483d-a83b-acac49115f83)

**Comment by ludeeus** [comment]
`/Users/adong/Workspace/hacs/` will not exist inside the container.
