### ISSUE TITLE
Deprecation Warning in hacs/base.py

### ISSUE THREAD

**Issue by jimjaeger** [hacs/integration#3767]
## System Information

version | core-2024.6.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.28-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4961
Installed Version | 1.34.0
Stage | running
Available Repositories | 1393
Downloaded Repositories | 4
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 219.3 GB
disk_used | 8.8 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi5-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (18.0.0), Log Viewer (0.17.0), MQTT Explorer (browser-1.0.3), File editor (5.8.0), Studio Code Server (5.15.0), Traccar (0.25.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 30. Mai 2024 um 18:34
-- | --
current_recorder_run | 7. Juni 2024 um 09:48
estimated_db_size | 604.21 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Hi there is a deprecation warning in HA log for hacs/base.py.

WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

### Reproduction steps

1. Install HACS
2. Open HA Log

### Debug logs

```text
-
```

**Comment by jimjaeger** [comment]
I am curious why the issue has been closed immediately...

**Comment by ludeeus** [comment]
![image](https://github.com/hacs/integration/assets/15093472/68845ae1-12de-49f8-a6ef-db0d9e76a8a7)

**Comment by jimjaeger** [comment]
Ah ok, I searched for base.py but did not find a duplicate. Good to see that it is already adressed. Thanks.
