### ISSUE TITLE
Domain "update" disappeared?

### ISSUE THREAD

**Issue by oywino** [hacs/integration#3781]
## System Information

version | core-2024.6.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 5.10.60-qnap
arch | x86_64
timezone | Europe/Oslo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1456
Downloaded Repositories | 27

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 14
views | 17
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 7, 2024 at 9:46 AM
-- | --
current_recorder_run | June 11, 2024 at 8:29 PM
estimated_db_size | 1365.19 MiB
database_engine | mysql
database_version | 11.4.2

</details>

<details><summary>Sonoff</summary>

version | 3.7.3 (e240aaf)
-- | --
cloud_online | 0 / 0
local_online | 1 / 1

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

About a month ago, I installed a custom:auto-entites card to display a list of all updates, and it worked very well - for a while.
Then one day, after updating HACS (I can't remember exactly from what version - to what version), then all my HACS entitles belonging to the domain;` update`, went unavailable. The error message says that HACS no longer provides this domain.  
`Update `entities from other integrations continue to work as expected though.

Is this by design now, or am I  just doing something wrong?
My HACS version is 1.34.0
My HA version is 2024.6.2

### Reproduction steps

This issue is not something that happens as a result of some action(s), thus it is present all the time and no steps are required to reproduce it.

### Debug logs

```text
This issue is not something that can be  found in the logs. It doesn't happen or occur at some specific point during startup. The logs do not contain any useful information
```

### Diagnostics dump

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:307
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 5:52:41 PM (2 occurrences)
Last logged: 5:54:25 PM

[140021230023968] Error handling message: expected str for dictionary value @ data['path']. Got None (invalid_format) by from 192.168.1.223 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0)

**Comment by ludeeus** [comment]
You need to turn experimental features back on to get that.
