### ISSUE TITLE
Request for removal of ekutner/home-connect-hass

### ISSUE THREAD

**Issue by bill1705** [hacs/integration#3792]
### Repository

ekutner/home-connect-hass

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

**Comment by ludeeus** [comment]
This has nothing to do with HACS.
Since you posted your token to that system in clear text, you need to ensure that you revoke it.
