### ISSUE TITLE
hacs accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11

### ISSUE THREAD

**Issue by bruvv** [hacs/integration#3805]
## System Information

version | core-2024.6.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1392
Downloaded Repositories | 25

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 457.7 GB
disk_used | 140.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Tautulli (4.0.1), Samba share (12.3.1), InfluxDB (5.0.0), Ombi (4.43.5), FlareSolverr (3.3.20), MariaDB (2.7.1), phpMyAdmin (0.9.1), ESPHome (2024.6.1), Node-RED (18.0.0), Zigbee2MQTT (1.38.0-1), Mosquitto broker (6.4.1), Whoogle Search (0.8.4-3), Epic Games Free (debian-2024-06-16), Home Assistant Google Drive Backup (0.112.1), Castsponsorskip (0.7.4), Studio Code Server (5.15.0), Whatsapper (2024.1.30), Signal Messenger (0.84.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 12
views | 16
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 5, 2024 at 22:55
-- | --
current_recorder_run | June 23, 2024 at 10:23
estimated_db_size | 2895.83 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

```
WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
```

### Reproduction steps

Just start the latest home assistant

**Comment by MajorAutomation** [comment]
I am having the same issues.
