### ISSUE TITLE
Validation fails when a brand gets moved from custom to core

### ISSUE THREAD

**Issue by andrew-codechimp** [hacs/integration#3812]
### Describe the issue

I have just had my custom integration domain sort of sherlocked by core, this means the validation for brands fails as the icons have moved.

frenck told me to take it up here as the icon will still work for hacs, it's just the validation that's the issue.  I think the validation needs to be changed to support core and custom locations so a custom integration can override a core one.

https://github.com/home-assistant/brands/pull/5581

### Link to action run

https://github.com/andrew-codechimp/HA-Mealie/actions/runs/9647678240/job/26607055465

### Link to action configuration

https://github.com/andrew-codechimp/HA-Mealie/blob/main/.github/workflows/validate.yml

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
This is behaving as designed.
You can turn of the check for “brands” if you are reusing a core domain.
