### ISSUE TITLE
Download with symlinks generates invalid file

### ISSUE THREAD

**Issue by duhow** [hacs/integration#3832]
## System Information

version | core-2024.6.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/Madrid
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4977
Installed Version | 1.34.0
Stage | waiting
Available Repositories | 1461
Downloaded Repositories | 20
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 30.8 GB
disk_used | 23.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.1), TasmoAdmin (0.30.3), ESPHome (2024.6.1), Advanced SSH & Web Terminal (18.0.0), MariaDB (2.7.1), snapcast-server (latest), Grocy (e232230), Vosk (0.0.15), Piper (1.5.0), Matter Server (6.1.2), openWakeWord (1.10.0), Whisper (2.1.0), AppDaemon (0.16.6), Music Assistant BETA (2.1.0b6)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 4
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 29 de maig de 2024, a les 20:44
-- | --
current_recorder_run | 27 de juny de 2024, a les 16:36
estimated_db_size | 957.94 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When downloading a integration repository non-zipped from GitHub, if the repository contains a **symlinked** file, HACS downloads it as **text**.

Example:
- `en.json` -> `../strings.json`
- File `en.json` contains the literal text `../strings.json`, instead of being a **symlink** file.

### Reproduction steps

- Download a custom_component which contains a symlink file
- The file is no longer a symlink

### Debug logs

```text
N/A
```

**Comment by ludeeus** [comment]
This is correct, HACS uses the github API.
For symlinks, you need to use git CLI.
