### ISSUE TITLE
Redownload version selection wont select selection

### ISSUE THREAD

**Issue by Mariusthvdb** [hacs/integration#3833]
### Web browser

Safari Mac

### Web browser version

17.5

## System Information

version | core-2024.7.0b3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.29-haos
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4940
Installed Version | 1.34.0
Stage | running
Available Repositories | 1398
Downloaded Repositories | 43
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 31 augustus 2024 om 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-5.ui.nabu.casa
certificate_status | ready
instance_id | f51092d0098f40faa50dfd391c4bf925
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | beta
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 458.4 GB
disk_used | 29.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Log Viewer (0.17.0), Samba share (12.3.1), Terminal & SSH (9.14.0), Mosquitto broker (6.4.1), Z-Wave JS (0.6.2), ESPHome (2024.6.3), Studio Code Server (5.15.0), Home Assistant Google Drive Backup (0.112.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 10
-- | --
resources | 23
views | 117
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 14 juni 2024 om 21:28
-- | --
current_recorder_run | 28 juni 2024 om 13:23
estimated_db_size | 2770.20 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

as title, selecting a version ('main' in this case) in the dropdown does not roll up to Main, but the v0.6.2 version remains selected

### Reproduction steps

1. click dropdown
2. select 'main'
3. see result
...

### Screenshots

select 'main' (cant screenshot that because it immediately rolls up again):

<img width="556" alt="Scherm­afbeelding 2024-06-28 om 13 20 16" src="https://github.com/hacs/integration/assets/33354141/8975da2b-190d-43dd-83bd-bca7dcb8d28d">

result:

<img width="555" alt="Scherm­afbeelding 2024-06-28 om 13 36 55" src="https://github.com/hacs/integration/assets/33354141/7851309a-487b-4003-8400-0a990885be51">

### Javascript logs from your browser console

```text
nothing in the log, it is completely empty
```

**Comment by ludeeus** [comment]
This is fixed in dev, and will be removed in the next version 👍
