### ISSUE TITLE
HACS download fails

### ISSUE THREAD

**Issue by enoch85** [hacs/integration#3842]
### System Health details

TBA

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I don't know if this is the correct repo to post the issue, but I'm having issues downloading a [certain HACS integration](https://github.com/elden1337/hass-peaqhvac/issues/113) since the download seems to get malformed.

I'm not home right now, so I can't add all the info needed here, but will update later tonight.

### Reproduction steps

1. Try to download hass-peaqhvac within HACS
2. Notice that it fails
...

The real link should be  https://github.com/elden1337/hass-peaqhvac/releases/download/3.0.1/peaqhvac.zip but HACS tried to download  https://github.com/elden1337/hass-peaqhvac/releases/download/tags/3.0.1/peaqhvaq.zip (notice the tags addition).

### Debug logs

```text
This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:986
integration: HACS (documentation, issues)
First occurred: 08:18:39 (1 occurrences)
Last logged: 08:18:39

<Integration elden1337/hass-peaqhvac> Failed to download https://github.com/elden1337/hass-peaqhvac/releases/download/tags/3.0.1/peaqhvaq.zip
```

**Comment by ludeeus** [comment]
Report this to the author.
<https://github.com/elden1337/hass-peaqhvac/blob/main/hacs.json#L5>

**Comment by enoch85** [comment]
Hmm, I'm not quite sure since the download fails due to missing `/tags/` in the URL.

Do you mean that the author should change the code somehow to remove `/tags/` in the URL? The line you posed are correct from my understanding, since the actual zip is named what's in the code.

**Comment by ludeeus** [comment]
No, that is not it, the author say the filename is `peaqhvaq.zip` but it should be `peaqhvac.zip`.

**Comment by enoch85** [comment]
Thanks! I'll send a PR.
