### ISSUE TITLE
"Learn more" Link in the reinstall dialog leads to 404 - not found

### ISSUE THREAD

**Issue by ralle12345** [hacs/integration#3845]
### Web browser

Firefox

### Web browser version

1127.0.2

## System Information

version | core-2024.6.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.0-22-amd64
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4989
Installed Version | 1.34.0
Stage | running
Available Repositories | 1396
Downloaded Repositories | 69
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 48
views | 24
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 7. Mai 2024 um 13:30
-- | --
current_recorder_run | 2. Juli 2024 um 08:14
estimated_db_size | 4555.92 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When reinstalling an integration from the three dosts menu on teh right a dialog is opened with a warning that the version chooser will go away in a future version. The "learn more" link leads to a non-existing page 

### Reproduction steps

1. Navigate to HACS
2. open the overflow menu on ahy installed integration
3. choose reinstall "Erneut herunterladen"
4. Click on "learn more"
5. See "404 - Not found" on your screen (URL displayes in the location bar is https://experimental.hacs.xyz/docs/entities/update_entities#install-service)
...

### Screenshots

none

### Javascript logs from your browser console

```text
none
```

### Diagnostics dump

none

**Comment by ludeeus** [comment]
A redirect has now been put into place for this.
