### ISSUE TITLE
I can't install new integration or repository

### ISSUE THREAD

**Issue by dpaganin** [hacs/integration#3849]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to one the HACS add-ons.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Which Add-on are you reporting an issue for?

get

### Describe the issue

Integration version:	  1.34.0
Frontend version:	  20220906112053
Repositories:		  1387
Downloaded repositories:  48

I have an issue to download new repository or Integration.

I open HACS, click on "Frontend" and then choose "+Explore & Download repository"

search for the repository I want and then click to view it.

And then it stay loading (spin) and the page to download the repository doesn't show up.

the same thing is happen if I click "Integration" and then choose "+Explore & Download repository"
search for the Integration I want and then click to open it.

### Add-on logs

[config_entry-hacs-4f3cce6d28930878127b257007058d52 (1).json](https://github.com/user-attachments/files/16088134/config_entry-hacs-4f3cce6d28930878127b257007058d52.1.json)

**Comment by ludeeus** [comment]
Your network is broken (and this is not add-on)

**Comment by dpaganin** [comment]
@ludeeus thank you for your reply.

what do you mean my Network is broken?

can you please help?
