### ISSUE TITLE
 integration 'hacs' accesses hass.components.frontend - is deprecated and will stop working in Home Assistant 2024.9

### ISSUE THREAD

**Issue by misa1515** [hacs/integration#3855]
### Web browser

not relevant

### Web browser version

not relevant

### System Health details

not relevant

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Logger: homeassistant.helpers.frame
Zdroj: helpers/frame.py:184
Prvýkrát sa vyskytol: 23:17:52 (17 výskytov)
Naposledy prihlásený: 23:18:24

Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles", "/config/www/community", True)])`; This function will be removed in 2025.7 at custom_components/hacs/base.py, line 1162: self.hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'simpleicons' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/simpleicons/si.js", "/config/custom_components/simpleicons/data/si.js", True)])`; This function will be removed in 2025.7 at custom_components/simpleicons/__init__.py, line 43: hass.http.register_static_path(, please report it to the author of the 'simpleicons' custom integration
Detected that custom integration 'garbage_collection' calls async_forward_entry_setup for integration, garbage_collection with title: Komunálny odpad and entry_id: 820d7188e79abf5f8777ee91d3ae1bf7, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/garbage_collection/sensor.py, line 176: await self.hass.config_entries.async_forward_entry_setup(, please create a bug report at https://github.com/bruxy70/Garbage-Collection/issues
Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

### Reproduction steps

1.
2.
3.
...

### Screenshots

not relevant

### Javascript logs from your browser console

```text
not relevant
```

**Comment by tjorim** [comment]
Duplicate.

**Comment by northrup** [comment]
> Duplicate.

if it's a duplicate could you reference the open issue where it's being tracked?

**Comment by tjorim** [comment]
It's a closed issue as it's fixed.

**Comment by rwjack** [comment]
@northrup check the pinned issues. 

Although I'm not sure why such a long delay in releasing the changes though. Like we're waiting for the pope to come down and bless the commits himself... Warnings are getting super annoying.

Look at this: https://github.com/hacs/integration/issues/3534
Less than 2 months left for it to be deprecated.
