### ISSUE TITLE
Update Problems (Update available)

### ISSUE THREAD

**Issue by milandzuris** [hacs/integration#3862]
### System Health details

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4957
Installed Version | 1.34.0
Stage | running
Available Repositories | 1407
Downloaded Repositories | 88
HACS Data | ok

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Hi on some integrations and cards it shows me a new update but is bug, if i do Redownload and turn off Show beta versions and turn on back after this new update disappears and it is fixed.

![image](https://github.com/hacs/integration/assets/42905545/3a380848-56b7-4784-bc38-ff65fc7fc2b7)

### Reproduction steps

*

### Debug logs

```text
*
```

**Comment by ludeeus** [comment]
These are both matching so it will display.
HA does a string compare when it do not recognize the version format like here.
