### ISSUE TITLE
 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop

### ISSUE THREAD

**Issue by heinemannj** [hacs/integration#3877]
## System Information

version | core-2024.7.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4994
Installed Version | 1.34.0
Stage | running
Available Repositories | 1476
Downloaded Repositories | 68
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 30.8 GB
disk_used | 10.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Filebrowser (2.23.0_14), Samba Backup (5.2.0), Terminal & SSH (9.14.0), eBUSd (23.2.5), Studio Code Server (5.15.0), step-ca-client (1.0.2), EMHASS (0.10.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 41
views | 58
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 9, 2024 at 02:26
-- | --
current_recorder_run | July 9, 2024 at 11:22
estimated_db_size | 20083.64 MiB
database_engine | mysql
database_version | 11.2.3

</details>

<details><summary>Solcast PV Forecast</summary>

can_reach_server | ok
-- | --
used_requests | 2
rooftop_site_count | 1

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/iconset.js", "/config/custom_components/hacs/iconset.js", True)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 57: hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues

### Reproduction steps

please see above

### Debug logs

```text
please see above
```

**Comment by heinemannj** [comment]
Could you please highlight how to fix???
No reference to original issue is provided ...

**Comment by snowmangh** [comment]
I too would like to know how to fix this issue. I am still getting the error. Thanks in advance.

**Comment by tjorim** [comment]
Fix was implemented but not released yet. It's not an error, just a warning: ignore it.

**Comment by snowmangh** [comment]
Thanks for the super fast response @tjorim. And yes, it is a warning. My bad.
