### ISSUE TITLE
Same folder name in two extensions

### ISSUE THREAD

**Issue by Kfrard** [hacs/integration#3883]
### System Health details

not applicable

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

There are two integrations that create a folder with the same name, which causes problems. 
I think that in such a situation, HACS should prohibit the installation/change the name of the folder of the integration downloaded second.
![obraz](https://github.com/hacs/integration/assets/52238753/266911a9-0643-4db5-ac52-2a21a9a68ce1)
![obraz](https://github.com/hacs/integration/assets/52238753/78fc08b0-2d07-49a1-aa6c-b2ffaadf735c)

### Reproduction steps

1. Installation https://github.com/andre0512/hon
2. Installation https://github.com/gvigroux/hon
3. The added integration remains in the devices as the previous one, which should not be the case.

### Debug logs

```text
not applicable
```

**Comment by ludeeus** [comment]
HACS is doing what it is supposed to.
It is a downloader, and that's it, it can not stop you from doing things and it can not change directory names (that would make things invalid).
