### ISSUE TITLE
HACS UI Not Working

### ISSUE THREAD

**Issue by nileshkc** [hacs/integration#3884]
### Web browser

Safari

### Web browser version

Latest 17.5

## System Information

version | core-2024.7.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4989
Installed Version | 1.34.0
Stage | running
Available Repositories | 1390
Downloaded Repositories | 1
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 7 November 2024 at 00:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-14.ui.nabu.casa
certificate_status | ready
instance_id | 43ce83f9161d40aba57fa4bf241b849a
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 469.4 GB
disk_used | 7.2 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | AirCast (4.2.1), Z-Wave JS UI (3.8.5), Z-Wave JS (0.6.2), Matter Server (6.2.1), CEC Scanner (3.0), AirSonos (4.2.1), Terminal & SSH (9.14.0), OpenThread Border Router (2.9.0), Samba share (12.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 4 July 2024 at 13:01
-- | --
current_recorder_run | 13 July 2024 at 11:58
estimated_db_size | 33.34 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I installed as per the official instructions but the UI is not showing I just get the following UI which Im pasting in below. I also re-installed HACS but removing the integration and the files and re starting twice. Please can someone help me

![CleanShot 2024-07-13 at 12 15 39](https://github.com/user-attachments/assets/2efc2bc7-0196-4326-b2b8-6cfabd7f8e25)

### Reproduction steps

1. Installed HACS by going to Add-On and following the command in the following page https://hacs.xyz/docs/setup/download in SSH wget -O - https://get.hacs.xyz | bash -
2. Restarted HA
3. Added HACS Integrations 
4. Enabled GitHub OAuth
5. Restarted HA
...

### Screenshots

![CleanShot 2024-07-13 at 12 15 39](https://github.com/user-attachments/assets/4a37a2c9-c6b7-4d42-ba85-50ca073b8ef1)

### Javascript logs from your browser console

```text
Nothing in console
```

### Diagnostics dump

Didn't have that option to download the log

**Comment by ludeeus** [comment]
Working as intended/requested.

**Comment by nileshkc** [comment]
When I click on the HACS I get the following. I was expecting a menu:

![CleanShot 2024-07-13 at 12 45 56](https://github.com/user-attachments/assets/30bc8c26-b4dd-425b-946e-58a61c8ab951)

**Comment by nileshkc** [comment]
I was expecting the follow screen but cannot see it :

![CleanShot 2024-07-13 at 12 55 51](https://github.com/user-attachments/assets/7b2d0e07-2313-4ee7-8b80-db0fc0526418)

**Comment by nileshkc** [comment]
> Working as intended/requested.

I don't know how to get the menu

**Comment by tjorim** [comment]
You enabled the experimental options, please read the experimental documentation: https://experimental.hacs.xyz/docs/use/dashboard/
