### ISSUE TITLE
HACS Not Showing Menu

### ISSUE THREAD

**Issue by nileshkc** [hacs/integration#3885]
### Web browser

Safari

### Web browser version

17.4

## System Information

version | core-2024.7.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1390
Downloaded Repositories | 1
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 7 November 2024 at 00:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-14.ui.nabu.casa
certificate_status | ready
instance_id | 43ce83f9161d40aba57fa4bf241b849a
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 469.4 GB
disk_used | 7.2 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | AirCast (4.2.1), Z-Wave JS UI (3.8.5), Z-Wave JS (0.6.2), Matter Server (6.2.1), CEC Scanner (3.0), AirSonos (4.2.1), Terminal & SSH (9.14.0), OpenThread Border Router (2.9.0), Samba share (12.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 4 July 2024 at 13:01
-- | --
current_recorder_run | 13 July 2024 at 11:58
estimated_db_size | 33.34 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When I got into HACS UI I don't see the menu. All I see is the following

![CleanShot 2024-07-13 at 13 05 08](https://github.com/user-attachments/assets/c9f0b8c1-d863-4507-9a0e-f870069e3f58)

Im NOT getting the UI in this screenshot :

 
![CleanShot 2024-07-13 at 13 13 45](https://github.com/user-attachments/assets/b3280acd-ae5d-42f0-8e8d-77bb4940468c)

### Reproduction steps

1.Installed HACS by going to Add-On and following the command in the following page https://hacs.xyz/docs/setup/download in SSH wget -O - https://get.hacs.xyz/ | bash -
2. Restarted HA
3. Added HACS Integrations
4. Enabled GitHub OAuth

### Screenshots

![CleanShot 2024-07-13 at 13 06 51](https://github.com/user-attachments/assets/c823ed15-bfa4-4057-8590-e9b49322c36a)

### Javascript logs from your browser console

```text
No Logs Available
```

### Diagnostics dump

None available

**Comment by nileshkc** [comment]
Im not seeing the menu :

![CleanShot 2024-07-13 at 13 13 45](https://github.com/user-attachments/assets/57c16bff-8905-4519-9238-9fc9d9f8cdcd)


How can I see the above menu

**Comment by ludeeus** [comment]
You do not.
https://experimental.hacs.xyz/docs/use/dashboard/
