### ISSUE TITLE
hacs has some problems reaching out to github and managing other custom integrations

### ISSUE THREAD

**Issue by GiannisDorokidis** [hacs/integration#3897]
### System Health details

![image](https://github.com/user-attachments/assets/20d1c051-d284-46f5-ad1f-1129fb137524)

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I have some issues maybe because of hacs? it was working find untill some devices like from local toya had (still have) problems with utilizing all intergrations from hacs have some problems and it also seems like the hacs integration has got rate limited by github for some reason. Also some other not custom ingrations got some problems and i cant find the reason why so many things broke without me experimenting with my home assistant instance. Install is docker arm64 on pi 4 8gb 

### Reproduction steps

Cant reproduce as it happend radomly

### Debug logs

```text
This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:471
integration: HACS (documentation, issues)
First occurred: July 16, 2024 at 10:06:18 (169 occurrences)
Last logged: 13:56:46

Timeout of 20 reached while waiting for https://api.github.com/rate_limit
Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [None]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 471, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/base.py", line 529, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Timeout of 20 reached while waiting for https://api.github.com/rate_limit
```

### Diagnostics dump

[config_entry-hacs-1ceeb4a7ed69ce965f84d8e594352fb4 (1).json](https://github.com/user-attachments/files/16264760/config_entry-hacs-1ceeb4a7ed69ce965f84d8e594352fb4.1.json)

**Comment by ludeeus** [comment]
Your host has network issues, maybe related to ipv6, but HACS is not the cause of it.

**Comment by GiannisDorokidis** [comment]
It was dns and no im not using ipv6 the docker container couldnt resolve any domain
