### ISSUE TITLE
the fronted version is not updated

### ISSUE THREAD

**Issue by andiukas** [hacs/integration#3942]
### Web browser

Chrome

### Web browser version

127.0.6533.89

## System Information

version | core-2024.8.0b1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/Vilnius
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1472
Downloaded Repositories | 72
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 2024 m. liepos 18 d. 03:00
relayer_connected | false
relayer_region | null
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
remote_server | null
certificate_status | null
instance_id | 2fef8185ce204939bbefb22d3e74b101
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | beta
supervisor_version | supervisor-2024.07.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 70.2 GB
disk_used | 36.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.1), File editor (5.8.0), Home Assistant Google Drive Backup (0.112.1), Samba share (12.3.2), Studio Code Server (5.15.0), ESPHome (2024.7.3), Advanced SSH & Web Terminal (18.0.0), Piper (1.5.1), Whisper (2.1.2), openWakeWord (1.10.0), eWeLink Smart Home (1.4.3), Zigbee2MQTT (1.39.1-1), Music Assistant Server (2.1.1), Microsoft TTS (1.0.7), Microsoft STT (1.0.6), Zigbee2MQTT (1.39.1-1), motionEye (0.20.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 54
views | 20
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 2024 m. liepos 26 d. 04:54
-- | --
current_recorder_run | 2024 m. rugpjūčio 4 d. 21:03
estimated_db_size | 6736.14 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Sonoff</summary>

version | 3.7.3 (e240aaf)
-- | --
cloud_online | 3 / 4
local_online | 1 / 1

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.19
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 13

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

the fronted version is not updated, reinstalling or clearing the cashe does not help.

Integration version: | 1.34.0
Frontend version: | 20240119163101

### Reproduction steps

1.
2.
3.
...

### Screenshots

![Screenshot 2024-08-05 092537](https://github.com/user-attachments/assets/8b953e12-1a04-4e8f-97d0-9d1b39d2ae12)
![Screenshot 2024-08-05 092511](https://github.com/user-attachments/assets/6abd8d64-a167-4868-aa30-c923f8702c2f)

### Javascript logs from your browser console

```text
.
```

**Comment by andiukas** [comment]
> There is no update yet.

but I see that the last fronted version is 20240729171855 and mine is 20240119163101

**Comment by ludeeus** [comment]
Sure...
But there has not been a release of HACS since that...
If you want a newer one, you need to do this: <https://community.home-assistant.io/t/hacs-2-0-join-the-alpha-testing-adventure/747891>
