### ISSUE TITLE
Deprecated function: json_loads

### ISSUE THREAD

**Issue by schmittyd** [hacs/integration#3943]
### Describe the issue

json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead

### Link to action run

na

### Link to action configuration

na

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This is a bug and not a feature request.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
Fixed in https://github.com/hacs/integration/pull/3857
