### ISSUE TITLE
use of deprecated async_track_time_interval; removal scheduled for Home Assistant 2024.11

### ISSUE THREAD

**Issue by DanceMore** [hacs/integration#3944]
## System Information

version | core-2024.7.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 5.10.0-11-amd64
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4794
Installed Version | 1.34.0
Stage | running
Available Repositories | 1385
Downloaded Repositories | 15

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 8
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 31, 2024 at 2:20 PM
-- | --
current_recorder_run | August 6, 2024 at 10:56 AM
estimated_db_size | 867.25 MiB
database_engine | postgresql
database_version | 14.12

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

simple detection of deprecation warning while chasing bugs / ghosts in other plugins and integrations.

mostly submitting for triage because[ I was surprised it's not already open](https://github.com/hacs/integration/issues?q=is%3Aissue+async_track_time_interval+) and I'm subscribing to all the open deprecation issues I find :)

```
2024-08-06 10:56:14.211 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
```

I guess I am technically unsure if this is Backend or Frontend. `helpers.frame` sounds like a UI component, but a `deprecation` log at start is the kind of thing Backend nerds like myself notice.

### Reproduction steps

1. restart HomeAssistant
2. notice the deprecation warning

### Debug logs

```text
should not be required to triage a deprecation warning
```

**Comment by DanceMore** [comment]
can you show me the dupe because I really tried to find it.

**Comment by tjorim** [comment]
https://github.com/hacs/integration/issues/3879
https://github.com/hacs/integration/issues/3869
https://github.com/hacs/integration/issues/3863
https://github.com/hacs/integration/issues/3801
...
