### ISSUE TITLE
 json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8.

### ISSUE THREAD

**Issue by Xavier82** [hacs/integration#3948]
### System Health details

The logging is telling me this:
`2024-08-08 11:12:52.725 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues`

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

[homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues

### Reproduction steps

1. Go to logging Core
2. Find errors with json_loads

### Debug logs

```text
`2024-08-08 11:12:52.725 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues`
```

**Comment by TNTLarsn** [comment]
Duplicate of https://github.com/hacs/integration/issues/3943

**Comment by Xavier82** [comment]
Thanks for your reaction. I had to restart HA for this. Now I don't have any errors anymore in the logging.
