### ISSUE TITLE
Deprecated json_loads

### ISSUE THREAD

**Issue by KitHubek** [hacs/integration#3950]
## System Information

version | core-2024.8.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1382
Downloaded Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>GIOŚ</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 234.0 GB
disk_used | 30.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.15.0), Mosquitto broker (6.4.1), Samba share (12.3.2), Duck DNS (1.18.0), NGINX Home Assistant SSL proxy (3.9.0), Zigbee2MQTT (1.39.1-1), ESPHome (2024.7.3), MariaDB (2.7.1), Advanced SSH & Web Terminal (18.0.0), phpMyAdmin (0.9.1), Node-RED (18.0.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 5
views | 34
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 11 czerwca 2024 14:03
-- | --
current_recorder_run | 7 sierpnia 2024 21:52
estimated_db_size | 4335.45 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.19
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 15

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Just see this warning at log

### Reproduction steps

1. Install newest ver HACS
2. look at log
3. see error

### Debug logs

```text
Rejestrator: homeassistant.util.json
Źródło: helpers/deprecation.py:197
Pierwsze zdarzenie: 7 sierpnia 2024 21:53:00 (45 zdarzenia)
Ostatnio zalogowany: 09:53:00

json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
```

**Comment by tjorim** [comment]
Duplicate. Please don't just check boxes but actually go over the checklist:
"This issue is not a duplicate issue of currently open or issues pending release."
https://github.com/hacs/integration/issues/3943

**Comment by KitHubek** [comment]
ok, duplicate 3943 and others
