### ISSUE TITLE
Use homeassistant.util.json.json_loads instead of json_loads call from hacs

### ISSUE THREAD

**Issue by ShantanuKhan** [hacs/integration#3951]
## System Information

version | core-2024.8.0
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | homeassistant
virtualenv | true
python_version | 3.12.2
os_name | Linux
os_version | 6.6.31+rpt-rpi-v8
arch | aarch64
timezone | Asia/Calcutta
config_dir | /home/homeassistant/.homeassistant

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4965
Installed Version | 1.34.0
Stage | running
Available Repositories | 1384
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 31, 2024 at 10:30 PM
-- | --
current_recorder_run | August 10, 2024 at 11:01 AM
estimated_db_size | 180.38 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

<details><summary>Sonoff</summary>

version | 3.7.3 (e240aaf)
-- | --
cloud_online | 2 / 2
local_online | 2 / 2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead

### Reproduction steps

1. Upgrade HASS from 2024.7.4 to 2024.8.0

### Debug logs

```text
Logger: homeassistant.util.json
Source: helpers/deprecation.py:197
First occurred: 11:01:40 AM (15 occurrences)
Last logged: 11:10:08 AM

json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
```

**Comment by tjorim** [comment]
Duplicate
