### ISSUE TITLE
Forced update failed. Entity update.####_update not found

### ISSUE THREAD

**Issue by mike4001** [hacs/integration#3963]
## System Information

version | core-2024.8.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1384
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 439.4 GB
disk_used | 22.5 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.2), Advanced SSH & Web Terminal (18.0.0), File editor (5.8.0), Samba Backup (5.2.0), Mosquitto broker (6.4.1), AppDaemon (0.16.6), Signal Messenger (0.88.0), MQTT Explorer (browser-1.0.1), ESPHome (2024.7.3), pigpio (1.5.2), Firefox (1.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 2
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15. Juli 2024 um 16:58
-- | --
current_recorder_run | 11. August 2024 um 17:51
estimated_db_size | 4569.16 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Since the update to Home Assistnat 2024.8.0 (or 8.1) logs show

Forced update failed. Entity update.apexcharts_card_update not found.
Forced update failed. Entity update.gardena_smart_system_update not found.
Forced update failed. Entity update.hacs_update not found.
Forced update failed. Entity update.myvaillant_update not found.

I can also see that these entities are not provided anymore by the HACS integration.

(I posted this previously in the Home Assistant Core Issue section and they closed the issue and said it was a HACS issue.)

### Reproduction steps

no steps. Logs just show it.

### Debug logs

```text
Logger: homeassistant.helpers.entity_component
Quelle: helpers/entity_component.py:60
Erstmals aufgetreten: 11. August 2024 um 20:28:55 (35 Vorkommnisse)
Zuletzt protokolliert: 06:36:59

Forced update failed. Entity update.apexcharts_card_update not found.
Forced update failed. Entity update.esphome_1_firmware not found.
Forced update failed. Entity update.gardena_smart_system_update not found.
Forced update failed. Entity update.hacs_update not found.
Forced update failed. Entity update.myvaillant_update not found.
```

**Comment by tjorim** [comment]
Have you enabled experimental mode?

**Comment by mike4001** [comment]
> Have you enabled experimental mode?

No

![image](https://github.com/user-attachments/assets/1782c81f-bfe2-4033-be48-152da3796e46)

**Comment by tjorim** [comment]
Then it's expected. You won't have these entities (and can't use native HA updates) in that case.

**Comment by mike4001** [comment]
OK, I have just removed the entities manually.

Thanks for your help.

**Comment by mike4001** [comment]
OK, I have just removed the entities manually.

Thanks for your help.
