### ISSUE TITLE
Updates to HACS items do not cause automations to trigger

### ISSUE THREAD

**Issue by geofffarmer** [hacs/integration#3980]
## System Information

version | core-2024.8.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.44-haos
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4988
Installed Version | 1.34.0
Stage | running
Available Repositories | 1391
Downloaded Repositories | 19
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 5 August 2025 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-central-1-6.ui.nabu.casa
certificate_status | ready
instance_id | e6f4346f8ff9413dac2e3d1b151a9361
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 116.7 GB
disk_used | 26.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.2), Home Assistant Google Drive Backup (0.112.1), Studio Code Server (5.15.0), Z-Wave JS UI (3.10.0), WireGuard (0.10.2), Duck DNS (1.18.0), Zigbee2MQTT (1.39.1-1), ESPHome (2024.7.3), Whisper (2.1.2), Piper (1.5.2), Mosquitto broker (6.4.1), openWakeWord (1.10.0), OpenSpeedTest (v2.0.5), Matter Server (6.4.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 13
views | 17
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 9 August 2024 at 01:01
-- | --
current_recorder_run | 18 August 2024 at 02:06
estimated_db_size | 896.92 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I have an automation that contains the following trigger. The automation does not trigger when there is an update to Mushroom Cards.

`platform: state
entity_id: update.mushroom_update
to: "on"
id: Mushroom Cards Update Available
variables:
  type: HACS front end
  trigger_message: >-
    Mushroom Cards Update Available {{ state_attr('update.mushroom_update',
    'latest_version') }}`

### Reproduction steps

1. Use experimental features
2. Install Mushroom Cards
3. Create an automation with the given trigger
4.Wait for an update to Mushroom Cards
...

### Debug logs

```text
.
```

**Comment by tjorim** [comment]
Updates are not instant. Did the actual update entity show an update? Anyway, this is a HA automation and not related to HACS directly.

**Comment by geofffarmer** [comment]
Hi @tjorim 

Thanks for looking at this.

I had 2 updates appear this morning and it may be useful for you if I explain what I think is happening.

![2024-08-19 08_22_59-Greenshot](https://github.com/user-attachments/assets/3bb2b24b-f655-4f29-832a-c42d3a523518)
![2024-08-19 08_24_34-Greenshot](https://github.com/user-attachments/assets/1762b8a8-009f-473a-ad1a-a0bfee256e3a)

Both these update entities seem to have gone to the 'Update Available' state at 02:01:29. I think this is because, at 02:01 my HA instance is set to restart (just to keep things healthy). My guess is that, only during the restart does the availablity of an update get 'registered'. Guessing further, this occurs before HA is ready to trigger automations, so my automation does not trigger.

**Comment by geofffarmer** [comment]
I'm not sure how to format my yaml. I'm using the Code option. What else is there?

**Comment by ludeeus** [comment]
If you need help with your automations, use the HA discord or forums.
This is not a bug in HACS.
