### ISSUE TITLE
Card out of range

### ISSUE THREAD

**Issue by kelilive** [hacs/integration#3988]
### Web browser

Google Chrome

### Web browser version

127.0.6533.120

## System Information

version | core-2024.8.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.1.43-haos
arch | aarch64
timezone | Asia/Shanghai
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

error | failed to load: unknown
-- | --

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 27.7 GB
disk_used | 6.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | panther-x2
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.2), File editor (5.8.0), Mosquitto broker (6.4.1), Node-RED (18.0.5), Zigbee2MQTT (1.39.1-1), Silicon Labs Flasher (0.2.3), Terminal & SSH (9.14.0), frigate-rknpu (rknn1.6-13.2-3), Advanced SSH & Web Terminal (18.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 15, 2024 at 9:56 AM
-- | --
current_recorder_run | August 15, 2024 at 7:05 PM
estimated_db_size | 1.77 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.19
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 185

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Please see the image

### Reproduction steps

none

### Screenshots

![image](https://github.com/user-attachments/assets/2e41d7b2-c817-409f-8c35-1ca66df8de42)

### Javascript logs from your browser console

```text
none
```

**Comment by tjorim** [comment]
That layout is obsolete and only used in an older version of HACS, it won't be updated anymore. You should update HACS to version 2.0.0, for more information check the blog post: https://www.home-assistant.io/blog/2024/08/21/hacs-the-best-way-to-share-community-made-projects/
