### ISSUE TITLE
Github Blockquote Notes are not rendered correctly in HACS frontend.

### ISSUE THREAD

**Issue by BJReplay** [hacs/integration#3995]
### Web browser

Chromium (tried in both Edge and Chrome)

### Web browser version

Version 129.0.2779.0 (Official build) dev (64-bit)

## System Information

version | core-2024.8.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.36.3-microsoft-standard-WSL2
arch | x86_64
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.0
Stage | running
Available Repositories | 1393
Downloaded Repositories | 25

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 16
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 12 August 2024 at 8:35 am
-- | --
current_recorder_run | 22 August 2024 at 1:39 pm
estimated_db_size | 510.38 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Solcast PV Forecast</summary>

can_reach_server | ok
-- | --
used_requests | 32
rooftop_site_count | 1

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

HACS 2.0 displays readme.md blockquotes much better than 1.3.4, but leaves out the entire first paragraph / sentence for some reason for ` [!NOTE]` blockquotes.

The current readme for this issue is at https://github.com/BJReplay/ha-solcast-solar/blob/main/README.md

An earlier version that won't change is at https://github.com/BJReplay/ha-solcast-solar/blob/66331bb39ba80f4003ab47cabc0d3f427adf59e6/README.md

### Reproduction steps

1. Add https://github.com/bjreplay/ha-solcast-solar as a custom integration to HACS
2. Browse to HACS in HA, and click on the Solcast PV Solar integration in Downloaded repositories
3. Observe that the ` [!NOTE]` blockquotes are missing the first sentence / paragraph.
...

### Screenshots

Image from HACS:

![image](https://github.com/user-attachments/assets/9e2baf86-c09c-4125-8689-110cdeb9e7e9)

Image from Github (Note, - the issue isn't so much the missing Warning or Note text, but the entire missing sentences).

The sentence `The use of beta versions can be a simple way to fix issues. Check the releases at` is missing from the first note, and the sentence (paragraph) `This integration can be used as a replacement for the oziee/ha-solcast-solar integration, which has been removed from GitHub and HACS.` is missing from the second note.

![image](https://github.com/user-attachments/assets/61926339-08ed-4dde-b463-7141ac5a7d9c)

### Javascript logs from your browser console

```text
Nothing recorded.
```

### Diagnostics dump

Not applicable (please let me know if I'm incorrect in this assessment, and I'll provide).

**Comment by ludeeus** [comment]
Is this a HACS or Home Assistant problem?
If you paste the same in a markdown card is it different?

**Comment by BJReplay** [comment]
> Is this a HACS or Home Assistant problem? If you paste the same in a markdown card is it different?

Stand by...

Testing...

**Comment by BJReplay** [comment]
> Is this a HACS or Home Assistant problem?

HACS, I think:

![image](https://github.com/user-attachments/assets/da203a22-8308-4532-b54a-ac68ca18e8b9)


![image](https://github.com/user-attachments/assets/cc8fc791-7725-44a0-982d-ea759a6a4a85)

**Comment by ludeeus** [comment]
Try the entire file.

**Comment by BJReplay** [comment]
Yeah, I just did, thinking that the first test wasn't enough!

![image](https://github.com/user-attachments/assets/036efbb8-cb16-4763-aafa-1fc403c3a091)

**Comment by autoSteve** [comment]
Google Fit is another example that I found, @ludeeus. https://github.com/YorkshireIoT/ha-google-fit.

**Comment by ludeeus** [comment]
Yeah, have verified there is some difference even on HA dev.

**Comment by ludeeus** [comment]
I took a look at it, and the markdown card uses a slightly different approach to how content breaks.
HACS uses the same as add-ons, which have the same problems.

So I think this is something that needs to be handled on the Home Assistant frontend as this will be a problem for add-ons as well.

**Comment by BJReplay** [comment]
> HACS uses the same as add-ons, which have the same problems.

As I'm using HA in a container, I don't have access to add-ons, so can't repro.

Will you raise this issue in the HA front end?

**Comment by elchininet** [comment]
Hi @ludeeus,
Is not [this logic](https://github.com/home-assistant/frontend/blob/682f5345cc93a61574c52135d6c374224082a031/src/components/ha-markdown-element.ts#L80) the one that manages that?

**Comment by elchininet** [comment]
Testing the public `content` property of the `ha-markdown-element` that is rendered, the text is there, it seems that it gets choped off by the logic of that component.

<img width="1593" alt="image" src="https://github.com/user-attachments/assets/c4576b3b-ab33-43fc-85ed-9b3145650437">

**Comment by ludeeus** [comment]
This is correct. It behaves differently depending on whether you pass it `break` or not (the markdown card does); HACS and add-ons do not.
<https://github.com/hacs/integration/issues/3995#issuecomment-2304271044> Witch has the side-effect of messing with other things like the badges are not all vertical.
