### ISSUE TITLE
`Update Information` context menu item does nothing

### ISSUE THREAD

**Issue by idogrf** [hacs/integration#3999]
### Web browser

Brave / Chrome

### Web browser version

Chromium: 128.0.6613.85

## System Information

version | core-2024.8.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.1.21-v8+
arch | aarch64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4312
Installed Version | 2.0.0
Stage | running
Available Repositories | 1390
Downloaded Repositories | 32

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 8 September 2024 at 03:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-12.ui.nabu.casa
certificate_status | ready
instance_id | 940cb8747b5546469bdfceef60a4738d
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 13
-- | --
resources | 23
views | 24
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 22 August 2024 at 21:48
-- | --
current_recorder_run | 23 August 2024 at 01:18
estimated_db_size | 6.45 MiB
database_engine | mysql
database_version | 10.11.4

</details>

<details><summary>Sonoff</summary>

version | 3.7.3 (e240aaf)
-- | --
cloud_online | 0 / 1
local_online | 1 / 1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I'm currently using the new HACS 2.0 UI. 
In the HACS section, I can see a list of all integrations, with those needing updates displayed at the top. 
When I click on the three dots menu for an integration, there is an option labeled Update Information. 
I expect this to open a window showing the changelog for the integration update and provide the option to proceed with the update.

However, when I click on the Update Information button, nothing happens. 
I checked the browser's console and network tabs in the developer tools, but there are no errors or network activity when the button is clicked - no entries show up at all.

The only way I have found to view the changelog and update the integration is through the main Home Assistant settings page using the new notifications.

### Reproduction steps

1. Go to HACS main page
2. Click on the 3 dots menu next to one of the integrations
3. Click on `Update Information`

### Screenshots

![image](https://github.com/user-attachments/assets/e4e2cc11-0fae-4e32-8c34-8e55046e3259)

### Javascript logs from your browser console

```text
-
```

### Diagnostics dump

[config_entry-hacs-470b6db2af66f0ff8db2af551ba57726.json](https://github.com/user-attachments/files/16719644/config_entry-hacs-470b6db2af66f0ff8db2af551ba57726.json)

**Comment by idogrf** [comment]
I now understand that I might have miss correctly assumed that the `Update Information` button shows you the information of updating the integration. Does it actually just a button that instructs HACS to pull new information?

If that's the case, the naming is a bit misleading. And it would also be nice to still be able to access all of the integration update in formation from the HACS homepage and not only the HA notifications.

**Comment by smarthomefamilyverrips** [comment]
> I now understand that I might have miss correctly assumed that the `Update Information` button shows you the information of updating the integration. Does it actually just a button that instructs HACS to pull new information?
> 
> If that's the case, the naming is a bit misleading. And it would also be nice to still be able to access all of the integration update in formation from the HACS homepage and not only the HA notifications.

Yes it just pulls again the information for the integration, like this also is in the old version of HACS

**Comment by tjorim** [comment]
Indeed not an issue, it updates the information. Feel free to open a PR in case of a better idea.
