### ISSUE TITLE
How to update installed integrations?

### ISSUE THREAD

**Issue by Moohan** [hacs/integration#4003]
### Describe the issue

I can't see how to update integrations in the new HACS UI. This used to be super simple and really nice to view changelogs etc. I checked the docs but didn't see it (sorry if I've just missed it!)

**Comment by tjorim** [comment]
It uses native home assistant update entities: https://hacs.xyz/docs/use/entities/update/.

**Comment by MEKadan** [comment]
Does this mean we need to monitor ALL installed  integrations? The old `sensor.hacs`, which showed if ANY updates available, seems not to be there anymore?

**Comment by tjorim** [comment]
Not sure what you mean by monitor. If there is an update it will pop-up in the settings.

**Comment by Moohan** [comment]
Can confirm the updates all popped up in settings for me. I guess I was just a bit keen with this Issue!

Any reason that there should have been a delay in the HACS table showing them as 'update available' and the notification appearing in settings?
