### ISSUE TITLE
HACS not acknowledging update

### ISSUE THREAD

**Issue by tbclark3** [hacs/integration#4004]
## System Information

version | core-2024.8.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.10.6-200.fc40.x86_64
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4992
Installed Version | 2.0.0
Stage | running
Available Repositories | 1399
Downloaded Repositories | 33

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 16
-- | --
resources | 17
views | 15
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 16, 2024 at 4:18 PM
-- | --
current_recorder_run | August 25, 2024 at 2:49 PM
estimated_db_size | 1555.95 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

After updating an integration and restarting, HACS returns to the "update needed" for that integration even though it is clear that the new version is running.  This initially happened with a single integration and remained in the "update needed" state after I updated and restarted several times.  I then got a notice of a second integration needing update, proceeded, restarted, and both showed successful updates.  A few minutes ago I got another upgrade notice.  I updated, restarted, and now HACS is showing "update needed" for that integration. I have confirmed in the integration's manifest that the newest version was downloaded and is running.

### Reproduction steps

1. Update integration
2. Check HACS page
3. HACS still says integration needed
...

### Debug logs

```text
Logs don't show anything significant
```

**Comment by wizu** [comment]
I have same problem, it looks like hacs only see intergration as updated, when I aceept notification about restart and it automatically restarts HA.

**Comment by tbclark3** [comment]
Good pickup. That explains why I see it every time. I can't restart HA from within HA because I have to restart an stunnel instance at the same time, so I always restart using docker.

**Comment by ludeeus** [comment]
HACS flushes the metadata to disk every 6h and on the shutdown event (which also happens during restart).
You need to allow more time before killing it if you are not using the UI to restart.
Closing as out of scope for HACS.

**Comment by wizu** [comment]
I use docker compose with stop_grace_period: 60s.
When i do "docker compose stop homeassistnat" then docker sends SIGTERM to container and waits 60s - after that time it sends SIGKILL. HA shut down in about 10s so no SIGKILL is send.
That clearly shows that HA completes it's shutdown procedure and it is not interrupted.
So HACS should also have time to do what it is supposed to do - but it clearly don't.

**Comment by wizu** [comment]
Oh, it may be the case that my new value for stop_grace_period was not applied correctly. I will observe it with next restarts and leave feedback here.

**Comment by wizu** [comment]
@ludeeus @tbclark3 stop_grace_period: 60s did the trick.
