### ISSUE TITLE
HACS do not respect the use of the primary_font-family variable

### ISSUE THREAD

**Issue by nagtegaal** [hacs/integration#4016]
### Web browser

Safari

### Web browser version

17.8

### System Health details

Even this link is out of date. There is no System health card located at the location mentioned in the link above.
I can not seem to find the info, the description above this field refers to.

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Change the primary font CSS variable in a theme of choice, to something other than the default "Roboto" and it isn't working/inherited  in HACS 2.
The primary_font_variable isn't used in the HACS code, which leads to unstyled content and an ever more inconsistent UI (amaturistic).

It would be nice if also HACS could respect the CSS variables. To me, this feels more like a bug than a feature request. Although, it's best for the maintainer to categorise this.

### Reproduction steps

1.  Open your own custom theme
2. Change `primary-font-family` to the name of the font you linked to at the "Add resources" dashboard-page in the Dasgboard-settings.
3. Clear caches and reload yaml/theme, etc
4. See how the custom font is used, but not inside HACS.
...

### Screenshots

<img width="1614" alt="image" src="https://github.com/user-attachments/assets/076e358a-165e-44b0-8e80-d9d27eb4224f">

### Javascript logs from your browser console

```text
N/A
```

### Diagnostics dump

N/A

**Comment by nagtegaal** [comment]
<img width="1488" alt="image" src="https://github.com/user-attachments/assets/b8b33f2c-748c-42d5-9a24-8fd96ee55c8d">

**Comment by ludeeus** [comment]
Do Home Assistant pass this to iframes?

**Comment by ludeeus** [comment]
I checked, no.
So this would be a feature request for HA, once its done there it will just start working.

**Comment by nagtegaal** [comment]
Thanks for your time/information, I made a bug report/feature request to fix/add this to basic HA...
