### ISSUE TITLE
Request for removal of marcokreeft87/room-card

### ISSUE THREAD

**Issue by lennon101** [hacs/integration#4019]
### Repository

marcokreeft87/room-card

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

This repository has been archived by the owner on Aug 30, 2024. It is now read-only.

### Link to issue

https://github.com/marcokreeft87/room-card/issues/344

**Comment by ashev** [comment]
Hi @ludeeus 
Why you remove wery nice repository marcokreeft87/room-card from HACS?
The @marcokreeft87 was harrassed by @lennon101 in the 'issues' then @marcokreeft87 makes repository readonly.
@lennon101 send request for removal in 10 minutes after that.
A lot of people usse this repository, please rollback removal.
![image](https://github.com/user-attachments/assets/e38a741d-9400-4d27-91fc-b25b77aaead0)
