### ISSUE TITLE
Unable to uninstall integrations

### ISSUE THREAD

**Issue by chemelli74** [hacs/integration#4020]
## System Information

version | core-2024.8.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 4.4.302+
arch | x86_64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4956
Installed Version | 2.0.0
Stage | running
Available Repositories | 1392
Downloaded Repositories | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 12
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25 agosto 2024 alle ore 18:25
-- | --
current_recorder_run | 30 agosto 2024 alle ore 13:00
estimated_db_size | 1124.41 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Unable to uninstall an integration even if all config entry have been removed

### Reproduction steps

1. Select an integration
2. Try to uninstall

### Debug logs

```text
2024-08-30 13:31:07.359 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139654642720848] Error handling message: Unknown error (unknown_error) admin from 93.66.71.204 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 268, in hacs_repository_remove
    await repository.uninstall()
  File "/config/custom_components/hacs/repositories/base.py", line 764, in uninstall
    raise HacsException("Could not uninstall")
custom_components.hacs.exceptions.HacsException: Could not uninstall
```

**Comment by chemelli74** [comment]
There was a issue during upload probably. Here the missing files:

[config_entry-hacs-124df6d59b49bc682dfb0f6e966aa01c.json](https://github.com/user-attachments/files/16816307/config_entry-hacs-124df6d59b49bc682dfb0f6e966aa01c.json)

[home-assistant_hacs_2024-08-30T11-38-30.404Z.log](https://github.com/user-attachments/files/16816308/home-assistant_hacs_2024-08-30T11-38-30.404Z.log)

**Comment by ludeeus** [comment]
A) /config/custom_components/midea_ac_lan does not exist
b) The user running HA does not have write permissions to /config/custom_components/midea_ac_lan.

**Comment by chemelli74** [comment]
> A) /config/custom_components/midea_ac_lan does not exist

```
homeassistant-prod:/config/custom_components# ls -l midea_ac_lan/
total 208
-rwxr-xr-x    1 root     root          6692 Nov 15  2023 __init__.py
drwxr-xr-x    1 root     root          1532 Jan 15  2024 __pycache__
-rwxr-xr-x    1 root     root          1124 Nov 15  2023 binary_sensor.py
-rwxr-xr-x    1 root     root         16972 Nov 15  2023 climate.py
-rwxr-xr-x    1 root     root         21714 Nov 15  2023 config_flow.py
-rwxr-xr-x    1 root     root           603 Nov 15  2023 const.py
-rwxr-xr-x    1 root     root          7132 Nov 15  2023 fan.py
-rwxr-xr-x    1 root     root          3217 Nov 15  2023 humidifier.py
-rwxr-xr-x    1 root     root          3855 Nov 15  2023 light.py
-rwxr-xr-x    1 root     root          1286 Nov 15  2023 lock.py
-rwxr-xr-x    1 root     root           409 Nov 15  2023 manifest.json
drwxr-xr-x    1 root     root            40 Nov 15  2023 midea
-rwxr-xr-x    1 root     root         86702 Nov 15  2023 midea_devices.py
-rwxr-xr-x    1 root     root          1879 Nov 15  2023 midea_entity.py
-rwxr-xr-x    1 root     root          2297 Nov 15  2023 number.py
-rwxr-xr-x    1 root     root          1372 Nov 15  2023 select.py
-rwxr-xr-x    1 root     root          1430 Nov 15  2023 sensor.py
-rwxr-xr-x    1 root     root           304 Nov 15  2023 services.yaml
-rwxr-xr-x    1 root     root          1205 Nov 15  2023 switch.py
drwxr-xr-x    1 root     root            94 Nov 15  2023 translations
-rwxr-xr-x    1 root     root          9087 Nov 15  2023 water_heater.py
```

> b) The user running HA does not have write permissions to /config/custom_components/midea_ac_lan.

I'm running docker HA official image from docker hub, and the issue happens only now after updating HACS to 2.0.0

**Comment by ludeeus** [comment]
Don't know what to tell you, it is failing on removing that directory.
`shutil.rmtree` is used for that operation.
Maybe some of your other integrations are overriding that.

**Comment by chemelli74** [comment]
Thx for your kind feedback, will investigate further on my side.
