### ISSUE TITLE
Request for removal of websylv/homeassistant-meteoswiss

### ISSUE THREAD

**Issue by websylv** [hacs/integration#4023]
### Repository

websylv/homeassistant-meteoswiss

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

No longer maintained by me

### Link to issue

I'm the author

**Comment by ludeeus** [comment]
I can not find this repo.
Did you delete it?
