### ISSUE TITLE
Method for adding Custom Repository has changed. Error message "Repository .... appears in the the store"

### ISSUE THREAD

**Issue by SmartBoatInnovations** [hacs/integration#4041]
## System Information

version | core-2024.8.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.28-haos-raspi
arch | aarch64
timezone | Europe/Lisbon
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4964
Installed Version | 2.0.1
Stage | running
Available Repositories | 1395
Downloaded Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 1 January 2018 at 01:00
relayer_connected | false
relayer_region | null
remote_enabled | true
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | null
certificate_status | null
instance_id | 9f7235b34b044489aa22a2ae547e40b2
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 109.3 GB
disk_used | 21.0 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Cloudflared (5.1.9), ESPHome (2024.7.3), File editor (5.8.0), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.4.0), Advanced SSH & Web Terminal (17.2.0), Studio Code Server (5.15.0), Zigbee2MQTT (1.36.1-1), Glances (0.21.1), Batmon (1.78)

</details>

<details><summary>Dashboards</summary>

dashboards | 18
-- | --
resources | 10
views | 17
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 5 September 2024 at 14:16
-- | --
current_recorder_run | 8 September 2024 at 11:33
estimated_db_size | 488.06 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I am an author of many integrations which I offer as custom HACS repository installations. I have specific instructions on how to install a custom HACS repository. Since HACS 2.0 when you add the custom repo you can now no longer click on the repo name to download it after you have added it.. Only the delete is possible.. This has confused many of my users. They now need to cancel and go back to the HACS screen and search for the Integration by name to download it.  I think this is an error in the flow process with the new version. It is much more difficult now than with HACS 1.*

### Reproduction steps

1.  Install custom repo https://github.com/SmartBoatInnovations/ha-smart2000usb
2. It is found ok. But when you click on the repo to install, either nothing happens or an error message appears. 
"Repository SmartBoatInnovations/ha-smart2000usb appears in the store"
Previously when clicked on the custom repo it would take you to the page to download it. 

 ![Image 9-7-24 at 4 16 PM](https://github.com/user-attachments/assets/184b2eb0-db6d-4bfa-af6f-afe95d4e3aa6)"

...

### Debug logs

```text
N/A
```

### Diagnostics dump

N/A

**Comment by ludeeus** [comment]
This changed so you can add multiple at the same time; the "error" you get is because you try to add the same one multiple times.

If you want the same instructions on both current and old versions of HACS, have them use a "my" link.
https://my.home-assistant.io/create-link/?redirect=hacs_repository

**Comment by SmartBoatInnovations** [comment]
But you couldn't you previously add multiple as well? Well you could delete
multiple.
But now you can only delete multiple.  So why is delete still there? It is
inconsistent. You permit a delete operation but not a simple click that
takes the user to the download page. Also inefficient.  After adding a
custom repo you then need to return to the store and do a search to find it
to download.
