### ISSUE TITLE
Component error: hacs - cannot import name 'VerificationMaterials' from 'sigstore.verify' (/usr/local/lib/python3.12/site-packages/sigstore/verify/__init__.py)

### ISSUE THREAD

**Issue by gianry** [hacs/integration#4044]
## System Information

version | core-2024.9.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | x86_64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 30.8 GB
disk_used | 4.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Advanced SSH & Web Terminal (18.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 7 settembre 2024, 19:40
-- | --
current_recorder_run | 8 settembre 2024, 12:41
estimated_db_size | 2.79 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I get an error when try to install HACS integration : impossible load flow configuration: {"message":"Invalid handler specified"}

### Reproduction steps

1.   open SSH terminal
2.  wget -O - https://get.hacs.xyz | bash -
3. reboot home assistant server
4. try to install hacs integration 
...

### Debug logs

```text


2024-09-08 15:01:59.401 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration hacs: cannot import name 'VerificationMaterials' from 'sigstore.verify' (/usr/local/lib/python3.12/site-packages/sigstore/verify/__init__.py)

```

**Comment by gianry** [comment]
@ludeeus 

please see and let me know how to fix the issue .

thanks

**Comment by ludeeus** [comment]
Try setting up the github integration first.
If that fails rebuild your container (ha forum can help with that)

**Comment by gianry** [comment]
I had to create the VM image again and I was able to add the HACS integration
