### ISSUE TITLE
Lost hacs dashboard after upgrade failed of hacs

### ISSUE THREAD

**Issue by agala68** [hacs/integration#4045]
### Web browser

Chrome

### Web browser version

128.0.6613.120

## System Information

version | core-2024.9.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.28+rpt-rpi-v8
arch | aarch64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

Disabled | HACS is not loaded, but HA still requests this information...
-- | --

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 12 (bookworm)
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 116.8 GB
disk_used | 69.2 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2024.8.3), Terminal & SSH (9.14.0), Plex Media Server (3.5.2), Mosquitto broker (6.4.1), VLC (0.3.0), Duck DNS (1.18.0), Samba share (12.3.2), phpMyAdmin (0.9.1), Log Viewer (0.17.0), Vaultwarden (Bitwarden) (0.22.0), NGINX Home Assistant SSL proxy (3.10.1), InfluxDB (5.0.0), MariaDB (2.7.1), Matter Server (6.4.2), Get HACS (1.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 24
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 13 giugno 2024 alle ore 18:39
-- | --
current_recorder_run | 7 settembre 2024 alle ore 23:55
estimated_db_size | 2181.38 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Sonoff</summary>

version | 3.7.3 (e240aaf)
-- | --
cloud_online | 1 / 2
local_online | 1 / 1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

After an upgarde of hacs core component, I cannot see its dashboard anoymore, while all integrations work correctly, I don' trudt the integration new setup, because in the checklist it ask to don't have integrations and I am afraid to loose them, that are working

### Reproduction steps

1.
2.
3.
...
In the manu HACS is not present

### Screenshots

<img width="1125" alt="image" src="https://github.com/user-attachments/assets/00216db4-edea-4767-aa7a-33ea0a23f6d5">

### Javascript logs from your browser console

```text
n/a
```

**Comment by tjorim** [comment]
The repair literally mentions what is wrong.
It's also part of the breaking changes:
"You can no longer configure HACS in YAML."
And there is duplicate 'issue' https://github.com/hacs/integration/issues/3997

**Comment by agala68** [comment]
I have restored the folder custom_components/hacs from a previous backup (version 1.34.0) and it runs correctly, the hacs tab is back, now it propose me to do the upgarde again to 2.0.1, is it safe?

**Comment by agala68** [comment]
if the message is ok, since the tab go awway, how can I upgrade the hacs integrations without the tab?

**Comment by agala68** [comment]
<img width="1157" alt="image" src="https://github.com/user-attachments/assets/8e018bd0-f178-4dfc-bd7f-3e61649d29f2">

**Comment by tjorim** [comment]
Not sure what you are saying. Update the integration and remove your yaml config.
