### ISSUE TITLE
HACS request to have an option to dismiss/skip/snooze notifications to restart

### ISSUE THREAD

**Issue by c11umw** [hacs/integration#4057]
### Web browser

Chrome

### Web browser version

Version 128.0.6613.120 (Official Build) (64-bit)

## System Information

version | core-2024.9.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | x86_64
timezone | Africa/Lagos
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4993
Installed Version | 2.0.1
Stage | running
Available Repositories | 1469
Downloaded Repositories | 52

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 1 January 2018 at 00:00
relayer_connected | false
relayer_region | null
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | false
remote_server | null
certificate_status | null
instance_id | 33666b5ca6244ca6a2c33a8fd1787380
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 125.3 GB
disk_used | 21.4 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (19.0.0), Cloudflared (5.1.19), DHCP server (1.4.0), Home Assistant Google Drive Backup (0.112.1), chrony (3.0.1), Log Viewer (0.17.0), MariaDB (2.7.1), Mosquitto broker (6.4.1), Studio Code Server (5.15.0), Samba share (12.3.2), Tailscale (0.21.0), RPC Shutdown (2.5), SQLite Web (4.2.0), Uptime Kuma (0.12.1), Piper (1.5.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 31
views | 40
mode | storage

</details>

<details><summary>Miele</summary>

component_version | 2024.8.1
-- | --
reach_miele_cloud | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 13 August 2024 at 04:00
-- | --
current_recorder_run | 10 September 2024 at 05:00
estimated_db_size | 8135.23 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Sonoff</summary>

version | 3.8.0 (79ecd72)
-- | --
cloud_online | 0 / 3
local_online | 2 / 2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

HACS is often prompting to update components through the day.
With many of them they require a reboot to complete, this means I can be rebooting our server several times through the day.
Before 2.0 I'd check HACS weekly+ and update en masse.

While you can dismiss/skip the update, if you proceed you can't dismiss, skip or snooze the prompt to reboot as the notification stays until you do. This means we are forced to reset otherwise we might miss a real problem alert thinking it's just the reboot nag.

Ideally we'd wait until later when no motion sensors are active before doing reboots as it saves us wandering through the home to update each sensor that could otherwise be stuck in an active state. 

With Core and OS updates we know it'll reset as part of the update and can plan accordingly.
With the HACS updates we don't know if it will nag for a reset until after it's been updated, otherwise we could skip it 'till later.

### Reproduction steps

1. Update an add-on that needs reboot
...

### Screenshots

No skip
![image](https://github.com/user-attachments/assets/5f047125-bb3c-44e0-b4c4-186426d326cf)

Nag
![image](https://github.com/user-attachments/assets/de9b4c00-a14a-421a-aecd-b44445412004)

### Javascript logs from your browser console

```text
n/a
```

**Comment by ludeeus** [comment]
This is by design; they should not be skipped.
