### ISSUE TITLE
depreciated function

### ISSUE THREAD

**Issue by ronald-winter** [hacs/integration#4060]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to one the HACS add-ons.
- [X] This is a bug and not a feature request.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Which Add-on are you reporting an issue for?

get

### Describe the issue

I hope this is the right section for this issue.

Logger: homeassistant.util.json
Quelle: helpers/deprecation.py:197
Erstmals aufgetreten: 8. September 2024 um 12:11:11 (767 Vorkommnisse)
Zuletzt protokolliert: 12:29:07

json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues

### Add-on logs

No logs available

**Comment by ludeeus** [comment]
It is not, its is also fixe.
update HACS.
