### ISSUE TITLE
HACS Not Updating Repository Information to notifiy of updates

### ISSUE THREAD

**Issue by AaronRichardsWFS** [hacs/integration#4069]
## System Information

version | core-2024.9.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4861
Installed Version | 2.0.1
Stage | running
Available Repositories | 1411
Downloaded Repositories | 32

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 10, 2025 at 8:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-4.ui.nabu.casa
certificate_status | ready
instance_id | db2f792a557745189dc11e213536ffa8
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | beta
supervisor_version | supervisor-2024.09.1
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 116.7 GB
disk_used | 29.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | TasmoAdmin (0.30.5), ESPHome (2024.8.3), Terminal & SSH (9.14.0), HassOS SSH port 22222 Configurator (0.9.3), Mosquitto broker (6.4.1), phpMyAdmin (0.9.1), Portainer (2.21.1), TasmoBackup (1.06.06), Tasmota Device Manager (2022.6.0), Studio Code Server (5.15.0), Samba share (12.3.2), EMQX (0.7.0), Home Assistant Google Drive Backup (0.112.1), Silicon Labs Multiprotocol (2.4.5), Advanced SSH & Web Terminal (19.0.0), Node-RED (18.0.5), Vaultwarden (Bitwarden) (0.22.0), Govee to MQTT Bridge (2024.07.13-82ddc6e9), Matter Server (6.5.1), MariaDB (2.7.1), Z-Wave JS UI (3.11.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 9
views | 19
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 1, 2024 at 11:49 AM
-- | --
current_recorder_run | September 16, 2024 at 9:59 AM
estimated_db_size | 5460.42 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Since updating to the V2 branch i am finding that HACS is not updating repo information.  I have to manually go though all my repos and tell them to update to see which ones have an update.

For instance i know this repo has been updated but still show up in HACS as the old version

![image](https://github.com/user-attachments/assets/5aeb8faf-e8b5-4757-9f8c-45f672888eba)

Once i click the 3 dots and select update then i see there is a newer version.  Some of these have been days updated and not displayed in my UI

After the update information was manually selected
![image](https://github.com/user-attachments/assets/ea2a0408-c2e1-4bfa-905b-2cd29ee0b6b2)

### Reproduction steps

Watch for any updates to Repos

### Debug logs

```text
N/A
```

**Comment by kersten-lohmeyer** [comment]
I have the same problem. HACS is not notifying me of new updates. I have to go into HACS, then I see available updates. But I don't get notified by HA.
