### ISSUE TITLE
New HACS Version: Missing Direct Download Option After Adding Custom Repositories

### ISSUE THREAD

**Issue by Robifz** [hacs/integration#4071]
### Web browser

Chrome

### Web browser version

128.0.6613.138

## System Information

version | core-2024.8.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.28-haos-raspi
arch | aarch64
timezone | Europe/Lisbon
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1408
Downloaded Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 1 January 2018 at 01:00
relayer_connected | false
relayer_region | null
remote_enabled | true
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | null
certificate_status | null
instance_id | 
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.09.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 109.3 GB
disk_used | 21.8 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Cloudflared (5.1.9), ESPHome (2024.7.3), File editor (5.8.0), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.4.0), Advanced SSH & Web Terminal (17.2.0), Studio Code Server (5.15.0), Zigbee2MQTT (1.36.1-1), Glances (0.21.1), Batmon (1.78)

</details>

<details><summary>Dashboards</summary>

dashboards | 19
-- | --
resources | 10
views | 18
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 12 September 2024 at 12:10
-- | --
current_recorder_run | 16 September 2024 at 17:50
estimated_db_size | 741.25 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

In previous versions, after adding a custom repo, it was possible to directly download it by simply clicking on the added repo entry. However, this functionality seems to be missing in the new version.

Currently, after adding a repo, the user has to go back to the store, search for the repo again, and then download it. This is inefficient and disrupts the workflow. Additionally, it's inconsistent since you still allow for bulk deletion, but not for a simple one-click download after adding a repository.

It would greatly improve usability if the previous behavior, where clicking on the added repo entry took you directly to the download page, could be restored.

### Reproduction steps

1. Custom Repositories
2. Type in Repo information and Click Add
3. Clicking on the added Repo does nothing. Only working option is delete.
...

### Screenshots

N/A

### Javascript logs from your browser console

```text
N/A
```

**Comment by Robifz** [comment]
Any update in this issue?

**Comment by ludeeus** [comment]
This is not an issue, it was removed on purpose.
