### ISSUE TITLE
White screen when entering HACS after update

### ISSUE THREAD

**Issue by VanQz** [hacs/integration#4076]
### Web browser

Chrome

### Web browser version

128.0.6613.138 

## System Information

version | core-2024.9.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.1.106-Unraid
arch | x86_64
timezone | Asia/Singapore
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1420
Downloaded Repositories | 19

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 13
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 9, 2024 at 16:08
-- | --
current_recorder_run | September 19, 2024 at 22:56
estimated_db_size | 633.45 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.20
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 0
total_devices | 0

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

After updating HACS and HA, when i try to access HA from my devices or my browser, it is just a white screen. I have tried opening using incognito but to no avail. I tried to roll back to 1.33.0 and it works but the recent version dosent work.

from the console logs, seems like im missing this file `main-c805434e.js`

### Reproduction steps

1. Update to latest HACS version

### Screenshots

![{8477E2FC-3568-4AD3-8906-4F1CBCD581BE}](https://github.com/user-attachments/assets/5bc934af-1025-4a6b-9c08-4879dc2cad23)

### Javascript logs from your browser console

```text
VM482:3 
 GET https://home.XXX.com/hacsfiles/frontend/main-c805434e.js net::ERR_ABORTED 404 (Not Found)
eval	@	VM482:3
(anonymous)	@	entrypoint.js?hacstag=20240903140523:3

hacs:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://home.XXX.com/hacsfiles/frontend/main-c805434e.js
```

**Comment by ludeeus** [comment]
you need to restart and clear app/browser/proxy cache.

**Comment by VanQz** [comment]
i have cleared all cache on browser as well as proxy (my proxy does not cache traffic) but to no avail.
