### ISSUE TITLE
Request for removal of custom-cards/stack-in-card

### ISSUE THREAD

**Issue by sweti3** [hacs/integration#4078]
### Repository

custom-cards/stack-in-card

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

It seems not to be maintained anymore, no answers in the "Issues" part of github, installation currently not working!

### Link to issue

https://github.com/custom-cards/stack-in-card/issues/45

**Comment by ludeeus** [comment]
Linked issue is config problem (and not by you).
