### ISSUE TITLE
Request for removal of georgezhao2010/midea_ac_lan

### ISSUE THREAD

**Issue by Kenneth-Audenaert** [hacs/integration#4086]
### Repository

georgezhao2010/midea_ac_lan

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

no longer maintained and outdated (breaking functionality)

### Link to issue

https://github.com/georgezhao2010/midea_ac_lan/issues/595

**Comment by jszczypk** [comment]
That's a duplicate of #3748

**Comment by BEFH** [comment]
> That's a duplicate of #3748

that's locked for some reason
