### ISSUE TITLE
HACS updated to new version, but no integrations are updated

### ISSUE THREAD

**Issue by bdollerup** [hacs/integration#4097]
## System Information

version | core-2024.9.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.1.0-25-amd64
arch | x86_64
timezone | Europe/Copenhagen
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4991
Installed Version | 2.0.1
Stage | running
Available Repositories | 1494
Downloaded Repositories | 99

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 10. september 2025 kl. 02.00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-9.ui.nabu.casa
certificate_status | ready
instance_id | 5391fc11589c4970a10add22043871aa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 14
-- | --
resources | 48
views | 45
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 21. september 2024 kl. 13.28
-- | --
current_recorder_run | 26. september 2024 kl. 17.03
estimated_db_size | 15878.84 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When updating the integrations, the UI shows that I need to re-start HA. Once HA has restarted the Integration shows up again as needed to be updated:
![image](https://github.com/user-attachments/assets/e52fbfda-c732-4e37-8917-e61b43ee7d92)

### Reproduction steps

1. Update HACS integrations
2. Restart HA
3. All updated integrations shows up again to be updated
...

### Debug logs

```text
Will upload separately
```

### Diagnostics dump

[config_entry-hacs-91c681e60a9d0893275767e4a6da2ef7.json](https://github.com/user-attachments/files/17166084/config_entry-hacs-91c681e60a9d0893275767e4a6da2ef7.json)

**Comment by bdollerup** [comment]
I can't upload the logs as it is too big. Please suggest a means to get the log to you....

**Comment by ludeeus** [comment]
post the last 10 lines of it after stopping.
My guess is that you are not restarting/stopping your container but killing it.

**Comment by chezpaul** [comment]
I've been having the same problem for the past week. I uninstalled HASC 2.0.1 and re installed as per instructions on hast.xyz and I'm still having the same problem. When I update a plugin or module, the update goes by in 5 seconds and it says it's updated. I restart and there it is again asking me to update the same module. I'm running on 2024.9.3 right now. This has started happening after the HASC 2.0 update. 

Reading what @ludeeus wrote above. Yes, I'm actually unplugging my instance of Home assistant as a means of rebooting because my home assistant has stopped restarting over 2 years ago. I've never been able to figure out why. When I check config it just hangs forever, even though I have no errors and system always reboots fine.

Any thoughts?
[home-assistant_2024-09-27T17-14-22.955Z.log](https://github.com/user-attachments/files/17167523/home-assistant_2024-09-27T17-14-22.955Z.log)

**Comment by ludeeus** [comment]
Not sure, HACS writes data every 6 hours.
And when home assistant shuts down (or restarts)
Killing it, breaks the last writes with will cause the issue describes here (and other issues with home assistant, HACS is not the only integration that writes on that signal).
You should try asking on HA discord server for general troubleshooting with HA.

**Comment by chezpaul** [comment]
@ludeeus. I understand what you are saying. But all this was working fine prior to v2 of HASC.
Does my log say anything about failing updates? I'm sorry. I'm not a coder.

**Comment by ludeeus** [comment]
Updates are not failing.
Writing the metadata about the update is just not being done as you terminate it.
Before it wrote too much, that changed to only do it on shutdown (and restart).

**Comment by bdollerup** [comment]
I am restarting the Docker container. I started seeing the same problem that @chezpaul describes above and I started restarting the Docker container. This has worked just fine up til updating the HACS v2.

**Comment by bdollerup** [comment]
Just tried restarting from HA after having updated the HACS components. And I'm happy to report that it worked as @ludeeus suggested. apparently restarting from HA started working again AND all my HACS components were updated.
