### ISSUE TITLE
HACS add on "bad address" - unable to complete installation

### ISSUE THREAD

**Issue by mdkchen** [hacs/integration#4106]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to one the HACS add-ons.
- [X] This is a bug and not a feature request.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Which Add-on are you reporting an issue for?

get

### Describe the issue

Tidying up after reinstalling HAOS (was previously in a container on Lubuntu). 

Previously got HACS to work well, bugged out since conversion over so decided to reinstall from scratch. get HACS add-on seems to have an issue resolving the initial address (log below). 

Simple measures obviously tried (cache cleared, uninstall/reinstall, restarting HAOS)

Core 2024.9.3
Supervisor 2024.09.1
Operating System 13.1
Frontend 20240909.1

Relatively new to HA so apologies if I'm missing something obvious.

### Add-on logs

s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[11:55:14] INFO: ------------------------------------
[11:55:14] INFO: Starting HACS download...
[11:55:14] INFO: Channel: current
[11:55:14] INFO: ------------------------------------
wget: bad address 'raw.githubusercontent.com'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by ludeeus** [comment]
You are having DNS issues, there is not really anything that can be done in the add-on to mitigate that.
I suggest you ask for help with network troubleshooting on the HA Discord server.
<https://www.home-assistant.io/help/>

**Comment by mdkchen** [comment]
Thanks for the advice. This is just a follow up comment RE: eventual resolution.

My issue was derived from originally flashing HAOS from lubuntu with Balena Etcher. Though the flashing seemed successful and HAOS booted, onboarded and seemed to function okay (despite Etcher freezing half way), it seems to have screwed the DNS (though I was still able to ping addresses).

Solution: Start from scratch and flash using USB Imager instead.

https://community.home-assistant.io/t/flashing-hard-drive-get-stuck-at-31-balena-fetcher/604336/37

**Comment by edoardolimone** [comment]
Same here but I've a new HAOS installed with Rasperry PI Imager

The error is the same, when I push Start I obtain this in the log
`[19:13:01] INFO: ------------------------------------
[19:13:01] INFO: Starting HACS download...
[19:13:01] INFO: Channel: development
[19:13:01] INFO: ------------------------------------
[19:13:01] INFO: Downloading the integration source...
Cloning into '/tmp/hacs'...
[19:13:02] INFO: Installing the frontend...
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting hacs-frontend==20240903140523
  Downloading https://github.com/hacs/frontend/releases/download/20240903140523/hacs_frontend-20240903140523-py3-none-any.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 108.7 MB/s eta 0:00:00
Installing collected packages: hacs-frontend
Successfully installed hacs-frontend-20240903140523
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
[19:13:04] INFO: Injecting a version...
[19:13:05] INFO: Version set to: 2.0.2-dev-2d5c1a5
[19:13:05] INFO: Copying the integration source...
[19:13:05] INFO: Download complete...
[19:13:05] INFO: Now, restart Home Assistant. Then, configure it.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
`


How can solve the problem ?
