### ISSUE TITLE
SmartThings Custom Integration Not Present

### ISSUE THREAD

**Issue by Fatalmose** [hacs/integration#4129]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to one the HACS add-ons.
- [X] This is a bug and not a feature request.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Which Add-on are you reporting an issue for?

get

### Describe the issue

I need to do this.

       HACS

     Remove your original smartthings integration if you have one set up (optional)
     Add https://github.com/veista/smartthings as a Custom Repository
     Install SmartThings Custom from the HACS Integrations tab
     Restart Home Assistant
     Install SmartThings from the HA Integrations tab

But when I look for SmartThings Custom on HACS I don't find that...

### Add-on logs

HACS

Remove your original smartthings integration if you have one set up (optional)
Add https://github.com/veista/smartthings as a Custom Repository
Install SmartThings Custom from the HACS Integrations tab
Restart Home Assistant
Install SmartThings from the HA Integrations tab
Enjoy!

**Comment by Fatalmose** [comment]
Thanks for the tip!

Le mer. 9 oct. 2024 à 19:55, hacs-bot[bot] ***@***.***> a
écrit :

**Comment by ludeeus** [comment]
Take any install/config problems with the author of the custom thing you need.
