### ISSUE TITLE
No automatic updates of information for custom repositories

### ISSUE THREAD

**Issue by PiotrMachowski** [hacs/integration#4131]
## System Information

version | core-2024.10.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | x86_64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4971
Installed Version | 2.0.1
Stage | running
Available Repositories | 1453
Downloaded Repositories | 67

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Custom repositories doesn't seem to be checked for updates.

### Reproduction steps

1. Add a custom repository to HACS
2. Create/wait for a new release of this repository
3. No update is visible in HACS (even after HA restart)
4. Force HACS to update information about this repo
5. Update becomes available

### Debug logs

```text
To be provided if really needed.
```

**Comment by ludeeus** [comment]
There is no automatic updates in HACS, that is not something that will be added.

**Comment by PiotrMachowski** [comment]
I have described it incorrectly, I'm sorry. Information about availability of a new release is not updated.

**Comment by ludeeus** [comment]
That is updated every 48h after startup, how long dis you wait?

**Comment by PiotrMachowski** [comment]
I have waited for a much longer than 2 days, buuuut I have an automation that reloads HACS every 24h, so I assume this might be the cause of such behavior. I have created this automation because update entities weren't working when I have turned on experimental features. I have disabled this automation so I will report back in 2 days.

**Comment by ludeeus** [comment]
Yes, doing that will reset the time.
And people doing that is the reason this no longer are fetched during startup.
Closing this now, reopen if its still not working after waiting 48h.
