### ISSUE TITLE
Updated components show up as "Pending" again after restarting HA

### ISSUE THREAD

**Issue by simonszu** [hacs/integration#4132]
### Web browser

Firefox

### Web browser version

131.0.2

## System Information

version | core-2024.10.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.1.0-23-amd64
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4999
Installed Version | 2.0.1
Stage | running
Available Repositories | 1437
Downloaded Repositories | 26

</details>

<details><summary>Dashboards</summary>

dashboards | 11
-- | --
resources | 5
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 1. Oktober 2024 um 08:20
-- | --
current_recorder_run | 11. Oktober 2024 um 12:16
estimated_db_size | 4052.29 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

After upgrading to HACS 2.x, i am encountering an issue where updates to custom components which require a restart of HA after fulfilling them show up as pending after the restart, although the component's manifest on the file system contains the new version number. This is regardless of the actual component, since it currently happens on 11 updates on my environment, so i'll show for one for example. 

### Reproduction steps

1. Open HA in your browser
2. In the settings panel are notifications for updates of custom component
3. For example, update Bambu Lab component from 2.0.21 to 2.0.22
4. Execute the update, it shows a "Restart needed" button
5. Restart HA via "docker restart homeassistant"
6. Reload browser tab
7. See notification for pending updates for Bambu Lab from 2.0.21 to 2.0.22
8. Check `<ha_data_dir>/custom_components/bambu_lab/manifest.json`and see `"version": "2.0.22"`
...

### Screenshots

Update notification in HACS
![Screenshot 2024-10-11 at 12 58 31](https://github.com/user-attachments/assets/9a5fe660-c9c6-4a47-a765-8f8283e28149)

Actual manifest of installed and updated component
![Screenshot 2024-10-11 at 12 58 47](https://github.com/user-attachments/assets/4f9fd174-9b0b-433b-8831-937afee0ad3f)

### Javascript logs from your browser console

```text
No console output is generated
```

### Diagnostics dump

[config_entry-hacs-af84f2cc04b768fb3ec7ba6ec2fcd2d8.json](https://github.com/user-attachments/files/17341668/config_entry-hacs-af84f2cc04b768fb3ec7ba6ec2fcd2d8.json)

Interestingly the diagnostics dump also show the upgraded versions installed, so i deduct that it's a frontend issue.

**Comment by ludeeus** [comment]
That happens when you do not restart, but terminate your container.
Adjust your termination logic to give home assistant enough time to handle the final write.
