### ISSUE TITLE
not detecting repository being unarchived

### ISSUE THREAD

**Issue by xip0rt** [hacs/integration#4136]
## System Information

version | core-2024.10.2
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.1.21-v8+
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4979
Installed Version | 2.0.1
Stage | running
Available Repositories | 1447
Downloaded Repositories | 25

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2024.10.0
agent_version | 1.4.1
docker_version | 27.3.1
disk_total | 114.7 GB
disk_used | 17.2 GB
healthy | true
supported | failed to load: Unsupported
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Terminal & SSH (9.15.0), Mosquitto broker (6.4.1), SQLite Web (4.2.2), openWakeWord (1.10.0)

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

There was a repository that was previously marked archived, but has since been un-archived. I still get an entry in the error log complaining about this repo being archived every time I restart HASS.

Tried "update information" and "redownload" for this repo in the HACS dashboard, yet this issue persists. Maybe the repo just hasn't been added back to HACS (and I'm only seeing it because I still have it installed)? In which case this issue should be converted to an add-on request.

I just don't want to completely "remove" it and find out if that's the case because the addon is still fully functional.

### Reproduction steps

1. use a time machine to add room-card repository to HACS before it was archived
2. still have room-card repository installed after it was unarchived
3. continue to see this appear in your error logs

### Debug logs

```text
You have 'marcokreeft87/room-card' installed with HACS this repository has been removed from HACS, please consider removing it. Removal reason (Repository is archived)
```

**Comment by ludeeus** [comment]
There is no automatic removal or re-add.
Once removed, the author needs to make a request to have it added back.
