### ISSUE TITLE
Request for removal of dalinicus/homeassistant-aerogarden

### ISSUE THREAD

**Issue by doctorkb** [hacs/integration#4145]
### Repository

dalinicus/homeassistant-aerogarden

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

The API has changed and hasn't been improved.  Furthermore, Aerogarden is winding down operations, with unclear terms on when their app will stop working.

### Link to issue

https://github.com/dalinicus/homeassistant-aerogarden/issues/36

**Comment by ludeeus** [comment]
CC @dalinicus

**Comment by dalinicus** [comment]
@ludeeus @doctorkb 

I already have an open issue for removal #4144 :)

I didn't see instructions for PRing a removal, so I used the incident form.

**Comment by dalinicus** [comment]
sorry, flubbed up the issue link.  Fixed.

**Comment by doctorkb** [comment]
closing as duplicate of #4142 - sorry I missed that!
