### ISSUE TITLE
Plugin Repository structure is not compliant Errors

### ISSUE THREAD

**Issue by thlucas1** [hacs/integration#4153]
### Describe the issue

I keep getting a generic "Error:  <Plugin X> Repository structure for Y is not compliant" error message when trying to run the validate.yml job on github for a new HACS PlugIn repository: [https://github.com/thlucas1/spotifyplus_card](https://github.com/thlucas1/spotifyplus_card).

I cloned the project code from an existing project that runs the HACS Validation just fine in it's repository hacs validation job.  
The only difference between the new repo that is failing and the one succeeding is that I created the new repo using the `gh` tools via command line.

I believe that I have the repository setup correctly, meeting all of the HACS [General Requirements](https://www.hacs.xyz/docs/publish/start/#hacsjson) as well as the [Plugin-specific Requirements](https://www.hacs.xyz/docs/publish/plugin/).  The new repository contains a description, topics are assigned, web-page assigned, wiki / issues / discussions configured.  The dist folder will contain the `spotifyplus-card.js` file upon successful build.  I also created an initial release in the repo

There is nothing in the HACS Validation step debug log that jumps out, other than the `x is missing key y` statements which I have no idea what they mean:
```
'GitHubResponseHeadersModel' is missing key 'x_accepted_github_permissions' for <class 'str'>
'GitHubBaseUserModel' is missing key 'user_view_type' for <class 'str'>
'GitHubBaseUserModel' is missing key 'user_view_type' for <class 'str'>
<Plugin thlucas1/spotifyplus_card> Running checks against refs/heads/master
'GitHubResponseHeadersModel' is missing key 'x_accepted_github_permissions' for <class 'str'>
```

Any ideas?

validate.yml job:
```
## https://github.com/thlucas1/spotifyplus_card/actions/runs/11472092157/workflow
jobs:
  validate-hacs: # https://github.com/hacs/action
    name: "HACS Validation"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@main"

        - name: "Run HACS validation"
          uses: "hacs/action@main"
          with:
            category: "plugin"
```

Debug Log:
```
...
##[debug]Loading env
Run hacs/action@main
/usr/bin/docker run --name ghcriohacsactionmain_cbc6a6 --label 990b95 --workdir /github/workspace --rm -e "INPUT_CATEGORY" -e "INPUT_IGNORE" -e "INPUT_REPOSITORY" -e "INPUT_COMMENT" -e "INPUT_GITHUB_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_DEBUG" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/spotifyplus_card/spotifyplus_card":"/github/workspace" ghcr.io/hacs/action:main
##[debug] Using selector: EpollSelector
::INFO:: Category: plugin
::INFO:: Repository: thlucas1/spotifyplus_card@refs/heads/master
##[debug] <Plugin thlucas1/spotifyplus_card> Checking repository.
##[debug] 'GitHubResponseHeadersModel' is missing key 'x_accepted_github_permissions' for <class 'str'>
##[debug] 'GitHubBaseUserModel' is missing key 'user_view_type' for <class 'str'>
##[debug] 'GitHubBaseUserModel' is missing key 'user_view_type' for <class 'str'>
##[debug] <Plugin thlucas1/spotifyplus_card> Running checks against refs/heads/master
##[debug] 'GitHubResponseHeadersModel' is missing key 'x_accepted_github_permissions' for <class 'str'>
Error:  <Plugin thlucas1/spotifyplus_card> Repository structure for refs/heads/master is not compliant
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Run HACS validation
```

### Link to action run

https://github.com/thlucas1/spotifyplus_card/actions/runs/11484058713

### Link to action configuration

https://github.com/thlucas1/spotifyplus_card/actions/runs/11484058713/workflow

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the HACS action.
- [X] This is a bug and not a feature request.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment]
Your repo is with _ and your file is with -

**Comment by thlucas1** [comment]
Thanks for the reply @ludeeus .

I understand your point about the underscore versus dash.

What's odd is that my working [soundtouchplus card repository](https://github.com/thlucas1/homeassistantcomponent_soundtouchplus_card) uses the same concept - it's repo name is `homeassistantcomponent_soundtouchplus_card`, and it contains a dist file path of `/dist/soundtouchplus-card.js` (note the omission of the `homeassistantcomponent_` prefix, and dash in the JS filename).

I wanted to shorten the path of my new [spotifyplus card repository](https://github.com/thlucas1/spotifyplus_card) by omitting the `homeassistantcomponent_` prefix, and set it up the same way as the soundtouchplus card.

Just wondering why the soundtouchplus card works and the spotifyplus card does not?

I do have a `release.yml` job that runs, which does some magic in the `Upload Files to Release` step - but that just affects the .zip file that get appended to the release build.
```
name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Prepare Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Repository checkout"
        uses: "actions/checkout@v4"

      - name: "NPM Build Plugin"
        run: |
          cd "${{ github.workspace }}"
          npm install
          npm run buildgithub

      - name: "Upload Files to Release"
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: "${{ github.workspace }}/dist/soundtouchplus-card.js"

      # plugin file(s) will be placed in the following Home Assistant configuration directory 
      # location once it is installed via HACS:
      # "/config/www/community/homeassistantcomponent_soundtouchplus_card/soundtouchplus-card.js"

```

**Comment by ludeeus** [comment]
oh so you are not using dist at all..
Your latest commit is from before your first release, try opening a PR in your repo now, might have been a timing issue.

**Comment by thlucas1** [comment]
Nope, not a timing thing - still failed.

I went ahead and replaced the dash with underscore, recompiled, and that fixed it.

I was just curious as to why the other worked and this did not, but no worries.  It's a small thing, and it's working now.

I appreciate your help - thank you for pointing me in the right direction with the underscores.
