### ISSUE TITLE
Can't bring up update information panel with latest HACS

### ISSUE THREAD

**Issue by ericswpark** [hacs/integration#4157]
### Web browser

Firefox

### Web browser version

131.0.3

## System Information

version | core-2024.10.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4823
Installed Version | 2.0.1
Stage | running
Available Repositories | 1452
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.10.3
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 30.8 GB
disk_used | 6.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Matter Server (6.6.0), ESPHome (2024.10.2), Tailscale (0.23.1), Advanced SSH & Web Terminal (19.0.0), Mosquitto broker (6.4.1), Zigbee2MQTT (1.40.2-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 19, 2024 at 5:57 PM
-- | --
current_recorder_run | October 26, 2024 at 10:24 AM
estimated_db_size | 16.92 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When an update is available for any of the items in HACS, either within the official repositories or a custom repository that I added, clicking on the "Update Information" menu in the overflow menu does nothing. There is one warning logged in the browser console, and there is no other way to update the item. Sometimes the item does show up under the general updates section of HA when I click into "Settings" of HA but this doesn't always show up.

### Reproduction steps

1. Find item with update (or push new commit to custom repo)
2. Click on overflow menu
3. Click on "Update Information"

### Screenshots

![image](https://github.com/user-attachments/assets/b55398df-823b-4d6c-86cd-f40332f2e0fa)

### Javascript logs from your browser console

```text
Keyframe property value “” is invalid according to the syntax for “transform”. 2 menu.ts:722:49
```

### Diagnostics dump

[config_entry-hacs-5823a6399964af06fffb60605a162625.json](https://github.com/user-attachments/files/17531012/config_entry-hacs-5823a6399964af06fffb60605a162625.json)

**Comment by ludeeus** [comment]
"Update information" updates what HACS knows about the repository, it does not update any files.
Use the update entity, or the "redownload" dialog for that.

**Comment by ericswpark** [comment]
@ludeeus then can there be some sort of modal or toast to let users know that the operation succeeded? I was expecting something to show like the other options.
