### ISSUE TITLE
Repos not visible

### ISSUE THREAD

**Issue by isibizi** [hacs/integration#4168]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to one the HACS add-ons.
- [X] This is a bug and not a feature request.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Which Add-on are you reporting an issue for?

get

### Describe the issue

Hello,

I’m unable to see any repositories in HACS. I have already uninstalled and reinstalled HACS version 2.0.1, cleared my cache, etc., but the issue persists.

I have definitely installed some repositories, but none of them are visible. Even when I install new repositories, they don’t appear in the list.

Any help would be appreciated.

![image](https://github.com/user-attachments/assets/632fc68a-2edf-424d-a6e2-17cb35db0384)

### Add-on logs

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.10.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.6.54-haos",
    "supervisor": "2024.10.3",
    "host_os": "Home Assistant OS 13.2",
    "docker_version": "27.2.0",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "2.0.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "alexa_media": {
      "documentation": "https://github.com/alandtse/alexa_media_player/wiki",
      "version": "4.13.5",
      "requirements": [
        "alexapy==1.29.3",
        "packaging>=20.3",
        "wrapt>=1.14.0"
      ]
    },
    "better_thermostat": {
      "documentation": "https://github.com/KartoffelToby/better_thermostat",
      "version": "1.6.0",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "hacs",
    "name": "HACS",
    "after_dependencies": [
      "python_script"
    ],
    "codeowners": [
      "ludeeus"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "websocket_api",
      "frontend",
      "persistent_notification",
      "lovelace",
      "repairs"
    ],
    "documentation": "https://hacs.xyz/docs/configuration/start",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/hacs/integration/issues",
    "requirements": [
      "aiogithubapi>=22.10.1"
    ],
    "version": "2.0.1",
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 4.903999979433138e-06
    },
    "01JBAPGNV0RWM64V3BA9476F85": {
      "wait_import_platforms": -0.5093203300000368,
      "config_entry_setup": 0.599021596
    }
  },
  "data": {
    "entry": {
      "created_at": "2024-10-28T23:13:58.112585+00:00",
      "data": {
        "token": "**REDACTED**"
      },
      "discovery_keys": {},
      "disabled_by": null,
      "domain": "hacs",
      "entry_id": "01JBAPGNV0RWM64V3BA9476F85",
      "minor_version": 1,
      "modified_at": "2024-10-28T23:13:58.112586+00:00",
      "options": {
        "experimental": true
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "title": "",
      "unique_id": null,
      "version": 1
    },
    "hacs": {
      "stage": "running",
      "version": "2.0.1",
      "disabled_reason": null,
      "new": false,
      "startup": false,
      "categories": [
        "theme",
        "integration",
        "plugin",
        "template"
      ],
      "renamed_repositories": {
        "xMrVizzy/Philips-AirPurifier": "kraineff/philips-airpurifier",
        "scottyphillips/mitsubishi_hass": "scottyphillips/echonetlite_homeassistant",
        "idittansikte/bootstrap-grid-card": "ownbee/bootstrap-grid-card",
        "marksie1988/atomic-calendar-revive": "totaldebug/atomic-calendar-revive",
        "PepegaBruh/CryptoTracker": "BigNocciolino/CryptoTracker",
        "9a4gl/hass-peltec": "9a4gl/hass-centrometal-boiler",
        "78wesley/Darkish-Theme": "78wesley/Home-Assistant-Darkish-Theme",
        "KartoffelToby/ai_thermostat": "KartoffelToby/better_thermostat",
        "nbogojevic/homeassistant-midea-dehumidifier-lan": "nbogojevic/homeassistant-midea-air-appliances-lan",
        "nikrolls/homeassistant-goldair-climate": "nicole-ashley/homeassistant-goldair-climate",
        "ulic75/power-distribution-card": "ulic75/power-flow-card",
        "wills106/homsassistant-solax-modbus": "wills106/homeassistant-solax-modbus",
        "dmitry-k/yandex_smart_home": "dext0r/yandex_smart_home",
        "uvjustin/alarmdotcom": "pyalarmdotcom/alarmdotcom",
        "wernerhp/appdaemon_wasp": "wernerhp/ha.appdaemon.wasp",
        "wernerhp/appdaemon_aqara_motion_sensors": "wernerhp/ha.appdaemon.aqara_motion_sensors",
        "wernerhp/ha_integration_load_shedding": "wernerhp/ha.integration.load_shedding",
        "TheLastProject/lovelace-valetudo-map-card": "Hypfer/lovelace-valetudo-map-card",
        "fuatakgun/kia_uvo": "Hyundai-Kia-Connect/kia_uvo",
        "DarkSir23/sensor.mylar": "WillowMist/sensor.mylar",
        "rj175/home-assistant-aws-codepipeline": "ohheyrj/home-assistant-aws-codepipeline",
        "jadson179/controlid": "gtjadsonsantos/controlid",
        "jadson179/vapix": "gtjadsonsantos/vapix",
        "jadson179/consul": "gtjadsonsantos/consul",
        "custom-components/integration_blueprint": "ludeeus/integration_blueprint",
        "mtarjoianu/ha_lektrico": "Lektrico/ha_lektrico",
        "haberda/update_lights": "haberda/Periodic-lights",
        "Wibias/hass-variables": "enkama/hass-variables",
        "custom-components/alexa_media_player": "alandtse/alexa_media_player",
        "johanfrick/custom-sonos-card": "punxaphil/custom-sonos-card",
        "arjenvrh/audi_connect_ha": "audiconnect/audi_connect_ha",
        "orickcorreia/caule-themes-pack-1": "ricardoquecria/caule-themes-pack-1",
        "htmltiger/numberbox-card": "junkfix/numberbox-card",
        "htmltiger/config-editor": "junkfix/config-editor",
        "htmltiger/config-editor-card": "junkfix/config-editor-card",
        "jonasniesner/open_epaper_link_homeassistant": "OpenEPaperLink/Home_Assistant_Integration",
        "Limych/ha-temperature-feels-like": "Limych/ha-apparent-temperature",
        "wimb0/home-assistant-saj-modbus": "wimb0/home-assistant-saj-r5-modbus",
        "t0mer/ims-custom-component": "GuyKh/ims-custom-component",
        "jm-73/Indego": "sander1988/Indego"
      },
      "archived_repositories": [
        "sakowicz/home-assistant-tenda-tracker",
        "JuanMTech/orange_dark",
        "JuanMTech/amoled_blue",
        "ppanagiotis/pymusiccast",
        "KTibow/lovelace-light-soft-ui-theme",
        "marrobHD/firetv-card",
        "tikismoke/home-assistant-nespressoble",
        "GeorgeSG/lovelace-folder-card",
        "dgomes/ha_rrd_recorder",
        "DCSBL/ha-homewizard-energy",
        "eavanvalkenburg/sia",
        "custom-components/sensor.tautulli",
        "Kraineff/philips-airpurifier",
        "nagyrobi/home-assistant-custom-components-pfsense-gateways",
        "marcomow/ble-bulb-card",
        "Sholofly/arrisdcx960",
        "dummylabs/watchman",
        "ThomasPrior/EthermineInfo",
        "chaptergy/noctis-grey",
        "Michsior14/ha-laser-egg",
        "DeebotUniverse/Deebot-4-Home-Assistant",
        "Petro31/ad_people_tracker",
        "briis/smartweather",
        "DavidMStraub/homeassistant-homeconnect",
        "heinoldenhuis/home_assistant_omnik_solar",
        "JuanMTech/green_dark_mode",
        "jensweimann/awb",
        "iantrich/aftership-card",
        "DSorlov/hasl-platform",
        "clayauld/lovelace-darksky-card",
        "georgezhao2010/climate_ewelink",
        "custom-components/sensor.untappd",
        "briis/hass-weatherflow",
        "disforw/inverse",
        "custom-components/sensor.custom_components",
        "atomic7777/atomic_calendar",
        "pilotak/homeassistant-mikrotik",
        "dr1rrb/ha-twinkly",
        "Thomas55555/husqvarna_automower",
        "jessevl/homeassistant-greenchoice",
        "custom-components/wienerlinien",
        "KTibow/lovelace-dark-soft-ui-theme",
        "Cyr-ius/hass-hue-service-advanced",
        "cgarwood/homeassistant-fullykiosk",
        "robmarkcole/HASS-Deepstack-face",
        "walthowd/ha-automower",
        "gerardag/person-entity-card",
        "pfunkmallone/HACS-camect-integration",
        "lukich48/hass_mqtt_template_switch",
        "spycle/microbot_push",
        "custom-components/custom_components",
        "patrickhilker/tedee_hass_integration",
        "pfunkmallone/HACS-camect-custom_card",
        "speleolontra/daikin_residential_altherma",
        "Mr-Groch/HA-Emulated-Color-Temp-Light",
        "robmarkcole/HASS-Deepstack-object",
        "JuanMTech/green_light_mode",
        "pippyn/Home-Assistant-Sensor-Groningen-Afvalwijzer",
        "digitaljamie/google-theme",
        "estevez-dev/extended-banner-card",
        "mampfes/hacs_wiffi",
        "PTST/O365-HomeAssistant",
        "thebino/rki_covid",
        "KoljaWindeler/kaco",
        "JuanMTech/orange_light",
        "Cyr-ius/hass-cozytouch",
        "alexarch21/history-explorer-card"
      ],
      "ignored_repositories": [],
      "lovelace_mode": "storage",
      "configuration": {
        "appdaemon": false,
        "country": "ALL",
        "debug": false,
        "dev": false,
        "python_script": false,
        "release_limit": 5,
        "theme": false
      }
    },
    "custom_repositories": [],
    "repositories": [
      {
        "data": {
          "archived": false,
          "authors": [
            "@kartoffeltoby"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "This custom component for Home Assistant will add crucial features to your climate-controlling TRV (Thermostatic Radiator Valves) to save you the work of creating automations to make it smart. It combines a room-temperature sensor, window/door sensors, weather forecasts, or an ambient temperature probe to decide when it should call for heat and automatically calibrate your TRVs to fix the imprecise measurements taken in the radiator's vicinity.",
          "domain": "better_thermostat",
          "downloads": 0,
          "etag_repository": "W/\"17ee28c04621d3204ee7541ddda20ffd291fde853f874c421bd109f5820ecd46\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "KartoffelToby/better_thermostat",
          "hide": false,
          "has_issues": true,
          "id": "422931599",
          "installed_commit": "23b3f23",
          "installed_version": "1.6.0",
          "installed": true,
          "last_commit": "23b3f23",
          "last_updated": "2024-07-23T08:24:43Z",
          "last_version": "1.6.0",
          "manifest_name": "Better Thermostat",
          "new": false,
          "open_issues": 0,
          "prerelease": null,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": true,
          "stargazers_count": 810,
          "topics": [
            "climate",
            "energy-efficiency",
            "moes",
            "sea801",
            "sea802",
            "spzb0001",
            "thermostat",
            "ts0601",
            "tuya",
            "zigbee",
            "zigbee2mqtt"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": true,
          "homeassistant": "2022.8.0",
          "manifest": {
            "name": "Better Thermostat",
            "render_readme": true,
            "homeassistant": "2022.8.0",
            "hide_default_branch": true
          },
          "name": "Better Thermostat",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/better_thermostat",
          "local": "/config/custom_components/better_thermostat",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@ludeeus"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "HACS gives you a powerful UI to handle downloads of all your custom needs.",
          "domain": "hacs",
          "downloads": 425372,
          "etag_repository": "W/\"782f673ed67686d2803072e77e55f2023b9296107bbee7f930adbd38d71bab5b\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "hacs/integration",
          "hide": false,
          "has_issues": true,
          "id": "172733314",
          "installed_commit": "b035707",
          "installed_version": "2.0.1",
          "installed": true,
          "last_commit": "91cf950",
          "last_updated": "2024-10-28T08:09:30Z",
          "last_version": "2.0.1",
          "manifest_name": "HACS",
          "new": false,
          "open_issues": 0,
          "prerelease": null,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 5340,
          "topics": [
            "community",
            "package-manager"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "hacs.zip",
          "hacs": "0.19.0",
          "hide_default_branch": true,
          "homeassistant": "2024.4.1",
          "manifest": {
            "name": "HACS",
            "zip_release": true,
            "hide_default_branch": true,
            "homeassistant": "2024.4.1",
            "hacs": "0.19.0",
            "filename": "hacs.zip"
          },
          "name": "HACS",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/hacs",
          "local": "/config/custom_components/hacs",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "config_flow": false,
          "default_branch": null,
          "description": "Additional vector icons for home assistant to model Philips  Hue bulbs and fixtures. ",
          "domain": null,
          "downloads": 17664,
          "etag_repository": "W/\"cea3ba117e6f014d14304ec7655bd17aadd4d46bcca7dd5341876be5e5ef0ea3\"",
          "etag_releases": null,
          "file_name": null,
          "first_install": false,
          "full_name": "arallsopp/hass-hue-icons",
          "hide": false,
          "has_issues": true,
          "id": "384434522",
          "installed_commit": "4604f9a",
          "installed_version": "v1.2.53",
          "installed": true,
          "last_commit": "4604f9a",
          "last_updated": "2023-12-13T18:53:17Z",
          "last_version": "v1.2.53",
          "manifest_name": null,
          "new": false,
          "open_issues": 0,
          "prerelease": null,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 300,
          "topics": [
            "custom-icons",
            "hue",
            "hue-lights",
            "icons",
            "iconset",
            "philips-hue",
            "svg"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": null,
          "manifest": {
            "name": "Hass Hue Icons",
            "render_readme": true
          },
          "name": "Hass Hue Icons",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": null,
        "paths": {
          "localpath": "/config/www/community/hass-hue-icons",
          "local": "/config/www/community/hass-hue-icons",
          "remote": null
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@alandtse",
            "@keatontaylor"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "This is a custom component to allow control of Amazon Alexa devices in Home Assistant using the unofficial Alexa API.",
          "domain": "alexa_media",
          "downloads": 36321,
          "etag_repository": "W/\"b0508eebf54dee52b8109326236540119c571361b724e2cb96468d4c486ff7dd\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "alandtse/alexa_media_player",
          "hide": false,
          "has_issues": true,
          "id": "139664351",
          "installed_commit": "b6c45d0",
          "installed_version": "v4.13.5",
          "installed": true,
          "last_commit": "64fd602",
          "last_updated": "2024-10-28T20:36:49Z",
          "last_version": "v4.13.5",
          "manifest_name": "Alexa Media Player",
          "new": false,
          "open_issues": 0,
          "prerelease": null,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 1504,
          "topics": [
            "alexa"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "alexa_media.zip",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2024.2.0b0",
          "manifest": {
            "name": "Alexa Media Player",
            "zip_release": true,
            "filename": "alexa_media.zip",
            "homeassistant": "2024.2.0b0"
          },
          "name": "Alexa Media Player",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/alexa_media",
          "local": "/config/custom_components/alexa_media",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "config_flow": false,
          "default_branch": null,
          "description": "Build a beautiful Home Assistant dashboard easily",
          "domain": null,
          "downloads": 147466,
          "etag_repository": "W/\"af04d94573e26184e6b93724f31302e03212282a1a2c202a4f1211dd0ec7c7b7\"",
          "etag_releases": null,
          "file_name": null,
          "first_install": false,
          "full_name": "piitaya/lovelace-mushroom",
          "hide": false,
          "has_issues": true,
          "id": "444350375",
          "installed_commit": "d5baf62",
          "installed_version": "v4.0.7",
          "installed": true,
          "last_commit": "0460e99",
          "last_updated": "2024-10-01T20:03:54Z",
          "last_version": "v4.0.7",
          "manifest_name": null,
          "new": false,
          "open_issues": 0,
          "prerelease": null,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 3654,
          "topics": [
            "card",
            "mushroom"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "mushroom.js",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2024.7.0b0",
          "manifest": {
            "name": "Mushroom",
            "filename": "mushroom.js",
            "homeassistant": "2024.7.0b0",
            "render_readme": true
          },
          "name": "Mushroom",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": null,
        "paths": {
          "localpath": "/config/www/community/lovelace-mushroom",
          "local": "/config/www/community/lovelace-mushroom",
          "remote": null
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "config_flow": false,
          "default_branch": null,
          "description": "a custom card for a better thermostat in home assistant based on better_thermostat intigration",
          "domain": null,
          "downloads": 45095,
          "etag_repository": "W/\"e1de7530ceaac8fce51e8221748eff0ec6ba1e3a5c1dd49e35c7d9123038af11\"",
          "etag_releases": null,
          "file_name": null,
          "first_install": false,
          "full_name": "KartoffelToby/better-thermostat-ui-card",
          "hide": false,
          "has_issues": true,
          "id": "439367892",
          "installed_commit": "015d5e5",
          "installed_version": "2.2.0",
          "installed": true,
          "last_commit": "4d50fea",
          "last_updated": "2024-07-14T01:10:01Z",
          "last_version": "2.2.0",
          "manifest_name": null,
          "new": false,
          "open_issues": 0,
          "prerelease": null,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": true,
          "stargazers_count": 220,
          "topics": [
            "thermostat"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "better-thermostat-ui-card.js",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": null,
          "manifest": {
            "name": "Better Thermostat UI",
            "render_readme": true,
            "filename": "better-thermostat-ui-card.js"
          },
          "name": "Better Thermostat UI",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": null,
        "paths": {
          "localpath": "/config/www/community/better-thermostat-ui-card",
          "local": "/config/www/community/better-thermostat-ui-card",
          "remote": null
        }
      }
    ],
    "rate_limit": {
      "resources": {
        "core": {
          "limit": 5000,
          "used": 43,
          "remaining": 4957,
          "reset": 1730158611
        },
        "search": {
          "limit": 30,
          "used": 0,
          "remaining": 30,
          "reset": 1730157828
        },
        "graphql": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1730161368
        },
        "integration_manifest": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1730161368
        },
        "source_import": {
          "limit": 100,
          "used": 0,
          "remaining": 100,
          "reset": 1730157828
        },
        "code_scanning_upload": {
          "limit": 1000,
          "used": 0,
          "remaining": 1000,
          "reset": 1730161368
        },
        "actions_runner_registration": {
          "limit": 10000,
          "used": 0,
          "remaining": 10000,
          "reset": 1730161368
        },
        "scim": {
          "limit": 15000,
          "used": 0,
          "remaining": 15000,
          "reset": 1730161368
        },
        "dependency_snapshots": {
          "limit": 100,
          "used": 0,
          "remaining": 100,
          "reset": 1730157828
        }
      },
      "rate": {
        "limit": 5000,
        "used": 43,
        "remaining": 4957,
        "reset": 1730158611
      }
    }
  }
}

**Comment by ludeeus** [comment]
repos visible in posted image.

**Comment by isibizi** [comment]
Two different setups, both have the same HACS version.


![3d133479-f92a-4c6b-a7ac-5cf82e9d60e0](https://github.com/user-attachments/assets/9ee68d8b-c5f4-49ad-9506-20a14a372173)
![IMG_1895](https://github.com/user-attachments/assets/3e2e23fc-0d12-4272-b800-ab9520dcb477)
