### ISSUE TITLE
Request for removal of georgezhao2010/midea_ac_lan

### ISSUE THREAD

**Issue by vernazza** [hacs/integration#4170]
### Repository

georgezhao2010/midea_ac_lan

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

The project cannot be installed (there is an error for missing file), no new version has been published since an year, the repository has not been updated since 9 months and it is abandoned

### Link to issue

https://github.com/georgezhao2010/midea_ac_lan/issues/595

**Comment by BEFH** [comment]
Why was this closed? Shouldn't the new repo be used, @vernazza?

**Comment by vernazza** [comment]
@BEFH I realized that it is a duplicate of https://github.com/hacs/integration/issues/3748

**Comment by BEFH** [comment]
Oh, word. It's been over a month on that without response from the original
maintainer BTW.
