### ISSUE TITLE
No UI

### ISSUE THREAD

**Issue by babyjames10** [hacs/integration#4197]
### Web browser

safari

### Web browser version

18.1

## System Information

version | core-2024.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4940
Installed Version | 2.0.1
Stage | running
Available Repositories | 1529
Downloaded Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.3
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 116.8 GB
disk_used | 8.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi5-64
supervisor_api | ok
version_api | ok
installed_addons | Scrypted (v0.120.0-jammy-full), Get HACS (1.3.1), Terminal & SSH (9.15.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 9, 2024 at 6:30 AM
-- | --
current_recorder_run | November 12, 2024 at 7:39 PM
estimated_db_size | 6.72 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I recently installed HACS. When I open it from the sidebar I don't get an UI with options. I get a page describing HACS. 

### Reproduction steps

1.click on HACS in sidebar
2.it takes me to a HACS icon and under the icon their is downloads where I can download apps. 
3.when I click the HACS icon it takes me to a page that gives me a description of HACS. I provided a screenshot. 
...

### Screenshots

<img width="1254" alt="Screenshot 2024-11-12 at 8 15 29 PM" src="https://github.com/user-attachments/assets/8fdf5065-1f1e-4d41-a558-16e3f5d8e13f">

### Javascript logs from your browser console

```text
Can't seem to pull it up from my MacBook.
```

**Comment by babyjames10** [comment]
[cb646a50_get_2024-11-13T02-09-19.076Z.log](https://github.com/user-attachments/files/17725173/cb646a50_get_2024-11-13T02-09-19.076Z.log)

**Comment by tjorim** [comment]
Nothing wrong, UI works. If you click on HACS in the sidebar you can search straight away. HACS itself is also a custom integration which will show up in HACS as downloaded. You seem to have clicked on HACS in the list of downloaded integrations. Documentation can be found here: https://hacs.xyz/docs/use/repositories/dashboard/

**Comment by tjorim** [comment]
Btw, the logs you provided are the ones of the Get HACS add-on which just downloads HACS for your convenience. It only needs to be run once.
