### ISSUE TITLE
dreame account not recognized

### ISSUE THREAD

**Issue by Fenixcyber** [hacs/integration#4200]
### System Health details

Hi everyone, I can't, after installing the integration, the dream account I use for the app is selected, it doesn't let me continue with the user error message and incorrect psw, has anyone had the same problem?

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Hi everyone, I can't, after installing the integration, the dream account I use for the app is selected, it doesn't let me continue with the user error message and incorrect psw, has anyone had the same problem?

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
.
```

**Comment by tjorim** [comment]
Dream account? App?

**Comment by Fenixcyber** [comment]
dreame account and app account are the same

Il Sab 16 Nov 2024, 12:10 Jorim Tielemans ***@***.***> ha
scritto:

**Comment by tjorim** [comment]
Sounds like you're talking about some custom integration, not HACS itself.

**Comment by Fenixcyber** [comment]
I installed the dreame vacum integration via hacs following the guided
configuration it makes me select if I want to connect with the dreame
account I enter the user and password of the dreame account with which I
log in to the app and the site but it does not recognize it

Il Sab 16 Nov 2024, 13:07 Jorim Tielemans ***@***.***> ha
scritto:
