### ISSUE TITLE
Please indicate how to 'open' or 'find' HACS once its installed

### ISSUE THREAD

**Issue by infrachris** [hacs/integration#4223]
### Describe the issue

This would help people use the product, I installed it but can't find it.  I'm sure this is endless eye roles, but this is a common real world situation.  Anyone using the instructions, has never used HACS and doesn't automatically know how to find it once installed.  Thank you

**Comment by ludeeus** [comment]
https://hacs.xyz/docs/use/repositories/dashboard/
