### ISSUE TITLE
Hacs not installing

### ISSUE THREAD

**Issue by wlambermont** [hacs/integration#4281]
## System Information

version | core-2024.12.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.66-haos
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.0
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 30.8 GB
disk_used | 9.5 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Matter Server (6.6.1), Grafana (10.2.2), Advanced SSH & Web Terminal (19.0.0), Get HACS (1.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 0
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 20 december 2024 om 12:51
-- | --
current_recorder_run | 20 december 2024 om 16:12
estimated_db_size | 3.48 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When I try to add HACS by installing it through the addon store, the "installation" works, then I say start. But the HACKS store doesn't show up anywhere. It then also stops running, there is no log or anything. Followed some guides downgrading the verions of HA but that didn't worked either. So something seems broken.

### Reproduction steps

1. Settings, addons, addon store, get HACS
2. click install
3. start, but nothing happens
4. reboot system, still nothing happens. No log nothing mentioned.

### Debug logs

```text
Connecting to raw.githubusercontent.com (185.199.108.133:443)
saving to './get-hacs'
get-hacs             100% |********************************|  4990  0:00:00 ETA
'./get-hacs' saved
INFO: Trying to find the correct directory...
INFO: Found Home Assistant configuration directory at '/homeassistant'
INFO: Changing to the custom_components directory...
INFO: Downloading HACS
Connecting to github.com (140.82.121.4:443)
Connecting to github.com (140.82.121.4:443)
Connecting to objects.githubusercontent.com (185.199.110.133:443)
saving to 'hacs.zip'
hacs.zip              47% |***************                 | 7838k  0:00:01 ETA
hacs.zip             100% |********************************| 16.0M  0:00:00 ETA
'hacs.zip' saved
WARN: HACS directory already exist, cleaning up...
INFO: Creating HACS directory...
INFO: Unpacking HACS...
INFO: Verifying versions
INFO: Current version is 2024.12.5, minimum version is 2024.4.1
INFO: Removing HACS zip file...
INFO: Installation complete.
INFO: Remember to restart Home Assistant before you configure it
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Diagnostics dump

The dump cant be done since the integration is not made

**Comment by tjorim** [comment]
Looks like you only downloaded HACS, have you tried to continue with the installation instructions? https://hacs.xyz/docs/use/download/download/#finalizing-steps

**Comment by wlambermont** [comment]
Yes thanks for the addition, I tried the logs but either they are at a different location then espected or they aren't there. (or atleast the translation from English to Dutch makes it hard to find. I checked the system logs, the logbooks at the side (balk?) and I also checked the logs in the addon option. There only the above can be seen. The rest doesn't even mention the HACS addon.
