### ISSUE TITLE
Update schedule configurable

### ISSUE THREAD

**Issue by emics** [hacs/integration#634]
Related to #53 

**Is your feature request related to a problem? Please describe.**
I use 4G broadband connection and HACS keep a lot of traffic of my 50GB sim card for update check

**Describe the solution you'd like**
The function for disable automatic update is important for people with similar scenarios

**Describe alternatives you've considered**
other solution is to define custom update interval, example every day or every three  days.

**Comment by ludeeus** [comment]
If you are on a limited connection you should not use hacs, hacs transfer a lot of data both during updates and installations.

You should look into alternative options to keep yourself updated, like octobox.

**Comment by emics** [comment]
I don't completely agree.
in the case of broadband connections with a lot of data traffic as in my case (50GB each month) it is convenient to use HACS to manage the installed packages, but the traffic generated by checking for updates is greater than the packages themselves.

**Comment by MZorzy** [comment]
or a button to check when we want.

is this the timer ?
https://github.com/custom-components/hacs/blob/310d968427696a58f31d276b7e2ceee03af7dd3c/custom_components/hacs/hacsbase/__init__.py#L166

**Comment by ludeeus** [comment]
That is one of them, the other one are a few lines down

**Comment by nikpait** [comment]
after upgrade from 0.16.3 version i see only TAB:
Installed, Integrations,Plugin, Settings

**Comment by chickenandpork** [comment]
I'm looking for a similar feature, but that's because I'm waiting and waiting and waiting for the update to finish so that I can do a thing.  The idea that HACS is unusable as a package manager while updating the metadata for each repos is a bit of a drag.  I have a ~200mbps uplink but it's been churning for ~20 minutes since last reboot.

Maybe a "no update within XX minutes of last update" config?

**Comment by ludeeus** [comment]
That is an issue and is not relevant to this FR @chickenandpork

**Comment by fortepc** [comment]
I would also like to have the ability to disable automatic updates. I have home assistant installed in a vehicle, and when my vehicle is home it connects to my wifi, but when I'm out I use a 4G dataplan. I don't care how much data it uses at home, but it would be nice to be able to have a bit more control on what data I use while connected to 4G
