### ISSUE TITLE
🚨 This repository is moving!

### ISSUE THREAD

**Issue by ludeeus** [hacs/integration#724]
This repository is moving to https://github.com/hacs, and during that move, it will also be renamed to `integration`.

Before that move is complete, and starting with version 0.15.11 of HACS you will start to see these messages during the startup:

```
ERROR (MainThread) [hacs] Validation for hacs/integration failed with GitHub returned 404 for https://api.github.com/repos/hacs/integration.
WARNING (MainThread) [hacs] custom-components/hacs is not in common.installed
```

This can safely be ignored.

I will do what I can to make sure this will not break much, but to be honest moving a repository is not a good idea in the first place, and I have never done it for something that is so tied to the repository like HACS is (everything it does are tied to repositories.)

The first attempt at moving it will probably happen this Thursday/Friday, I will update this issue and the forum and probably discord before the move.

Worst case, if it breaks everything, I can probably just move it back, until I figure something else out.

If you can, you should update to 0.15.11 before the move starts.

**Comment by ludeeus** [comment]
If everything goes as planned 0.15.11 will be released in the new repository which will remove all references to the ole repository, which will have a planed release date on Sunday/Saturday.

**Comment by jayscovill** [comment]
I'm seeing these errors but I'm also seeing the behaviour where HACS is forgetting my installed customizations every time I restart HASSIO.  I have to go back and add them but restarts forget them.  Is that a symptom of this migration as well?

**Comment by ludeeus** [comment]
No @jayscovill <https://github.com/custom-components/hacs/issues/729>

**Comment by jayscovill** [comment]
Ok thanks. I upgraded to .15.11 (was on .15.10) and it seems to have sorted itself out now.

**Comment by aidbish** [comment]
@ludeeus 
Just updated to 15.11 and initiall got the 404 validation error, but also a few of these
2019-10-23 08:17:24 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139624413345552] Received invalid command: hacs/config


2019-10-23 08:17:24 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139624413345552] Received invalid command: hacs/repositories

I presume this is all part of preparing for the move?

**Comment by ludeeus** [comment]
It's not, no issue _before_ the move will be, after however... _who knows_ ;)

**Comment by niemyjski** [comment]
It should create a repository alias so anything cloning this url will update. That's been the experience for the repositories I've moved or renamed.

**Comment by ludeeus** [comment]
Same here and I have done multiple tests of that the past couple of days.

**Comment by ludeeus** [comment]
I will now 10AM (UTC+2) attempt to move the HACS repository.

**Comment by ludeeus** [comment]
After about 40 min of testing various things, I think this move was a success.

There are 2 minor graphical issues that will be handled in the next update, both will appear the next time you restart HA.

- You will see 2 HACS repositories in the overview/installed tab.
- You will see `hacs/integration` as a custom repository under the settings tab.
