### ISSUE TITLE
Only a single configuration of HACS is allowed.

### ISSUE THREAD

**Issue by Reconos87** [hacs/integration#735]
Description: I wanted to re-install hacs, following the new guide, so i uninstalled HACS using the guide. Now everytime i try to install Hacs via integration i get the following message: Only a single configuration of HACS is allowed.

## Version of HACS
0.100.3

## Describe the bug
Unaware whether it's a bug or just my own stupidity. But can't reinstall HACS

## Debug log
Can't find anything concerning Hacs in the logs

**Comment by dasb00ter** [comment]
I had this and had to remove the settings from config.yaml which is for the token than I think im ok as the new config dialog under integrations has come up instead of that warning. I guess that it had been some time since I installed hacs so forgot if I had that entry.
