### ISSUE TITLE
emigrating from legacy install to integration install

### ISSUE THREAD

**Issue by dasb00ter** [hacs/integration#737]
Home Assistant
0.100.3
Hacs 0.15.11

I've deleted my config.yaml configuration for HASS and I am able to proceed with the integration installation however I do not see the icons to enable experimental features in the upper right. All I see is the garbage can. Restarted HASS with no resolution. There was some core entries when I was looking around for HACS entries in visual studio do I need to remove something to start with a clean slate in order to update latest

Thanx for your time

**Comment by ludeeus** [comment]
1 click the trashcan
2. Remove from YAML configuration
3. Restart HA
4. Restart HA (yes, this needs to be done twice.)
5. Make sure that you actually restarted HA, if you do it from the UI it will **not** restart if you have a config issue.
6: Enable the HACS integration.

**Comment by dasb00ter** [comment]
> 1 click the trashcan
> 2. Remove from YAML configuration
> 3. Restart HA
> 4. Restart HA (yes, this needs to be done twice.)
> 5. Make sure that you actually restarted HA, if you do it from the UI it will **not** restart if you have a config issue.
> 6: Enable the HACS integration.

Thanks after multiple restarts I do have those icons and was able to get the icons without using the garbage can. If i have further difficulties/oddities I will try using it then reinstall but for now it seems to work. Seems like your trying to make the HACS install less um HACKY which is good either way I just follow along the leaders. Thanks for all your help and when you helped back when I was using HASSBIAN
