### ISSUE TITLE
Integration Installation Error - Personal Access Token Not Correct

### ISSUE THREAD

**Issue by THATDONFC** [hacs/integration#745]
## Version of HACS

I have downloaded and attempted to install the latest version of HACS 0.16.1

## Describe the bug
I was able to successfully install HACS. Before the integration could finish updating (process that runs after integration is installed) the integration disappeared from my integrations list. I uninstalled the config and tried to reinstall. When I pasted my access token, I was given an error "Personal Access Token is not correct." 

I deleted the HACS folder, created a new access token and tried to install the integration again. I downloaded the latest version from github and put the HACS folder in the config/custom_components/ folder. I tried to install the integration again with the new access token and was given the same error "Personal Access Token is not correct."

## Debug log

```text

No logs

```

**Comment by betz** [comment]
I can confirm this issue.
have the following log:

> Error handling request
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
>     messages, upgraded, tail = self._request_parser.feed_data(data)
>   File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
> aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
