### ISSUE TITLE
Update all button

### ISSUE THREAD

**Issue by ljmerza** [hacs/integration#747]
Sometimes there are 5+ things that need to be updated and I have to go into each one and cliklcu pdate. Can we have an updater all button that just updates all items that need updating? Thanks

**Comment by ludeeus** [comment]
You mean like the one under the settings tab?

**Comment by ljmerza** [comment]
doh sorry

**Comment by quthla** [comment]
Unfortunately that button doesn't do anything for me. There's also no log message.

Never used it before and I'd think it'd better be placed in the installed tab.

Is it possible that the button does not work yet in experimental ui?
