### ISSUE TITLE
Not all repos are shown

### ISSUE THREAD

**Issue by andriej** [hacs/integration#754]
## Version of HACS 
0.16.1

## Describe the bug
Not all repos are shown even if they are already added in HACS database.
Example: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Rozkladzik/ - when I try to add it manually, HACS says it's already in the database.
No way to find the component in HACS tho.

## Debug log
n/a

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/68045536-03e63780-fcda-11e9-9895-7b57346551a7.png)
It's there.

**Comment by ludeeus** [comment]
If you have a country filter active, and that is not "PL" you will not see it.

**Comment by andriej** [comment]
I have "ALL":
![image](https://user-images.githubusercontent.com/6303489/68045727-8111ac80-fcda-11e9-915a-a1fd4d5e83d9.png)

**Comment by andriej** [comment]
![image](https://user-images.githubusercontent.com/6303489/68045760-9555a980-fcda-11e9-902b-658096ba505f.png)

**Comment by ludeeus** [comment]
Is it listed as hidden under settings?

**Comment by andriej** [comment]
Where exactly I can find it?
![image](https://user-images.githubusercontent.com/6303489/68045903-e796ca80-fcda-11e9-8a15-461927128a05.png)

**Comment by ludeeus** [comment]
Will only show if it was there.
Enable this and see if that helps:
![image](https://user-images.githubusercontent.com/15093472/68045947-01381200-fcdb-11e9-9fbf-e3e27b9ee6ff.png)

**Comment by andriej** [comment]
I've just also confirmed it with author of addon:
`Something is strange there, because only those with specified regions do not work.`

**Comment by andriej** [comment]
I can see it after enabling experimental, but whole HACS is different too. 
It has to be some bug in 0.16.1 then

**Comment by ludeeus** [comment]
Bug in the old UI, that will not be fixed.
The experimental will replace the old UI in 0.17.0

**Comment by andriej** [comment]
Turning it back off made it disappear again

**Comment by andriej** [comment]
Will be fixed I guess.
