### ISSUE TITLE
Allow plugins to have cacheable dependencies

### ISSUE THREAD

**Issue by gadgetchnnel** [hacs/integration#761]
**Is your feature request related to a problem? Please describe.**
I have been converting a plugin which has remote dependencies (ES6 modules from unpkg.com) to make those dependencies local to avoid issues if the remote source is unavailable. However, since HACS disables caching for all files served from the /community endpoint (by setting Cache-Control max-age to 0), these dependencies are fetched on every load.

**Describe the solution you'd like**
I would like a way to have files in the folder for the plugin which are cached for a period of time. This could possibly be done by allowing a subfolder named **dependencies** or similar under the root of the repository or the **dist** folder. Files in that folder would be served with a Cache-Control max-age of a period of time (such as 1 day).
Although this may cause issues if a dependency changes, this could be handled by versioning in the filename.

**Describe alternatives you've considered**

**Additional context**

**Comment by ludeeus** [comment]
If you don't want cache use the `/local` endpoint.

You can also look at https://github.com/custom-cards/boilerplate-card, with that structure you will provide your users with a single file.

The HACS frontend used that repo as a starting point.
