### ISSUE TITLE
HACS was shipped with hassio?

### ISSUE THREAD

**Issue by rradar** [hacs/integration#764]
## Version of HACS

unkown

## Describe the bug

I have hass.io running and didn't install hacs. Today I was checking my **home assistant logs** and found this:

## Debug log

```text
Log Details (WARNING)

You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
```

Did some google kungfu and found out what hacs is. Reading a little the documentation and checked my custom_components folder therefor:

![image](https://user-images.githubusercontent.com/34582688/68383729-1931ea80-014e-11ea-8fba-cc1a85a3115d.png)

Looks like the filze in place since the end of august. Last restart of my hassio was on the 31th of October I guess.

Next step for sure was to check if I could add it in the integrations panel. It wasn't auto discovered but choosing to add HACS and waiting a little this window came up:

![image](https://user-images.githubusercontent.com/34582688/68383546-c5270600-014d-11ea-9360-8310722b420c.png)

I stopped here to don't include old software in my setup.

But I really wondering where this came from because I didn't add it :thinking:

**Comment by ludeeus** [comment]
Someone with access to your filesystem did add it, if you do not want it, remove it.

And to answer your title "HACS was shipped with hassio?"
_if_ you followed official installation guides for hassio, no
_if_ you did not follow the official instructions there is no telling what you might have on your system.

**Comment by rradar** [comment]
Okay, this was useful information @ludeeus. Thank's for it.

So best for me would be to delete the hacs folder I have on my hassio system reboot two times and it should be cleaned.

To add the newest version I would just follow the guide then: https://hacs.xyz/docs/installation/prerequisites
