### ISSUE TITLE
Following the HACS Installation Guide, I can not add HACS as an integration into Hassio

### ISSUE THREAD

**Issue by Monty24m** [hacs/integration#766]
I was following the HACS installation guide successfully. But on the configuration step I was not able to select the HACS Integration in the List of integrations. 

I'm using HassOS 2.12 (production)
I have created the **custom_components/** inside of the config folder

my configuration file looks like this:
```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
```
and my config folder looks like this 
```
automations.yaml      groups.yaml           scripts.yaml
configuration.yaml    home-assistant.log    secrets.yaml
custom_components     home-assistant_v2.db  tts
deps                  known_devices.yaml
```
inside of custom_components i have created the folder named hacs
```
core-ssh:/config/custom_components# ls
hacs
```

and the folder is filled with all the files downloaded:
```
core-ssh:/config/custom_components/hacs# ls
__init__.py              frontend                 sensor.py
api.py                   hacsbase                 services.yaml
config_flow.py           handler                  setup.py
configuration_schema.py  helpers                  store.py
const.py                 http.py                  strings.json
constrains.py            manifest.json            ws_api_handlers.py
deprecated.py            repositories
core-ssh:/config/custom_components/hacs#
```
After rebooting the system and also clearing the browser cache, I'm not able to find the component fo HACS in the integrations, following step 4 https://hacs.netlify.com/docs/configuration/basic. Any idea about this?

**Comment by ludeeus** [comment]
Run `ls -la` _inside_ the `hacs` directory

**Comment by Monty24m** [comment]
drwxr-xr-x    7 root     root          4096 Nov  9 20:44 .
drwxr-xr-x    3 root     root          4096 Nov  9 20:42 ..
-rwxr--r--    1 root     root          6671 Nov  2 15:07 __init__.py
-rwxr--r--    1 root     root         13845 Nov  2 15:07 api.py
-rwxr--r--    1 root     root          3539 Nov  2 15:07 config_flow.py
-rwxr--r--    1 root     root          1703 Nov  2 15:07 configuration_schema.py
-rwxr--r--    1 root     root          4021 Nov  2 15:08 const.py
-rwxr--r--    1 root     root          1335 Nov  2 15:07 constrains.py
-rwxr--r--    1 root     root          2168 Nov  2 15:07 deprecated.py
drwxr-xr-x    5 root     root          4096 Nov  2 15:07 frontend
drwxr-xr-x    2 root     root          4096 Nov  2 15:07 hacsbase
drwxr-xr-x    2 root     root          4096 Nov  2 15:07 handler
drwxr-xr-x    2 root     root          4096 Nov  2 15:07 helpers
-rwxr--r--    1 root     root          8456 Nov  2 15:07 http.py
-rwxr--r--    1 root     root           496 Nov  2 15:07 manifest.json
drwxr-xr-x    2 root     root          4096 Nov  2 15:07 repositories
-rwxr--r--    1 root     root          2382 Nov  2 15:07 sensor.py
-rwxr--r--    1 root     root           489 Nov  2 15:07 services.yaml
-rwxr--r--    1 root     root          3290 Nov  2 15:07 setup.py
-rwxr--r--    1 root     root           699 Nov  2 15:07 store.py
-rwxr--r--    1 root     root          4567 Nov  2 15:07 strings.json
-rwxr--r--    1 root     root         11474 Nov  2 15:07 ws_api_handlers.py

**Comment by ludeeus** [comment]
As I suspected, you are missing the `.translations` directory.
Most of OS's hides that

**Comment by Monty24m** [comment]
Great thanks ... Perfect:-)
