### ISSUE TITLE
ERROR (MainThread) [hacs] Tried to serve up <file> but it does not exist

### ISSUE THREAD

**Issue by mf-social** [hacs/integration#769]
## Version of HACS

16.3

## Describe the bug

Error message in the logs - no actual observable error AFAIK - ie file is in the correct place and plugin is working in the ui.  Error message is from the HACS integration.

## Debug log

2019-11-10 16:49:56 ERROR (MainThread) [hacs] Tried to serve up '/config/www/community/lovelace-card-templater/card-templater.js' but it does not exist

**Comment by ludeeus** [comment]
Show me the contents of that directory

**Comment by mf-social** [comment]
HACS config is all in the UI

Lovelace config (in case required) = 

```
resources:
  - type: js
    url: /community_plugin/lovelace-card-templater/card-templater.js
```

Contents of the www/community/ directory:

www/community/
|
|--/lovelace-card-templater/
|..........|--lovelace-card-templater.js
|..........|--lovelace-card-templater.js.gz
|
|--/lovelace-card-tools/
|..........|--card-tools.js
|..........|--card-tools.js.gz
|..........|--webpack.config.js
|..........|--webpack.config.js.gz
|
|--/vertical-stack-in-card/
|..........|--vertical-stack-in-card.js
|..........|--vertical-stack-in-card.js.gz

**Comment by mf-social** [comment]
...and I've just noticed the error message is referencing the filename to not have the 'lovelace' word on the start, but the actual files do.

**Comment by ludeeus** [comment]
And there is your issue.
You need to update your lovelace configuration to use the file that actually exist.
