### ISSUE TITLE
Can't enable theme tracking after intial config?

### ISSUE THREAD

**Issue by TychoWerner** [hacs/integration#774]
**Is your feature request related to a problem? Please describe.**
When the intial config has been done and you decide after the fact that you do want theme tracking it's nowhere a option to still enable it.

**Describe the solution you'd like**
A option to enable tracking of themes and python scripts etc.

**Describe alternatives you've considered**
"Reinstalling" the integration

**Additional context**
none

**Comment by ludeeus** [comment]
Correct, but let me ask you this.
Can you change the initial configuration of _any_ integration in Home Assistant?

**Comment by tcarlsen** [comment]
@ludeeus I came across this issue because I wanted to add theme tracking as well. I get that you will need to remove it at re enable it. But I stand with a question that aint answered in the Wiki. will HACS refind all the plugins it has installed after a re enable? or do I have to reinstall all the plugins etc?

**Comment by ludeeus** [comment]
https://hacs.xyz/docs/basic/existing_elements

**Comment by tcarlsen** [comment]
@ludeeus so do I med to uninstall Them sæl first? Or do a re install of the plugins just re enable or overwrite the “old” files?

**Comment by ludeeus** [comment]
Reinstall is fine

**Comment by tcarlsen** [comment]
@ludeeus FYI i just removed the integration and added it again.  I did find all the all ready installed plugins that the "old" HACS hand installed

**Comment by ludeeus** [comment]
That info is not stored in the integration, that is stored in `.storage/hacs.repositories`
