### ISSUE TITLE
Integration issue

### ISSUE THREAD

**Issue by giangi007** [hacs/integration#776]
## Version of HACS

0.16.3
HA 0.100.3

## Describe the bug
HACS doesn't works correctly so I uninstall it following the procedure, after that I reinstall but without lucky. So I decide to delete HACS "account" in github and re-create a new one.
After I try to installa HACS, restart HA, but after the reboot in Integration tab I have already HACS integratio (with non correct token). In community Tab i see blue screen with Overwiev tab, store tab and setting and stop

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
you need to remove, and reinstall if you change the token.

https://hacs.xyz/docs/installation/remove
https://hacs.xyz/docs/installation/prerequisites

**NB!: The restarts are _important_.**
