### ISSUE TITLE
[Errno 13] Permission denied: 'sensor.py'

### ISSUE THREAD

**Issue by ekendra-nz** [hacs/integration#790]
When upgrading from 0.16.1 to 0.17.1 via web interface. I get:

`[Errno 13] Permission denied: 'sensor.py'`

**Comment by ludeeus** [comment]
Please read the release notes one more time.

**Comment by ekendra-nz** [comment]
Same error when upgrading from 0.16.1 to 0.16.2 or 0.16.3

 .... until I changed file permissions. 

Then it worked fine. Nice new interface by the way.
