### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by andriej** [hacs/integration#792]
## Version of HACS 

latest 0.17.2

## Describe the bug
Error thrown in log althought HACS seems to work

## Debug log

```text
019-11-18 22:50:47 ERROR (MainThread) [frontend.js.latest.201910251] https://DOMAIN/hacs_frontend/main.js?v=0.17.3:1:1 Uncaught SyntaxError: Identifier 'e' has already been declared
```

**Comment by ludeeus** [comment]
That can happen due to cache, I've seen similar in the devely-tools part of HA after upgrade

**Comment by friendodevil** [comment]
@ludeeus How do you resolve caching issue? clearing browser cache did not fix it
