### ISSUE TITLE
Upgrade to 0.17.3 version

### ISSUE THREAD

**Issue by nikpait** [hacs/integration#795]
after upgrade from 0.16.3 version i see only TAB:
Installed, Integrations,Plugin, Settings

**Comment by ludeeus** [comment]
And?

**Comment by ianfretwell** [comment]
...just guessing here as I'm in the same position...

all the example screenshots all seem to also have 'APPDAEMON APPS', 'PYTHON SCRIPTS' & 'THEMES'...

Not that this is affecting me in the slightest but...should they be visible?

**Comment by ludeeus** [comment]
Only if enabled

**Comment by ianfretwell** [comment]
Which is fine, but where would I actually do that though - I've looked everywhere I can think of.

**Comment by ludeeus** [comment]
<https://hacs.xyz/docs/configuration/basic>
<https://hacs.xyz/docs/configuration/legacy>

**Comment by ianfretwell** [comment]
Right I think this is beginning to explain it then, I have my token configured as the only HACS entry in configuration.yaml - and when I look at the integration it looks nothing like what's shown in the docs - it's far simpler (still has the 'enable experimental features' option for example.

So do I have to remove the integration, remove the token from configuration.yaml and then re-add the configuration (presumably losing everything I have already set up) ?

**Comment by ludeeus** [comment]
Correct, currently Home Assistant does not have the ability to change the configuration of an integration.
You will not lose anything, but you do need to restart after adding it again.

**Comment by ianfretwell** [comment]
Confirmed, thats all working/looking as it should now - many thanks.

Hopefully that's what the OP's actual problem was too!
