### ISSUE TITLE
Initial loading screen background not matching theme 

### ISSUE THREAD

**Issue by SublimePotato** [hacs/integration#801]
## Version of HACS
![image](https://user-images.githubusercontent.com/4058166/69227579-5355b000-0b82-11ea-8e40-fdf65d1474c9.png)

## Describe the bug
The loading screen is always white, no matter what the theme defines. 

![image](https://user-images.githubusercontent.com/4058166/69227299-e6421a80-0b81-11ea-9347-7b9b74a67498.png)

## Possible Solution
I could not exactly find the location, where the white color is defined, but I could overwrite it by adding some styles to `<hacs-frontend>`

![image](https://user-images.githubusercontent.com/4058166/69229450-b72da800-0b85-11ea-93b0-3d5dbb6377c4.png)
![image](https://user-images.githubusercontent.com/4058166/69229487-c6145a80-0b85-11ea-8458-fadc4b0d5d12.png)

**Comment by ludeeus** [comment]
Neat

**Comment by ludeeus** [comment]
This needs to be done in the HA repo.
You get the same when loading _any_ custom/iframe panels.
