### ISSUE TITLE
State icons for colour-blinded

### ISSUE THREAD

**Issue by aluisperezh** [hacs/integration#803]
Last revisions have changed the colors of the icons in the installed, not updated and available elements, and for me (color-blind) it's really difficult to differenitate the  state of the element. Could it be possible to use different shapes for each state? I understand that colours are easier for normal people, but it's really difficult for us (or at least for me, there are a lot of different color-blindness)

**Comment by ludeeus** [comment]
The colors have not changed there was a bug in the 0.17.x that is fixed in 0.17.4, and they are now again themeable to suit your needs.
https://hacs.xyz/docs/basic/theming

Adding different shapes would be difficult to implement, and would be impossible to make everyone happy.
