### ISSUE TITLE
0.16.3 not in install candidate list

### ISSUE THREAD

**Issue by dlashua** [hacs/integration#813]
## Version of HACS
0.16.1

## Describe the bug
Changelog says to upgrade to 0.16.3 before moving to 0.17.0 or newer. However, 0.16.3 is not a version option in the dropdown list. 0.17.0 is the oldest version available.

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
https://hacs.xyz/docs/configuration/legacy#options-map
