### ISSUE TITLE
How to upgrade from 0.11.1

### ISSUE THREAD

**Issue by IanAdd** [hacs/integration#816]
## Version of HACS

0.11.1

## Describe the bug

Click on HACS tile with a view to doing the upgrade gives:
500 Internal Server Error
Server got itself in trouble

I recall some request that we got to a certain version before you did a mjor update but I forgot about this old system of mine!

## Debug log

Do you need me to enable and send logs or is the resolution well known?

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
Most likely (timewise) you are better off just doing a reinstall with the newest version, and reinstalling the stuff you have inside HACS.

**Comment by bohtho** [comment]
Sorry, but if I was too quick and stupid and updated from 0.16 only to first get the 500 error and now broken UI (can’t find buttons). How do I reinstall ?

**Comment by ludeeus** [comment]
Just restart HA

**Comment by bohtho** [comment]
Still broken UI. I may have messed up the upgrade totally.

**Comment by ludeeus** [comment]
Download the files again (upgrade and install are identical)

**Comment by boralyl** [comment]
@bohtho I had a similar issue when upgrading from 0.16.3 to 0.17.4.  First I got a 500 error, even after a restart.  I decided to wipe the hacs directory and start over but the tabs and buttons were not visible and some text was missing when browsing repositories.

The solution for me was to enter the /config/.storage directory and delete any `hacs.*` files, then restart.  Hopefully that helps!
