### ISSUE TITLE
Where does HACS store the list of installed integrations/plugins

### ISSUE THREAD

**Issue by carlos-sarmiento** [hacs/integration#821]
## Version of HACS

N/A

## Describe the bug
I currently use git to store my  HA configuration. Right now my repo includes the `custom_component` folder, but I'd like to be able to exclude it. What I'm trying to figure out is where HACS store the list of installed plugins so I can make sure that I keep a copy of that inside my repo. 

## Debug log
N/A

**Comment by ludeeus** [comment]
All HACS related data files are in `.storage`
