### ISSUE TITLE
HACS does not appear in HASS as documented

### ISSUE THREAD

**Issue by gfischershaw** [hacs/integration#824]
HassOS 3.5
Supervisor version 192
HACS 0.17.4
H/W rpi 4b
Followed HACS installation instructions step-by-step, copying hacs directory to the rpi directory specified. Restarted HASS and cleared browser cache. No HACS in integration dropdown. Restarted rpi, still no HACS. Please verify that HACS actually functions on the latest hassio.

**Comment by gfischershaw** [comment]
Adding requested details. I believe that the version information above is complete, but the actual issue is slightly different:
HACS is in the list, but has no label.
Steps:
Clean install of the above version of HassOS.
Install Samba.
Follow HACS installation steps using above version of HACS.
Note that the dialogs are missing various bits of text as well. Log attached as requested, along with screen captures of the various dialog windows.

[hass.log](https://github.com/hacs/integration/files/3898040/hass.log)
![Integrations List](https://user-images.githubusercontent.com/4001348/69745312-d634b880-10f6-11ea-8138-d54f46f69cd3.PNG)
![HACS Config Dialog](https://user-images.githubusercontent.com/4001348/69745321-d9c83f80-10f6-11ea-9ae6-2a53e01dff8a.PNG)
![Installed Integrations](https://user-images.githubusercontent.com/4001348/69745329-dfbe2080-10f6-11ea-85bd-babca0fa9dbe.PNG)
![HACS Options Dialog](https://user-images.githubusercontent.com/4001348/69745334-e0ef4d80-10f6-11ea-9bcc-be5a45560d90.PNG)

**Comment by gfischershaw** [comment]
And then there is nothing in the community store:
![Community Store](https://user-images.githubusercontent.com/4001348/69745717-a0440400-10f7-11ea-9737-9050cd28c8d7.PNG)

**Comment by ludeeus** [comment]
You are missing the `.translations` folder

**Comment by gfischershaw** [comment]
Must have been a Windows thing and did not copy to the destination.
