### ISSUE TITLE
Adding custom component blocked because it need review ??

### ISSUE THREAD

**Issue by claudegel** [hacs/integration#834]
Just created a pull request to add a new custom component claudegel/sinope-130. Check pass ok but it is stalled with comment that it need to be reviewed ? How long it take and is it normal procedure ?

**Comment by ludeeus** [comment]
Hi,

The data branch is no longer in use, and its content has been moved to a separate repository.
The documentation has been updated to reflect this https://hacs.xyz/docs/publish/include

The reason it still files here is to not break old installations.

As for the timeframe:

When I get to it, currently this project is maintained by a single person, I do have other things I do with my time as well.
