### ISSUE TITLE
Setup failed for hacs: Integration not found.

### ISSUE THREAD

**Issue by scubieman** [hacs/integration#840]
I setup HACS long time ago and worked great! Then I did a upgrade and it messed up. I tried to remove it to reinstall but it will not remove itself. Everytime I restart I get the error 

> Setup failed for hacs: Integration not found.

**Comment by ludeeus** [comment]
removing is tricky, folow this https://hacs.xyz/docs/installation/remove

**Comment by scubieman** [comment]
Tried all the steps. I even tried searching for HACS and there is nothing. I also viewed hidden files. Also config.yaml shows nothing
