### ISSUE TITLE
Frontend missing from all releases 0.17.0 forward

### ISSUE THREAD

**Issue by ketudb** [hacs/integration#841]
Installing the latest (0.17.4) has caused issues with the front-end not loading correctly, so I tried installing some older versions (back to 0.17.0) with the same issue. It doesn't render correctly in the integrations list, and if it does show up in the sidebar, the pages are missing significant components. 

Having dug through the tree a bit, it looks as though there is no `frontend` folder at `custom_components/hacs/` in these releases. Installing 0.16.3, in which this folder does exist, works as I would expect it to.

**Comment by ludeeus** [comment]
You are missing the .translations folder

**Comment by gavinhelyar** [comment]
I had the same issue, I copied the frontend and .translations folders from the 0.16.3 release hacs.zip and restarted Home Assistant all working fine now

**Comment by MadmanMonty** [comment]
**Versions**
Issue persists in the hacs.zip for 0.18.0. 
0.17.0 >= 0.18.0

**Issue:** 
Installing hacs from fresh results in the 'Integration' UI not loading.

**Resolution:** 
Coping over the frontend folder from 0.16.3 into the hacs folder and restarting solves the issue.
