### ISSUE TITLE
Impossible to read descriptions in dark themes

### ISSUE THREAD

**Issue by VDRainer** [hacs/integration#844]
## Version of HACS
0.18.0

## Describe the bug
In dark themes the descriptions are not readable.
For example slate:
![Auswahl_224](https://user-images.githubusercontent.com/26381449/70378393-3100b800-1920-11ea-810f-4147fccbf39b.png)
Dark orange is a little better:
![Auswahl_225](https://user-images.githubusercontent.com/26381449/70378405-58f01b80-1920-11ea-82d7-9a59c29cc34f.png)

## Debug log

```text

Add your logs here.

```

**Comment by rpitera** [comment]
Yep.  Same here.  Also in the description for HACS itself, the animated gif refers to https://hacs.xyz/img/hacsdemo.gif which appears to have been renamed to https://hacs.xyz/img/demo.gif

**Comment by ludeeus** [comment]
Has already been fixed, will be in next release
