### ISSUE TITLE
HACS gif in description is still named incorrectly

### ISSUE THREAD

**Issue by rpitera** [hacs/integration#850]
Just a heads up; in the description details, the animated GIF for HACS is still pointing to 

https://hacs.xyz/img/hacsdemo.gif

instead of

https://hacs.xyz/img/demo.gif

I mentioned this in #844 but I guess you missed it.  Would probably be easier to copy demo.gif over to hacsdemo.gif rather than making another release for this small issue.

**Comment by ludeeus** [comment]
Was fixed a few hours ago
