### ISSUE TITLE
Not finding HACS under Integrations in Homeassistant

### ISSUE THREAD

**Issue by Ogbergo** [hacs/integration#851]
## Version of HACS
0.18.1

## Describe the bug
I'm kind of a newbie on Home Assistant and am having some problems in adding HACS (with the goal to add an Arlo integration). According to what I can see HACS is the best way to do this. But....

I followed the instructions on the webpage https://hacs.xyz/docs/installation/manual and placed the HACS-folder in the following path \\HASSIO\config\custom_components\hacs, see image below. 

![image](https://user-images.githubusercontent.com/57356602/70472034-b4f8a280-1ace-11ea-9754-8c46c5564c8c.png)

Next I rebooted HA through SSH and continued according to instructions, ie I went to Integrations and cleared the cache, before I clicked the "+" to add another Integrations. There is however no HACS listed, see image below:

![image](https://user-images.githubusercontent.com/57356602/70471883-58958300-1ace-11ea-859d-d4aa5db419f5.png)

I can therefore not add HACS. 

According to another issue, someone hade made changes to HACS files. Is this necessary? Or what seems to be the problem according to the log? Please help me!! :)

Have also found other issues of the same type, but have tried all the posted solutions, but can't seem to fix the error....

## Debug log

2019-12-09 22:18:17 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.hacs. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 346, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/hacs/__init__.py", line 8, in <module>
    from aiogithubapi import AIOGitHub
ModuleNotFoundError: No module named 'aiogithubapi'

```

**Comment by Ogbergo** [comment]
Apparently my copy process is missing some files from GitHub. However when I look into the folder of version Master or 18.1 the files aren't there (like for example Translations or file api.py). 

![image](https://user-images.githubusercontent.com/57356602/70480525-3dcc0a00-1ae0-11ea-9c10-eb88138f6f0e.png).

However when I select "tag 16.3" or earlier they have the folder ".translations" and file api.py. 

![image](https://user-images.githubusercontent.com/57356602/70480829-001bb100-1ae1-11ea-8e23-d66a9fe00051.png)


Can I select version? Or how can I download the rest of the files for version Master.

**Comment by ludeeus** [comment]
Don't use master
Use the zip file from the release as stated in the documentation

**Comment by Ogbergo** [comment]
I have tried everything.. First I just downloaded and saved the zipfile to my desktop and extracted it by rightclicking. The folder Hacs was then moved to custom_components. That didn't work since not all files are downloaded..

Now I just clicked on the zipfile on this webpage:

![image](https://user-images.githubusercontent.com/57356602/70562988-b3da7a80-1b8d-11ea-9e7c-efcb7f9b7a38.png)

That downloads the zipfile to my computer. If I click the zipfile it shows all the files on this picture:

![image](https://user-images.githubusercontent.com/57356602/70563156-06b43200-1b8e-11ea-9f33-d4c15f852c93.png)

I just copy the files directly from there to my hacs folder in HA, which in this case includes the previously missing folder Translations.

According to instructions, I then should reboot HA (which I've done in Putty) and after that go into Integrations, clear cache, and go on the "+" to add integration and magically HACS should appear. However... no... it doesnt'...

Am I still missing files? Or what could otherwise be the problem?

If I enter the token and check configuration I still get the error from the log above.

**Comment by smith-scot** [comment]
I am having exactly the same issue

**Comment by pilotak** [comment]
what helped was to install 0.18.0 version and on integration page press `ctrl+f5` to reload the page without cache in browser

**Comment by smith-scot** [comment]
Fat finger mistake I created a folder named custom_component rather than custom_components, I also downloaded version 0.18.0 and deleted 0.18.1, but I feel sure the folder name was the problem

**Comment by Ogbergo** [comment]
Still not working. I tried with version 0.18.0 aswell and by pressing Ctrl+F5 after reboot, but no difference. Getting really frustrated.

**Comment by robinviking** [comment]
So I had the same problem as Ogbergo. What did it for me was this:

When I downloaded hacs, I press "Source Code (zip)". That didn't work. 
When I pressed hacs.zip and extracted that into custom componets, it worked! 

![hacs](https://user-images.githubusercontent.com/42220326/70701714-20a85e80-1ccd-11ea-851a-1475ccec00d0.PNG)

**Comment by pilotak** [comment]
@Ogbergo try it again, you did something wrong. Delete custom_components folder restart HA, download hacs.zip unzip it, create custom_components and place hasc folder inside, restart HA go to integrations page press `ctrl+f5` click on "+" find HACS and configure

**Comment by Ogbergo** [comment]
I managed to resolve the issue. Probably it was resolved by updating HA to the latest version. Can't explain it in any other way..

**Comment by OriginalHotrodder** [comment]
> 
> 
> what helped was to install 0.18.0 version and on integration page press `ctrl+f5` to reload the page without cache in browser

Thank you for sharing the refresh after clearing the browser cache.  I was trying and trying and HACS was not showing up until I refreshed the page after clearing the browser cache, success!
