### ISSUE TITLE
Flag interesting items

### ISSUE THREAD

**Issue by Tom-ahawk** [hacs/integration#856]
HACS is filling up with items. Sometimes an item looks interesting for future usage. It would be helpful to be able to flag (star/hart/..?) items, and then be able to sort or have a tab with the flagged items.

This way in an easy manner to find items which was interesting.

**Comment by ludeeus** [comment]
Bookmark the page ;)

**Comment by Tom-ahawk** [comment]
@ludeeus  That’s an option. But would prefer to keep the bookmarks within HA.

**Comment by ludeeus** [comment]
I will not add duplicated features that have existed in browsers for 20 something years.
Sorry.
Both the core functionality of any browser or any number of other "remember this" clients will cover this.
