### ISSUE TITLE
Install button grey Out

### ISSUE THREAD

**Issue by pasqui7** [hacs/integration#859]
Hi guys ,
I installed HACS, but it is impossible to install any integration.

For example, When I try to search the Atag integration, I can see it, but the "Install" button it is grey out, and also for all of other integrations .

![Schermata 2019-12-15 alle 00 13 16](https://user-images.githubusercontent.com/37555547/70855778-c5df5480-1ed0-11ea-98e2-34b530ba7c3f.png)

Can you help me?

thanks

**Comment by wyefei** [comment]
Facing the same problem. Also having the same moving orange bar on top. Installed page looks like this with HACS indicating there's an update. However, the `update` button in HACS is also grayed out
![image](https://user-images.githubusercontent.com/1811081/70858548-cb30a500-1eb8-11ea-8493-17eeea1fdd61.png)

**Comment by pasqui7** [comment]
It’s works. 
You need to wait that the integrations, for the first time, will be loaded before first installation.

**Comment by ludeeus** [comment]
install/upgrade/uninstall is disabled while the background task is running to make sure you don't corrupt your data files.

**Comment by unikitty37** [comment]
Could the moving orange bar be replaced by a line of text indicating what is going on, maybe? Preferably containing something like "processed 25 items of 380" so we have some idea whether to wait or come back later?

(A tooltip on the disabled install button to indicate this is why it's been disabled might be useful, too — and certainly a bit easier to implement 🙂)
