### ISSUE TITLE
Integration Item for HACS is Blank 

### ISSUE THREAD

**Issue by jscott304** [hacs/integration#861]
Version of HACS 0.18.2 
HassOS 3.6

When you go to integrate hacs and search hacs the entry is blank.
When you click on the entry the form has no descriptions.

The first time i tried to install hacs I mistakenly did not include the subfolders but that has been corrected. I've restarted the HASS.io several times and removed and readded HACS but something is broken or stuck.

Currently HACS is not integrated

 Debug log
```text

2019-12-15 10:57:34 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

```
<img width="451" alt="Screen Shot 2019-12-15 at 11 23 53 AM" src="https://user-images.githubusercontent.com/24324316/70866989-7aa75f00-1f2d-11ea-8ff0-be9e2de589bf.png">
<img width="244" alt="Screen Shot 2019-12-15 at 11 24 14 AM" src="https://user-images.githubusercontent.com/24324316/70866987-7aa75f00-1f2d-11ea-870f-6b789cfd0f6e.png">

**Comment by ludeeus** [comment]
You are missing a folder

**Comment by jscott304** [comment]
I Have everything that is in hacs.zip moved over to config/custom_components/hacs/ including the 4 sub folders. What other folder would I need?

**Comment by ludeeus** [comment]
`.translations`

**Comment by jscott304** [comment]
.translations is not mentioned in the install documents

**Comment by ludeeus** [comment]
no
Not any of the subdirectories are

**Comment by jscott304** [comment]
I understand now, on mac files that start with a . are hidden. Can we get a note added into the installation instructions page to check for hidden files and then links on how to do that.
