### ISSUE TITLE
Upgrade all service

### ISSUE THREAD

**Issue by dwffls** [hacs/integration#865]
**Is your feature request related to a problem? Please describe.**
I have set up the mobile app to push a notification to my phone when an update becomes available. At the moment I have to open the app go to HACS and update the component manually. It would be great to have a button to update the component from within the notification.

**Describe the solution you'd like**
The solution would be to have a service like `hacs.upgrade_all ` _(just like the button in the frontend)_. This would make it possible to send an automation to update the component.

**Describe alternatives you've considered**
I've tried to write the code myself but was not able to do so.

**Additional context**
The function would then look something like this on an iPhone.

![IMG_3643](https://user-images.githubusercontent.com/1469494/70911403-232eef00-2012-11ea-9a4d-a489c97a796b.jpg)

**Comment by ludeeus** [comment]
Hi,
This will not be implemented.

Reason:
That feature would be too dangerous, folks would just be using it without regards to breaking changes.

Before HACS goes to 1.0.0 the button under Settings will probably be removed as well.
I have seen too many times users that are just blindly updating XX plugins/integrations without reading the releasenotes.

**Comment by dwffls** [comment]
Ok that's an understandable reason. 
Thanks for the quick response!

**Comment by ProLoser** [comment]
I wanted to do something similar but I understand the reservations. Perhaps the notification can provide a button that takes you straight to the relevant page to at least reduce the number of steps necessary
