### ISSUE TITLE
Unsupported operand types when upgrading integration

### ISSUE THREAD

**Issue by nmaggioni** [hacs/integration#867]
## Version of HACS

0.18.2

## Describe the bug

When upgrading an integration ([SmartIR](https://github.com/smartHomeHub/SmartIR) 1.7.3 to 1.7.4 is the only one I can try at the moment), the upgrade button in the UI loads forever until the page gets manually refreshed, and the logs show the following error.

Basing on [this change](https://github.com/hacs/integration/commit/5ca4169c419c48cca9934f6b070e3492088babad#diff-0b65b1e035d575dbb81ff0882fda3cbdR373) and [these docs](https://pymotw.com/3/tempfile/), shouldn't a `tempfile.TemporaryDirectory().name` call be more suited for this use? This quick fix seems to be working for me _(the upgrade succeeds, but I can't vouch for the integrity of the `Backup` function since `tempfile` seems to be cleaning up after itself)_.

## Debug log

```text
2019-12-17 16:09:19 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140325568997192] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/root/.homeassistant/custom_components/hacs/ws_api_handlers.py", line 193, in hacs_repository
    await repository.install()
  File "/root/.homeassistant/custom_components/hacs/repositories/repository.py", line 378, in install
    tempfile.TemporaryFile() + "/hacs_persistent_directory/",
TypeError: unsupported operand type(s) for +: '_io.BufferedRandom' and 'str'
```

## UI screenshot

![upgrade](https://user-images.githubusercontent.com/3594528/71008420-dd912580-20e8-11ea-84e4-c0766170ddf4.png)

**Comment by ludeeus** [comment]
How are you running Home Assistant?

**Comment by ludeeus** [comment]
I have pytests to validate backup/restore functions and those seems to still be valid with that change, if it helps you please provide a PR for it.

```bash
ash-5.0# cat custom_components/hacs/hacsbase/backup.py | grep TemporaryDirectory
BACKUP_PATH = tempfile.TemporaryDirectory().name + "/hacs_backup/"
bash-5.0# python3 -m pytest tests/hacsbase/test_backup.py 
===================================================================== test session starts ======================================================================
platform linux -- Python 3.7.5, pytest-5.3.2, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /workspaces/integration, inifile: pytest.ini
plugins: cov-2.8.1, asyncio-0.10.0
collected 3 items                                                                                                                                              

tests/hacsbase/test_backup.py::test_file PASSED                                                                                                          [ 33%]
tests/hacsbase/test_backup.py::test_directory PASSED                                                                                                     [ 66%]
tests/hacsbase/test_backup.py::test_muilti PASSED                                                                                                        [100%]

====================================================================== 3 passed in 0.40s =======================================================================
```

**Comment by nmaggioni** [comment]
I'm running HA without a venv on a dedicated LXC container. After having looked a bit more into the code I've PRed a better fix; for what I reckon, the [original commit](https://github.com/hacs/integration/commit/5ca4169c419c48cca9934f6b070e3492088babad) applied the right solution in `backup.py` bot not in `repository.py`.
