### ISSUE TITLE
Upgrade from 16.x to 18.x - inital HTTP 500 error resolved by reinstall but now UI is broken

### ISSUE THREAD

**Issue by timdonovanuk** [hacs/integration#869]
## Version of HACS

I was on 16.x and tried upgrading to 18.x

## Describe the bug

I tried upgrading through the UI and got HTTP 500 errors. I restarted HA multiple times as indicated by other logged issues here, but this did not fix the problem. I then removed the old version and replaced the /custom_components/hacs directory with the latest (at the time).

I restarted HA, but the HACS UI is broken (missing tabs, text etc):

![image](https://user-images.githubusercontent.com/8156439/71070195-2ccf6880-2172-11ea-925b-6f713670c3fc.png)

![image](https://user-images.githubusercontent.com/8156439/71070223-39ec5780-2172-11ea-838d-672a387b838f.png)

## Debug log

Cannot see anything relevant in the debug logs 

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
You  are  missing  the  `.translations`  folder

**Comment by timdonovanuk** [comment]
I'm not though:

```
pi@192.168.1.3:~$ ls -l /opt/homeassistant/custom_components/hacs/.translations
total 108
-rwxr--r-- 1 pi pi 5172 Dec 16 19:38 de.json
-rwxr--r-- 1 pi pi 5539 Dec 16 19:38 el.json
-rwxr--r-- 1 pi pi 4870 Dec 16 19:38 en.json
-rwxr--r-- 1 pi pi 3993 Dec 16 19:38 es.json
-rwxr--r-- 1 pi pi 5198 Dec 16 19:38 fr.json
-rwxr--r-- 1 pi pi 3885 Dec 16 19:38 it.json
-rwxr--r-- 1 pi pi 5053 Dec 16 19:38 nb.json
-rwxr--r-- 1 pi pi 4525 Dec 16 19:38 nl.json
-rwxr--r-- 1 pi pi 5074 Dec 16 19:38 nn.json
-rwxr--r-- 1 pi pi 5191 Dec 16 19:38 pl.json
-rwxr--r-- 1 pi pi 3975 Dec 16 19:38 pt-BR.json
-rwxr--r-- 1 pi pi 4065 Dec 16 19:38 ro.json
-rwxr--r-- 1 pi pi 6551 Dec 16 19:38 ru.json
-rwxr--r-- 1 pi pi 5117 Dec 16 19:38 sl.json
-rwxr--r-- 1 pi pi 3924 Dec 16 19:38 sv.json
-rwxr--r-- 1 pi pi 4835 Dec 16 19:38 zh-Hans.json
```

**Comment by ludeeus** [comment]
Restart HA and those should load.
If not just upgrade HACS, in 0.19.0 the UI translations moved to the forntend python package

**Comment by timdonovanuk** [comment]
Yep, just wiped the 18.x install and manually installed 19.0. All working. Thanks for a great project and support :) 👍
