### ISSUE TITLE
Version 'master' always shows upgrade available

### ISSUE THREAD

**Issue by tjorim** [hacs/integration#873]
**Is your feature request related to a problem? Please describe.**
There is an option to set the desired version to master. However, when doing this, HACS always shows that there's an update available.

**Describe the solution you'd like**
To track wether or not an integration got updated, HACS should look at commit hashes, just like it does when there are no releases (like most themes).

**Comment by ludeeus** [comment]
Sure, I think I have it, but I'm lazy so can test it before some of the repositories I have installed updates,

**Comment by ludeeus** [comment]
https://github.com/hacs/integration/commit/171c9014730b2324c1e8323348aa58c2a3b7c5c2
