### ISSUE TITLE
Unable to upgrade from 0.18.2 to 0.19.0

### ISSUE THREAD

**Issue by grewhit25** [hacs/integration#878]
## Version of HACS

0.19.0

## Describe the bug

I am not able to upgrade from version 0.18.2 to 0.19.0 for some reason.
The integration fail with "Setup failed for hacs: Unable to import component"

HACS currently installed via integration config_flow, however, I have being a hacs user since custom_updater and have followed all the upgrade stages and critical instructions. So hopefully, I haven't missed anything.

There is very little in the start up logs as detailed below.

I know I'am currently on home-Assistant Dev branch, but I have drop back to builds, 0.103.0, .1, .2 & .3 all with the same result.

I have dropped back to hacs 0.18.2 which installs successfully but I am not able to go forward.

```yml
Home Assistant 0.104.0.dev20191219
Frontend version: 20191204.1 - latest

System Health
arch      armv7l
dev       true
docker    true
hassio    false
os_name   Linux
python_version  3.7.5
timezone  Europe/London
version 0.104.0.dev20191219
virtualenv  false

```

## Debug log

```text

2019-12-19 17:34:39 INFO (SyncWorker_18) [homeassistant.util.package] Attempting install of backoff==1.10.0
2019-12-19 17:34:55 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of hacs_frontend==29
2019-12-19 17:35:11 ERROR (MainThread) [homeassistant.setup] Setup failed for hacs: Unable to import component

```

**Comment by ludeeus** [comment]
I only use dev builds, and it works for me.
It's not unusual for some installations needing 2-3 restarts for all packages to be installed.
If that does not help try to exec into the container and installing them manually.

**Comment by grewhit25** [comment]
@ludeeus Thank you for you rapid response.

When I exec into the container both backoff and hacs_frontend was already installed satisfactory. Not 100% certain what other commands you expected me to execute, I backed out.

So, I removed hacs completely using the removal procedure.
Then with a fresh copy of hacs.zip (0.19.0) downloaded to /config/custom_components/hacs and adding hacs from the integration page. I receive the following in ha's log.

```logs

2019-12-19 22:39:39 INFO (SyncWorker_11) [homeassistant.util.package] Attempting install of backoff==1.10.0
2019-12-19 22:39:57 INFO (SyncWorker_14) [homeassistant.util.package] Attempting install of hacs_frontend==29
2019-12-19 22:40:16 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading config flow for integration hacs: No module named 'hacs_frontend.version'

```

**Comment by ludeeus** [comment]
I don't know, it should just work.
I set it up probably 5-10 times a day and rarely see these kinds of issues.

Other than restarting multiple times I have no other tips.

**Comment by ccellist** [comment]
I've actually tried installing this from scratch (had to rebuild my hass installation) and the hacs.zip link is not downloadable. I get an "Access denied" XML. Is this expected? I'm following the installation instructions at https://hacs.xyz/docs/installation/manual.

**Comment by ludeeus** [comment]
no, you should open an issue with GitHub itself @ccellist

**Comment by grewhit25** [comment]
@ludeeus I've got it working, but I'm a bit confused.
Here are my findings.

When I exec into the container and tried installing hacs_frontend==29, I got:

Requirement already satisfied: hacs_frontend==29 in /usr/local/lib/python3.7/site-packages (29)

Note directory path: /usr/local/lib/python3.7/site-packages

When I tried adding hacs from the integration page, it's actually looking in:
directory path: /config/deps/lib/python3.7/site-packages/

The later path looks like this:
drwxr-xr-x  3 xxx xxx  4096 Dec 12 10:18 hacs_frontend
drwxr-xr-x  2 xxx xxx  4096 Dec 12 10:18 hacs_frontend-18.dist-info

When I copy accross:
/usr/local/lib/python3.7/site-packages/hacs_frontend to /config/deps/lib/python3.7/site-packages/
/usr/local/lib/python3.7/site-packages/hacs_frontend-29.dist-info /config/deps/lib/python3.7/site-packages/

The hacs integration gets installed successfully.

Not sure if I have broken something or it's a breaking change by home-assistant

**Comment by ludeeus** [comment]
Can you rename that directory from `/config/deps` to `/config/deps_not_in_use` and try again?
If that solves it, delete the `/config/deps_not_in_use`

This will cause you issues with 90% of custom_components since they rely on external packages.

**Comment by grewhit25** [comment]
@ludeeus I carried out the steps above all is good after HA restart.

I have since also upgraded successfully to 0.20.1.
So please close when you are ready.

Thanks once again for all your hard work on this brilliant project.
