### ISSUE TITLE
HACS not detected

### ISSUE THREAD

**Issue by spinside** [hacs/integration#881]
I have installed HACS in my Homeassistant under custom_components:

```➜  /config ls custom_components/hacs
config_flow.py           const.py       hacsbase  helpers  __init__.py    __pycache__   sensor.py      setup.py  strings.json
configuration_schema.py  constrains.py  handler   http.py  manifest.json  repositories  services.yaml  store.py  ws_api_handlers.py```

When I open an incognito tab and go to the integrations page. HACS is not available.

What am I doing wrong?


I tried going to the following links, but they seem to be broken:
https://hacs.xyz/docs/faq
https://hacs.xyz/issues/

**Comment by ludeeus** [comment]
You do not have `.translations` there

**Comment by lassieee** [comment]
I had the exact same thing. The instruction say's you'll end up with a hacs dir after unzipping, but you actually end up with the files and dirs that should go into the hacs dir. If you then do 'mv * hacs' you'll end up moving everything EXCEPT files and dirs starting with a '.', like .translations ;-)

**Comment by spinside** [comment]
Thank you for the comments! I did have the .languages folder though. It is a hidden folder as it starts with a trailing dot so it did not show up using the `ls` command. I updated my HA and downloaded a newer version of HACS and that fixed the problem!
