### ISSUE TITLE
Hacs plugin install routine configures Lovelace incorrectly

### ISSUE THREAD

**Issue by crandy2** [hacs/integration#885]
## Version of HACS
0.19.0

## Describe the bug
When installing plugins ( I did button-card and button-entity row) HACS puts the folders and files in /config/www/community.  Then when you tell it to update Lovelace it sets the URL to /community-plugin/
Therefore none of the custom cards can be found when trying to use them in a manual card.
As a workaround I created a folder named community-plugin and copied the files there and it started working.

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
That is just wrong, please have a look here https://hacs.xyz/docs/categories/plugins#custom-view-community_plugin

**Comment by crandy2** [comment]
> That is just wrong, please have a look here https://hacs.xyz/docs/categories/plugins#custom-view-community_plugin

I read the link, but the behavior I observed was different. Note that I didn't manually update Lovelace, I chose to have HACS update it. After installation, I was unable to use the plugin (said it couldn't find it). Only when I copied the plugin files to the locations listed above did it start working.

**Comment by ludeeus** [comment]
The first time you add a new resource you need to clear your HA browser cache.

**Comment by crandy2** [comment]
> The first time you add a new resource you need to clear your HA browser cache.

Yeah I tested this and your right. This issue can be closed as far as I'm concerned.

It would have saved me (and noobs like me) a lot of time it that were in the documentation somewhere.
