### ISSUE TITLE
HACS and other languages does not work

### ISSUE THREAD

**Issue by povlhp** [hacs/integration#888]
Just installed HACS on my new system (docker based).
All text strings where missing from "Add integration" and all the way through.

Personally I fixed it for me adding a symlink from danish to the english
da.json -> en.json

Code should have fallback to english in case it can not find users language.

**Comment by ludeeus** [comment]
AFAIK English is fallback, for custom_components you need to clear the cache of that page.
If you remove that link, restart HA and clear your cache it should display with `en`.
This is all handled by Home Assistant, there is not much I can do here.
