### ISSUE TITLE
Configuration option 'theme' is deprecated

### ISSUE THREAD

**Issue by skrenes** [hacs/integration#889]
## Version of HACS
0.20.1

## Describe the bug
Upgraded to latest version and keep getting this error with no obvious way of changing the setting.

```text
Log Details (WARNING)
Configuration option 'theme' is deprecated, HACS will know if you use it, this option will be removed in a future release.
```

**Comment by royto** [comment]
Before this version, theme was optional and have to be activated in your configuration
For example, I added 
themes: true 

Now this option is deprecated. You just have to remove it your configuration

**Comment by ludeeus** [comment]
For YAML that is simple, but if you configured in the UI, you would need to remove the integration, then add it again without those options.
I'll release a patch later today that hides that warning if the setup is done with UI.

**Comment by paularmstrong** [comment]
Is there any information on why themes was deprecated? I think the issue is that it just says "deprecated", but there's no reasoning, no suggestion on what to use instead, nor any path forward.
