### ISSUE TITLE
Dependency conflict with Home Assistant 0.103.2

### ISSUE THREAD

**Issue by dannyk81** [hacs/integration#899]
## Version of HACS

0.20.3

## Describe the bug

Upgrading HACS from 0.19.0 to 0.20.3 fails due to dependency conflict with aiohttp=3.6.2 (homeassistant requires aiohttp=3.6.1), there were also other conflicts but they all seem to be related to aiohttp.

Since HACS needs to "live" in the same environment as Home Assistant, it seems that we need to establish some parity in the requirements, otherwise it creates a mess when trying to upgrade HACS with incompatible requirements.

## log

```text
ERROR: homeassistant 0.103.2 has requirement aiohttp==3.6.1, but you'll have aiohttp 3.6.2 which is incompatible.

```

**Comment by ludeeus** [comment]
aiohttp is a default dependency in Home Assistant, so it can be removed from HACS.

**Comment by dannyk81** [comment]
@ludeeus indeed :+1: removed aiohttp=3.6.2 from the build and seems OK now.

---

This should probably go in a separate issue, but current installation method of HACS makes it tricky when HASS runs in a container, basically I need to cook a container image with the updated dependencies every time HACS is upgraded.

Any ideas here?

**Comment by ludeeus** [comment]
Remove the deps dir from your /config dir

**Comment by ludeeus** [comment]
`aiohttp` is not a requirement of HACS...
https://github.com/hacs/integration/blob/master/custom_components/hacs/manifest.json#L16-L23

**Comment by dannyk81** [comment]
@ludeeus true, I mistakenly identified aiohttp as a requirement. 

but the general comment about dependencies is still true (when running HASS in a container) for example in order to have HACS work in a HASS container, I need to build the following custom image:

```
FROM homeassistant/home-assistant:0.103.2
RUN pip3 install aiofiles==0.4.0 aiogithubapi==0.4.3 integrationhelper==0.2.2 backoff==1.10.0 pytest-cov==2.8.1 pytest==5.3.2 semantic_version==2.8.4 hacs_frontend>=20191226110059
```

otherwise, HACS tries to install these requirements during the setup phase and fails, since it can't update the container file system (and would be problematic since it won't persist).

**Comment by ludeeus** [comment]
It should try (and manage) to install during startup, that is how it's used for every user.

I run this on Hassio myself (also docker), and never have issues with installation/upgrade of custom components.

**Comment by xHirscHx** [comment]
Just update hacs and rebooted, wont load and i get this.
Is this the issue your talking about or new one.
was running fine before updating. 

Invalid config
The following components and platforms could not be set up:

hacs
Please check your config.

**Comment by ludeeus** [comment]
@xHirscHx Open a separate issue, fill out the template (with debug logs)

**Comment by dannyk81** [comment]
> It should try (and manage) to install during startup, that is how it's used for every user.
> 
> I run this on Hassio myself (also docker), and never have issues with installation/upgrade of custom components.

thanks @ludeeus, in my case this issue seem to be related to permissions, since I'm running the HASS container with non-root UID/GID (you know, for security :smile:) the user only has write permissions to `/config` and this happens:
```
Dec 27 12:18:40 adl01 home-assistant[18653]: 2019-12-27 17:18:40 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package integrationhelper: ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/site-packages/integrationhelper-0.2.2.dist-info'
Dec 27 12:18:40 adl01 home-assistant[18653]: Consider using the `--user` option or check the permissions.
```

this seems to be related to this https://community.home-assistant.io/t/installing-ha-in-docker-on-ubuntu-as-non-root-user/48424/24 and looks like getting things to work with a non-root user is a bit tricky... will close this, as it doesn't seem to be related to HACS but a more general issue for any of us running HASS with non-root user.

**Comment by GMFalka** [comment]
> > It should try (and manage) to install during startup, that is how it's used for every user.
> > I run this on Hassio myself (also docker), and never have issues with installation/upgrade of custom components.
> 
> thanks @ludeeus, in my case this issue seem to be related to permissions, since I'm running the HASS container with non-root UID/GID (you know, for security 😄) the user only has write permissions to `/config` and this happens:
> 
> ```
> Dec 27 12:18:40 adl01 home-assistant[18653]: 2019-12-27 17:18:40 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package integrationhelper: ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/site-packages/integrationhelper-0.2.2.dist-info'
> Dec 27 12:18:40 adl01 home-assistant[18653]: Consider using the `--user` option or check the permissions.
> ```
> 
> this seems to be related to this https://community.home-assistant.io/t/installing-ha-in-docker-on-ubuntu-as-non-root-user/48424/24 and looks like getting things to work with a non-root user is a bit tricky... will close this, as it doesn't seem to be related to HACS but a more general issue for any of us running HASS with non-root user.

Hi!
Have you managed to fix the permission issue (with docker)?
