### ISSUE TITLE
Problems with installation of meross_cloud integration

### ISSUE THREAD

**Issue by mfabiani53** [hacs/integration#921]
## Version of HACS
0.20.7

## Describe the bug
Trying to update the integration i always get 'download not complete' error, so cannot upgrade it.
If uninstalling it and trying to reinstall i cannot install as the page refresh and still get the _install_ button.

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
Please read the issue guidelines and try again.
