### ISSUE TITLE
Auto download all data

### ISSUE THREAD

**Issue by Biancanero** [hacs/integration#923]
**Is your feature request related to a problem? Please describe.**
Going through all integrations, plugins etc i takes some time loading all text and images. And when wanting to go through all of them quickly that gets a bit slow. 

**Describe the solution you'd like**
A way to cache all data, so it goes up and downloads everything and caches it client side so the browsing is superfast. 

**Describe alternatives you've considered**
None

**Additional context**

**Comment by ludeeus** [comment]
This will not be possible, the API is limited to 5000 calls/h.
To get all the needed information needed it will go over that limit.
