### ISSUE TITLE
Specify files for HACS to download

### ISSUE THREAD

**Issue by benct** [hacs/integration#924]
**Is your feature request related to a problem? Please describe.**
I have an image or two in a custom lovelace card plugin which I need HACS to include when installing the plugin on peoples system. However, I do not use releases or a `dist` directory, nor do I want to have everything in a `dist` folder for a simple JS script.

**Describe the solution you'd like**
For example, in hacs.json, I could specify a list of additional files/paths for HACS to include.
```
files: [
  "some-other-file.js",
  "images/some-image.png"
],
```

**Describe alternatives you've considered**
Git releases and dist directory.

**Additional context**
None.

**Comment by ludeeus** [comment]
As you mentioned there are 2(3 really) ways of doing this, I will not add another one.

One that you did not mention, is that you can bundle all your js files into a single file (like how the [boilerplate-card](https://github.com/custom-cards/boilerplate-card) is structured.) and for images, those can be encoded and included as base64.

**Comment by benct** [comment]
I don't see the problem with adding more flexibility to HACS (for developers). But fair enough, I guess I can make it work using base64 encoded images.

**Comment by ludeeus** [comment]
The problem is in 2 parts.
1) I have to build it.
2) I have to maintain and support it forever.

And when there are methods that works now, I don't see the need to adding more.
"plugins" are already the most flexible category in HACS.

**Comment by benct** [comment]
I can totally understand that, and that you want to avoid additional "unnecessary" work :)

Looking closer at encoding the images though, I see that it would add a ridiculous amount of extra bytes (in my example, two 200kb images) to the javascript file, which I don't think is optimal in regards to loading or performance.

**Comment by benct** [comment]
I was (somehow) under the impression that all files/assets in git releases were included and downloaded when installing/updating a plugin? Just added releases to my lovelace card, but it is still just the .js file that is included when installing through HACS.. Is this correct?

**Comment by ludeeus** [comment]
currently yes

**Comment by ludeeus** [comment]
This is actually supported now, not sure when, but it works.
_NB: Might be just in master for now_
Verification: <https://github.com/hacs/integration/commit/08bf3f3dd49caeabdd0239a6a9858f63f1a058b0>
result: <https://github.com/hacs/integration/runs/447618341?check_suite_focus=true#step:12:33>
