### ISSUE TITLE
0.20.x: cannot reuse already awaited coroutine

### ISSUE THREAD

**Issue by bieniu** [hacs/integration#927]
## Version of HACS
0.20.x

## Describe the bug
HACS doesn't allow to install or update anything. Buttons Install/Update are grayed. All the time progress bar shows update data from GitHub and every 30 minutes I have error in log. This state persists for several days.

## Debug log
```text
2020-01-15 11:57:13 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/hacs/hacsbase/__init__.py", line 304, in recuring_tasks_installed
    await self.factory.execute()
  File "/home/homeassistant/.homeassistant/custom_components/hacs/hacsbase/task_factory.py", line 24, in execute
    await asyncio.gather(*self.tasks)
RuntimeError: cannot reuse already awaited coroutine
```

**Comment by ludeeus** [comment]
Restart Home Assistant

**Comment by bieniu** [comment]
I'll do that when I come back home.

**Comment by bieniu** [comment]
After HA restart everything is normal.

**Comment by bieniu** [comment]
After few days without restart issue returns.

**Comment by andriej** [comment]
Same error, 0.104.2, latest HACS. Restart helps but problem reappeares.

**Comment by Tadimsky** [comment]
Same issue for me:
![image](https://user-images.githubusercontent.com/1149244/72853263-bf799080-3c65-11ea-90af-3e07770f0dfc.png)

**Comment by drthanwho** [comment]
Exactly the same error for me too. 

It seems that it is happening consistently at exactly 30min intervals

**Comment by smcue** [comment]
Same issue here, random continuous loading preventing me from taking any actions. However, restarting HA or HassOS does not resolve the issue unfortunately.

**Comment by gadgetchnnel** [comment]
I've looked at the code, and my understanding is that the task factory is called on different schedules to run various sets of background tasks (getting data for installed repositories, getting data for all repositories, etc.).
As these use all use the same instance of the task factory, if two of the schedules happen to overlap (e.g. refreshing all repositories at the same time as installed repositories), it may end up trying to await one or more tasks which have already completed which would result in the "cannot reuse already awaited coroutine" error.

Would the solution in this case be to either have multiple task factory instances or to not allow the task factory to execute background tasks if they are already running?

**Comment by ludeeus** [comment]
That is correct @gadgetchnnel.

The taskfactory should have exception handling

**Comment by bimki** [comment]
I have the same issue :/
Are You working on some solution?

Home Assistant 0.104.2.
hacs 0.20.8

**Comment by bimki** [comment]
today again the same issue...

**Comment by estiens** [comment]
+1

**Comment by ludeeus** [comment]
Fixed in https://github.com/hacs/integration/releases/tag/0.20.9
