### ISSUE TITLE
problem upgrading alexa_media plugin

### ISSUE THREAD

**Issue by pilot1981** [hacs/integration#929]
## Version of HACS
0.20.8

## Describe the bug
I tried to update alexa_media plugin from 0.24.1 to 0.25.0, but HACS isn0t able to complete this process: I found file zip in alexa directory....

## Debug log
No error logs about HACS found; only this error on alexa related to problem of integration:
```
Platform error notify.alexa_media - Integration 'alexa_media' not found.
```

**Comment by ludeeus** [comment]
You need to report that to that integration, I can only controll HACS
