### ISSUE TITLE
Add developer option to specify branch as beta

### ISSUE THREAD

**Issue by alandtse** [hacs/integration#935]
**Is your feature request related to a problem? Please describe.**
No; other than laziness.

**Describe the solution you'd like**
Option in hacs.json to specify a beta branch such as `dev` and have it appear as the top entry if `Show Beta` is enabled. This would allow devs to have a beta branch for those using a two stage model like HA uses (next vs master).

**Describe alternatives you've considered**
Use of the prerelease flag for releases is an alternative that is already supported but even rolling a release seems like more of a process than I'd like. Also, not all devs use a releases model which is already supported by HACS.  Of course, I can live with the status quo if it's your preference. ;)

**Additional context**

**Comment by ludeeus** [comment]
You can already do this ;)
HACS will show the default branch, if you have a separate dev branch, that should really be the default branch (for several reasons)

**Comment by alandtse** [comment]
Oops, you're right. I forgot you had me switch my dev to default. Perhaps the behavior should be if someone turns on Show Beta it should push the default branch to the top?

**Comment by alandtse** [comment]
FYI, doesn't look like you can download the branch under certain conditions. Right now I'm not on the latest release v2.5.2 but on the previous v2.5.1. Wanted to go directly to the beta branch and got the following error.

```
2020-01-20 13:55:49 INFO (MainThread) [hacs.repository.integration.custom-components.alexa_media_player] ref: dev  ---  tag: v2.5.2
2020-01-20 13:55:49 ERROR (MainThread) [hacs.repository.integration.custom-components.alexa_media_player] Download was not complete.
```

Let me know if I should open a new issue.

**Comment by ludeeus** [comment]
Yeah, do that.
When default branch is selected it should ignore release assets
