### ISSUE TITLE
Unable to update HACS

### ISSUE THREAD

**Issue by schildgenb** [hacs/integration#943]
## Version of HACS
20.4

## Describe the bug
When trying to update to newer versions I get the error message permissions denied: misc.py
![Screenshot_20200125-200226](https://user-images.githubusercontent.com/31838470/73129614-cd088080-3fad-11ea-8540-a5f0751ef744.png)
Any ideas on what would cause this? 
## Debug log

```text
Log Details (ERROR)
Sat Jan 25 2020 20:41:35 GMT-0600 (Central Standard Time)
Download was not complete.

Log Details (ERROR)
Sat Jan 25 2020 20:41:02 GMT-0600 (Central Standard Time)
http://192.168.1.38:8123/hacs_frontend/20191228174812.js:1:1 Uncaught SyntaxError: Identifier 'config' has already been declared

```

**Comment by ludeeus** [comment]
the user running HA needs FULL access/permissions to the `hacs` dir.
