### ISSUE TITLE
HACS Integration Not Showing on HA 103.5

### ISSUE THREAD

**Issue by jcqrs** [hacs/integration#946]
-->

## Version of HACS

Not sure. Whatever version was out the week of Jan. 20, 2020.

## Describe the bug
HACS integration doesn't show up after following install instructions to the letter; and after multiple restarts of Home Assistant.

## Debug log
##per the HA log:
_You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant._
#####
The problem is, I can't disable something if I can't ENABLE it in the first place.

##OTHER INFO THAT MIGHT BE USEFUL
Running HA ver. 103.5 hosted on Rasberry Pi4 - (Raspbian OS)
```

**Comment by TurtleHunter** [comment]
I've been dealing with this for a couple days. You know what finally fixed it for me?
I renamed the folder from `HACS `to `hacs`. That's it.

I had saved the files in a folder on my desktop called HACS, and then moved all of those with FileZilla to the custom_configs folder. Other things I've seen are to make sure the .translations folder is there by going to the `hacs `directory and typing `ls -la`

**Comment by jcqrs** [comment]
> I've been dealing with this for a couple days. You know what finally fixed it for me?
> I renamed the folder from `HACS `to `hacs`. That's it.
> 
> I had saved the files in a folder on my desktop called HACS, and then moved all of those with FileZilla to the custom_configs folder. Other things I've seen are to make sure the .translations folder is there by going to the `hacs `directory and typing `ls -la`

Lol, it’s the little things, I guess. Well, I will rename as you suggest. Thanks very much!

For now, I would consider this issue resolved, unless there are other ideas I can explore. Not fussing around with it anymore til tomorrow.
