### ISSUE TITLE
'INSTALLED' bar keeps cycling on top of screen

### ISSUE THREAD

**Issue by k-rock** [hacs/integration#947]
HACS VERSION:
Integration version: | 0.20.0
-- | --
Frontend version: | 20191224134044
Repositories: | 395
Home Assistant 0.104.3
<img width="1126" alt="Screen Shot 2020-01-28 at 3 49 51 PM" src="https://user-images.githubusercontent.com/15674791/73304233-de3bd200-41e5-11ea-870b-060b154362bd.png">

HACS is installed w/ several integrations installed… however, I cannot view which items are installed in the '‘INSTALLED’ heading in my home assistant web interface. It keeps showing a horizontal bar (for weeks). Any insight how to fix would be appreciated. Thanks!!

**Comment by thomasklein** [comment]
In my case it's after the initial setup, so I can"t actually install any components.

```
HACS VERSION:
Integration version: | 0.20.8
-- | --
Frontend version: | 20200104192235
Home Assistant 0.104.3
```

**Comment by ludeeus** [comment]
Fixed in https://github.com/hacs/integration/releases/tag/0.20.9
