### ISSUE TITLE
Community support section - Why not help each other?

### ISSUE THREAD

**Issue by TheGreatBorg** [hacs/integration#952]
**Is your feature request related to a problem? Please describe.**
No - it's only a product of trying out components that doesn't seems to have any impact and then examples from the community would be nice to have with screenshots maybe. **Like a picture tells a thousand words.** 

**Describe the solution you'd like**
It should maybe be a feature that Github should have (the Wiki or insight part). But if not only contributes but actual users was able to identify and describe what they have done with a component then even more components could get out to the masses (it must be the main goal of contributors that more than them self will use the component) - the insights should show more than development contribution - it should show user popularity even. This could also be a part of Hacs telling that this many users is actually using the component     

**Describe alternatives you've considered**
Alternatives could also be liking to https://community.home-assistant.io/ or https://discordapp.com/channels/330944238910963714/672220541343760384

It could also adding a working example that can be tested to see if things is actually working.

**Additional context**

By the way: I love the https://hacs.xyz/ part of HACS and I only want to help others :-) (how can I contribute?) I could be the dumbest of the pact but not all will be on the same level of conception in this HA reality and how will we get even more into the magic of DIY and making your home automated...

**Comment by ludeeus** [comment]
This is not something for HACS to "solve".
This will have to be something for each developer to add in their repo (like the README).

If I where to create something new for it, that would not be fair to the user or the developer that get another place to monitor.
