### ISSUE TITLE
problem upgrading to ShellyForHass using HACS

### ISSUE THREAD

**Issue by pilot1981** [hacs/integration#953]
## Version of HACS
HACS 0.20.9
HASSIO 0.104.3

## Describe the bug
It'sn't possibile complete upgrade to ShellyForHass 0.1.6, please se attached image
<img width="1007" alt="Schermata 2020-02-05 alle 11 50 36" src="https://user-images.githubusercontent.com/46350465/73836410-7998fc80-480f-11ea-80fb-669042264626.png">

If I click on the restart button, I receive 2 messages to confirm restart, but it don't restart/message don't desappear, I also trie to redo upgrade of plugin or reboot of HASSIO...

## Debug log
I enabled debug log but I don't message in log file...

I also opened an issue on repository of ShellyForHass plugin:
https://github.com/StyraHem/ShellyForHASS/issues/174

**Comment by ludeeus** [comment]
If it does not restart you have an issue with your configuration

**Comment by pilot1981** [comment]
configuration.yaml or configuration of HACS?

**Comment by ludeeus** [comment]
The first one.
The service to restart HA does not execute if there is a config issue

**Comment by pilot1981** [comment]
ok, solved.

thanks!
