### ISSUE TITLE
hacs.jon doesn't enforce minimum version of HA

### ISSUE THREAD

**Issue by chemelli74** [hacs/integration#956]
## Version of HACS

0.20.9

## Describe the bug
Even if ShellyForHASS implemented "hacs.json" with minimum version of HA, HACS allow installation on older version.

## Debug log

More than debug log, a pointer to the config file:

[https://github.com/StyraHem/ShellyForHASS/blob/master/hacs.json](url)

Please see also #858

**Comment by ludeeus** [comment]
Was fixed in 0.21
