### ISSUE TITLE
v0.21.1 new install not showing in Config-->Integrations

### ISSUE THREAD

**Issue by kkellner** [hacs/integration#958]
Installed v0.21.1, restarted HA, but nothing shows in Configuration-->Integrations.

I tried uninstalling, and re-installing but still nothing.

**Comment by ludeeus** [comment]
1. Missing `.translations` directory
2. Browser cache

**Comment by kkellner** [comment]
Not sure what you are saying above.  Is there something I need to do on my end?    

I tried a clean browser cache and Chrome Incognito mode to see if its a browser cache issue -- still nothing.   

As for the `.translations` directory, is that something I should have?   Below is my `config` directory.


![image](https://user-images.githubusercontent.com/9540241/74177027-1f74ae80-4bf6-11ea-8879-ad1f8c874343.png)

**Comment by ludeeus** [comment]
The content of your blueiris directory is not relevant here.
There needs to be a .translations directory _inside_ hacs directory.

**Comment by kkellner** [comment]
Yep, I have one of those:


![image](https://user-images.githubusercontent.com/9540241/74177835-bdb54400-4bf7-11ea-910d-e1da4b06c12d.png)

**Comment by ludeeus** [comment]
Then I'm out of ideas.
- Missing .translations directory
- Browser cache
is the only things I have seen in the past.

**Comment by postlund** [comment]
I have gotten two reports about missing .translations directories after upgrading my custom component for the Apple TV, despite me not making any updates to it. I suspect something is up.

https://github.com/postlund/pyatv/issues/209

**Comment by ludeeus** [comment]
That for is not missing, see screenshot

**Comment by postlund** [comment]
It's not missing for HACS but for the integration that it downloads. So the add dialog and config flow becomes empty.

**Comment by ludeeus** [comment]
Open a separate issue and provide debug logs of the installation.

**Comment by vikdb** [comment]
I have a similar issue, i can see the integration but it keeps loading when i click it..

**Comment by kkellner** [comment]
@vikdb Your issue sounds different then this issue.   This issue is that there is **no** blue iris item found in the integrations page.   I have dark theme so I thought maybe it's there but I can't see it, but I went back to default theme and still nothing shows.

**Comment by ludeeus** [comment]
Blue Iris??
Oh... I thought this was no HACS...
You should have stated that..
This is the same as @postlund wrote.
I have the fix made, but needs more manual testing before I can release it.

**Comment by kkellner** [comment]
My fault, this issue was opened on the incorrect repo.   This is a `ha-blueiris` integration issue.

The issue is tracked here: https://github.com/elad-bar/ha-blueiris/issues/25

**Comment by ludeeus** [comment]
No, it is a HACS issue, currently it does not respect subdirectories

**Comment by ludeeus** [comment]
Fixed in https://github.com/hacs/integration/releases/tag/0.21.2
