### ISSUE TITLE
Spelling in error message

### ISSUE THREAD

**Issue by Woodcat64** [hacs/integration#961]
Error message while upgrading Simple Thermostat
-->

## Version of HACS

Integration version: | 0.21.3
Frontend version: | 20200209160602

## Describe the bug

Incorrect spelling
"An error ocoured while prosessing"
Could not use repository with ID 158654878

Should say "An error occurred while processing"

```

**Comment by bazorante14** [comment]
O mesmo aqui.

An error ocoured while prosessing
Could not use repository with ID 146194325

Frontend version: 20200209160602
Installed: 0.21.3

**Comment by gabriel600r** [comment]
Same error when trying to download a plugin

Frontend version: 20200209160602
Installed: 0.21.3

Download was not complete [Got status code 404 when trying to download https://raw.githubusercontent.com/custom-cards/spotify-card/v1.11/.circleci]
