### ISSUE TITLE
It says I need to upgrade to 0.16 first but it is not available in dropdown

### ISSUE THREAD

**Issue by fondberg** [hacs/integration#964]
## Version of HACS
0.14.2

-

## Describe the bug
HACS says 
```
DO NOT UPGRADE TO THE LATEST VERSION!
First upgrade to version 0.16.3, then upgrade to the latest version.
````
but it is not available in dropdown
## Debug log

<details>
  <summary>Logs</summary>
```text
Paste your logs here.
```
</details>

**Comment by ludeeus** [comment]
`Number of releases to show` if your version supports that.
<https://hacs.xyz/docs/configuration/options>

Or get the zip from the release page of that release.

**Comment by fondberg** [comment]
ok, thanks!
