### ISSUE TITLE
Missing custom HACS icon in HA left side menu

### ISSUE THREAD

**Issue by PieBru** [hacs/integration#968]
## Version of HACS

HACS v0.21.4

## Describe the bug
While installing HACS I declared a custom MDI icon instead of the suggested alpha_c_...
I simply substituted the _C_ with a _H_ , but now no icon is shown and I am not able to figure out where it is defined to be changed with a text editor, or how can I change it in the GUI.
I'm on Arch Linux with HASSIO in docker (HACS newbie).
Here is a screenshot of the behavior in my installation:
![Screenshot from 2020-02-13 13-25-54](https://user-images.githubusercontent.com/6537434/74435683-4edd2280-4e65-11ea-9051-6467bcbaa562.png)

## Debug log

The log is too much beefy to report it here, what should I search for (grep)?

<details>
  <summary>Logs</summary>

```text
Paste your logs here.
```

</details>

**Comment by ludeeus** [comment]
The icon needs to be valid

**Comment by PieBru** [comment]
OK, can I correct my mistake by editing some file or I must install the whole HACS and custom repos only to change an icon?
Thanks,
Piero

P.S.: I though it was valid, as I changed only the icon letter. Probably I'm wrong, anyway reinstalling is a pain.

**Comment by ludeeus** [comment]
Goto configuration -> integrations -> hacs.
Delete it, and add it again.
It does not remove stuff you have downloaded

**Comment by PieBru** [comment]
Solved, all installed custom components are as before.
Sorry for being dumb, but as a HACS newbie I was afraid to loose all my last month tinkerings by trashing HACS.
Thank you much, @ludeeus 
Piero
