### ISSUE TITLE
API limit?

### ISSUE THREAD

**Issue by jcqrs** [hacs/integration#973]
-->

## Version of HACS
20.7

## Describe the bug
api limit?

## Debug log-
“Sun Feb 16 2020 21:10:28 GMT-0600 (CST)
Validation for hacs/integration failed with GitHub returned 401 for https://api.github.com/rate_limit.”

<details>
  <summary>Logs</summary>

```text 
_Sun Feb 16 2020 21:10:28 GMT-0600 (CST)

Validation for hacs/integration failed with GitHub returned 401 for https://api.github.com/rate_limit._
```

</details>

I am not using the latest version of hacs, but of late my custom cards are working. i am posting this out of concern, will this “api limit” mean i need to generate a new token? What does this mean?

**Comment by ludeeus** [comment]
You should really upgrade, the latest versions does not use as many API calls.

When you get that message, just wait 1h for it to reset.
