### ISSUE TITLE
After install Beta 0.22.0b1 HACS reverts to 'Hide Beta'

### ISSUE THREAD

**Issue by VDRainer** [hacs/integration#982]
## Version of HACS
0.22.0b1

## Describe the bug
HACS reverts to 'Hide Beta' and then shows the last stable Release as update.
![20200224_10:20:55_001](https://user-images.githubusercontent.com/26381449/75140534-6763fd00-56ef-11ea-9c49-ba7c45b1acee.png)
Checking 'Show Beta' once again fixes this.

## Debug log

<details>
  <summary>Logs</summary>

```text
Paste your logs here.
```

</details>

**Comment by DavidFW1960** [comment]
Yeah and if you set beta again, the sensor is correct again but on next restart it reverts again.

**Comment by ludeeus** [comment]
Fix in b2 https://github.com/hacs/integration/releases/tag/0.22.0b2
