### ISSUE TITLE
[Feature request] Browser cache invalidation for plugins

### ISSUE THREAD

**Issue by bokub** [hacs/integration#983]
**Is your feature request related to a problem? Please describe.**
Browser cache systems can be a real pain when updating plugins

*Here is a small scenario:*
- I update a Lovelace card from version 1.1 to version 1.2 using HACS. The download works well
- This card now accept interesting parameters, so I update my card configuration to try them
- The card throws an error saying the parameters are invalid...
- Just in case, I clear my browser's cache, and here we go, the card is working !
- I open my android app, and here is the error again...

**Describe the solution you'd like**
When adding the plugin to the Lovelace resources, add the version in a query parameter

So,instead of adding `url: /community_plugin/rgb-light-card/card.js` to the resources, add `url: /community_plugin/rgb-light-card/card.js?v=1.5.0`

When the card is updated through HACS, invalidate the browser cache by updating the `v` query parameter, so every client will download the file again. In my example, replace `?v=1.5.0` with `?v=1.5.1`.

**Describe alternatives you've considered**
:man_shrugging: 

**Additional context**
- [Here](https://github.com/bokub/rgb-light-card/issues/18) is an issue from a real card user

- Here is a screenshot of Firefox using cached files:
![image](https://user-images.githubusercontent.com/17952318/75156998-8d02fd80-5713-11ea-8f6b-645b6c210b0c.png)

**Comment by ludeeus** [comment]
This is bug.
If it's in HACS or the client I'm not sure.
HACS should serve files with headers that tells the client to never cache.

**Comment by bokub** [comment]
Oh, I didn't realize the HACS headers...

It's true that I have the following headers:

```
HTTP/1.1 200 OK
Content-Type: application/javascript
Content-Encoding: gzip
Last-Modified: Mon, 24 Feb 2020 13:41:21 GMT
Content-Length: 2302
Accept-Ranges: bytes
Date: Mon, 24 Feb 2020 15:25:26 GMT
Cache-Control: max-age=0, must-revalidate
Server: Python/3.8 aiohttp/3.6.1
```

**Comment by ludeeus** [comment]
Those should be enough, I'll do some testing when I get home

**Comment by ludeeus** [comment]
The headers does what it should.
But there is a serviceworker, not sure if it's HA or the browser that causes some issues.

**Comment by bokub** [comment]
It looks like the service worker is from [this library](https://github.com/GoogleChrome/workbox), which doesn't respect the headers...

![image](https://user-images.githubusercontent.com/17952318/75173835-ca758400-572f-11ea-8ea1-cee833289318.png)

**Comment by bokub** [comment]
Don't you think my solution would be a good way to:
- Use the cache system for faster load times (if you remove the cache headers)
- Invalidate cache when updating a plugin

**Comment by ludeeus** [comment]
I tested it, it will not help.
It will still require you to refresh (F5) twice (just how it is now)

**Comment by ludeeus** [comment]
and it will not work as intended for folks who modifies the source locally, or for imgfiles that folks use (camera snapshots)

**Comment by ludeeus** [comment]
I can "fix" it, by busting the workbox cache, but that is ugly.
I do not want to fix this any more than what is already done in regards to this.
Double refresh works as-is.
