### ISSUE TITLE
Highlight unused plugins

### ISSUE THREAD

**Issue by kloggy** [hacs/integration#984]
# Is your feature request related to a problem? 
Is there an overhead with having plugins installed and included in the Lovelace resources? If not (or the overhead is insignificant) then please close this feature request and accept my apologies for opening it ;-)

If there is an overhead it would be nice if HACS could highlight any that aren't currently being used. That way we could know that we can uninstall them. I for one install a lot of plugins to try them out and then lose track of if I decide to keep using them.

# Describe the solution you'd like
I *imagine* this could be achieved by searching the config for the plugin name? If this is in itself too much of an overhead for HACS to check automatically, maybe it could be an option to check manually?

**Comment by kloggy** [comment]
Edited original but not sure if that gets recognised by *hacs-bot* so repeating it here.

---------

# Is your feature request related to a problem? 
Is there an overhead with having plugins installed and included in the Lovelace resources? If not (or the overhead is insignificant) then please close this feature request and accept my apologies for opening it ;-)

If there is an overhead it would be nice if HACS could highlight any that aren't currently being used. That way we could know that we can uninstall them. I for one install a lot of plugins to try them out and then lose track of if I decide to keep using them.

# Describe the solution you'd like
I *imagine* this could be achieved by searching the config for the plugin name? If this is in itself too much of an overhead for HACS to check automatically, maybe it could be an option to check manually?

**Comment by ludeeus** [comment]
It already does that if you use the UI to manage Lovelace, for YAML and all the different was that supports it is not feasible to add it for that mode.

**Comment by kloggy** [comment]
Ok, fair enough, thanks for responding.
(I don't use the UI)
