### ISSUE TITLE
non-direct operation of version 0.22 with xiaomi gateway and aqara wireless switches

### ISSUE THREAD

**Issue by runnerfanspb** [hacs/integration#988]
When you upgrade to version 0.22.0, the aqara wireless switches continue to work in conjunction with the xiaomi gateway. They do not give the click status. when rolling back to version 0.21.6, the operation of the switches is normalized.

**Comment by ludeeus** [comment]
And where is the logs?

**Comment by KuChar91** [comment]
Same issue here after upgrading to the latest version.

**Comment by to4ko** [comment]
same hare - i have 3 instances (2 on x86 and one RPI 3B+). HACS was updated on 1 x86 and on RPI. After that updates from Xiaomi sensors (connected via Xiaomi Gateways 2) not received on "updated" instances. Same time on any interaction with Zigbee devices i get Invalid key in log.

Debug were turned on for xiaomi_gw component. It was observed that MCAST messages got received 2-3 times on HA server restart. After that no any updates on sensors even after button pressed.

Once HACS downgraded to 0.21.6 everything comes back to nortmal.

**Comment by AlexxIT** [comment]
Logs from the console (does not fall into the logs HA):

```Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Python37-64\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Python37-64\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python37-64\Lib\site-packages\xiaomi_gateway\__init__.py", line 169, in _listen_to_msg
    data, (ip_add, _) = self._mcastsocket.recvfrom(self.SOCKET_BUFSIZE)
socket.timeout: timed out```

This line:
https://github.com/Danielhiversen/PyXiaomiGateway/blob/master/xiaomi_gateway/__init__.py#L169

**Comment by ludeeus** [comment]
Looks like slow networks/hosts can get in a timeout on the socket.
Remove L 144-146 in custom_components/hacs/__init__.py

```
    if not await hacs.hass.async_add_executor_job(internet_connectivity_check):
        hacs.logger.critical("No network connectivity")
        return False
```

**Comment by to4ko** [comment]
how come two servers on same network, connected via same 1gb Ethernet cable became "slow" and "fast". And one that are slow became fast once hacs downgraded?

**Comment by ludeeus** [comment]
Logs don't lie ;)
```
socket.timeout: timed out
```

**Comment by ludeeus** [comment]
https://github.com/hacs/integration/releases/tag/0.22.1

**Comment by jacekpaszkowski** [comment]
i can confirm that it helps. Works ok in HA 0.106.2 and HACS 0.22.1
