### ISSUE TITLE
The "Add to Lovelace" button won't appear if there are types that are not "module" in the resource list.

### ISSUE THREAD

**Issue by gadgetchnnel** [hacs/integration#993]
## Version of HACS
0.22.2

## Describe the bug
Many (possibly all, it has been all the ones I have checked) plugins are showing that they should be added to the resources with a type of "module", even though the repository shows that it should be added with a type of "js".
For example: https://github.com/gadgetchnnel/lovelace-home-feed-card/
has the following in the README.md file:

```
resources:
  - url: /local/custom-lovelace/home-feed-card/lovelace-home-feed-card.js?v=0.0.0
    type: js
```

but shows this in HACS

![Screenshot 2020-03-05 at 19 27 36](https://user-images.githubusercontent.com/2099542/76017971-69139900-5f17-11ea-8821-5f8aa7ab37dc.png)

## Debug log

<details>
  <summary>Logs</summary>

```text
2020-03-05 19:30:28 DEBUG (MainThread) [hacs.repository.plugin.gadgetchnnel.lovelace-home-feed-card] Getting repository information
2020-03-05 19:30:29 DEBUG (MainThread) [hacs.repository.plugin.gadgetchnnel.lovelace-home-feed-card] Running checks against 0.4.0b3
2020-03-05 19:30:30 DEBUG (MainThread) [hacs.template] 'states' is undefined
2020-03-05 19:30:36 INFO (MainThread) [hacs.factory] Task processing of 36 tasks completed in 27 seconds
2020-03-05 19:30:36 DEBUG (MainThread) [hacs.data] Saving data
2020-03-05 19:30:37 DEBUG (MainThread) [hacs] Recuring background task for installed repositories done
2020-03-05 19:30:37 DEBUG (MainThread) [hacs.data] Saving data
```

</details>

**Comment by ludeeus** [comment]
That is by design

**Comment by gadgetchnnel** [comment]
@ludeeus Would it cause issues if it is added as "module" if if was designed to be added as "js"? Incidentally, has the "add to Lovelace" option been removed from HACS as I couldn't see it when I was just trying out a new card?

**Comment by ludeeus** [comment]
No, it should not cause issues.
No it has not been removed, but not all cards can be used with it yet.

**Comment by Misiu** [comment]
> No it has not been removed, but not all cards can be used with it yet.
@ludeeus is this something the card author must add?

**Comment by ludeeus** [comment]
now yes, but I do not like it.
Do you have an example of a card that does not work with "type: module"?

**Comment by gadgetchnnel** [comment]
@ludeeus I think they were asking what needs to be added for the "Add to Lovelace" option to appear (uninstalling a plugin still seems to automatically remove it from the Lovelace config, but can't automatically add it to the config when installing it).

I answer to the your question, I haven't personally found any cards which have had any issues if I have changed them in the resources from "type: js" to "type: module"

**Comment by ludeeus** [comment]
From 107 the author will not need to do anything, HACS will assume `module`.
Pre 107, there needs to be `type: js` or `type: module` _somewhere_ in the README file.

**Comment by gadgetchnnel** [comment]
I uninstalled one of my own cards ([repo](https://github.com/gadgetchnnel/lovelace-home-feed-card)) which has "type: js" in the README and reinstalled it, but don't see the option to add it:

![Screenshot 2020-03-07 at 14 27 47](https://user-images.githubusercontent.com/2099542/76145270-143f6200-6080-11ea-9f96-59c8f4da971b.png)

**Comment by ludeeus** [comment]
Then you:
a) Still have it in your resources.
b) Are using YAML

**Comment by gadgetchnnel** [comment]
I am using storage mode and it is was definitely not in my resources, but I seem to have found the issue.
It appears that if I have any resources which have a type other than "module" (this include "js" but also "css" since resources can also include css stylesheets) the "Add to Lovelace" button won't appear in HACS. Removing all resources of types other than "module" (or changing them all to "module") makes the button appear. It seems that the other resource types are confusing HACS in some way.

(I can raise a separate issue regarding this if needed).

**Comment by ludeeus** [comment]
The initial issue was not an issue, but more a question.
So can probably let this take over.

**Comment by ludeeus** [comment]
https://github.com/hacs/integration/releases/tag/0.22.3
