### ISSUE TITLE
Impossible to update HACS ([Errno 13] Permission denied: 'http.py')

### ISSUE THREAD

**Issue by GianCann** [hacs/integration#994]
When i try to update HACS...

(On Home Assistant 0.104.3)

arch | armv7l
-- | --
dev | false
docker | false
hassio | false
os_name | Linux
python_version | 3.7.3
timezone | Europe/Rome
version | 0.104.3
virtualenv | true

![image](https://user-images.githubusercontent.com/45897944/76074940-6c9d3380-5f9c-11ea-9760-bd281728392f.png)

**Comment by ludeeus** [comment]
You need to fix your permissions.

**Comment by GianCann** [comment]
Ok, i fix the permission for folder /hacs (and subfolder) to user howner 'homeassistant'.
Now, no error when i try to update, but HACS still in this situation:
![image](https://user-images.githubusercontent.com/45897944/76077373-df101280-5fa0-11ea-8851-5a28000a2da7.png)

**Comment by ludeeus** [comment]
"this situation"?

**Comment by GianCann** [comment]
"Pending Upgrades..."

**Comment by ludeeus** [comment]
Make sure you have read the [issue guidelines](https://hacs.xyz/docs/issues) and that you filled out the **entire** template.

**Comment by GianCann** [comment]
1. Click to HACS (pending updgrades)
2. Select new version 0.22.2
3 Click to update
(at this point, the system seems to do somethings)
4. when the 'running circle' stop to run, no change is appened and HACS is still in 'Pending upgrades'

**Comment by ludeeus** [comment]
You are still missing the most important part...
_Debug logs_

**Comment by GianCann** [comment]
I enable log, and restart HACS.
Now, this is the error:

"Setup failed for hacs: Unable to import component"

**Comment by ludeeus** [comment]
How did you enable log?

**Comment by GianCann** [comment]
In configuration.yaml...

However I solved it: I deleted the hacs folder in custom_components and recreated it through the user 'homessistant' (instead of pi, with sudo). Then I copied hacs.zip inside and unzipped it ... everything is ok now

**Comment by GianCann** [comment]
thank you @ludeeus  for support ;)
