### ISSUE TITLE
Hacs not appearing in HA.

### ISSUE THREAD

**Issue by hav0ck** [hacs/integration#995]
I am running HA ver: 0.106.0
I am using HACs ver: 0.22.2

I downloaded hacs on my sserver, extracted the zip file to the /custom_components folder. This folder is located in the same place as configuration.yaml file. I have other customer components currently running. I also made sure that the .translations folder was present.

When I go to the Integrations page and attempt to add HACS it does not appear in the list. I have cleared the browser's cache and I've installed Firefox and tried that browser with no change.

There is nothing showing up in my logs, even after adding the recommended logging entry.

I then tried to manually add HACs by adding this to my configuration.yaml file:
```
hacs:
  token: !secret hacs_github_token #Necessary
  sidepanel_title: HACS #Optional
  sidepanel_icon: mdi:store #Optional
  options: #Optional
    experimental: true #Optional
  theme: true #Optional
```

When I refreshed HA after the manual add I get this in my log file:
```
Logger: homeassistant.loader
First occured: 2:11:54 PM (7 occurences)
Last logged: 2:26:27 PM

Error loading custom_components.hacs. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 391, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/hacs/__init__.py", line 9, in <module>
    from aiogithubapi import AIOGitHub
ModuleNotFoundError: No module named 'aiogithubapi'
```

**Comment by ludeeus** [comment]
Let me guess.
Docker with a custom user/group?

**Comment by hav0ck** [comment]
> Let me guess.
> Docker with a custom user/group?

Sorry I don't have a prize to award you. Yes I forgot to mention that I am running HA in docker on an Ubuntu server.

**Comment by ludeeus** [comment]
But are HA running as root (recommended) or did you make it use another user/group?

It looks like you have issues installing pypi packages, usually that is a premission/network issue

**Comment by hav0ck** [comment]
> But are HA running as root (recommended) or did you make it use another user/group?
The user that docker is running under is not root, but that user has full rights for the HA container.

**Comment by ludeeus** [comment]
Until you can make HA able to install requirements, you can not use HACS (or many other custom_components)

**Comment by jdm12989** [comment]
I had the same issue and making sure the HA was running as root in the container was the solution. I would suggest this should be added as a note in the installation instructions.

**Comment by ludeeus** [comment]
That is a requirement for HA in general after 0.107
