### ISSUE TITLE
Require AppDaemon restart for apps

### ISSUE THREAD

**Issue by chbndrhnns** [hacs/integration#999]
**Is your feature request related to a problem? Please describe.**
Some HACS apps run in AppDaemon. When they are updated, they sometimes require a restart of appdaemon. This requirement cannot(?) be indicated the same way a HA restart can be indicated.

**Describe the solution you'd like**
AppDaemon apps can change the UI so that a restart of AppDaemon can be triggered or at least indicated.

**Describe alternatives you've considered**

**Additional context**

**Comment by ludeeus** [comment]
Appdeamon should reload apps when they change/update.

**Comment by chbndrhnns** [comment]
Would this even if they introduce new requirements (like packages)? 
I am trying to remember where I had to actually restart appdaemon to make a package work. Let me try to come up with it, again.

**Comment by ludeeus** [comment]
It there is a requirement, there is nothing I can do from HACS about it, Home Assistant and therefore HACS is not aware of your AD installation.

**Comment by chbndrhnns** [comment]
Ok, thanks for the quick replies! I will close this issue for now.
